### ISSUE TITLE
Add support for multi-person conversations

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1]
Currently the logs in which each conversation is recorded contain the name of the speaker. These details could be used to allow the program to have a conversation with multiple people simultaneously in which each person can be replied to but the relevance of topics in the conversation still hold weight.

**Comment by The-Penultimate-Defenestrator** [comment]
This would be great. Is it possible somehow to make multiple chatterbot instances, and then periodically 'combine' their training into one database so that they all benefit from the others' experience?

**Comment by gunthercox** [comment]
Yes, one way that this would be possible would be to simply create a number of chatterbot instances and set the parameter so that they all use the same database.

**Comment by The-Penultimate-Defenestrator** [comment]
Great, thanks for the info.
