### ISSUE TITLE
Switching between different DB SQLite files

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/ChatterBot#1005]
How can we switch between 1 or more DB SQLite files based on the user input, so that CHATBOT replies specific to that module that user asked.

**Comment by kishore-devaraj** [comment]
You can create two instance of chatbot, each having different botname and a database name. Whenever the user enters the input you can switch between by calling the name of the bot.

**Comment by gunthercox** [comment]
@ayushecps This is definitely feasible to do with ChatterBot, however it isn't a feature that exists right now.

I think the only challenge you might face is regarding how to determine which database to switch to for a particular input. Do you have any ideas for how you might achieve this (or at least theoretically how yo would *like* it to work)?

**Comment by Issen007** [comment]
@ayushecps way do you want multiple databases in this case? 
Are you trying to feed the chatterbot from a BigData datalake environment? Or do you have multiple Knowledge databases you want to use?

**Comment by ayushecps** [comment]
@gunthercox The major problem I am facing is like how can we catch the user input and modify the input then display the output as per the modified input. Please help.

**Comment by vkosuri** [comment]
I think this what you are looking  http://chatterbot.readthedocs.io/en/stable/preprocessors.html

**Comment by gunthercox** [comment]
@ayushecps Another option you could try is to create your own logic adapter. Within it you could handle the users input and return the exact response you want. There is an example in the documentation http://chatterbot.readthedocs.io/en/latest/logic/create-a-logic-adapter.html#example-logic-adapter
