### ISSUE TITLE
I'm not sure what im doing :(

### ISSUE THREAD

**Issue by CruelAlpha** [gunthercox/ChatterBot#1007]
Hey Guys!
Sorry, however im not sure what im doing, i learnt about tensorflow and deep learning, and im quite interested in learning.
I'm having trouble starting the bot up in general, could someone show me how i can start up the bot?
Thanks!

**Comment by Issen007** [comment]
@CruelAlpha what do you want? 
Do you want to run it from a Python CLI or via a Web Interface?

**Comment by vkosuri** [comment]
@CruelAlpha Sure

>  i learnt about tensorflow and deep learning, and im quite interested in learning.

Let me clarify few things Chatterbot is independent of [Tensorflow ](https://www.tensorflow.org/) and [Deep Learning ](https://en.wikipedia.org/wiki/Deep_learning). 

> how i can start up the bot?

I will give a birdeye view of chatterbot,

1. Did you [installed ](http://chatterbot.readthedocs.io/en/stable/setup.html#installation) chaterbot? If not please do so.
2. Second major import thing is, understanding of [chartterbot-corpus](http://chatterbot.readthedocs.io/en/stable/corpus.html#chatterbot-corpus). In brief talks about [statements ](http://chatterbot.readthedocs.io/en/stable/conversations.html#statements) and [response ](http://chatterbot.readthedocs.io/en/stable/conversations.html#responses) are in either  [JSON or YAML](https://stackoverflow.com/a/1729545/358458)
3. [Train](http://chatterbot.readthedocs.io/en/stable/training.html) your bot.
4. Read some time on [logic-adapter](http://chatterbot.readthedocs.io/en/stable/logic/index.html#logic-adapters) and how they are working. In short they are process your input requests.
5. After that where you are getting [input ](http://chatterbot.readthedocs.io/en/stable/input/index.html) and [output ](http://chatterbot.readthedocs.io/en/stable/output/index.html) to chat with your bot. i.e. [Linux/Windows Terminal](http://chatterbot.readthedocs.io/en/stable/input/index.html#terminal-input-adapter), [Hipchat](http://chatterbot.readthedocs.io/en/stable/output/index.html#id1), [Gitter ](http://chatterbot.readthedocs.io/en/stable/output/index.html#gitter-output-adapter) or etc.
6. Take look at [storage adapters](http://chatterbot.readthedocs.io/en/stable/storage/index.html), how your are data will store.
7. **Optional** readings, [Filters ](http://chatterbot.readthedocs.io/en/stable/filters/index.html) and [Session management](http://chatterbot.readthedocs.io/en/stable/sessions.html).

After all these steps, Try to make use of [awesome examples](http://chatterbot.readthedocs.io/en/stable/examples.html).

Let us know if you need any further help, Happy chatting 👍
