### ISSUE TITLE
Question: Create a Django RestAPI

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#1008]
Hi,
Just want to check if anyone have try and successfully created a Django RestAPI that takes to a centralized chatterbot?
If yes, is it possible for you to share that knowledge?
If you have any other ideas, please feel free to comment. 

@gunthercox @vkosuri you guys maybe have ideas?

**Comment by Issen007** [comment]
If no one have done it I will continue my milestone project for this and I hope to have this done end of the year.

**Comment by vkosuri** [comment]
@issen007 I think this what your are looking https://stackoverflow.com/a/40904241/358458

And i am trying to implement same thing here https://github.com/vkosuri/django-apiai , If anything i achieved i will share with you.

**Comment by vkosuri** [comment]
Another thing i found here https://github.com/gunthercox/django-rest-requirements

**Comment by ellenawoo** [comment]
I am very keen to know how to implement chatterbot Django REST API as backend and communicate with a front end client in JSON as well.

**Comment by gunthercox** [comment]
@Issen007 The Django example included in this repo is API based and uses a single chat bot. Is there anything missing from this example that doesn't meet what you are looking for?

**Comment by Issen007** [comment]
@gunthercox maybe now, but what I'm looking for at the moment is to split the chatterbot.
So I got a Client Chatterbot where we do all the presentation and Q&A functions and the ChatterBot Server where we do all background job and give back the responds from the statement that the client have done.

So in that case I can then build a multiple client network that take to the same backend that is in this case a PostgreSQL database that has a lot of CPU/Memory and Flash Storage to work with.

**Comment by gunthercox** [comment]
@Issen007 Understood. I agree this would be useful and I have a similar need for one of my projects. I've been thinking about adding something like this for a while.
