### ISSUE TITLE
Discord Integration?

### ISSUE THREAD

**Issue by CruelAlpha** [gunthercox/ChatterBot#1009]
Is it possible to have [discord integration](https://discordapp.com/) added in as an example?
Just a suggestion!
Thanks

**Comment by vkosuri** [comment]
@CruelAlpha Yes, it is possible by looking this API https://discordapp.com/developers/docs/reference 

@gunthercox Master,Future update https://github.com/gunthercox/ChatterBot/issues/528

And suggestions: https://github.com/gunthercox/ChatterBot/pull/770#issuecomment-312465339
