### ISSUE TITLE
cassandra storage adapter

### ISSUE THREAD

**Issue by umaash** [gunthercox/ChatterBot#1013]
We would like to build a Cassandra storage adapter for  ChatterBot. We already went through the documentation on creating new adapter but couldn't figure out much. 
So, could anyone guide us on the building the  adapter.

**Comment by vkosuri** [comment]
@umaash Sure.

For your request, you need write up new storage adapter. 

1. Install python[ cassandra driver](https://github.com/datastax/python-driver) on your machine.
2. Extend [Cassandra Storage](https://docs.datastax.com/en/cassandra/2.1/cassandra/dml/manage_dml_intro_c.html) class with base class [StorageAdapter](http://chatterbot.readthedocs.io/en/stable/_modules/chatterbot/storage/storage_adapter.html#StorageAdapter)
3. Override StorageAdapter methods based on your requirement, if needed you could write your own definition to improve
    - generate_base_query - Create a base query for the storage adapter.
    - count - Return the number of entries in the database.
    - [find ](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/select_r.html)- Returns a object from the database if it exists
    - [remove ](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/delete_r.html)- Removes the statement that matches the input text.
    - filter - Returns a list of objects from the database.
    - [update ](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/update_r.html)- Modifies an entry in the database.
    - drop - Drop the database attached to a given adapter.

After you have implemented methods/defincation It look like something like below.

``` Python



from chatterbot.storage import StorageAdapter
from cassandra.cluster import Cluster

class CassandraAdapter(StorageAdapter):
    """
    """

    def __init__(self, **kwargs):
        super(CassandraAdapter, self).__init__(**kwargs)
        from pymongo import MongoClient
        from pymongo.errors import OperationFailure

        # Create cluster to connect a session
        session = Cluster().connect()

    def count(self):
        pass

    def find(self, statement_text):
        pass

    def filter(self, **kwargs):
        """
        Returns a list of statements in the database
        that match the parameters specified.
        """
        pass

    def update(self, statement):
        pass
    
    def create_conversation(self):
        """
        Create a new conversation.
        """
        pass

    def get_latest_response(self, conversation_id):
        """
        Returns the latest response in a conversation if it exists.
        Returns None if a matching conversation cannot be found.
        """
        pass

    def add_to_conversation(self, conversation_id, statement, response):
        """
        Add the statement and response to the conversation.
        """
        pass

    def get_random(self):
        """
        Returns a random statement from the database
        """
        pass

    def remove(self, statement_text):
        """
        Removes the statement that matches the input text.
        Removes any responses from statements if the response text matches the
        input text.
        """
        pass

    def get_response_statements(self):
        """
        Return only statements that are in response to another statement.
        A statement must exist which lists the closest matching statement in the
        in_response_to field. Otherwise, the logic adapter may find a closest
        matching statement that does not have a known response.
        """
        pass
    
    def drop(self):
        """
        Remove the database.
        """
        pass
```
