### ISSUE TITLE
Return google map in Chat window

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/ChatterBot#1015]
How can we get a google map of a location entered by user in chat window ?
Please help me with code I am a beginner.

Also I want to know is like how can we catch the user input and modify the input then display the output as per the modified input. Please help.

**Comment by vkosuri** [comment]
@ayushecps 

> How can we get a google map of a location entered by user in chat window ?

Google has it's own [REST API](https://developers.google.com/maps/documentation/geolocation/intro) to access google maps. 

I found google python repo https://github.com/googlemaps/google-maps-services-python, which will be useful and a example

``` Python
import googlemaps
from datetime import datetime

gmaps = googlemaps.Client(key='Add Your Key here')

# Geocoding an address
geocode_result = gmaps.geocode('1600 Amphitheatre Parkway, Mountain View, CA')

# Look up an address with reverse geocoding
reverse_geocode_result = gmaps.reverse_geocode((40.714224, -73.961452))

# Request directions via public transit
now = datetime.now()
directions_result = gmaps.directions("Sydney Town Hall",
                                     "Parramatta, NSW",
                                     mode="transit",
                                     departure_time=now)
``` 

> Also I want to know is like how can we catch the user input and modify the input then display the output as per the modified input. Please help.

Using pre processor http://chatterbot.readthedocs.io/en/stable/preprocessors.html and pre processor function http://chatterbot.readthedocs.io/en/stable/preprocessors.html#preprocessor-functions
