### ISSUE TITLE
Mathematical_evaluation adapter fails for words (to numbers) greater than unit digits

### ISSUE THREAD

**Issue by taiwotman** [gunthercox/ChatterBot#1016]
Using the chatterbot Mathematical_evaluation with say:

`Five - 6 
`

gives:

`(5-6) = -1`

But it fails to compute correctly:
`sixty-six - 6`
Or any word conversion to a number with a value greater than 10 or unit digit.

Hence words form of 31  to 39, 41 to 49, 51-59 etc all fail the test.

**Comment by gunthercox** [comment]
Is the hyphen throwing it off? I think `sixty six - 6` might work. I'll still mark this as a bug because either way this is a case that should be handled.

**Comment by taiwotman** [comment]
Two observations:
1. Absolutely, the hyphen is throwing it off.
2. Without the hyphen from `ninety one` upward does not seems to conform to the math rule.

**Comment by gunthercox** [comment]
I'm going to close this ticket off. I've reported this problem on the issue tracker for the mathparse library.
