### ISSUE TITLE
CMS or Portal

### ISSUE THREAD

**Issue by elkhawajah** [gunthercox/ChatterBot#1019]
Hi,

Is there a cms interface for this project to train the bot?

If not, does it have an api that support building a portal for that? 

Thanks!

**Comment by vkosuri** [comment]
@elkhawajah Did you mean Content management System https://en.wikipedia.org/wiki/Content_management_system

**Comment by elkhawajah** [comment]
I meant like wi.ai where u can interface to train chatbot on responses.
Define actions/intent.

So I can bring normal person and train the bot through this cms or whatever
it should be called.

Makes sense ?

**Comment by gunthercox** [comment]
@elkhawajah I have plans to start a separate project that might be close to what you are looking for. Nothing that fits that description currently exists (at least that I'm aware of). What kind of "normal people" are you looking to target? If they are developers then the new project (eventually) might be close to a CRM / Portal for the chat bot's dialog data.

**Comment by elkhawajah** [comment]
I plan to build one that close to wit.ai initially. Eventually we want any
person to use it, not only engineers/developers.

**Comment by sarva-anu** [comment]
I am also looking for the same like wit.ai , API.ai(dialogflow). we need the simple UI to train the Chatbot.

**Comment by taiwotman** [comment]
@gunthercox @elkhawajah @vkosuri,  I also would like to see something close to the API.ai(dialogflow). I hope @gunthercox's  new project on this would set sail early next year. I look forward to helping in any way possible and I hope others join in as well - we can make it the best chatbot for all users. Let's continue to encourage @gunthercox  and his team for the wonderful AI work they are doing.

I see there hasn't been a comment on my issue #1027 raised couple of days back. Thanks in advance for helping to check it out.

**Comment by gunthercox** [comment]
I'm going to close this off. In the future, this functionality may be available through [Dialog Data Studio](https://github.com/gunthercox/DialogDataStudio). (A new, not-yet-created project).
