### ISSUE TITLE
Is it possible to deploy this chatterbot in Skype channel.?

### ISSUE THREAD

**Issue by Cosmos19** [gunthercox/ChatterBot#1022]
Hello,

Currently am running chatterbot application through web interface. Now am interested to run this with Skype. 

I have checked Skype4Py library. its not working and also currently the development has stopped.

Thanks in advance.!

**Comment by gunthercox** [comment]
@Cosmos19 At this point Microsoft has made changes so that access to skype is available through the Microsoft Bot Framework https://dev.skype.com/bots

**Comment by Issen007** [comment]
@Cosmos19 if you start working on anything, I'm more then interesting to watch what you have completed. This could be really fun hobby project

**Comment by Cosmos19** [comment]
@gunthercox  Thanks for your reply. i will have a look
