### ISSUE TITLE
New page for use cases and Example demo.

### ISSUE THREAD

**Issue by phpmind** [gunthercox/ChatterBot#1023]
Hi Gunther, 
Is it possible to create a page for users to allow Demo URLs and a bit explanation how their bot works etc?  
This way other users can experience performance and get motivation and can follow that path. 
For us, some use cases and some implementation. 

Thanks

**Comment by gunthercox** [comment]
@phpmind Would something like this be close to what you are looking for?

https://github.com/gunthercox/ChatterBot/wiki/ChatterBot-Showcase

**Comment by phpmind** [comment]
Thanks, Gunther, 
I know this page but people can not post their working demo  URLs for other people to see and experience. 
This page is very useful.

**Comment by vkosuri** [comment]
@phpmind I think these items also be a part of show case

1. Heroku Deployment https://github.com/vkosuri/chatterbot-live-example
2. Flask Deployment https://github.com/chamkank/flask-chatterbot
3. Integration or IO Adapter
i. [Gitter](http://chatterbot.readthedocs.io/en/stable/input/index.html#gitter-input-adapter)
ii. [Hipchat](http://chatterbot.readthedocs.io/en/stable/input/index.html#id1)
iii. [Microsoft](http://chatterbot.readthedocs.io/en/stable/input/index.html#microsoft-bot-framework-input-adapter)
iv. [Mailgun](http://chatterbot.readthedocs.io/en/stable/input/index.html#mailgun-input-adapter)
4. chatterbot-voice https://github.com/gunthercox/chatterbot-voice
5. chatterbot weather https://github.com/gunthercox/chatterbot-weather

**Comment by phpmind** [comment]
Thanks, vkosuri. 
Do you know if any of these are using elastic search as storage engine?

**Comment by phpmind** [comment]
I just want to experience a production-grade heavy data-oriented chatbot with great performance. 
vkosuri - Can you guide me how to utilize this chatbot engine for other different languages. Tamil, Hindi, Spanish etc.

I want to allow local people to chat in their own language, not just English also on a particular topic like heath, local-regional disease etc.

**Comment by vkosuri** [comment]
> Do you know if any of these are using elastic search as storage engine?

I don't know much about elastic search

> vkosuri - Can you guide me how to utilize this chatbot engine for other different languages. Tamil, Hindi, Spanish etc.

Yes, chatterbot will able to do this, but you have train the bot in accurate way. If possible i will try to make any example ASAP

After this implementation of chatterbot news letter https://github.com/gunthercox/ChatterBot/issues/952 will provide more usecases/exposure

**Comment by phpmind** [comment]
Thanks, vkosuri.

Do you know any good large data source for training in hindi or tamil?

**Comment by vkosuri** [comment]
I think this information will help you

http://ml-india.org/datasets/
http://lipitk.sourceforge.net/hpl-datasets.htm
http://www.cfilt.iitb.ac.in/Downloads.html
http://tdil.mit.gov.in/
