### ISSUE TITLE
How do I change file location of Chatterbot_corpus data?

### ISSUE THREAD

**Issue by nanda248** [gunthercox/ChatterBot#1024]
Hi, I have developed my own UI for creating Q&A for chatterbot_corpus data. I can test chatterbot responses also. They are working fine.
Now when i create Q&A from my project, the YAML files will be stored in location "C:/Python27/Lib/site-packages/chatterbot_corpus/data/english/". For the simplicity of my project, I want to move it into my project folder so that I don't have to use absolute path, but using relative path instead. Can I do it?

**Comment by vkosuri** [comment]
@nanda248 Yes, you could, Read this [documentation ](http://chatterbot.readthedocs.io/en/stable/training.html#specifying-corpus-scope) will guide you how to configure.

```Python
chatterbot.train(
    "./data/greetings_corpus/custom.corpus.json",
    "./data/my_corpus/"
)
```
