### ISSUE TITLE
Mathematical_evaluation adapter division returning integer value instead of double.

### ISSUE THREAD

**Issue by taiwotman** [gunthercox/ChatterBot#1027]
The mathematical_evaluation adapter division returning integer value instead of double such that

` 4/6 = 0`

**Comment by vkosuri** [comment]
It's working fine for me, Did you tried any other division methods, and observed same response?

```
>>> str(mathparse.parse('4 / 6'))
'0.6666666666666666666666666667'
``

**Comment by taiwotman** [comment]
@vkosuri, It is not the same as what I get using:
        
     ```
    {
                'import_path': 'chatterbot.logic.MathematicalEvaluation',
                
         },
```
Here are the  outputs to the console( it is only the division operator  giving the wrong results):
while the bot is running with `python manage runserver 0.0.0.0:8000`

```

5/6
0 = 0

6 * 7

( 6 * 7 ) = 42

8/6
( 1 ) = 1

6 + 8
( 6 + 8 ) = 14

4/6
0 = 0

8%3
( 2 ) = 2

2 times 0.002
( 2 * 0.002 ) = 0.004

4 divided by 8
( 4 / 8 ) = 0

```

**Comment by gunthercox** [comment]
This should be fixed in the latest version. ChatterBot now uses the `mathparse` library which has better handling of numeric tokens.
