### ISSUE TITLE
Operation not permitted Issue

### ISSUE THREAD

**Issue by tisuchi** [gunthercox/ChatterBot#1028]
Hi, 

I am trying to integrate chatterbot with django. However, it shows me following error after implementing ```pip install django chatterbot``` on terminal. 

```
Operation not permitted: '/tmp/pip-ObDyQO-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

Any solution for that?

**Comment by tisuchi** [comment]
Guys, I found a solution for that. If you same issue, you may follow this-

To address my issue, I use-

```
pip install django chatterbot --ignore-installed six
```

**Comment by vkosuri** [comment]
@tisuchi glad, you figured out.
