### ISSUE TITLE
I can not import settings in python3.5

### ISSUE THREAD

**Issue by Tracy6465** [gunthercox/ChatterBot#1032]
I try the doc demo,but there is a problem that i can't import settings module

from settings import GITTER
ImportError: No module named 'settings'

**Comment by vkosuri** [comment]
It seems to me those are unused import, you could remove and try?

**Comment by gunthercox** [comment]
@Tracy6465 You need to create a file called `settings.py` in the same directory as the python file you are trying to run.

**Comment by mrrohitarora** [comment]
after doing the above it still gives the following error:
ImportError: cannot import name GITTER
