### ISSUE TITLE
How can you change the threshold for the Jaccard Similarity logic adapter?

### ISSUE THREAD

**Issue by rdt712** [gunthercox/ChatterBot#1034]
How can you change the threshold for the Jaccard Similarity logic adapter? Looking at the code, it seems it is hard coded at 0.50.

**Comment by vkosuri** [comment]
@rdt712 you could try like this, after the bot initialization

```Python
from chatterbot import jaccard_similarity

jaccard_similarity.SIMILARITY_THRESHOLD=0.6
```

**Comment by rdt712** [comment]
In Django I don't see how that would be possible?

**Comment by vkosuri** [comment]
Using low confidence adapter http://chatterbot.readthedocs.io/en/stable/logic/index.html#low-confidence-response-adapter

**Comment by rdt712** [comment]
@vkosuri I have that, but that doesn't affect the Jaccard Similarity Threshold. I'm looking at this: 
![image](https://user-images.githubusercontent.com/13369991/31888618-d618ae56-b7ca-11e7-8efa-6974538f11bf.png). It is the threshold that is in the comparison function itself. There is no way to directly set it in the Django settings.

**Comment by vkosuri** [comment]
@rdt712 Thanks, I think this is a possible bug, i will tag it as Bug.
