### ISSUE TITLE
Custom Script?

### ISSUE THREAD

**Issue by sharma-ji** [gunthercox/ChatterBot#1036]
Can we integrate custom scripts for specific replies to chatbot? For e.g. when the user say "Find hotels in NY" then the chatbot loads another python script to execute this task. 
If we don't have this option then how will the chatbot respond to the above query? Or specifically hw it will execute a particular task ??

**Comment by vkosuri** [comment]
Yes, this definately possible. Here is an example on weather API 

```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
import requests

# Uncomment the following lines to enable verbose logging
# import logging
# logging.basicConfig(level=logging.INFO)

# Create a new instance of a ChatBot
bot = ChatBot(
    'Action or Intent Response Example Bot',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'statement_comparison_function': 'chatterbot.comparisons.jaccard_similarity',
            'response_selection_method': 'chatterbot.response_selection.get_first_response'
        },
        {
            'import_path': 'chatterbot.logic.SpecificResponseAdapter',
            'input_text': 'Help me!',
            'output_text': 'Ok, here is a link: https://openweathermap.org/current'
        }
    ],
    trainer='chatterbot.trainers.ListTrainer'
)

# Train the chat bot with a few responses
bot.train([
    'Current weather in London',
    'http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1',
    'Have you read the documentation?',
    'No, I have not',
    'This should help get you started: http://chatterbot.rtfd.org/en/latest/quickstart.html'
])

# Get a response from bot
response = bot.get_response('current weather in London?')
# Handle JSON data, get all required data and print them
if 'http' in response.text:
    resp = requests.get(response.text)
    print(resp.json())
```

**Comment by rajasimon** [comment]
It will be good if we can override the `SpecificResponseAdapter` for our need. But we can also create your own adapter for this need...

    from __future__ import unicode_literals
    from chatterbot.logic import LogicAdapter


    class SpecificResponseAdapter(LogicAdapter):
        """
        Return a specific response to a specific input.
        """

        def __init__(self, **kwargs):
            super(SpecificResponseAdapter, self).__init__(**kwargs)
            self.input_text = kwargs.get('input_text')

        def can_process(self, statement):
            if statement == self.input_text:
                return True

            return False

        def process(self, statement):
            # Process the statement and return
            pass


and in the settings

        {
            'import_path': 'anonchat.logic.specific_response.SpecificResponseAdapter',
            'input_text': 'Help me!'
        },

Not tested the above code but I think it still works...
