### ISSUE TITLE
Question: The core working of Chatterbot

### ISSUE THREAD

**Issue by sharma-ji** [gunthercox/ChatterBot#1037]
I believe at the core the chatterbot works as AIML chat bot, with only difference being it uses yml and if it is so, then there should be a compiled brain file as well, because loading the English Corpous every time will be lengthy task. 

Also can anyone explain how it is different from AIML chat bot, and how it actually learns from past experiences and how NLTK is used here?

I shall be thankful to the community...

**Comment by sharma-ji** [comment]
Checkout my bot, it uses AIML and its not self learning or connected to Database but its pretty nice 
https://github.com/sharma-ji/tony_bot

**Comment by vkosuri** [comment]
Thanks @sharma-ji I found some of the difference between AIML and chatterbot are https://github.com/gunthercox/ChatterBot/issues/469#issuecomment-267481465
