### ISSUE TITLE
use existing conversation as dataset ?

### ISSUE THREAD

**Issue by guangrei** [gunthercox/ChatterBot#1038]
hi i have archived conversation/chat in file.txt like
me : ..
friend : ..
me : ..
me : ..
friend : ..
me : ..
friend : ..
friend : ..
me : ..
and so on..
can i use that as dataset ?
thanks

**Comment by nikhilv-quantela** [comment]
Yes, you can store this conversation in proper corpus format (**.JSON** or **.YML**) as you can see in _site-packages/chatterbot_corpus/data/_.
You can add your conversation in _site-packages/chatterbot_corpus/data/custom/_.
I prefer **.YML**, as it is more human readable, as compared to **.JSON**

**Comment by vkosuri** [comment]
Yes using existing export feature http://chatterbot.readthedocs.io/en/stable/corpus.html?highlight=export#exporting-your-chat-bot-s-database-as-a-training-corpus

**Comment by guangrei** [comment]
its possible to have multiple statement in one section ?
as i see in documentation :
Satement
Response
Satement
Response
Satement
Response
etc ...

and here what would i do :
Satement
Response
Statement
Statement
Response
statement
statement
statement
Response

**Comment by vkosuri** [comment]
@guangrei It won't possible with current training algorithm. But i didn't understand your usecase, if possible can with some examples with your usecase?

**Comment by Karamya** [comment]
for custom dataset, is it necessary to export our database as a training corpus. If not, can anyone recommend me how to train on a custom dataset. I have a .yml file in a folder. If I train based on the .yml file, it gives an error 

AttributeError: 'list' object has no attribute 'get'

**Comment by guangrei** [comment]
the case look like a multiple statement with one response e.g:
when statement match one of statement 1 or statement 2 or statement 3 then will get same response

**Comment by gunthercox** [comment]
@guangrei It currently isn't possible to have more than one statement as a response. I agree this might be useful, and I've had a number of requests for this functionality. I'll look into the possibility of adding this feature (https://github.com/gunthercox/chatterbot-corpus/issues/58).
