### ISSUE TITLE
Use Chatterbot as a reference

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#1039]
@gunthercox this is a direct question to you. 
I will be on main stage on a IBM Event in Europe and talk about my project working with AI together with one IBM Software called IBM Spectrum Protect.

My question to you, is it OK if I use Chatterbot as a reference in my presentation and do some print screens from the code to show on the main screen?

Thanks
Christian

**Comment by gunthercox** [comment]
Yes, that is perfectly acceptable.

Best of luck with your presentation 😄

**Comment by Issen007** [comment]
Thanks

**Comment by vkosuri** [comment]
@Issen007 All the best
