### ISSUE TITLE
Chatterbot has far fewer responses than statements

### ISSUE THREAD

**Issue by kokenjr** [gunthercox/ChatterBot#1040]
Looking through my database, I noticed that I have about ~16K statements, but only about 400 responses (and occurrences are all, for the most part, a value of 1). Is this normal? 

My understanding from reading about the [statement-response-relationship](http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-response-relationship) is that there should be a database record for each response to a statement. Unless it is the same response to the same statement in which case the existing record's `occurrence` should be updated. 

I've also noticed that my `conversations` table is empty. Please advise. Thanks.

**Comment by vkosuri** [comment]
> Looking through my database, I noticed that I have about ~16K statements, but only about 400 responses (and occurrences are all, for the most part, a value of 1). Is this normal?

@kokenjr It's not normal. I think you were correct each statement must have a response, is same response the occurrence count will increment, However the tests are covering this scenario also

https://github.com/gunthercox/ChatterBot/blob/ec189e05f2ccd4d16bca2a3168e0ecee61a20e68/tests/conversation_tests/test_statements.py#L68

> I've also noticed that my conversations table is empty. Please advise. Thanks.

Yes it's in under implementation

**Comment by kokenjr** [comment]
@vkosuri How can I go about troubleshooting this issue. I'm not really sure why this is occurring.

**Comment by kokenjr** [comment]
Ah it seems I wasn't passing back a cookie with the `sessionid` on my API calls. I seem to have rectified this issue.

**Comment by kokenjr** [comment]
@vkosuri After further testing, I'm still not consistently getting responses stored

**Comment by vkosuri** [comment]
@kokenjr If possible could you post your observations with example scenarios?

**Comment by kokenjr** [comment]
After monitoring it for long, I think it's behaving as expected now.

**Comment by vkosuri** [comment]
@kokenjr could you please post your observation, so that it will be useful for future verfications.
