### ISSUE TITLE
Request for documentation on Creating my own corpus

### ISSUE THREAD

**Issue by pranavlal** [gunthercox/ChatterBot#1041]
Hi all,
I want to use chatter bot in a FAQ situation. My users will pose questions to the bot and the bot will answer them. I have a list of questions and responses in AIML that are broken down by topics. Does chatter bot support topics? I see a category tag but I am not sure if this is the same thing as an AIML topic.
Is there any documentation that explains this in detail?

**Comment by vkosuri** [comment]
@pranavlal Thank you showing interesting updating corpus. The information grabbed from http://www.alicebot.org/aiml.html

```
The most important units of AIML are:

<aiml>: the tag that begins and ends an AIML document
<category>: the tag that marks a "unit of knowledge" in an Alicebot's knowledge base
<pattern>: used to contain a simple pattern that matches what a user may say or type to an Alicebot
<template>: contains the response to a user input
```
The free A.L.I.C.E. AIML includes a knowledge base of approximately 41,000 categories. Here's an example of one of them:
``` XML
<category>
    <pattern>WHAT ARE YOU</pattern>
    <template>
        <think><set name="topic">Me</set></think> 
        I am the latest result in artificial intelligence,
        which can reproduce the capabilities of the human brain
        with greater speed and accuracy.
    </template>
</category>
```

<b>And the below response is very clear, AIML category and chatterbot tag both are same, but coming AIM topic and Chatterbot tag aren't same</b>

<p>
In any case, if this category is called, it will produce the response "I am the latest result in artificial intelligence..." shown above. In addition, it will do something else interesting. Using the <think> tag, which causes Alicebot to perform whatever it contains but hide the result from the user, <b>the Alicebot engine will set the "topic" in its memory to "Me"</b>. This allows any categories elsewhere with an explicit "topic" value of "ME" to <b>match better than categories with the same patterns that are not given an explicit topic</b>. This illustrates one mechanism whereby a botmaster can exercise precise control over a conversational flow.
</p>

**Comment by pranavlal** [comment]
Hi,
Thanks for your answer. I understand how topics are used in AIML. I am confused by the YAML syntax in chatter bot. There is a categories: heading that I see in the corpus files. What is that used for? Can I exercise flow control by using these categories?

**Comment by vkosuri** [comment]
The best answer you could found here https://github.com/gunthercox/ChatterBot/issues/924

**Comment by pranavlal** [comment]
Understood thanks.
