### ISSUE TITLE
Serverless chatterbot is here

### ISSUE THREAD

**Issue by rajasimon** [gunthercox/ChatterBot#1045]
I've tried to bring the chatterbot to serverless world and tried deployed in AWS Lambda function.

Check out this repo [serverless-chatterbot](https://github.com/rajasimon/serverless-chatterbot) deployed in AWS Lambda.

**Comment by rajasimon** [comment]
@gunthercox Can you link this example to Chatterbot Readme. Or may be add new page in docs regarding the community project. i.e)  [channels community project](http://channels.readthedocs.io/en/stable/community.html)

**Comment by vkosuri** [comment]
@rajasimon can you make PR to address this issue?

**Comment by rajasimon** [comment]
@vkosuri thanks I'm making the changes for the pull request. Also I've plan to do the DynamoDB storage adapter for Chatterbot. Just started out let's see how this thing goes...
