### ISSUE TITLE
Django chatterbot web page looks like this and not working

### ISSUE THREAD

**Issue by nikhilv-quantela** [gunthercox/ChatterBot#1046]
My django chatterbot is up but suddenly it looks just like template, not the actual working one.
![screenshot from 2017-10-30 10-08-57](https://user-images.githubusercontent.com/31243445/32155013-b2bd8324-bd5a-11e7-9770-a727cb1108e1.png)

Some aid would be helpful. Thanks.

**Comment by vkosuri** [comment]
@nikhilv-quantela The problem here static fonts aren't loading, check here https://docs.djangoproject.com/en/1.11/howto/static-files/

Make sure you template added ``{% load staticfiles %}``

https://github.com/gunthercox/ChatterBot/blob/c3163c84e0c18dc712ea0a449175b5eff4ccd0e6/examples/django_app/example_app/templates/app.html#L1

**Comment by nikhilv-quantela** [comment]
@vkosuri 
Thanks for quick response, I checked the _app.html_ file` {% load staticfiles %}` is there.
I also cross checked _example_app/settings.py_, it has static files code block also

```
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(
        os.path.dirname(__file__),
        'static',
    ),
)
```

**Comment by nikhilv-quantela** [comment]
@vkosuri @gunthercox 
Any updates on this, I tried reinstalling the chatterbot, also installed and tested different system, in case any cache in browser affects this. But same result.

**Comment by nikhilv-quantela** [comment]
@vkosuri @gunthercox 
Sorry for extending but I have an update
Working properly when `Debug=True`, problems arise when `Debug=False`
But **SECURITY WARNING: don't run with debug turned on in production!**
So, is that to be taken care of while making separate websites?
Please clarify.
