### ISSUE TITLE
Testing django chatterbot on ubuntu server

### ISSUE THREAD

**Issue by nikhilv-quantela** [gunthercox/ChatterBot#1047]
@vkosuri @gunthercox 
I am tryning to test my django chatterbot on aws based ubuntu server, I have installed and tested the files, on `python manage.py runserver`, it is coming on 127.0.0.1:8000, which is not working.
My doubt is how to get it running through the server address which is like XX.XX.XXX.XXX:<port>

**Comment by rajasimon** [comment]
You have to run Django runserver in 0.0.0.0:80 . This resolves the ip address of the instance. And then you can view by your address...

https://stackoverflow.com/a/33735648/3762142

**Comment by nikhilv-quantela** [comment]
@rajasimon 
thanks for the response, but got this error

Django version 1.11.6, using settings 'example_app.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Error: You don't have permission to access that port.

Been studying on how to get that back, but need assist, used netstat to get the ports used, it is just showing nginx80 already in use.
Thanks

**Comment by rajasimon** [comment]
By theory you have to root all the Django traffic to Nginx and Nginx take care of the rest. Remember that nginx always running in the port 80 because of this you don't have to your Django server by port 80. 

- Case1. Please run Django as normal server `python manange.py runserver` Please see below example taken from gunicorn nginx settings...
```  
server {
    listen 80;
    server_name example.org;
    access_log  /var/log/nginx/example.log;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
```
- Case2. Stop Nginx server so port 80 will be free and run Django as 

    python manage.py runserver 0.0.0.0:80

**Comment by nikhilv-quantela** [comment]
@rajasimon 
thank you for detailed explanation, will work on it and get back

**Comment by nikhilv-quantela** [comment]
@rajasimon 

Case 1 is not my case, as nginx is used at port 80 for some other important applications. So, my question is:-

1. Is testing framework django chatterbot possible on port 80 as you described only, or can testing be done on some other ports?

2. If testing can only be done in port 80, how to migrate the applications on port 80 to another port?

Thanks

**Comment by rajasimon** [comment]
No you got it wrong... you can run Django runserver whichever port you want. Please run your django runserver as 127.0.0.1:8010 or etc...

**Comment by nikhilv-quantela** [comment]
ok thanks
