### ISSUE TITLE
mysql database save response with field 'text'

### ISSUE THREAD

**Issue by hochochoc** [gunthercox/ChatterBot#1050]
This is the error:
![screenshot from 2017-11-03 21-50-39](https://user-images.githubusercontent.com/18477288/32379839-33021098-c0e1-11e7-93b8-56074e68db1e.png)
Here is my database:
![screenshot from 2017-11-03 21-53-24](https://user-images.githubusercontent.com/18477288/32379987-8bc266ce-c0e1-11e7-9d59-6a7d7c230508.png)
How can I change the limit of field 'text' in the table 'django_chatterbot_statement' to save longer response.text ? Thank you.
![screenshot from 2017-11-03 21-57-22](https://user-images.githubusercontent.com/18477288/32380161-fea1eb56-c0e1-11e7-8d6c-2b5abada4295.png)

**Comment by vkosuri** [comment]
@hochochoc You could find the changes are here ``DIALOG_MAXIMUM_CHARACTER_LENGTH=400``

https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/corpus.py#L4

You could change like this, I hope this will help you.

``` Python
self.you_bot_obj.corpus.DIALOG_MAXIMUM_CHARACTER_LENGTH=500
```
