### ISSUE TITLE
Responding to foul language

### ISSUE THREAD

**Issue by pranavlal** [gunthercox/ChatterBot#1052]
Hi all,

How should I filter foul language? I see a file called swear_words.csv in the english corpus. I want to give a standard response to anyone using sware words.

**Comment by gunthercox** [comment]
This can be done by creating a custom logic adapter for your chat bot.

For example:

```python

from chatterbot.logic import LogicAdapter

class CustomLogicAdapter(LogicAdapter):

    def can_process(self, statement):
        word_list = ['one', 'two', 'three']
        for word in word_list:
            if word in statement.text:
                return True
        return False

    def process(self, statement):
        response = Statement(text='No foul language will be tolerated!')
        response.confidence = 1

        return response
```

***

Keep in mind, that ChatterBot will still be capable of learning foul language from the people that it talks to. I'm working on changes that will be released in version 1.0 that will prevent the chat bot from responding with foul language.
