### ISSUE TITLE
How can one create a chatterbot conversation in Django?

### ISSUE THREAD

**Issue by Ginliebhaber** [gunthercox/ChatterBot#1054]
How can one create a chatterbot conversation in Django?

I am sending a post request with "text" attribute. After getting the answer I want to respond, but the  answers in the "second level" of the conversation are never given back by the bot.

Any solutions?

**Comment by vkosuri** [comment]
@Ginliebhaber Could you please let me know fallowing things, to help in better way

1. Which version of chatterbot are you using, to know ``python -m cahtterbot --version``
2. Did you trained your bot using ``python manage.py train``

For sophisticated documentation about Django found here http://chatterbot.readthedocs.io/en/stable/django/index.html

**Comment by Ginliebhaber** [comment]
@vkosuri Thank you very much for your quick response.

1. Version is 0.7.6
2. I trained the bot via python manage.py train (with 'chatterbot.corpus.english.greetings',
        'chatterbot.corpus.english.conversations')

Maybe an example helps:
When I send post requests to http://localhost:8000/api/chatterbot/
the bot never goes into conversations e.g.:

me: "The cake is a lie."
bot: "No it is not. The cake is delicious."
me: "What else is delicious?"
bot: "Nothing" // never reached ....

So how does the bot know my session? ...
Is something like ...
{
"text" : "...",
"current_user_session_id" : "user1_xxxxx"
}

... possible?
Especially if two users are chatting with the chatbot at the same time, how could the bot distinguish between the two users (when they chat via the API) ?

**Comment by vkosuri** [comment]
@Ginliebhaber Here two questions

> You didn't received response from chatterbot 

I am not sure what exactly happened on your end, to debug your issue use ``browser developer tools``, go to ``network`` tab, It visualize all requests going through your end, And you can identify why your post request was dropped. 

Here is a documentation link how to developer tool in chrome https://developers.google.com/web/tools/chrome-devtools/network-performance/

> So how does the bot know my session? ...

Through ``conversation_id``, again use ``browser developer tools`` to view your ``conversation_id``

https://github.com/gunthercox/ChatterBot/blob/c3163c84e0c18dc712ea0a449175b5eff4ccd0e6/chatterbot/ext/django_chatterbot/views.py#L40
