### ISSUE TITLE
Other public chat/conversation corpuses available to train on Chatterbot 

### ISSUE THREAD

**Issue by nikhilv-quantela** [gunthercox/ChatterBot#1058]
Are there public chat/conversation corpuses on which chatterbot can be trained. Any links/ references would be really helpful.

Thanks

**Comment by vkosuri** [comment]
There are many datasets are publically valiable here http://archive.ics.uci.edu/ml/index.php

But you have to write your own corpus class to train your bot using chatterbot. More information about how to write new training class available here http://chatterbot.readthedocs.io/en/stable/training.html#creating-a-new-training-class

**Comment by nikhilv-quantela** [comment]
Will look into it, thanks
