### ISSUE TITLE
ChatterBot Django-training

### ISSUE THREAD

**Issue by EmanSaad11** [gunthercox/ChatterBot#1060]
Hello,
i’m developing a ML Arabic Chatbot using the Chatterbot in a Django application.
So, i set the setting file as follow:

```Python
CHATTERBOT = {
    'name': 'Female_bot',
    'storage_adapter' : {'import_path': 'chatterbot.storage.SQLStorageAdapter','database': 'Female'},
    'logic_adapters':[
        {"import_path": "chatterbot.logic.BestMatch",},
        {'import_path': 'chatterbot.logic.LowConfidenceAdapter','threshold': 0.5,'default_response': 'UNK'},],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': ['chatterbot.corpus.Arabic.Fcon'],
}

CHATTERBOT = {
    'name': 'Male_bot',
    'storage_adapter' : {'import_path': 'chatterbot.storage.SQLStorageAdapter','database': ‘Male'},
    'logic_adapters':[
        {"import_path": "chatterbot.logic.BestMatch",},
        {'import_path': 'chatterbot.logic.LowConfidenceAdapter','threshold': 0.5,'default_response': 'UNK'},],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': ['chatterbot.corpus.Arabic.Mcon'],
}
```

and added the app 'chatterbot.ext.django_chatterbot’, to INSTALLED_APP list. after that i want to train it but i got this:
``` Bash
[mansard@web569 src]$ python3 manage.py train
Mcon.yml Training: [####################] 100%
ChatterBot trained using “ChatterBotCorpusTrainer
```

The Female chatbot is not trained.
After the training the two bot the result was (  Male.db with the the Mcon crops data in it - Female.db with not data)

**Comment by vkosuri** [comment]
@EmanSaad11 I think you are using same setting file for your two objects, But chatterbot is considering only one configuration dict at a time, see here 

https://github.com/gunthercox/ChatterBot/blob/c3163c84e0c18dc712ea0a449175b5eff4ccd0e6/chatterbot/ext/django_chatterbot/views.py#L13

Currently ``chatterbot`` supports only one database at time perform different operations.

**Comment by EmanSaad11** [comment]
@vkosuri so there is no way to create two chatterbot in Django? because i need two chat bots with two different DB

**Comment by vkosuri** [comment]
Yes, this is possible with different ports.
