### ISSUE TITLE
how to deploy?

### ISSUE THREAD

**Issue by jszzzjs** [gunthercox/ChatterBot#1062]
how to deploy the code on to server?
i need to display this chatbot on a asp.net web page. I have already added HTML code on to ASP.net page. But need information on how we can interact with chatbot

**Comment by vkosuri** [comment]
@jszzzjs Are you trying to connect you web app to chatterbot server.  You could deploy your bot using Django integration, more information available here http://chatterbot.readthedocs.io/en/stable/django/index.html

**Comment by jszzzjs** [comment]
I have integrated it to Django. I am able to chat with the bot locally using local host. (using run server command -----python manage.py runserver 8080). 
Now I am trying to understand how to deploy this django and python code to server and access the same on asp.net webpage. I haven't done any deployments so far and this is my first attempt.

**Comment by taiwotman** [comment]
@jszzzjs, I don't quite understand why you want to place a python code on an Asp.net webpage? Python is not C# or VB that can be used with Asp.net webpage. Kindly correct me if am wrong.

**Comment by jszzzjs** [comment]
On asp. Net web page i have created the chatbot UI and connecting to python code through Ajax. Is it not possible?

**Comment by taiwotman** [comment]
I suggest you use REST web service by calling the chatterbot/api.

**Comment by jszzzjs** [comment]
Yes that's how I am able to make chatbot work locally. Now how to deploy the django/ python code to server is my question? Current project code is on iis. Shall I deploy to iis or Apache?

**Comment by shashank-sj** [comment]
Hoping this would be helpful https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/modwsgi/

**Comment by vkosuri** [comment]
You need public domain to deploy? Then these are the options you have http://chatterbot.readthedocs.io/en/stable/django/wsgi.html#webservices
