### ISSUE TITLE
How to switch the logic adapter if confidence is below certain value?

### ISSUE THREAD

**Issue by susmithHCK** [gunthercox/ChatterBot#1063]
Suppose i have an input, "Who is Elon musk", If Database have no coherent response, i.e low confidence i want to change the adapter to my own custom made adapter "WhoIsLogicAdapter" which can do certain task. Help me out.

**Comment by gunthercox** [comment]
Each logic adapter returns a "confidence" value that determine how accurately that particular logic adapter thinks that its chosen response is. This means that if there are no candidate responses in the database, that logic adapter would return a low confidence value and its response would be unlikely to be chosen.

In your custom logic adapter, you will just need to return a high confidence value if it thinks that in knows the person being asked about.
