### ISSUE TITLE
Can I have multiple questions give same answer?

### ISSUE THREAD

**Issue by nikhilv-quantela** [gunthercox/ChatterBot#1064]
Can I answer multiple questions like:
**What can you do for Mack?
How can you help Mack?
Can you do something for Mack?**
with:
**I can make mac-n-cheese**

I am using yml format for my custom corpus. Is there quicker way to do this, or do I have to create separate lines for all:
- - What can you do for Mack?
  - I can make mac-n-cheese
- - How can you help Mack?
  - I can make mac-n-cheese
- - Can you do something for Mack?
  - I can make mac-n-cheese

**Comment by gunthercox** [comment]
Currently there is not a quicker way to achieve that. This is a feature request that I've seen a number of times though. I've opened a ticket in the corpus module for getting this functionality added: https://github.com/gunthercox/chatterbot-corpus/issues/58
