### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by likyen** [gunthercox/ChatterBot#1067]
I run _int_.py and all I get is Traceback (most recent call last):
```
  File "/Users/connergoodall/Desktop/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
ModuleNotFoundError: No module named '__main__.chatterbot'; '__main__' is not a package
```

**Comment by vkosuri** [comment]
Hi @likyen I didn't know what exactly in ``int.py``, you try one example in [examples](https://github.com/gunthercox/ChatterBot/tree/master/examples) directory to understand more on how chatterbot will work.
