### ISSUE TITLE
Train data based on condition

### ISSUE THREAD

**Issue by dheerajvarmarsv** [gunthercox/ChatterBot#1075]
I created a normal chatbot with training data using sqllite3.db . Now how can i i train my data based on certain id ... like for id = 1 i need to get one set of responses and for id = 2 i need to get one set of responses which doesnt match with id = 1 @vkosuri @gunthercox

**Comment by vkosuri** [comment]
@dheerajvarmarsv This is possible

``` Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

# Create a new chat bot named Charlie
chatbot = ChatBot(
    'Charlie',
    trainer='chatterbot.trainers.ListTrainer'
)

corpus = [
    "1",
    "Sure, I'd like to book a flight to Iceland.",
    "2", 
    "Your flight has been booked."
]

train_data = []

for line in corpus:
    if line == "1":
        train_data.append(first_set_list)
   elif line == "2":
       train(data.append(second_set_list)


chatbot.set_trainer(ListTrainer)
chatbot.train(train_data)

# Get a response to the input text 'How are you?'
response = chatbot.get_response('I would like to book a flight.')

print(response)
```

**Comment by dheerajvarmarsv** [comment]
Thanks @vkosuri  this is great ....since i am a beginner i have one more doubt how can i use it for ChatterBotCorpusTrainer because i have huge training data 

this is the code i am using

 from chatterbot import ChatBot
    bot = ChatBot(
        "charlie",    
        logic_adapters=[
            {
                 "import_path": "chatterbot.logic.BestMatch"            }          
        ],     
        trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
                 
        )
    bot.train(("Example.yml"))
    response = bot.get_response(input)
    print(response)


for each user ..based on his id he gets his response from that id   

thanks in advance

**Comment by dheerajvarmarsv** [comment]
I want to pass some unique id and get the data from the response and statement table based on that id and my bot should return the answer based on that set of data instead of getting all data from table @vkosuri  @gunthercox

**Comment by gunthercox** [comment]
@dheerajvarmarsv I apologize, I don't fully understand your question. It's been a few months since this ticket was opened, I'm going to close it off. Feel free to re-open it if you're still encountering an issue.
