### ISSUE TITLE
follow the conversation

### ISSUE THREAD

**Issue by mariopaonessa** [gunthercox/ChatterBot#1076]
Hi there. First I love this work! Well done!

Probably I did not found the right settings. But I asked me if there is an option to follow the conversation if possible. In example: I have questions in my corpora that can be answered with a simple "yes" or a "no" in my case it replies depending on the strategy "BestMatch" or "Random" even with a Session just something out of the possible Answers to "yes" and "no". But it takes not care of the previous conversation.

Training Sample:

A: Hi
B: Hello
A: Are you hungry?
B: yes
A: Then lets eat something

A: Hello
B: Hi
A: Are you happy?
B: yes
A: Nice!

If I follow now the first conversation it is more or less luck if I have the right answer. Is there a trick or should I work on this feature. Or am I the only one with this issue?

Regards

mario

**Comment by vkosuri** [comment]
@mariopaonessa What you are looking this feature? 

https://github.com/gunthercox/ChatterBot/blob/7255298d17051e78c0a8c309284ba285d41d8763/chatterbot/chatterbot.py#L116

Did you tried feedback_example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py

**Comment by mariopaonessa** [comment]
I'll try it out. Thx for the hint.

But I'm not sure if this will fix my issue. Because it seems just to take the latest response into account. Not the whole conversation, right? Just another example:

A: How can I help you?
B: My computer is broken!
A: Do you rebooted it?
B: yes
A: Is the powersupply well connected?
B: yes
A: Then please call the number 123456789

Now after my input "yes" it replies randomly or if BestMatch with always the same answer to my question. I know that with simple Answers there are other Architectures around like in Workflow-Engines. But this is just an example. I need to model the answer related to the whole conversation to enhance the flow.

regards

mario

**Comment by mariopaonessa** [comment]
👍  
Closest subtree matching #362  this sounds more like the solution :) Let me know if I can contribute to this.

regards

mario

**Comment by vkosuri** [comment]
You are more than welcome @mariipaoessa
