### ISSUE TITLE
Use existing database table instead of statement training table.

### ISSUE THREAD

**Issue by tisuchi** [gunthercox/ChatterBot#1078]
I am using existing mysql database for chatterbot. I have a table where more than 100K record that I want to use to train chatterbot instead of default **django_chatterbot_statement** training data. 

Any tips how to implement that?

**Comment by vkosuri** [comment]
@tisuchi As per my knowledge currently there is no support mysql storage in chatterbot. How ever did you tried to replace settings.py to mysql storage

https://github.com/gunthercox/ChatterBot/blob/8eb3971eca42f3f2c3b70444ca1b0e0e479cdb90/examples/django_app/example_app/settings.py#L80

This guide will help configure mysql on Django https://www.digitalocean.com/community/tutorials/how-to-use-mysql-or-mariadb-with-your-django-application-on-ubuntu-14-04

If didn't worked all above steps, try to sync your database mysql with sqllite https://github.com/sqlite-sync/SQLite-sync.com

**Comment by tisuchi** [comment]
Since its a django app, I think we can do that. Although I am a new comer (few weeks) in django / python world, however, I have managed to connect with mysql. 

Here is my code-

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sb',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
```
That's working fine. Now what's is my expectation to train chatterbot based on my existing data from existing table. 


By default it store into ** django_chatterbot_statement** table, however, I want to store into **messages** table that is my existing table.

**Comment by tisuchi** [comment]
Any suggestion / luck so for for me guys?

**Comment by taiwotman** [comment]
Usually for development environmnent,  Django comes with dbsqlite which is just enough to get started and to fo your test. Yes, in production you may need a better database like MySQL. However if you are going to deploy on Heroku cloud, it make sense to go with Postgres database in your production settings.

**Comment by taiwotman** [comment]
Usually for development environmnent,  Django comes with dbsqlite which is just enough to get started and to do your test. Yes, in production you may need a better database like MySQL. However if you are going to deploy on Heroku cloud, it make sense to go with Postgres database in your production settings.

**Comment by tisuchi** [comment]
@taiwotman 
I am able to connect with mysql database for local development easily. However, what I want now to use different database table to store train up data of chatterbot instead of **django_chatterbot_statement**.

**Comment by taiwotman** [comment]
I only know the simple chatterbot Django database method that tested and trusted. Perhaps someone else might resolve  your question. However, as currently state by @vkosuri "...currently there is no support for  mysql storage in chatterbot"

**Comment by gunthercox** [comment]
@tisuchi If you are using Django, then it is possible to specify your own table names as a part of the model meta data attributes. There is a section describing it in the Django documentation:

https://docs.djangoproject.com/en/1.11/ref/models/options/#db-table

ChatterBot has abstract base classes for each model available that you can import and use to create new models that have an modified model name.

I'll note that this isn't something I've tried before, I'm purely going off of what appears to be possible based on the Django docs.

Here is a quick example of what your modified models might look like:

```python
# models.py

from chatterbot.ext.django_chatterbot.abstract_models import AbstractBaseStatement

class CustomStatement(AbstractBaseStatement):

    class Meta:
        db_table = 'my_custom_table_name'
```

```python
# settings.py

CHATTERBOT = {
    'statement_model': 'CustomStatement'
}
```

I haven't tested the code above, but hopefully it might guide you in the right direction.
You _might_ end up needing to create your own, new models for ALL of ChatterBot's abstract base models for this to work. If this is the case then you'll probably have to set `CHATTERBOT['django_app_name']` equal to whatever your Django App is called in your `settings.py` file.
