### ISSUE TITLE
Custom adapter not returning values

### ISSUE THREAD

**Issue by pramodpm** [gunthercox/ChatterBot#1079]
I am using Chatterbot 0.7.6 version. I want to integrate a custom logic adapter which will get activated based on a special character at the start of statement(^).  I want to retrieve some values for local Solr search when there is a special character. Otherwise I want to use the other logic adapters.

The issue I am facing is that the  custom logic adapter is  unable to return the values(confidence,response_statement) to the call from Chatbot. Below line is unable to retrieve the confidence value and response statement. 
response = bot.get_response("^How can I help u")

Let me know how can I return those values to display the response from search.

``` Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot


# Create a new instance of a ChatBot
bot = ChatBot(
    'Default Response Example Bot',

    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation'
        },
        {
            'import_path': 'chatterbot.logic.TimeLogicAdapter'
        },
        {
            'import_path': 'custom_adapter.MyLogicAdapter',
            #'default_response': 'I am sorry, but I do not understand.'
        }

    ]
)
response = bot.get_response("Hello")
print(response)

response = bot.get_response("What is 2 + 9?")
print(response)

response = bot.get_response("What is 4 * 9?")
print(response)

# Print an example of getting one time based response
response = bot.get_response("What time is it?")
print(response)
#response = ""
# Print an example of getting custom response

response = bot.get_response("^How can I help u")
print(response)
######################################################################

from chatterbot.logic import LogicAdapter

class MyLogicAdapter(LogicAdapter):
    def __init__(self, **kwargs):
        super(MyLogicAdapter, self).__init__(**kwargs)

    def can_process(self, statement):
        if statement.text.startswith('^'):
                return True
        else:
                return False
    def process(self, statement):
        from chatterbot.conversation import Statement
        import requests

        # Make a request to the temperature API
        #response = requests.get('http://api.temperature.com/current?units=celsius')
        response = requests.get('http://localhost:8983/solr/search/select?indent=on&q=*:*&wt=json')
        data = response.json()
        #print response.status_code
        # Let's base the confidence value on if the request was successful
        if response.status_code == 200:
                confidence = 1
        else:
                confidence = 0

        temperature = data.get('temperature', 'unavailable')

        response_statement = Statement('The current temperature is {}'.format(temperature))
         return confidence,response_statement

```

**Comment by vkosuri** [comment]
Did you tried to import from python console? Did it worked?

**Comment by pramodpm** [comment]
I tried on Python console. There also it is not returning the expected response from custom adapter. It is returning another response from corpus English.

>>> response = bot.get_response("Hello")
>>> print(response)
Hi
>>> response = bot.get_response("What is 2 + 9?")
>>> print(response)
( 2 + 9 ) = 11
>>>
>>> response = bot.get_response("What is 4 * 9?")
>>> print(response)
( 4 * 9 ) = 36
>>>
>>> # Print an example of getting one time based response
... response = bot.get_response("What time is it?")
>>> print(response)
The current time is 01:52 AM
>>> response = bot.get_response("^How can I help u")
>>> print(response)
A robot cannot take offense.

**Comment by vkosuri** [comment]
chatterbot uses [import module](https://docs.python.org/2/library/importlib.html) using path, the should be accessible by your scripts. Read some of issues are https://stackoverflow.com/a/67692/358458

**Comment by pramodpm** [comment]
I am able to import module. In fact I was able to do  a print statement from the imported module. I was able to see the values for status_code. 
    print response.status_code
But then while returning it is not reached the calling program.
