### ISSUE TITLE
DjangoStorageAdapter django.db.utils.DataError: value too long for type character varying(255)

### ISSUE THREAD

**Issue by mikekeda** [gunthercox/ChatterBot#1083]
I'm try to use DjangoStorageAdapter and I'm getting an error on https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/humor.yml#L34:
`django.db.utils.DataError: value too long for type character varying(255)`
limit for the text field is 255 and this joke has 394 characters.

I think we need to increase the limit to 500

**Comment by mikekeda** [comment]
As I see it's fixed in master branch, and there are limit 400 (I used 0.7.6)

**Comment by glxiong** [comment]
Can we increase it to 1000? The current 400 is not sufficient. I got the following error training using my own yml.

django.db.utils.DataError: value too long for type character varying(400)
