### ISSUE TITLE
Splitting my responses into 2

### ISSUE THREAD

**Issue by Pythonbotty** [gunthercox/ChatterBot#1084]
I am trying to split my response into basically 2 responses. I am trying to do a "split" on the response with the following code with a word <stop>. But I ran into the error of "Statement" object has no attribute "split". Since what is returned should have been a string, why will there  be an error? Here are my codes: 

while True:
    try:
        sentence = raw_input (" ")
        abc = bot.get_response(sentence)
        abcSplit = abc.split("<stop>")
        print abcSplit
    except(KeyboardInterrupt,EOFError,SystemExit):
        break

**Comment by vkosuri** [comment]
You have to write a pre processor to accomplish
Documentation how to do here http://chatterbot.readthedocs.io/en/stable/preprocessors.html

**Comment by Pythonbotty** [comment]
Return my response with .text.split(), and has resolved this. Thanks Gunther!
