### ISSUE TITLE
Ubuntu Training Time

### ISSUE THREAD

**Issue by Kapowpenguin1** [gunthercox/ChatterBot#1088]
I don't know if this is the right place to ask, but I ran the Ubuntu corpus training example. Now my terminal is just endlessly spewing out dialogue. How long should the training take?

**Comment by vkosuri** [comment]
Mostly it will take 1 day? Read useful information http://chatterbot.readthedocs.io/en/stable/training.html#training-with-the-ubuntu-dialog-corpus
