### ISSUE TITLE
Read only mode doesn't work

### ISSUE THREAD

**Issue by xiaolitang** [gunthercox/ChatterBot#1090]
Hello :)

This is the code I wrote:

``` Python
from chatterbot import ChatBot
from chatterbot.response_selection import get_random_response
from chatterbot.trainers import ChatterBotCorpusTrainer

import logging
logging.basicConfig(level=logging.INFO)

chatbot = ChatBot("ChatBot",
                  response_selection_method=get_random_response,
                  logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.80,
            'default_response': 'umm..'
        }
        ],

                  )

chatbot.set_trainer(ChatterBotCorpusTrainer)
chatbot.train('chatterbot.corpus.untitled')

while True:
    input_statement=input('>>')
    response = chatbot.get_response(input_statement)
    print(response)
```

Everything goes well with this code. 

But as I do not want the bot to learn extra conversations from my inputs, I followed the guide to add the command 'read_only=True'. 

But unfortunately it didn't work at all. From logging, it was still giving the information that 'Adding "something" as a response to "something".

Is there any way to solve the problem?

I would be grateful for your help :)

**Comment by vkosuri** [comment]
Similar issue https://github.com/gunthercox/ChatterBot/issues/1091?

**Comment by xiaolitang** [comment]
Thanks vkosuri for your reply. But unfortunately it is not similar.. My problem is the bot still keeps adding my input as response to the latest output (adding to the storage file) when I use 'read_only=True'.

**Comment by vkosuri** [comment]
@xiaolitang Thanks, The test are confirming that the ``read_only`` feature is working fine. 

https://github.com/gunthercox/ChatterBot/blob/2ff9a2c5b12c4597ccd630db388b05b9208d28ba/tests/test_context.py#L11

Could you verify the actual value present read_only of your bot, after ``train`` on your example?

for example

``` Python
print(chatbot.read_only)
```

**Comment by xiaolitang** [comment]
Thanks vkosuri,

I printed it out and I found it turn up with 'False'. Thats the reason why it kept learning from my input. But later I was sure it has been successfully set to read only mode and it printed 'True'. But the logging showed the following:
INFO:chatterbot.adapters:Not processing the statement using BestMatch
INFO:chatterbot.adapters:Not processing the statement using LowConfidenceAdapter

I couldn't use those logic adapters with 'read_only=True' then.

Do you have any clue to solve it?


Thank you very much

**Comment by vkosuri** [comment]
``
INFO:chatterbot.adapters:Not processing the statement using BestMatch
INFO:chatterbot.adapters:Not processing the statement using LowConfidenceAdapter
`` 
These are default adapters that consumes by chatterbot

https://github.com/gunthercox/ChatterBot/blob/7255298d17051e78c0a8c309284ba285d41d8763/chatterbot/logic/multi_adapter.py#L74

https://github.com/gunthercox/ChatterBot/blob/7255298d17051e78c0a8c309284ba285d41d8763/chatterbot/chatterbot.py#L25

**Comment by xiaolitang** [comment]
Thanks vkosuri,

Yes, they are. But how could I let the bot go through these adapters at read only mode?
I hope to get the same responses as 'read_only=False'. And make the bot not learn from my inputs.

**Comment by xiaolitang** [comment]
I think my issue is the same as 'Error with read_only=False #1091'.
That is, when I enabled read only mode, the bot did not capture my input anymore. And it didn't go through the adapters and database either.

**Comment by gunthercox** [comment]
This issue should have been corrected in the latest release. Please let me know if this issue persists in version 1.0
