### ISSUE TITLE
Update corpus based on confidence

### ISSUE THREAD

**Issue by rttestgithub** [gunthercox/ChatterBot#1101]
Hello,

thanks for starting this great bot-project.
After deployment and testing I came up with two general questions:

1) Is it possible to update the conversations in the corpus based on the confidence of a response ?
For example, when response to a given statement is above a certain confidence threshold.
How can I write the given statement and high confidence response directly to the corpus,
that after a brief restart of the the valid response was "learned" by the bot.

2) Alternatively, how is it possible to store a certain response together with the previous statement under the response section of a sqlite3 database file, directly after the response was produces by the bot ?

Have a great week &
many Thanks

**Comment by gunthercox** [comment]
Hi @rttestgithub 

Sorry, it is not possible to apply confidence values to the statements in the ChatterBot corpus files.

ChatterBot automatically stores associations between statements. This can be done using the `train` method using one of the supported training classes (such as the corpus trainer).
