### ISSUE TITLE
Error running basic examples

### ISSUE THREAD

**Issue by engrphil** [gunthercox/ChatterBot#1103]
$ python ./basic_example.py
Traceback (most recent call last):
  File "./basic_example.py", line 7, in <module>
    trainer='chatterbot.trainers.ListTrainer'
  File "/Library/Python/2.7/site-packages/ChatterBot/chatterbot/chatterbot.py", line 39, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/Library/Python/2.7/site-packages/ChatterBot/chatterbot/utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "/Library/Python/2.7/site-packages/ChatterBot/chatterbot/storage/sql_storage.py", line 41, in __init__
    from sqlalchemy import create_engine
ImportError: No module named sqlalchemy

I AM VERY SURE sqlalchemy folder exists in the Library under site-packages

**Comment by vkosuri** [comment]
@engrphil Which version of chatterbot are you using?

```Bash
pip install -U chatterbot
```

If you still osereve same issue try to install 
```Bash
pip install -U sqlalchmey
```

**Comment by engrphil** [comment]
Looking at the log below. Everything seems fine and chatterbot was installed successfully but I can't find chatterbot-0.8.1 folder anywhere in the site-packages directory. Please, help

Phil$ sudo -H pip install -U --user chatterbot
Collecting chatterbot
  Using cached ChatterBot-0.8.1-py2.py3-none-any.whl
Requirement already up-to-date: python-dateutil<2.7,>=2.6 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from chatterbot)
Requirement already up-to-date: nltk<4.0,>=3.2 in /Library/Python/2.7/site-packages (from chatterbot)
Requirement already up-to-date: chatterbot-corpus<1.2,>=1.1 in /Library/Python/2.7/site-packages (from chatterbot)
Requirement already up-to-date: pymongo<4.0,>=3.3 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from chatterbot)
Requirement already up-to-date: jsondatabase<1.0.0,>=0.1.7 in /Library/Python/2.7/site-packages (from chatterbot)
Requirement already up-to-date: python-twitter<4.0,>=3.0 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from chatterbot)
Requirement already up-to-date: mathparse<0.2,>=0.1 in /Library/Python/2.7/site-packages (from chatterbot)
Requirement already up-to-date: sqlalchemy<1.2,>=1.1 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from chatterbot)
Requirement already up-to-date: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil<2.7,>=2.6->chatterbot)
Requirement already up-to-date: PyYAML<4.0,>=3.12 in /Library/Python/2.7/site-packages (from chatterbot-corpus<1.2,>=1.1->chatterbot)
Requirement already up-to-date: requests-oauthlib in /private/var/root/Library/Python/2.7/lib/python/site-packages (from python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: future in /private/var/root/Library/Python/2.7/lib/python/site-packages (from python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: requests in /private/var/root/Library/Python/2.7/lib/python/site-packages (from python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: oauthlib>=0.6.2 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from requests-oauthlib->python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: idna<2.7,>=2.5 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: certifi>=2017.4.17 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot)
Installing collected packages: chatterbot
  Found existing installation: ChatterBot 0.7.6
    Uninstalling ChatterBot-0.7.6:
      Successfully uninstalled ChatterBot-0.7.6
Successfully installed chatterbot-0.8.1

**Comment by vkosuri** [comment]
@engrphil I can tell it's installed here 

```
 /private/var/root/Library/Python/2.7/lib/python/site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot)
```
I am not sure why it appreaing in that folder, you may try to get version of the chatterbot by doing like, if it works, it's installed,

```
python -m chatterbot --version
```
