### ISSUE TITLE
New User Questions

### ISSUE THREAD

**Issue by genacct1977** [gunthercox/ChatterBot#1104]
I have been pouring over documentation.  I have basic chatterbox along with my own corpus.  How can I handle the two following situations?

1. When having a conversion with the bot will it retrain new data learned from the conversation?
Me:How are you?
Bot:Fine and you.
Me: I have a cold but not the flu.
Bot. Sorry you are sick.
Me: What did I tell you I was sick with?
BOT: A cold but not the flu                       <----Is this possible? Also can it remember later say tomorrow I 
                                                                         start the bot and ask it when I was last sick?

2.Web interface
What is the best way to have a web interface? I have the terminal working now.

**Comment by genacct1977** [comment]
I tried it in the bot and this is what it did:

J: Hi
Bot: How are you doing?
J: I am tired.
Bot: Sorry.

J: How did I say I am doing?
Bot: I am sorry, but I do not understand.

**Comment by vkosuri** [comment]
@genacct1977 See example to achieve first question https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py

Web interface chatterbot has multiple web interface Django http://chatterbot.readthedocs.io/en/stable/django/index.html and lighter version https://github.com/chamkank/flask-chatterbot

A live Heroku example for chatterbot  https://github.com/vkosuri/chatterbot-live-example

**Comment by genacct1977** [comment]
Any suggestion?      bot.storage.add_to_conversation(CONVERSATION_ID, request, response)

 bot.storage.add_to_conversation(CONVERSATION_ID, request, response)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/sql_storage.py", line 312, in add_to_conversation
    text=statement.text
