### ISSUE TITLE
how to multiprocess training?

### ISSUE THREAD

**Issue by mrmrn** [gunthercox/ChatterBot#1105]
I am using [cornell university corpus](https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html) for training my bot.
It takes time more than 2 days. could I split the dataset.txt file into 4 files and merge all result in 1 sqlite file finally?

**Comment by gunthercox** [comment]
It sounds like you wrote your own training class for your chat bot. Have you looked into Python's multiprocessing library?

https://docs.python.org/3.6/library/multiprocessing.html

***

Related #354
