### ISSUE TITLE
Is it possible to save a pre-trained chatbot? 

### ISSUE THREAD

**Issue by NavyaZaveri** [gunthercox/ChatterBot#1106]
Title, really. I was wondering if it's possible to save an existing model so that I don't have to train it every time I re-run my script. 

I've looked at the docs, and the closest I found was the method `export_for_training`; but that only exports training data, not the chatbot itself.

Is there a mechanism that saves a chatbot?

**Comment by gunthercox** [comment]
ChatterBot instances are designed to be stateless. Everything that they learn is stored in a chat bot's connected database.

You shouldn't need to re-train your chat bot each time the script is run because the training data is persisted.

***

So, to answer the question, there is no method that allows a chat bot to be "saved", but if yo want to create a database backup then you can easily restore it to another chat bot's database.

**Comment by NavyaZaveri** [comment]
> You **shouldn't need to re-train** your chat bot each time the script is run because the training data is persisted.

I'm not sure I follow. 

While the training data is persisted, I'm still going to have to train the chatbot _on the data_ the next time I run the script, correct? I'm looking to avoid the time-cost to training it at every re-run

I was hoping for something like tensorflow's functionality where you can persist the state of a model so you don't have to re-train the model if you want to use it later. But since ChatterBot instances are stateless by design, that doesn't seem to be an option.

**Comment by NavyaZaveri** [comment]
Thanks!

**Comment by vkosuri** [comment]
As master @gunthercox said, the trained data is persist, so we can re-use whenever you required.

some workaround or an actual answer i am not sure, you could split your bot program into two phase one for train, one for bot.

For example

> train.py
```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

# Create a new chat bot named Charlie
chatbot = ChatBot(
    'Charlie',
    trainer='chatterbot.trainers.ListTrainer'
)

chatbot.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])
```

> bot.py
```Python
```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

# Create a new chat bot named Charlie
chatbot = ChatBot(
    'Charlie',
    trainer='chatterbot.trainers.ListTrainer'
)
# Get a response to the input text 'How are you?'
response = chatbot.get_response('I would like to book a flight.')

print(response)
```
