### ISSUE TITLE
ChatterBot context in conversation.

### ISSUE THREAD

**Issue by genacct1977** [gunthercox/ChatterBot#1108]
I have ChatterBot running in Ubuntu and Armbian.  
I have created a ListTrainer and later a custom Corpus.  The system works well and loads for the conversation.  I have two things I am not making headway with and wanted to see if anyone had some code examples.  I am running these from CLI  so no gui.

1. I would like to see if there was a way for ChatterBot to remember something just said in the conversion.  I looked at the example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py

When I try to add to the conversation I get the following error:
Code:
bot.storage.add_to_conversation(CONVERSATION_ID, request, response)

File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/sql_storage.py", line 312, in add_to_conversation
text=statement.text

The example file does not have it reading the request and response from a CLI.  I can only gather the function needs specific types of input that I don't know how to convert.

2.
I know how to train with corpus and with List Trainer and I have created code that will allow you to type a request and get a response saved into the database.  But should the system be learning new things through conversation?  Like if I say I like a certain color or food.  Can I add that request/response without starting a "training session"?  I ask because I saw how to disable the learning with the "read only" command but It doesn't appear to be learning new things unless I train.

Any help would be appreciated.

`while True:

        request = raw_input(UserName + ': ')

        response = bot.get_response(request)

        input_statement = bot.input.process_input_statement()

        statement, response = bot.generate_response(input_statement, CONVERSATION_ID)

        print('Bot: ' + str(response))

        print('Statement:' + statement.text)

        bot.storage.add_to_conversation(CONVERSATION_ID, statement, response)

        bot.output.process_response(response)`

**Comment by genacct1977** [comment]
So I figured out number 2.  I added the following code and can see how the system works.

import logging
logging.basicConfig(level=logging.INFO)
 

Still need help with number 1.

**Comment by vkosuri** [comment]
@genacct1977 could you post your full stack trace, we can help further on this?
```Bash
File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/sql_storage.py", line 312, in add_to_conversation
text=statement.text
```

**Comment by genacct1977** [comment]
Traceback (most recent call last):
  File "rem.py", line 81, in <module>
    bot.storage.add_to_conversation(CONVERSATION_ID, request, response)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/sql_storage.py", line 312, in add_to_conversation
    text=statement.text
AttributeError: 'str' object has no attribute 'text'

**Comment by vkosuri** [comment]
This were the problem, you were converting ``response`` object into string. You could write like this

``` Python
request = raw_input(UserName + ': ')
response = bot.get_response(request)
print('Bot: ' + response)
print('Bot: "+ response.text)
bot.storage.add_to_conversation(CONVERSATION_ID, request, response)
bot.output.process_response(response)
```

**Comment by genacct1977** [comment]
I am getting an error that says request has no property called text.

raceback (most recent call last):
  File "rem.py", line 70, in <module>
AttributeError: 'str' object has no attribute 'text'

**Comment by vkosuri** [comment]
@genacct1977 if possible can you share your code?

**Comment by PoojaPatel05** [comment]
I am also getting the same error
  ` print('chatbot: ' + response.text)
AttributeError: 'str' object has no attribute 'text'
`

**Comment by vkosuri** [comment]
Instead try ``print('chatbot: ' + response)``

**Comment by LeoLuo22** [comment]
I'm runing ChatterBot with Python 3.5.3 on Windows10. When I use UbuntuCorpusTrainer to train my bot, I got an UnicodeDecodeError: codec cannot decode 'gbk' code. So confused.

**Comment by vkosuri** [comment]
@LeoLuo22 I think your question different from this issue, could you please create a separate issue with stacktrace? So that you will get better answers from others also.
