### ISSUE TITLE
Learn from conversation

### ISSUE THREAD

**Issue by DaCodaHUB** [gunthercox/ChatterBot#1111]
I have been playing with Chatterbot and it's awesome. You guys did a terricfic job. Now I want to take it a step further. I want my bot to learn from the conversation.

User: How're you?
Bot: I'm fine
User: And you?

I want to save "I'm fine" as a statement and "And you?" as a response. I know that I can use add_to_conversation() to save the response, but I'm having trouble getting the last response. Is there a way to save the last response to the database and recall it later?

**Comment by gunthercox** [comment]
Hi @DaCodaHUB,

ChatterBot will save the last response to the database automatically. This is the default behavior.

**Comment by DaCodaHUB** [comment]
So how do I retrieve it?

**Comment by vkosuri** [comment]
```Python
<chatbot_instance>.response.text
```
