### ISSUE TITLE
Tell me a joke

### ISSUE THREAD

**Issue by genacct1977** [gunthercox/ChatterBot#1113]
I have a corpus file called humor.yml

It has multiple examples of  Tell me a joke.  The problem is it has the same joke each time.

How can I have it tell different jokes each time?

**Comment by alvarogalvez** [comment]
hi, 

I'm not prety sure, but if I don't get wrong, you need to set the response_selection_method in the logic adapter into random_response instead of chatterbot.response_selection.get_first_response

**Comment by genacct1977** [comment]
I got this working code is below.  My only issue is it says Random or Not Random every query.

 logic_adapters=[
        "chatterbot.logic.MathematicalEvaluation",
        {
        "import_path": "chatterbot.logic.BestMatch",
        "response_selection_method": "chatterbot.response_selection.get_random_response"      
        },
