### ISSUE TITLE
Add a link in the Documentation to the ChatterBot Blog

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1122]
I'd like to see a link to the new ChatterBot Blog added to the ChatterBot documentation.

I'm open to suggestions on the best location for this. Maybe an addition to the sidebar?

- Documentation: https://chatterbot.readthedocs.io
- Blog: https://blog.chatterbot.us

The documentation site source can be found in the [`docs`](https://github.com/gunthercox/ChatterBot/tree/master/docs) directory.
The documentation can be build locally using the [Sphinx}(http://www.sphinx-doc.org/) command:

```
sphinx-build -nW -b html ./docs/ {envtmpdir}/build/
```

**Comment by vkosuri** [comment]
My choice would be also a sidebar

**Comment by GitCMDR** [comment]
Sidebar would be nice!

**Comment by gunthercox** [comment]
I'm closing this ticket off for now. I've been rethinking the layout of the docs & blog and I might go for something that is a bit more unified.
