### ISSUE TITLE
Question that is answered in another question's answer.

### ISSUE THREAD

**Issue by genacct1977** [gunthercox/ChatterBot#1123]
Example corpus:

- - What did you do on 12/7/2017
  - I saw star wars the the jedi

Question asked of chat bot:  Have you seen Star Wars the last jedi?

Is it possible to generate a answer based on the Answer to a different question?

Either print What did you do on 12/7/2017  or something more unique like "yes I saw it on 12/7/2017."

**Comment by gunthercox** [comment]
Sorry, it's not currently possible to generate new, unique output in ChatterBot.
