### ISSUE TITLE
default response for custom adapter

### ISSUE THREAD

**Issue by sinscary** [gunthercox/ChatterBot#1124]
I am building a chatbot and I have created a few custom adapters. my custom adapters inherit from logic adapter class. I am not able to set a default response in case my adapter can't process a statement and in that case, it returns the query itself as a response.

Please help me how can I set a default response for my custom adapters, if it can't process the response.

**Comment by vkosuri** [comment]
could you provide your chatbot config?

**Comment by sinscary** [comment]
Here is my chatbot config file - 

```
from chatterbot import ChatBot
import conversation_adapters
import pdb
chatbot = ChatBot(
    "Terminal bot",
    logic_adapters=[{
            "import_path" : "my_custom_adapter.MyCustomAdater1"
        },
        {
            "import_path" : "my_custom_adapter.MyCustomAdater2"
        },
        {
            "import_path" : "my_custom_adapter.MyCustomAdater3"
        }
    ],
    input_adapter="chatterbot.input.TerminalAdapter",
    output_adapter="chatterbot.output.TerminalAdapter"
)

print("Hello I am Terminal bot")

while True:
    try:
        bot_input = chatbot.get_response(None)

    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

Here is a sample of my one of custom adapter

```
from chatterbot.logic import LogicAdapter
from chatterbot.conversation import Statement
import location_details
import random
import pdb

class MyCustomAdapter1(LogicAdapter):

	def __init__(self, **kwargs):
		super().__init__(**kwargs)

	def can_process(self, statement):

		words = ["Hello", "Hi", "Hey" ]
		if any(word in statement.text.lower().split() for word in words):
			return True
		else:
			return False


	def process(self, statement):
		responses = ["Hello", "Hi there!", "How are you"]
		confidence = 1
		response_statement = (Statement(random.choice(responses)))
		return confidence, response_statement

```

**Comment by vkosuri** [comment]
I didn't find any issue with your logic, may you could try with enabling logging to see how chatterbot is selecting logic functions

https://github.com/gunthercox/ChatterBot/blob/dc1af906d1e34884deddd4857cc7947fa5257697/examples/terminal_example.py#L7

**Comment by sinscary** [comment]
I tried that. NoConfidenceAdapter selects the response. This is what i got in verbose logs

```
skldjflksd
INFO:chatterbot.adapters:Received input statement: skldjflksd
INFO:chatterbot.adapters:"skldjflksd" is not a known statement
INFO:chatterbot.adapters:Not processing the statement using CustomAdapter1
INFO:chatterbot.adapters:Not processing the statement using CustomAdapter2
INFO:chatterbot.adapters:Not processing the statement using CustomAdapter3
INFO:chatterbot.adapters:NoKnowledgeAdapter selected "skldjflksd" as a response with a confidence of 0
skldjflksd
```

Instead of it I want to get a default response "I am sorry but I did not understand that."
Is there a way I can handle this. I tried with lowconfidence adapter, but in that case, it always returns "I am sorry but I did not understand that." as a response even though my custom adapters are able to process the statement.

This is the verbose logs when I use lowconfidence adapter
```
INFO:chatterbot.adapters:Received input statement: Hello
INFO:chatterbot.adapters:"Hello" is a known statement
INFO:chatterbot.adapters:Not processing the statement using CustomAdapter1
INFO:chatterbot.adapters:CustomAdapter2 selected "Hello" as a response with a confidence of 0
INFO:chatterbot.adapters:Not processing the statement using CustomAdapter3
INFO:chatterbot.adapters:LowConfidenceAdapter selected "I am sorry, but I do not understand." as a response with a confidence of 0
INFO:chatterbot.adapters:NoKnowledgeAdapter selected "Hello" as a response with a confidence of 0
INFO:chatterbot.chatterbot:Adding "Hello" as a response to "I am sorry, but I do not understand."
```
I am not getting how can I handle this.

**Comment by vkosuri** [comment]
You could write like this

```Python
from chatterbot import ChatBot
import my_custom_adapter
import pdb
chatbot = ChatBot(
    "Terminal bot",
    logic_adapters=[{
            "import_path" : "my_custom_adapter.MyCustomAdater1"
        },
        {
            "import_path" : "my_custom_adapter.MyCustomAdater2"
        },
        {
            "import_path" : "my_custom_adapter.MyCustomAdater3"
        }
    ]
)

print("Hello I am Terminal bot")

while True:
    try:
        input_text = input("Enter your name: ")   # Python 3 builtlin function read input from standard input stream
        response = chatbot.get_response(input_text)
        if response.confidence == 0:
            print("I am sorry, but I do not understand.")

    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

**Comment by sinscary** [comment]
No that didn't seem to work. Even my adapter is returning confidence as 1. when I do response.confidence it's always 0.

**Comment by vkosuri** [comment]
I didn't understand your statements

> when I do response.confidence it's always 0.

What i understood above statements response.confidences is always "0" then your problem solved right?

**Comment by sinscary** [comment]
What I meant was, if my adapter able to process the statement, it should return confidence as 1. But I am getting it 0. I have checked in logs, it says 
`
CustomAdapter2 selected "Hello" as a response with a confidence of 1
`
But I am getting 0 when I do response.confidence for a valid statement. I don't understand where I am going wrong.

**Comment by sinscary** [comment]
Thanks, @vkosuri for the help.

**Comment by sinscary** [comment]
@vkosuri I have one more doubt. Say two of my adapters are able to process the statement and they both return the response with confidence 1. In such case, chatterbot picks up a random response and returns it. What I want is return all the responses in such case. I looked at custom output adapter documentation but it's not clear. Can you tell me if that's possible with the chatterbot. If yes how can I do that?

**Comment by vkosuri** [comment]
@sinscary I am not sure, may be you could overwrite your selected ``logic adapter`` process method.

For example if you are using best match adapter, https://github.com/gunthercox/ChatterBot/blob/c777b98d51d413c8fa662cdee90476ffdcb2cd5e/chatterbot/adapters/logic/base_match.py#L5

over ride process methods what origianl method going to return https://github.com/gunthercox/ChatterBot/blob/c777b98d51d413c8fa662cdee90476ffdcb2cd5e/chatterbot/adapters/logic/base_match.py#L71
