### ISSUE TITLE
django admin

### ISSUE THREAD

**Issue by jynjyn** [gunthercox/ChatterBot#1125]
I have a question, lets say if I add a new Statement and Response, how do I update the training files (eg. ai.yml) or database from whatever i edited in Django admin ? Is there a command or do i have to do something ? Thanks!
![image](https://user-images.githubusercontent.com/34668754/34139338-295a5f5e-e4af-11e7-824b-f0c6b7dab7d6.png)

**Comment by vkosuri** [comment]
As per my knoweldge currently this feature didn't support chatterbot other Django admin, What you are looking feature to achieve through this repository no ETA to complete https://github.com/gunthercox/DialogDataStudio
