### ISSUE TITLE
Get response function

### ISSUE THREAD

**Issue by DaCodaHUB** [gunthercox/ChatterBot#1132]
I read your code a bit and it seems like in this function you let the bot learn from user's response. However, it doesn't seem to work in my test. I probably don't understand it enough. How did you test it? How can I see it in action?

**Comment by vkosuri** [comment]
Try this example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py#L10

Try to enable logging mechanism, you will get to know how bot learning response and how logic adapters are working, etc.

https://github.com/gunthercox/ChatterBot/blob/d5540e1429100ecea854e8b5a8c51b1d35b3e9ad/examples/learning_feedback_example.py#L10
