### ISSUE TITLE
Error on Django 2.0

### ISSUE THREAD

**Issue by johnnogent** [gunthercox/ChatterBot#1135]
Hello,

when I launch Django I hav the following error
'Specifying a namespace in include()without providing an app_name
django.core.exceptions.ImproperlyConfigured: Specifying a namespace() in include() without providing an app_name....
...
...

This is an issue with chatterbot url.

How can I fix it please?

Many thanks

**Comment by gunthercox** [comment]
Are you using version 2.0 of Django?

**Comment by johnnogent** [comment]
Hi Gunter, yes I am. Thanks

**Comment by gunthercox** [comment]
ChatterBot hasn't been updated to use Django 2.0 yet. For 2.0, a small change needs to be made to ChatterBot's url files to include the `app_name` variable.

**Comment by johnnogent** [comment]
Many thanks I installed 1.11 and this works now. John
