### ISSUE TITLE
Issue with getting bestmatch statement

### ISSUE THREAD

**Issue by MuhammadAnas410** [gunthercox/ChatterBot#1136]
hi

This is what i trained.
``` YAML
- - Photoshop
  - Here is the link to Photoshop 123
- - Excel
  - Hey I see you need help with Microsoft Excel please click on the following link Etc
- - Math
  - Hey I see you need help with Math please click on the following link Etc
- - Graphic
  - Hey I see you need help with Graphic please click on the following link Etc
- - Music
  - Hey I see you need help with Music please click on the following link Etc
- - Coding
  - Hey I see you need help with Coding please click on the following link Etc
```

Here is my logic adapter.

``` Python
'logic_adapters':[
        {
            "import_path": "chatterbot.logic.BestMatch",
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
            "response_selection_method": "chatterbot.response_selection.get_first_response"
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': "I didn't understand that question; do you need help with Math, Excel, Music or Graphic?"
        },
    ],
    'filters': [
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
    'django_app_name': 'django_chatterbot',
    'use_django_models': True,
    'read_only': True
```

1.1)Me: I need help with math
     Bot: I didn't understand that question; do you need help with Math, Excel, Music or Graphic?

1.2)Me: Math
     Bot:Hey I see you need help with Math please click on the following link Etc

1.3)Me:I need help with coding
     Bot: I didn't understand that question; do you need help with Math, Excel, Music or Graphic?

However in 1.3 "coding" keyword is trained so why it responses i didn't understand.

Thanks

**Comment by vkosuri** [comment]
This is because LowConfidenceAdapterthre threshold as 0.65, the  levenshtein_distance algorithm calculated between ``I need help with coding`` and ``coding`` is 0.40

**Comment by MuhammadAnas410** [comment]
1.1)Me: I need help with math
Bot: I didn't understand that question; do you need help with Math, Excel, Music or Graphic?

why it response this, although it is also in statement.

it should response Hey "I see you need help with Math please click on the following link Etc"

**Comment by vkosuri** [comment]
I think it is very similar issue https://github.com/gunthercox/ChatterBot/issues/1137

**Comment by MuhammadAnas410** [comment]
Please help me to sort out this issue ?
what should i do ?
