### ISSUE TITLE
pymongo.errors.OperationFailure: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.

### ISSUE THREAD

**Issue by anurag-arora** [gunthercox/ChatterBot#1138]
I have trained my bot with Ubuntu Dialog Corpus for 1 day, and after running i am receiving this error
**pymongo.errors.OperationFailure: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.**
Please look into this and tell me if it is possible to work around this issue.
I have terminated the training as it was taking too much time and **chatterbot-database** size is around **0.390GB** .

**Comment by vkosuri** [comment]
I am not sure this is a bug, because we already declared a warning message to Ubuntu Dialog Corpus http://chatterbot.readthedocs.io/en/stable/training.html#training-with-the-ubuntu-dialog-corpus

In order to fix this you have use ``allowDiskUse`` to ``true`` in below specified file, I will create PR for this issue

https://github.com/gunthercox/ChatterBot/blob/2cef1ce9c1853fa7c5466b4a150b5c752b3f2abc/chatterbot/storage/mongodb.py#L368

```Python
response_query = self.statements.aggregate(
    [
        {
            '$group': {
                '_id': '$in_response_to.text'
            }
        }
    ],
    {
        'allowDiskUse': true
    }
)
```

**Comment by vkosuri** [comment]
Source https://docs.mongodb.com/manual/reference/method/db.collection.aggregate/#perform-large-sort-operation-with-external-sort

**Comment by anurag-arora** [comment]
Hello @vkosuri,

There is a small error in your solution, it will be `'allowDiskUse': True` instead of `'allowDiskUse': true`. As it was throwing **NameError: name 'true' is not defined**.

After running my previous issue has been resolved but **another issue** has been arised. If you will add this code to even a small training database or even without Ubuntu Dialog Corpus. it is not working.
Type something to begin...
hi
```
Traceback (most recent call last):
  File "cbot.py", line 26, in <module>
    bot_input = chatterbot.get_response(None)
  File "/usr/local/lib/python3.4/dist-packages/chatterbot/chatterbot.py", line 113, in get_response
    statement, response = self.generate_response(input_statement, conversation_id)
  File "/usr/local/lib/python3.4/dist-packages/chatterbot/chatterbot.py", line 132, in generate_response
    response = self.logic.process(input_statement)
  File "/usr/local/lib/python3.4/dist-packages/chatterbot/logic/multi_adapter.py", line 52, in process
    output = adapter.process(statement)
  File "/usr/local/lib/python3.4/dist-packages/chatterbot/logic/best_match.py", line 54, in process
    closest_match = self.get(input_statement)
  File "/usr/local/lib/python3.4/dist-packages/chatterbot/logic/best_match.py", line 16, in get
    statement_list = self.chatbot.storage.get_response_statements()
  File "/usr/local/lib/python3.4/dist-packages/chatterbot/storage/mongodb.py", line 377, in get_response_statements
    'allowDiskUse': True
  File "/usr/local/lib/python3.4/dist-packages/pymongo/collection.py", line 2181, in aggregate
    **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pymongo/collection.py", line 2088, in _aggregate
    client=self.__database.client)
  File "/usr/local/lib/python3.4/dist-packages/pymongo/pool.py", line 464, in command
    self.validate_session(client, session)
  File "/usr/local/lib/python3.4/dist-packages/pymongo/pool.py", line 609, in validate_session
    if session._client is not client:
AttributeError: 'dict' object has no attribute '_client'
```
PS: This is a very cool framework for creating a ChatBot. I would like to continue working on this as it is very flexible for creating our own adapters and manipulating it.
As soon as customers engage with our bot our database will increase with time. So i am just testing if it will work for large database.

**Comment by anurag-arora** [comment]
I think i have figured out how to solve this

`response_query = self.statements.aggregate(
	[
		 {
		        '$group': {
		                '_id': '$in_response_to.text'
		            }
		 }
	 ],
       allowDiskUse= True
)`
Reference: https://stackoverflow.com/questions/27272699/cant-get-allowdiskusetrue-to-work-with-pymongo#answer-27273358

But now finally I am getting this issue

`pymongo.errors.DocumentTooLarge: BSON document too large (119687233 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.`

I know it can be solved via GridFS, but thats needs to be implemented on your library right?

**Comment by gtzinos** [comment]
Could you please give me a feedback?

**Comment by kyle-sorensen** [comment]
Don't have to necessarily use GridFs BSON raw data is compressed before insertion into MongoDB
