### ISSUE TITLE
pymongo.errors.DocumentTooLarge: BSON document too large - the connected server supports BSON document sizes up to 16777216 bytes.

### ISSUE THREAD

**Issue by abhayhayarancedcoss** [gunthercox/ChatterBot#1140]
I've been using ChatterBot since last week, it was woking perfectly. But yesterday when i tried to train my bot with a larger dataset, then it started showing this issue. Does your library support only BSON document sizes up to 16777216 bytes? What if in future when my databases increases and BSON file extends 16MB. My bot will stop working because your library does not support multiple chunks of BSON file or even GridFS proposed by MongoDB.

**Comment by silverstar194** [comment]
I found a workaround by taking a sample  from database.

In mongodb.py line 368 change line to:
```
response_query = self.statements.aggregate([{ "$sample": { "size": 200000 }}, {'$group': {'_id': '$in_response_to.text'}} ], allowDiskUse=True)
```
