### ISSUE TITLE
How to store database file at different location

### ISSUE THREAD

**Issue by PoojaPatel05** [gunthercox/ChatterBot#1160]
``` Python
            chatbot = ChatBot(
                 "Terminal",
                  storage_adapter="chatterbot.storage.DjangoStorageAdapter",
                  input_adapter="chatterbot.input.TerminalAdapter",
                 output_adapter="chatterbot.output.TerminalAdapter",
                 database="../database",
             )
```
I want to store this database file in different (another) location. how to do that? I have tried all possible ways, But I am fail to do that.

**Comment by vkosuri** [comment]
I hope some workaround I googled will work for you https://stackoverflow.com/a/7431385/358458

**Comment by PoojaPatel05** [comment]
But I am not using any Git Apis or App. There is no settings.py.
I think I have to change something in above code only,

**Comment by gunthercox** [comment]
If you are using the `DjangoStorageAdapter` there is likely a `settings.py` file for your Django project. This file may have been automatically generated by Django itself but it should be fairly easy to find. I'd recommend looking at the `DATABASES` variable in `settings.py`, this is where Django looks to get the database location.

For example, the following is how one might define a path to a sqlite file in Django's settings.

```
# settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```

**Comment by PoojaPatel05** [comment]
Done!! Thank you so much for your support.
