### ISSUE TITLE
Dropping support for Python 2.7

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1163]
The ChatterBot 0.8.x series will be the last version of ChatterBot to support Python 2.7.
The 0.9.x series for ChatterBot will only support Python 3.

This change is intended to do the following:

1. Increase the maintainability of this project by eliminating the need to support features and quirks of older versions of Python.
2. Enforce the benefits of using Python 3.
2. Support a [trend of Python projects](http://www.python3statement.org) dropping support for 2.7

***

**Pull request to do list***

- [x] Remove `__future__` imports
- [x] Remove Python 2.7 from `.travis.yml`
- [x] Remove `input_function` from `utils.py` and update anything that uses it to just use the Python `input` function.
- [x] Remove any `sys.version_info` checks.
- [x] A number of string `encode` calls should be safe to remove.

**Comment by hugovk** [comment]
👍 

See also http://www.python3statement.org.

---

Here's the pip installs for ChatterBot from PyPI for December, 63% for Python 3:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 3.6            |   40.6% |          1,577 |
| 2.7            |   36.9% |          1,435 |
| 3.5            |   16.9% |            658 |
| 3.4            |    4.7% |            183 |
| 3.7            |    0.7% |             29 |
| 2.6            |    0.1% |              4 |
| 3.2            |    0.1% |              2 |
| 3.3            |    0.0% |              1 |

Source: `pypinfo --start-date -51 --end-date -21 --percent --pip --markdown ChatterBot pyversion`
