### ISSUE TITLE
Python with HTML for Django Example

### ISSUE THREAD

**Issue by engrphil** [gunthercox/ChatterBot#1166]
I am quite new to Python and I had to start learn it because chatterbot is based on Python.

I have setup django and run the example on the localhost server successfully. However, I am challenges integrating python into html view. I have the chatbot written in python and works fine in terminal but I am not sure how to integrate it with the html view in django. Does anyone has any working example? I will greatly appreciate it.

Thank you.

**Comment by vkosuri** [comment]
Chatterbot has inbuilt djanog example, you could found here https://github.com/gunthercox/ChatterBot/tree/master/examples/django_app
