### ISSUE TITLE
Statement matching query does not exist in Django example

### ISSUE THREAD

**Issue by kalentang** [gunthercox/ChatterBot#1167]
hello,
I run the django_app example by default, it works well.
But when I add some logic adapters to the config at the django_app settings.py, it is not work when I ask "what time is it?", the other greetings questions still can work.

the error message is:
  File "C:\Users\xx\AppData\Local\Programs\Python\Python36\lib\site-packages\django\db\
9, in get
    self.model._meta.object_name
chatterbot.ext.django_chatterbot.models.DoesNotExist: Statement matching query does not exist.

my environment:
python 3.6.5
django 1.11
chatterbot 0.8.1 or 0.8.2

the django_app settings.py as below:

CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'logic_adapters': [
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter',
        'chatterbot.logic.BestMatch'
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        'chatterbot.corpus.english.greetings'
    ],
    'django_app_name': 'django_chatterbot'
}

is there any other code need to update?
Thank you.

**Comment by gunthercox** [comment]
I'm not certain why it isn't responding with the time for you. I'll mark this as a possible bug.

**Comment by gunthercox** [comment]
I'm going to close this off. I was never able to recreate this issue, and I suspect that it has been fixed in some of the recent changes to ChatterBot.
