### ISSUE TITLE
How to get an answer through api

### ISSUE THREAD

**Issue by PoojaPatel05** [gunthercox/ChatterBot#1169]
I want to create an API to get an answer.
```Python
print("Type your question here...")
while True:
    try:
        chatbot_input = chatbot.get_response(None)
    # Press ctrl-c or ctrl-d to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```
instead of above code I want to create an api to get answer of entered question

**Comment by gunthercox** [comment]
I'd highly recommend taking a look at either the Django example that comes with ChatterBot (although it has a chat interface, it also has an API): https://github.com/gunthercox/ChatterBot/tree/master/examples/django_app

@chamkank also has a great example of using ChatterBot with Flask https://github.com/chamkank/flask-chatterbot
