### ISSUE TITLE
speed of response is really slow is there any way that i could improve its efficiency in replying speed

### ISSUE THREAD

**Issue by edwinjose900** [gunthercox/ChatterBot#1171]
there is a delay in the response of the chat bot

**Comment by Truth0906** [comment]
Me too

**Comment by zxsimple** [comment]
@edwinjose900 @Truth0906 did you 1). use mongodb storage, 2). installed python-Levenshtein.

see whether https://github.com/gunthercox/ChatterBot/pull/1158 help.

**Comment by Truth0906** [comment]
So I see the pull request has been merged.
I just need to `sudo pip3 install chatterbot --upgrade` to apply update?

**Comment by gunthercox** [comment]
@Truth0906 Yup, the changes from that that pull request have been released to PyPi so you're clear to upgrade. :+1:

**Comment by Truth0906** [comment]
@gunthercox 
Hi I aleady 1). use mongodb storage, 2). installed python-Levenshtein
And I upgraded chatterbot to 0.8.4, and I retrain 43 MB data

It still take hours.

Is my data too big?

Here is my setting

```
Bot = ChatBot(
    'PTTDeeplearningVillager',
    trainer='chatterbot.trainers.ListTrainer',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=[
        "chatterbot.logic.BestMatch"
    ],
    filters=[
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    database='chatterbot-database'
)
```
And I train like this

`Bot.train([Question, Answer])`

**Comment by gunthercox** [comment]
@Truth0906 The quantity of data being trained with definitely could be playing a factor. How many questions / answer combinations are you training with?

**Comment by Truth0906** [comment]
@gunthercox 
About 70000 questions / answer

**Comment by edwinjose900** [comment]
@gunthercox  can you post that program that u used to train 7000questions 
and did you put 7000 questions inside Bot.train([Question, Answer])
so u put 7000 questions and answers consecutively in bot.train()?

**Comment by Truth0906** [comment]
@edwinjose900 Do you mean me?

**Comment by edwinjose900** [comment]
anyone is fine

**Comment by edwinjose900** [comment]
i think i got it.but still facing installing mongo db in opensuse

**Comment by gunthercox** [comment]
I'm going to close this off as a duplicate of one of the many other "slow" tickets. I'm aware of the issue and I'm incrementally making changes intended to improve the overall performance and development experience of ChatterBot.

**Comment by saucyy90** [comment]
Can somebody help me on the same issue . The bot is taking too much time to respond. I have not fed even 1000 questions/answers but its lazy in answering . If i upgrade to latest version of chatBot it will not run as (this is the issue i faced during the intial set up of this program, i had to degrade it to 0.7.4 ). 
Please advise
