### ISSUE TITLE
Add option to disable training progress output

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1177]
This will keep test output cleaner and it will also speed them up because the console wont need to buffer the standard output.

**Comment by vkosuri** [comment]
Master, How about separating training process and bot instance process. 

I mean train in separate file and bot instance in a separate file because chatterbot training process persist chat data in a separate file? Does it make sense?

**Comment by gunthercox** [comment]
That can definitely be done. I'm not sure if that would prevent the training progress indicators from printing during tests though.

**Comment by vkosuri** [comment]
🥇
