### ISSUE TITLE
Add option for storing conversations

### ISSUE THREAD

**Issue by kevinyst** [gunthercox/ChatterBot#1179]
The _read_only_ option is very limited. I want the bot to store new conversations, but do not learn from new inputs. This is useful to keep the database clean and maintain consistency in responses.

**The options could be something like:**
_learn_from_conversation="False"
store_conversations="True"_

Rather than just: _read_only="True"_

If you have a quick workaround to this, please let me know.

**Comment by gunthercox** [comment]
I've been considering adding something very similar to what you're describing. I'll mark this as a feature request.
