### ISSUE TITLE
Add class documentation

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#118]
At the moment, there is no documentation for each class. I suggest that we add a "quote block" (I can't remember the official name for the triple-quote comment) immediately before each class which describes exactly what the class's function is, how it accomplishes whatever it does, author, etc.

I believe this will become very important to help keep track of what each class does once we get complex logic adapters implemented. For instance, I am writing a logic adapter for a developer assistant. This class will become very complex over time as additional features are implemented, and a summary of how it works will help potential developers understand the code.

@gunthercox What do you think?

**Comment by The-Penultimate-Defenestrator** [comment]
The official name is "docstring"

**Comment by gunthercox** [comment]
Internally documenting code as well as descriptive variable names are always a good idea.

**Comment by DarkmatterVale** [comment]
I will work on this and send a PR when I'm done.

**Comment by gunthercox** [comment]
I believe this has been accomplished by #119.

**Comment by DarkmatterVale** [comment]
Yes, thank you.
