### ISSUE TITLE
How to add an Emoji pickup tray to chatterbot?

### ISSUE THREAD

**Issue by ghost** [gunthercox/ChatterBot#1182]
Please help me out.

**Comment by gunthercox** [comment]
Sure. I'm not really sure what an emoji pickup tray is (I'm guessing it's like a popup keyboard or something). Do you have an example?

**Comment by Utpal69** [comment]
Yes.. adding emoji support to chatbot understands emoji and gives a response based on it...
There is an emoji package for python. I am wondering how to train my bot to understand emoji and give a logical response to it..

**Comment by vkosuri** [comment]
This might help you 

https://github.com/gunthercox/ChatterBot/blob/ade3b228d97fd587116b0d23ecc738c9c47c0c8a/tests/test_chatbot.py#L92

https://github.com/gunthercox/ChatterBot/blob/ade3b228d97fd587116b0d23ecc738c9c47c0c8a/tests/training_tests/test_list_training.py#L123

**Comment by gunthercox** [comment]
An emoji is just a character to the chat bot, so you can train it with emoji characters and the desired responses you want your bot to give for each one. I can provide a code-example if needed, but you pretty much can stick to the format shown in the training docs http://chatterbot.readthedocs.io/en/latest/training.html
