### ISSUE TITLE
why i got error with non ascii words?

### ISSUE THREAD

**Issue by devM4x** [gunthercox/ChatterBot#1195]
i have vk_api for connection and your chatterbot to answer users and learning.

vk json returns array with body like this:  

``` Python
 {u'body': u'\u041f\u0440\u0438\u0432\u0435\u0442 \u0425\u0430\u0431\u0440!',
   u'date': 1491934479,
   u'id': 7386,
   u'out': 0,
   u'read_state': 0,
   u'title': u' ... ',
   u'user_id': 23107592}]}
```
it's in array but when i put it in bot response it crashes all time 

``` Python
  question = msg.encode('ascii', 'ignore').decode('ascii')

    def answerUser(self, question):
        return self.chatbot.get_response(question)
```

**Comment by vkosuri** [comment]
@devM4x Just curiosity may i know fallow things

1. how your training data look like?
2. stack trace of the crash?
3. chatterbot version?

**Comment by devM4x** [comment]
sorry, problem is in returned json from vk it body i just can't convert to normal string cyrillic and chatterbot (i think) don't understand it and return empty and everything crashes

**Comment by gunthercox** [comment]
Hi @devM4x, I just had a chance to glance over your code. If you are using Python 2.7 I would highly recommend switching to Python 3 so you can use Unicode string directly.
