### ISSUE TITLE
Cant import my own custom logic adapter 

### ISSUE THREAD

**Issue by lws803** [gunthercox/ChatterBot#1196]
Hi, I've created a custom logic adapter with class "getYoutube" and I've placed the .py file in the directory of my virtual environment running the chatbot. I've also include import_path in the main chatterbot script but it cant seem to find the module. Throwing me an error that there's no module of that name.

**Comment by vkosuri** [comment]
@lws803 could you provide fallowing details?
1. chatterbot config?
2. chatterbot version?
3. Error stack trace?
