### ISSUE TITLE
Train with multiple questions/responses

### ISSUE THREAD

**Issue by john-bonachon** [gunthercox/ChatterBot#1198]
Say you want to train a bot with ListTrainer, but feed it with a real conversation. You may have,

A> Hi monkey
B> hahahah
B> you mean donkey
B> what about Brenda? Did she went to the party?
A> what party?
A> ahhh
A> yes

Should I just concatenate both parties' lines into a single each time? Would it confuse NLP?

**Comment by gunthercox** [comment]
Hi @john-bonachon this sounds very similar to #429. Unfortunately this isn't a function that is currently supported (although it might be in the future).

One way to achieve this currently might be to concatenate a newline character between the consecutive sentences, for example:

A> `Hi monkey`
B> `hahahah\nyou mean donkey\nwhat about Brenda? Did she went to the party?`
A> `what party?\nahhh\nyes`
