### ISSUE TITLE
Removing the utils.import_module function

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1201]
I originally added the `utils.import_module` function as a way to conveniently import and dynamically initialize classes that the `ChatBot` class would initialize. I've noticed a trend of confusion around this and I'm wondering if removing this function and requiring classes to be imported and used directly would solve the problem.

I'd like to get some feedback and comments from developers who are actively using ChatterBot before in make any changes.

***

To illustrate an example of what would happen, here is an example.

**Current**

```python
from chatterbot import ChatBot

bot = ChatBot(
    "Terminal",
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    logic_adapters=[
        "chatterbot.logic.MathematicalEvaluation",
        "chatterbot.logic.TimeLogicAdapter",
        "chatterbot.logic.BestMatch"
    ]
)
```

**Proposed**

```python
from chatterbot import ChatBot
from chatterbot.storage import SQLStorageAdapter
from chatterbot.logic import MathematicalEvaluation, TimeLogicAdapter, BestMatch

bot = ChatBot(
    "Terminal",
    storage_adapter=SQLStorageAdapter,
    logic_adapters=[
        MathematicalEvaluation,
        TimeLogicAdapter,
        BestMatch
    ]
)
```

***

My goal is only to alleviate possible points of confusion. I am more than willing to accept alternate proposals for ways to achieve this.

**Comment by vkosuri** [comment]
👍 💯

**Comment by gunthercox** [comment]
I'm going to close this ticket off. I am no longer planning to make this change.
