### ISSUE TITLE
Prompt for input if ChatterBot's low confidence level is below a threshold?

### ISSUE THREAD

**Issue by merkader69** [gunthercox/ChatterBot#1204]
I apologize if this is a frustratingly stupid question, it's been a hot minute since I've been able to use ChatterBot, but as I'm about to try to use it again, I was wondering if it would be possible for chatterbot, when chatting with a user and the low confidence threshold is below a certain point, if it would be possible for the bot to prompt the author and ask for input and then learn it based off what the author puts in? Thank you # #

**Comment by vkosuri** [comment]
@merkader69 Not problem, 

See this example this might give an overview of somewhat close related to you https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_new_response.py

You could tweak above example, into your requirement Each response object has confidence, you could make use.

``` Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot

# Create a new chat bot named Charlie
chatbot = ChatBot(
    'Charlie',
    trainer='chatterbot.trainers.ListTrainer'
)

chatbot.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

# Get a response to the input text 'How are you?'
response = chatbot.get_response('I would like to book a flight.')

print(response)
if response.confidence >= 0.65:
   proceed_further_def()
```

**Comment by merkader69** [comment]
perfect, thank you sir!
