### ISSUE TITLE
ImportError: cannot import name 'chatbot'

### ISSUE THREAD

**Issue by Stratuholic** [gunthercox/ChatterBot#1205]
Got this:
>>> from chatterbot import chatbot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'chatbot'

**Comment by Stratuholic** [comment]
I'm using python 3.6.2. The problem occured on my friend's computer, too.

**Comment by vkosuri** [comment]
Did you installed chatterbot from ``pip install -U chatterbot`` or git cloned version

If yes, which version of chatterbot are you using , to know ``python -m chatterbot --version``

**Comment by jipiyan** [comment]
The class name is ChatBot not chatbot

**Comment by Stratuholic** [comment]
Thanks. Solved.

**Comment by mikegustafson101** [comment]
I'm having this issue to. I copy/pasted 'pip install chatterbot' from git, then attempted to run python -m chatterbot --version but I still get cannot import name ChatBot. Tried the test document to see if things are working and still the same error. I have a fresh install of linux, but I don't see any dependencies so I don't think Im missing anything.  Any thoughts on this would be appreciated.

**Comment by vkosuri** [comment]
@mikegustafson101 ``pip install chatterbot`` did you got any errors?

**Comment by mikegustafson101** [comment]
I'll have to reboot into linux to doublecheck, but Im 99% sure it installed correctly, and that's why I thought it was confusing that I couldn't even get the test script to run.
