### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'confidence'

### ISSUE THREAD

**Issue by ravaga** [gunthercox/ChatterBot#1208]
Im trying to set up a custom logic adapter, but somehow im getting
`AttributeError: 'int' object has no attribute 'confidence'`
im following the exact example provided on the docs.. could someone point out what im doing wrong..

This is my return of the def process function on my logic adapter

        if response.status_code == 200:
            confidence = 1
        else:
            confidence = 0

        info = data.get('data', 'unavailable')

        response_statement = Statement('The current info is {}'.format(info))
        return confidence, response_statement

**Comment by ravaga** [comment]
Nevermind.. i figured out... 
```
response_statement = Statement('The current info is {}'.format(info))
response_statement.confidence = confidence
return response_statement
```

**Comment by vkosuri** [comment]
@ravaga glad to figured it out :)
