### ISSUE TITLE
how to create autocomplete chatterbot....

### ISSUE THREAD

**Issue by ashisheric** [gunthercox/ChatterBot#1210]
autocomplete chatterbot more useful thah normal chatterbot...

**Comment by vkosuri** [comment]
I think you are looking something similar to this https://stackoverflow.com/a/7821956/358458?

If so implement this in chatterbot preprocessors http://chatterbot.readthedocs.io/en/stable/preprocessors.html

**Comment by ashisheric** [comment]
@vkosuri Thanks for your input but still I have facing issue to implementing "autocomplete chatterbot"

**Comment by vkosuri** [comment]
what kind of problems you were facing?

**Comment by ashisheric** [comment]
I have used modules 'preprocessors':[
		'chatterbot.preprocessors.clean_whitespace',
		'chatterbot.preprocessors.unescape_html',
		'chatterbot.preprocessors.convert_to_ascii'
    ],
but still no any autocomplete....

**Comment by gunthercox** [comment]
Hi @ashisheric depending on the type of content that you want to implement auto complete for, you might be able to use one of Google's api's to get auto complete results for strings of text.

https://stackoverflow.com/questions/6428502/google-search-autocomplete-api

***

If you're looking to build you own auto-completion service, then you might be able to search around and probably find a few existing examples for reference.
