### ISSUE TITLE
Not able to install chatterbot at conda (python3.5)

### ISSUE THREAD

**Issue by rafa1985** [gunthercox/ChatterBot#1213]
I have tried to install chatterbot with pip install chatterbot at:

-window7 64bit
-anaconda with spyder(Python 3.5)

Someone knows the problem?

Thanks
![chatbot](https://user-images.githubusercontent.com/27998435/36480988-a409eabc-170e-11e8-83aa-e6c1a4a4b582.jpg)

**Comment by gunthercox** [comment]
It looks like the error is occurring in an anaconda email feedparser module. Are you sure this is an issue related to ChatterBot?

**Comment by rafa1985** [comment]
I am not sure but It should be a problema of ChatterBot with conda (python 3.5) .... someone has chatterbot with conda (python 3.5)?

**Comment by gunthercox** [comment]
I've also received reports about issues with `spyder` and `ChatterBot` in the past. I'm not extremely versed in Conda but pull requests are welcome if you or anyone else knows of a solution.

For use with ChatterBot I highly recommend installing the normal Python installation instead www.python.org.

**Comment by riteshk28** [comment]
Not sure if you guys have resolved the issue, however, I faced the same error and by upgrading my pip I was able to install chatterbot with no issues.

python -m pip install --upgrade pip
pip install chatterbot

**Comment by sachinmotwani20** [comment]
Tried but failed yet again.
