### ISSUE TITLE
Chatterbot responding very slowly if I have too many files in my corpus

### ISSUE THREAD

**Issue by noufali** [gunthercox/ChatterBot#1218]
Hey! 

Awesome project. Sooo chatterbot works perfectly if my corpus contains files with short length conversations (similar to what you have in the examples). 

I then tested it with files containing facebook conversations I have had throughout the years and it works....but it runs super slowly. It will basically give me a response after a minute of "thinking".. Is it something I'm doing? or can it not handle that magnitude of files?

I'm training it with the list trainer as such: 
``` Python
files = os.listdir("corpus/")
for f in files:
    data = open('corpus/' + f,'r').readlines()
    nouf.train(
        data
    )
```
Thank you!

**Comment by faraazc** [comment]
+1

@gunthercox I observing the same issue. The response time is increasing as the statement sets grow and also the length of the statement text increases.

The bot is really good. But do you have any suggestion or best practices for performance gains, mainly in improving in response time?

**Comment by gunthercox** [comment]
I've introduced additional filtering in https://github.com/gunthercox/ChatterBot/tree/1.0.0a1, https://github.com/gunthercox/ChatterBot/tree/1.0.0a2, and https://github.com/gunthercox/ChatterBot/tree/1.0.0a3 that decreases the size of the result set before a response if processed.

These changes improve the response time significantly for large data sets. I'm going to continue work to improve the overall response time, but I think this ticket should be safe to close off. Please let me know if you have any questions.
