### ISSUE TITLE
How to define TwitterTrain language?

### ISSUE THREAD

**Issue by outlaw6** [gunthercox/ChatterBot#1219]
Can someone show the code how to use the TwitterTrain class with parameters for seed word and language. Or maybe just the language. I dont get it. I was trying something
``bot.set_trainer(TwitterTrain(lang='cs'))``

but it doesnt work. I also tried to google it , but no luck.
Basically Ive got a bot thats working, except that I cant define the language from Twitter to learn from.

Thank you.

**Comment by gunthercox** [comment]
Admittedly this is not the most obvious way to do this, but

```python
chatbot = ChatBot(
    # ...
    twitter_lang='cs',
    trainer='chatterbot.trainers.TwitterTrainer'
)
```
