### ISSUE TITLE
 I want to clear the memory of the ChatterBota

### ISSUE THREAD

**Issue by Gfifius** [gunthercox/ChatterBot#1221]
I want to clear the memory of the robot from what he learned from unsuccessful corps.
 How to do it?

**Comment by vkosuri** [comment]
Did you tried this example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_new_response.py

**Comment by gunthercox** [comment]
By "clear the memory" do you mean that you want to delete the content stored in the chat bot's database?

**Comment by Gfifius** [comment]
I deleted the old case, made a new one. but the answers from the bot come from the old one, which is not in the folder. I understood that his training is somewhere saved, but I could not find where

**Comment by Gfifius** [comment]
besides, he began to respond very long

**Comment by gunthercox** [comment]
Assuming you are using the default SQL storage configuration, there should be a `.sqlite3` file that was created relative to the location of your code. Deleting this file will delete all of the learned content.

**Comment by Gfifius** [comment]
yes, this is what I needed, many thanks
