### ISSUE TITLE
unable to get chatterbot version

### ISSUE THREAD

**Issue by xtaraim** [gunthercox/ChatterBot#1224]
`VERSION = CHATTERBOT.__version__`
not  defined

**Comment by vkosuri** [comment]
could try like this ``python -m chatterbot --version``

**Comment by gunthercox** [comment]
@xtaraim Where did you import `CHATTERBOT` from?

**Comment by xtaraim** [comment]
Import sklearn faces problems

**Comment by gunthercox** [comment]
@xtaraim I apologise, but I don't seem to understand. Could you please provide more information about the problem?

**Comment by xtaraim** [comment]
Issues to import sklearn

**Comment by xtaraim** [comment]
Sorry I busy on another project 
Issues is how to defined VERSION = CHATTERBOT.__version__ 
It's not working

**Comment by gunthercox** [comment]
Try the following instead.

```python
import chatterbot

VERSION = chatterbot.__version__
```

**Comment by xtaraim** [comment]
Okk i will be try it

**Comment by vkosuri** [comment]
that sounds good
