### ISSUE TITLE
Context Handle

### ISSUE THREAD

**Issue by Selvaganapathi06** [gunthercox/ChatterBot#1225]
Can you please explain how handle contexts?. if user reply something after bot response based on user reply.  please explain.

**Comment by vkosuri** [comment]
duplicate see https://github.com/gunthercox/ChatterBot/issues/1229, https://github.com/gunthercox/ChatterBot/issues/812#issuecomment-312465690

**Comment by Selvaganapathi06** [comment]
Still, i am not clear on context handling.

bot.train([
"i want to check my account balance",
"in which account",
"Savings account",
"50000",
"i want to deposit ",
"how much you want to deposit in Savings account",
])
bot.train([
"i want to check my account balance",
"in which account",
"checking account",
"70000",
"i want to deposit ",
"how much you want to deposit in checking account "
])

If the user asks about savings account, bots response should be based on  savings account.

Next time, If the user asks about checking account, bots response should be based on  checking account.

how to handle context in this scenario. Is there any other solution for this?
