### ISSUE TITLE
Chatbot error when response is UTF-8

### ISSUE THREAD

**Issue by cryptax** [gunthercox/ChatterBot#1227]
I am training chatbot in French, so with some accents. Unfortunately, chatbot does not like to answer with such sentences and replies an error. I tried to encode the response in UTF-8 but didn't work better:
 
```python
unicode(str(chatbot.get_response(command)),"utf-8")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 28: ordinal not in range(128)
```

How to handle "weird" characters with chatbot?

**Comment by cryptax** [comment]
I found how to do it myself. This was rather a [Python Unicode problem](https://docs.python.org/2.7/howto/unicode.html#the-unicode-type) than anything else.

This will print out the string properly:
```python
 response = chatbot.get_response(command).text.encode('utf-8')
```

**Comment by vkosuri** [comment]
Did you tried all these string encoding techniques http://chatterbot.readthedocs.io/en/stable/encoding.html?highlight=unicode#python-string-encoding?
