### ISSUE TITLE
Improvement of LowConfidenceAdapter

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#1231]
Assume we have 3 adapters: BestMatchAdapter, CustomAdapter, LowConfidenceAdapter (threshold=0.65)

Confidence of each adapter:
BestMatchAdapter: 0.2
CustomAdapter: 0.9
LowConfidenceAdapter: 1

In here LowConfidenceAdapter response will be selected since BestMatchAdapter confidence is lower than threshold value, but actually the bot should select CustomAdapter response since it has the highest confidence among all Adapter except BestMatchAdapter

**Comment by vkosuri** [comment]
Thanks, Pull requests are welcome :+1:

**Comment by gunthercox** [comment]
The `LowConfidenceAdapter` can be tuned using the `threshold` parameter that it accepts. You could set the threshold of the `LowConfidenceAdapter` to a lower value, 0.5 for example to help more accurately confident adapters overtake it.
