### ISSUE TITLE
Can I send query and get response only from http? like I want integrate this to JAVA Android or iOS applications

### ISSUE THREAD

**Issue by 2666fff** [gunthercox/ChatterBot#1233]
i had test this on python platform,its doing good. And I'm a mobile applicaiton developer are there any api for lite integrating? I can do this in a commerce way.

simply like i send a query to the server, and receive a response. Only normal conversation, no commerce purpose.

``` Bash
>>> print(chatbot.get_response("Hello, how are you today?"))
I am doing well.
>>> print(chatbot.get_response("im going home"))
That is good to hear
>>> print(chatbot.get_response("Do you know JIXIANGGE?"))
hal is the famous artificial intelligence from "2001".
>>> print(chatbot.get_response("who am i?"))
Who? Who is but a form following the function of what
>>> print(chatbot.get_response("nice talking to you"))
Thank you.
```

**Comment by vkosuri** [comment]
Yes you could, I don't know how to do in Java, I do provide some examples on Python based 

On Django http://chatterbot.readthedocs.io/en/stable/django/index.html

On Flask https://github.com/chamkank/flask-chatterbot

On Heroku https://github.com/vkosuri/chatterbot-live-example
