### ISSUE TITLE
default database.db gives KeyError: 'in_response_to'

### ISSUE THREAD

**Issue by roxxup** [gunthercox/ChatterBot#124]
Traceback (most recent call last):
  File "speech.py", line 77, in <module>
    chatvoice(chatbot.get_response(takeString))
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 67, in get_response
    existing_statement = self.storage.find(input_statement.text)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/storage/jsondatabase.py", line 29, in find
    response_list = self.deserialize_responses(values["in_response_to"])
KeyError: 'in_response_to'

**Comment by gunthercox** [comment]
@DarkmatterVale Looks like this involves the speech adapter. Any thoughts on what might be causing it?

**Comment by DarkmatterVale** [comment]
The speech adapter that I currently have implemented is in the file "tts.py". I believe he has created a custom wrapper on top of the default implementation, but I cannot be sure unless I can see the code.

@roxxup What version of ChatterBot are you using? Newest? Also, maybe you could provide us with the database you are having issues with?

Thanks!

**Comment by roxxup** [comment]
@DarkmatterVale Thanks for giving me suggestions .

**Comment by gunthercox** [comment]
I'm closing this off as I believe this has been resolved.
