### ISSUE TITLE
Need to add a sentiment también in training 

### ISSUE THREAD

**Issue by Ardumania** [gunthercox/ChatterBot#1243]
Can I use the "add_extra_data" method in training?. I'm working on a robot that can simulate emotions and I need to add a sentiment tag to every statement.
In the documentation there is no example of how to use that method. 
Can you give me an example of use? 
And, how can I add that tag in training?

**Comment by vkosuri** [comment]
Did you tried using category tag, I think this example will give some idea on how to write a category example https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/ai.yml

**Comment by gunthercox** [comment]
ChatterBot now supports the ability to add tags to any statement.

For example:
```
statement.add_tags('sentiment:POS:0.8')
```

The `filter` method on the storage adapter can also be used to search for statements that have a given tag.
