### ISSUE TITLE
issue in chatterbot or chatterbot_corpus installation

### ISSUE THREAD

**Issue by atulanandnitt** [gunthercox/ChatterBot#1246]
Neither
pip install --upgrade chatterbot_corpus    nor
pip install --upgrade chatterbot
is working for me.

I am using:
Python 3.6.3 :: Anaconda custom (64-bit)
in windows 7.

**Comment by atulanandnitt** [comment]
both 
pip3 install --upgrade chatterbot_corpus    and
pip3 install --upgrade chatterbot
worked.
Mentioning here rather than deleting the post.To help others.

**Comment by vkosuri** [comment]
sure :+1:
