### ISSUE TITLE
Is it possible to use mysql/postgresql as storage adapter for chatterbot?

### ISSUE THREAD

**Issue by prathibha** [gunthercox/ChatterBot#1247]
I've tried the following

database_uri = "mysql://username:password@127.0.0.1/db_chatterbot"

but its creating only sqlite db.

Tried with postgres also.

**Comment by Reddaa** [comment]
Yes if fact there is a part of the document telling exactly how.
http://chatterbot.readthedocs.io/en/stable/storage/index.html#sql-storage-adapter

**Comment by vkosuri** [comment]
@prathibha I think it's default actions, did you faced any issues

**Comment by tnmurthy** [comment]
does this apply for MongoDB as well?

**Comment by vkosuri** [comment]
@tnmurthy are you looking MongoDB storage adapter, if so http://chatterbot.readthedocs.io/en/stable/storage/index.html#mongodb-storage-adapter

**Comment by prabhat428** [comment]
@tnmurthy yes you can see it here.
https://chatterbot.readthedocs.io/en/stable/storage/index.html#mongodb-storage-adapter

**Comment by ignertic** [comment]
what about for mysql

**Comment by prabhat428** [comment]
Hi Gunthercox/Chatterbot
  yes surely , you can use mysql for chatbot
