### ISSUE TITLE
MySQL Connection - Schema error

### ISSUE THREAD

**Issue by itsmehemant123** [gunthercox/ChatterBot#1248]
I'm trying to use MySQL as the database. I've set the correct attributes, and when I run the bot, I get this error:

```
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

sqlalchemy.exc.CompileError: (in table 'tag', column 'name'): VARCHAR requires a length on dialect mysql
```

Server version: 5.7.21-0ubuntu0.16.04.1 (Ubuntu)
SQLAlchemy (1.2.5)
ChatterBot (0.8.4)
chatterbot-corpus (1.1.1)
discord.py (0.16.12)

**Comment by gunthercox** [comment]
I believe this was fixed by #1200. @itsmehemant123 I haven't released a package update containing the fix yet. I'm planning on releasing version 0.8.5 within the next few days wich will include the fix.

**Comment by gunthercox** [comment]
The new version was released. Apologies about the the delay.

**Comment by itsmehemant123** [comment]
Super! Thanks for the great work @gunthercox !
