### ISSUE TITLE
how Can I develop flow based chatbot & mcq type questions using chatterbot

### ISSUE THREAD

**Issue by DhruvMevada** [gunthercox/ChatterBot#1249]
1. how to create mcq type question in chatterbot?

2. I want a sequential flow based chatbot like:
   hows you mood?
   1 -> good
   2. ->sad
If user type 1 then it will go to another flow question and if user select 2 then it will go to another question.

**Comment by vkosuri** [comment]
Rightnow there is no implementation such type features, You could write your own training adapter and possible logic adapters.

These resource will guide how to write those

- http://chatterbot.readthedocs.io/en/stable/training.html#creating-a-new-training-class
- http://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html

**Comment by DhruvMevada** [comment]
OK thanks @vkosuri
