### ISSUE TITLE
Any examples for social commerce chatbots?

### ISSUE THREAD

**Issue by taewookim** [gunthercox/ChatterBot#1250]
Not an issue.. but i am looking for examples of how social commerce chatbots are trained + deployed... particularly in non-English languages. Simple tasks such as answering FAQ and taking orders.

Can anyone shed some light? Perhaps to something on the web somewhere?

**Comment by vkosuri** [comment]
I don't find any example on other languages, may be you could use these example train with your wish language

- https://github.com/gunthercox/django_chatterbot
- https://github.com/chamkank/flask-chatterbot
- https://github.com/vkosuri/chatterbot-live-example

**Comment by vkosuri** [comment]
@taewookim i am closing this, please feel free to reopen if you have any questions.
