### ISSUE TITLE
Weird database records (text column not updates)

### ISSUE THREAD

**Issue by MrDini123** [gunthercox/ChatterBot#1251]
Hi,

I have just installed this amazing project and tried to set up a basic chatbot. I am using this for initialization:

```py
chatbot = ChatBot("TestBot",
                                trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
                                storage_adapter="chatterbot.storage.SQLStorageAdapter",
                                output_adapter="chatterbot.output.OutputAdapter",
                                output_format='text',
                                database='./database.sqlite3')
```

Now, the `chatbot.get_response('message')` works, but it looks like duplicating in the database... The input never refreshes. Is it a bug, or I am doing something wrong?

![multiplies](https://user-images.githubusercontent.com/16760748/37557577-e218a6a8-2a06-11e8-93f6-f361efc7b8b6.png)

Thanks

**Comment by vkosuri** [comment]
The logic adapter compares input statement with other statements http://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#how-logic-adapters-select-a-response

> A typical logic adapter designed to return a response to an input statement will use two main steps to do this. The first step involves searching the database for a known statement that matches or closely matches the input statement. Once a match is selected, the second step involves selecting a known response to the selected match. Frequently, there will be a number of existing statements that are responses to the known match.

Could try with other adapters http://chatterbot.readthedocs.io/en/stable/logic/multi-logic-adapter.html

**Comment by MrDini123** [comment]
I don't think it is a logic adapter issue, because I got _What is Baseball_ when I typed in _TELL ME ABOUT BASEBALL_ and when I asked _Good question... What is baseball?_, I actually got _A game played with a hard, rawhide covered ball and wooden bat by two opposing teams of nine or ten players each. It is played on a field with four bases forming a diamond-shaped circuit._. That is great. But as you Can see, all the other responses are saved to the first bot response after initialization, and that was _I am still young by your standards._ .

It is always saves records attached to the first bot response. But while chatting, it returns the good input...
