### ISSUE TITLE
Training via List Data vs Training with Corpus Data

### ISSUE THREAD

**Issue by engramar** [gunthercox/ChatterBot#1252]
Hello Guys, 

I started looking at Chatterbot and I am very amazed on how easy it is to activate the chatbot and train it on the fly using list data. However, I noticed there is an option to train via corpus data as well so I have some questions. 

1. Can I just stick on using list data for training as I find it very handy?
2. There seems to be a 'category' when training using bespoke corpus data. Can I also set the category when using list data?

Please let me know of your thoughts. Cheers and thanks in advance!

_Related reading: http://chatterbot.readthedocs.io/en/stable/training.html#set-trainer_

Regards,
Engramar

**Comment by gunthercox** [comment]
Hi @engramar, there is no way to set categories when using the list trainer.

**Comment by engramar** [comment]
@gunthercox thanks mate for finding time to respond. will keep it in mind. i like training via list data approach as i can just provide prospective users an option to just upload their own training data from their side via a web page. thanks again and enjoy the rest of the weekend.
