### ISSUE TITLE
How to include hyperlinks in chatterbot response in django html page?

### ISSUE THREAD

**Issue by GowthamSB** [gunthercox/ChatterBot#1253]

**Comment by myc2dc** [comment]
In the createRow function within the app.html file, you can change `$row.text(text)` into `$row.html(text)`.  The `text` variable can have the a tags within it, and the response will display as a hyperlink.

**Comment by vkosuri** [comment]
https://github.com/gunthercox/ChatterBot/blob/9e36b35fd681bef497cbbee3bd9918753bd79053/examples/django_app/example_app/templates/app.html#L69
