### ISSUE TITLE
How to externally set the threshold of low confidence adapter

### ISSUE THREAD

**Issue by sarthakmahapatra9** [gunthercox/ChatterBot#1254]
What I want to do is, if the confidence level of the bot is less than 0.9 then I will reply the user with a default response as given in the statement attribute of low confidence adapter. But a supervisor will be able  to see the real response of the bot where the low confidence adapter threshold will be greater than or equal to 0.6. So how can I get the response of the bot by externally setting the low confidence adapter threshold value??

**Comment by vkosuri** [comment]
I think you might looking this http://chatterbot.readthedocs.io/en/stable/logic/index.html#low-confidence-response-adapter
