### ISSUE TITLE
accommodate low confidence adapter default response

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#1257]
The [Low confidence adapter works](https://chatterbot.readthedocs.io/en/stable/logic/index.html#low-confidence-response-adapter) as expected when a user configured with some threshold value and default response. The response correctly filtering out.

The problems is here if a response falls under specified threshold value, the low confidence adapter **default response** didn't updated in the conversation instead it returning an empty value like below

``` JSON
{"conversation": [], "detail": "You should make a POST request to this endpoint.", "name": "ChatterBot"},
```

To reproduce this issue, you may use below configuration in Django training
``` Python
CHATTERBOT = {
    'logic_adapters' : [
        {
            'import_path': "chatterbot.logic.BestMatch"
        },
        {
        'import_path': 'chatterbot.logic.LowConfidenceAdapter',
        'threshold': 0.5,
        'default_response': 'You can ask other question'
        }
    ]
}
```

**Comment by vkosuri** [comment]
@gunthercox Thanks master, updated, let me know still unclear parts are there

**Comment by gunthercox** [comment]
@vkosuri Do you know if this will still be an issue in the latest version?

**Comment by vkosuri** [comment]
@gunthercox Not yet verified, I think this might get fixed. For time being will close this JIRA, If it found will reopen this issue.
