### ISSUE TITLE
replies only hello, doesn't responds to typing

### ISSUE THREAD

**Issue by kunalwanikar** [gunthercox/ChatterBot#1259]
![screenshot 51](https://user-images.githubusercontent.com/29946239/37842707-d906728e-2ee8-11e8-8e13-c2795848bb15.png)
here when i copy the content from corpus it gives me correct reply, but when i type the exact sentence or type anything it replies only hello... help me

**Comment by vkosuri** [comment]
I think that's depends on how comparison methods you are configured, try to use JaccardSimilarity http://chatterbot.readthedocs.io/en/stable/comparisons.html#chatterbot.comparisons.JaccardSimilarity

**Comment by kunalwanikar** [comment]
sir,
      actually used the same as in project :
https://github.com/gunthercox/Chatterbot/tree/master/examples/django_app .
I m not getting what's going wrong. can you please help me out with it?

**Comment by kunalwanikar** [comment]
basically whatever you type in "type here box" it responds with hello.. can you please help me

**Comment by vkosuri** [comment]
http://chatterbot.readthedocs.io/en/stable/django/training.html
