### ISSUE TITLE
Best way to delete a response from the database

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [gunthercox/ChatterBot#126]
Is there an easy way to delete a response from a Mongo database? Say, for example, I have a public bot, and someone enters an inappropriate response I'd like to delete.

**Comment by gunthercox** [comment]
Currently, no. You would have to manually remove it.

This seems like a reasonable problem. I will leave this ticket open until I have a chance to add a method to address it.

**Comment by The-Penultimate-Defenestrator** [comment]
Great, thanks.

**Comment by gunthercox** [comment]
@The-Penultimate-Defenestrator https://github.com/gunthercox/ChatterBot/pull/130 Adds a method for removing statements. It will be included in the next release.

**Comment by The-Penultimate-Defenestrator** [comment]
Great, thanks a lot! I'll take a look
