### ISSUE TITLE
Doesn't respond according to trained conversation.

### ISSUE THREAD

**Issue by ShaguftaMethwani** [gunthercox/ChatterBot#1262]
I have a chatbot created with Chatterbot, it is supposed to help people with issues.
I have a custom corpus as follows.

``` Python
{
    "conversations": [
        [
            "Q1",
            "a1. worked?",
            "yes",
            "Great!"
        ],
        [
            "Q1",
            "a1. worked?",
            "no",
            "_sad. try a2. worked?_",
            "yes",
            "great!"
        ],
        [
            "Q1",
            "a1. worked?",
            "no",
            "_sad. try a2. worked?_",
            "no",
            "**try a3, if it doesnt work please get in touch with ABC"**
        ]
       
    ]
}
```

The problem is that the conversation never reaches the bold answer. the italicised one is repeated again and again and again. As long as the user keeps typing No. How to make this work. Is there any other alternative aproach for if-else/condition based responses?

**Comment by vkosuri** [comment]
@ShaguftaMethwani Did you tried this example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py, I think you are looking something closer to this with some modifications to your requirement

**Comment by gunthercox** [comment]
This issue has been open without a response for quite some time. I'm going to close it off. Please let me know or open a new issue if this question was not completely answered or resolved.
