### ISSUE TITLE
 ModuleNotFoundError: No module named 'settings'

### ISSUE THREAD

**Issue by bluesky632** [gunthercox/ChatterBot#1264]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-19-8c6969593791> in <module>()
      1 from chatterbot import ChatBot
----> 2 from settings import GITTER

ModuleNotFoundError: No module named 'settings

**Comment by gunthercox** [comment]
You have to create a file called `settings.py` and put a dictionary in it called `GITTER`. Your values will look different, but here is an example of what it should look like.

Be sure to replace `xxx` with a valid Gitter API access token for your account.
In this example, `chatter_bot/test_room` is the Gitter room designation.

```
GITTER = {
    'API_TOKEN': 'xxx',
    'ROOM': 'chatter_bot/test_room'
}
```
