### ISSUE TITLE
New Beginner

### ISSUE THREAD

**Issue by WarrenCloud** [gunthercox/ChatterBot#1265]
I am new here for this. Might I know anyone can let me know what steps and platform need to setup after the sample code is fownloaded? Thanks

**Comment by vkosuri** [comment]
These things will give some basic idea how to use chatterbot

### Basic Tutorials

1. Training process http://chatterbot.readthedocs.io/en/stable/training.html
2. Logic adapters http://chatterbot.readthedocs.io/en/stable/logic/index.html
3. Storage adapters http://chatterbot.readthedocs.io/en/stable/storage/index.html

### Examples
After some reading go through these examples https://github.com/gunthercox/ChatterBot/tree/master/examples

### Integration
Try these integration

1. Django http://chatterbot.readthedocs.io/en/stable/django/index.html
2. flask https://github.com/chamkank/flask-chatterbot

### Cloud applications
This example will give an idea how to deploy your application on to Heorku cloud https://github.com/vkosuri/chatterbot-live-example
