### ISSUE TITLE
How can i use different data to train chatterbot for each time?

### ISSUE THREAD

**Issue by talatccan** [gunthercox/ChatterBot#1266]
Hi, thanks for this amazing project.

Im wondering that, how can i use different data to train chatterbot for each time?

In this case, user will choose train data and chatterbot will be trained with choosen data. What is best way to do that? Can you suggest me something?

My chatterbot working with django.

**Comment by vkosuri** [comment]
Write your own training class, go through this http://chatterbot.readthedocs.io/en/stable/training.html#creating-a-new-training-class

An example https://github.com/gunthercox/ChatterBot/blob/9e36b35fd681bef497cbbee3bd9918753bd79053/chatterbot/trainers.py#L171

**Comment by vkosuri** [comment]
@talatccan I am closing this issue, please fell free to reopen if you have any questions.
