### ISSUE TITLE
Merge MultiAdapter code into the ChatBot class

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1267]
I originally created the MultiAdapter class because ChatterBot supported using only a single LogicAdapter at a time. The MultiAdapter was a simple way to introduce the feature without breaking backwards compatibility.

**This reason for the MultiAdapter to exist _isn't_ obvious and it has lead to confusion in a number of cases.**

Just one example https://stackoverflow.com/a/48352509/1547223
(There is also a number of closed GitHub issues that share a similar theme)

At this point, I'd like to do some refactoring and make the MultiAdapter code a part of the main ChatBot class. I think this will improve the understandability of the code and eliminate this point of confusion.

**Comment by GowthamSB** [comment]
how to install version 0.9....when i do pip install chatterbot it installs the previous version

**Comment by vkosuri** [comment]
@GowthamSB the current version of chatterbot is https://github.com/gunthercox/ChatterBot/releases/tag/0.8.4

All release found here https://github.com/gunthercox/ChatterBot/releases
