### ISSUE TITLE
If   I load a big .yml file ,I want to know that If I can train it once ,then I saved it ,I input a question ,I  can get a responce quickly.

### ISSUE THREAD

**Issue by wenjiahua** [gunthercox/ChatterBot#1271]

**Comment by vkosuri** [comment]
Hope that I am expecting. You have separate training and bot process that way you can save training process.

**Comment by mcseml** [comment]
我的chatterbot训练了9万条记录，回答一次要10秒，很难用的机器。

My chatterbot trained 90, 000 records to answer for 10 seconds at a time，Difficult machine to use.

**Comment by flyfy** [comment]
90K knowledge entry? Wow, I think you should make the training set more dedicated and granular into a few subsets, or a few categories and then train each set using a separate trainer, that will make it much faster for the machine to "search" for an optimal match with best accuracy and speed, by the way, how accurate it is when you get the result? Do you think it is a good result to you?

**Comment by gunthercox** [comment]
As of ChatterBot version 0.8.x, 90,000 records will not allow a response to be returned in optimal time.
