### ISSUE TITLE
NoKnowledgeAdapter always return message with confidence=1

### ISSUE THREAD

**Issue by tomliau33** [gunthercox/ChatterBot#1273]
I created ChatterBot instance in read-only mode with a customized logic adapter, but I found that the default adapter NoKnowledgeAdapter always return message with confidence=1, and then the message returned from my logic adapter always be skipped because of NoKnowledgeAdapter has higher priority.

Is it possible to disable NoKnowledgeAdapter when I create a ChatterBot object?

**Comment by gunthercox** [comment]
It is not currently possible to disable the NoKnowledgeAdapter. Have you made sure that you chat bot has been trained? The NoKnowledgeAdapter will only return a confidence of 1 if there is no responses for the chat bot to reply with.

**Comment by tomliau33** [comment]
I have my own model, I implemented a logic adapter which store trained data in my own table, so the statement table was empty. Since NoKnowledgeAdapter would return confidence=1 if self.chatbot.storage.count() == 0, so my own logic adapter would be ignore even it return a response with confidence==1.

**Comment by tomliau33** [comment]
I have my own model, I implemented a logic adapter which store trained data in my own table, so the statement table was empty. Since NoKnowledgeAdapter would return confidence=1 if self.chatbot.storage.count() == 0, so my own logic adapter would be ignore even it return a response with confidence==1.
If it is possible, I hope that I can pass a default adapter to replace NoKnowledgeAdapter when I new a ChatBot object. 
Ex: 
chatbot = ChatBot(default_logic_adapter=MyOwnDefaultLogicAdapter)

**Comment by tomliau33** [comment]
I have my own model, I implemented a logic adapter which store trained data in my own table, so the statement table was empty. Since NoKnowledgeAdapter would return confidence=1 if self.chatbot.storage.count() == 0, so my own logic adapter would be ignore even it return a response with confidence==1.

If it is possible, I hope that I can pass a default adapter to replace NoKnowledgeAdapter when I new a ChatBot object.

Ex:
chatbot = ChatBot(default_logic_adapter=MyOwnDefaultLogicAdapter())

**Comment by vkosuri** [comment]
Just curios, Could you please let me know what are the use case your trying achieving using above scenario?

**Comment by tomliau33** [comment]
I use ChatterBot as the engine to implement a questionnaire survey bot. The bot will ask question to user, and then user response their answer. User's answers are privacy, others should not have chance to know the answer, so it is better to prevent chatbot reply those message, I disabled to store message and keep statement table as empty.

**Comment by vkosuri** [comment]
Just curios, how you are managing, could you please elaborate this situation with more information. I think it should be a separate usecase or feature that needs to separate user based conversations.

I think this can achieved by using conversation_id http://chatterbot.readthedocs.io/en/stable/conversations.html#conversation-scope? did you tried this method, instead disabled training process.

@gunthercox Master, do you have any comments?

**Comment by gunthercox** [comment]
@tomliau33 I'm glad to see that you created your own model, that's awesome!

I think I can make a small code change that will make it easier for you to disable the `NoKnowledgeAdapter` since you don't need it for your project. Just opened a pull request with the changes: #1296

**Comment by tomliau33** [comment]
That's awesome. 
Thank you very much!

**Comment by tomliau33** [comment]
PR #1296 can solve this issue.
Thank you!
