### ISSUE TITLE
Help with conversations

### ISSUE THREAD

**Issue by ajwsert** [gunthercox/ChatterBot#1275]
I have been trying to use Chatterbot to setup an AI for a Discord bot and it has been working reasonably. However, I suppose the bot would need to talk with several people at once then it would need to keep track of each conversation somehow.

I have noticed that [_get_response_](https://chatterbot.readthedocs.io/en/stable/_modules/chatterbot/chatterbot.html#ChatBot.get_response) has a `conversation_id` parameter but I haven't been able to get it working. If I pass like a Number to it I get errors. I went to look up for some doc and the only thing I could find is an example for Django in [here](https://chatterbot.readthedocs.io/en/stable/conversations.html#conversation-example) but my implementation is going to use SQLite. I have been having trouble to adapt it and I don't have any `django` libs installed (I don't even need them).

How could I use the `conversation` feature with the SQLite and inputs coming from a script?

Thanks in advance and sorry if doing it in the wrong place.

**Comment by vkosuri** [comment]
I think you have to handle conversation ids to solve your problem, I am not sure this is the solution for you, i think this could be a workaround fro you https://github.com/gunthercox/ChatterBot/blob/9e36b35fd681bef497cbbee3bd9918753bd79053/examples/learning_new_response.py#L21

**Comment by ajwsert** [comment]
Thanks for the reply. Yes, I had seen about that function but I still can't understand properly how it works and I have some doubts.

Is that ID (and conversation stuff) stored in the database somewhere? If so, is there a way to retrieve it again? I haven't found any function/way to retrieve conversation IDs, only that one to create it, so I realize I should store the ID in a variable/session or something, but what when the bot is restarted? Would I need to create new IDs and supposedly leave litters in the database?

I'm ok with starting over after a restart (after all the previous conversation would be over with a restart) but I'm afraid about having useless data stored in the database.

Let me know if I'm not being clear here.

P.S.: I think I see it now, maybe I should store the created IDs persistently in the database or somewhere else and implement a way to retrieve those myself.

**Comment by gunthercox** [comment]
@ajwsert Sorry about these issues that you ran into. I'm working to make changes that will remove the concept of a conversation_id entirely. The next version of ChatterBot will use a `conversation` label (an attribute of each statement) to indicate the conversation that each statement is a part of. This eliminates the need to create new conversations while still making it possible to differentiate the conversation that a statement is a part of.
