### ISSUE TITLE
Theading?

### ISSUE THREAD

**Issue by MoonGem** [gunthercox/ChatterBot#1276]
Curious if threading/multiprocessing would be in the works anytime soon.

**Comment by vkosuri** [comment]
Threading isn't safe, some past issues talks about threading

https://github.com/gunthercox/ChatterBot/issues/110#issuecomment-175009154
https://github.com/gunthercox/ChatterBot/pull/317
https://github.com/gunthercox/ChatterBot/issues/604#issuecomment-275274552

**Comment by MoonGem** [comment]
I got you, but well, there's possibility of threading something say like, mongodb and the weight calculation on the items maybe by dividing the entries in the database by the number of cores you have? Seems doable.

Also:
![GitHub Logo](https://cdn.discordapp.com/attachments/184324186284621824/437306830084112404/photo_2018-04-21_12-41-00.jpg)

**Comment by MoonGem** [comment]
I THINK I might have a solution, but could use some external input:
Before I run off an make PRs all over the place:

```
        for statement in statement_list:
            confidence = self.compare_statements(input_statement, statement)

            if confidence > closest_match.confidence:
                statement.confidence = confidence
                closest_match = statement

        return closest_match
```
LN 34-42

https://github.com/gunthercox/ChatterBot/blob/9e36b35fd681bef497cbbee3bd9918753bd79053/chatterbot/logic/best_match.py#L35


Could this be edited as such:

```
        from multiprocessing import Pool,cpu_count
        
        for statement in statement_list:
            def Matcher(self, input, state):
                confidence = self.compare_statements(input, state)
                if confidence > closest_match.confidence:
                    statement.confidence = confidence
                    closest_match = statement
                    return closest_match
            p = Pool(cpu_count())
            res = p.map(Matcher, (self, input_statement, statement,))
        if res not None:
            return res
```


Is it possible to pass self to Multiprocessing pool?

**Comment by MoonGem** [comment]
Actually...... To be fair, this thing is far fast enough already. I'm going to close this. I imported 25% of a 200K-sentence chatlog and the responses are very fast.
