### ISSUE TITLE
how do I use Microsoft Bot Framework Input/Output Adapter?

### ISSUE THREAD

**Issue by earcearce16** [gunthercox/ChatterBot#1279]
I have my Microsoft Bot Framework set-up with the proper channels. Now I would like to integrate my python script to the Microsoft Bot Framework. I have looked around but have not found anything. I have my access token.

Where would I find "directline_host", "conversation_id"?

Here is the sample code:
```
#from chatterbot import ChatBot

#'''
#See the Microsoft DirectLine api documentation for how to get a user access token.
https://docs.botframework.com/en-us/restapi/directline/
'''

#chatbot = ChatBot(
    'MicrosoftBot',
    directline_host='directline_host',
    direct_line_token_or_secret='token',
    conversation_id='conversation_id',
    input_adapter='chatterbot.input.Microsoft',
    output_adapter='chatterbot.output.Microsoft',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)

chatbot.train('chatterbot.corpus.english')

# The following loop will execute each time the user enters input
while True:
    try:
        response = chatbot.get_response(None)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

**Comment by vkosuri** [comment]
I think it was written on Directline1.1 which is very old version, that is the reason i may not work with latest, needs to upgrade it Directlin 3.3 API https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-concepts

**Comment by vkosuri** [comment]
I have created a separate issue https://github.com/gunthercox/ChatterBot/issues/1285
