### ISSUE TITLE
Use Chinese Corpus

### ISSUE THREAD

**Issue by Goooaaal** [gunthercox/ChatterBot#1280]
How to use the Chinese Training Library in the project and use it？
I know that I want to import the Chinese corpus and I do it, but I can't ask questions in Chinese why？
It looks like I've trained
![_15247249497616](https://user-images.githubusercontent.com/33569679/39289799-1cfedcd8-4960-11e8-9fdf-6e9da81c6b5a.png)
![_15247248987930](https://user-images.githubusercontent.com/33569679/39289819-275c2424-4960-11e8-8cc7-1d48687c77eb.png)

@tentamen @rmdort @yangl @gsingers @emijrp # ****

**Comment by vkosuri** [comment]
@Goooaaal which version of chatterbot are you using? I this issue was fixed in latest release. Try to upgrade to latest one ``pip install --upgrade chatterbot``

**Comment by gunthercox** [comment]
@Goooaaal If you are using Python 2 you might want to upgrade to Python 3 for better unicode support.

You can check your python version by running `python --version` in your terminal.

**Comment by gunthercox** [comment]
@Goooaaal Looking at he stack trace you posted, I'm fairly certain that you have a syntax error in your code. You likely need to wrap the text indicated in the error message with quotation marks.
For example: `u'your-text'`
