### ISSUE TITLE
Simple way of data migration to mongodb

### ISSUE THREAD

**Issue by lws803** [gunthercox/ChatterBot#1288]
Hi, is there a simple way of migrating data from sqlite to mongodb? I've tried exporting it as csv but I realised that data stored in monogodb is a little different (entries and all are stored a little differently). 

Thanks!

**Comment by gunthercox** [comment]
You could export your data from your sqlite chat bot as a training corpus:
http://chatterbot.readthedocs.io/en/stable/corpus.html#exporting-your-chat-bot-s-database-as-a-training-corpus

and then after switching to Mongo DB, train the chat bot with it again.

**Comment by lws803** [comment]
Hmm wont work too cause my data contains emojis. I wrote a script that reads the csv and then use chatbot.learn_response to learn every single row of the response and text.

**Comment by gunthercox** [comment]
Strange, it should work with emojis. If you are getting an error message feel free to post it, it might be a bug.

**Comment by lws803** [comment]
Hmm this was the error that came out: 

```
'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x009f: special characters are not allowed
```

**Comment by vkosuri** [comment]
@lws803 can you try it from python3 for better handle of unicodes

**Comment by lws803** [comment]
Just tried it, works really well. There's a way to utf strip too if there are any unknown characters for some reason
