### ISSUE TITLE
At what rate does the Chatterbot increases the confidence level on an answer?

### ISSUE THREAD

**Issue by sarthakmahapatra9** [gunthercox/ChatterBot#1292]
I need to understand how does the chatterbot improves or  builds the confidence on an answer and at what rate? I have been asking the same question more than 15 times and checking it's confidence on the answer, but it is always the same. I am doing something like this ( a pseudo code because I cannot share the real code here) -
if response.confidence <= 0.90 then 
     reply saying "we are working on it"
else
      reply the response

but even after asking the same question more than 15 times it is still replying "we are working on it". Is there a way to increase the rate of learning programmatically?

**Comment by gunthercox** [comment]
The rate is typically based on the percent similarity between the input statement and a known statement, then the response that the chat bot returns from the selection of similar statements is based on the occurrence frequency of the response where the number of occurrences is the number of times that the bot has received the response to a statement it returned.
