### ISSUE TITLE
for any input bot gives output as ('bot', 'No possible replies could be determined.')

### ISSUE THREAD

**Issue by PaarthBatra** [gunthercox/ChatterBot#13]
from chatterbot import Terminal
terminal = Terminal()
terminal.log_directory="D:/python_logs/chatterbot/conversation_engrams"
terminal.begin()

and for any input i just get No possible replies could be determined. How to fix this ?

hi
('bot', 'No possible replies could be determined.')
how r u ?
('bot', 'No possible replies could be determined.')

**Comment by PaarthBatra** [comment]
I have done some edit suggestions in the document . Please have a look . This is first time i am working on a open source project , Please let me know if i do something wrongly .

**Comment by gunthercox** [comment]
Awesome, sorry for the late reply. I've read over the additions and left a few comments in the document. Let me know what you think. I'm hoping to finish up the changes for the database pull request sometime in the next few days. Once its finished I think we should be good to finalize the knowledge-base training plan. I've also added you as a project contributor, you should now have push access to this repository which will be useful if you're interested in making additions to the code base.

**Comment by gunthercox** [comment]
Sorry, didn't mean to close this.

**Comment by gunthercox** [comment]
This has been fixed by the changes made in https://github.com/gunthercox/ChatterBot/pull/27
