### ISSUE TITLE
cannot import name chatbot from chatterbot line 3

### ISSUE THREAD

**Issue by yojan95** [gunthercox/ChatterBot#1301]
`# -*- coding: utf-8 -*-

from chatterbot import Chatbot

bot = Chatbot(
       "brayan",
storage_adapter="chatterbot.storage.SQLSstorageaAdapter",
logic_adapter={
     "chatterbot.logic.bestmach",
     "chatterbot.logic.timeLogicAdapter",
     "chatterbot.logic.mathematicalEvaluation"
},
input_adapter="chatterbot.input.TerminalAdapter",
output_adapter="chatterbot.output.TerminalAdapter",
database="./brayan"

)

while True:
    boti = bot.get_response(none)
`

**Comment by vkosuri** [comment]
It's ChatBot not Chatbot

``` Python
# Create a new chat bot named Charlie
chatbot = ChatBot(
    'Charlie',
    trainer='chatterbot.trainers.ListTrainer'
)
```

For more options see example section https://github.com/gunthercox/ChatterBot/tree/master/examples

**Comment by gunthercox** [comment]
@yojan95 That error message likely means that you don't have sqlalchemy installed.

Please install ChatterBot using the following command:

```
pip install chatterbot --upgrade
```
