### ISSUE TITLE
Can't launch an instance of chatterbot after training

### ISSUE THREAD

**Issue by bannedghost** [gunthercox/ChatterBot#1306]
So the problem is like this
I used one of the examples for training
then I quit the terminal
Now I don't want to train it at every instance
so how do I converse with the bot after I quit it?

**Comment by vkosuri** [comment]
Chatterbot training is persisted into sqlite.db file, you could separate files for training and learning, this example may give an overview how to do https://github.com/gunthercox/ChatterBot/issues/1106#issuecomment-351020080
