### ISSUE TITLE
statement.remove_response() not working

### ISSUE THREAD

**Issue by AxelAli** [gunthercox/ChatterBot#1307]
**chatterbot version 0.8.5**
I am wanting to delete a "bad response".
Wrote a new trainer to do this.

**Used**
[conversations (Documentation)](http://chatterbot.readthedocs.io/en/stable/conversations.html)

>  remove_response(response_text)
>    Removes a response from the statement’s response list based on the value of the response text.

**My trainer**
```
class SingleShotTrainer(Trainer):

    def train(self, conversation,remove=False):
        previous_statement_text = None
        for conversation_count, text in enumerate(conversation):

            statement = self.get_or_create(text)

            if previous_statement_text:
                if(remove):
                    statement.remove_response(text)
                else:
                    statement.add_response(Response(previous_statement_text))

            previous_statement_text = statement.text
            self.storage.update(statement)
```
**Main code**
```
*generic chatterbot code*

chatbot.train("hello","hi there")
chatbot.train("hello","hey there!")
chatbot.reply("hello")
>>>'hi there'
chatbot.train("hello","hey there!",True) #Calls remove_response()
chatbot.reply("hello")
>>>'hi there'
```

Im missing anything?

Thanks

**Comment by gunthercox** [comment]
@AxelAli I'm sorry for not responding until now. Recent changes to ChatterBot have removed the `remove_response` method. The project is now using a single `Statement` model to store all information related to a statement. I'm going to close this ticket off but feel free to open a new one if you have any questions about the new design.
