### ISSUE TITLE
Problem Importing Gitter

### ISSUE THREAD

**Issue by ishubhamgupta** [gunthercox/ChatterBot#1311]
#Gitter Conversation

from chatterbot import ChatBot

from settings import GITTER

---------------------------------------------------------------------------
While I'm running the following code

from settings import GITTER

All that I'm getting is......

ImportError                               Traceback (most recent call last)
<ipython-input-14-d6dc72a91c52> in <module>()
      1 
      2 from chatterbot import ChatBot
----> 3 from setting import GITTER
      4 
      5 

ImportError: No module named setting

**Comment by vkosuri** [comment]
https://github.com/gunthercox/ChatterBot/issues/1032 Need to create a file called settings.py in the same directory as the python file you are trying to run.
