### ISSUE TITLE
Connect to a source QnA database ?

### ISSUE THREAD

**Issue by Christian1980** [gunthercox/ChatterBot#1312]
Hi,
I have a database with questions and answers. A question can have multiple answers.
How can I use my database a a source for the bot to respond to users ?

Do I need to export the database to some source text file ? I can't find any sample in the doc on how to use an existing database to populate the data to the bot to chat with users.

Thanks for any advices or (better) samples...

**Comment by gunthercox** [comment]
One way to do this is to export your QA content as a `yml` file for training.

The format is describe here: http://chatterbot-corpus.readthedocs.io/en/latest/data.html

Let me know if you have any questions.
