### ISSUE TITLE
Regarding learning model used in Chatterbot

### ISSUE THREAD

**Issue by yogesh127** [gunthercox/ChatterBot#1313]
which machine learning model is used in this chatterbot for training ?

**Comment by vkosuri** [comment]
@yogesh127 https://chatterbot.readthedocs.io/en/stable/faq.html#what-kinds-of-machine-learning-does-chatterbot-use

1. [Search algorithms](https://chatterbot.readthedocs.io/en/stable/faq.html#search-algorithms)
2. [Classification algorithms](https://chatterbot.readthedocs.io/en/stable/faq.html#classification-algorithms)

curios to know what are different ML learning models are available?
