### ISSUE TITLE
Chatterbot not working properly

### ISSUE THREAD

**Issue by FathimaFirdhouse** [gunthercox/ChatterBot#1315]
Hi,

I'm trying to create a chatterbot using flask. I got it but unfortunately I face few issues.
1. I have 10 YML files, If I ask a question, the chatterbot is getting the answer from some other file and not where it should fetch, basically not answering properly
2. Secondly when I run the chatterbot for the second time, the first time question that I asked which chatterbot could not reply for the first time is stored and it is asking me back when I ask a known question.

I used the following code:

``` Python
from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.response_selection import get_first_response
from chatterbot.comparisons import levenshtein_distance
import os

app = Flask(__name__)

english_bot = ChatBot("Chatterbot", storage_adapter="chatterbot.storage.SQLStorageAdapter",
                        preprocessors=['chatterbot.preprocessors.clean_whitespace'],
				logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
            "response_selection_method": "chatterbot.response_selection.get_first_response"
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': 'I am sorry, but I do not understand.'
        } 
    ],
    trainer='chatterbot.trainers.ListTrainer'
)

english_bot.set_trainer(ListTrainer)

for files in os.listdir('../mytraining/'):
		data = open('../mytraining/' + files, 'r').readlines()
		english_bot.train(data)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(english_bot.get_response(userText))


if __name__ == "__main__":
    app.run()
Please help me as early as possible 
![not_working](https://user-images.githubusercontent.com/39655998/40579319-774fa1fa-6142-11e8-8bd3-d066c7a4f830.JPG)
```

**Comment by FathimaFirdhouse** [comment]
Please somebody help me

**Comment by vkosuri** [comment]
Did you tired this https://github.com/chamkank/flask-chatterbot repo?

sometimes chatterbot will work based on your training data, may read these documents https://chatterbot.readthedocs.io/en/stable/logic/index.html

**Comment by FathimaFirdhouse** [comment]
Yes I tried replicating the link you mentioned. I saw those theories of algorithms but I don't know how to make use of that in my chatterbot.. Currently I added levenshtein distance algorithm plug in as shown in my code.. but no great use.. what else can I do?

**Comment by FathimaFirdhouse** [comment]
My chatterbot is working somewhat fine but I have a issue, 
when I run the chatterbot for the second time, the first time question that I asked which chatterbot could not reply for the first time is stored and it is asking me back when I ask a known question.

I want to clear the SQLITE File in python itself after every response that is right after 
def get_bot_response():
    userText = request.args.get('msg')
    return str(english_bot.get_response(userText))

Can somebody help me ?

**Comment by vkosuri** [comment]
It seems you don't learn previous response, this might help you https://chatterbot.readthedocs.io/en/stable/examples.html#read-only-mode

>Read only mode

Your chat bot will learn based on each new input statement it receives. If you want to disable this learning feature after your bot has been trained, you can set read_only=True as a parameter when initializing the bot.

**Comment by FathimaFirdhouse** [comment]
Thank you for your suggestion, but when I tried giving read_only=True in my code. The bot replies just as the user. Please find the snapshot of code and the result below:
![bot_ready_only](https://user-images.githubusercontent.com/39655998/40632651-d5f4a528-6306-11e8-8343-167b21a2cde1.JPG)
![issue_read_only](https://user-images.githubusercontent.com/39655998/40632652-d62e2884-6306-11e8-9f24-767496717878.JPG)

**Comment by FathimaFirdhouse** [comment]
Please help me

**Comment by vkosuri** [comment]
I am not what happening on your end, My suggestions are

1. Try to enable logging how the response are selecting, see this example https://github.com/gunthercox/ChatterBot/blob/ebfd4be9a7a4402fbbce2399af7758c347e2f567/examples/learning_feedback_example.py#L12
2. Try to change response_selection_method to random response selection method https://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#module-chatterbot.response_selection
3. insted using your own corpus, could try to use one of existing corpus files https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data/english

Let me know your observation after this?

**Comment by FathimaFirdhouse** [comment]
Thank you so much for your help. It is working now with read_only=True instead of adding it in initialization I added it after training statement that is after bot.train(data) now it's working fine. Thank you very much.

**Comment by vkosuri** [comment]
@FathimaFirdhouse glad to hear your problem was resolved.

**Comment by gunthercox** [comment]
@FathimaFirdhouse The file format of the data (json / yaml) has no effect on the accuracy.

If you are getting different responses between use of single and multiple files I'd suggest making sure that the conversations in each file follow the correct notation for responses.

**Comment by FathimaFirdhouse** [comment]
Oh ok. Thank you so much for your response

**Comment by swathy06** [comment]
I would like to know, what is the correct notation for responses?

**Comment by vkosuri** [comment]
@swathy06 This might give an idea https://chatterbot.readthedocs.io/en/stable/conversations.html#statement-response-relationship

an example https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/greetings.yml

**Comment by shishu19** [comment]
Hi FathimaFirdhouse
Can U send Me code for your GUI what U have created for your chat bot as I am need in UI

Please Help
Thanks
