### ISSUE TITLE
NoSuchColumnError: "Could not locate column in row for column '1'"

### ISSUE THREAD

**Issue by ankurgulati** [gunthercox/ChatterBot#1316]
Hi,

I am following the exact same steps mentioned here: [](https://chatterbot.readthedocs.io/en/stable/quickstart.html)
Everything works until the last step. 
```
response = chatbot.get_response("Good morning!")
print(response)
```
I am facing the below error : 

> NoSuchColumnError:  "Could not locate column in row for column '0'"

FYI I upgraded chatterbot and sqlalchemy

**Comment by gunthercox** [comment]
Do you know what version of ChatterBot you upgraded from?

**Comment by ankurgulati** [comment]
I am not sure about previous version but in that version there was an option of JSONStorageAdapator which is missing/removed

**Comment by gunthercox** [comment]
I'm going to close this ticket off. I don't think I can solve it in a simple way.

For anyone who runs into this error, the following is the best advice I can provide at this time: ChatterBot does non include database migrations between SQL Alchemy versions. Before upgrading, be sure to back up your database and check ChatterBot's release notes to determine if new columns need to be created manually.
