### ISSUE TITLE
nodejs loop problem  not synchronize 

### ISSUE THREAD

**Issue by krishnaraj1993** [gunthercox/ChatterBot#1323]
con.query('SELECT *  from table',async function(err, rows, fields){
					rows.forEach(async function(data, index, arr) { 
						 const result = await cal_funct(json);
						 console.log(result); 
					});
			});

function cal_funct(){
//some--action
retrun 'a';
}
//============================================
it print table data after 'a'

i want result like this
table data--1
'a'
table data --2
'a'

please help me...................................................................... :)

**Comment by gunthercox** [comment]
@krishnaraj1993 Sorry for my lack of response until now. It doesn't look like anything related to ChatterBot was included in what you posted. I'm going to close this ticket off.
