### ISSUE TITLE
Chatter bot not working as expected 

### ISSUE THREAD

**Issue by prithvirajrmd2015** [gunthercox/ChatterBot#1324]
Hi im trying to use chatter bot i had given my training data below if i say 'im fine' its just executing the second line as the answer 'What can you do for me' can any one help me with this...
``` Python
chatterbot = ChatBot("Training Example")
chatterbot.set_trainer(ListTrainer)
chatterbot.train([
"hi",
"hello",
"how are you,
"im fine",
"what can you do for me",
"I can help you in bank related queries, second resp"
])
```

**Comment by vkosuri** [comment]
I think you have to [filters](https://chatterbot.readthedocs.io/en/stable/filters/index.html) or [response selection methods](https://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#module-chatterbot.response_selection) to get different responses.
