### ISSUE TITLE
 which machine learning algorithm is this chatter bot  using and how it is calculating the confidence?

### ISSUE THREAD

**Issue by jason0luck** [gunthercox/ChatterBot#1329]
many thanks:)

**Comment by gunthercox** [comment]
This page in the documentation describe the types of algorithms that are used in ChatterBot: https://chatterbot.readthedocs.io/en/stable/faq.html#what-kinds-of-machine-learning-does-chatterbot-use

The confidence scores are determined based on definitions that are specific to each logic adapter but in general, the confidence (which is the expected accuracy of the response) is based on a calculated similarity between a known response and the value that a response needs to be generated for.
