### ISSUE TITLE
How do I set the trigger request using regex?

### ISSUE THREAD

**Issue by senthilrameshjv** [gunthercox/ChatterBot#1334]
Hello,
I understand Chatterbot uses question and answer type of training , where the response from the bot is based on the request it sends to.

Although that's interesting, how can I make the response generic..

For example, the bot can handle 'Do you know Java'?

But how do I make '* Java *' to match any string with Java in it.. This is something tools like Rivescript is able to.. this is one thing I look to before deciding on which framework I start with for chatbot Dev..

**Comment by vkosuri** [comment]
@senthilrameshjv IMO using regular expression in the requests, your will see poor performance getting accurate response.

Instead did you tried different comparison methods available in chattbot https://chatterbot.readthedocs.io/en/stable/comparisons.html

**Comment by senthilrameshjv** [comment]
Thank you @vkosuri , let me check on that.
