### ISSUE TITLE
How to store value in sqlite databse and fetch data from it in chatterbot?

### ISSUE THREAD

**Issue by bhavikapanara** [gunthercox/ChatterBot#1336]
I have a query regarding storage of important attribute. for example when first-time human start to talk with a bot, then bot ask the name of human? so the question is how to store the name in the database so we can use in future.
 for example:
human: hi
bot: hi. what's your name?
human: my name is mark.
bot: nice name mark. 
human: can you talk with me.
bot: sure, mark

Please give me suggestions. How can I do to store and retrieve data?

**Comment by vkosuri** [comment]
@bhavikapanara I think this conversation will give you some basic idea what you are looking https://github.com/gunthercox/ChatterBot/issues/469#issuecomment-267481465
