### ISSUE TITLE
Chatterbot for non-english language like Arabic and Mandarian

### ISSUE THREAD

**Issue by Mukund0007** [gunthercox/ChatterBot#1339]
Hi All,
I have a requirement for making a chatbot which supports Arabic and Chinese.
My question is does chatterbot has this capability to understand Chinese and Arabic return required answer?

If not so, is there any way to create our own corpus and train my bot in above language?

Thanks and Regards,
Mukund

**Comment by vkosuri** [comment]
Yes absolutely https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data/chinese

**Comment by Mukund0007** [comment]
Thats good! I have seen but how we can customize it? I am looking for providing location assistance using some map API like google API. 
Can we make it voice enabled?
Also how can we do same in Arabic language?

**Comment by gunthercox** [comment]
@Mukund0007 I can't speak for the Google API, but I'm sure they support a variety of languages.

ChatterBot can be voice-enabled in a number of ways, depending on how you plan you build your application. For example, many browsers support built-in speech-to-text that can be sent to your ChatBot via a web request.
