### ISSUE TITLE
How to save chat records in excel at the time of conversation?

### ISSUE THREAD

**Issue by c230269** [gunthercox/ChatterBot#1340]

**Comment by vkosuri** [comment]
If you are using sqlite storage adapter this method might be useful to you http://www.sqlitetutorial.net/sqlite-export-csv/

**Comment by Jereemi** [comment]
> If you are using sqlite storage adapter this method might be useful to you http://www.sqlitetutorial.net/sqlite-export-csv/
I have tried this method @vkosuri and this was able to export the table in the database.
But what I wanted is: to save the chats that the users do with the chatbot through the terminal?
Any suggestion??
