### ISSUE TITLE
Get category (or categories) (of Corpus) from a Statement or a Response

### ISSUE THREAD

**Issue by isaam14** [gunthercox/ChatterBot#1343]
Hello!
Is there a way to ask for the category of a certain Statement or a certain Response?
Ideally I'm searching for something like a function:
get_category_from_statement(statement)
or
get_category_from_response(response)
and it would return a list of categories (or an empty list if any category matches the given statement/response).

**Comment by vkosuri** [comment]
Yes you could by using ``response.category``

**Comment by isaam14** [comment]
@vkosuri  I get this error :
AttributeError: 'Statement' object has no attribute 'category'

**Comment by isaam14** [comment]
@vkosuri please help. What can I do about that error? What could be causing it?

**Comment by vkosuri** [comment]
@isaam14 which version of chatterbot are you using? try to upgrade your chatterbot if you are using older version ``pip install --upgrade chatterbot``

**Comment by isaam14** [comment]
@vkosuri I have version 0.8.7 (the latest) but it still doesn't work.

**Comment by isaam14** [comment]
And when I try 
print(response.tags)
or
print(response.get_tags())
I only get
[]

Do you think the problem has something to do with the fact that my chatbot has read_only = True ?
