### ISSUE TITLE
how to make chatterbot stop learning after training?

### ISSUE THREAD

**Issue by XufengXufengXufeng** [gunthercox/ChatterBot#1348]
I have trained a bot. At first it answers questions just fine. However, latter when i ask some asked questions, it starts to answer nonsense. I think it is because the bot keep learning through my questions.

I have set the read_only=True, hoping it wouldn't stop learning (I learned this from some post). However, that mode literally means the bot will reponse question back to my question, as read my questions. 

So, how can I disable the learning through questions setting properly.

Thank you in advance.

**Comment by WildDylan** [comment]
Hey, I'm chinese, can you talk in chinese? 

```
However, that mode literally means the bot will reponse question back to my question, as read my questions.
```

this words means ? 
you want stop/start learning by some key word?

bot will not learning after set `read_only=True`. 

<img width="647" alt="default" src="https://user-images.githubusercontent.com/2519544/42921050-61bf4870-8b4c-11e8-9d43-b941b2ac8824.png">
process flow for ChatterBot.

**Comment by WildDylan** [comment]
give some example for what you say?

**Comment by WildDylan** [comment]
是的，训练结束之后，全部的数据都会存储到你设置的地方。
