### ISSUE TITLE
Store chat in excel file

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/ChatterBot#1350]
Whenever chatbot response is "Hello" I want to capture very next input response from user in an excel file which should automatically get downloaded in the code folder.
eg. User input            : hi
      Chatbot reponse : hello
      User input            : ABC
Now i want to capture only ABC in excel file.

Below is the code i used in chatterbot.py file to store the input this is working fine in local system but when i deploy to heroku i am not getting excel file downloaded:
        if str(previous_statement) == 'Hello':
            wb = Workbook()
            sheet1 = wb.add_sheet('Sheet 1')
            sheet1.write(0, 0, str(input_statement))
            wb.save('store.xls')

**Comment by ayushecps** [comment]
Thanks for the quick reply but my requirement is storing only a particular user response in excel, can you please help me with the above code thats working very fine in local bit deploying to heroku only this particular change is not moving

**Comment by vkosuri** [comment]
@ayushecps You could read the yml file and input any python converter for example https://github.com/tokland/yaml2csv
