### ISSUE TITLE
output adapter problem

### ISSUE THREAD

**Issue by k3s4** [gunthercox/ChatterBot#1351]
Hello,

I'm trying to write some plugin and while I have finished my input adapter I have there some authorization data variables etc and my problem is - how I can access variables from input adapter in output adapter?

I have some globals variables defined in input adapter but is there simple way to access this data in output adapter?

**Comment by k3s4** [comment]
@vkosuri can u say something more? some examples?

ley't say I have following input adapter:

```
from chatterbot.input import InputAdapter
from chatterbot.conversation import Statement
import requests, json, time

class LivePerson(InputAdapter):
def Authorization(self):
        payload = {'somedata'}
        headers = {'Content-Type': 'application/json'}
        login_url = 'https://lo.agentvep.liveperson.net/api/account/91200013/login??v=1&NC=true'
        r = requests.post(login_url, headers=headers, data=json.dumps(payload))
        parsed_json = json.loads(r.content)
        bearer = parsed_json['bearer']
        print "Auth bearer: ", bearer
        return bearer

    def __init__(self, **kwargs):
        super(LivePerson, self).__init__(**kwargs)
        global bearer 
        bearer = self.Authorization()
```

How I can see 'bearer' variable in output adapter?

**Comment by gunthercox** [comment]
@k3s4 depending on the authentication workflow you are following, you will likely need to cache the bearer token for your application. This can be done on a database, or other level depending on the level of security you require. Beyond that, I'm not certain there is any further advice that can be given at this time.
