### ISSUE TITLE
get_most_frequent_response is not working correctly

### ISSUE THREAD

**Issue by sahanaarya** [gunthercox/ChatterBot#1355]
I selected "get_most_frequent_response" as the Response Selection Algorithm and I noticed that it answers the question correctly the first time but returns a greeting every time the question is asked again. Why is this the case?

**Comment by vkosuri** [comment]
The [get_most_frequent_response](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/response_selection.py#L8) work on number of trained occurence, if ouccrence count > 0 then you will get that match.

https://github.com/gunthercox/ChatterBot/blob/9f4a4ecac32564f245d721854d2698a07d84b405/chatterbot/response_selection.py#L29

I this option will depend on https://chatterbot.readthedocs.io/en/stable/examples.html#read-only-mode

**Comment by gunthercox** [comment]
I've made changes to ChatterBot so that it uses the `filter` function instead of `get_most_frequent_response`. The new functionality is intended to be more consistent and reliable.

I'm going to close this ticket off. Please let me know if you have any questions.
