### ISSUE TITLE
Example django app is not working?

### ISSUE THREAD

**Issue by kumarkrish85** [gunthercox/ChatterBot#1356]
Hi,

I am trying to run the example django app using the below command 

`python manage.py runserver 127.0.0.1:8000`

I have got the below error 

`django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.`

I went ahead and removed the include in urls.py

After clearing i hit with an another issue, 

`django.urls.exceptions.NoReverseMatch: 'chatterbot' is not a registered namespace`

`app_name = "chatterbot"; \n
urlpatterns = [ \n
    url(r'^$', ChatterBotAppView.as_view(), name='main'), \n
    url(r'^admin/', admin.site.urls, name='admin'), \n
    url(r'^api/chatterbot/', ChatterBotApiView.as_view(), name='chatterbot'), \n
]`

Can you please help me resolving the issue?

![namespace](https://user-images.githubusercontent.com/27405093/43137744-4c342e90-8f6a-11e8-8670-d8a0edf5372c.png)

**Comment by vkosuri** [comment]
I think it should update like 

```Python
<a class="nav-link" href="{% url 'chatterbot' %}">API</a>
```
could you replace line https://github.com/gunthercox/ChatterBot/blob/master/examples/django_app/example_app/templates/nav.html#L21 with above then restart server?

**Comment by kumarkrish85** [comment]
Thanks @vkosuri for the information. I did change the code and restarted it. When i click on API/ Admin. The below error i am getting it, please help to resolve the issue.

`

Request Method: | GET
-- | --
http://localhost:8082/api/chatterbot/
2.0.7
AttributeError
'WSGIRequest' object has no attribute 'session'

`

**Comment by vkosuri** [comment]
I am not sure, I googled it i found this https://stackoverflow.com/questions/39480179/wsgirequest-object-has-no-attribute-session-while-upgrading-from-django-1-3 you may try this

**Comment by kumarkrish85** [comment]
Thanks @vkosuri , I have googled it and applied the same fix. Thanks!! , I hit with this below issue

django.db.utils.OperationalError: no such table: 

I have applied the fix mentioned in the [https://stackoverflow.com/questions/34548768/django-no-such-table-exception/36453000](url)
