### ISSUE TITLE
Using ChatterBot with queries

### ISSUE THREAD

**Issue by hugo-pires** [gunthercox/ChatterBot#1357]
Hello

Is it possible to parse input sentences in order to find words that could be used in a SQL query, and return a response according to this result?

Thank you

Hugo

**Comment by vkosuri** [comment]
IMO This possible in two way one either through preprocesors https://chatterbot.readthedocs.io/en/stable/preprocessors.html or you could write your own logic adapter https://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html

**Comment by hugo-pires** [comment]
Thank you. Is it possible to have some example from the documentation?

**Comment by vkosuri** [comment]
Sure, ASAP

**Comment by elcolie** [comment]
Any update on this?

**Comment by gunthercox** [comment]
Sorry everyone. I don't have any examples for how to so this. I would recommend looking into [Python's regular expression](https://docs.python.org/3/howto/regex.html) capabilities to extract SQL-like words from a string of text. Custom text tokenization through a library like NLTK might be another option if you are looking for something that can use examples to generate the rules for what words to use. https://www.nltk.org/book/ch03.html
