### ISSUE TITLE
SystemError: Parent module '' not loaded, cannot perform relative import

### ISSUE THREAD

**Issue by SolarPolarMan** [gunthercox/ChatterBot#136]
I tried installing with pip but python's not registering so I put it in the directory and it's now having troubles with
```py
Traceback (most recent call last):
  File "index.py", line 3, in <module>
    from chatterbot import ChatBot
  File "/media/solarpolarman/hdd/code/discord/markov/chatterbot.py", line 1, in <module>
    from .adapters.exceptions import UnknownAdapterTypeException
```

**Comment by gunthercox** [comment]
I am assuming the file `/media/solarpolarman/hdd/code/discord/markov/chatterbot.py` is one you created. I have no way of knowing what the contents of this file are, _but_ if you are importing something from the chatterbot module you installed with pip inside of another file named chatterbot.py this can cause some issues.

**Solution:** Rename the chatterbot.py file to something else.

Please let me know if this works.

**Comment by gunthercox** [comment]
@SolarPolarMan Any update on this? I'm closing this off, feel free to comment or reopen if you need more assistance.
