### ISSUE TITLE
Retrieve chat history from database 

### ISSUE THREAD

**Issue by kumarkrish85** [gunthercox/ChatterBot#1360]
Thanks to the team for creating this wonderful chatbot. Can you please share your inputs on following queries?

1. In my chatbot, i want to show choices like a/b/c , based on the user inputs it should respond based on the selection. 

2. I want to save the chat conversation in database (I have read the documentation) and pull out the chat histroy for analytics?

3. I want to host it inside Apache web server and got the this link for reference [https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/modwsgi/](url)

Thanks,
Krishna

**Comment by kumarkrish85** [comment]
Hi @vkosuri any inputs?

**Comment by vkosuri** [comment]
I don't understand what you are looking exactly. could you please elaborate.

By looking points those things are doable using chatterbot.

1. Feedback example will guide you how to do this https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py
2. chatterbot default storage is sqllite https://chatterbot.readthedocs.io/en/stable/storage/index.html#sql-storage-adapter
3. I haven't tried on apache, I know few other things 
a. Django https://chatterbot.readthedocs.io/en/stable/django/index.html
b. Deploy it on heroku https://github.com/vkosuri/chatterbot-live-example
c. Using flask https://github.com/chamkank/flask-chatterbot

**Comment by kumarkrish85** [comment]
Thanks @vkosuri . I want to retrieve the chat conversations between bot and user, with that we can identify which are most asked.

**Comment by kumarkrish85** [comment]
Hi @vkosuri , I want to host it in open source web server like Apache. The one you suggested Heroku involve pricing. Please suggest open source project can host the django or WSGI?
