### ISSUE TITLE
Ubuntu Corpus Taking a week to train...?

### ISSUE THREAD

**Issue by bobland1** [gunthercox/ChatterBot#1361]
Got a couple of questions
1) My training corpus has taken nearly a week and im not entirely sure why. 
2) Does the bot work if i cancel the training
3) What happens if you cancel the training, i cancelled it once to increase the ram / cpu sockets on the VM. does it just carry on from where it left off.. it hasnt added anything to the response section of the response database

**Comment by vkosuri** [comment]
1. Yes, it was documented here https://chatterbot.readthedocs.io/en/stable/training.html#training-with-the-ubuntu-dialog-corpus
2.  Yes, with trained data, check sqlite.db file in your worksapce.
3. No

**Comment by bobland1** [comment]
It hasnt added anything to the database since the 24th but is still showing the training screen

**Comment by vkosuri** [comment]
I tink first it will download ubuntu corpus, then it will start training process, did you verified the ubuntu corpus downloaded from 'http://cs.mcgill.ca/~jpineau/datasets/ubuntu-corpus-1.0/ubuntu_dialogs.tgz'

**Comment by bobland1** [comment]
Yes, dont worry. im just going to start from fresh. How would i add my own training class, id like to train by bot of this https://github.com/hellohaptik/conversation_data
