### ISSUE TITLE
Response too slow.

### ISSUE THREAD

**Issue by nishant260190** [gunthercox/ChatterBot#1363]
Hi,

First of all thanks for this wonderful work.

I have tried it with sqlitedb but it was too slow that's why I shifted to mongodb. Initially it is good but Now I am having only 14500 statements and it is giving response after 4-5 seconds. How can I make response more faster. is there any way ?
``` Python
bot = ChatBot(
    'mychatbot',
    read_only=True,
    trainer='chatterbot.trainers.ListTrainer',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'threshold': 0.85,
            'default_response': 'I am sorry, but I do not understand.'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.85,
            'default_response': 'I am sorry, but I do not understand.'
        }
    ],
    filters=[
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    preprocessors=[
        'chatterbot.preprocessors.clean_whitespace', 'chatterbot.preprocessors.unescape_html', 'chatterbot.preprocessors.convert_to_ascii'
    ],
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    database='mychatterbot'
}
```
If I am not wrong it is matching each input statement with all existing statements in loop that's why now responding slow with increase of number of statements.

Can we try elastic search as a db (as text based search is much faster in it). We can tokenize input statement and removing stop words than find out some top result from ES than apply LevenshteinDistance algo.

Please suggest.

**Comment by bobland1** [comment]
use       "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance"

**Comment by bobland1** [comment]
but do pip install python-levenshtein

**Comment by nishant260190** [comment]
Thanks @bobland1 : But still response is taking 4-5 seconds in reply. Is there any other way to speed it up?
