### ISSUE TITLE
Training the chatterbot (repeated addition)

### ISSUE THREAD

**Issue by ChristinaLai2019** [gunthercox/ChatterBot#1364]
Hey guys. I am wondering if there is a way that I can train my chatterbot without having to train the old ones when I get some new corpuses. It will save me a lot of time if I only need to train the new one and my chatterbot is not losing the old trained-corpuses memory.

**Comment by vkosuri** [comment]
I think it will possible, using some workarounds.

The default storage adapter for chatterbot is sqllite https://chatterbot.readthedocs.io/en/stable/storage/index.html#sql-storage-adapter, it will be saved ``sqlite.db`` file in your workspace.

I would suggest place new data in newfile, train only those files. For example

> train1.py
```Python
# Create a new instance of a ChatBot
bot = ChatBot(
    "Terminal",
    storage_adapter="chatterbot.storage.SQLStorageAdapter"
)
bot.set_trainer(ChatterBotCorpusTrainer)

bot.train("chatterbot.corpus.english")
```

> train2.py
```Python
# Create a new instance of a ChatBot
bot = ChatBot(
    "Terminal",
    storage_adapter="chatterbot.storage.SQLStorageAdapter"
)
bot.set_trainer(ChatterBotCorpusTrainer)

bot.train("chatterbot.corpus.ai")
```

> P.S I never tried the example, I hope it will work. Let me your observations
