### ISSUE TITLE
how to display accuracy of training and testing data

### ISSUE THREAD

**Issue by xmen1412** [gunthercox/ChatterBot#1370]
i have done to train and test my model with chatterbot. but, i want evaluate performance as well as accuracy of my model. is there any method to calculate and show performance's result?

**Comment by vkosuri** [comment]
There are some benchmark tests are there, these might help you https://github.com/gunthercox/ChatterBot/blob/master/tests/test_benchmarks.py

**Comment by xmen1412** [comment]
is there any documentation for 'test_benchmarks.py' i do not understand how to use it?

**Comment by gunthercox** [comment]
`test_benchmarks.py` just tests performance (speed). It can be run like this: `nosetests tests.test_benchmarks`
