### ISSUE TITLE
where will be the trained conversation stored.in which file ?in chatterbot 

### ISSUE THREAD

**Issue by fabhari** [gunthercox/ChatterBot#1374]

**Comment by fabhari** [comment]
where will be the trained conversation of a chatter bot be stored .in which file

**Comment by pengoox** [comment]
You have to specify where you want to store it. after training your chat bot, you have to:

`chatbot.trainer.export_for_training('./export.yml')`

**Comment by fabhari** [comment]
on what basis it select the appropriate answer for the quetion form db..what dose the whole algorithm about?

**Comment by vkosuri** [comment]
Chatterbot uses [logic adapters](https://chatterbot.readthedocs.io/en/stable/logic/index.html ) for how ChatterBot selects a response to a given input statement. 

Chatterbot default adapter is [Multilogic adapter](https://chatterbot.readthedocs.io/en/stable/logic/multi-logic-adapter.html)

Next, it starts to compare with each statement to find the exact match using [comparison methods](https://chatterbot.readthedocs.io/en/stable/comparisons.html)
