### ISSUE TITLE
 statement_comparison_function= 'chatterbot.comparisons.synset_distance' not working.

### ISSUE THREAD

**Issue by pritibaheticompumatrice** [gunthercox/ChatterBot#1377]
I am trying to implement chatterbot.comparisons.SynsetDistance class. I want to get the response even if the user statement contains a word which is the synonym of the statement present in the training corpus.
But instead it returns the default response.

**Comment by gunthercox** [comment]
Hi @pritibaheticompumatrice, I'm working on fixing a bug in the `SynsetDistance` class (#1436) that was causing incorrect confidence scores. It is quite possible that this was related.
