### ISSUE TITLE
GUI for progress bars and user interaction

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [gunthercox/ChatterBot#1378]
Has a GUI been something discussed?   If so I just completed writing a front-end for ChatterBot.

It replaces the text progress meters with graphical ones:
![chatterbot progress meter](https://user-images.githubusercontent.com/13696193/44594902-703fdf80-a795-11e8-883d-91377f330ad7.jpg)

It also has a classic "chat window" for interacting.
![chatterbot chat window 2](https://user-images.githubusercontent.com/13696193/44595091-0c69e680-a796-11e8-84d2-b824347f93a6.jpg)

I'm unsure if this is the place to post about this or not.  Seems like people interested in Chatterbot are going to come here.... question is if the GUI is welcomed too.

Feel free to close if not appropriate.  Happy to post link to it if OK.  It's not very much code.  About 30 lines.

**Comment by MikeTheWatchGuy** [comment]
OK, hearing on objections, I'll go ahead and point you to the front-end code...[ This link ](https://github.com/MikeTheWatchGuy/PySimpleGUI/blob/master/Demo_Chatterbot.py)will get your the Chatterbot GUI Demo code.  Place [the code for the PySimpleGUI package](https://github.com/MikeTheWatchGuy/PySimpleGUI/blob/master/PySimpleGUI.py) in the same folder.  This version has not been uploaded toe PyPI yet.

This version of the Chatterbot GUI retains the training information so that it's visible after the training completes, like a dashboard.

![chatterbot training 2](https://user-images.githubusercontent.com/13696193/44614245-03593380-a7ef-11e8-93c2-a17484100faf.jpg)
![chatterbot training](https://user-images.githubusercontent.com/13696193/44614248-05bb8d80-a7ef-11e8-80d1-6393cee2833e.jpg)

**Comment by MikeTheWatchGuy** [comment]
OK, I just added info about PySimpleGUI in the Wiki on the page that asks for projects that use Chatterbot.

I really hope someone that is 'in charge' is OK with both this issues being opened and the Wiki edit. Please let me know if these are bad things!

**Comment by gunthercox** [comment]
You're all welcome to edit the wiki, I highly encourage it in fact

**Comment by MikeTheWatchGuy** [comment]
I hope someone finds this GUI a help :-)  I appreciate the time you left this issue open so that people discovered it!  Congrats on your successful project.
