### ISSUE TITLE
Where data is stored after training the bot.

### ISSUE THREAD

**Issue by geeekyvaibhavatgithub** [gunthercox/ChatterBot#1383]
I have trained the Bot using chatterbot.corpus.english. May I know where this data is stored because it is not creating any sqlite3 file, nor any MongoDB. can you please let me know.

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from pymongo import MongoClient

import logging
logging.basicConfig(level=logging.INFO)

chatbot = ChatBot(
    "Terminal",
    database_uri='mongodb://localhost:27017/chatterbot_test_database',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=[
        "chatterbot.logic.BestMatch"
    ],
    input_adapter="chatterbot.input.TerminalAdapter",
    output_adapter="chatterbot.output.TerminalAdapter"
) 

chatbot.set_trainer(ChatterBotCorpusTrainer)
chatbot.train("chatterbot.corpus.english")
print("Type something to begin...")

while True:
    try:
        bot_input = chatbot.get_response(None)
    except (KeyboardInterrupt, EOFError, SystemExit):
        break

**Comment by vkosuri** [comment]
sqllite.db file under your workspace.
