### ISSUE TITLE
Specification of Chatter Bot

### ISSUE THREAD

**Issue by HJStella** [gunthercox/ChatterBot#1388]
Hi, I am planning to try Chatter Bot code for sentence recognition. Before starting this, I want to know the spec.

Therefore, what is the minimum/recommended specifications of CPU/RAM for using "Chatter Bot". And how can I verify it?

Thank you for reading my question :)

**Comment by gunthercox** [comment]
Hi @HJStella I've developed ChatterBot on a system that has a quad-core (i7) processor and 16 GB of memory. Systems with less available resources should be able to run it as well, but I don't currently have a way to provide any benchmarks that could be used to determine the minimum system requirements.
