### ISSUE TITLE
Request for new API under Storage class to list all conversations for a specific conversation id

### ISSUE THREAD

**Issue by faraazc** [gunthercox/ChatterBot#1399]
Hi,

I am looking for a new API under Storage class to list all conversations for a specific conversation id.

I am not if that already exists. If not it will be helpful to have something like as shown below

bot.storage.get_conversations(conversation_id),. where bot is an bot of a chatterbot class

Thanks

**Comment by gunthercox** [comment]
Hi @faraazc, development of a feature similar to this is planned. It will allow filtering to be done based on a named conversation, for example:

```python
statement_for_conversation = bot.storage.filter(conversation='<string>')
```

I hope this is close enough to your use-case to be useful?

**Comment by faraazc** [comment]
conversation='<string>' is a conversation id right?.

and if the statement_for_conversation = bot.storage.filter(conversation='<string>' call returns me a list of statements under a particular conversation id, then solves my requirement.

Thanks for quick response.

**Comment by gunthercox** [comment]
`conversation` will be a string. With the new changes, each statement will have an `conversation` attribute to label the conversation that it is a part of. The conversation string can be anything though, including an id.
