### ISSUE TITLE
How to create custom webAPis using django chatterbot 

### ISSUE THREAD

**Issue by RishiTeke** [gunthercox/ChatterBot#1408]
I am using example_app on django-chatterbot integration. If i want to create custom rule based API that uses chatterbot also how can i do it? I tried creating functions inside ChatterBotApiView class but it not accessible. I am new to django, any help appreciated. Thanks

**Comment by gunthercox** [comment]
You can create new views, similar to the example `ChatterBotApiView`. Adding the new views to the `urls.py` file will make them available to access.

Please let me know if there is anything I can clarify specifically. I'd be happy to provide links to some of the awesome documentation that exists for Django's views and url settings depending on what you are attempting to build.

**Comment by RishiTeke** [comment]
Thanks for reply @gunthercox . I managed to create function based views and created APIs.
