### ISSUE TITLE
What is the usage scenario of chatterbot?

### ISSUE THREAD

**Issue by KevinChen1994** [gunthercox/ChatterBot#1410]
First of all ,thanks for your work!
I'm thinking about does Chatterbot can be a Specific field chat bot ?  I have almost 3GB data , I try to train them in Chatterbot with MongoDB , but the speed is too slow . Then I use 100MB data to train , when it finished training. the response is too slow , maybe it takes 2 hours to response an answer .
So does Chatterbot only can be used in a small amount of corpus ？My demand is almost 3 million questions to answer by Chatterbot . Can Chatterbot do it?

Thanks !

**Comment by vkosuri** [comment]
Thank you, I think this is known issue, Hope this will be improved with the latest upcoming build.

**Comment by KevinChen1994** [comment]
@vkosuri  So you mean Chatterbot can't deal with 3 million data?
