### ISSUE TITLE
Time consumption for training is very high(reading from excel,55000 conversations)

### ISSUE THREAD

**Issue by tghv** [gunthercox/ChatterBot#1419]
I'm training data of 55000 questions and answers reading from excel with two columns,the time consumption for training the data is  very high.Is there a solution for reducing time for training 

alexa_bot=ChatBot("alexa_bot",trainer='chatterbot.trainers.ListTrainer',storage_adapter='chatterbot.storage.MongoDatabaseAdapter',database='Alexa_db')

#test_bot.storage.drop()
alexa_bot.set_trainer(ListTrainer)
alexa_data=pd.read_excel("Alexa_train_data.xlsx",encoding='latin1')
for index, row in alexa_data.iterrows():
    alexa_bot.train([row["Question"], row['Answer']])

**Comment by gunthercox** [comment]
Hi @tghv, the `MongoDatabaseAdapter` will insert the statements one at a time which would be the main cause of the slowness. You might be able to achieve better performance by doing a bulk-insert operation to get the data into your database.

https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/
