### ISSUE TITLE
JSON loading in corpus.py is quite slow

### ISSUE THREAD

**Issue by korymath** [gunthercox/ChatterBot#143]
When working with multiple MB files in the corpus JSON limps along loading them slowly... I have found that working with a faster JSON handling library (simplejson, ultrajson) speeds things up significantly.

**Comment by korymath** [comment]
Perhaps this is part of a larger ticket on speed of the algorithms in general. While finding strings in a dictionary is relatively quick for small databases, it seems that with a large corpus (over 200kb json) then the bot takes a long time to respond.... any experience with this?

**Comment by gunthercox** [comment]
I am aware of limitations with speed when saving statements. I'm not sure how much can be done to fix it considering the problem has to do with the amount of time it takes a computer to read and write to its hard disk.

I would reccomend using the MongoDB database for significantly better performance.
https://github.com/gunthercox/ChatterBot/wiki/Storage-adapters#mongo-database-adapter

**Comment by korymath** [comment]
Yes, it seems that MongoDB is a good solution here to speed things up considerably. A little more overhead for the installation, but well worth it when using big data sets. 

Much appreciated.

**Comment by korymath** [comment]
Perhaps there is even a way to increase the speed of training a MongoDB backed model as well? 

Perhaps update_one is faster than replace_one in the storage adapter.
