### ISSUE TITLE
ChatBot Issue with learn_response() function

### ISSUE THREAD

**Issue by Jereemi** [gunthercox/ChatterBot#1430]
I am running the file "learning_new_response.py" and when I type in a word 'Hi', it displays me the response "How are you doing" and further ask me **"Is 'How are you doing?' a coherent response to "Hi"?"**
But when I type the response as "yes" the terminal stops and it doesn't show up anything
And another error when I type the response as "no", I get the following error:
**please input the correct one
hello
Traceback (most recent call last):
  File "bot.py", line 52, in <module>
    bot.learn_response(CONVERSATION, response1, input_statement)
TypeError: learn_response() takes 3 positional arguments but 4 were given**

Please help me with this issue.

**Comment by gunthercox** [comment]
The error you are getting seems to be related to the issues you encountered earlier (#1426). Again, that function changed slightly in the latest alpha release (1.0.0a1). It's almost as if you have the alpha release installed instead of version 0.8.7.

**Comment by Jereemi** [comment]
> The error you are getting seems to be related to the issues you encountered earlier (#1426). Again, that function changed slightly in the latest alpha release (1.0.0a1). It's almost as if you have the alpha release installed instead of version 0.8.7.

@gunthercox But how is it possible? I have already checked the version and it clearly shows its Chatterbot version 0.8.7 and even I have downgraded the version to 0.8.6.
Is there any solution to the above-mentioned issue??

**Comment by Jereemi** [comment]
@gunthercox Is there any other alternative that I can implement this learn_response.py? I really wanted to make my bot learn from the responses of different users.

**Comment by Jereemi** [comment]
@gunthercox I have resolved the issue now. When I looked into the documentation of Chatterbot, I realized that the line "**bot.learn_response(CONVERSATION, response1, input_statement)**" which is specified in the file learn_response.py is wrong because in the documentation the declaration was "**def learn_response(self, statement, previous_statement):**" and so we can specify only 3 arguments including the implicit call to self. 
This has solved the error:)

Just an additional question: After I type "no" as the answer, I could specify my new answer and it displays "Responses added to bot". But the next time I rerun the file, I could not get the answer that I had given. Why is this so?

**Comment by gunthercox** [comment]
I'm glad to hear that your initial issue was resolved.
***
> Just an additional question: After I type "no" as the answer, I could specify my new answer and it displays "Responses added to bot". But the next time I rerun the file, I could not get the answer that I had given. Why is this so?

This could be due to the response selection method that is being used:
https://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#module-chatterbot.response_selection

**Comment by Jereemi** [comment]
@gunthercox Thank you so very much in taking the initiative to help whenever a problem arises.

All the issues have been solved:D

**Comment by zebrucfish** [comment]
Hi guys I have the same issue, and I’m a newbie to python. Please can you post how you fixes this error? 
![1fee6950-701e-4d88-9a25-365bcb392369](https://user-images.githubusercontent.com/44651908/47812380-2bf63000-dd40-11e8-93bc-13ab2ca50ceb.jpeg)
