### ISSUE TITLE
How to distinguish between questions and answers

### ISSUE THREAD

**Issue by cswww** [gunthercox/ChatterBot#1432]
I want to distinguish between questions and answers.
The answer is also a question.

**Comment by gunthercox** [comment]
HI @cswww, I'll try to help the best I can but I might need some more info to do so. Is this a question about Natural Language Processing or about the structure of data stored in ChatterBot?

**Comment by cswww** [comment]
Thank you very much for your help，It's data structure problem. Answers will be processed as questions leading to one answer being matched to trigger the next question as answers I have found a solution

# conversation = [
#     'Question',
#     'answer'
# ]
# conversation2 = [
#     'Question',
#     'answer'
# ]
#
bot.set_trainer(ListTrainer)
# bot.train(conversation)
# bot.train(conversation2)

**Comment by gunthercox** [comment]
@cswww I'm glad to hear that you found a solution. I'm going to close this ticket off. Feel free to open a new one if you have any further questions.
