### ISSUE TITLE
Add ability to create database exports

### ISSUE THREAD

**Issue by korymath** [gunthercox/ChatterBot#144]
Is there a means by which to combine two learned databases... it would seem to me that this is a critical component to store learned responses, and transfer and combine them with other learned interactions? 

Is this something that is covered?

**Comment by gunthercox** [comment]
This is not currently supported, however I would be in favor of adding this as an import / export feature.

**Comment by gunthercox** [comment]
The implementation of database exporting capabilities is currently waiting on my designs for AIML Integration (#137). Some of the features in the AIML specification currently do not agree with ChatterBot's design (such as wildcard statements). I need to create a common internal format for storing this information before database exports can be allowed.
