### ISSUE TITLE
No random responses

### ISSUE THREAD

**Issue by UziFTW** [gunthercox/ChatterBot#1442]
Hi! I have an issue with the responses I get with Chatterbot. I keep getting the same responses regardless of how many times I enter the input. It happens for my own corpus and the english corpus that comes with the package.

Here is my code:
https://pastebin.com/dSTBsmLB

**Comment by gunthercox** [comment]
@UziFTW Do you know what version of ChatterBot you are using?

**Comment by UziFTW** [comment]
@gunthercox can you please respond?

**Comment by gunthercox** [comment]
Your code sample that you posted looks correct. I am uncertain why you are getting the same response repeatedly.

**Comment by drodil** [comment]
You have to add the response_selection_method for the BestMatch adapter:

```python
{
    'import_path': 'chatterbot.logic.BestMatch',
    'response_selection_method': 'chatterbot.response_selection.get_random_response'
}
```
