### ISSUE TITLE
Can Chatterbot use SMS channel as output?

### ISSUE THREAD

**Issue by santannamv** [gunthercox/ChatterBot#1453]
Sorry, I know that it is a very dumb question. But I really do not know where to ask about it. Thanks.

**Comment by gunthercox** [comment]
Hi @santannamv, SMS could be used as a method for users to communicate with a chat bot. ChatterBot currently doesn't have anything built-in that works specifically with SMS, but I do not think it would be difficult for you to set up.

Essentially, you'd want to have a section of your code where, if a message is received it will pass the content to ChatterBot to generate a response. You can then return that response as a SMS message to the sender.

***

For reference, Twillio has a good example that shows how to use their API to send and receive messages in Python: https://www.twilio.com/docs/sms/quickstart/python
