### ISSUE TITLE
Tweet cleanup

### ISSUE THREAD

**Issue by talentoscope** [gunthercox/ChatterBot#1455]
Hi all,

Great project! Would it be possible to add a simple regex into the statement/response before saving to DB for tweets to remove @mentions, possibly URLS, and maybe the # in hashtags?

It seems that these are messy and don't generalise well if a bot replies with a mention of an unrelated user.

**Comment by gunthercox** [comment]
Nobody has picked this up since October. I'm going to close this ticket off.
