### ISSUE TITLE
Getting the error cb.train is not callable.

### ISSUE THREAD

**Issue by ana301** [gunthercox/ChatterBot#1469]
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

cb=ChatBot("Ruhi")

cb.train([
   "Hello",
   "Hi there!",
   "How are you doing?",
   "I'm doing great.",
   "That is good to hear.",
   "Thank you",
   "You're Welcome"
])

response=cb.get_response("Good Morning")
print(response)

**Comment by gunthercox** [comment]
Hi @ana301 Instead of calling the train method, try the following:

```python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot('Charlie')

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])
```
