### ISSUE TITLE
beginner struggling to get chatbot running python 3.7

### ISSUE THREAD

**Issue by bobstheman** [gunthercox/ChatterBot#1472]

**Comment by bobstheman** [comment]
not sure why the word are so huge and bold, i copy pasted them from the "basic usage" section.

**Comment by bobstheman** [comment]
Using the instructions at https://chatterbot.readthedocs.io/en/stable/

I created this script:

https://pastebin.com/yQL2bwd2

It seems I am kind of getting somewhere now but the only thing my chatbot will say is:

The current time is 01:37 PM


Why is it only telling me the current time over and over and nothing else?

**Comment by bobstheman** [comment]
What a waste of time.

**Comment by vkosuri** [comment]
Have you seen documentation about chatterbot https://chatterbot.readthedocs.io/en/stable/
