### ISSUE TITLE
Need to install chatterbot on codio python3.5

### ISSUE THREAD

**Issue by Luhizz** [gunthercox/ChatterBot#1475]
So I am trying to install chatterbot and "pip install chatterbot" works but it installs to python2.7 version. I have tried to install in other python versions "python3.5 pip install chatterbot" but it says that there is no such file or directory. https://i.imgur.com/C6ZkgUa.png Maybe any of you know how should I have this fixed?

**Comment by vkosuri** [comment]
I would recommend using python virtual environments instead using global python for more information https://realpython.com/python-virtual-environments-a-primer/

did you tried ``pip3 install --upgrade chatterbot``

**Comment by gunthercox** [comment]
@Luhizz In the picture you posted the command `sudo python3.5 install chatterbot` is incorrect. You will need to install ChatterBot using the pip command. For example:
```
sudo pip install chatterbot
```
or
```
sudo pip3 install chatterbot
```

**Comment by Luhizz** [comment]
@vkosuri I tried to upgrade, that does not help. I am using codio, it runs linux there.
@gunthercox I tried all the different variations, nothing.

**Comment by gunthercox** [comment]
> I tried all the different variations, nothing.

So... nothing gets printed out? Or are you getting the same error, or a different error?

**Comment by Luhizz** [comment]
Both 

> sudo pip install chatterbot

and 

> sudo pip3 install chatterbot

works, but pip installs on python 2 and pip3 installs on python 3.4 and I need to run it on python 3.5, so when I try to run it it says

> No module named 'chatterbot'

**Comment by gunthercox** [comment]
I think I understand now.

```
python3.5 -m pip install chatterbot
```

This command will let you run `pip` commands from the `python3.5` installation and chatterbot will be installed to Python 3.5 as a result.

**Comment by Luhizz** [comment]
That worked, thanks!!

**Comment by gunthercox** [comment]
The `-m` allows a module, such as `pip`, to be executed as a script. A more in-depth explanation can be found in Python's documentation for the command:
https://docs.python.org/3/using/cmdline.html#cmdoption-m
