### ISSUE TITLE
ImportError: No module named 'chatterbot.storage'

### ISSUE THREAD

**Issue by sumitroy630** [gunthercox/ChatterBot#1485]
File "C:\Users\HP\Desktop\ChatterBot-master\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter

ImportError: No module named 'chatterbot.storage'; 'chatterbot' is not a package

How to fix this?

**Comment by gunthercox** [comment]
It sounds like you might need to install `chatterbot`.

```
pip install chatterbot
```
> ~ https://chatterbot.readthedocs.io/en/stable/setup.html
