### ISSUE TITLE
Play and pause video using chatbot

### ISSUE THREAD

**Issue by c230269** [gunthercox/ChatterBot#1489]
How can i pause and play video using chatbot.

For eg. There is an html page in which 3 sections are there each containing one video and in the same page chatbot icon is also there. Now when i click on chatbot icon and chat window opens up i started typing play video1 then chatbot should start playing video from the first section, if i say pause video1 then it should pause.

**Comment by ayushecps** [comment]
please help how to resolve this issue

**Comment by gunthercox** [comment]
You may be able to use the `play` and `pause` functions that are provided by the HTML video element.

https://www.w3schools.com/tags/av_met_pause.asp
