### ISSUE TITLE
How do I continue to train my bot?

### ISSUE THREAD

**Issue by Larry850806** [gunthercox/ChatterBot#149]
Because my computer have to shutdown.
How do I continue to train my bot after restart the script?

**Comment by benjpi** [comment]
If I'm correct it should be either saved to a database?

**Comment by Larry850806** [comment]
Store the data and train the bot every time?

**Comment by gunthercox** [comment]
Your chat bot saves what it learns on your computer. It's knowledge is not erased when the computer is shut down. You should only need to train it once.

**Comment by Larry850806** [comment]
@gunthercox 
Thanks. In this case, How do I remove what the bot have learned and retrain it?

**Comment by gunthercox** [comment]
You can remove what a bot has learned by calling: `mychatbot.storage.drop()`.

For example:
```python
mychatbot = ChatBot("Example")
mychatbot.storage.drop()
```

**Comment by Larry850806** [comment]
@gunthercox 
Thanks.
I have used it and it's awesome.
