### ISSUE TITLE
How to save training

### ISSUE THREAD

**Issue by UnknownUser1234** [gunthercox/ChatterBot#1492]
```
from chatterbot import ChatBot
import chatterbot.trainers as trainers

chatbot = train()

def predict(input):
    return str(chatbot.get_response(input))

def train():
    chatbot = ChatBot(
        'Charlie',
        storage_adapter='chatterbot.storage.SQLStorageAdapter',
        database='./database.sqlite3'
    )

    chatbot.set_trainer(trainers.ChatterBotCorpusTrainer)
    chatbot.train('chatterbot.corpus.english')
    return chatbot
```
With the code above, I am training a chatbot based on the english corpus. However, every time I run this script it retrains itself on EVERYTHING. Is there any way I could stop this from happening, and perhaps have it only train once, and at the very least not train on everything again.

**Comment by gunthercox** [comment]
You can create a second file; `train.py` and import your chat bot class to do the training. Then, the training process will only be run if you call `python train.py`.

**Comment by gunthercox** [comment]
Sure, this is a quick example. Let me know if I can elaborate further or improve it.

```python
# chatbot.py

chatbot = ChatBot(...)
```

```python
# train.py
from chatbot import chatbot

chatbot.train('chatterbot.corpus.english')
```
```bash
python train.py
```
