### ISSUE TITLE
Can i apply LSTM, RNN in chatterbot? How?

### ISSUE THREAD

**Issue by khushbumodi0** [gunthercox/ChatterBot#1502]
Hi, I want to apply memory network in Chatterbot for better performance. I want to know that can i apply LSTMs and RNN in chatterbot?

**Comment by datasciraj** [comment]
I am not sure if this option is readily available. But i guess custom adapter can help you.

**Comment by khushbumodi0** [comment]
@gunthercox Please, can u give me some idea that LSTM & RNN is possible in chatterbot? If yes then how can I implement with chatterbot? Should I have to create a new custom logic adapter for that? Please, can you give me some suggestion on that?

**Comment by gunthercox** [comment]
@khushbumodi0 I cannot currently provide an example of LSTM & RNN is possible in ChatterBot.
