### ISSUE TITLE
Long Conversation

### ISSUE THREAD

**Issue by betolley** [gunthercox/ChatterBot#1515]
ChatterBot appears to always answer based on the question I asked.  The question I have is is there a way to have it keep track and answer based on what we are talking about?  I would like it to do the following:

Me:Hi how are you today?
ChatterBot: Good and you?
Me: Good but it is raining.
Chatterbot: I am glad you are good and sorry it is raining.

To do the above I would have to have  a Good but it is raining and it has no context.

**Comment by gunthercox** [comment]
There is not currently a way to do what you are looking for. I have plans to add this functionality eventually, the ticket number is #276
