### ISSUE TITLE
Hello. Need someone to help me install it

### ISSUE THREAD

**Issue by aawee** [gunthercox/ChatterBot#1517]
Hi. 
I asked for help on freelancer to help me install Chatterbot with corpus module but i can't find someone that can help me.
I would like to have it installed on my ubuntu vps with web access (working on my active website).

My budget is $40 on freelancer or in paypal or btc.

If someone can help me please give me an response.

thank you!

**Comment by saydulk** [comment]
@aawee https://chatterbot.readthedocs.io/en/stable/django/index.html

**Comment by aawee** [comment]
I don't get this part. Thanks

Add chatterbot.ext.django_chatterbot to your INSTALLED_APPS

**Comment by gunthercox** [comment]
@aawee, I apologize for the delayed response. The `INSTALLED_APPS` should be a variable that you can find in the `settings.py` file of your Django project.

I hope that other than this, all has gone smoothly with the installation?
