### ISSUE TITLE
ImportError: No module named 'chatterbot.storage'; 'chatterbot' is not a package "

### ISSUE THREAD

**Issue by prilcool** [gunthercox/ChatterBot#1518]
I have python version Python 3.5.2
I installed chatterbot and it shows it is installed using pip freeze.

But i have this error 

" module = self._original_import(*args, **kw)
ImportError: No module named 'chatterbot.storage'; 'chatterbot' is not a package "

Can you list your exact python version you use 
can you list your exact chatterbot version that is working 
Can you provide directory structure on how i should place chatterbot..

Because everything i tried doesnt resolve this issue.

**Comment by gunthercox** [comment]
The message `chatterbot' is not a package` sounds like the clue here.

Did you know that if you have multiple versions of Python installed, there are different entry points for each one?

For example: `python example.py` might execute the program using Python 2.7, but `python3 example.py` might execute the program using Python 3.5.

**Comment by prilcool** [comment]
Thanks gunther for your great work .
I only have python 3.52 and it is executing using that .

can you tell me how do you have your directory structure setup .

I've already done pip3 install chatterbot and the dependencies are installed successfully.
Currently i have just downloaded  ChatterBot-master  unzipped it and placed on desktop

next I am navigating to the subdirectory  ChatterBot-master\examples 
and than from command prompt executing  python3 basic_example.py 

Is there another setup expected ? 
what  directory structure and placement and how do you have it setup on your end that information would really help.
I'm assuming that the  chatterbot module is not registered properly during install

**Comment by gunthercox** [comment]
I usually set ChatterBot up in one of two ways.

1. With pip, in which case the Python file for the chat bot can be located anywhere.
2. With the chat bot Python file located relative to the source code (this sounds like it's what you're looking to do).
```
ChatterBot-master/
    chatterbot/
        ...
    example_code.py
     ...
```
(The code you are executing must be in the same directory as the Python module for the import to work.)
