### ISSUE TITLE
Dialog Tree - feature enhancement

### ISSUE THREAD

**Issue by johndpope** [gunthercox/ChatterBot#152]
I think it would be valuable to attempt upgrade the bot with some dialog tree capabilities. 
It maybe as simple as something like this 
https://github.com/jeromeetienne/dialogtree.js

This app - http://www.chatmapper.com/features/ looks more robust / supporting multiple languages.
![celi02dweauwns-](https://cloud.githubusercontent.com/assets/289994/14689857/1a642ad8-0717-11e6-9c0c-0ba3880fd448.jpg)

If there was an appealing UI editor for this - it would further grow the dialog tree database. 
It will be interesting to see Facebook's ui for this.

**Comment by gunthercox** [comment]
Based on the description of a dialog tree from @jeromeetienne's README, I believe this is something that ChatterBot is already doing (except for the GUI component).

> A Dialog tree is used in game to code the conversation the player may have with bots (or non playable characterer).
> 
> A dialog tree is in fact a graph, multiple answer may lead to the same questions. In this tree, what is a node ? A dialog node encodes one exchange in the dialog. 1. Bot can say something. 1. Player got multiple choises to pick 1. depending on player choise, we go to the next node 1. if there are no more children, the conversation is over.

ChatterBot stores all of the input statements it receives as a graph data structure with connections between a statement and it's possible responses.

For visualizations, another ticket was recently opened (#257) which proposes adding support for Orient DB as a storage backend. Orient DB looks like it has some cool features for generating visualizations of the graph http://orientdb.com/orientdb/

***

I'm going to close this ticket off as I believe it is all set. Please feel free to reopen it if I missed something.
