### ISSUE TITLE
How do I ask a series of questions in succession?

### ISSUE THREAD

**Issue by ThatsGabeBro** [gunthercox/ChatterBot#1522]
Hello! First of all, I'd like to say that I love Chatterbot and it has proven very helpful in my studies. I just have a question. I'm trying to create a new Logic Adapter in Django that asks a question, and then once given a valid answer, goes to the next question. But since the training data is made with Statement -> Response in mind, how would I go about making the adapter?

**Comment by vkosuri** [comment]
This example is a close example https://github.com/gunthercox/ChatterBot/blob/master/examples/learning_feedback_example.py
