### ISSUE TITLE
How to supply your own training data?

### ISSUE THREAD

**Issue by MilkyWay90** [gunthercox/ChatterBot#1525]
Title is self-explanatory.

**Comment by vkosuri** [comment]
Two training methods are available one train with list data and corpus data
https://chatterbot.readthedocs.io/en/stable/training.html#training-via-list-data
https://chatterbot.readthedocs.io/en/stable/training.html#training-with-corpus-data

corpus repo https://github.com/gunthercox/chatterbot-corpus

**Comment by MilkyWay90** [comment]
Thank you!
