### ISSUE TITLE
How to implement new logic adapter 

### ISSUE THREAD

**Issue by hpaiml** [gunthercox/ChatterBot#1527]
I have 3 different csv files. I want to create a new logic adapter for each. like I have to create 3 different logic adapter. In each logic adapter I have to set condition like if confidence is less than 0.7 it should show data which has cofidence level 0.7 else other data . so how I can code for it.

**Comment by vkosuri** [comment]
https://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html this will give an idea how to implement new logic adapter.

**Comment by gunthercox** [comment]
@hpaiml What do you have for code so far?

**Comment by hpaiml** [comment]
> @hpaiml What do you have for code so far?

 I want to read sqlite3 trained database in function and call in new logic adapter class.

**Comment by hpaiml** [comment]
If asked question is related to histrory word then response confidence should be greater than 0.75..how to write code for it.
