### ISSUE TITLE
Document example setup

### ISSUE THREAD

**Issue by MartinDelille** [gunthercox/ChatterBot#1528]
For a non python developer like me it is not very easy to understand how to set up the examples.

I would be happy to document this but I would need some basic info. For example, I first installed ChatterBox given following command:

```
pip install chatterbox
```

Unfortunately, when I try to run `basic_example` it fails:

```
$ python basic_example.py
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "basic_example.py", line 12, in <module>
    "Your flight has been booked."
  File "/usr/local/lib/python3.7/site-packages/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/usr/local/lib/python3.7/site-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'
```

**Comment by IndigoFuzz** [comment]
Martin, see: https://github.com/gunthercox/ChatterBot/issues/1426

**Comment by MartinDelille** [comment]
I proposed a fix based on the comments: https://github.com/gunthercox/ChatterBot/pull/1529
