### ISSUE TITLE
No module named LocationLogicAdapterchatterbot.adapters.logic

### ISSUE THREAD

**Issue by bogomil** [gunthercox/ChatterBot#153]
Hi,
I have created a new module, based on your instructions for a Logic adapter, but when I run the bot this error appears (I have added it in `_init_.py`)

```python
Traceback (most recent call last):
  File "chatbot.py", line 8, in <module>
    "chatterbot.adapters.logic.LocationLogicAdapter"
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 49, in __init__
    self.add_adapter(adapter, **kwargs)
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 62, in add_adapter
    NewAdapter = import_module(adapter)
  File "C:\Python27\lib\site-packages\chatterbot\utils\module_loading.py", line 12, in import_module
    module = importlib.import_module(module_path)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named LocationLogicAdapterchatterbot.adapters.logic
```

**Comment by gunthercox** [comment]
The import error (`LocationLogicAdapterchatterbot.adapters.logic`) suggests a possible issue in your code.

Perhaps you meant `chatterbot.adapters.logic.LocationLogicAdapter`?

**Comment by kevin-brown** [comment]
Quick guess, you appear to be missing a trailing comma on line 8 of `chatbot.py`, and as a result your settings for multiple logic adapters are being interpreted as one single (invalid) logic adapter. This is happening because [otherwise it treats it as one long string](http://stackoverflow.com/q/7992559/359284) instead of multiple strings.

**Comment by bogomil** [comment]
@kevin-brown you are right and I am stupid :) Now it works.
Thanks!
