### ISSUE TITLE
Return list of responses from Chatterbot

### ISSUE THREAD

**Issue by Quarion25** [gunthercox/ChatterBot#1533]
Hello

Is there any way to get a list of responses instead of just one from trained chatterbot?

**Comment by gunthercox** [comment]
Currently there is not.

**Comment by Quarion25** [comment]
Are you planning to add this feature in future release?

**Comment by gunthercox** [comment]
This is something that has come up before, #606 for example. I would be willing to consider adding this feature but I consider it lower priority as of right now. I'd be happy to discuss prioritizing it differently though. The key deciding factor would likely be based on what use cases exist.
