### ISSUE TITLE
Corpus categorization

### ISSUE THREAD

**Issue by QuAlan996** [gunthercox/ChatterBot#1536]
Hi all,
my question is related to the logic used by ChatterBot when processing multiple corpora. More specifically I made a chatbot to use in a company internal e-learning system: when a user asks a question about the behaviour of a specific software, the bot should provide the specific response.

This is the use case: my chatbot is trained with multiple corpora, each one about a specific topic. I would like it to provide informations more or less technical according to the company user's role.
I wrote corpora containing informations to be used as answers for different roles: for example, if I'm a simple user, when asking "What is a car?", I would like to receive a simple response like "It is a system composed by wheels and an engine"; if I'm a more technical user, contrariwise, the bot should provide a more technical and detailed description of a car, such as "A car (or automobile) is a wheeled motor vehicle used for transportation, composed by an engine, which is...". 

So how can I tell the bot to search for the response according to the role of the user, with the assumption that there are different answers (on different level of detail and in different corpora) for the same question?

Thank you so much in advance

Alan

**Comment by gunthercox** [comment]
@QuAlan996 Since ChatterBot does not currently have a way to know what kind of user it is talking to, I would recommend creating multiple chat bots, (one designed to speak with less technically inclined personnel and another to speak with more technical users).

Would this be a viable solution for this scenario?

**Comment by QuAlan996** [comment]
Thank you @gunthercox , I also considered that solution. But it is not possible to have only one istance of the bot, assuming that there is a system to categorize users? For example, I could add a log-in system to cathegorize them: if a "User1" (where "User1" is a user category) is logged-in the bot will consider only "corpus1" and "corpus3", if a "User2" is logged only "corpus2" and "corpus5", etc.

In practice the problem is: can I tell to the bot, after the training, to consider only some of his corpora to produce answers?

If this is not possibile I am going to fall back to your suggested solution.
