### ISSUE TITLE
About Zapier Connection

### ISSUE THREAD

**Issue by Pd08111997** [gunthercox/ChatterBot#1537]
When I try to connect my Chatterbot Account with Zapier its showing error.

I have A Demo Account on Platform.chatterbotbuilder.com and a PAid account on Build.thechatterbots.com

I cannot connect my Paid Account to Zapier.
And for Documentation, it's saying to visit Platform.chatterbotbuilder.com But The Paid account is not connecting?

**Comment by gunthercox** [comment]
Hi @Pd08111997 I am not affiliated with either of those products. This is also the first time that I have heard about either of them. You will need to seek out help from whoever the owner of those websites is.
