### ISSUE TITLE
Russian ChatterBot

### ISSUE THREAD

**Issue by Nonamow** [gunthercox/ChatterBot#1538]
Firstly, you are very cool guys! Secondly, how can I use this [link](https://github.com/gunthercox/ChatterBot/issues/345) to create chatterbot.logic.MathematicalEvaluation with russian words? Also I'm trying to train bot with corpus-json files like in [russian site](https://habr.com/post/323570/) but python-script just ignored it (they are not some output). With YAMI-files all works perfectly... 
Thanks!
Code:
`# -*- coding: utf-8 -*-
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os

bot = ChatBot(
    name="Robby",
    input_adapter="chatterbot.input.TerminalAdapter",
    output_adapter="chatterbot.output.TerminalAdapter",
    logic_adapters=[{
        'import_path' : 'chatterbot.logic.BestMatch'
       },
       {
        'import_path': 'chatterbot.logic.MathematicalEvaluation',
        'math_words_language' : 'russian'
       },
       {
        'import_path': 'chatterbot.logic.LowConfidenceAdapter',
        'threshold': 0.45,
        'default_response': 'Как интересно. А расскажешь еще что-нибудь?'
       }],
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    filters=["chatterbot.filters.RepetitiveResponseFilter"],
    database='./database.db'
  )

print("Производится обучение на corpus данных")
# train chatterbot with our corpus (all files if ./corpus folder)
bot.set_trainer(ChatterBotCorpusTrainer)
bot.train("./corpus")
print("Обучение завершено")

print("Type something to begin...")

# The following loop will execute each time the user enters input
while True:
    try:
        # We pass None to this method because the parameter
        # is not used by the TerminalAdapter
        bot_input = bot.get_response(None)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break`
I can send json files if it need.

**Comment by gunthercox** [comment]
Hi @Nonamow, you can use the Russian language support of the `MathematicalEvaluation` adapter like this:

```python
bot = ChatBot(
    # ...
    language='RUS'
    # ...
)
```
