### ISSUE TITLE
Possible to apply multilingual within a bot?

### ISSUE THREAD

**Issue by herboratory** [gunthercox/ChatterBot#1541]
Hello! Thanks for making chatterbot that helps my project a lot.
I am writing a bot that will link to various IM platforms. I want to let the users choose and set either English or Chinese in the future. I would like to know if it’s possible to apply 2 languages within a bot?
This is my very first project and my programming skill is not good. If my question is inappropriate here, please free to tell me and refer where I can ask.
Many thanks!

**Comment by gunthercox** [comment]
Hi @herboratory, I would recommend creating one bot per language as this may be simpler to implement with the current version of ChatterBot.

***

**Note:** A question similar to this recently came up (#1536) where the goal was to have a single chat bot for multiple types of users (as opposed to the multiple types of languages as described in this case). I am currently considering adding functionality to ChatterBot that would make it easier to implement the functionality that you are looking for.

**Comment by herboratory** [comment]
OK! That would be great! Thank you so much for the reply! :)

**Comment by gunthercox** [comment]
I have made some changes that should be available when the next version of ChatterBot is released.

Here is a small example for your convenience, I hope this helps.

```python
from chatterbot import ChatBot
from chatterbot.conversation import Statement


chatbot = ChatBot(
    'Example Bot',
    # This database will be a temporary in-memory database
    database_uri=None
)

english_statements = [
    Statement(text='I like dogs.', tags=['language:english']),
    Statement(text='I like cats.', tags=['language:english']),
    Statement(text='I like animals.', tags=['language:english'])
]

chinese_statements = [
    Statement(text='我喜欢狗', tags=['language:chinese']),
    Statement(text='我喜欢猫', tags=['language:chinese']),
    Statement(text='我喜欢动物', tags=['language:chinese'])
]

chatbot.storage.create_many(
    english_statements + chinese_statements
)

# Return a response from "english_statements"
response_from_english = chatbot.get_response(
    'How are you?',
    additional_response_selection_parameters={
        'tags': ['language:english']
    }
)

# Return a response from "chinese_statements"
response_from_chinese = chatbot.get_response(
    'How are you?',
    additional_response_selection_parameters={
        'tags': ['language:chinese']
    }
)

print('Response from english collection:', response_from_english.text)
print('Response from chinese collection:', response_from_chinese.text)
```
