### ISSUE TITLE
Chatterbot Connecting Mysql Database

### ISSUE THREAD

**Issue by lxz1992** [gunthercox/ChatterBot#1546]
Hi guys, I want to put the chatterbot in the Django project and connect the MySQL database in the server. How to connect the MySQL database?  Thanks a lot.

**Comment by gunthercox** [comment]
Hi @lxz1992, when using ChatterBot with Django the chat bot can have access to whatever Database your Django setup has been configured to use. Here are some instructions for configuring Django to use MySQL.

https://docs.djangoproject.com/en/2.1/ref/databases/#connecting-to-the-database

**Comment by gersosa** [comment]
But it throws error: django_chatterbot.Statement.text: (mysql.E001) MySQL does not allow unique CharFields to have a max_length > 255.
