### ISSUE TITLE
Concurrent connections

### ISSUE THREAD

**Issue by kulkarniniraj** [gunthercox/ChatterBot#1547]
Since create_conversation is removed now (in 1.0 alpha), how to create concurrent conversation?

**Comment by gunthercox** [comment]
Conversations are now "created" by passing a `conversation` parameter to the `Statement` object.
You can now think of a conversation as something like a label for a statement.

```python
Statement(
    text="...",
    conversation="conversation_1"
)
```

The value you set for `conversation` can be any string you choose.

**Comment by kulkarniniraj** [comment]
Thanks. That is easy to use.
