### ISSUE TITLE
please tell us the detail of how the bot to study itself

### ISSUE THREAD

**Issue by JasonZhang1991** [gunthercox/ChatterBot#1556]
please tell us the detail of how the bot to study itself

**Comment by gunthercox** [comment]
In general, this is achieved by comparing known examples of responses that have been given to the bot (we assume that whoever the bot interacts with is a trustworthy source, someone who knows how to respond correctly) and those responses are used in the future to respond to similar inputs.

More information about this can be found in the documentation.
https://chatterbot.readthedocs.io/en/latest/#how-chatterbot-works

**Comment by JasonZhang1991** [comment]
> In general, this is achieved by comparing known examples of responses that have been given to the bot (we assume that whoever the bot interacts with is a trustworthy source, someone who knows how to respond correctly) and those responses are used in the future to respond to similar inputs.
> 
> More information about this can be found in the documentation.
> https://chatterbot.readthedocs.io/en/latest/#how-chatterbot-works

thank you very much
