### ISSUE TITLE
How to delete chatterbot learning data.

### ISSUE THREAD

**Issue by syu3** [gunthercox/ChatterBot#1557]
database-Aを学習させた後、学習したものを一度消して、次にdatabase-Bを学習させたいです。
しかし、私が試した方法では一度学習したものを消すことができません。

聞きたいこと
-学習したデータを削除する方法

**Comment by vkosuri** [comment]
delete ``sqlite.db`` in your workspace. I think it's in the current directory.

**Comment by syu3** [comment]
@vkosuri 
I want to execute code and realize it.
However, if you do this with python, you get a `Server Error (500)` error
```
import os
os.remove (path)
```
How can I do it?

**Comment by gunthercox** [comment]
Here is an example of removing the content from a chat bot's database.

```python
from chatterbot import ChatBot

chatbot = ChatBot('Example Bot')

chatbot.storage.drop()
```
