### ISSUE TITLE
why there always an error while running running `python manage.py runserver 0.0.0.0:8000`

### ISSUE THREAD

**Issue by CharlieChengtianyue** [gunthercox/ChatterBot#1559]
although someperson did ask this question
i am confused about what is wrong toward this?

NoReverseMatch at /

'chatterbot' is not a registered namespace

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/
Django Version: 	2.1.5
Exception Type: 	NoReverseMatch
Exception Value: 	

'chatterbot' is not a registered namespace

Exception Location: 	/home/charliecheng/.local/lib/python3.5/site-packages/django/urls/base.py in reverse, line 86
Python Executable: 	/usr/bin/python3
Python Version: 	3.5.2
Python Path: 	

['/home/charliecheng/Desktop/ChatterBot-master/examples/django_app',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/home/charliecheng/.local/lib/python3.5/site-packages',
 '/usr/local/lib/python3.5/dist-packages',
 '/usr/local/lib/python3.5/dist-packages/ChatterBot-1.0.0a3-py3.5.egg',
 '/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.2.16-py3.5-linux-x86_64.egg',
 '/usr/local/lib/python3.5/dist-packages/python_twitter-3.5-py3.5.egg',
 '/usr/local/lib/python3.5/dist-packages/pymongo-3.7.2-py3.5-linux-x86_64.egg',
 '/usr/local/lib/python3.5/dist-packages/chatterbot_corpus-1.2.0-py3.5.egg',
 '/usr/local/lib/python3.5/dist-packages/requests_oauthlib-1.1.0-py3.5.egg',
 '/usr/local/lib/python3.5/dist-packages/future-0.17.1-py3.5.egg',
 '/usr/local/lib/python3.5/dist-packages/PyYAML-3.13-py3.5-linux-x86_64.egg',
 '/usr/local/lib/python3.5/dist-packages/oauthlib-2.1.0-py3.5.egg',
 '/usr/lib/python3/dist-packages']

Server time: 	Sat, 12 Jan 2019 14:42:56 +0000
Error during template rendering

In template /home/charliecheng/Desktop/ChatterBot-master/examples/django_app/example_app/templates/nav.html, error at line 21
'chatterbot' is not a registered namespace
11 	    <li class="nav-item">
12 	      <a class="nav-link" href="http://chatterbot.readthedocs.io/en/stable/">Documentation</a>
13 	    </li>
14 	    <li class="nav-item">
15 	      <a class="nav-link" href="https://github.com/gunthercox/ChatterBot">GitHub</a>
16 	    </li>
17 	  </ul>
18 	
19 	  <ul class="nav navbar-nav float-xs-right">
20 	    <li class="nav-item">
21 	      <a class="nav-link" href="{% url 'chatterbot:chatterbot' %}">API</a>
22 	    </li>
23 	    <li class="nav-item">
24 	      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
25 	    </li>
26 	  </ul>
27 	</nav>
Traceback Switch to copy-and-paste view

    /home/charliecheng/.local/lib/python3.5/site-packages/django/urls/base.py in reverse

                        extra, resolver = resolver.namespace_dict[ns]

         ...
    ▶ Local vars
    During handling of the above exception ('chatterbot'), another exception occurred:
    /home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/exception.py in inner

                    response = get_response(request)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response

                        response = self.process_exception_by_middleware(e, request)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response

                        response = response.render()

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/response.py in render

                    self.content = self.rendered_content

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/response.py in rendered_content

                content = template.render(context, self._request)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/backends/django.py in render

                    return self.template.render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in render

                            return self._render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in _render

                return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in render

                        bit = node.render_annotated(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/loader_tags.py in render

                    return template.render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in render

                        return self._render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in _render

                return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in render

                        bit = node.render_annotated(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/template/defaulttags.py in render

                    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)

         ...
    ▶ Local vars
    /home/charliecheng/.local/lib/python3.5/site-packages/django/urls/base.py in reverse

                            raise NoReverseMatch("%s is not a registered namespace" % key)

         ...
    ▶ Local vars

Request information
USER

[unable to retrieve the current user]
GET

No GET data
POST

No POST data
FILES

No FILES data
COOKIES

No cookie data
META
Variable 	Value
CLUTTER_IM_MODULE 	

'xim'

COMPIZ_CONFIG_PROFILE 	

'ubuntu'

CONTENT_LENGTH 	

''

CONTENT_TYPE 	

'text/plain'

DBUS_SESSION_BUS_ADDRESS 	

'unix:abstract=/tmp/dbus-zfV5ALKRKJ'

DEFAULTS_PATH 	

'/usr/share/gconf/ubuntu.default.path'

DESKTOP_SESSION 	

'ubuntu'

DISPLAY 	

':0'

DJANGO_SETTINGS_MODULE 	

'example_app.settings'

GATEWAY_INTERFACE 	

'CGI/1.1'

GDMSESSION 	

'ubuntu'

GDM_LANG 	

'en_US'

GNOME_DESKTOP_SESSION_ID 	

'this-is-deprecated'

GNOME_KEYRING_CONTROL 	

''

GNOME_KEYRING_PID 	

''

GPG_AGENT_INFO 	

'/home/charliecheng/.gnupg/S.gpg-agent:0:1'

GTK2_MODULES 	

'overlay-scrollbar'

GTK_IM_MODULE 	

'ibus'

GTK_MODULES 	

'gail:atk-bridge:unity-gtk-module'

HOME 	

'/home/charliecheng'

HTTP_ACCEPT 	

'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'

HTTP_ACCEPT_ENCODING 	

'gzip, deflate'

HTTP_ACCEPT_LANGUAGE 	

'en-US,en;q=0.5'

HTTP_CONNECTION 	

'keep-alive'

HTTP_HOST 	

'127.0.0.1:8000'

HTTP_USER_AGENT 	

'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0'

IM_CONFIG_PHASE 	

'1'

INSTANCE 	

''

JOB 	

'dbus'

LANG 	

'en_US.UTF-8'

LANGUAGE 	

'en_US'

LESSCLOSE 	

'/usr/bin/lesspipe %s %s'

LESSOPEN 	

'| /usr/bin/lesspipe %s'

LOGNAME 	

'charliecheng'

LS_COLORS 	

'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'

MANDATORY_PATH 	

'/usr/share/gconf/ubuntu.mandatory.path'

PATH 	

'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

PATH_INFO 	

'/'

PWD 	

'/home/charliecheng/Desktop/ChatterBot-master/examples/django_app'

QT4_IM_MODULE 	

'xim'

QT_ACCESSIBILITY 	

'1'

QT_IM_MODULE 	

'ibus'

QT_LINUX_ACCESSIBILITY_ALWAYS_ON 	

'1'

QT_QPA_PLATFORMTHEME 	

'appmenu-qt5'

QUERY_STRING 	

''

REMOTE_ADDR 	

'127.0.0.1'

REMOTE_HOST 	

''

REQUEST_METHOD 	

'GET'

RUN_MAIN 	

'true'

SCRIPT_NAME 	

''

SERVER_NAME 	

'localhost'

SERVER_PORT 	

'8000'

SERVER_PROTOCOL 	

'HTTP/1.1'

SERVER_SOFTWARE 	

'WSGIServer/0.2'

SESSION 	

'ubuntu'

SESSIONTYPE 	

'gnome-session'

SESSION_MANAGER 	

'local/ubuntu:@/tmp/.ICE-unix/1634,unix/ubuntu:/tmp/.ICE-unix/1634'

SHELL 	

'/bin/bash'

SHLVL 	

'1'

SSH_AUTH_SOCK 	

'/run/user/1000/keyring/ssh'

TERM 	

'xterm-256color'

TZ 	

'UTC'

UPSTART_SESSION 	

'unix:abstract=/com/ubuntu/upstart-session/1000/1392'

USER 	

'charliecheng'

VTE_VERSION 	

'4205'

WINDOWID 	

'54526215'

XAUTHORITY 	

'/home/charliecheng/.Xauthority'

XDG_CONFIG_DIRS 	

'/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg'

XDG_CURRENT_DESKTOP 	

'Unity'

XDG_DATA_DIRS 	

'/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'

XDG_GREETER_DATA_DIR 	

'/var/lib/lightdm-data/charliecheng'

XDG_MENU_PREFIX 	

'gnome-'

XDG_RUNTIME_DIR 	

'/run/user/1000'

XDG_SEAT 	

'seat0'

XDG_SEAT_PATH 	

'/org/freedesktop/DisplayManager/Seat0'

XDG_SESSION_DESKTOP 	

'ubuntu'

XDG_SESSION_ID 	

'c2'

XDG_SESSION_PATH 	

'/org/freedesktop/DisplayManager/Session0'

XDG_SESSION_TYPE 	

'x11'

XDG_VTNR 	

'7'

XMODIFIERS 	

'@im=ibus'

_ 	

'/usr/bin/python3'

wsgi.errors 	

<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>

wsgi.file_wrapper 	

''

wsgi.input 	

<django.core.handlers.wsgi.LimitedStream object at 0x7ff7da66dcc0>

wsgi.multiprocess 	

False

wsgi.multithread 	

True

wsgi.run_once 	

False

wsgi.url_scheme 	

'http'

wsgi.version 	

(1, 0)

Settings
Using settings module example_app.settings
Setting 	Value
ABSOLUTE_URL_OVERRIDES 	

{}

ADMINS 	

[]

ALLOWED_HOSTS 	

[]

APPEND_SLASH 	

True

AUTHENTICATION_BACKENDS 	

['django.contrib.auth.backends.ModelBackend']

AUTH_PASSWORD_VALIDATORS 	

'********************'

AUTH_USER_MODEL 	

'auth.User'

BASE_DIR 	

'/home/charliecheng/Desktop/ChatterBot-master/examples/django_app'

CACHES 	

{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

CACHE_MIDDLEWARE_ALIAS 	

'default'

CACHE_MIDDLEWARE_KEY_PREFIX 	

'********************'

CACHE_MIDDLEWARE_SECONDS 	

600

CHATTERBOT 	

{'django_app_name': 'django_chatterbot', 'name': 'Django ChatterBot Example'}

CSRF_COOKIE_AGE 	

31449600

CSRF_COOKIE_DOMAIN 	

None

CSRF_COOKIE_HTTPONLY 	

False

CSRF_COOKIE_NAME 	

'csrftoken'

CSRF_COOKIE_PATH 	

'/'

CSRF_COOKIE_SAMESITE 	

'Lax'

CSRF_COOKIE_SECURE 	

False

CSRF_FAILURE_VIEW 	

'django.views.csrf.csrf_failure'

CSRF_HEADER_NAME 	

'HTTP_X_CSRFTOKEN'

CSRF_TRUSTED_ORIGINS 	

[]

CSRF_USE_SESSIONS 	

False

DATABASES 	

{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/home/charliecheng/Desktop/ChatterBot-master/examples/django_app/db.sqlite3',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': ''}}

DATABASE_ROUTERS 	

[]

DATA_UPLOAD_MAX_MEMORY_SIZE 	

2621440

DATA_UPLOAD_MAX_NUMBER_FIELDS 	

1000

DATETIME_FORMAT 	

'N j, Y, P'

DATETIME_INPUT_FORMATS 	

['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']

DATE_FORMAT 	

'N j, Y'

DATE_INPUT_FORMATS 	

['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']

DEBUG 	

True

DEBUG_PROPAGATE_EXCEPTIONS 	

False

DECIMAL_SEPARATOR 	

'.'

DEFAULT_CHARSET 	

'utf-8'

DEFAULT_CONTENT_TYPE 	

'text/html'

DEFAULT_EXCEPTION_REPORTER_FILTER 	

'django.views.debug.SafeExceptionReporterFilter'

DEFAULT_FILE_STORAGE 	

'django.core.files.storage.FileSystemStorage'

DEFAULT_FROM_EMAIL 	

'webmaster@localhost'

DEFAULT_INDEX_TABLESPACE 	

''

DEFAULT_TABLESPACE 	

''

DISALLOWED_USER_AGENTS 	

[]

EMAIL_BACKEND 	

'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST 	

'localhost'

EMAIL_HOST_PASSWORD 	

'********************'

EMAIL_HOST_USER 	

''

EMAIL_PORT 	

25

EMAIL_SSL_CERTFILE 	

None

EMAIL_SSL_KEYFILE 	

'********************'

EMAIL_SUBJECT_PREFIX 	

'[Django] '

EMAIL_TIMEOUT 	

None

EMAIL_USE_LOCALTIME 	

False

EMAIL_USE_SSL 	

False

EMAIL_USE_TLS 	

False

FILE_CHARSET 	

'utf-8'

FILE_UPLOAD_DIRECTORY_PERMISSIONS 	

None

FILE_UPLOAD_HANDLERS 	

['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']

FILE_UPLOAD_MAX_MEMORY_SIZE 	

2621440

FILE_UPLOAD_PERMISSIONS 	

None

FILE_UPLOAD_TEMP_DIR 	

None

FIRST_DAY_OF_WEEK 	

0

FIXTURE_DIRS 	

[]

FORCE_SCRIPT_NAME 	

None

FORMAT_MODULE_PATH 	

None

FORM_RENDERER 	

'django.forms.renderers.DjangoTemplates'

IGNORABLE_404_URLS 	

[]

INSTALLED_APPS 	

('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'chatterbot.ext.django_chatterbot',
 'example_app')

INTERNAL_IPS 	

[]

LANGUAGES 	

[('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]

LANGUAGES_BIDI 	

['he', 'ar', 'fa', 'ur']

LANGUAGE_CODE 	

'en-us'

LANGUAGE_COOKIE_AGE 	

None

LANGUAGE_COOKIE_DOMAIN 	

None

LANGUAGE_COOKIE_NAME 	

'django_language'

LANGUAGE_COOKIE_PATH 	

'/'

LOCALE_PATHS 	

[]

LOGGING 	

{}

LOGGING_CONFIG 	

'logging.config.dictConfig'

LOGIN_REDIRECT_URL 	

'/accounts/profile/'

LOGIN_URL 	

'/accounts/login/'

LOGOUT_REDIRECT_URL 	

None

MANAGERS 	

[]

MEDIA_ROOT 	

''

MEDIA_URL 	

''

MESSAGE_STORAGE 	

'django.contrib.messages.storage.fallback.FallbackStorage'

MIDDLEWARE 	

[]

MIDDLEWARE_CLASSES 	

('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

MIGRATION_MODULES 	

{}

MONTH_DAY_FORMAT 	

'F j'

NUMBER_GROUPING 	

0

PASSWORD_HASHERS 	

'********************'

PASSWORD_RESET_TIMEOUT_DAYS 	

'********************'

PREPEND_WWW 	

False

ROOT_URLCONF 	

'example_app.urls'

SECRET_KEY 	

'********************'

SECURE_BROWSER_XSS_FILTER 	

False

SECURE_CONTENT_TYPE_NOSNIFF 	

False

SECURE_HSTS_INCLUDE_SUBDOMAINS 	

False

SECURE_HSTS_PRELOAD 	

False

SECURE_HSTS_SECONDS 	

0

SECURE_PROXY_SSL_HEADER 	

None

SECURE_REDIRECT_EXEMPT 	

[]

SECURE_SSL_HOST 	

None

SECURE_SSL_REDIRECT 	

False

SERVER_EMAIL 	

'root@localhost'

SESSION_CACHE_ALIAS 	

'default'

SESSION_COOKIE_AGE 	

1209600

SESSION_COOKIE_DOMAIN 	

None

SESSION_COOKIE_HTTPONLY 	

True

SESSION_COOKIE_NAME 	

'sessionid'

SESSION_COOKIE_PATH 	

'/'

SESSION_COOKIE_SAMESITE 	

'Lax'

SESSION_COOKIE_SECURE 	

False

SESSION_ENGINE 	

'django.contrib.sessions.backends.db'

SESSION_EXPIRE_AT_BROWSER_CLOSE 	

False

SESSION_FILE_PATH 	

None

SESSION_SAVE_EVERY_REQUEST 	

False

SESSION_SERIALIZER 	

'django.contrib.sessions.serializers.JSONSerializer'

SETTINGS_MODULE 	

'example_app.settings'

SHORT_DATETIME_FORMAT 	

'm/d/Y P'

SHORT_DATE_FORMAT 	

'm/d/Y'

SIGNING_BACKEND 	

'django.core.signing.TimestampSigner'

SILENCED_SYSTEM_CHECKS 	

[]

STATICFILES_DIRS 	

('/home/charliecheng/Desktop/ChatterBot-master/examples/django_app/example_app/static',)

STATICFILES_FINDERS 	

['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']

STATICFILES_STORAGE 	

'django.contrib.staticfiles.storage.StaticFilesStorage'

STATIC_ROOT 	

None

STATIC_URL 	

'/static/'

TEMPLATES 	

[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]

TEST_NON_SERIALIZED_APPS 	

[]

TEST_RUNNER 	

'django.test.runner.DiscoverRunner'

THOUSAND_SEPARATOR 	

','

TIME_FORMAT 	

'P'

TIME_INPUT_FORMATS 	

['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']

TIME_ZONE 	

'UTC'

USE_I18N 	

True

USE_L10N 	

True

USE_THOUSAND_SEPARATOR 	

False

USE_TZ 	

True

USE_X_FORWARDED_HOST 	

False

USE_X_FORWARDED_PORT 	

False

WSGI_APPLICATION 	

'example_app.wsgi.application'

X_FRAME_OPTIONS 	

'SAMEORIGIN'

YEAR_MONTH_FORMAT 	

'F Y'

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by gunthercox** [comment]
Hi @CharlieChengtianyue, a fix has been merged. See #1552 for details.

**Comment by CharlieChengtianyue** [comment]
Hi @gunthercox, thanks for your reply, although the website can work now, but if i submit anything, nothing happens, and there are lots of errors in my terminal.
my python version is 3.5 and django is 2.1, can this app fit these versions?

**Comment by CharlieChengtianyue** [comment]
here are the errors:
Internal Server Error: /api/chatterbot/
Traceback (most recent call last):
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_chatterbot_conversation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/charliecheng/Desktop/django_app/example_app/views.py", line 35, in post
    response = self.chatterbot.get_response(input_data)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 110, in get_response
    self.default_conversation_id = self.storage.create_conversation()
  File "/home/charliecheng/.local/lib/python3.5/site-packages/chatterbot/storage/django_storage.py", line 174, in create_conversation
    conversation = Conversation.objects.create()
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/charliecheng/.local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_chatterbot_conversation
[13/Jan/2019 05:59:45] "POST /api/chatterbot/ HTTP/1.1" 500 20118

**Comment by gunthercox** [comment]
Python 3.5 and Django 2.1 are both the ideal versions to be using.

For this error, I think this line is the describes what the issue is: `django.db.utils.OperationalError: no such table: django_chatterbot_conversation`. It sounds like your database is missing a table that it needs.

**Comment by CharlieChengtianyue** [comment]
so what i need to do is to install chatterbot again?
i am new here and i am not quite familiar with this

**Comment by gunthercox** [comment]
Installing ChatterBot again probably won't fix this issue. As long as there isn't any data in your database that you want to keep, I'd recommend just deleting the database file (it is probably labeled something like `database.sqlite3`). Then, after restarting your application, a new database will be created with the correct tables.

Please let me know if you encounter any issues with this.

**Comment by CharlieChengtianyue** [comment]
thanks sir, after i deleted this file(db.sqlite3), a new database did came out. But it is still empty, and in the app still nothing pops out? 
I am afraid simply deleting it cannot fix the problem

**Comment by gunthercox** [comment]
I think you are correct. Can you make sure you have the latest version of ChatterBot installed? It should be version 1.0.0
