### ISSUE TITLE
What to do now for low confidence?

### ISSUE THREAD

**Issue by jkries** [gunthercox/ChatterBot#1571]
I see that as of this new Version 1, the LowConfidenceAdapter has been removed.

What has replaced it?

I have the following code which is now broken:

bot = ChatBot(
    "Chat Bot",
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': 'I don\'t have a response for that. What else can we talk about?'
        }
    ],
    response_selection_method=get_random_response, #Comment this out if you want best response
    input_adapter="chatterbot.input.VariableInputTypeAdapter",
    output_adapter="chatterbot.output.OutputAdapter",
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    database="botData.sqlite3"
)

**Comment by gunthercox** [comment]
The `BestMatch` logic adapter not encompasses the previous functionality of the `LowConfidenceAdapter`.

You can make the following change to continue to use your code the way you were before.

```python
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'maximum_similarity_threshold': 0.65
            'default_response': 'I don't have a response for that. What else can we talk about?'
        }
    ]
```

I hope this helps, please let me know if you have any questions.

**Comment by jkries** [comment]
That solves that issue, thank you!

I have another question, but I will open a separate ticket as it seems unrelated.
