### ISSUE TITLE
Link to docs for version 0.8.7

### ISSUE THREAD

**Issue by borissevo** [gunthercox/ChatterBot#1581]
Are the docs for version 0.8.7 still somewhere available?

https://media.readthedocs.org/pdf/chatterbot/stable/chatterbot.pdf are the docs for the current release (1.0.0).

**Comment by gunthercox** [comment]
Hi @borissevo, I've added version 0.8.7 back to the available documentation versions.
https://chatterbot.readthedocs.io/en/0.8.7/
I would highly recommend using version 1.0 if possible because I will no longer be making changes to support the 0.8 series.

**Comment by borissevo** [comment]
Thank you @gunthercox for the docs.

We are planning to upgrade to 1.0.0, but we had couple of problems with 1.0.0 and that's why we are still on 0.8.7. Examples of problems: 

- changes related to LowConfidenceAdapter/threashold
- differences in data persisted in database
- the same training set that gives good results in 0.8.7, gives worse results in 1.0.0

**Comment by gunthercox** [comment]
If it helps at all, here is an example of how an instance of the `BestMatch` logic adapter be used to recreate the previous functionality of the `LowConfidenceAdapter`.

```python
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'maximum_similarity_threshold': 0.65,
            'default_response': 'I don\'t have a response for that. What else can we talk about?'
        }
    ]
```

***

The differences in how data is persisted in database will likely be the biggest challenge, but I hope that the design used in 1.0 will provide enough value to make it worth while to upgrade.

***

I'm very interested to hear that you experienced a decrease in the quality of results in 1.0. To the best of my knowledge this should not happen. If you can provide any sample data that I can use to recreate this, I would be happy to try to determine the cause and fix the issue.
