### ISSUE TITLE
str' object is not callable 

### ISSUE THREAD

**Issue by sarangjain40** [gunthercox/ChatterBot#1584]
I am running this code. 

from chatterbot import ChatBot
from chatterbot.conversation import Statement
from chatterbot.trainers import ListTrainer
from chatterbot.comparisons import levenshtein_distance
from chatterbot.comparisons import jaccard_similarity
"""
This example shows how to create a chat bot that
will learn responses based on an additional feedback
element from the user.
"""

# Uncomment the following line to enable verbose logging
import logging
logging.basicConfig(level=logging.INFO)

# Create a new instance of a ChatBot
bot = ChatBot(
    'Feedback Learning Bot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    statement_comparison_function=jaccard_similarity,
    logic_adapters=[
         {
            'import_path': 'chatterbot.logic.BestMatch',
            'statement_comparison_function': 'chatterbot.comparisons.levenshtein_distance',
            'response_selection_method': 'chatterbot.response_selection.get_first_response'
         }
    ]
)

def get_feedback():
    print('\nInside Get Feedback\n')
    text = input()

    if 'yes' in text.lower():
        return False
    elif 'no' in text.lower():
        return True
    elif 'exit' in text.lower():
        return True
    else:
        print('Please type either "Yes" or "No"')
        return get_feedback()

print('Type something to begin...')

# The following loop will execute each time the user enters input
while True:
    try:
        print('Sarang1!')
        print('Sarang1!')
        print('Sarang1!')
        
        print('Sarang1!')
        add_param=None
        input_statement = Statement(text=input())
        response = bot.generate_response(
            Statement(input_statement)
        )

        print('\n Is "{}" a coherent response to "{}"? \n'.format(
            response.text,
            input_statement.text
        ))
        print('Sarang2!')
        if get_feedback():
            print('please input the correct one')
            print('Sarang3!')
            correct_response = Statement(text=input())
            if correct_response == 'exit':
                break
            bot.learn_response(correct_response, input_statement)
            print('Responses added to bot!')
            print('Sarang4!')
    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break

I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-31272a2d710b> in <module>()
     58         input_statement = Statement(text=input())
     59         response = bot.generate_response(
---> 60             Statement(input_statement)
     61         )
     62 

D:\Users\Sarang_Jain\Anaconda3\lib\site-packages\chatterbot\chatterbot.py in generate_response(self, input_statement, additional_response_selection_parameters)
    152             if adapter.can_process(input_statement):
    153 
--> 154                 output = adapter.process(input_statement, additional_response_selection_parameters)
    155                 results.append((output.confidence, output, ))
    156 

D:\Users\Sarang_Jain\Anaconda3\lib\site-packages\chatterbot\logic\best_match.py in process(self, input_statement, additional_response_selection_parameters)
     88                 input_statement,
     89                 response_list,
---> 90                 self.chatbot.storage
     91             )
     92 

TypeError: 'str' object is not callable

If I remove this line from logic_adapters section, it works fine.  
'response_selection_method': 'chatterbot.response_selection.get_first_response'

Anyone please help me where  I am making a mistake.

**Comment by basr18** [comment]
Hi, I have the same issue. I try to use your solution but still the same. Is there another way to make it work?

**Comment by basr18** [comment]
In my chatbot, the logic adapter are:

logic_adapters = [{
            "import_path": 'chatterbot.logic.BestMatch',
            "statement_comparision_function": 'chatterbot.comparisons.SynsetDistance',
            "response_selection_method": 'chatterbot.response_selection.get_random_response'
}]
