### ISSUE TITLE
AttributeError: type object 'ChatBot' has no attribute 'storage'

### ISSUE THREAD

**Issue by dilzeet100** [gunthercox/ChatterBot#1586]
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os

bot = ChatBot('Bot')

trainer = ChatterBotCorpusTrainer(ChatBot)
trainer.train("chatterbot.corpus.english")

for files in os.listdir('C:/Users/Dell/Downloads/chatterbot-corpus-master/chatterbot_corpus/data/english/'):
data = open('C:/Users/Dell/Downloads/chatterbot-corpus-master/chatterbot_corpus/data/english/' + files, 'r').readlines()
bot.train(data)

while True:
message = input('You:')
if message.strip() != 'Bye':
reply = bot.get_response(message)
print('ChatBot:',reply)

if message.strip() == 'Bye':
    print('ChatBot : bye')
    break

this error is showing...

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data] C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data] Package averaged_perceptron_tagger is already up-to-
[nltk_data] date!
[nltk_data] Downloading package punkt to
[nltk_data] C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data] Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data] C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data] Package stopwords is already up-to-date!
Training ai.yml: [ ] 1%Traceback (most recent call last):
File "C:\Users\Dell\Desktop\chatbot.py", line 9, in
trainer.train("chatterbot.corpus.english")
File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\trainers.py", line 157, in train
statement_search_text = self.chatbot.storage.tagger.get_bigram_pair_string(text)
AttributeError: type object 'ChatBot' has no attribute 'storage'

**Comment by gunthercox** [comment]
Hi @dilzeet100, I made a few changes to your code, try this:

```python
from chatterbot import ChatBot #import the chatbot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os

bot= ChatBot('Bot')
trainer = ChatterBotCorpusTrainer(bot)

corpus_path = 'C:/Users/Dell/Downloads/chatterbot-corpus-master/chatterbot_corpus/data/english/'

for file in os.listdir(corpus_path):
    trainer.train(corpus_path + file)

while True:
    message = input('You:')
    print(message)
    if message.strip() == 'Bye':
        print('ChatBot: Bye')
        break
    else:
        reply = bot.get_response(message)
        print('ChatBot:', reply)
```

Also, please make sure to download the latest copy of the corpus data. I have made changes that fix a few lines of invalid data.

**Comment by dilzeet100** [comment]
hello, problem is still persist...pls check

C:\Users\Dell\Desktop>chatbot.py
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Training ai.yml: [####################] 100%
Training botprofile.yml: [####################] 100%
Training computers.yml: [####################] 100%
Training conversations.yml: [####################] 100%
Training emotion.yml: [####################] 100%
Training food.yml: [####################] 100%
Training gossip.yml: [####################] 100%
Training greetings.yml: [####################] 100%
Training health.yml: [####################] 100%
Training history.yml: [####################] 100%
Training humor.yml: [####################] 100%
Training literature.yml: [#############       ] 67%Traceback (most recent
call last):
  File "C:\Users\Dell\Desktop\chatbot.py", line 11, in <module>
    trainer.train(corpus_path + file)
  File
"C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\trainers.py",
line 157, in train
    statement_search_text =
self.chatbot.storage.tagger.get_bigram_pair_string(text)
  File
"C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\tagging.py",
line 135, in get_bigram_pair_string
    for sentence in self.tokenize_sentence(text.strip()):
AttributeError: 'dict' object has no attribute 'strip'



thanks for your help

**Comment by gunthercox** [comment]
Did you make sure you downloaded the latest copy of the ChatterBot corpus data?

**Comment by dilzeet100** [comment]
Yes...I think so...
If not..then share link for latest corpus data plss

**Comment by gunthercox** [comment]
https://github.com/gunthercox/chatterbot-corpus

**Comment by dilzeet100** [comment]
thank you so much buddy for your help

**Comment by dilzeet100** [comment]
buddy, I want to set some questions on my own for chatbot...how can I do
that??

**Comment by gunthercox** [comment]
@dilzeet100 I'm not certain what you are asking. Perhaps you are looking to enter your own training data, similar to this example: https://github.com/gunthercox/ChatterBot/blob/master/examples/training_example_list_data.py

**Comment by dilzeet100** [comment]
Hello,
I want to know that,
like chatterbot corpus has already files having set of questions and
answers...
I want to make my own file with questions and responses,,,and want to load
it in my chatbot..how I can do that

**Comment by gunthercox** [comment]
If you would like to create your own corpus files, it is very easy to do so.

First, create the files containing the data that you want them to contain. An explanation of how to format the data can be found here: https://chatterbot-corpus.readthedocs.io/en/latest/data.html

Then, you can pass the path to the directory or file that contains the data into the train method.
```
trainer.train('path-to/my-data/')
```

**Comment by dilzeet100** [comment]
thanks a lot for your help
