### ISSUE TITLE
Can i train multiple answers to the same question ?

### ISSUE THREAD

**Issue by kangaroocancode** [gunthercox/ChatterBot#1587]
for example the question is asking for some recommendation, so i want the bot randomly provide different answer, is it possible to do this? how should i format the corpus?

- - Question
   - Answer 1
   - Answer 2 
   - Answer 3

OR ?

- - Question
   - Answer 1

- - Question
   - Answer 2

- - Question
   - Answer 3

**Comment by gunthercox** [comment]
Yes, this is possible to do. Here is a quick example.

```python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot('Example Bot')

trainer = ListTrainer(chatbot)

trainer.train([
    'Hello, how are you?',
    'I am doing well.',
    'That is good to hear.',
    'Thank you'
])

# You can train with a second list of data to add response variations

trainer.train([
    'Hello, how are you?',
    'I am great.',
    'That is awesome.',
    'Thanks'
])
```
