### ISSUE TITLE
Purging database

### ISSUE THREAD

**Issue by justquantum** [gunthercox/ChatterBot#159]
I am using ChatterBot as a feature in a Kik Bot I've been developing as a hobby. As ChatterBot learns things from users talking to it, it can learn some not so great things, some of which end up violating the Kik terms of service for bots. I would like to be able to completely purge the database and reteach from the corpus via a special command only I have access to, but I'm not sure how I would go about doing this. Can I just delete the db file while the script is running or do I need to do something special?

**Comment by gunthercox** [comment]
You can delete the database or you can remove what a bot has learned by calling: `mychatbot.storage.drop()`.

For example:
```python
mychatbot = ChatBot("Example")
mychatbot.storage.drop()
```

**Comment by justquantum** [comment]
awesome, thanks

**Comment by justquantum** [comment]
how do I generate a new database without reinstatiating the ChatBot?

**Comment by gunthercox** [comment]
After you delete the old database, ChatterBot should create a new one automatically the next time you run your program.

**Comment by justquantum** [comment]
yeah, but I was wondering if there was a way to regenerate it without restarting/reinstantiating

**Comment by gunthercox** [comment]
I'm not sure what you mean by regenerate. If you're looking to populate the database with content you can use the `.train()` method as described in the [documentation](https://github.com/gunthercox/ChatterBot/wiki/Training).

**Comment by justquantum** [comment]
Ok, I worked around this by instantiating another ChatBot without getting rid of the already existing one. That generated the database I needed to keep using the one I had.

**Comment by justquantum** [comment]
I needed the actually database file. when I dropped it with the earlier command, I couldn't run any subsequent commands because the file was missing.
