### ISSUE TITLE
chatterbot is not working properly

### ISSUE THREAD

**Issue by gsatkumar** [gunthercox/ChatterBot#1592]
Hi ,I have installed chatterbot 0.8.6 on Python 3.5.2

I have trained the data with .yml files.

prob1 : It is picking the first answer from the list of responses.When we give same question multiple times it is giving the same(first) answer.

prob2 : if you delete anything from data and re-train ,it still giving the same response.

**Comment by gunthercox** [comment]
By default, the chatbot selects the first response from each set of possible results. This behavior is possible to change. See https://chatterbot.readthedocs.io/en/latest/logic/response_selection.html#module-chatterbot.response_selection for details on the possible options.

The reason you are seeing the same results, even after re-training, is that the ChatBot stores a database of everything it has been trained with, including consecutive trainings.
