### ISSUE TITLE
On no matching input "The current time is xxx" with confidence 1.0

### ISSUE THREAD

**Issue by capaximperii** [gunthercox/ChatterBot#1594]
When the chatterbot is given an input that does not match its trained corpus:
1. It takes a very long time.
2. It always defaults to "The current time is {current time}" with confidence 1.0 preventing the default response from triggering. 
`
chatbot = ChatBot('Pluto',     logic_adapters=[ 'chatterbot.logic.UnitConversion',
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter',
        'chatterbot.logic.BestMatch',
    ])
`

**Comment by gunthercox** [comment]
Hi @capaximperii can you add the following to the top of your code and post the output after getting a response from the chatbot?

```python
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
```

This will cause additional information to be printed out related to the selection process, and it will help to indicate where the incorrect response is coming from.

**Comment by capaximperii** [comment]
@gunthercox I will do that. Currently I am working on a pull request and want your opinion about using word vectors. That way - a sentence can be represented by a constant vector and can be compared to any other sentence for closeness. The performance is not better but the calculation can be stored.

**Comment by gunthercox** [comment]
@capaximperii Thank you, I'll be very interested to see the additions you're proposing.

**Comment by capaximperii** [comment]
Hello @gunthercox , I have a pull request with a clustering approach to reduce the number of comparisons using clusters. The clusters themselves depend on word vector embeddings. The performance isnt better just yet but I am still trying to figure out how spacy stores word vectors on disk to avoid recomputing each time.

**Comment by gunthercox** [comment]
Hi @capaximperii, I've looked over your pull request (#1612) briefly. This looks like an interesting approach.

**Comment by capaximperii** [comment]
@gunthercox I have optimised it further. The only delay now comes from reading the entire corpus from sqlite db and 1 time creation of model. So the first input will take a while but the next ones show a marked improvement in response times.

**Comment by gunthercox** [comment]
I'm closing this ticket off since I haven't heard anything related to the original issue. Feel free to reopen it or open a new ticket if you still require assistance.
