### ISSUE TITLE
ImportError: No module named 'chatterbot.storage'; 'chatterbot' is not a package

### ISSUE THREAD

**Issue by GunjanChourasia** [gunthercox/ChatterBot#1595]
I have already installed chatterbot using pip, but the problem isn't solved. 
Also i am running it on python3.

**Comment by capaximperii** [comment]
can you run python --version and post the output. 
Also if on windows try `where python` if not on linux try `which python`

Your pip is most likely installing the package to a different version of python.

Alternately, you could try `python -m pip install chatterbox`

**Comment by GunjanChourasia** [comment]
` python --version
Python 2.7.12
~$ python3 --version
Python 3.5.2
`

It shows error on running `python -m pip install chatterbox`:
`Could not find a version that satisfies the requirement chatterbox (from versions: )
No matching distribution found for chatterbox
`

**Comment by gunthercox** [comment]
> No matching distribution found for chatterbox

Please change `chatterbox` to `chatterbot`. The correct package name must be used for ChatterBo**t** to be installed.

**Comment by GunjanChourasia** [comment]
`python3 -m pip install ChatterBot --upgrade
Collecting ChatterBot
  Using cached https://files.pythonhosted.org/packages/43/eb/ae2466f9873ee9266a613c8650dd843b31d6c8af0143946125e94f7a8f81/ChatterBot-1.0.2-py2.py3-none-any.whl
Collecting mathparse<0.2,>=0.1 (from ChatterBot)
`
But still its not recognising the package.

`python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chatterbot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package
>>> 
`

**Comment by gunthercox** [comment]
@GunjanChourasia Please make sure that you are also using the `python3` command to launch the terminal. For example:

```
python3
>>>import chatterbot
```

**Comment by GunjanChourasia** [comment]
`python3 chatterbot.py 
Traceback (most recent call last):
  File "chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "/home/ChatterBot/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package
`
I am using python3 only

**Comment by capaximperii** [comment]
chatterbot is a library, you cannot directly run chatterbot.py. you have to create different python file where you invoke chatterbot. please refer to the documentation for a simple list trainer example.

**Comment by manzoorali29** [comment]
As there any logical answer of this questions. I am using conda python 3.7, pycharm install chatbot successfully. I am working in a file but the above error is showing.

**Comment by dmaurya98** [comment]
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package

**Comment by theanmolgoyal** [comment]
Hey, I am using conda spyder and have latest version of python (3.8.0) and facing same problem
File "chatterbot.py", line 2, in <module> from chatterbot.storage import StorageAdapter File "/home/ChatterBot/chatterbot/chatterbot.py", line 2, in <module> from chatterbot.storage import StorageAdapter ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package
Also I rename the file of chatterbot.py to filename.py
Please help for this

**Comment by jadeye** [comment]
@dmaurya98 any solution to this?? anyone...

**Comment by Abhishek-oss-create** [comment]
ERROR: Command errored out with exit status 1: 'D:\Python 3.8\python.exe' 'D:\P
ython 3.8\lib\site-packages\pip' install --ignore-installed --no-user --prefix
'C:\Users\abhishek\AppData\Local\Temp\pip-build-env-djqmnp0g\overlay' --no-warn
-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/si
mple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed
>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the log
s for full command output.

**Comment by theanmolgoyal** [comment]
try to update setuptools

**Comment by theanmolgoyal** [comment]
> @dmaurya98 any solution to this?? anyone...

rename the file. We cant use chatterbot.py  as filename
