### ISSUE TITLE
error: chatbot object has no attribute train

### ISSUE THREAD

**Issue by Gnaneswari** [gunthercox/ChatterBot#1598]
runfile('C:/Users/gnane/OneDrive/Documents/PhD/phd2018 Implementation/GGBot/reflexivemodel.py', wdir='C:/Users/gnane/OneDrive/Documents/PhD/phd2018 Implementation/GGBot')
Training the Reflexive Layer
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\gnane\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gnane\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gnane\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):

  File "<ipython-input-5-5e98e236c263>", line 1, in <module>
    runfile('C:/Users/gnane/OneDrive/Documents/PhD/phd2018 Implementation/GGBot/reflexivemodel.py', wdir='C:/Users/gnane/OneDrive/Documents/PhD/phd2018 Implementation/GGBot')

  File "C:\Users\gnane\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\gnane\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/gnane/OneDrive/Documents/PhD/phd2018 Implementation/GGBot/reflexivemodel.py", line 12, in <module>
    refbot.train(conversation)

AttributeError: 'ChatBot' object has no attribute 'train'

This is the error when I tried installing in my new system and tried to execute my code.

**Comment by gunthercox** [comment]
Hi @Gnaneswari, the error message you have encountered is correct. The `ChatBot` object does not have a `train` attribute.

Could you tell me where you found the instructions that said to call the `train` method on the `ChatBot` object? I think there might be a mistake in the documentation and I would like to correct it.

**Comment by Gnaneswari** [comment]
Thank you. I got it, I had used 0.8.6 version and coded.
