### ISSUE TITLE
Django training

### ISSUE THREAD

**Issue by RIBA-test** [gunthercox/ChatterBot#1600]
Unable to train chatterbot as a django app and store it to postgresql database
@gunthercox

**Comment by gunthercox** [comment]
Hi @RIBA-test, when I have a chance, I will create a small Django application connected to a Postgres database so I can try to test this.

In the meantime, are there any specific error messages you have encountered? Posting a copy of them may make it easier for me to help point you towards a solution.

**Comment by RIBA-test** [comment]
Hi @gunthercox there are no errors while training without specifying storage adapter but Chatbot doesn't respond as intended to trained data. while specifying sql storage adapter  and postgres uri it fails in corpus training.

**Comment by gunthercox** [comment]
Okay, I'm glad to hear that there aren't any errors being produced. I'll let you know what what I find when I try to test this out.

**Comment by gunthercox** [comment]
@RIBA-test I created a Django application connected to a Postgres (version 11) database to test with. Everything seems to be running correctly for me.

**Comment by Jayapraveen** [comment]
Oh, It's nice to hear, please do share the code, it will be helpful. Thanks

**Comment by gunthercox** [comment]
Sure, I will be happy to share the code that I used. For reference, I used the Django example from the current `master` branch (which is intended to to be used with version 1.0). Then, after creating a Postgres instance locally, and adding the relevant variables to my working environment, I made the following change to `settings.py`:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRES_DB_NAME'),
        'USER': os.environ.get('POSTGRES_USERNAME'),
        'HOST': os.environ.get('POSTGRES_HOSTNAME'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'PORT': os.environ.get('POSTGRES_PORT', 5432),
        'OPTIONS': {
            'sslmode': 'prefer',
        }
    }
}
```
