### ISSUE TITLE
ChatterBot executable application

### ISSUE THREAD

**Issue by Ss0061933** [gunthercox/ChatterBot#1602]
[setup.txt](https://github.com/gunthercox/ChatterBot/files/2824562/setup.txt)

Hi All,
Can we convert Chatterbot code into executable code using CX_FREEZE?
I am completly new to python and just did basic tutorials in last 2 days. Just explored chatterbot and created rule based chatterbot with help of excel.Able to run index.html file and its running as expected .
Tried converting file to executable using command python setup.py build. But not working .
Looks like server is not getting setup.

[QA_TEST.xlsx](https://github.com/gunthercox/ChatterBot/files/2824557/QA_TEST.xlsx)

[openindex.txt](https://github.com/gunthercox/ChatterBot/files/2824566/openindex.txt)
[mainsetup.txt](https://github.com/gunthercox/ChatterBot/files/2824569/mainsetup.txt)
[chatbot_trainexcel.txt](https://github.com/gunthercox/ChatterBot/files/2824571/chatbot_trainexcel.txt)

**Comment by gunthercox** [comment]
Hi @Ss0061933 I am not familiar with `CX_FREEZE` so unfortunately I don't have anything to contribute on how to use it.

Based on your mention of an `index.html` file, it sounds like you might be creating a web application. [Docker](https://docs.docker.com/) can be a very good method for  distributing web applications.

**Comment by gunthercox** [comment]
Hi @Ss0061933 I am not familiar with `CX_FREEZE` so unfortunately I don't have anything to contribute on how to use it.

As a possible alternative: based on your mention of an `index.html` file, it sounds like you might be creating a web application. [Docker](https://docs.docker.com/) can be a very good method for containerizing and distributing web applications.
