### ISSUE TITLE
Is there any reserch paper or something that can be referenced related to this?

### ISSUE THREAD

**Issue by gpjyothish** [gunthercox/ChatterBot#161]
Any algorithm that it uses?

**Comment by gunthercox** [comment]
I currently haven't written a research paper for ChatterBot, although I would not be opposed to eventually writing one. You may have luck with finding research papers related to some of the project's dependencies:

- [FuzzyWuzzy](https://github.com/seatgeek/fuzzywuzzy) - A Python implementation of the [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance) algorithm
- [Natural Language Toolkit](http://www.nltk.org/)

Aside from that I apologize if those links aren't exactly what you're looking for. Feel free to use anything from the project wiki (https://github.com/gunthercox/ChatterBot/wiki) if it is useful. Don't hesitate to let me know if there is specifically anything I can add that would improve the projects's descriptions or documentation.

**Comment by imumair** [comment]
Hi, I had a question, I was reading the source fro Logic adapters, and specially for the Closest matching adapter, ... sorry for the dumb question...new at machine learning, but still tryign to figure out which machine learning algorithms are you using for the chatterbot it Naive Baysean or ... ... also I was lookign at the nltk documentation ... it says these 3 as machine learnign modules .. are you usign any od these :  classify, cluster, tbl  ... on this link :  ... http://www.nltk.org/book/ch00.html

**Comment by gunthercox** [comment]
Hi @imumair, from NLTK, the classify machine learning algorithm is used in logic adapters such as the time logic adapter. NLTK is also used in the closest meaning adapter, but it is only used for calculating synonyms when traversing the knowledge graph. Another adapter (the closest match adapter) uses [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) as an alternate method of knowledge graph traversal.

**Comment by vkosuri** [comment]
@iamhssingh I didn't understand what you are trying conveying here? could you please elaborate more what are your differnt suggestions.

**Comment by gunthercox** [comment]
@iamhssingh Awesome, feel free to let me know if you have any questions or if there is anything I can clarify for you.

**Comment by iamhssingh** [comment]
@vkosuri I am actually writing a Project Report for my college based on this project. I have mentioned the usage of GuntherCox's chatterbot in it.

The theme of project is: Self-Learning Chat Bot as Teacher based on Gunthercox’s Chatterbot 

@gunthercox I want to write a research paper based on IEEE format for this project. I am not sure how do I list all the contributors in the research paper. Can you please let me know what is the possible way and right way of adding all the contributors of the project in the Research Paper? Right now, it only contains the name of project as GuntherCox's Chatterbot and reference link to the GitHub and name of three people (incl. me) as Author of the research paper.

**Comment by gunthercox** [comment]
@iamhssingh I believe for citations you can reference the copyright holder and just mention "individual contributors" as a whole. I'm definitely not an expert in the correct way to set up these references, but I'm going off of other open source projects as an example.

For example, the Django license uses the phrasing "Django Software Foundation and individual contributors".

https://github.com/django/django/blob/master/LICENSE

**Comment by gunthercox** [comment]
@mikhailhathey That is possible to do with ChatterBot.

**Comment by gunthercox** [comment]
Quite a bit has changed since this ticket was first opened. At this point I'm no longer planning to write a research paper related to ChatterBot. My efforts will instead be directed towards improving the existing documentations and tutorials.
