### ISSUE TITLE
Problem , reinstalling doesn't work

### ISSUE THREAD

**Issue by RizwaanShaik** [gunthercox/ChatterBot#1610]
I have tried to run the following file
[1.txt](https://github.com/gunthercox/ChatterBot/files/2837401/1.txt) but it gives me the following error. I have tried re-installing the whole package , didn't work. 
[2.txt](https://github.com/gunthercox/ChatterBot/files/2837406/2.txt)
Please i need help.

**Comment by gunthercox** [comment]
Hi @RizwaanShaik did you attempt do follow the recommendation of the error message you received?
> The NLTK corpus file being opened is not a zipfile, or it ha s been corrupted and needs to be manually deleted.
If not, I hope that this solves your issue.

**Comment by RizwaanShaik** [comment]
When i try to delete the NLTK file and run the code, it shows an error of No module of NLTK
Can you please tell which file is to be deleted exactly
thank you

**Comment by capaximperii** [comment]
Would it be possible for you to try this with virtualenv, It is an easy way to create and remove development environments without stalling your work.

**Comment by RizwaanShaik** [comment]
> 
> 
> Would it be possible for you to try this with virtualenv, It is an easy way to create and remove development environments without stalling your work.

I can try that, but i still need to make it work on the main platform.
thanks

**Comment by gunthercox** [comment]
The NLTK files that need to be deleted are in a folder named `nltk_data`. You are most likely to find this folder in your home directory on your computer. You should be safe to delete everything in `nltk_data`.

**Comment by RizwaanShaik** [comment]
> 
> 
> The NLTK files that need to be deleted are in a folder named `nltk_data`. You are most likely to find this folder in your home directory on your computer. You should be safe to delete everything in `nltk_data`.

Thanks , it works now
