### ISSUE TITLE
How the bot search in web when it is under confidence level?

### ISSUE THREAD

**Issue by rdhar8502** [gunthercox/ChatterBot#1611]

**Comment by capaximperii** [comment]
can you add more information? the title is not sufficient and by the looks of it you are probably looking at default response when confidence is low?

**Comment by rdhar8502** [comment]
Thank you for reply.
My question is suppose I asked a General Knowledge question (ex : "Who kill Abraham Lincoln?"). Now we cant't train a bot a whole world encyclopedia, it's never possible. But I want to answer it via internet search (ex : google.com) like amazon alexa. How can I?

**Comment by rdhar8502** [comment]
Thank you for reply.
My question is suppose I asked a General Knowledge question (ex : "Who kill Abraham Lincoln?"). Now we cant't train a bot a whole world encyclopedia, it's never possible. But I want to answer it via internet search (ex : google.com) like amazon alexa. How can I?

**Comment by capaximperii** [comment]
when the response.confidence is below a threshold that you consider acceptable - lets say 0.70 then you can initiate a web search, that is business logic outside the scope of the chatterbot itself.
