### ISSUE TITLE
Custom LogicAdapter

### ISSUE THREAD

**Issue by FlaDev** [gunthercox/ChatterBot#1613]
I'm following the current documentation for creating a new logic adapter and I'm running in a problem when starting my project.  Looked at other examples and all others look the same.

python --version
Python 3.7.2

I've created the the following structure:
app.py --> It has the main function
app_adapter.py --> new adapter.

in app.py:

myBot = ChatBot(
    "MyBot",
    logic_adapters=[
        {
            'import_path': 'app_adapter.MyLogicAdapter'
        }
    ])

app_adapter:

class MyLogicAdapter(LogicAdapter):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

ERROR:
  File "C:\Users\prumu\PycharmProjects\Bot\app.py", line 10, in <module>
    'import_path': 'app_adapter.MyLogicAdapter'
  File "C:\Users\prumu\PycharmProjects\Bot\venv\lib\site-packages\chatterbot\chatterbot.py", line 39, in __init__
    logic_adapter = utils.initialize_class(adapter, self, **kwargs)
  File "C:\Users\prumu\PycharmProjects\Bot\venv\lib\site-packages\chatterbot\utils.py", line 50, in initialize_class
    return Class(*args, **data)
TypeError: __init__() takes 1 positional argument but 2 were given

**Comment by gunthercox** [comment]
It looks like my example in the documentation is out of date. Your init method should look like this:
```python
    def __init__(self, chatbot, **kwargs):
        super().__init__(chatbot, **kwargs)
```

**Comment by FlaDev** [comment]
Thanks, that worked.

def process definition has the same issue. It would be great to have the documentation updated.
