### ISSUE TITLE
Unable to install / run on windows 7

### ISSUE THREAD

**Issue by dktechindia** [gunthercox/ChatterBot#1614]
I manually downloaded the current version of the ChatterBot and my Windows 7 in which python 3.7.2 is installed.
Extracted  the zip file and navigated to the  home directory D:\ChatterBotTest\ and then executed setup.py 

> D:\ChatterBotTest>python setup.py
> Traceback (most recent call last):
>   File "setup.py", line 9, in <module>
>     CHATTERBOT = __import__('chatterbot')
>   File "D:\ChatterBotTest\chatterbot\__init__.py", line 4, in <module>
>     from .chatterbot import ChatBot
>   File "D:\ChatterBotTest\chatterbot\chatterbot.py", line 2, in <module>
>     from chatterbot.storage import StorageAdapter
>   File "D:\ChatterBotTest\chatterbot\storage\__init__.py", line 1, in <mod
> ule>
>     from chatterbot.storage.storage_adapter import StorageAdapter
>   File "D:\ChatterBotTest\chatterbot\storage\storage_adapter.py", line 3,
> in <module>
>     from chatterbot.tagging import PosHypernymTagger
>   File "D:\ChatterBotTest\chatterbot\tagging.py", line 3, in <module>
>     from chatterbot import utils
>   File "D:\ChatterBotTest\chatterbot\utils.py", line 4, in <module>
>     from nltk.corpus import wordnet
> ModuleNotFoundError: No module named 'nltk'

also I tried the command given in the documentation at https://chatterbot.readthedocs.io/en/stable/setup.html 
 and I got the same error as above.
> D:>pip install ./ChatterBotTest

Can you guide me how can I install it and run it or is there any way to run it without installing it?

**Comment by gunthercox** [comment]
I see that the last part of the error you are getting says `ModuleNotFoundError: No module named 'nltk'`. Perhaps this indicates that `nltk`, and ChatterBot's other dependencies are not being installed for you.
You can install the requirements directly if you have the `requirements.txt` file available locally. The command looks like this:
```
pip install -r requirements.txt
```

**Comment by dktechindia** [comment]
@gunthercox Thank You. I was facing issue while installation because of some proxy . So I tried with pip install  <Package Name> --trusted-host pypi.org --trusted-host files.pythonhosted.org and everything worked fine.

When I am training the Bot using ListTrainer I am getting some random responses and one liner in the console as "No value for search_text was available on the provided input" .

How can I train it so that I get proper response as per the keywords I am sending?

**Comment by gunthercox** [comment]
The output `No value for search_text was available on the provided input` sounds very similar to this ticket: https://github.com/gunthercox/ChatterBot/issues/1589#issuecomment-458500020
I would recommend looking at the solution that was described there.
