### ISSUE TITLE
is it possible to generate reply based on multiple questions

### ISSUE THREAD

**Issue by kangaroocancode** [gunthercox/ChatterBot#1615]
Bot: what is your favorite color?
User: red
Bot: do you like sweet?
User: yes
Bot: do you like fruits?
User: yes
Bot: i guess you like apple?

Does Chatterbot able to perform such kind of conversation?

**Comment by gunthercox** [comment]
Currently this is not possible.

**Comment by kangaroocancode** [comment]
how about creating new logic adaptor ?

**Comment by gunthercox** [comment]
If you create a new logic adapter that performs the desired functionality, then yes.
