### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by nish-sura** [gunthercox/ChatterBot#1624]
i am getting this error. does anyone know how to fix it?

**CODE_**
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

bot = ChatBot('Bot')
bot.set_trainer(ListTrainer)

for files in os.listdir('C:/Users/nisha\chatterbot-corpus-master\chatterbot_corpus\data\english'):
	data = open('C:/Users/nisha\chatterbot-corpus-master\chatterbot_corpus\data\english' + files ,'r').readlines()
	bot.train(data)

while True:
	message = input('You:')
	if message.strip()!= 'Bye':
		reply = bot.get_response(message)
		print('ChatBot :',reply)
	if message.strip() == 'Bye':
		print('ChatBot : Bye')
		break

**ERROR-**
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/nisha\\chatterbot-corpus-master\\chatterbot_corpus\\data\\englishai.yml'

**Comment by gunthercox** [comment]
I think you might be missing a `/` after `english`. It should be `english/' + files`.
Also, it might be a good idea for you to replace all of your backslashes `\` with forward slashes `/`.

**Comment by nish-sura** [comment]
Got another error when i did ur fix DX
List Trainer: [####################] 100%
List Trainer: [####################] 100%
List Trainer: [####################] 100%
List Trainer: [####################] 100%
List Trainer: [####################] 100%
Traceback (most recent call last):
  File "chatbot_train.py", line 9, in <module>
    data = open('C:/Users/nisha\chatterbot-corpus-master\chatterbot_corpus\data\english/' + files ,'r').readlines()
  File "C:\Users\nisha\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3461: character maps to <undefined>

**Comment by Sangarshanan** [comment]
Try using utf-8 encoding
Check out https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character
