### ISSUE TITLE
ChatterBot Survey

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#1625]
I have a short (six-question) survey I'd like to hopefully use to get some good feedback to help improve ChatterBot for the development community.

https://goo.gl/forms/XMDowFjUGZ9ashSF2

I would be extremely thankful if anyone has time to fill it out.

**Comment by vkosuri** [comment]
@gunthercox Master, may i know the response outcome?

**Comment by gunthercox** [comment]
I'm still waiting on a few more responses to come in, I can post something like a summary, or an interpretation of the findings after the survey closes.
