### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by AfrahAsif** [gunthercox/ChatterBot#1627]
from chatterbot import ChatBot 
from chatterbot.trainers import ChatterBotCorpusTrainer
import os
import logging 
logger = logging.getLogger() 
logger.setLevel(logging.CRITICAL)
bot= ChatBot('Bot')
trainer = ChatterBotCorpusTrainer(bot)

corpus_path="C:/Users/Afrah/Desktop/Internship/CBot/chatterbot-corpus-master/chatterbot-corpus-master/chatterbot_corpus/data/english/"
for file in os.listdir(corpus_path):
    trainer.train(corpus_path + file)

this is the error getting:

![capture](https://user-images.githubusercontent.com/22939515/53075141-7596a080-3512-11e9-8b0b-88178d403287.PNG)

**Comment by vkosuri** [comment]
Which version chatterbot are you using? It seems me to you are using JSONAdater that is removed from latest version

``pip install --upgrade chatterbot``

**Comment by AfrahAsif** [comment]
Thanks working now.. :)
