### ISSUE TITLE
AttributeError: 'ChatBot' object has no attribute 'set_trainer'

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1628]
HI,

The bellow code is for chatter bot using flask when i am trying to execute this file i am getting an error 
**"Attribute Error: 'ChatBot' object has no attribute 'set_trainer'"**

so please any handle this it will very helpful for me i tried all the alternatives but i not working suddenly i am getting an error in previous it was worked but now its not working now could any one help in this 

**Note: The folder data consists of the yml files for the chatbot requirement **

Thank you in advance

Happy pythoining

from flask import Flask, render_template
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

app = Flask(__name__)

english_bot = ChatBot("Chatterbot", storage_adapter="chatterbot.storage.SQLStorageAdapter")

english_bot.set_trainer(ListTrainer)
english_bot.train("./data")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(english_bot.get_response(userText))

if __name__ == "__main__":
    app.run()

**Comment by Ligh7bringer** [comment]
Have a look at my [comment](https://github.com/gunthercox/ChatterBot/issues/1622#issuecomment-464369262) in #1622.

**Comment by mady143** [comment]
I am getting an issue if i change the code as per the issue 

from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

app = Flask(__name__)

english_bot = ChatBot("Chatterbot", storage_adapter="chatterbot.storage.SQLStorageAdapter")

english_bot.ListTrainer(english_bot)
english_bot.train("./data")


@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(english_bot.get_response(userText))


if __name__ == "__main__":
    app.run()

**ERROR**

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    english_bot.ListTrainer(english_bot)
AttributeError: 'ChatBot' object has no attribute 'ListTrainer'

Could please help me in this to avoid this errors

Thank in advance

**Happy codding....**

**Comment by Ligh7bringer** [comment]
Did you read my comment?  You should create a **trainer** object and pass the chatbot to it, and then call train on the trainer. Something like this:
<pre><code>
english_bot = ... # init bot
<b>trainer = ListTrainer(english_bot)
trainer.train([
    "How are you?",
    "Great!",
]) </b>
</code></pre>

Additionally, if you are storing your training data in a file, I think you should be using the **ChatterCorpusTrainer** (I might be wrong).
