### ISSUE TITLE
Chatterbot

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1629]
Hi ,

I want to know how to save chat history between the user and the bot in to the file 
 and i want to create it as dynamic chat without any data providing before and train that files just we need to train the chat history file through that we can make the conversation

**Comment by mady143** [comment]
Hi,

I need an example for chatterbot which works in the web browser without any issues can you please provide me that code link

**Comment by vkosuri** [comment]
https://github.com/chamkank/flask-chatterbot

https://github.com/vkosuri/chatterbot-live-example
