### ISSUE TITLE
Is there any self-learning/self-improving chatterbot (preferably AIML bot) library/engine?

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1631]
Hi Every one,

I want to know is their any docs related to self learning chart bot for better understanding and giving quick responses as humans can do can please help me in this i want to know more about this

**Comment by gunthercox** [comment]
Hi @mady143, Unfortunately, I don't currently have any documentation available related to this.

**Comment by mady143** [comment]
How to prepare the chatter bot using NLP Deep Learning

**Comment by vkosuri** [comment]
Look tensorflow and fastText
