### ISSUE TITLE
Input adapter options

### ISSUE THREAD

**Issue by Dulce06** [gunthercox/ChatterBot#1632]
Hi,

I am searching for the folder in chatterbot where it has different types of input adapters available to use.
I have not specifically mentioned input/output adapter in the code but it takes terminal input by default.

It was in "chatterbot.input.terminal..." folder in version 0.8.7. Can't find this in 1.0.0 version.
Any help please.

I am build RESTful APIs. As of now, I am using postman to verify this.

**Comment by gunthercox** [comment]
Hi @Dulce06,

The input and output adapters were remove in version 1.0 in favor of using Python's native `input` and `print` functions.

There is sample code showing this in the documentation if it helps:
https://chatterbot.readthedocs.io/en/latest/examples.html#terminal-example

**Comment by Dulce06** [comment]
Thank you. :)
