### ISSUE TITLE
yml creation and training

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1633]
Hi everyone ,

I had created the yml file in the form of below code 

User: hi
YBot: Hi,Good Morning
User: need help
YBot: yeah tell me how can i help you
User: ayurvedhic products
YBot: sure please visit https://www.arogyarahasya.com/
User: name

but in need the file to be as 

- - hi
  - Hi,Good Morning
- - hello
  - hi
  - Good morning
  - Very Good Morning, How may i help you
  - I need some ayurvedic products may i know best site for selling these products?
  - sure please visit https://www.arogyarahasya.com/
  - Thank you
so that i can train my new saved file to the system and start the converstaion

could any one help me in this issue

**This is my code for getting response and saving the yml file**

userText = request.args.get('msg')
	text = str(english_bot.get_response(userText))
	
	
	a = {"User": userText,"YBot": text}

	with open('chat.yml', 'a') as outfile:
		yaml.dump(a,outfile, default_flow_style=False)

	return text

Thanks in advance

Happy codding.....

**Comment by vkosuri** [comment]
@mady143 could you please let me know, what are the difference between your yml files and chatterbot export yml files

```Python
from chatterbot import ChatBot
chatbot = ChatBot('Export Example Bot')
chatbot.trainer.export_for_training('./export.yml')
```
