### ISSUE TITLE
Please, help chatterbot 1.02

### ISSUE THREAD

**Issue by CelliusCtba** [gunthercox/ChatterBot#1635]
Does anyone help me to fix this code?
``` Python
# -*- coding: utf-8 -*-

"""
This example shows how to train a chat bot using the
Ubuntu Corpus of conversation dialog.
"""
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

# Create a new chat bot named Caramba
chatbot = ChatBot('Caramba')
import os

trainer.train([
                                             
for arq in os.listdir('arq'):
    chats = open('arq/' + arq, 'r').readlines()
    bot.train(chats)
while True:
    resq = input('Você: ')
    resp = bot.get_response(resq)
    print('Bot: ' + str (resp))  
])
```

**Comment by brightening-eyes** [comment]
this is the corrected code:
"""
This example shows how to train a chat bot using the
Ubuntu Corpus of conversation dialog.
"""
import os
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
#Create a new chat bot named Caramba
chatbot = ChatBot('Caramba')
trainer = ListTrainer(chatbot)
for arq in os.listdir('arq'):
    chats = open('arq/' + arq, 'r').readlines()
trainer.train(chats)

while True:
	resq = input('Você: ')
	resp = bot.get_response(resq)
	print('Bot: ' + str (resp))

**Comment by vkosuri** [comment]
@CelliusCtba I am closing this issue, please feel free reopen you want to discuss further on this issue.
