### ISSUE TITLE
How to create API in Python 

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1639]
Hi Every one.
I want to learn how to create API's in Python and how deploy in the server for the project should be in live and how to call the API's in the server

**Comment by gunthercox** [comment]
A great way to do this is with [Django](https://www.djangoproject.com) and [Django REST Framework](https://www.django-rest-framework.org). Both of these projects have excellent documentation and very supportive development communities.

Mozilla provides a lot of good information about deploying a project into production.
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment

There is also a very basic example of an API using ChatterBot in the Django example (See `examples` directory in source code).

I hope this helps. Happy coding!

**Comment by Dulce06** [comment]
Hi @gunthercox 
I have not used Django to develop chatterbot. I have written my code in a python file and executed. 
In this case, how can we create an API?

Many thanks

**Comment by mady143** [comment]
HI @Dulce06 

you can create through Flask its very simple creating API through flask

**Comment by Dulce06** [comment]
Hi @mady143 

Thanks for the prompt reply. But, I have seen Flask supports one user at a time. 

I want my bot to train only once at the beginning ( should be running all the time) and then it should be accessed by multiple users at a time.

Is this possible with Flask?

**Comment by mady143** [comment]
Hi, @Dulce06 

I am doing the same task chatterbot 

I am working on flask and creating an API to run on the browser experience with no issues currently i am running with flask 

You said that training is running all the time na then do one just comment the train line (once train can been finished) becoz for me also its not working i tried but no use

**Comment by Dulce06** [comment]
Thank you. Will need to search for another one that fits the purpose.
