### ISSUE TITLE
How to add speech to text in chatterbot using flask 

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1642]
Hi everyone,

I need a help just done i done with text to text in chatter bot using flask now i have to add the speech to text in the code is it possible of adding speech to text in the same code 

My code

from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import yaml

app = Flask(__name__)

english_bot = ChatBot("Chatterbot", storage_adapter="chatterbot.storage.SQLStorageAdapter")

english_bot.set_trainer(ChatterBotCorpusTrainer)
english_bot.train("./data")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
	
	userText = request.args.get('msg')
	# print(userText)
	text =  str(english_bot.get_response(userText))

	Chathistory = "chathistory"
	a = {"converstaions":[[userText,text]]}
	# b = {"converstaions":[[userText,text]]}
	
	

	with open("chat.yml","a") as outfile:
		
		yaml.dump(a['converstaions'],outfile,default_flow_style=False)
		# yaml.dump(b,outfile,default_flow_style=False)
	
	return text
if __name__ == "__main__":
    app.run()
For the above code i have to add the speech to text functionality could any one help me in this

Thanks in advance 

Happy Codding

**Comment by vkosuri** [comment]
It's browser capability 

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API
https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API

**Comment by mady143** [comment]
Hi @vkosuri  thank you for your response but i had done it and i can run it on browser also with the help of flask plz click here https://github.com/mady143/mani/blob/master/app.py you can find the temple as well
