### ISSUE TITLE
API for chatterbot?

### ISSUE THREAD

**Issue by kangaroocancode** [gunthercox/ChatterBot#1649]
i want to create an IOS app that could chat with the bot, if i do not have django integration, is it possible to have an api directly communicate with the bot?

**Comment by kangaroocancode** [comment]
sorry i am new to programming... i feel confused with the django integration example, could you help me with following questions? 

1) the example used views.py and urls.py to create a API ? so we can use website to send request to the chatterbot ? 
2) Can i use an IOS app instead of website to send request to the chatterbot? 
3) If not, we need to use Django REST framework? what is the difference between Django REST framework with the API used in the example ?
4) Can i host the chatterbot without using django and create API for it?

**Comment by Dulce06** [comment]
Hi @kangaroocancode ,

I have not used Django for my chatbot but I created an API using falcon library. Please have a look if that works with your code. 

If it works, I can help you with any issues further.

**Comment by ignertic** [comment]
Hi @kangaroocancode , yes it is possible with Flask, if you are still on to this feel free email me directly

**Comment by MatheusRV** [comment]
https://github.com/gabru-md/chatterbot-api :)
