### ISSUE TITLE
Specific response logic adapter is not working

### ISSUE THREAD

**Issue by kangaroocancode** [gunthercox/ChatterBot#1651]
i am using django integration and created a new specific response logic adapter for the bot, 
i already added the adapter to settings, but even i input the specific text, the bot cannot reply with the output text that i set in the code. what is the reason?? 

Which folder should i put my new adapter? i already made multiple copies in different folder but still not help

**Comment by gunthercox** [comment]
Hi @kangaroocancode feel free to put your new logic adapter in any folder you would like. The only requirement is that it has to be within the path of the Python module you are working in. Then you can just import your new logic adapter the way you would with any other python module.
