### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by nabeelahmedsabri** [gunthercox/ChatterBot#1652]
After installing chatterbot this error occurs!
C:\Users\Nabeel\chatbot> py chat.py
Traceback (most recent call last):
  File "chat.py", line 1, in <module>
    from chatterbot import ChatBot
ModuleNotFoundError: No module named 'chatterbot'

**Comment by sarangjain40** [comment]
it seems python is not able to find chatterbot installation directories.

**Comment by nabeelahmedsabri** [comment]
So what to do know?

**Comment by Dulce06** [comment]
Try this. This worked for me.

In the terminal, type the command "which chat" and hit enter
chat is the name of your python file

You get a path like "/usr/bin/chat"

Then run the command depending on this path. 

Looks like " ./venv/bin/gunicorn" (In my case, I have all my files in venv)

Then type "path you get" chat.py

Hope this helps
