### ISSUE TITLE
ImportError: cannot run the code name 'ChatBot'

### ISSUE THREAD

**Issue by neelabhsriv** [gunthercox/ChatterBot#1658]
I am trying to run below code in Anaconda. However, I am getting an error. kindly help.
CODE:

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainers
import os

bot= ChatBot('Bot')
bot.set_trainers(ListTrainers)

for files in os.listdir('C:\\Users\\lenovo\\Downloads\\BOT\\chatterbot-corpus-master\\chatterbot_corpus\\data\\english'):
data=open('C:\\Users\\lenovo\\Downloads\\BOT\\chatterbot-corpus-master\\chatterbot_corpus\\data\\english\\'+files,'r').readlines()
bot.train(data)

while True:
message=input("USER:")
if(message.strip() != 'bye'):
reply=bot.get_response(message)
print("BOT:" + reply)
if(message.strip() == 'bye'):
print("BOT:BYE :-), hope to see you again")
break

![image](https://user-images.githubusercontent.com/46059269/54000429-99c7c380-4147-11e9-9160-5c6337282953.png)

**Comment by Ligh7bringer** [comment]
Your code is not indented correctly. 

```
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainers
import os

bot = ChatBot('Bot')
bot.set_trainers(ListTrainers)

for files in os.listdir('C:\Users\lenovo\Downloads\BOT\chatterbot-corpus-master\chatterbot_corpus\data\english'):
	data=open('C:\Users\lenovo\Downloads\BOT\chatterbot-corpus-master\chatterbot_corpus\data\english\'+files,'r').readlines()
	bot.train(data)

while True:
	message=input("USER:")

	if(message.strip() != 'bye'):
		reply=bot.get_response(message)
		print("BOT:" + reply)

	if(message.strip() == 'bye'):
		print("BOT:BYE :-), hope to see you again")	
		break
````

**Comment by neelabhsriv** [comment]
Thanks for the reply.
again getting an error:
![image](https://user-images.githubusercontent.com/46059269/54004308-6724c780-4155-11e9-8205-2eba6a52272d.png)

CODE: 

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainers
import os

bot = ChatBot('Bot')
bot.set_trainers(ListTrainers)

for files in os.listdir('C:\\Users\\lenovo\\Downloads\\BOT\\chatterbot-corpus-master\\chatterbot_corpus\\data\\english'):
	data=open('C:\\Users\\lenovo\\Downloads\\BOT\\chatterbot-corpus-master\\chatterbot_corpus\\data\\english\\'+files,'r').readlines()
	bot.train(data)

## I AM NOT A MAC USER THAT IS WHY I AM USING \\

while True:
	message=input("USER:")

	if(message.strip() != 'bye'):
		reply=bot.get_response(message)
		print("BOT:" + reply)

	if(message.strip() == 'bye'):
		print("BOT:BYE :-), hope to see you again")	
		break


Also, I downloaded the code from GitHub and using the same path.

**Comment by Ligh7bringer** [comment]
```

**Comment by Ligh7bringer** [comment]
Your import is not correct.

```
from chatterbot.trainers import ListTrainer
```

Have a look at the [documentation](https://chatterbot.readthedocs.io/en/stable/index.html) if you need more information about something.

You can also install chatterbot-corpus with pip. I don't think there are any advantages of downloading it from github and using an absolute path to the training files. There are examples in the documentation.

**Comment by neelabhsriv** [comment]
Sir, Thanks for your advice.
