### ISSUE TITLE
Logic Adapters 

### ISSUE THREAD

**Issue by Augus2411** [gunthercox/ChatterBot#1663]
@gunthercox is there a way for the logic adapters can give responce even though the users input right key words in a random way. 
below is oneof  the statement for my data training 
- - monthly payment BEED 4th year 
  - $ 4, 588.00  
users input
4th year BEED monthly payment. 

can logic adapters still give the   - $ 4, 588.00  answer?
please help

**Comment by Dulce06** [comment]
You can use this in your logic adapter.

>  {
>                     'import_path': 'chatterbot.logic.BestMatch',
>                     'statement_comparison_function': 'levenshtein_distance',
>                 },

You could browse to get more info about **"levenshtein_distance"**
