### ISSUE TITLE
requirements.txt is missing "pytz"

### ISSUE THREAD

**Issue by i3games** [gunthercox/ChatterBot#1664]
Chatterbot requires **pytz**, but it is not installed with pip.

Running the first example new users currently see this: 

`ModuleNotFoundError: No module named 'pytz'`

**Comment by vkosuri** [comment]
which version of chatterbot are you using, try to upgrade to latest version ```pip3 install --upgrade chatterbot``

**Comment by i3games** [comment]
The master branch. pytz is missing in requirements.txt

**Comment by Ligh7bringer** [comment]
I was also missing pytz when I installed chatterbot (latest) with pip.

**Comment by vkosuri** [comment]
Yes it seems to me the conversion required ``pytz``, meanwhile you could install through ``pip install pytz``

**Comment by i3games** [comment]
I did install manually, I am reporting the error so you can fix it.

**Comment by florimondmanca** [comment]
@i3games I proposed a fix in #1670. It was a matter of a quick edit to `requirements.txt` on the GitHub editor!
