### ISSUE TITLE
how to hide the elements which are in loop in either javascript or jquery 

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1666]
Hi everyone,

I want to know how to hide and show the elements from the for loop in java script/J query

Thanks in advance....

Happy codding......

**Comment by vkosuri** [comment]
Are looking anything relevant to chatterbot?

**Comment by mady143** [comment]
yes @vkosuri

**Comment by gunthercox** [comment]
Hi @mady143 perhaps this is similar to what you are looking to do?

https://www.w3schools.com/jquery/jquery_hide_show.asp

**Comment by mady143** [comment]
Hi @gunthercox  i had a small doubt in chatter bot

***** when we are developing a chatter bot for a eCommerce application then if we entered any string that relates to our products then we will display the particular data when we entered a spell mistake of the particular then how can we get the exact string from the csv file 

***** How can we check with lower and uppercase if out string is uppercase letters in csv file but my csv file is full of Uppercase letter how can we compare with the case sensitive

*****  and how can we match the inputs which we are entered that exactly matches to the csv file 

can you clarify me these three conditions 

Thanks in advance .....
Happy codding

**Comment by gunthercox** [comment]
1. Spelling correction is a challenging problem to solve and I'm certain that a perfect solution doesn't exist. However, you may be able to find an existing library that will help with this. Google is an excellent way to start your research.

2. One strategy that you can use to compare strings that are a combination of uppercase and lowercase letters is to "normalize" the capitalization. For example, if you convert both strings to lowercase, they will be equal if all the characters are the same regardless of their previous capitalization.

3. A good way to design this might be to think about how you would write this code normally (in other words: don't try to think about how you would do this search in ChatterBot). Once you have a working solution, then you can work on integrating it with your chat bot. A good place to begin may be to write a customized logic adapter for this. I can help further if this is the direction you choose to go in.
