### ISSUE TITLE
AttributeError: 'str' object has no attribute 'text'

### ISSUE THREAD

**Issue by anjarul** [gunthercox/ChatterBot#1667]
"""
Created on Thu Mar 14 23:59:27 2019

@author: anjarul
"""

from chatterbot import ChatBot

from chatterbot.comparisons import LevenshteinDistance

bot2 = ChatBot('Eagle',
               logic_adapters=['chatterbot.logic.BestMatch'
                               ],
               preprocessors=[
                       'chatterbot.preprocessors.clean_whitespace'
                             ],
               read_only=True
               )

while True:

    message = input ('You: ')
  
    
    reply = bot2.get_response(message) 
    
    dist = LevenshteinDistance().compare(message,reply)
    print (dist,'   sdd')
    print('Eagle: ',reply)
    
    if message.strip()=='bye':
        print('Eagle: bye')
        break;

when i run this, i got an error.

Traceback (most recent call last):
  File "two.py", line 51, in <module>
    dist = LevenshteinDistance().compare(message,reply)
  File "/home/anjarul/anaconda3/lib/python3.6/site-packages/chatterbot/comparisons.py", line 44, in compare
    if not statement.text or not other_statement.text:
AttributeError: 'str' object has no attribute 'text'

how can I solve this issue

**Comment by Ligh7bringer** [comment]
It looks like the ```LevenshteinDistance().compare()``` method takes 2 ```Statement``` objects as parameters and your ```message``` variable is just a string. I'm guessing you need to create a Statement object from the ```message``` string you have, e.g.
```
from chatterbot.conversation import Statement


message = input ('You: ')
# do the other stuff you're doing

msg_statement = Statement(message)
dist = LevenshteinDistance().compare(msg_statement , reply)
# do everything else
```

**Comment by anjarul** [comment]
Thank you. it works
