### ISSUE TITLE
unable to deploy to heroku

### ISSUE THREAD

**Issue by eeerrrttty** [gunthercox/ChatterBot#1668]
Counting objects: 52, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (43/43), done.
Writing objects: 100% (52/52), 125.35 KiB | 0 bytes/s, done.
Total 52 (delta 6), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote: -----> Installing python-3.7.2
remote: -----> Installing pip
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting django<2.2,>=2.1 (from -r /tmp/build_f28562aae66b42bd561ce2065e8f0f3a/requirements.txt (line 1))
remote:          Downloading https://files.pythonhosted.org/packages/c7/87/fbd666c4f87591ae25b7bb374298e8629816e87193c4099d3608ef11fab9/Django-2.1.7-py3-none-any.whl (7.3MB)
remote:        Collecting pytz (from django<2.2,>=2.1->-r /tmp/build_f28562aae66b42bd561ce2065e8f0f3a/requirements.txt (line 1))
remote:          Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
remote:        Installing collected packages: pytz, django
remote:        Successfully installed django-2.1.7 pytz-2018.9
remote: 
remote: -----> $ python manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "manage.py", line 10, in <module>
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
remote:            django.setup()
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
remote:            apps.populate(settings.INSTALLED_APPS)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
remote:            app_config = AppConfig.create(entry)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
remote:            mod = import_module(mod_path)
remote:          File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 983, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
remote:          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:          File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 983, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
remote:        ModuleNotFoundError: No module named 'chatterbot'
remote: 
remote:  !     Error while running '$ python manage.py collectstatic --noinput'.
remote:        See traceback above for details.
remote: 
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote: 
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote: 
remote:        https://devcenter.heroku.com/articles/django-assets
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to demo-herot-chatbotter.
remote: 
To https://git.heroku.com/demo-herot-chatbotter.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/demo-herot-chatbotter.git'

Wanting a explanation guide on how deploy on heroku.

**Comment by vkosuri** [comment]
These note might help you https://github.com/vkosuri/chatterbot-live-example

**Comment by eeerrrttty** [comment]
Hi friend, i tried this also. It is 2 years old, cloning and deploying is not working here.

**Comment by eeerrrttty** [comment]
I'm new on django and wanted to not waste much time deploying. (I'm the project owner of a very big project, do not have much time)

**Comment by eeerrrttty** [comment]
Would be nice if you update your chatterbot-live-example with the recent code of chatterbot

**Comment by eeerrrttty** [comment]
Your code didn't run even after cloning + basic command, returning:

  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage

**Comment by vkosuri** [comment]
Yes will do

**Comment by eeerrrttty** [comment]
adium-theme-ubuntu==0.3.4

unity-lens-photos==1.0

these two requirements conflicts with heroku deploy. (At least here).
Im use the django_example from chatterbot directly

**Comment by gunthercox** [comment]
The error message you posted indicated that ChatterBot is not installed in your Heroku setup:

```
No module named 'chatterbot'
```

Please make sure that you are installing the `chatterbot` library before attempting to run your code.
