### ISSUE TITLE
Error is occuring: 'ChatBot' object has no attribute 'set_trainer

### ISSUE THREAD

**Issue by suman56** [gunthercox/ChatterBot#1675]
#code 

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

bot=ChatBot('Bot')
bot.set_trainer(ListTrainer)

for files in os.listdir('D:/chatterbot-corpus-master/chatterbot_corpus/data/english/'):
    data= open('D:/chatterbot-corpus-master/chatterbot_corpus/data/english/'+files,'r').readlines()
    bot.train(data)

while True:
       message=input('You: ')
       if message.strip() != 'Bye':
          reply=bot.get_response(message)
          print('ChatBot:',reply)
       if message.strip() == 'Bye':
              print('ChatBot : Bye')
              break
       

Please help us and guide us where we are going wrong.

**Comment by gunthercox** [comment]
Hi @suman56 there is an excellent solution to your problem mentioned here: https://github.com/gunthercox/ChatterBot/issues/1674#issuecomment-475469375

**Comment by suman56** [comment]
Thank you so much @gunthercox . The problem is solved.
I have one more question/doubt. Actually, when I'm importing ChatterBotCorpusTrainer, there are .yml scripts that are being executed. However, all the responses are not up to the mark.
So, my question is if I want to write my own script and train the chatbot, what are the changes I need to make in the program?
Moreover, is there any pre-existing chatbot script which is more efficient that Chatterbot_Corpus script and compatible with Python 3.7?

**Comment by gunthercox** [comment]
@suman56 No problem, I'm happy I could help.

To train a chat bot with your own data (via yml files) you can just pass the file names or directory path into the `train` function. Here is a quick example:

```
trainer.train(
    "./data/greetings_corpus/custom_file.yml",
    "./data/my_corpus/"
)
```

**Comment by suman56** [comment]
Okay :-)
is there any pre-existing chatbot script which is more efficient that Chatterbot_Corpus script and compatible with Python 3.7?

**Comment by gunthercox** [comment]
Can you clarify what you mean by "Chatterbot_Corpus script"?
Also, by "efficient" do you mean faster, more accurate, or something else?

**Comment by suman56** [comment]
By Chatterbot corpus script I mean the subfiles (.yml files) of the folder "data"-->"chatterbot_corpus"-->chatterbot corpus master. For example, we are selecting English as a language and then further we have .yml files related to history, politics, AI etc..
So, if I'm trying to edit the contents in subfile "AI" and then running the program it's giving an error.

Basically, my question to you is can't I edit these files? Is there no other "data" to train the bot to be more accurate. By efficient I only meant more accurate and not faster.

**Comment by gunthercox** [comment]
Yes, these files can be edited. This can be done by downloading a copy and making modifications.
I am not aware of any other training data that can be used to make the bot more accurate.

**Comment by suman56** [comment]
Hey @gunthercox,

When I am writing the code as you suggested previously, i.e.,
trainer.train(
               "D:/chatterbot-corpus-master/chatterbot_corpus/data/english/",
               "C:/Users/suman/Desktop/chat.yml"        #my data
             )
 I am getting an error for this while training:

Traceback (most recent call last):
  File "major_project.py", line 7, in <module>
    "C:/Users/suman/Desktop/chat.yml"
  File "C:\Users\suman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\trainers.py", line 138, in train
    for corpus, categories, file_path in load_corpus(*data_file_paths):
  File "C:\Users\suman\AppData\Local\Programs\Python\Python37-32\lib\site-packages\chatterbot\corpus.py", line 65, in load_corpus
    conversations = corpus_data.get('conversations', [])
AttributeError: 'str' object has no attribute 'get'

Please help.

**Comment by gunthercox** [comment]
For this new error, it is likely that the format of the content in `C:/Users/suman/Desktop/chat.yml` is incorrect. Double check that the layout of the markup fully resembles how it is done in the other corpus files.

**Comment by suman56** [comment]
I tried and checked the layout of the markup. Could you please tell me the procedure to create my own corpus file that could be used to train the chatbot?

**Comment by gunthercox** [comment]
Yes.

1. Create a new yml file.

```
my_example.yml
```

2. Add the following header content to the file:

```
categories:
- category_1
- category_2
```

3. Add dialog content to the file after the header:

```
conversations:
- - Good morning, how are you?
  - I am doing well, how about you?
  - I'm also good.
- - Will you have a new conversation with me?
  - No, I am busy.
```

Note that the start of each new conversation is denoted by a `- -` mark.

**Comment by suman56** [comment]
Thank you @gunthercox. The chatbot is working fine. Keep helping people, God bless you.

**Comment by modiayush98** [comment]
# code

from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
import os

bot =  ChatBot('Test')
bot.set_trainer(ListTrainer)

for  _files in os.listdir('C:/Users/ayush\Downloads\Compressed\chatterbot-corpus-master\chatterbot_corpus\data\english/'):
      chats = open('C:Users/ayush\Downloads\Compressed\chatterbot-corpus-master\chatterbot_corpus\data\english/' +_file, 'r').readlines()

      bot.train(chats)
while True:
      request = input('You:  ')
      reponse = bot.get_reponse(request)
      print('Bot: ' + response)


error
AttributeError: 'ChatBot' object has no attribute 'set_trainer'

i have tried #1674  , but still getting an error.... plz help....

**Comment by gunthercox** [comment]
@modiayush98 Make sure you have removed the `bot.set_trainer(ListTrainer)` as shown in the solution demonstrated in #1674. If the issue persists please open a new issue.

**Comment by saurabhnagvekar** [comment]
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

bot = ChatBot(
    'Techo',
     storage_adapter='chatterbot.storage.SQLStorageAdapter',
     input_adapter='chatterbot.input.TerminalAdapter',
     output_adapter='chatterbot.output.TerminalAdapter',
     logic_adapter=[
         
         "chatterbot.logic.BestMatch"
     ],
     database='./database.sqlite3'
)
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ROCK\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ROCK\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

bot.set_trainer(ListTrainer)
data = open('Chat_bot.txt').read()
talk = data.strip().split('\n')
bot.train(talk)
AttributeError                            Traceback (most recent call last)
<ipython-input-8-17bb3bd88535> in <module>
----> 1 bot.set_trainer(ListTrainer)
      2 data = open('Chat_bot.txt').read()
      3 talk = data.strip().split('\n')
      4 bot.train(talk)

AttributeError: 'ChatBot' object has no attribute 'set_trainer'

@guntercox, please help me out to solve this error

**Comment by vkosuri** [comment]
I think you are using old version, please upgrade to latest version ``pip install --upgrade chatterbot``

Here is the latest version sample example

``` Python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

# Create a new chat bot named Charlie
chatbot = ChatBot('Charlie')

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

# Get a response to the input text 'I would like to book a flight.'
response = chatbot.get_response('I would like to book a flight.')

print(response)
```

**Comment by saurabhnagvekar** [comment]
> I think you are using old version, please upgrade to latest version `pip install --upgrade chatterbot`
> 
> Here is the latest version sample example
> 
> ```python
> from chatterbot import ChatBot
> from chatterbot.trainers import ListTrainer
> 
> # Create a new chat bot named Charlie
> chatbot = ChatBot('Charlie')
> 
> trainer = ListTrainer(chatbot)
> 
> trainer.train([
>     "Hi, can I help you?",
>     "Sure, I'd like to book a flight to Iceland.",
>     "Your flight has been booked."
> ])
> 
> # Get a response to the input text 'I would like to book a flight.'
> response = chatbot.get_response('I would like to book a flight.')
> 
> print(response)
> ```

Thank you for your time.
I have a doubt, I want to call my chat file in the program. So please tell me about this

**Comment by saurabhnagvekar** [comment]
> > I think you are using old version, please upgrade to latest version `pip install --upgrade chatterbot`
> > Here is the latest version sample example
> > ```python
> > from chatterbot import ChatBot
> > from chatterbot.trainers import ListTrainer
> > 
> > # Create a new chat bot named Charlie
> > chatbot = ChatBot('Charlie')
> > 
> > trainer = ListTrainer(chatbot)
> > 
> > trainer.train([
> >     "Hi, can I help you?",
> >     "Sure, I'd like to book a flight to Iceland.",
> >     "Your flight has been booked."
> > ])
> > 
> > # Get a response to the input text 'I would like to book a flight.'
> > response = chatbot.get_response('I would like to book a flight.')
> > 
> > print(response)
> > ```
> 
> Thank you for your time.
> I have a doubt, I want to call my chat file in the program. So please tell me about this

I have an updated version of 3.7. So why I was getting that AttributeError: 'ChatBot' object has no attribute 'set_trainer'.
Please clear my doubt

**Comment by vkosuri** [comment]
The method wasn't available in later version, please go through some of the examples https://chatterbot.readthedocs.io/en/stable/examples.html#simple-example

**Comment by saurabhnagvekar** [comment]
> The method wasn't available in later version, please go through some of the examples https://chatterbot.readthedocs.io/en/stable/examples.html#simple-example

Ok thank you. Please tell me how can I use my chat files (i.e .txt file) into the program. How can I upload it?
