### ISSUE TITLE
open database.db file in my PC with Ubuntu 18 v

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1680]
Hi every one

I was unable to open the database.db file in my system with Ubuntu v 18  can any one clear this doubt

Thanks in advance...
Happy Codding....

**Comment by ignertic** [comment]
Please shed more light on your problem. 
How have you tried to open the database ?
Are you opening via a script or a gui program ? 
What problems are being triggered by this issue ?

**Comment by gunthercox** [comment]
I frequently use this tool to access various databases such as Sqlite: https://sqlectron.github.io/
