### ISSUE TITLE
Trainer module 

### ISSUE THREAD

**Issue by gods-mack** [gunthercox/ChatterBot#1682]
I am not able to run the file. It shows
ModuleNotFoundError: No module named 'chatterbot.trainer'
I also used this command: pip3 install chatterbot.trainer

![Screenshot from 2019-03-28 18-44-23](https://user-images.githubusercontent.com/31279522/55160567-a4470d00-5189-11e9-85ea-736f818435ec.png)

**Comment by ignertic** [comment]
You just left out "s" on trainer, 
> chatterbot.trainers

so your import would look like 
```python
from chatterbot.trainers import ListTrainer
```
