### ISSUE TITLE
"import chatterbot" ERROR

### ISSUE THREAD

**Issue by AfrahAsif** [gunthercox/ChatterBot#1688]
This has been working perfectly until the recents upgradations you have made..
Following is the error I get when I run the cell with ```import chatterbot```
![Captureerror](https://user-images.githubusercontent.com/22939515/55375679-baa6ed00-552a-11e9-9d69-48a6ff435ad8.PNG)

**Comment by AfrahAsif** [comment]
okay, so I resolved the previous error by commenting line 5 in corpus.py

Now I get a new error while running the cell with ```chatbot = ChatBot('TestBot')```
and following error arises,
```TypeError                                 Traceback (most recent call last)
<ipython-input-18-dcdc0d6a7088> in <module>()
----> 1 chatbot = ChatBot('Bot')

c:\users\afrah\appdata\local\programs\python\python36\lib\site-packages\chatterbot\chatterbot.py in __init__(self, name, **kwargs)
     36         for adapter in logic_adapters:
     37             utils.validate_adapter_class(adapter, LogicAdapter)
---> 38             logic_adapter = utils.initialize_class(adapter, self, **kwargs)
     39             self.logic_adapters.append(logic_adapter)
     40 

c:\users\afrah\appdata\local\programs\python\python36\lib\site-packages\chatterbot\utils.py in initialize_class(data, *args, **kwargs)
     45         Class = import_module(data)
     46 
---> 47         return Class(*args, **kwargs)
     48 
     49 

c:\users\afrah\appdata\local\programs\python\python36\lib\site-packages\chatterbot\logic\best_match.py in __init__(self, chatbot, **kwargs)
     19 
     20     def __init__(self, chatbot, **kwargs):
---> 21         super().__init__(chatbot, **kwargs)
     22 
     23         self.excluded_words = kwargs.get('excluded_words')

c:\users\afrah\appdata\local\programs\python\python36\lib\site-packages\chatterbot\logic\logic_adapter.py in __init__(self, chatbot, **kwargs)
     33 
     34     def __init__(self, chatbot, **kwargs):
---> 35         super().__init__(chatbot, **kwargs)
     36         from chatterbot.response_selection import get_first_response
     37 

TypeError: __init__() takes 1 positional argument but 2 were `given```

**Comment by Orfeous** [comment]
Hello @AfrahAsif ,

You should read the docs first.
To create the bot instance you need 2 parameters. 
1 is already there: the name of the bot.
2 is the configuration of your bot

[https://chatterbot.readthedocs.io/en/stable/chatterbot.html](https://chatterbot.readthedocs.io/en/stable/chatterbot.html)

see the example here
[https://chatterbot.readthedocs.io/en/stable/chatterbot.html#example-chat-bot-parameters](https://chatterbot.readthedocs.io/en/stable/chatterbot.html#example-chat-bot-parameters)
