### ISSUE TITLE
Python File is not Running for Chatterbox

### ISSUE THREAD

**Issue by dheeraj035** [gunthercox/ChatterBot#1689]
**code:**
from chatterbot.trainers import ListTrainer      #method to train the chatbot
from chatterbot import ChatBot     #import the chat bot
bot = ChatBot('Test') # Create a Chatbot
conv = open('chats.txt','r').readlines()
bot.set_trainer(ListTrainers) # Set the Trainer
bot.train(conv) # train the bot
while True:
        request = input('you:')
        response = bot.get_response(request)
print('Bot : ',response)

**error:**
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from chatterbot.trainers import ListTrainer      #method to train the chatbot
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/storage/__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/storage/storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosHypernymTagger
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/tagging.py", line 4, in <module>
    from chatterbot.tokenizers import get_sentence_tokenizer
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/tokenizers.py", line 4, in <module>
    from chatterbot.corpus import load_corpus, list_corpus_files
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/corpus.py", line 5, in <module>
    from chatterbot_corpus.corpus import DATA_DIRECTORY
ImportError: No module named 'chatterbot_corpus'

**Comment by burunducom** [comment]
Observed the similar issue with just installed ChatterBot on simple "from chatterbot import ChatBot":
```
Traceback (most recent call last):
  File "C:/my/src/bu/tester.py", line 1, in <module>
    from chatterbot import ChatBot
  File "C:\Python37\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Python37\lib\site-packages\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "C:\Python37\lib\site-packages\chatterbot\storage\__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "C:\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosHypernymTagger
  File "C:\Python37\lib\site-packages\chatterbot\tagging.py", line 4, in <module>
    from chatterbot.tokenizers import get_sentence_tokenizer
  File "C:\Python37\lib\site-packages\chatterbot\tokenizers.py", line 4, in <module>
    from chatterbot.corpus import load_corpus, list_corpus_files
  File "C:\Python37\lib\site-packages\chatterbot\corpus.py", line 5, in <module>
    from chatterbot_corpus.corpus import DATA_DIRECTORY
ModuleNotFoundError: No module named 'chatterbot_corpus'
```
Configuration:
```
ChatterBot 1.0.5
Python 3.7.3
Windows 10
```

**Comment by burunducom** [comment]
> Observed the similar issue with just installed ChatterBot on simple "from chatterbot import ChatBot":
> 
> ```
> Traceback (most recent call last):
>   File "C:/my/src/bu/tester.py", line 1, in <module>
>     from chatterbot import ChatBot
>   File "C:\Python37\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
>     from .chatterbot import ChatBot
>   File "C:\Python37\lib\site-packages\chatterbot\chatterbot.py", line 2, in <module>
>     from chatterbot.storage import StorageAdapter
>   File "C:\Python37\lib\site-packages\chatterbot\storage\__init__.py", line 1, in <module>
>     from chatterbot.storage.storage_adapter import StorageAdapter
>   File "C:\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 3, in <module>
>     from chatterbot.tagging import PosHypernymTagger
>   File "C:\Python37\lib\site-packages\chatterbot\tagging.py", line 4, in <module>
>     from chatterbot.tokenizers import get_sentence_tokenizer
>   File "C:\Python37\lib\site-packages\chatterbot\tokenizers.py", line 4, in <module>
>     from chatterbot.corpus import load_corpus, list_corpus_files
>   File "C:\Python37\lib\site-packages\chatterbot\corpus.py", line 5, in <module>
>     from chatterbot_corpus.corpus import DATA_DIRECTORY
> ModuleNotFoundError: No module named 'chatterbot_corpus'
> ```
> Configuration:
> 
> ```
> ChatterBot 1.0.5
> Python 3.7.3
> Windows 10
> ```

Solved after I've installed chatterbot-corpus Python module. It seems it isn't installed with "pip install chatterbot".

**Comment by PrinceChukz** [comment]
@burunducom did you use "pip install chatterbot-corpus" ? Which other methods?

**Comment by burunducom** [comment]
> @burunducom did you use "pip install chatterbot-corpus" ? Which other methods?

Yes, with pip.

**Comment by burunducom** [comment]
> @burunducom did you use "pip install chatterbot-corpus" ? Which other methods?

I think you can also use 'pip install git+git://github.com/gunthercox/chatterbot-corpus@master'

**Comment by PrinceChukz** [comment]
please help @orfeous @gunthercox 
'pip install git+git://github.com/gunthercox/chatterbot-corpus@master'
error:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\PRINZC~1
\AppData\Local\Temp\pip-req-build-jm4uoru6\

**Comment by Orfeous** [comment]
Hi @PrinceChukz,

Please try to run first
pip install --upgrade setuptools

Then rerun the corpus install.

Cheers,
/Gabor

**Comment by Barun-Kumar** [comment]
if nothing works you could try.
I struggle a lot i tried with python 3.7 and 3.6 , I was facing the same issue. 
finally i manually download and pasted in the C:\Python\python36\Lib\site-packages
and it worked .
make sure you put your python path correctly.
