### ISSUE TITLE
how to train from corpus when use in the django

### ISSUE THREAD

**Issue by cupcakefromchina** [gunthercox/ChatterBot#1703]
I put a train.py in the same file with the manage.py.
the code like this
`from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
chatbot = ChatBot('Chatterbot',trainer='chatterbot.trainers.CorpusTrainer')
trainer = ChatterBotCorpusTrainer(chatbot)
trainer.train( 'chatterbot.corpus.chinese' )`
I run the train.py first.
and run manage.py migrate
then run manage.py runserver.
But it can't answer the question right from the corpus.

**Comment by Orfeous** [comment]
I'm not that familiar with django usage (i use flask) but i believe you should run the migrate first to initialize the database before you train.

**Comment by cupcakefromchina** [comment]
> Hi @cupcakefromchina
> 
> I'm not that familiar with django usage (i use flask) but i believe you should run the migrate first to initialize the database before you train.

hello can you use the flask right.Before i use the django,i use the flask.But it will not give me the answer,even if the wrong.It can't work.
I will try migrate first.

**Comment by gunthercox** [comment]
The current way to achieve training using Django and ChatterBot will require you to build a new view, API endpoint, or custom script/command that takes your data and passes it to the `train` method of your trainer. (There isn't anything pre-built for this).

**Comment by cupcakefromchina** [comment]
> The current way to achieve training using Django and ChatterBot will require you to build a new view, API endpoint, or custom script/command that takes your data and passes it to the `train` method of your trainer. (There isn't anything pre-built for this).

thank you.I use the chatterbot
