### ISSUE TITLE
self.chatbot.storage  TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by FCALVO90** [gunthercox/ChatterBot#1705]
Hi, i am getting this error before interactuating with the Bot in various sentences. That is the CODE:

```
from chatterbot import ChatBot
from pymongo import MongoClient
from chatterbot.storage import StorageAdapter
from chatterbot.response_selection import get_most_frequent_response

import logging
logging.basicConfig(level=logging.CRITICAL)

chatbot = ChatBot(
    'Chatterbot',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    input_adapter="chatterbot.input.TerminalAdapter",
    output_adapter="chatterbot.output.OutputAdapter",
    output_format="text",
    logic_adapters=[
        {
            "import_path": "chatterbot.logic.BestMatch",
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
            "response_selection_method": "chatterbot.response_selection.get_most_frequent_response"
        },
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'maximum_similarity_threshold': 0.99,
            'default_response': 'Disculpa, no te he entendido bien, sólo soy experto en viajes. ¿Puedes ser más específico?.'
        },
        {
            'import_path': 'chatterbot.logic.SpecificResponseAdapter',
            'input_text': 'Quiero reservar un crucero',
            'output_text': 'Puedes reservarlo ahora en: https://www.logitravel.com/cruceros/'
        },
    ],
    database_uri='mongodb://localhost:27017/chatterbot_cruises_database',
    preprocessors=[
        'chatterbot.preprocessors.clean_whitespace'
    ],
    read_only=False
)


#l entrenamos
from chatterbot.trainers import ListTrainer
trainer = ListTrainer(chatbot)

from chatterbot.trainers import ChatterBotCorpusTrainer
trainer = ChatterBotCorpusTrainer(chatbot)

trainer.train("C:/Users/***/Documents/cruises_ES.yml")

while(True):
    input_string2 = input('Tu: ')
    response = chatbot.get_response(input_string2)
    print('Chatbot: '+ response.text)
```

That is the Output:

Tu: hola
Chatbot: No, no se admiten mascotas a bordo.

Tu: por ?
Traceback (most recent call last):

  File "<ipython-input-19-f53a0ca4d130>", line 51, in <module>
    response = chatbot.get_response(input_string2)

  File "C:\Users\****\Anaconda3\lib\site-packages\chatterbot\chatterbot.py", line 139, in get_response
    response = self.generate_response(input_statement, additional_response_selection_parameters)

  File "C:\Users\****\Anaconda3\lib\site-packages\chatterbot\chatterbot.py", line 175, in generate_response
    output = adapter.process(input_statement, additional_response_selection_parameters)

  File "C:\Users\****\Anaconda3\lib\site-packages\chatterbot\logic\best_match.py", line 90, in process
    self.chatbot.storage

TypeError: 'str' object is not callable

**Comment by gunthercox** [comment]
Some of your settings need to be changed into callables:

```
from chatterbot import comparisons, response_selection
# ...
# ...
# ...
            "statement_comparison_function": comparisons.levenshtein_distance,
            "response_selection_method": response_selection.get_most_frequent_response
```

**Comment by FCALVO90** [comment]
getting the same error.
![image](https://user-images.githubusercontent.com/48654949/56864966-e0f46700-69c8-11e9-827c-00b1860f99d7.png)

Thanks, regards.
Felipe.

**Comment by gunthercox** [comment]
@FCALVO90 based on the screen shot you posted, I can only guess that one of the values you set in the configuration is a string when it is suppose to be a callable instead. If you'd like I can provide further insight, just post the following:

1. The version of ChatterBot you are using.
2. A copy of the parameters you are passing into the `ChatBot` class in your code.
