### ISSUE TITLE
Error in training custom YML file as corpus

### ISSUE THREAD

**Issue by kartik810** [gunthercox/ChatterBot#1706]
Code:
`english_bot = ChatBot("Chatterbot",
                      storage_adapter="chatterbot.storage.SQLStorageAdapter",
                             )

trainer = ChatterBotCorpusTrainer(english_bot)
trainer.train("data/train11.yml")
`
YML File:
- - Can you tell me the history of the college?
  - HITAM today is a standing testimony to the vision of Arutla Prashanth, its Founder & Chairman.It was established in 2001.
  - what is the history of the college?
- - Hi
  - hello how are you?
  - Hey there
  - whatsup?
  - sup
- - how are you?
  - I am great
  - I am fine
  - Fine how are you?

After running this I am getting the error as
Traceback (most recent call last):

  File "app.py", line 38, in <module>
    trainer.train("data/train11.yml")
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatterbot\trainers.py", line 138, in train
    for corpus, categories, file_path in load_corpus(*data_file_paths):
  File "C:\ProgramData\Anaconda3\lib\site-packages\chatterbot\corpus.py", line 65, in load_corpus
    conversations = corpus_data.get('conversations', [])
AttributeError: 'list' object has no attribute 'get'

I am using  Python 3.7.0 and Chatterbot version 1.0.4
Hey @gunthercox can you please help me out

**Comment by gunthercox** [comment]
You'll want to make sure that you include the `conversations` identifier at the beginning of the list of conversations in your YAML. Here is an example:

```
categories:
- conversations
conversations:
- - Good morning, how are you?
  - I am doing well, how about you?
- - Hello
  - Hi
  - How are you doing?
  - I am doing well.
```
