### ISSUE TITLE
i'm getting this issue please help!

### ISSUE THREAD

**Issue by proguy627** [gunthercox/ChatterBot#1707]
[nltk_data] Downloading package stopwords to C:\Users\XXXX
[nltk_data]     XXX\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\XXXXXXXX\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
Traceback (most recent call last):
  File "C:\Users\XXXXXXXXX\myproject\chatbotpro\chatbot.py", line 8, in <module>
    bot.set_trainer(ListTrainer)
AttributeError: 'ChatBot' object has no attribute 'set_trainer'

**Comment by proguy627** [comment]
getting this issue please help noob in python

**Comment by Orfeous** [comment]
set_trainer is obsolete, and has been removed. see below how to use the trainer.
`...
trainer = ListTrainer(bot)
trainer.train()
...`

**Comment by PrinceChukz** [comment]
👆👆that's correct @orfeous
