### ISSUE TITLE
ModuleNotFoundError: No module named 'chatterbot_corpus' error

### ISSUE THREAD

**Issue by SperCoder** [gunthercox/ChatterBot#1708]
i was running a the basic example code from \examples:

`

**_from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

# Create a new chat bot named Charlie
chatbot = ChatBot('Charlie')

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

# Get a response to the input text 'I would like to book a flight.'
response = chatbot.get_response('I would like to book a flight.')

print(response)

`_**

________
Your work is great so pls respond fastly! Thanks!

**Comment by PrinceChukz** [comment]
I am having the same issue of no module chatterbot corpus, must i pip install chatterbot-corpus to be able to train the chatterbot? Or will pip install chatterbot alone do everything

**Comment by SperCoder** [comment]
I fixed it myself. pip install chatterbot-coprus worked for me

**Comment by Orfeous** [comment]
Hello @PrinceChukz,
@SperCoder is correct.
The corpus itself is a separate package, thus have to be installed separately.

**Comment by PrinceChukz** [comment]
pip install chatterbot-corpus worked but it uninstalls the version of the pyYAML file needed as a requirement for the chatterbot to work properly and installs an older version. Which is not good for the training

**Comment by PrinceChukz** [comment]
![image](https://user-images.githubusercontent.com/37223482/56588003-6eefdc80-65da-11e9-8951-fb2bac49cc7f.png)

**Comment by PrinceChukz** [comment]
@gunthercox @Orfeous Getting that error when i try installing from git as stated in chatterbot requirements.txt

**Comment by Orfeous** [comment]
Hello @PrinceChukz,

This looks strange. 
Just to close out common cases:

- Do you have enough free disk space?
- What version of windows 10 ou running? The path may be longer that 260 characters. [Read more here](https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/)
- when you browse into that directory can you write and/or modify files there?

**Comment by shamsher786** [comment]
Not able to install chatterbot-corpus library using pip command.

![Screenshot_71](https://user-images.githubusercontent.com/20358682/59011386-33d7fe80-8852-11e9-9e41-0f6f24e221f9.png)

![Screenshot_72](https://user-images.githubusercontent.com/20358682/59011413-481bfb80-8852-11e9-8ab1-e70d9748992a.png)

**Comment by Barun-Kumar** [comment]
Hi,
I having the same issue.
any suggestion

**Comment by Barun-Kumar** [comment]
I struggle a lot i tried with python 3.7 and 3.6 , I was facing the same issue. 
finally i manually download and pasted in the C:\Python\python36\Lib\site-packages
and it worked .
make sure you put your python path correctly.

**Comment by vishal2612200** [comment]
> I fixed it myself. pip install chatterbot-coprus worked for me

This one also worked for me. Thank you

**Comment by vishal2612200** [comment]
> Not able to install chatterbot-corpus library using pip command.
> 
> ![Screenshot_71](https://user-images.githubusercontent.com/20358682/59011386-33d7fe80-8852-11e9-9e41-0f6f24e221f9.png)
> 
> ![Screenshot_72](https://user-images.githubusercontent.com/20358682/59011413-481bfb80-8852-11e9-8ab1-e70d9748992a.png)

@shamsher786 You have written wrong command i.e corpus not coprus
correct command
<pre>pip install chatterbot-corpus</pre>

**Comment by divyareddy10** [comment]
unable to install chatterbot-corpus
tried 
`pip install chatterbot-corpus`
`conda install -c anaconda pyyaml`
nothing worked
![error](https://user-images.githubusercontent.com/22145883/59799028-1a7a8c00-9301-11e9-89ad-629c034b26ca.PNG)

**Comment by Orfeous** [comment]
How about
`pip3 install chatterbot-corpus`

? :)

**Comment by gunthercox** [comment]
Hey @SperCoder, I'm glad you were able to resolve your issue. I'm going to close this ticket off.
