### ISSUE TITLE
data error

### ISSUE THREAD

**Issue by sadmansad2003** [gunthercox/ChatterBot#1711]
![error](https://user-images.githubusercontent.com/38854489/56682620-c2068400-66ed-11e9-8fbb-662679cfbfb0.png)
this is the error i got every time i run it.
i don't know what to do.please tell me what to do.

**Comment by Orfeous** [comment]
`pip install chatterbot-corpus`

This will install the corpus which is a separate package.

**Comment by sadmansad2003** [comment]
![solve](https://user-images.githubusercontent.com/38854489/56734618-2b85a180-6785-11e9-9dd8-83164e08c9a2.png)
thank you very much for your help

**Comment by sadmansad2003** [comment]
![problem](https://user-images.githubusercontent.com/38854489/56744667-c2a92400-679a-11e9-8db0-b16e30e5e96d.PNG)
![problem2](https://user-images.githubusercontent.com/38854489/56744674-c5a41480-679a-11e9-9a8e-e2947f7a4e02.PNG)
what should i do now.please help me

**Comment by sadmansad2003** [comment]
by the way i fix that problem.sorry for that. now i got a new problem.i don't know how to fix this one.
![problem](https://user-images.githubusercontent.com/38854489/56800053-01db8180-683c-11e9-8b20-66bd79a3822a.PNG)
please help me with this problem.

**Comment by Orfeous** [comment]
`bot.train(data)`
should be
`trainer.train(data)`

**Comment by sadmansad2003** [comment]
after trainer.train(data) this shows
![problem](https://user-images.githubusercontent.com/38854489/56805680-a2856d80-684b-11e9-80ff-35341ad2ea34.PNG)

**Comment by sadmansad2003** [comment]
Tell me something.I am giving you the file. Tell me where i did wrong.
[chatbot.zip](https://github.com/gunthercox/ChatterBot/files/3122396/chatbot.zip)
Please help.I need your help fast.Please do something.

**Comment by Orfeous** [comment]
Hello @sadmansad2003 ,

Just realized what you did here.
Please check it in the [docs](https://chatterbot.readthedocs.io/en/stable/training.html#training-with-corpus-data).

You don't have to read the file manually, let the trainer do that for you.

replace this part:
```
for files in os.listdir('data/english/'):
 data = open('data/english/' + files , 'r').readlines()
 trainer.train(data)
```
With this:
```
trainer.train(
    "./data/english/"
)
```
and it should be fine. :)

**Comment by sadmansad2003** [comment]
@Orfeous thanks you very much.my problem is solve.
