### ISSUE TITLE
I cannot add levenshtein_distance in statement_comparison_function: logic adapter

### ISSUE THREAD

**Issue by Pechi77** [gunthercox/ChatterBot#1712]
Hi I initiated the bot as described [here](https://chatterbot.readthedocs.io/en/stable/logic/#setting-parameters),

my code: 
```
import chatterbot
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.response_selection import get_most_frequent_response


bot = ChatBot('Manoj',
response_selection_method=get_most_frequent_response,
storage_adapter='chatterbot.storage.SQLStorageAdapter',
input_adapter='chatterbot.input.TerminalAdapter',
output_adapter='chatterbot.output.TerminalAdapter',
logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            "statement_comparison_function":chatterbot.comparisons.levenshtein_distance,
            "response_selection_method": "chatterbot.response_selection.get_random_response",
            'import_path': 'chatterbot.logic.BestMatch',
            'threshold': 0.7,
        }
  ]
)
```

when I run the code I get,

`AttributeError: module 'chatterbot' has no attribute 'comparisons'` Please help.

**My chatterbot version: 1.0.5**

**Comment by bufferbox** [comment]
Hello,
Did you try putting `chatterbot.comparisons.levenshtein_distance` in quotes?

For example,

`logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            "statement_comparison_function": **"chatterbot.comparisons.levenshtein_distance"**,
            "response_selection_method": "chatterbot.response_selection.get_random_response",
            'import_path': 'chatterbot.logic.BestMatch',
            'threshold': 0.7,
        }
  ]`

**Comment by Pechi77** [comment]
ya with quotes it is working but  why there is no quotes in the documentation? here[https://chatterbot.readthedocs.io/en/stable/logic/#setting-parameters]
