### ISSUE TITLE
How to install odoo 11 in ubutu 18.04 and work with python

### ISSUE THREAD

**Issue by mady143** [gunthercox/ChatterBot#1714]
Hi,Every one 

I am trying to install odoo in my system ubuntu 18.04 v and i am getting an error like 

**dpkg Error**

**No directory, logging in with HOME=/
chown: cannot access '/var/lib/odoo': No such file or directory
dpkg: error processing package odoo (--configure):
 installed odoo package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 odoo
E: Sub-process /usr/bin/dpkg returned an error code (1)**

and also tried this commands to rectify these errors  like

**sudo apt install -f

sudo dpkg --configure -a**

and still i am getting above error please help in this issue how can i rctify it and please help in the  installation part of odoo 11 

Thanks in advance,
Happy Codding.

**Comment by Orfeous** [comment]
How is this related to the Chatterbot?

**Comment by mady143** [comment]
No Orfeous its sepearte

**Comment by mady143** [comment]
I am getting 

**Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

**Comment by gunthercox** [comment]
Hi @mady143, I am not familiar with what odoo is. I believe you may have better luck seeing out a solution from the owners/maintainers of that software.
