### ISSUE TITLE
How do you actually get "Personas" to work

### ISSUE THREAD

**Issue by UniqueUname** [gunthercox/ChatterBot#1719]
It looks like commit https://github.com/gunthercox/ChatterBot/pull/1431/commits/0768dacc2b2b9295da49ba176ee284f61e73b227 added a persona thing,
Let's say that I have a huge conversation, if I create different bots and trainers for every person on the conversation and train every bot via their messages, would that work?
The actual reason why I'm asking this is because I've tried it that way and trainers just trained every single bot in the same way, after I exported every trainer's training data every json file had the same size and hash.
Different bots also respond in same way.
How can I use this properly?
(Also how can I get rid of my previous training data, the current export files include the example training data)

**Comment by gunthercox** [comment]
"Personas" is still an undeveloped feature in ChatterBot that isn't used yet. Feel free to follow #32 for additional updates related to the functionality of that feature.
