### ISSUE TITLE
Which logic adpater use the naive Bayesian classification algorithms？

### ISSUE THREAD

**Issue by cupcakefromchina** [gunthercox/ChatterBot#1722]
I saw this passage in [https://chatterbot.readthedocs.io/en/stable/]

> Several logic adapters in ChatterBot use naive Bayesian classification algorithms to determine if an input statement meets a particular set of criteria that warrant a response to be generated from that logic adapter.

But I don‘t know the specific logic adapter.I will write in my report，so I want to know the detail about the ChatterBot.

Thanks for the  help. @gunthercox

**Comment by cupcakefromchina** [comment]
Is it only TimeLogicAdapter that uses naive Bayesian network classification?

**Comment by vkosuri** [comment]
https://github.com/gunthercox/ChatterBot/blob/9f4a4ecac32564f245d721854d2698a07d84b405/docs/faq.rst#2-classification-algorithms

**Comment by cupcakefromchina** [comment]
> https://github.com/gunthercox/ChatterBot/blob/9f4a4ecac32564f245d721854d2698a07d84b405/docs/faq.rst#2-classification-algorithms

thank you！
