### ISSUE TITLE
Error installing build dependencies

### ISSUE THREAD

**Issue by boumediane10** [gunthercox/ChatterBot#1725]
I'm getting this error although I've downloaded Microsoft Visual C++ from this link

https://www.scivision.dev/python-windows-visual-c-14-required/

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by Orfeous** [comment]
Hello, 
please share the error message what you receive.

/Gabor

**Comment by boumediane10** [comment]
I'm getting this error although I've downloaded Microsoft Visual C++ from this link

https://www.scivision.dev/python-windows-visual-c-14-required/

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

**Comment by boumediane10** [comment]
Solved!
