### ISSUE TITLE
OSError: [E050] Can't find model 'en'.

### ISSUE THREAD

**Issue by dewangsatyam** [gunthercox/ChatterBot#1736]
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by habi3000** [comment]
@dewangsatyam  Could you post code snippet and stack trace?

**Comment by brightening-eyes** [comment]
do the following:
```python
python -m spacy download en
```

**Comment by sanchit892** [comment]
Even I am facing the same issue 
OSError: [E050] Can't find model 'en' It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory

Here is my Code 
from rasa_nlu.training_data import load_data
from rasa_nlu.config import RasaNLUModelConfig
from rasa_nlu.model import Trainer
from rasa_nlu import config

def train_nlu(data, config_file, model_dir):
    training_data = load_data(data)
    trainer = Trainer(config.load(config_file))
    trainer.train(training_data)
    model_directory = trainer.persist(model_dir, fixed_model_name='weathernlu')


if __name__ == '__main__':
    train_nlu("./data/data.json", "config_spacy.json", "./models/nlu")



here is the result that I am getting:


C:\Users\sanchit\PycharmProjects\chatbots\venv\Scripts\python.exe C:/Users/sanchit/PycharmProjects/chatbots/nlu_model.py
Traceback (most recent call last):
  File "C:/Users/sanchit/PycharmProjects/chatbots/nlu_model.py", line 18, in <module>
    train_nlu("./data/data.json", "config_spacy.json", "./models/nlu")
  File "C:/Users/sanchit/PycharmProjects/chatbots/nlu_model.py", line 12, in train_nlu
    trainer = Trainer(config.load(config_file))
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_nlu\model.py", line 150, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_nlu\model.py", line 162, in _build_pipeline
    component = component_builder.create_component(component_cfg, cfg)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_nlu\components.py", line 448, in create_component
    component_config, cfg)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_nlu\registry.py", line 186, in create_component_by_config
    return component_class.create(component_config, config)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\rasa_nlu\utils\spacy_utils.py", line 64, in create
    nlp = spacy.load(spacy_model_name, disable=['parser'])
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "C:\Users\sanchit\PycharmProjects\chatbots\venv\lib\site-packages\spacy\util.py", line 171, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Process finished with exit code 1

**Comment by JanuaryThomas** [comment]
python -m spacy download en

**Comment by gunthercox** [comment]
You can also do something like this to link the installed spacy model to the preferred language code name:
```
python -m spacy link en_core_web_sm en
```

**Comment by codePerfectPlus** [comment]
try these command
```
pip install spacy
python -m spacy download en
```

**Comment by h0oni** [comment]
These commands worked for me. Had the same issue. 
`pip` install spacy
python -m spacy download en
python -m spacy link en_core_web_sm en`

**Comment by h0oni** [comment]
These commands worked for me. Had the same issue.
`pip install spacy\n
python -m spacy download en\n
python -m spacy link en_core_web_sm en`

**Comment by h0oni** [comment]
These commands worked for me. Had the same issue.
`pip install spacy
python -m spacy download en
python -m spacy link en_core_web_sm en`

**Comment by h0oni** [comment]
These commands worked for me. Had the same issue.
`pip install spacy`
`python -m spacy download en`
`python -m spacy link en_core_web_sm en`

**Comment by sabinahschmitz** [comment]
This worked for me! Note that there's the library "spacey" and "spacy". I kept adding the "e", which failed.

**Comment by sanjayanbu** [comment]
use anaconda navigator create new virtual environment name it tensorflow_development
install nltk, tensorflow, sklearn, numpy==1.19.3, chatterbot , chatterbot_corpus

for certain libraries use pip install to install chatterbot==0.8.7, chatterbot_corpus==1.1.4

launch the newly created env and use it for all machine learning development it will definitely work bec conda takes care of all the dependency issuses
