### ISSUE TITLE
chatterbot.logic.SpecificResponseAdapter not giving specified response

### ISSUE THREAD

**Issue by ArunSingh1** [gunthercox/ChatterBot#1741]
While running the code on documentation 

from chatterbot import ChatBot

# Create a new instance of a ChatBot
bot = ChatBot(
    'Exact Response Example Bot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.SpecificResponseAdapter',
            'input_text': 'Help me!',
            'output_text': 'Ok, here is a link: http://chatterbot.rtfd.org'
        }
    ]
)

# Get a response given the specific input
response = bot.get_response('Help me!')
print(response)

output_text': 'Ok, here is a link: http://chatterbot.rtfd.org' ---IS NOT PRINTED

![bug](https://user-images.githubusercontent.com/38204368/58703392-31932180-83c6-11e9-9d06-42deeda79721.png)

**Comment by minjae1025** [comment]
[similar issue](https://github.com/gunthercox/ChatterBot/issues/1677)

**Comment by ArunSingh1** [comment]
self.response_statement = Statement(text=output_text)

    def can_process(self, statement):
        if statement == self.input_text:
        if str(statement) == self.input_text:  ###code change calling str explicitly solves the problem 
            return True

        return False
