### ISSUE TITLE
How integrate Chatterbot with Wikipedia

### ISSUE THREAD

**Issue by AndrasPataki** [gunthercox/ChatterBot#1742]
Hello, I'm having a strong doubt about chatterbot + wikipedia integration. Since the last update in Chatterbot, many codes have changed and I was confused. I need to know how to integrate with chatterbot and wikipedia. So that what the bot does not know to answer, look in wikipedia.

**Comment by gunthercox** [comment]
Integrating ChatterBot with Wikipedia sounds like a pretty large feature, and quite a programming challenge. I would be glad to entertain a conversation about the topic. As a start, how about a demonstrative question: as a human, what process would you follow to answer the following? If you can, describe each step that you would go through to answer it.

> What are the four types of nitrogen bases found in human DNA?

**Comment by AndrasPataki** [comment]
Hello Gunthercox, I already gotta do the connect function with wikipedia. The code is very simple. It is based on the function: startswith (key): where key, is a list of predefined keys such as: who was, who defined, what is .... the rest is the own API of wikipediia. But I have another question, and it may not be so complicated. I want to know how to capture default values ​​in user inputs, and have a default response by default. For example a phrase: "I was traveling through the forest and found a bear!" the bear will be my key, which when read, will have a standard response. This answer will be indifferent to the phrase.

**Comment by minjae1025** [comment]
I'm also interested in this issue. I haven't thought about it yet, but I think we can implement it at the response_selection stage.

**Comment by gunthercox** [comment]
For returning a default response bases on the input you could create a logic adapter that returns a high confidence value (1) if the key word is in the user's input. The only downside would be that any time someone ever mentioned that word, the response would be triggered (although that might be the desired functionality in this case).

**Comment by minjae1025** [comment]
[I've written the LogicAdapter code that way.](https://github.com/gunthercox/ChatterBot/pull/1748)
