### ISSUE TITLE
logic_adapters is overlaying database_uri

### ISSUE THREAD

**Issue by leobaiano** [gunthercox/ChatterBot#1744]
I'm trying to make my bot use logical adapters and continue querying the database for the answers, but when I do this it ignores the database and everything it has been taught and only responds based on the two adapters.

I'm starting the robot like this:

```
     self.bot = ChatBot(
            nome_bot,
            storage_adapter='chatterbot.storage.SQLStorageAdapter',
            logic_adapters=[
                'chatterbot.logic.MathematicalEvaluation',
                'chatterbot.logic.TimeLogicAdapter'
            ],
            database_uri='sqlite:///db.sqlite3',
      )
```

If I remove logic_adapters it returns to respond based on the database, but I would like to keep the logical adapters and the database, is this not possible or am I doing something wrong?

**Comment by Orfeous** [comment]
Hi,

the two defined logic adapter doesn't use database for its operation.
when you remove them chatterbot falls back to its default which relies on database.

the solution is to define a logic adapter like BestMatch on top of math and time. and it should be fine. :)

**Comment by Orfeous** [comment]
see more here: [LogicAdapters](https://chatterbot.readthedocs.io/en/stable/logic/)

**Comment by leobaiano** [comment]
Many thanks @Orpheu!

I was able to solve this:

```
self.bot = ChatBot (
             name_bot,
             logic_adapters = [
                 'chatterbot.logic.BestMatch',
                 'chatterbot.logic.MathematicalEvaluation',
                 'chatterbot.logic.TimeLogicAdapter'
             ]
         )
```
Despite being sad to see that he often chooses the TimeLogicAdapter to respond instead of the bank, but I understand that this should be lacking in training :)

The example in the documentation made me understand that it would just point the bank path and they would use the adapters and the bank without needing the BestMatch.

Once again thank you very much for the help, I will continue studying here.

**Comment by Orfeous** [comment]
I'm glad to hear that. Keep learning. :)
