### ISSUE TITLE
How to integrate Chatterbot with Telegram?

### ISSUE THREAD

**Issue by imsurinder90** [gunthercox/ChatterBot#1747]
Hello,

I want to create a chatbot using Chatterbot framework, then I want to integrate with the Telegram, so the multiple users can interact to it and it is publicly accessible to everyone through the mobile device.

Please help.

Regards,
Surinder

**Comment by gunthercox** [comment]
Hi @imsurinder90, I'm not very familiar with Telegram, but I'd be happy to leave this issue open for a while in case anyone else has experience building something like this and they'd like to share.

**Comment by brightening-eyes** [comment]
use something like [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) for connecting to telegram's bot api.
you may want to use webhook feature, when your bot receives any messages, you will process it with chatterbot.
