### ISSUE TITLE
How export chatterbot to a exe project or similar

### ISSUE THREAD

**Issue by AndrasPataki** [gunthercox/ChatterBot#1750]
Hello good day. I have a problem. I can not export my chatterbot in any application. I tried the Pyinstaller but it has problems with the nltk library, cx_freeze is not exporting, it has problems in certain modules. I do not know what to do to make chatterbot an accessible application. I would like directions or help.
I have seen that it is possible to do an integration with django or flask, however I would have to reprogram all of my chatbot for integration.

**Comment by habi3000** [comment]
would it be possible to make it as a web application? using Django or Flask. This would solve all these problems and also there are already examples out there :)

**Comment by brightening-eyes** [comment]
install the latest PyInstaller, I have wrote a hook for nltk for it.
or instead, you can add nltk.chunk.named_entity to hiddenimports in your spec file.
also, chatterbot is going to use SpaCy, which you can write a hook for it as well or add it's modules in the hiddenimports

**Comment by AndrasPataki** [comment]
Hello guys. I solved the problems with the pyinstaller nltk hook. After much research, I decided to go it alone in the code structure. I solved my problem by commenting on the lines:
`datas=[]`

`'''for p in nltk.data.path:
    datas.append((p, "nltk_data"))'''`

`hiddenimports = ["nltk.chunk.named_entity"]`

What's more, you need to rename the file: pyi_rth__nltk.cpython-36.pyc to pyi_rth_nltk.cpython-36.pyc . This file have 1 more underline. Warning with the python version.

**Comment by gunthercox** [comment]
Hey @AndrasPataki, I'm glad you were able to get an executable created. Thank you for describing the changes you had to make. hopefully this will help anyone in the future who is looking to do something similar.
