### ISSUE TITLE
chatterbot issue

### ISSUE THREAD

**Issue by maheshbonagiri** [gunthercox/ChatterBot#1751]

**Comment by maheshbonagiri** [comment]
Installing build dependencies ... error
  ERROR: Complete output from command 'c:\users\mahesh\appdata\local\programs\py
thon\python37-32\python.exe' 'c:\users\mahesh\appdata\local\programs\python\pyth
on37-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:
\Users\Mahesh\AppData\Local\Temp\pip-build-env-cmkc4tc7\overlay' --no-warn-scrip
t-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --
 setuptools 'wheel>0.32.0.<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,
<2.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.0.0.dev6:
  ERROR: Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0
380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.w
hl
  Collecting wheel>0.32.0.<0.33.0
    Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f
227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
  Collecting Cython
    Using cached https://files.pythonhosted.org/packages/66/2e/8c294e995c1988f28
007b3f2c0be567e5935af19626b45b6567b19833d66/Cython-0.29.10-cp37-cp37m-win32.whl
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://files.pythonhosted.org/packages/eb/cb/4ff546a491f764f67
284572d25c57927e3f17103adf979bc99d90128f3eb/cymem-2.0.2-cp37-cp37m-win32.whl
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://files.pythonhosted.org/packages/00/52/ef641ebb40e287b95
e9742e7f3120dca0350d92b3d0ef050e5133acf8931/preshed-2.0.1-cp37-cp37m-win32.whl
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://files.pythonhosted.org/packages/22/e9/411be1845f1ac07ae
3bc40a4b19ba401819baed4fa63b4f5ef28b2300eb4/murmurhash-1.0.2.tar.gz
  Collecting thinc==7.0.0.dev6
    Using cached https://files.pythonhosted.org/packages/f2/bf/3685c4718b547583b
fe3a3d54db8f0f992e30b49db1ecbce8e5d8a4c7604/thinc-7.0.0.dev6.tar.gz
  Collecting blis<0.3.0,>=0.2.1 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/59/9e/84a83616cbe5daa94
909da38b780e93bf566dc2113c3dc35d7b4cad52f63/blis-0.2.4.tar.gz
  Collecting thinc_gpu_ops<0.1.0,>=0.0.1 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/a4/ad/11ab80a24bcedd7dd
0cfabaedba2ceaeca11f1aaeeff432a3d2e63ca7d02/thinc_gpu_ops-0.0.4.tar.gz
  Collecting numpy>=1.7.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/07/46/656c25b39fc152ea5
25eef14b641993624a6325a8ae815b200de57cff0bc/numpy-1.16.4-cp37-cp37m-win32.whl
  Collecting wrapt<1.11.0,>=1.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/a0/47/66897906448185fcb
77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
  Collecting plac<1.0.0,>=0.9.6 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2a
a1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
  Collecting tqdm<5.0.0,>=4.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f
3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
  Collecting six<2.0.0,>=1.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fec
fe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Collecting wasabi<1.1.0,>=0.0.9 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/f4/c1/d76ccdd12c716be79
162d934fe7de4ac8a318b9302864716dde940641a79/wasabi-0.2.2-py3-none-any.whl
  Collecting srsly<1.1.0,>=0.0.5 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/59/1b/542f85474db8be31b
dd6350f2d33ac8db110a98b58b30f42e2dbc446174b/srsly-0.0.6.tar.gz
  Installing collected packages: setuptools, wheel, Cython, cymem, preshed, murm
urhash, numpy, blis, thinc-gpu-ops, wrapt, plac, tqdm, six, wasabi, srsly, thinc

    Running setup.py install for murmurhash: started
      Running setup.py install for murmurhash: finished with status 'error'
      ERROR: Complete output from command 'c:\users\mahesh\appdata\local\program
s\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'
"'C:\\Users\\Mahesh\\AppData\\Local\\Temp\\pip-install-s2ftb1p1\\murmurhash\\set
up.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().rep
lace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'e
xec'"'"'))' install --record 'C:\Users\Mahesh\AppData\Local\Temp\pip-record-m2oy
x5vr\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\
Mahesh\AppData\Local\Temp\pip-build-env-cmkc4tc7\overlay' --compile:
      ERROR: running install
      running build
      running build_py
      creating build
      creating build\lib.win32-3.7
      creating build\lib.win32-3.7\murmurhash
      copying murmurhash\about.py -> build\lib.win32-3.7\murmurhash
      copying murmurhash\__init__.py -> build\lib.win32-3.7\murmurhash
      creating build\lib.win32-3.7\murmurhash\tests
      copying murmurhash\tests\test_against_mmh3.py -> build\lib.win32-3.7\murmu
rhash\tests
      copying murmurhash\tests\test_import.py -> build\lib.win32-3.7\murmurhash\
tests
      copying murmurhash\tests\__init__.py -> build\lib.win32-3.7\murmurhash\tes
ts
      copying murmurhash\mrmr.pyx -> build\lib.win32-3.7\murmurhash
      copying murmurhash\mrmr.pxd -> build\lib.win32-3.7\murmurhash
      copying murmurhash\__init__.pxd -> build\lib.win32-3.7\murmurhash
      creating build\lib.win32-3.7\murmurhash\include
      creating build\lib.win32-3.7\murmurhash\include\murmurhash
      copying murmurhash\include\murmurhash\MurmurHash2.h -> build\lib.win32-3.7
\murmurhash\include\murmurhash
      copying murmurhash\include\murmurhash\MurmurHash3.h -> build\lib.win32-3.7
\murmurhash\include\murmurhash
      running build_ext
      building 'murmurhash.mrmr' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visua
l C++ Build Tools": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command "'c:\users\mahesh\appdata\local\programs\python\python37-32\pyt
hon.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Mahesh\\App
Data\\Local\\Temp\\pip-install-s2ftb1p1\\murmurhash\\setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'
"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --re
cord 'C:\Users\Mahesh\AppData\Local\Temp\pip-record-m2oyx5vr\install-record.txt'
 --single-version-externally-managed --prefix 'C:\Users\Mahesh\AppData\Local\Tem
p\pip-build-env-cmkc4tc7\overlay' --compile" failed with error code 1 in C:\User
s\Mahesh\AppData\Local\Temp\pip-install-s2ftb1p1\murmurhash\
  ----------------------------------------
ERROR: Command "'c:\users\mahesh\appdata\local\programs\python\python37-32\pytho
n.exe' 'c:\users\mahesh\appdata\local\programs\python\python37-32\lib\site-packa
ges\pip' install --ignore-installed --no-user --prefix 'C:\Users\Mahesh\AppData\
Local\Temp\pip-build-env-cmkc4tc7\overlay' --no-warn-script-location --no-binary
 :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.3
2.0.<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0
.28.0,<1.1.0' thinc==7.0.0.dev6" failed with error code 1 in None

**Comment by maheshbonagiri** [comment]
please help me to solve this issue  
installing build dependency-----error

**Comment by maheshbonagiri** [comment]
Installing build dependencies ... error
  ERROR: Complete output from command 'c:\users\mahesh\appdata\local\programs\py
thon\python37-32\python.exe' 'c:\users\mahesh\appdata\local\programs\python\pyth
on37-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:
\Users\Mahesh\AppData\Local\Temp\pip-build-env-cmkc4tc7\overlay' --no-warn-scrip
t-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --
 setuptools 'wheel>0.32.0.<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,
<2.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.0.0.dev6:
  ERROR: Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0
380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.w
hl
  Collecting wheel>0.32.0.<0.33.0
    Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f
227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
  Collecting Cython
    Using cached https://files.pythonhosted.org/packages/66/2e/8c294e995c1988f28
007b3f2c0be567e5935af19626b45b6567b19833d66/Cython-0.29.10-cp37-cp37m-win32.whl
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://files.pythonhosted.org/packages/eb/cb/4ff546a491f764f67
284572d25c57927e3f17103adf979bc99d90128f3eb/cymem-2.0.2-cp37-cp37m-win32.whl
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://files.pythonhosted.org/packages/00/52/ef641ebb40e287b95
e9742e7f3120dca0350d92b3d0ef050e5133acf8931/preshed-2.0.1-cp37-cp37m-win32.whl
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://files.pythonhosted.org/packages/22/e9/411be1845f1ac07ae
3bc40a4b19ba401819baed4fa63b4f5ef28b2300eb4/murmurhash-1.0.2.tar.gz
  Collecting thinc==7.0.0.dev6
    Using cached https://files.pythonhosted.org/packages/f2/bf/3685c4718b547583b
fe3a3d54db8f0f992e30b49db1ecbce8e5d8a4c7604/thinc-7.0.0.dev6.tar.gz
  Collecting blis<0.3.0,>=0.2.1 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/59/9e/84a83616cbe5daa94
909da38b780e93bf566dc2113c3dc35d7b4cad52f63/blis-0.2.4.tar.gz
  Collecting thinc_gpu_ops<0.1.0,>=0.0.1 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/a4/ad/11ab80a24bcedd7dd
0cfabaedba2ceaeca11f1aaeeff432a3d2e63ca7d02/thinc_gpu_ops-0.0.4.tar.gz
  Collecting numpy>=1.7.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/07/46/656c25b39fc152ea5
25eef14b641993624a6325a8ae815b200de57cff0bc/numpy-1.16.4-cp37-cp37m-win32.whl
  Collecting wrapt<1.11.0,>=1.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/a0/47/66897906448185fcb
77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
  Collecting plac<1.0.0,>=0.9.6 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2a
a1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
  Collecting tqdm<5.0.0,>=4.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/45/af/685bf3ce889ea191f
3b916557f5677cc95a5e87b2fa120d74b5dd6d049d0/tqdm-4.32.1-py2.py3-none-any.whl
  Collecting six<2.0.0,>=1.10.0 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fec
fe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Collecting wasabi<1.1.0,>=0.0.9 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/f4/c1/d76ccdd12c716be79
162d934fe7de4ac8a318b9302864716dde940641a79/wasabi-0.2.2-py3-none-any.whl
  Collecting srsly<1.1.0,>=0.0.5 (from thinc==7.0.0.dev6)
    Using cached https://files.pythonhosted.org/packages/59/1b/542f85474db8be31b
dd6350f2d33ac8db110a98b58b30f42e2dbc446174b/srsly-0.0.6.tar.gz
  Installing collected packages: setuptools, wheel, Cython, cymem, preshed, murm
urhash, numpy, blis, thinc-gpu-ops, wrapt, plac, tqdm, six, wasabi, srsly, thinc

    Running setup.py install for murmurhash: started
      Running setup.py install for murmurhash: finished with status 'error'
      ERROR: Complete output from command 'c:\users\mahesh\appdata\local\program
s\python\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'
"'C:\\Users\\Mahesh\\AppData\\Local\\Temp\\pip-install-s2ftb1p1\\murmurhash\\set
up.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().rep
lace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'e
xec'"'"'))' install --record 'C:\Users\Mahesh\AppData\Local\Temp\pip-record-m2oy
x5vr\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\
Mahesh\AppData\Local\Temp\pip-build-env-cmkc4tc7\overlay' --compile:
      ERROR: running install
      running build
      running build_py
      creating build
      creating build\lib.win32-3.7
      creating build\lib.win32-3.7\murmurhash
      copying murmurhash\about.py -> build\lib.win32-3.7\murmurhash
      copying murmurhash\__init__.py -> build\lib.win32-3.7\murmurhash
      creating build\lib.win32-3.7\murmurhash\tests
      copying murmurhash\tests\test_against_mmh3.py -> build\lib.win32-3.7\murmu
rhash\tests
      copying murmurhash\tests\test_import.py -> build\lib.win32-3.7\murmurhash\
tests
      copying murmurhash\tests\__init__.py -> build\lib.win32-3.7\murmurhash\tes
ts
      copying murmurhash\mrmr.pyx -> build\lib.win32-3.7\murmurhash
      copying murmurhash\mrmr.pxd -> build\lib.win32-3.7\murmurhash
      copying murmurhash\__init__.pxd -> build\lib.win32-3.7\murmurhash
      creating build\lib.win32-3.7\murmurhash\include
      creating build\lib.win32-3.7\murmurhash\include\murmurhash
      copying murmurhash\include\murmurhash\MurmurHash2.h -> build\lib.win32-3.7
\murmurhash\include\murmurhash
      copying murmurhash\include\murmurhash\MurmurHash3.h -> build\lib.win32-3.7
\murmurhash\include\murmurhash
      running build_ext
      building 'murmurhash.mrmr' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visua
l C++ Build Tools": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command "'c:\users\mahesh\appdata\local\programs\python\python37-32\pyt
hon.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Mahesh\\App
Data\\Local\\Temp\\pip-install-s2ftb1p1\\murmurhash\\setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'
"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --re
cord 'C:\Users\Mahesh\AppData\Local\Temp\pip-record-m2oyx5vr\install-record.txt'
 --single-version-externally-managed --prefix 'C:\Users\Mahesh\AppData\Local\Tem
p\pip-build-env-cmkc4tc7\overlay' --compile" failed with error code 1 in C:\User
s\Mahesh\AppData\Local\Temp\pip-install-s2ftb1p1\murmurhash\
  ----------------------------------------
ERROR: Command "'c:\users\mahesh\appdata\local\programs\python\python37-32\pytho
n.exe' 'c:\users\mahesh\appdata\local\programs\python\python37-32\lib\site-packa
ges\pip' install --ignore-installed --no-user --prefix 'C:\Users\Mahesh\AppData\
Local\Temp\pip-build-env-cmkc4tc7\overlay' --no-warn-script-location --no-binary
 :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.3
2.0.<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0
.28.0,<1.1.0' thinc==7.0.0.dev6" failed with error code 1 in None

**Comment by mistaah** [comment]
Install 64bit python
