### ISSUE TITLE
Chatbot object has no attribute get response error

### ISSUE THREAD

**Issue by Manav1918** [gunthercox/ChatterBot#1755]
Chatbot object has no attribute get response error is occurring.
I have python 3.7 64bit 
Win 64bit
Chatterbot 1.0.5

**Comment by gunthercox** [comment]
Hi @Manav1918, I'm very confident at the `ChatBot` object does have a `get_response` attribute.

See here for details:
https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/chatterbot.py

One possible reason that you might be seeing this message is if you created your own class called `ChatBot` that is overriding the existing one.
