### ISSUE TITLE
unable to install pyalsaaudio in windows 10,python 3.7

### ISSUE THREAD

**Issue by kunalsamanta** [gunthercox/ChatterBot#1759]
![Screenshot (28)](https://user-images.githubusercontent.com/20750096/59700200-7f09ee00-9210-11e9-91ad-9bb818d27c6c.png)

**Comment by Orfeous** [comment]
You should reach out to the developers of pyalsaaudio instead.

Also if this issue is part of your chatbot project then you will face other issues as well very soon because you use 32 bit python which is not supported by ChatterBot.

**Comment by gunthercox** [comment]
I think you might mean "pulseaudo", which is a Linux only application to the best of my knowledge.

**Comment by brightening-eyes** [comment]
alsa is for linux only, It can't be installed on windows, so as it's python binding (if i'm not mistaken). if your chatbot uses audio, I recommend you to use pyAudio instead.
