### ISSUE TITLE
hello team help me i was trying all of possiblities like update python and remove another python version i have still updated version 3.7.3

### ISSUE THREAD

**Issue by Arsalanz007** [gunthercox/ChatterBot#1763]
Traceback (most recent call last):   File "bot.py", line 1, in <module>     from chatterbot import ChatBot   File "C:\Users\M Arsalan\chatterbot.py", line 2, in <module>     from chatterbot.storage import StorageAdapter ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package
.
.
.

code

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

bot:ChatBot('Bot')
bot.set_trainer(ListTrainer)

for files in os.listdir('C:/Users/M Arsalan\chatterbot-corpus-master/chatterbot_corpus/data/english/'):
 data = open('C:/Users/M Arsalan\chatterbot-corpus-master/chatterbot_corpus/data/english/' + files  , 'r' ).readlines()
bot.train(data)

while true:
    message = input('you:')
    if message.strip() != 'Bye':
           reply = bot.get_response(message)
           print('ChatBot :', reply)
    if message.strip() == 'Bye':
           print('ChatBot:Bye')
           break

**Comment by Orfeous** [comment]
Hello, 
Rename your file to something else.

if you create a file named chatterbot, that will overlap the whole chatterbot library.

name it like testbot.py
