### ISSUE TITLE
Documentation link  'http://chatterbot.readthedocs.io/' dead

### ISSUE THREAD

**Issue by hemangsk** [gunthercox/ChatterBot#179]
Hello @gunthercox , chatterBot rocks. 
That readthedocs.io link can be replaced by https://github.com/gunthercox/ChatterBot/wiki/, whatsay?

**Comment by gunthercox** [comment]
The read the docs link appears to be working. The wiki page is currently in the process of being phased out as all of the updated documentation is being written for read the docs.

**Comment by gunthercox** [comment]
Can you confirm that the link is still broken for you? Or was this possibly a network hickup?

**Comment by hemangsk** [comment]
That was a network issue. I tried opening in different browsers earlier and it didn't load, but now its loading fine.
