### ISSUE TITLE
docs are misguiding

### ISSUE THREAD

**Issue by franciscovargas** [gunthercox/ChatterBot#180]
the docs are wrong since they are not pointing out that you need to use the set trainer method before training. The class passed to this is not specified anywhere.

**Comment by gunthercox** [comment]
Hi, could you possibly link to the page where this is unclear? I am currently looking at the [docs](http://chatterbot.readthedocs.io/en/latest/training.html) and all the examples appear to have this included.

![image](https://cloud.githubusercontent.com/assets/2030578/15558512/89c6d928-22a8-11e6-8337-b6d8973b66b8.png)

![image](https://cloud.githubusercontent.com/assets/2030578/15558528/97f6d660-22a8-11e6-8943-58751599e6cd.png)

***

I will attempt to go through and make things a bit more clear. Please let me know if there is anything else I can clarify.

**Comment by gunthercox** [comment]
I have updated a few outdated code examples in the readme and wiki pages. I believe everything should be up to date now. Feel free to reopen this ticket if there are any other issues.
