### ISSUE TITLE
AttributeError: 'SQLStorageAdapter' object has no attribute 'create_session'

### ISSUE THREAD

**Issue by fperezm1** [gunthercox/ChatterBot#1802]
CONVERSATION_ID = chatbot.storage.create_session()

AttributeError: 'SQLStorageAdapter' object has no attribute 'create_session'

What should i change here to create a session...? Please help me
Version 1.0.5

I read this issue but does not help me,https://github.com/gunthercox/ChatterBot/issues/920

**Comment by vkosuri** [comment]
I think you need to upgrade to latest chatterbot, the create session was removed in latest versions, please try to upgrade ``pip3 install --upgrade chatterbot``
