### ISSUE TITLE
how to train a bot

### ISSUE THREAD

**Issue by HariBollu** [gunthercox/ChatterBot#1805]

**Comment by vkosuri** [comment]
This quick start guide will hlep you https://chatterbot.readthedocs.io/en/stable/quickstart.html

**Comment by aguilard07** [comment]
Hello, I would like to know if there is way to indicate to the bot if one of his answers is wrong.
For example: if I say to him 'Hello, my name is Daniel'
and he answers me : 'The weather is great'
How do I tell him that it is a bad response?

**Comment by vkosuri** [comment]
It all depends on confidence value and [logic adapter](https://chatterbot.readthedocs.io/en/stable/logic/index.html) you have chosen

You can put a benchmark for your corpus if confidence value below x (assume 0.70) then it would be a bad answer.
