### ISSUE TITLE
DATABASE STRUCTURE

### ISSUE THREAD

**Issue by bobyzoo** [gunthercox/ChatterBot#1809]
I would like to understand how the structure of the database generated in the code works.
I took a look and realized that there are three tables: 'stantment', 'tag' and 'tag_association'
I want to understand what the tag and tag_association table is for, and I would also like to understand the columns in the stantment table, as there is the "search_text" column that breaks my question and places initials in front:
text -> CLICQ is a complete platform for product and process quality management of your business.
column -> NNP: click NNP: a JJ: platform NN: complete NN: to DT: management NN: prosecutor NN: quality NN: from IN: FW products: VBP processes: your VB: business
What would each initials?

**Comment by vkosuri** [comment]
This might give an idea on database https://chatterbot.readthedocs.io/en/stable/conversations.html#statement-response-relationship

the search_text column is a string of text containing part-of-speech, lemma pairs.
