### ISSUE TITLE
Fail to install ChatterBot with pip3 on linux

### ISSUE THREAD

**Issue by Glane13** [gunthercox/ChatterBot#1811]
Hi,

The install process for ChatterBot is failing for me. I'm running Ubuntu 18 on an AWS free tier server. I've been using the commands:
pip3 install chatterbot and 
pip3 install --upgrade chatterbot

The install process ends abruptly with a message saying "Killed". I'm pretty sure this is when the SpaCy package is being installed. I had the same error when I tried to install SpaCy separately. 

I'm aware that SpaCy no longer supports 32 bit but, as far as I can tell, I'm running 64 bit python. Definitely, my server is 64 bit.

I've tried running as sudo but this failed at the same point. Please can you offer any advice. 

Thanks,
Graham

**pip3 install --upgrade chatterbot**

Collecting chatterbot
  Using cached https://files.pythonhosted.org/packages/6c/0e/dac0d82f34f86bf509cf5ef3e2dfc5aa7d444bd843a2330ceb7d854f84f2/ChatterBot-1.0.5-py2.py3-none-any.whl
Requirement already up-to-date: nltk<4.0,>=3.2 in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: pyyaml<5.2,>=5.1 in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: python-dateutil<2.8,>=2.7 in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: sqlalchemy<1.3,>=1.2 in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: pytz in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: pymongo<4.0,>=3.3 in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: mathparse<0.2,>=0.1 in ./lib/python3.6/site-packages (from chatterbot)
Collecting spacy<2.2,>=2.1 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/95/9c/afd55bb35cc03e4b3dadc41dd48bc26e0678b08d59f32411735c35bda550/spacy-2.1.8-cp36-cp36m-manylinux1_x86_64.whl
Requirement already up-to-date: pint>=0.8.1 in ./lib/python3.6/site-packages (from chatterbot)
Requirement already up-to-date: six in ./lib/python3.6/site-packages (from nltk<4.0,>=3.2->chatterbot)
Requirement already up-to-date: murmurhash<1.1.0,>=0.28.0 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: thinc<7.1.0,>=7.0.8 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: blis<0.3.0,>=0.2.2 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: plac<1.0.0,>=0.9.6 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: requests<3.0.0,>=2.13.0 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: wasabi<1.1.0,>=0.2.0 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: numpy>=1.15.0 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: cymem<2.1.0,>=2.0.2 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: preshed<2.1.0,>=2.0.1 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: srsly<1.1.0,>=0.0.6 in ./lib/python3.6/site-packages (from spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: tqdm<5.0.0,>=4.10.0 in ./lib/python3.6/site-packages (from thinc<7.1.0,>=7.0.8->spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: certifi>=2017.4.17 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: idna<2.9,>=2.5 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.2,>=2.1->chatterbot)
Requirement already up-to-date: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy<2.2,>=2.1->chatterbot)
Installing collected packages: spacy, chatterbot

The terminal hangs and then says Killed

**pip3 install spacy**

Collecting spacy
  Using cached https://files.pythonhosted.org/packages/95/9c/afd55bb35cc03e4b3dadc41dd48bc26e0678b08d59f32411735c35bda550/spacy-2.1.8-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: srsly<1.1.0,>=0.0.6 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: wasabi<1.1.0,>=0.2.0 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: numpy>=1.15.0 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: thinc<7.1.0,>=7.0.8 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: blis<0.3.0,>=0.2.2 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: preshed<2.1.0,>=2.0.1 in ./lib/python3.6/site-packages (from spacy)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in ./lib/python3.6/site-packages (from thinc<7.1.0,>=7.0.8->spacy)
Requirement already satisfied: idna<2.9,>=2.5 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy)
Installing collected packages: spacy

The terminal hangs and then says: Killed

**Comment by Glane13** [comment]
Sorry, I missed the -U option

**Comment by vkosuri** [comment]
Glad to hear you resolved it 👍
