### ISSUE TITLE
Set a new folder to store the conversation Database

### ISSUE THREAD

**Issue by rafamedin** [gunthercox/ChatterBot#1824]
Hello!~

Could someone tell me how I choose a new directory to the database conv register? Like a especific folder. 

Thanks

**Comment by sohamnandi007** [comment]
if you want to store all your chats, you ca do it in this way

filename = input ("write your name: ");
while True:
    request =input("you: ") 
    with open(filename, "a") as f:
        f.write (request + '\n');
     
    response = bot.get_response(request)
    print("bot: " + str(response))

    with open(filename, "a") as f:
        f.write (str(response) + '\n');

**Comment by rafamedin** [comment]
thank u!
