### ISSUE TITLE
Default response on logic adapter

### ISSUE THREAD

**Issue by JDZC** [gunthercox/ChatterBot#1825]
hey, i'm just using the doc code for default response:
´def get_default_response(self, input_statement):
 from random import choice

        if self.default_responses:
            response = choice(self.default_responses)
        else:
            try:
                response = self.chatbot.storage.get_random()
            except StorageAdapter.EmptyDatabaseException:
                response = input_statement

        self.chatbot.logger.info(
            'No known response to the input was found. Selecting a random response.'
        )

        return response´

but, could I define one especif response instead of selecting a new one?

**Comment by vkosuri** [comment]
If you are looking specific response please specific response adapter for more information please go through this link https://chatterbot.readthedocs.io/en/stable/logic/index.html#specific-response-adapter
