### ISSUE TITLE
Converting chatterbot used py to exe 

### ISSUE THREAD

**Issue by ProPython007** [gunthercox/ChatterBot#1827]
After converting a simple chatbot program (using chatterbot module) to exe i encountered thousands of module not found runtime error when i run the exe file.... I simply keep adding hidden imports while compiling to exe using pyinstaller but i am tired now as there are tons of hidden modules require i guess...... So is there any easy way to solve the error???

**Comment by vkosuri** [comment]
use docker https://github.com/gunthercox/ChatterBot/pull/617/files

**Comment by gunthercox** [comment]
I'm not aware of a good way to convert a python project with several dependencies into an exe file.
