### ISSUE TITLE
Import and export pre-trained bot data.

### ISSUE THREAD

**Issue by chamecall** [gunthercox/ChatterBot#1833]
Let's say I'd like to train a bot on my custom data.
The train lasted a lot of time and after that I'd like to export my trained data in order to load it 
into a bot in the next time instead of re-training.

How could I approach it?
10x in advance.

**Comment by vkosuri** [comment]
@chamecall you could find ``database.db`` file in your current workspace. with few modification you could reuse that file instead retraining everytime.
