### ISSUE TITLE
ModuleNotFoundError: No module named 'chatterbot'

### ISSUE THREAD

**Issue by keshyagol** [gunthercox/ChatterBot#1840]
I have installed Chatterbot using pip and installation is successful but i am getting following error please help me.  

C:\Users\A R A N N Y A\Desktop\kk>test.py
Traceback (most recent call last):
  File "C:\Users\A R A N N Y A\Desktop\kk\test.py", line 1, in <module>
    import chatterbot
ModuleNotFoundError: No module named 'chatterbot'

**Comment by sohamnandi007** [comment]
Hello @keshyagol, I would suggest reinstall python 3.7.2 also keep in mind to delete the cache file after uninstalling. So,
delete the pip folder from C:\Users\soham\AppData\Local\pip and
delete the old python setup files from C:\Users\soham\AppData\Local\Programs\Python
then reinstall python 3.7.2
then pip install chatterbot
it will work

**Comment by sourav8168** [comment]
This is not a clean setup

**Comment by gunthercox** [comment]
The error you have described can occur of the ChatterBot library is not installed. Please refer to ChatterBot's documentation for installation instructions.
