### ISSUE TITLE
Install Error  

### ISSUE THREAD

**Issue by arielpajares** [gunthercox/ChatterBot#1842]
I have a problem . The problem is this ,when i install the chatterbot the cmd tells me

ERROR: Command errored out with exit status 1: 'C:\Users\Ariel\AppData\Local\Programs\Python\Python38-32\python.exe' 'C:\Users\Ariel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Ariel\AppData\Local\Temp\pip-build-env-3gguqdfl\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output

**Comment by sohamnandi007** [comment]
Hello @arielpajares, I would suggest go for python 3.7.2 also keep in mind to delete the cache file after uninstalling. So,
**delete the pip folder** from **C:\Users\soham\AppData\Local\pip** and
**delete the old python setup files** from **C:\Users\soham\AppData\Local\Programs\Python**
then **reinstall python 3.7.2** 
then **pip install chatterbot**

**Comment by gunthercox** [comment]
I believe this installation issue may have been resolved with #2027. Please let me know or open a new ticket if issues persist.
