### ISSUE TITLE
AttributeError: 'SQLStorageAdapter' object has no attribute 'create_conversation'

### ISSUE THREAD

**Issue by garboh** [gunthercox/ChatterBot#1843]
I'm using the latest chatterbot version: 1.0.5

When I run this
```
chat_session = chatbot.storage.create_conversation()
output = chatbot.get_response(input, conversation_id=chat_session)
```
I recive this error: 

> AttributeError: 'SQLStorageAdapter' object has no attribute 'create_conversation'

what can I do?

**Comment by gunthercox** [comment]
This error is the result of trying to run outdated code with the latest version of ChatterBot. Please take a look at the latest version of the documentation for examples.
