### ISSUE TITLE
The search of BestMatch cannot process Chinese flexibly

### ISSUE THREAD

**Issue by AlucardNosferatu** [gunthercox/ChatterBot#1844]
Maybe this ISSUE has already been reported, but I haven't found one in the ISSUES of this repo.

The 'search_text_contains' in filter() of sql_adapter would split the sentence into words and create search queries for those words:
`if search_text_contains:`
&emsp;`or_query = [`
&emsp;&emsp;`Statement.search_text.contains(word) for word in search_text_contains.split(' ')`
&emsp;`]`
&emsp;`statements = statements.filter(`
&emsp;&emsp;`or_(*or_query)`
&emsp;`)`
Spaces in English could be use to separate every words in a sentence, but Chinese do not use spaces, thus it only matches the whole sentence input as the keyword for search, and results in the mismatching covered by random output (which is less meaningful).

there are words can be separate with Jieba (A Chinese words segmentation LIB) and I try to add Spaces in a Chinese sentences:
`raw_str = "我永远喜欢她。"`
`# there was a sentence as "我一直喜欢她。" in the training list`
`cut_str = jieba.lcut(raw_str)`
`temp_str = ''`
`for each in cut_str:`
&emsp;`temp_str += each`
&emsp;`temp_str += ' '`
`response = bot.get_response(temp_str)`
However, when matching goes on, this would not help though the words in sentences are sucessfully separated and tagged, and the bot still output a random answer.

I check the training process and I found the difference between English corpus and Chinese corpus training, English training will make tags for words in corpus while Chinese are not. I am not sure if this will affect the matching process in database for I am not familiar with the mechanism of: `Statement.search_text.contains(word)` Which seems like some kind of SQL query.

I will appreciate it if someone could join this discussion.

Thank you!

**Comment by AlucardNosferatu** [comment]
This issue happens before the comparison, `self.chatbot.storage.filter(**search_parameters)` give `compare_statements()` 2 identical statement from Users' input

**Comment by fg607** [comment]
@AlucardNosferatu I have the same issue with chinese searching , have you find some solutions. and exactly  this issue happens before comparison,bcuz the comparison i defined dosen't  execute.

**Comment by fg607** [comment]
@AlucardNosferatu I have found the point,input_statement.search_text is not correct,it's just the last word of statement.text.

**Comment by fg607** [comment]
I have solved this issue by [ChatterBot中文适配版](https://github.com/fg607/ChatterBot)

**Comment by AlucardNosferatu** [comment]
> I have solved this issue by [ChatterBot中文适配版](https://github.com/fg607/ChatterBot)

GJ ! That's awesome !
