### ISSUE TITLE
chatterbot issue ModuleNotFoundError: No module named 'chatterbot'

### ISSUE THREAD

**Issue by Carnage-Cloud** [gunthercox/ChatterBot#1848]
Traceback (most recent call last):
  File "centaurbot1.py", line 1, in <module>
    from chatterbot.trainers import ListTrainer
ModuleNotFoundError: No module named 'chatterbot'

**Comment by Carnage-Cloud** [comment]
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
from chatterbot.storage import SQLStorageAdapter

bot = ChatBot('Test')

conv = open('chats.txt', 'r').readlines()

bot.set_trainer(ListTrainer)

bot.train(conv)

while True:
    request = imput('you: ')
    response = bot.get_response(request)
    
    print('Bot; ', response)

**Comment by sohamnandi007** [comment]
Hello @Carnage-Cloud, I would suggest reinstall python 3.7.2  also keep in mind to delete the cache file after uninstalling. So,
**delete the pip folder** from **C:\Users\soham\AppData\Local\pip** and
**delete the old python setup files** from **C:\Users\soham\AppData\Local\Programs\Python**
then **reinstall python 3.7.2** 
**then pip install chatterbot**

**Comment by gunthercox** [comment]
The error you are describing can occur if the ChatterBot library is not installed. Please refer to the ChatterBot documentation for installation instructions.
