### ISSUE TITLE
Good day guys i need help with the chatbot. I am getting and error " File "thel.py", line 8     for files in os.listdir('C:/Users/PC\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english/');  ^ SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by 1virus1** [gunthercox/ChatterBot#1858]
from chatterot import ChatBot
from chatterot.traiers import ListTrainer
import os

bot = ChaBot('Bot')
bot.set_trainer(ListTrainer)

for files in os.listdir('C:/Users/PC\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english/');
	data =open('C:/Users/PC\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english/' + files , 'r').readlines(
		bot.train(data)

while True:
		message = input('You:')
		if message.strip() != 'Bye';
					reply = bot.get_response(message)
					print('ChatBot :',reply)
		if message.strip() == 'Bye'
					print('ChatBot : Bye')
					break

**Comment by sohamnandi007** [comment]
@1virus1   You have an invalid syntax.. slash problems..once try this one

os.listdir('C:\Users\PC\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english\');
data =open('C:\Users\PC\Desktop\chatterbot-corpus-master\chatterbot_corpus\data\english\' + files , 'r').readlines(bot.train(data)
