### ISSUE TITLE
Need multiple chatbot instances which are trained separately.

### ISSUE THREAD

**Issue by Sundarasan** [gunthercox/ChatterBot#186]
I need to create chatbots which are trained separately with different set of conversation.

For example, say I have two chatbot instances **A** and **B**.
- **A** should reply _"18"_ to _"What is your age?"_
- **B** should reply _"35"_ to _"What is your age?"_

**Comment by gunthercox** [comment]
If you specify a different database endpoint for each bot, this should provide the functionality you desire. http://chatterbot.readthedocs.io/en/latest/adapters/storage.html#database
