### ISSUE TITLE
 ChatBot: 'str' object has no attribute 'storage'

### ISSUE THREAD

**Issue by DeekshithSanem** [gunthercox/ChatterBot#1862]
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
List Trainer: [                    ] 0%Traceback (most recent call last):
  File "C:\Users\asus\Desktop\spypy.py", line 9, in <module>
    trainer.train(data)
  File "C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\trainers.py", line 103, in train
    statement_search_text = self.chatbot.storage.tagger.get_bigram_pair_string(text)
AttributeError: 'str' object has no attribute 'storage'

Process returned 1 (0x1)        execution time : 2.625 s

**Comment by gunthercox** [comment]
This error is the result of trying to run outdated code with the latest version of ChatterBot. Please take a look at the latest version of the documentation for examples.
