### ISSUE TITLE
Does this thing even work?

### ISSUE THREAD

**Issue by chebz** [gunthercox/ChatterBot#1863]
I just installed chatterbot and run my script with following settings:

```
        chatbot = ChatBot('Chilibot')
        trainer = ChatterBotCorpusTrainer(self.chatbot)
        trainer.train("chatterbot.corpus.english")
        trainer.train("chatterbot.corpus.english.greetings")
        trainer.train("chatterbot.corpus.english.conversations")
```

whenever I try to get response to almost any question it returns some nonsense answer. The only ones that more or less match are questions like "what are you?" and "what is your favorite color?"

I assume the trained data should contain at least something to respond to basic conversational questions?

update:
I've tried learning responses, with my own clean db, following the provided examples. Even after learning the response, it does not reply correctly. I don't know why. There is no clear explanation how to do it, except a really basic example that simply doesn't work. It spammed the database with hundreds of empty and repeated entries. My "learned" response was simply one of 100s there so it never got picked. I tried playing with different logic adapters for all good that did...nothing. Responses in database themselves have no weights attached to them, so no wonder it would never pick the "learned" one...

At this point I am done trying to work with this API, I wasted too much time on this hobby project. I think you guys need some better getting started guides and possibly rework the user-facing API because I have no idea why is it spamming my database with erroneous answers when I try to tell it, the response is wrong. 

I don't want to run your basic example and see "How are you?" "I am AI" responses either... After importing all the provided training data it should respond with something that makes sense...

**Comment by sohamnandi007** [comment]
@chebz, if you are asking chatterbot module works then  YES, it works. To get it working I would suggest you create your own chat's database and train it. Also to get the desired output you can use:
the best match just increase the threshold

bot = ChatBot(
    'Example Bot', read_only=True,
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': 'I am sorry, but I do not understand.',
            'maximum_similarity_threshold': 0.90
        },
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation',
        }
        ],
    preprocessors=['chatterbot.preprocessors.clean_whitespace']
    )

**Comment by sohamnandi007** [comment]
@chebz for reference, you can check out:
[](https://github.com/sohamnandi007/chatbot)

**Comment by leocornelius** [comment]
Why are you training the chatterbot.corpus.english.greetings after training chatterbot.corpus.english? chatterbot.corpus.english trains every thing. Likely the reason you are getting nonsensical responses is because you have over trained the same response.
