### ISSUE TITLE
default_response

### ISSUE THREAD

**Issue by ex-fendi** [gunthercox/ChatterBot#1866]
hello, I have a problem in providing default responses, although I also use lowconfidence to provide default responses, but it doesn't work at all. Please help me 

this my code :
chatbot = ChatBot(
	'Lia', read_only = True,

	storage_adapter= "chatterbot.storage.MongoDatabaseAdapter",
	preprocessors =["chatterbot.preprocessors.clean_whitespace"],
	logic_adapter =[
        {
			'import_path': 'chatterbot.logic.BestMatch',
			"statement_comparison_function": "chatterbot.comparisons.jaccard_similarity",
			"response_selection_method": "chatterbot.response_selection.get_first_response"
        },
		{
		    'import_path': "chatterbot.logic.LowConfidenceAdapter",
			'default_response': "Maaf saya tidak Mengerti.",
			'maximum_similarity_threshold': 0.90
		}

**Comment by sohamnandi007** [comment]
hello @ex-fendi --
Try this one
bot = ChatBot(
    'Example Bot', read_only=True,
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': 'I am sorry, but I do not understand.',
            'maximum_similarity_threshold': 0.90
        },
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation',
        }],
    preprocessors=['chatterbot.preprocessors.clean_whitespace']
        )

**Comment by ex-fendi** [comment]
Oke, thank you
