### ISSUE TITLE
'ChatBot' object has no attribute 'response_selection'

### ISSUE THREAD

**Issue by epuyana** [gunthercox/ChatterBot#1869]
Hello! for a Python class in school I decided to code a Chatbot that helps students answer anything from day to day schedule questions to developing meaningful conversations. Right now, I'm trying to get the bot to use the get_first_response function, but whenever I try to run the code terminal returns with 'ChatBot' object has no attribute 'response_selection'. 

I'm currently using python3 3.7.4.

Thanks in advance

from flask import Flask, render_template, request
from datetime import datetime
import chatterbot
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import ListTrainer

app = Flask(__name__)

mybot = ChatBot("Chatterbot", storage_adapter="chatterbot.storage.SQLStorageAdapter")
mybot_trainer = ChatterBotCorpusTrainer(blairbot)
mybot_trainer.train("chatterbot.corpus.english")

file = open("convo.txt")

# conversation = []
#
# for line in file:
#     conversation.append(line)
#
# trainer = ListTrainer(mybot)
# trainer.train(conversation)

input_statement = ("What is my next class?")

response_list = [
    "Your next class is C block",
]

mybot.response_selection.get_first_response(input_statement, response_list, storage=None)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(blairbot.get_response(userText))

@app.route("/name")
def hello():
    if 'name' in request.args:
        name = request.args['name']
    else:
        name = 'Person'
    return """
        <html><body>
             <h1>Hello, {0}!</h1>
             The time is {1}.
         </body></html>
          """.format(
             name, str(datetime.now()))

if __name__ == "__main__":
    app.run(debug = False, port=2420)

**Comment by sohamnandi007** [comment]
Hello @epuyana 
Try removing 
response_selection.
 `mybot.get_first_response(input_statement, response_list, storage=None)`

**Comment by epuyana** [comment]
@sohamnandi007 

That doesn't seem to work. When run it says: 'ChatBot' object has no attribute 'get_first_response'

**Comment by sohamnandi007** [comment]
Hello @epuyana
there is no response_selection, it is get_response
`mybot.get_response(input_statement, response_list, storage=None)`

**Comment by sohamnandi007** [comment]
if you need an example regarding chatterBot :
[](https://github.com/sohamnandi007/chatbot)

**Comment by gunthercox** [comment]
This error is the result of trying to run outdated code with the latest version of ChatterBot. Please take a look at the latest version of the documentation for examples.
