### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by futetest** [gunthercox/ChatterBot#187]
Hi I'm trying to understand the learning process of the chatter bot. I see database.json being created but i do not understand what is going on in there. The relationship of the statements and the responses. Please help me clarify that.

**Comment by dcsan** [comment]
@futetest I'm also going through this! Where is that file being created for you? I don't see it.

You'll have to look in the logic inside the chatter bot. I have things setup using a virtualenv so the code is in

    YOURENV/lib/python2.7/site-packages/chatterBot

then you can see the input/output adapters making the logical decisions.

**Comment by futetest** [comment]
i get the logical decisions and all but i do not get the structure of the database.json file from which the bot is reading and mapping the inputs. Can someone explain the structure of the database.json file.

**Comment by gunthercox** [comment]
Hi @futetest 

The primary feature of the conversation representations in ChatterBot's databases is the ability for the known responses to a given statement to be tracked.

Each statement object in the database represents something that someone has said to the chat bot. On top of that, each statement in the database also holds a reference to each other statement that it has been issued in response to.

So for example, the statement "Thank you very much!" could be in response to any number of the following statements: "Have a good day madam.", "Here is the cake you ordered.", and "Wow, I like your motorcycle!".

Does this explanation help? If not please let me know so I can clarify.
