### ISSUE TITLE
AttributeError: 'ChatBot' object has no attribute 'train'

### ISSUE THREAD

**Issue by chipperr** [gunthercox/ChatterBot#1871]
having problem getting past this error:
AttributeError: 'ChatBot' object has no attribute 'train'

using chatterbot 0.8.7 and Python 3.7

code:
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os

bott = ChatBot('Bot')
trainer = ChatterBotCorpusTrainer(bott)
trainer.train("chatterbot.corpus.english")
for files in os.listdir('C:/Users/name/chatterbot_corpus/data/english/'):
        data = open('C:/Users/name/chatterbot_corpus/data/english/'+files, 'r').readlines()
        bott.train(data)
while True:
    message = input('Youhoo:  ')
    if message.strip() !='Bye':
        reply = bott.get_response(message)
        print('ChatBot: ' + reply)
        
    if message.strip() =='Bye':
        print('ChatBot: Bye Bye') 
        break

**Comment by gunthercox** [comment]
This error is the result of trying to run outdated code with a newer version of the ChatterBot libary. Please take a look at the latest version of the documentation for examples.
