### ISSUE TITLE
Several errors in Chatterbot

### ISSUE THREAD

**Issue by oaktons** [gunthercox/ChatterBot#1875]
Hello,

I am having horrendous problems getting chatterbot to work:
1. It will not install in command prompt despite installing pyYaml etc 
2. After installing via ubuntu it still causes errors:
   chatbot = ChatBot("botname") produces an error 'name not defined' when it is clearly defined (note I have also tried chat_bot)
   from chatterbot.trainers import ListTrainer produces error 'corpus' not found.
Even after installing chatterbot-corpus as well as providing the filepath to the master corpus it still produces the same error.

Please help as I am wanting to use Chatterbot for a university project.

**Comment by oaktons** [comment]
These are the errors in more detail running jupyter in Ubuntu:
Collecting PyYAML
Installing collected packages: PyYAML
Successfully installed PyYAML-5.1.2
pip install chatterbot-corpus
equirement already satisfied: chatterbot-corpus in ./anaconda3/lib/python3.7/site-packages (1.2.0)
Collecting PyYAML<4.0,>=3.12 (from chatterbot-corpus)
chatterbot 1.0.5 has requirement pyyaml<5.2,>=5.1, but you'll have pyyaml 3.13 which is incompatible. (AS ABOVE I NOW HAVE 5.1.2)
Installing collected packages: PyYAML
  Found existing installation: PyYAML 5.1
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Chatterbot:
from chatterbot import ChatBot
chatbot.set_trainer(ListTrainer)
chatbot.train(Chatbot)
chatbot.set_trainer(ListTrainer)
chatbot.train(Chatbot)

#creating a new chatbot

chatbot = ChatBot("bot")
                       
trainer = ChatterBotCorpusTrainer (chatbot)
trainer = ListTrainer (chatbot)

trainer.train (
    "chatterbot.corpus.english"
)
trainer.train (
    "chatterbot.corpus.french"
)
trainer.train()

NameError                                 Traceback (most recent call last)
<ipython-input-7-b0f94dd2ab82> in <module>
----> 1 chatbot.set_trainer(ListTrainer)
      2 chatbot.train(Chatbot)
      3 
      4 #creating a new chatbot
      5 

NameError: name 'chatbot' is not defined

**Comment by gunthercox** [comment]
Your code looks valid to me. Writing:

```
chatbot = ChatBot("bot")
```

should not result in an error such as

```
NameError: name 'chatbot' is not defined
```

in the same file. I'm not certain what would cause this.
