### ISSUE TITLE
Freezing chatbot statements after training

### ISSUE THREAD

**Issue by Mew-www** [gunthercox/ChatterBot#1877]
When the chatbot is using SQL backend _(Django extension in this case)_, calling `bot.get_response("a-new-statement")` seems to add `"a-new-statement"` to database of possible responses. This would allow users to add responses I may not want. Is it possible to freeze the learning, or is there an alternative method to get_response without learning the passed input?

(See attached image where only words "one" & "two" are taught, but finally bot learns from input to answer "four" with "three" at the end.)
![image](https://user-images.githubusercontent.com/23376146/69536606-ee85c580-0f86-11ea-945e-2f034186b2aa.png)

**Comment by Arthur-Chan** [comment]
Try This  [Read Only Mode](https://chatterbot.readthedocs.io/en/stable/examples.html#read-only-mode)

**Comment by Mew-www** [comment]
Thank you, that should fix my issue!
