### ISSUE TITLE
Edits on documentation made for university student project

### ISSUE THREAD

**Issue by compSciKai** [gunthercox/ChatterBot#1878]
For a university school project I will be making some edits to your documentation which will aim to make writing more technical

Please add edits if you would like :)

**Comment by vkosuri** [comment]
Sure @compSciKai i am curiosly waiting for your edits

**Comment by vkosuri** [comment]
If possible add your edits on statement similarity and string comparisons techniques

**Comment by compSciKai** [comment]
I apologize, I only found this after making edits. They were only minor edits. But please let me know if you would like anything changed
