### ISSUE TITLE
Where is the data saved?

### ISSUE THREAD

**Issue by adhoc92** [gunthercox/ChatterBot#188]
I want to delete all of the data I've inputted into my bot, but I can't find where it's stored on my computer.

**Comment by futetest** [comment]
Hi, the data is saved into a database file. This file is in the same place where you executing your python bot from. 

See the below code:
bot = ChatBot("Terminal",
    storage_adapter="chatterbot.adapters.storage.JsonDatabaseAdapter",
    logic_adapters=[
        "chatterbot.adapters.logic.MathematicalEvaluation",
        "chatterbot.adapters.logic.TimeLogicAdapter",
        "chatterbot.adapters.logic.ClosestMatchAdapter"
    ],
    input_adapter="chatterbot.adapters.input.TerminalAdapter",
    output_adapter="chatterbot.adapters.output.TerminalAdapter",
    database="../database.json"
)

The bot you've created is using database.json file to save all the data. Path in the above code suggests the file is being created in the same directory where the bot is.

I hope it helps.

**Comment by adhoc92** [comment]
Ohhh, thanks!

**Comment by mady143** [comment]
Hi,

How can save the chat history and save it on one file either json or txt or yml file and when we start a new conversation how can we call that file into my code could you please help me 

Train.py

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

def setup():
    chatbot = ChatBot('Bot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    trainer='chatterbot.trainers.ListTrainer')
    for file in os.listdir('data/'):
        convData = open(r'data/' + file,encoding='latin-1').readlines()
        chatbot.set_trainer(ListTrainer)
        chatbot.train(convData)
    print("Training completed")
    

setup()
 **NOTE**
the data folder represents the sample conversations 


chatbot.py

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import speech_recognition as sr
from pyaudio import PyAudio

def get_response(usrText):
    bot = ChatBot('Bot',
                  storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.70,
            'default_response': 'I am sorry, but I do not understand.'
        }
    ],
    trainer='chatterbot.trainers.ListTrainer')
    bot.set_trainer(ListTrainer)
    r = sr.Recognizer()
    while True:
        if usrText.strip()!= 'Bye':
            result = bot.get_response(usrText)                        
            reply = str(result)
            return(reply)
        if usrText.strip() == 'bye' or usrText.strip() == 'bye':
            return('Bye Take Care')
            break
        
and this is the response we are getting from the bot

Thanks in advance

Happy Codding........
