### ISSUE TITLE
ModuleNotFoundError: No module named 'en'

### ISSUE THREAD

**Issue by YOKI2048** [gunthercox/ChatterBot#1888]
I'm using chatterbot to build a ChatBot, but I met this error when I run my code and I don't know how to deal with it, please help me . my code is:
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import en
# Create a new chat bot named Charlie
chatbot = ChatBot('Charlie')

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

# Get a response to the input text 'I would like to book a flight.'
response = chatbot.get_response('I would like to book a flight.')

print(response)

I had download en but it still does not work, I  need help

**Comment by ViniciusFigueiredo** [comment]
Is this 'import en' necessary? I checked and it worked normal without it, I just needed to put it inside a While and add a input for tests, compare with u code:

```
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

# import en

chatbot = ChatBot('Charlie', read_only=True)

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

while True:
    response = str(input("U: "))
    if response == 'stop':
        break
    response = chatbot.get_response(response)
    print('chatbot: ' + str(response))

```

**Comment by YOKI2048** [comment]
Thanks for your help! I 'import en' just because if I don't import it, It will return me with the error:ModelNotFoundError. It can't find the model "en", so I installed the model and import it, but it doesn't work! I use the jupyternotebook to run the code, I also have change the environment with python 3.6 and I am sure that I have installed the model "en" in it.

Finally, I used pycharm and built a new one and it run well.

**Comment by Kevin-Rose** [comment]
c:\users\rose\miniconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'en'

would you help me resolve this error

**Comment by gunthercox** [comment]
From spacy's dodumentation:

```
# set up shortcut link to load installed package as "en_default"
python -m spacy link en_core_web_md en_default

# set up shortcut link to load local model as "my_amazing_model"
python -m spacy link /Users/you/model my_amazing_model
```

~ https://spacy.io/usage/models

So you should be able to fix this error by running the following:
```
python -m spacy link en_core_web_sm en
```

**Comment by deepu14d** [comment]
Hi all.
I am also facing the same issue - "ModuleNotFoundError: No module named 'en' "
I have 'en' module already installed but still I am getting this error.
Please help.

**Comment by intercontoni** [comment]
deepu14d put in ssh this code
````
python -m spacy link en_core_web_sm en
````

Look gunthercox....

**Comment by intercontoni** [comment]
deepu14d put in ssh this code

````
python -m spacy link en_core_web_sm en

````

Look gunthercox....
