### ISSUE TITLE
improved time adapter example

### ISSUE THREAD

**Issue by digitaldesaster** [gunthercox/ChatterBot#189]
Hi, i have played around with chatterbot the last two days and it is a really great starting point into the world of chatbots. So thanks for your awesome work! 

i tried to optimize the time adapter example. 

1.) for my usecase i need to have german "umlaute" like 'äöü' etc. I changed the coding to utf-8 but it did not helped. so i made this "jsonfy" function to get rid of the "umlaute".

2.) i recognized that only a single "what" results in outputting the current time. i removed the classifier and added the closest_match function. 

3.) furthermore i liked to give the confidence some more weight depending if some keywords in the input_statement.

here it is.

best regards
Alex

http://pastebin.com/JSsdyAdT

**Comment by gunthercox** [comment]
Hi @digitaldesaster, this looks like a good improvement. Would you be interested in creating a pull request?
