### ISSUE TITLE
Can the ChatterBot forget the answer to a single learned question?

### ISSUE THREAD

**Issue by AdorableParker** [gunthercox/ChatterBot#1890]
I trained a ChatterBot, and after using it for a while, I trained some more data, but due to errors, the data was mixed with something I didn't need. Is it possible for ChatterBot to directly forget this unwanted data? Or you can only clear all information and retrain？

**Comment by Lord-DMion** [comment]
Deleting and retraining would be a better option. It is a lot faster than changing the data.
