### ISSUE TITLE
AttributeError: module 'chatterbot.logic' has no attribute 'LowConfidenceAdapter'

### ISSUE THREAD

**Issue by DanielRojas2008** [gunthercox/ChatterBot#1891]
When I run my code, I1, an error pops up, I2. I am using Visual Studio, Python 3.7.6, using pipenv to install packages and am on a Mac OS X Catalina. I am taking Udemy Course Create a Python Powered Chatbot in Under 60 Minutes.

(I1)
`from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.response_selection import get_random_response
import random
#from chatterbot.trainers import ChatterBotCorpusTrainer

import logging
logging.basicConfig(level=logging.INFO)

app = Flask(__name__)

chatbotName = 'Demo ChatBot'
botAvatar = '/static/bot.png'

bot = ChatBot(
    "ChatBot",
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': 'IDKnull'
        }
    ],
    response_selection_method=get_random_response, #Comment this out if you want best response
    input_adapter="chatterbot.input.VariableInputTypeAdapter",
    output_adapter="chatterbot.output.OutputAdapter",
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    database="demoData.sqlite3"
)

bot.read_only=True #Comment this out if you want the bot to learn based on experience
print("Bot Learn Read Only:" + str(bot.read_only))

#You can comment these out for production later since you won't be training everytime:
#bot.set_trainer(ChatterBotCorpusTrainer)
#bot.train("data/trainingdata.yml")

@app.route("/")
def home():
    return render_template("index.html", botName = chatbotName, botAvatar = botAvatar)

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    botReply = str(bot.get_response(userText))
    noResponse = ["I don't know.", "I'm not sure about that.", "Is there a different way you can ask that?","I don't have a response for that.","I will have to give that some thought.","I don't really know what you are asking.", userText + '. Who knows what your talking about.']
    if botReply == "IDKnull":
        botReply = random.choice(noResponse)
    return botReply

if __name__ == "__main__":
    #app.run()
    app.run(host='0.0.0.0', port=80)
`

(I2)
![Screen Shot 2019-12-30 at 10 11 25 AM](https://user-images.githubusercontent.com/56618141/71594494-0522bd80-2aed-11ea-9007-e93048dd0212.png)

Please Help, I've had errors with python chatbots, since I've started.

**Comment by sohamnandi007** [comment]
https://github.com/gunthercox/ChatterBot/issues/1644#issuecomment-468087642

**Comment by gunthercox** [comment]
This error is the result of trying to run outdated code with the latest version of ChatterBot. Please take a look at the latest version of the documentation for examples.
