### ISSUE TITLE
ModuleNotFoundError: No module named 'chatterbot_corpus'

### ISSUE THREAD

**Issue by SaloniSS** [gunthercox/ChatterBot#1894]
Already tried `pip install --upgrade chatterbot_corpus` and `pip install --upgrade chatterbot`

```
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

# Create a new trainer for the chatbot
trainer = ChatterBotCorpusTrainer(chatbot)

# Train the chatbot based on the english corpus
trainer.train("chatterbot.corpus.english")

# Get a response to an input statement
chatbot.get_response("Hello, how are you today?")
```

**Comment by sohamnandi007** [comment]
Hello @SaloniSS, I would suggest deleting the cache file. 
So, 
Delete the pip folder from **C:\Users\soham\AppData\Local\pip** and
then **pip install chatterbot_corpus**
it will work and remember if it shows **using cached** during installation then it will not install properly in your system so, in those cases remember to delete pip cache files.
**Also, python 3.7.0 + is recommended.**

**Comment by srianbury** [comment]
thanks @sohamnandi007! I didn't realize I needed to `pip install chatterbot_corpus`

**Comment by Ahammedjaleel** [comment]
Try below command 
pip install git+git://github.com/gunthercox/chatterbot-corpus@master#egg=chatterbot_corpus
