### ISSUE TITLE
Error is occuring 'ChatBot' object has no attribute 'set_trainer'

### ISSUE THREAD

**Issue by MuhammadAnas14** [gunthercox/ChatterBot#1896]
from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

app = Flask(__name__)

docbot = ChatBot('Bot',
                 storage_adapter='chatterbot.storage.SQLStorageAdapter',
                 logic_adapters=[
                     {
                         'import_path': 'chatterbot.logic.BestMatch'
                     },

                 ],
                 trainer='chatterbot.trainers.ListTrainer')
docbot.set_trainer(ListTrainer)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')  #user query
    response = str(docbot.get_response(userText)) #bot response

    return response

if __name__ == '__main__':
    app.run(debug=True)

**Comment by gunthercox** [comment]
This error is the result of trying to run older code with newer versions of the ChatterBot library. Please take a look at the documentation for updated examples.
