### ISSUE TITLE
How to load a model?

### ISSUE THREAD

**Issue by jonrules48** [gunthercox/ChatterBot#1897]
I want to know if I can load a SQL3 file as training data. Is it possible and how? Here is my code:

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
my_bot = ChatBot(name='PyBot', read_only=True,
          logic_adapters=
['chatterbot.logic.MathematicalEvaluation',
          'chatterbot.logic.BestMatch'])
from chatterbot.trainers import ChatterBotCorpusTrainer

corpus_trainer = ChatterBotCorpusTrainer(my_bot)
corpus_trainer.train('chatterbot.corpus.english')

def chat():
    chat=input()
    print(my_bot.get_response(chat))

**Comment by AllanNyasha** [comment]
l after training you chatterbot l woud suggest you comment out 

`corpus_trainer.train('chatterbot.corpus.english')`

so that it doesnt do the training again when this file called/imported and you save the file
