### ISSUE TITLE
No module named 'en'

### ISSUE THREAD

**Issue by qmffnrns** [gunthercox/ChatterBot#1899]
I'm going to start a chatbot through this site [https://chatterbot.readthedocs.io/en/stable/quickstart.html]
But an error occurred. I want to solve this but what should I do?
help me please :(

`
from chatterbot import ChatBot

chatbot = ChatBot(
    'Charlie',
    trainer='chatterbot.trainers.ListTrainer'
)
`

> ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-dec491829d36> in <module>
      1 chatbot = ChatBot(
      2     'Charlie',
----> 3     trainer='chatterbot.trainers.ListTrainer'
      4 )

D:\Anacon\lib\site-packages\chatterbot\chatterbot.py in __init__(self, name, **kwargs)
     26         self.logic_adapters = []
     27 
---> 28         self.storage = utils.initialize_class(storage_adapter, **kwargs)
     29 
     30         primary_search_algorithm = IndexedTextSearch(self, **kwargs)

D:\Anacon\lib\site-packages\chatterbot\utils.py in initialize_class(data, *args, **kwargs)
     31         Class = import_module(data)
     32 
---> 33         return Class(*args, **kwargs)
     34 
     35 

D:\Anacon\lib\site-packages\chatterbot\storage\sql_storage.py in __init__(self, **kwargs)
     18 
     19     def __init__(self, **kwargs):
---> 20         super().__init__(**kwargs)
     21 
     22         from sqlalchemy import create_engine

D:\Anacon\lib\site-packages\chatterbot\storage\storage_adapter.py in __init__(self, *args, **kwargs)
     21 
     22         self.tagger = Tagger(language=kwargs.get(
---> 23             'tagger_language', languages.ENG
     24         ))
     25 

D:\Anacon\lib\site-packages\chatterbot\tagging.py in __init__(self, language)
     24         self.punctuation_table = str.maketrans(dict.fromkeys(string.punctuation))
     25 
---> 26         self.nlp = spacy.load(self.language.ISO_639_1.lower())
     27 
     28     def get_text_index_string(self, text):

D:\Anacon\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 

D:\Anacon\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    132             return load_model_from_link(name, **overrides)
    133         if is_package(name):  # installed as package
--> 134             return load_model_from_package(name, **overrides)
    135         if Path(name).exists():  # path to model data directory
    136             return load_model_from_path(Path(name), **overrides)

D:\Anacon\lib\site-packages\spacy\util.py in load_model_from_package(name, **overrides)
    152 def load_model_from_package(name, **overrides):
    153     """Load a model from an installed package."""
--> 154     cls = importlib.import_module(name)
    155     return cls.load(**overrides)
    156 

D:\Anacon\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

D:\Anacon\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

D:\Anacon\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

D:\Anacon\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'en'

**Comment by YOKI2048** [comment]
I used to meet this error too. I had installed the 'en',but it didn't work. In the beginning I used anaconder, Finally I solved the proplem by using pycharm and made a new env, maybe this will help you.

**Comment by gunthercox** [comment]
You can also do something like this to link the installed spacy model to the preferred language code name:
```
python -m spacy link en_core_web_sm en
```

**Comment by Riseryn** [comment]
Hello
I have a similar problem
Can't find model 'en'

the problem is that i installed spacy with french and after installation it said

✔ Download and installation successful
You can now load the model via spacy.load('fr_core_news_sm')
✔ Linking successful

I defined my bot like this :

bot = ChatBot(
        'Nora',
        language='FRE',
		...
		
So i expected the language to be recognized as french.

Im using chatterbot 1.1.1

any idea?
Thanks

**Comment by conradbm** [comment]
> You can also do something like this to link the installed spacy model to the preferred language code name:
> 
> ```
> python -m spacy link en_core_web_sm en
> ```

>>python -m spacy link en_core_web_sm en
DeprecationWarning: The command link is deprecated.
⚠ As of spaCy v3.0, model symlinks are not supported anymore. You can load
trained pipeline packages using their full names or from a directory path.

**Comment by immacool** [comment]
> DeprecationWarning: The command link is deprecated.
> ⚠ As of spaCy v3.0, model symlinks are not supported anymore. You can
> load trained pipeline packages using their full names or from a directory
> path.
Same issue
