### ISSUE TITLE
Is that a definition or an oppinion? 

### ISSUE THREAD

**Issue by dcsan** [gunthercox/ChatterBot#190]
I'm trying to train the bot and keep getting the response. 

> Is that a definition or an oppinion?

Can't see this in the training sets... is it inside the source somewhere for the bot?
Is this a prompt to train the default bot somehow?

**Comment by TimPchelintsev** [comment]
This is from training set - https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/corpus/data/english/conversations.json#L122

**Comment by gunthercox** [comment]
Hi @dcsan 

Just to clarify further, if you wish to limit the scope of the training data to just the English conversations you can do so by passing the following value to your chat bot's train method.

```python
my_chat_bot.train("chatterbot.corpus.english.conversations")
```

Likewise, the following would train the bot off of every data set in the English corpus.

```python
my_chat_bot.train("chatterbot.corpus.english")
```

Hope this helps.

**Comment by kevin-brown** [comment]
"opinion" is misspelled, any chance we can get that corrected?

**Comment by gunthercox** [comment]
@kevin-brown Corrected spelling https://github.com/gunthercox/ChatterBot/commit/db06771539b4a09dc5cca2ee92145bd8d973e63e
