### ISSUE TITLE
chatterbot installation problem on raspberry pi 

### ISSUE THREAD

**Issue by saicharan0304** [gunthercox/ChatterBot#1928]
while using **sudo pip install chatterbot** command it is giving an error as python versio. >2.7 is needed 
but my pi is installed with python 3.x version . so kindly provide me solution to my issue.

**Comment by gitCommitWiL** [comment]
Try using pip3 instead of pip

**Comment by Riseryn** [comment]
Hi
I have the same problem even using sudo pip3.
Any clue ?
Thanks

**Comment by mustious** [comment]
Hello,
Try installing using the following command:
sudo pip3 install Chatterbot==1.0.2

**Comment by Riseryn** [comment]
thanks, it works

**Comment by wholesum** [comment]
You can also change your default python installation to 3 instead of having to use pip3 every time - https://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux
