### ISSUE TITLE
help please chatterbot: AttributeError: 'ChatBot' object has no attribute 'set_trainer'

### ISSUE THREAD

**Issue by sourav8168** [gunthercox/ChatterBot#1933]
Hello,
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('SM')
chatbot.set_trainer(ListTrainer)

while True:
    try:
        request = input('You: ')
        if request.strip() != 'BYE':
            response = chatbot.get_response(request)
            #response = chatbot.get_response('How are you doing today?')
            print('Bot: ', response)
        if request.strip() == 'n':
            request = input('You: ')
        elif request.strip() == 'BYE':
            print('Bot: Bye')
            break
    except(KeyboardInterrupt, EOFError, SystemExit):
            print ('Oops!  That was not a valid input.  Try again, Recompile...')
            break

Whenever, I'm running the above simple bot, I'm getting this error.
**AttributeError: 'ChatBot' object has no attribute 'set_trainer'**

Kindly advise, how to prevent running the corpus at every time which increased the "db.sqlite3" file considerably.

Regards

**Comment by rohanrmallya** [comment]
The `set_trainer` function was removed.
A solution to this problem is listed here https://github.com/gunthercox/ChatterBot/issues/1674#issuecomment-475469375

**Comment by shanmuhappriyamuthukrishnan** [comment]
from chatterbot import ChatBot
chatbot = ChatBot("CHAT BOT")
from chatterbot.trainers import ListTrainer

conversation = [
"Hey",
"Hi there!",
"Hey bot! how are you doing?",
"I'm doing great. What's up Dude?.",
"Nothing much. Good to hear from you",
"Thank you.",
"You're welcome."
]
trainer = ListTrainer(chatbot)
trainer.train(conversation)
while True:
    request = input("you : ")
    response = bot.get_response(request)
    print("Bot : ", response)

Try this!
