### ISSUE TITLE
Installation and first use error

### ISSUE THREAD

**Issue by mrmrn** [gunthercox/ChatterBot#194]
Dear Developers,
At first this is so good for me that can test a language independent chat bot.
I tried to install ChatterBot in ubuntu 14.04 and I can`t install it without sudo!
then I used this document to start an example: http://chatterbot.readthedocs.io/en/latest/examples.html#terminal-example
I create a chatbot.py text file and input the example1 in it. but when I start the example I gave this error:
"ubuntu@lts ~/chatbot> python3 chatbot.py 
Traceback (most recent call last):
  File "chatbot.py", line 1, in <module>
    from chatterbot import ChatBot
ImportError: No module named 'chatterbot'
"
and the chatterbot is installed.
"ubuntu@lts ~/chatbot> pip install chatterbot
Requirement already satisfied (use --upgrade to upgrade): chatterbot in /usr/local/lib/python2.7/dist-packages
Cleaning up..."

I have same error with sudo...

thank you.

**Comment by gustavo-gomez** [comment]
Hi, I am not the developer but can help you, you installed chatterbot into Python 2.7 but tried to use it with Python 3, so make sure you use or Python 2.7 or Python 3 but no both.

**Comment by futetest** [comment]
yup, gustavo-gomez is right, just do 

`python chatbot.py
`
it'll work
