### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by montematico** [gunthercox/ChatterBot#1941]
The clock function was removed from python 3.8 so you need to downgrade to a previous version to run chatterbot.

**Comment by Vishnu2003** [comment]
Or try changing...
time_func = time.process_time()
insted of.. time_func = time.clock in
C:\Users\Admin\AppData\Local\Programs\Python\Python38\Lib\
site-packages\sqlalchemy\util\compat.py

**Comment by gunthercox** [comment]
This should be fixed as of ChatterBot version 1.0.7
