### ISSUE TITLE
I dont Know what is happening, please, help me

### ISSUE THREAD

**Issue by satteridk** [gunthercox/ChatterBot#1943]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\satter\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Satter\\AppData\\Local\\Temp\\pip-install-g85vt90c\\blis\\setup.py'"'"'; __file__='"'"'C:\\Users\\Satter\\AppData\\Local\\Temp\\pip-install-g85vt90c\\blis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Satter\AppData\Local\Temp\pip-wheel-2ted1nrw'
         cwd: C:\Users\Satter\AppData\Local\Temp\pip-install-g85vt90c\blis\
    Complete output (21 lines):
    BLIS_COMPILER? None
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\blis
    copying blis\about.py -> build\lib.win-amd64-3.8\blis
    copying blis\benchmark.py -> build\lib.win-amd64-3.8\blis
    copying blis\__init__.py -> build\lib.win-amd64-3.8\blis
    creating build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\common.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\test_dotv.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\test_gemm.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\tests\__init__.py -> build\lib.win-amd64-3.8\blis\tests
    copying blis\cy.pyx -> build\lib.win-amd64-3.8\blis
    copying blis\py.pyx -> build\lib.win-amd64-3.8\blis
    copying blis\cy.pxd -> build\lib.win-amd64-3.8\blis
    copying blis\__init__.pxd -> build\lib.win-amd64-3.8\blis
    running build_ext
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
    ERROR: Failed building wheel for blis
    Running setup.py clean for blis
  Failed to build preshed thinc blis
  Installing collected packages: setuptools, wheel, Cython, cymem, preshed, murmurhash, numpy, blis, wasabi, srsly, plac, tqdm, thinc
      Running setup.py install for preshed: started
      Running setup.py install for preshed: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\satter\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Satter\\AppData\\Local\\Temp\\pip-install-g85vt90c\\preshed\\setup.py'"'"'; __file__='"'"'C:\\Users\\Satter\\AppData\\Local\\Temp\\pip-install-g85vt90c\\preshed\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Satter\AppData\Local\Temp\pip-record-nrzifn8e\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Satter\AppData\Local\Temp\pip-build-env-ykkpwl3p\overlay' --compile --install-headers 'C:\Users\Satter\AppData\Local\Temp\pip-build-env-ykkpwl3p\overlay\Include\preshed'
           cwd: C:\Users\Satter\AppData\Local\Temp\pip-install-g85vt90c\preshed\
      Complete output (6 lines):
      running install
      running build
      running build_py
      running build_ext
      building 'preshed.maps' extension
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\satter\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Satter\\AppData\\Local\\Temp\\pip-install-g85vt90c\\preshed\\setup.py'"'"'; __file__='"'"'C:\\Users\\Satter\\AppData\\Local\\Temp\\pip-install-g85vt90c\\preshed\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Satter\AppData\Local\Temp\pip-record-nrzifn8e\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Satter\AppData\Local\Temp\pip-build-env-ykkpwl3p\overlay' --compile --install-headers 'C:\Users\Satter\AppData\Local\Temp\pip-build-env-ykkpwl3p\overlay\Include\preshed' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\satter\appdata\local\programs\python\python38\python.exe' 'c:\users\satter\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Satter\AppData\Local\Temp\pip-build-env-ykkpwl3p\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

**Comment by gunthercox** [comment]
Hi, although that is a long error message I think the relevant part you should look at is this:
> Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

In Windows, some additional programs such as Visual C++ are required to build some Python packages that contain c++ code.
