### ISSUE TITLE
How would i train a bot using the cornell movie corpus

### ISSUE THREAD

**Issue by idkwhyievenhavegithub** [gunthercox/ChatterBot#1948]
Could you please give me some example code on how I would convert the Cornell movie corpus into something I could use in a training instance Thanks

**Comment by AllanNyasha** [comment]
Use the below code to remove the the strings 

`import pandas as pd

df=pd.read_csv('training_data/movie_lines.txt', sep = '\+\+\+\$\+\+\+', engine = 'python', index_col = False)
df.head()`

then use the below code to drop the columns you dont need

`df.drop(df.columns[0:4], axis=1, inplace=True)
df.drop([0])
df.head()`

**Comment by leocornelius** [comment]
@AllanNyasha would you then use that with the list trainer?

**Comment by AllanNyasha** [comment]
Yes l did

**Comment by leocornelius** [comment]
im afraid youve used it wrong. its not in order and you have to construct it from the conversation lines file

**Comment by AdhTri-001** [comment]
@idkwhyievenhavegithub @AllanNyasha Have you found the way to do it? Pls share how u did it with me, i m stuck?
