### ISSUE TITLE
How to build Interactive Chatbot with Chatterbot

### ISSUE THREAD

**Issue by ankush7489** [gunthercox/ChatterBot#1954]
Hi Team,
I am developing a ChatBot for Our DevOps Team, which will be hosted in our internal Infrastructure i.e. on Intranet.
Our Requirement is to have chatbot with fixed responses, e.g. the user has to select from the given option only. Like dominos app.
Please help me how to build it and please share any example of chatterbot + Flask with this kind of use case.

**Comment by leocornelius** [comment]
That would be on your end. Not the bots end. Rather than having a typed interface where the users can ask questions have boxes with all the supported questions they can ask
