### ISSUE TITLE
Problem installing Chatterbot

### ISSUE THREAD

**Issue by BardurianHero** [gunthercox/ChatterBot#1955]
Hello,
I fail to install Chatterbot. I am using 64bits python, and I don't understand where the problem comes from.
Here is what appears in the shell (I use Pyzo):

>>> pip install chatterbot
Collecting chatterbot
  Using cached https://files.pythonhosted.org/packages/6c/0e/dac0d82f34f86bf509cf5ef3e2dfc5aa7d444bd843a2330ceb7d854f84f2/ChatterBot-1.0.5-py2.py3-none-any.whl
Collecting spacy<2.2,>=2.1 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/1f/e2/46650d03c7ff2b57ed7af211d41c3f606540f7adea92b5af65fcf9f605c0/spacy-2.1.9.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\yona\appdata\local\programs\python\python38\python.Error in pip command:
'utf-8' codec can't decode byte 0xe9 in position 5339: invalid continuation byte

I also tried directly typing 'pip install chatterbot' in the cmd. The result is in the pdf.

[Chatterbotfail.pdf](https://github.com/gunthercox/ChatterBot/files/4510926/Chatterbotfail.pdf)

Thank you

**Comment by jonathanferreiras** [comment]
I have the same problem to install this package on windows.

**Comment by jonathanferreiras** [comment]
My friend use **pip install chatterbot==1.0.2**

**Comment by BardurianHero** [comment]
It worked ! Thank you very much !
