### ISSUE TITLE
Unable to install ChatterBot using terminal

### ISSUE THREAD

**Issue by benthecreator** [gunthercox/ChatterBot#1965]
I'm still kind of new to this whole ChatterBot program, and I'm trying to learn more about it. When I tried to install it in Terminal, I used: `pip install chatterbot`
This didn't work before, supposedly because I didn't have Python 3 installed. But I do now, and to check myself I typed `python` which yielded version 3.8.2. I've tried many commands to install ChatterBot, like `pip3 install chatterbot` or `pip install chatterbot-corpus --user` but nothing seems to be working, including running as an admin. I get the following error message every time I try to install it:

ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-gnesqnks/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

Here is another part of that message:

ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-sbudea1v/blis/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-sbudea1v/blis/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-2s1xy34k/install-record.txt --single-version-externally-managed --prefix /private/tmp/pip-build-env-gnesqnks/overlay --compile Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 20.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.

(For those of you asking about the last line talking about pip upgrading, I _did_ use 'pip install --upgrade pip' to upgrade pip).

EDIT: I saw something about an Environment Error multiple times, if that helps at all.

Does anyone know how to fix this? Any help would be appreciated. Thanks.

**Comment by psidney** [comment]
I was able to get it to work installing LLVM, but it's likely due to Python 3.8. I would downgrade to 3.7 for now to use Chatterbot.

**Comment by benthecreator** [comment]
> I was able to get it to work installing LLVM, but it's likely due to Python 3.8. I would downgrade to 3.7 for now to use Chatterbot.

The only version that looks like it is compatible with chatterbot is 3.7, for me at least. I was able to install it and used a virtual environment. Now I’m just stuck on how to use it inside that virtual environment.

**Comment by gunthercox** [comment]
This may have been resolved by #2027 which eliminated a number of dependencies from the instillation process. You may be able to install the latest version of ChatterBot without any issues.
