### ISSUE TITLE
Chatterbot Installation Issue

### ISSUE THREAD

**Issue by hdkhoa162** [gunthercox/ChatterBot#1967]
Hi guys,

I have an issue with installing chatterbot 1.0.5 in the docker image (amd64/python:3.7.3). It hangs in "installing collected packages". What is this problem?

**Comment by mmoore7** [comment]
How long have you waited? When I install chatterbot in a virtual environment, it can take up to 10 minutes.

**Comment by hdkhoa162** [comment]
I waited for 30 mins

**Comment by Thrillerbuddy** [comment]
Probably it must be an Memory issue, the virtual env memory for me earlier was 2GB and it maxed out and throwed up error Killed and then increased the memory to 8GB and got successfully installed chatterbot.
