### ISSUE TITLE
Nested in_response_to keys appearing in json database

### ISSUE THREAD

**Issue by nvartolomei** [gunthercox/ChatterBot#197]
Hi! I'm getting familiar with ChatterBot, at the moment I try to understand how it works under the hood.
When I opened the database I saw this:
```json
"Again...": {
    "in_response_to": [
      {
        "in_response_to": [
          {
            "occurrence": 2,
            "signature": [],
            "text": "It depends how you define life"
          }
        ],
        "text": "Life is the condition that distinguishes organisms from inorganic matter, including the capacity for growth, reproduction, functional activity, and continual change preceding death."
      }
    ]
  },
```

Hm, it looks like this is conversation tracking, but issue #2 say otherwise
> Currently, ChatterBot only responds to the last statement that was entered

Can someone shed some light on this?

**Comment by gunthercox** [comment]
Hi @nvartolomei, This looks like a case where a statement is being saved as a response somewhere in the code base. It won't cause any problems but I will take a look through and see if I can determine where this is occurring. Could you let me know what adapters you are using for your chat bot?

**Comment by nvartolomei** [comment]
@gunthercox basic example with english corpus trainer. Also when asking some questions, when asking empty questions, after few questions it can't parse the database anymore. This also happens when using mongodb storage.

```
from chatterbot import ChatBot

# Create a new chat bot named Charlie
chatbot = ChatBot("Charlie")

chatterbot.set_trainer(ChatterBotCorpusTrainer)

chatterbot.train(
    "chatterbot.corpus.english"
)

# Get a response to the input "How are you?"
response = chatbot.get_response("How are you?")

print(response)
```

**Comment by gunthercox** [comment]
I believe this issue has been resolved by https://github.com/gunthercox/ChatterBot/pull/224
Feel free to reopen if it continues.
