### ISSUE TITLE
image as chatterbot response

### ISSUE THREAD

**Issue by thiaguiarfideles** [gunthercox/ChatterBot#1979]
I need to return an answer with an image on chatterbot.corpus

the image already exists in this static directory
static \ rogbot \ img

- - How does the vital sign monitor work?
  - <img async = on src = "{{url_for ('static / rogbot / img', filename = 'vital_jp.JPG')}}" alt = "start" />

I need her to appear in the chat as an answer

**Comment by ignertic** [comment]
Hi there, I doubt you can be able to get an image file as a response unless you make some sort of adapter

But here is a workaround, in wherever you process the input have the adapter return an image url and in your UI load it

**Comment by thiaguiarfideles** [comment]
this way it worked
app.py 
@app.route("/get-image/<image_name>")
def download_file(filename):
    return send_from_directory(app.config['ROGBOT_IMAGES'],
                               filename, as_attachment=True)

config.py
# The absolute path of the directory containing images for users to download
app.config["ROGBOT_IMAGES"] = "Users/THIAG/PycharmProjects/ROGBOT_/static/rogbot/img"
