### ISSUE TITLE
Any way to leverage Spark for better performance?

### ISSUE THREAD

**Issue by quanghoc** [gunthercox/ChatterBot#198]
I'd like to figure out if it's possible to convert the usage of local file system for .json file to HDFS and have Spark MLib to do the machine learning instead. What are the thoughts on this?

**Comment by gunthercox** [comment]
This sounds possible. You may be able to implement a custom storage adapter that connects to HDFS and a custom logic adapter that uses Spark. ChatterBot's documentation covers these and there is also various existing adapters that can be used as examples in this repository.
