### ISSUE TITLE
Installation Error:Cannot uninstall 'PyYAML'

### ISSUE THREAD

**Issue by Monsieurvishal** [gunthercox/ChatterBot#1980]
I use windows 10 OS

(base) C:\Users\Vishal>pip install chatterbot==0.8.6
Requirement already satisfied: chatterbot==0.8.6 in c:\users\vishal\anaconda3\new\lib\site-packages (0.8.6)
Requirement already satisfied: mathparse<0.2,>=0.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from chatterbot==0.8.6) (0.1.2)
Requirement already satisfied: chatterbot-corpus<1.2,>=1.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from chatterbot==0.8.6) (1.1.4)
Requirement already satisfied: pymongo<4.0,>=3.3 in c:\users\vishal\anaconda3\new\lib\site-packages (from chatterbot==0.8.6) (3.10.1)
Requirement already satisfied: python-twitter<4.0,>=3.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from chatterbot==0.8.6) (3.5)
Requirement already satisfied: sqlalchemy<1.3,>=1.2 in c:\users\vishal\anaconda3\new\lib\site-packages (from chatterbot==0.8.6) (1.2.19)
Collecting python-dateutil<2.7,>=2.6 (from chatterbot==0.8.6)
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
Requirement already satisfied: nltk<4.0,>=3.2 in c:\users\vishal\anaconda3\new\lib\site-packages (from chatterbot==0.8.6) (3.4.4)
Collecting PyYAML<4.0,>=3.12 (from chatterbot-corpus<1.2,>=1.1->chatterbot==0.8.6)
  Using cached https://files.pythonhosted.org/packages/bf/96/d02ef8e1f3073e07ffdc240444e5041f403f29c0775f9f1653f18221082f/PyYAML-3.13-cp37-cp37m-win_amd64.whl
Requirement already satisfied: future in c:\users\vishal\anaconda3\new\lib\site-packages (from python-twitter<4.0,>=3.0->chatterbot==0.8.6) (0.18.2)
Requirement already satisfied: requests-oauthlib in c:\users\vishal\anaconda3\new\lib\site-packages (from python-twitter<4.0,>=3.0->chatterbot==0.8.6) (1.3.0)
Requirement already satisfied: requests in c:\users\vishal\anaconda3\new\lib\site-packages (from python-twitter<4.0,>=3.0->chatterbot==0.8.6) (2.22.0)
Requirement already satisfied: six>=1.5 in c:\users\vishal\anaconda3\new\lib\site-packages (from python-dateutil<2.7,>=2.6->chatterbot==0.8.6) (1.12.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests-oauthlib->python-twitter<4.0,>=3.0->chatterbot==0.8.6) (3.1.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot==0.8.6) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot==0.8.6) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot==0.8.6) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\vishal\anaconda3\new\lib\site-packages (from requests->python-twitter<4.0,>=3.0->chatterbot==0.8.6) (2.8)
Installing collected packages: python-dateutil, PyYAML
  Found existing installation: python-dateutil 2.8.1
    Uninstalling python-dateutil-2.8.1:
      Successfully uninstalled python-dateutil-2.8.1
  Found existing installation: PyYAML 5.1.1

**ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.**

**Comment by c-chaitanya** [comment]
Do try out the solutions mentioned [here](https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml).
`sudo -H pip3 install --ignore-installed PyYAML` should get the task accomplished

**Comment by Monsieurvishal** [comment]
Thanks ! It worked .
