### ISSUE TITLE
how to solve this error

### ISSUE THREAD

**Issue by sijukallada** [gunthercox/ChatterBot#1989]
AttributeError                            Traceback (most recent call last)
<ipython-input-3-0bb4c77e4b66> in <module>
      2 from chatterbot.trainers import ListTrainer
      3 
----> 4 bot = ChatBot('MyChatBot')
      5 trainer=ListTrainer(bot)
      6 

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\chatterbot\chatterbot.py in __init__(self, name, **kwargs)
     32         self.logic_adapters = []
     33 
---> 34         self.storage = utils.initialize_class(storage_adapter, **kwargs)
     35 
     36         for adapter in logic_adapters:

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\chatterbot\utils.py in initialize_class(data, *args, **kwargs)
     52         Class = import_module(data)
     53 
---> 54         return Class(*args, **kwargs)
     55 
     56 

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\chatterbot\storage\sql_storage.py in __init__(self, **kwargs)
     20         super().__init__(**kwargs)
     21 
---> 22         from sqlalchemy import create_engine
     23         from sqlalchemy.orm import sessionmaker
     24 

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\__init__.py in <module>
      6 # the MIT License: http://www.opensource.org/licenses/mit-license.php
      7 
----> 8 from . import util as _util  # noqa
      9 from .inspection import inspect  # noqa
     10 from .schema import BLANK_SCHEMA  # noqa

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\__init__.py in <module>
     12 from functools import update_wrapper  # noqa
     13 
---> 14 from ._collections import coerce_generator_arg  # noqa
     15 from ._collections import collections_abc  # noqa
     16 from ._collections import column_dict  # noqa

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\_collections.py in <module>
     14 import weakref
     15 
---> 16 from .compat import binary_types
     17 from .compat import collections_abc
     18 from .compat import itertools_filterfalse

c:\users\origin\appdata\local\programs\python\python38\lib\site-packages\sqlalchemy\util\compat.py in <module>
    262 
    263 if win32 or jython:
--> 264     time_func = time.clock
    265 else:
    266     time_func = time.time

AttributeError: module 'time' has no attribute 'clock'

**Comment by sijukallada** [comment]
How to solve this issue??

**Comment by gunthercox** [comment]
You are seeing this error because ChatterBot has not been modified to support Python 3.8 yet.
Currently the possible options to resolve your issue are:
1. Downgrade to Python 3.7
2. Wait for someone to submit a pull request that adds support for python 3.8
