### ISSUE TITLE
Provide the bot with facts/axioms?

### ISSUE THREAD

**Issue by fr0hsty** [gunthercox/ChatterBot#199]
What would be a best practice method for feeding the bot information that it can consider 'true' and then later recall during conversation eg: 

The sky is blue. Chocolate is delicious. You like Coffee.

>What color is the sky?
- Blue.

>Do you enjoy coffee? 
- Yes

I'm absolutely loving my limited ChatterBot experience thus far :)

**Comment by gunthercox** [comment]
One way to do this could be to create your own training corpus. Check out the existing ones that come with ChatterBot for an example: https://github.com/gunthercox/ChatterBot/tree/master/chatterbot/corpus/data/english

You may also want to see the documentation on training from corpus data if you haven't yet: http://chatterbot.readthedocs.io/en/latest/training.html#training-with-corpus-data
