### ISSUE TITLE
Having issues installing chatterbot in python 3.8

### ISSUE THREAD

**Issue by Hassanolowofela** [gunthercox/ChatterBot#1998]
A wonderful day to you,
I have a project to build a chat bot, but while trying to install chatterbot in my python3.8, these errors keeping stopping the process.

  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\pycharmprojects\mychatbot\venv\scripts\python.exe' 
 'c:\users\user\pycharmprojects\mychatbot\venv\lib\site-packages\pip' install --ignore-i
nstalled --no-user --prefix 'C:\Users\User\AppData\Local\Temp\pip-build-env-ic157z8y\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i ht
tps://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (74 lines):
  Collecting setuptools
    Using cached setuptools-47.3.1-py3-none-any.whl (582 kB)...

Please what is the way out?

**Comment by gunthercox** [comment]
Sorry, I haven't had a chance to add Python 3.8 supported yet.

**Comment by Hassanolowofela** [comment]
Okay, much thanks.
Please is there any suggestions for a way out or alternatives for me to meet up with deadline for my project submission?

**Comment by gunthercox** [comment]
This should be resolved now that ChatterBot version 1.0.7 was released.
