### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by NotSoSuper** [gunthercox/ChatterBot#200]
The responses become very slow after the brain/AI becomes to be used more/learns more.

If theres any way to make it faster after lots of input, as it is very slow at responses with a few thousands conversations.

**Comment by gunthercox** [comment]
Have you tried the MongoDB storage adapter? http://chatterbot.readthedocs.io/en/latest/adapters/storage.html#mongo-database-adapter

**Comment by NotSoSuper** [comment]
I'll try it soon, thanks!

**Comment by NotSoSuper** [comment]
Not sure how much faster it will be now because it didn't transfer the previous contents of what it learned to the new database. However I'll post results in a few days when it becomes used again!

**Comment by Utsav2** [comment]
@NotSoSuper did you notice an improvement?

**Comment by NotSoSuper** [comment]
Yes, however, even after the mongodb gets very large it can tend to slow down.
