### ISSUE TITLE
Bot retrains each response

### ISSUE THREAD

**Issue by EternalDusk** [gunthercox/ChatterBot#2003]
I've tried scouring the issues tab, but to no avail.

Im wondering how do I get the bot not to train again and again each run of my script, and use a trained model?

Code:
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

trainer = ChatterBotCorpusTrainer(chatbot)

trainer.train("chatterbot.corpus.english")

response = chatbot.get_response("Hello, how are you today?")

print(response)

Output:
Training ai.yml: [####################] 100%
Training botprofile.yml: [####################] 100%
Training computers.yml: [####################] 100%
Training conversations.yml: [####################] 100%
Training emotion.yml: [####################] 100%
Training food.yml: [####################] 100%
Training gossip.yml: [####################] 100%
Training greetings.yml: [####################] 100%
Training health.yml: [####################] 100%
Training history.yml: [####################] 100%
Training humor.yml: [####################] 100%
Training literature.yml: [####################] 100%
Training money.yml: [####################] 100%
Training movies.yml: [####################] 100%
Training politics.yml: [####################] 100%
Training psychology.yml: [####################] 100%
Training science.yml: [####################] 100%
Training sports.yml: [####################] 100%
Training trivia.yml: [####################] 100%
What's up?

I dont want it to train again and again, just once and then continuously test the model.

**Comment by humanusa** [comment]
Run this script again but comment the line trainer.train. 

Also check out the Terminal script example - if you want to enter multiple input.

**Comment by EternalDusk** [comment]
Wow okay that was simple. Thank you!
