### ISSUE TITLE
I cant install Chatterbot by pip on CMD

### ISSUE THREAD

**Issue by Jndungue089** [gunthercox/ChatterBot#2009]
When i try, that happens:
pip install ./ChatterBot
Processing c:\users\10\chatterbot
Collecting mathparse<0.2,>=0.1
  Using cached mathparse-0.1.2-py3-none-any.whl (7.2 kB)
Collecting nltk<4.0,>=3.2
  Using cached nltk-3.5.zip (1.4 MB)
Collecting pint>=0.8.1
  Using cached Pint-0.14-py2.py3-none-any.whl (197 kB)
Collecting python-dateutil<2.9,>=2.8
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyyaml<5.4,>=5.3
  Using cached PyYAML-5.3.1-cp38-cp38-win32.whl (199 kB)
Collecting spacy<2.2,>=2.1
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\10\appdata\local\programs\python\python38-32\python.exe' 'c:\users\10\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\10\AppData\Local\Temp\pip-build-env-g6cajw2n\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (76 lines):
  Collecting setuptools
    Using cached setuptools-49.2.0-py3-none-any.whl (789 kB)
  Collecting wheel<0.33.0,>0.32.0
    Using cached wheel-0.32.3-py2.py3-none-any.whl (21 kB)
  Collecting Cython
    Using cached Cython-0.29.21-cp38-cp38-win32.whl (1.6 MB)
  Collecting cymem<2.1.0,>=2.0.2
    Using cached cymem-2.0.3.tar.gz (51 kB)
  Collecting preshed<2.1.0,>=2.0.1
    Using cached preshed-2.0.1.tar.gz (113 kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached murmurhash-1.0.2.tar.gz (35 kB)
  Collecting thinc<7.1.0,>=7.0.8
    Using cached thinc-7.0.8.tar.gz (1.9 MB)
  Collecting blis<0.3.0,>=0.2.1
    Using cached blis-0.2.4.tar.gz (1.5 MB)
  Processing c:\users\10\appdata\local\pip\cache\wheels\7f\14\56\4339536b2a4a77b537f83c8f08b6115b3b945c9d2b2455ae99\wasabi-0.7.0-py3-none-any.whl
  Collecting srsly<1.1.0,>=0.0.6
    Using cached srsly-1.0.2.tar.gz (192 kB)
  Collecting numpy>=1.7.0
    Using cached numpy-1.19.0-cp38-cp38-win32.whl (10.9 MB)
  Collecting plac<1.0.0,>=0.9.6
    Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)
  Collecting tqdm<5.0.0,>=4.10.0
    Using cached tqdm-4.47.0-py2.py3-none-any.whl (66 kB)
  Using legacy setup.py install for cymem, since package 'wheel' is not installed.
  Using legacy setup.py install for preshed, since package 'wheel' is not installed.
  Using legacy setup.py install for murmurhash, since package 'wheel' is not installed.
  Using legacy setup.py install for thinc, since package 'wheel' is not installed.
  Using legacy setup.py install for blis, since package 'wheel' is not installed.
  Using legacy setup.py install for srsly, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, Cython, cymem, preshed, murmurhash, numpy, blis, wasabi, srsly, plac, tqdm, thinc
      Running setup.py install for cymem: started
      Running setup.py install for cymem: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\10\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10\\AppData\\Local\\Temp\\pip-install-2ql9j5is\\cymem\\setup.py'"'"'; __file__='"'"'C:\\Users\\10\\AppData\\Local\\Temp\\pip-install-2ql9j5is\\cymem\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\10\AppData\Local\Temp\pip-record-0a_h_0kz\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\10\AppData\Local\Temp\pip-build-env-g6cajw2n\overlay' --compile --install-headers 'C:\Users\10\AppData\Local\Temp\pip-build-env-g6cajw2n\overlay\Include\cymem'
           cwd: C:\Users\10\AppData\Local\Temp\pip-install-2ql9j5is\cymem\
      Complete output (36 lines):
      WARNING: The wheel package is not available.
      running install
      running build
      running build_py
      creating build
      creating build\lib.win32-3.8
      creating build\lib.win32-3.8\cymem
      copying cymem\about.py -> build\lib.win32-3.8\cymem
      copying cymem\__init__.py -> build\lib.win32-3.8\cymem
      package init file 'cymem\tests\__init__.py' not found (or not a regular file)
      creating build\lib.win32-3.8\cymem\tests
      copying cymem\tests\test_import.py -> build\lib.win32-3.8\cymem\tests
      copying cymem\cymem.pyx -> build\lib.win32-3.8\cymem
      copying cymem\cymem.pxd -> build\lib.win32-3.8\cymem
      copying cymem\__init__.pxd -> build\lib.win32-3.8\cymem
      running build_ext
      building 'cymem.cymem' extension
      creating build\temp.win32-3.8
      creating build\temp.win32-3.8\Release
      creating build\temp.win32-3.8\Release\cymem
      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\10\appdata\local\programs\python\python38-32\include -Ic:\users\10\appdata\local\programs\python\python38-32\include -Ic:\users\10\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpcymem/cymem.cpp /Fobuild\temp.win32-3.8\Release\cymem/cymem.obj /Ox /EHsc
      cymem.cpp
      cymem/cymem.cpp(4501): warning C4996: '_typeobject::tp_print': deprecated in 3.8
      c:\users\10\appdata\local\programs\python\python38-32\include\cpython/object.h(260): note: see declaration of '_typeobject::tp_print'
      cymem/cymem.cpp(4509): warning C4996: '_typeobject::tp_print': deprecated in 3.8
      c:\users\10\appdata\local\programs\python\python38-32\include\cpython/object.h(260): note: see declaration of '_typeobject::tp_print'
      cymem/cymem.cpp(4519): warning C4996: '_typeobject::tp_print': deprecated in 3.8
      c:\users\10\appdata\local\programs\python\python38-32\include\cpython/object.h(260): note: see declaration of '_typeobject::tp_print'
      cymem/cymem.cpp(4525): warning C4996: '_typeobject::tp_print': deprecated in 3.8
      c:\users\10\appdata\local\programs\python\python38-32\include\cpython/object.h(260): note: see declaration of '_typeobject::tp_print'
      C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\10\appdata\local\programs\python\python38-32\libs /LIBPATH:c:\users\10\appdata\local\programs\python\python38-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" /EXPORT:PyInit_cymem build\temp.win32-3.8\Release\cymem/cymem.obj /OUT:build\lib.win32-3.8\cymem\cymem.cp38-win32.pyd /IMPLIB:build\temp.win32-3.8\Release\cymem\cymem.cp38-win32.lib
         Creating library build\temp.win32-3.8\Release\cymem\cymem.cp38-win32.lib and object build\temp.win32-3.8\Release\cymem\cymem.cp38-win32.exp
      Generating code
      Finished generating code
      LINK : fatal error LNK1158: cannot run 'rc.exe'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1158
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\10\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\10\\AppData\\Local\\Temp\\pip-install-2ql9j5is\\cymem\\setup.py'"'"'; __file__='"'"'C:\\Users\\10\\AppData\\Local\\Temp\\pip-install-2ql9j5is\\cymem\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\10\AppData\Local\Temp\pip-record-0a_h_0kz\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\10\AppData\Local\Temp\pip-build-env-g6cajw2n\overlay' --compile --install-headers 'C:\Users\10\AppData\Local\Temp\pip-build-env-g6cajw2n\overlay\Include\cymem' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\10\appdata\local\programs\python\python38-32\python.exe' 'c:\users\10\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\10\AppData\Local\Temp\pip-build-env-g6cajw2n\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

I already tried to install chatterbot-corpus, but nothing

**Comment by ankongithub** [comment]
Can u simply type
pip install chatterbot==1.0.4

**Comment by CrusaderMage** [comment]
You are using Python 3.8, this was not implemented yet for that version. Install a Python 3.7 version or create a virtual environment using Python 3.7.
