### ISSUE TITLE
Same answer for two completely different questions

### ISSUE THREAD

**Issue by tinkuad77** [gunthercox/ChatterBot#2012]
Hi,

here is how I trained my chatbot.

question: Genesis 1:1 
answer: In the beginning, God created heavens and the earth
question: Exodus 1:1
answer: These are the names of the sons of the Israel who came to Egypt with Jacob, each with his household

Issue -->

if I ask the question exodus 1:1 or Genesis 1:1 , it is giving me the same answer which is for Genesis 1:1
Could you please help ?

Here is my logic:

from chatterbot import ChatBot
from chatterbot.response_selection import get_first_response
from chatterbot.comparisons import levenshtein_distance

{
                "import_path": "chatterbot.logic.BestMatch",
                "statement_comparison_function": levenshtein_distance,
                "response_selection_method": get_first_response
        },

        {
                    'import_path': 'chatterbot.logic.BestMatch',
                    'threshold': 0.99,
                    'default_response': 'I am sorry, but I do not understand.'
        },

**Comment by ocideos** [comment]
I think you need to consider, what do you expect as an answer?
That is a very vague question for a chatbot. Are you looking for preference, length of verse, how many words are you comparing, etc.?
What would you be expecting if someone asks genesis 1:1 or genesis 100:5 or anything that’s not encoded in your database?

**Comment by tinkuad77** [comment]
Thank you for your response.

sorry, I am just using the default logic found in documentation.  so, not sure how many words it will match before giving me the answer. I am expecting it to return " I am sorry, but I do not understand' when it does not find anything in my database.

I am looking for the exact match as my training data specifically fed it Genesis 1:1  , Exodus 1:1 

so, looks like it is just going by 1:1 and giving me the answer. how can I alter my code to match the entire string as oppose to just 1:1 ?

**Comment by ocideos** [comment]
You should look into "SpecificResponseAdapter"
Try running the code with the log enabled, with this code at the beginning of your file:

import logging
logging.basicConfig(level=logging.INFO)

So you can see why its selecting that answer

**Comment by tinkuad77** [comment]
thank you. I tried it and here is the log info I got when I searched for Exodus 1:1

confidence is more for Exodus still confused on why it is choosing Genesis with a confidence of 0.57 :-(

INFO:chatterbot.chatterbot:Beginning search for close text match
INFO:chatterbot.chatterbot:Processing search results
INFO:chatterbot.chatterbot:Similar text found: Genesis 1:1 0.57
INFO:chatterbot.chatterbot:Similar text found: Exodus 1:1 1.0
INFO:chatterbot.chatterbot:Using "Exodus 1:1" as a close match to "Exodus 1:1" with a confidence of 1.0
INFO:chatterbot.chatterbot:Selecting response from 12 optimal responses.
INFO:chatterbot.response_selection:Selecting first response from list of 12 options.
INFO:chatterbot.chatterbot:Response selected. Using "In the beginning God created the heavens and the earth."
INFO:chatterbot.chatterbot:BestMatch selected "In the beginning God created the heavens and the earth." as a response with a confidence of 1.0
INFO:chatterbot.chatterbot:Beginning search for close text match
INFO:chatterbot.chatterbot:Processing search results
INFO:chatterbot.chatterbot:Similar text found: Genesis 1:1 0.57
INFO:chatterbot.chatterbot:Similar text found: Exodus 1:1 1.0
INFO:chatterbot.chatterbot:Using "Exodus 1:1" as a close match to "Exodus 1:1" with a confidence of 1.0
INFO:chatterbot.chatterbot:Selecting response from 12 optimal responses.
INFO:chatterbot.response_selection:Selecting first response from list of 12 options.
INFO:chatterbot.chatterbot:Response selected. Using "In the beginning God created the heavens and the earth."
INFO:chatterbot.chatterbot:BestMatch selected "In the beginning God created the heavens and the earth." as a response with a confidence of 1.0

**Comment by ocideos** [comment]
The answer is here:
"INFO:chatterbot.response_selection:Selecting first response from list of 12 options."

Your code is selecting the first of 12 possible answers:
"response_selection_method": get_first_response

**Comment by tinkuad77** [comment]
could you please let me know how can I tweak it to select the appropriate response?

**Comment by ocideos** [comment]
As I was telling you before, the issue is "personal".
What do you need your bot to answer?
Based on that you need to prepare your corpus and the logic accordingly.
