### ISSUE TITLE
chatterbot error

### ISSUE THREAD

**Issue by garimatiwa** [gunthercox/ChatterBot#2024]
from chatterbot import chatBot
from chatterbot.trainers import ListTrainer

Bot=chatBot("my Bot")

convo = {

"Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
}

trainer=ListTrainer(Bot)

trainer.train(convo)

answer=Bot.get_response("what is your name")
print(answer)
**whenever i am executing the above code .it showing me this error:
**ImportError: cannot import name 'chatBot' from 'chatterbot' (C:\Users\Garima\PycharmProject\chatterbotdemo\chatterbot.py)

**Comment by gunthercox** [comment]
The first line in your code has the incorrect casing:
Change `from chatterbot import chatBot` to `from chatterbot import ChatBot`

**Comment by garimatiwa** [comment]
I have already done this .

**Comment by garimatiwa** [comment]
You haven't replied me

**Comment by gunthercox** [comment]
Yes, I haven't replied. Please be respectful and curious of my time.

You haven't given me very much to work with:
![Screenshot from 2020-08-25 16-42-10](https://user-images.githubusercontent.com/2030578/91225666-fd560000-e6f1-11ea-9826-07408bb176f5.png)

Take a look at this whole conversation. Other than the original message that you posted where you were using the incorrect casing you haven't provided any other information that I can possibly use to help you.
