### ISSUE TITLE
How to reset a trained chatterbot?

### ISSUE THREAD

**Issue by RoyCoya** [gunthercox/ChatterBot#2025]
Hi,

I've trained a chat bot with serveral different language corpuses
and when I tried to get response it also returned by different languages...
Is there any way to reset the bot to initial status? didn't find in documents

Sincerely thanks

**Comment by gunthercox** [comment]
To reset a chatbot, you will need to clear the content of its database. If your chatbot is using a sqlite database (the default option) then you can just delete that file. It should be a file named something like `db.sqlite3` located relative to where you have your code.

**Comment by RoyCoya** [comment]
> To reset a chatbot, you will need to clear the content of its database. If your chatbot is using a sqlite database (the default option) then you can just delete that file. It should be a file named something like `db.sqlite3` located relative to where you have your code.

Thanks!
it works
