### ISSUE TITLE
Chatterbot installation issue

### ISSUE THREAD

**Issue by Deepika2010** [gunthercox/ChatterBot#2032]
Does python 3.8 ..32 bit doesn't support chatterbot???

**Comment by luantorrex** [comment]
Hello,
Try to install chatterbot version 1.0.2, running this:
`pip install chatterbot==1.0.2`

**Comment by gunthercox** [comment]
I just tested installing version 1.0.8 on a 32 bit Raspberry Pi without any issues. I think you should be good to go.

```
Successfully installed chatterbot-1.0.8 mathparse-0.1.2 python-dateutil-2.8.1 sqlalchemy-1.3.19
```
