### ISSUE TITLE
Chatterbot Giving  SpaCy Key Error / Adapter Issue

### ISSUE THREAD

**Issue by hankp46** [gunthercox/ChatterBot#2035]
While running follow script:
`from chatterbot import ChatBot

bot = ChatBot(
    'Maxine',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter'
    ],
    database_uri='sqlite:///database.sqlite3'
)

print('ask me something')
while True:
    try:
        bot_input = bot.get_response(input())
        print(bot_input)

    except(KeyboardInterrupt, EOFError, SystemExit):
        break
Get following responses
ask me something
how are you
I am good.
Which is correct
But then:
how much is 2 + 2
Traceback (most recent call last):
  File "maxine.py", line 17, in <module>
    bot_input = bot.get_response(input())
  File "/home/pi/.virtualenvs/chatterbot/lib/python3.7/site-packages/chatterbot/chatterbot.py", line 114, in get_response
    response = self.generate_response(input_statement, additional_response_selection_parameters)
  File "/home/pi/.virtualenvs/chatterbot/lib/python3.7/site-packages/chatterbot/chatterbot.py", line 150, in generate_response
    output = adapter.process(input_statement, additional_response_selection_parameters)
  File "/home/pi/.virtualenvs/chatterbot/lib/python3.7/site-packages/chatterbot/logic/best_match.py", line 61, in process
    input_statement.text
  File "/home/pi/.virtualenvs/chatterbot/lib/python3.7/site-packages/chatterbot/tagging.py", line 45, in get_bigram_pair_string
    tokens[index].lemma_.lower()
  File "token.pyx", line 894, in spacy.tokens.token.Token.lemma_.__get__
  File "strings.pyx", line 136, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '471611514'. This usually refers to an issue with the `Vocab` or `StringStore`."

`I am running this on a RPi4 with this version of SpaCy 
spaCy version    2.3.2                         
Location         /home/pi/.virtualenvs/chatterbot/lib/python3.7/site-packages/spacy
Platform         Linux-5.4.51-v7l+-armv7l-with-debian-10.4
Python version   3.7.3                         
Models           en  

Also if i comment out the BestMatch Adapter I get:
 python maxine.py
ask me something
how much is 2 + 2
2 + 2 = 4
what time is it
The current time is 05:02 PM
how are you
The current time is 05:02 PM

Which seems to mean bestMatch is taking precedence of the the other adapters

**Comment by hankp46** [comment]
I  changed my architecture to arm64 and it seems to be working now.  
BTW still needed to install spacy using 
BLIS_ARCH="generic" pip3 install --user spacy --no-binary=blis

**Comment by bobthechemist** [comment]
@hankp46 Can you clarify if you used the 64 bit (beta) image or if you enabled the 64 bit kernel with `arm_64bit=1`?
