### ISSUE TITLE
Is there a better way to handle big data?

### ISSUE THREAD

**Issue by AtomynosAtom** [gunthercox/ChatterBot#2037]
I have recently downloaded a big data file and was processing it. I successfully extracted required data and stored it in a .db file. I then proceeded to convert data from the .db file to a Yaml file. But I keep on getting errors when trying to train the bot.

```
Training train0.yml: [##                  ] 9%
 Failed to process ./trainfiles/train0.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16
Training train1.yml: [#                   ] 3%
 Failed to process ./trainfiles/train1.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16

 Failed to process ./trainfiles/train2.yml 

unacceptable character #x007f: special characters are not allowed
  in "./trainfiles/train2.yml", position 676364
<class 'yaml.reader.ReaderError'> Train.py 16

 Failed to process ./trainfiles/train3.yml 

unacceptable character #x007f: special characters are not allowed
  in "./trainfiles/train3.yml", position 260191
<class 'yaml.reader.ReaderError'> Train.py 16
Training train4.yml: [##                  ] 8%
 Failed to process ./trainfiles/train4.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16
Training train5.yml: [#####               ] 24%
 Failed to process ./trainfiles/train5.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16
Training train6.yml: [                    ] 2%
 Failed to process ./trainfiles/train6.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16
Training train7.yml: [#                   ] 6%
 Failed to process ./trainfiles/train7.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16
Training train8.yml: [#                   ] 7%
 Failed to process ./trainfiles/train8.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16
Training train9.yml: [#                   ] 5%
 Failed to process ./trainfiles/train9.yml 

'bool' object has no attribute 'strip'
<class 'AttributeError'> Train.py 16

 Failed to process ./trainfiles/train10.yml 

[Errno 2] No such file or directory: './trainfiles/train10.yml'
<class 'FileNotFoundError'> Train.py 16

```

The 1st set of errors was that the data started with a symbol. But I avoided that by removing each line containing such. Now I am not really sure what to do with errors 
>'bool' object has no attribute 'strip'

and
>unacceptable character #x007f: special characters are not allowed

Any help on how to solve this or any advice to handle big data would be very much appreciated.

**Comment by gunthercox** [comment]
Currently, there is not an implementation that allows ChatterBot to handle large amounts of data efficiently.

**Comment by shanu2698** [comment]
@AtomynosAtom  even i was having this error 
'bool' object has no attribute 'strip'
So after hours of debugging i found that if thge data set is having a line initiating with 'yes' or 'no' irrespective of the letter case it prompts the above error

for me it worked i simply appended an underscore to that text in the beginning

**Comment by shanu2698** [comment]
@AtomynosAtom  the below code is to remove emojis from your txt  although they are not all the emoticons they're just samples

`
import re

emojiList="[`~!@#$%^&*()-+=🚡🚛🛣🍾🏃🕴🍻🥃🥂⛄☃️❄️😎🤓🧐🤨🙁😣😖😫😻😼😾🙌🏻👐🏻🤲🏻👏🏻👏🏻🤝🏻👍🏻👎🏻✊🏻🤛🏻]"
chat_ob = open("Chats.txt","r")  # source txt file or the data file (whatsapp chat in my case) 
chat=chat_ob.readlines()
CleanedChat=open("Chats.yml","w")  #creating a new yaml  file

for eachline in chat:
	count=0
	lineCleaned=re.sub("^[0-3].*[AP]M ","",eachline) # removing the date format
	temp=re.findall(emojiList,lineCleaned)  # removing the  emojis and special characters
	count=len(temp)
	NotAllremoveEmoji=re.sub(emojiList,"", lineCleaned,count-1)
	removeEmoji=re.sub(emojiList," I would have sent emojis but this system does not support it :) ", NotAllremoveEmoji) 
	if not removeEmoji.strip():
		continue
	if removeEmoji:
		CleanedChat.write(removeEmoji)  # this will write the chats into newly created yaml file
CleanedChat.close()
`

**Comment by AtomynosAtom** [comment]
> @AtomynosAtom even i was having this error
> 'bool' object has no attribute 'strip'
> So after hours of debugging i found that if thge data set is having a line initiating with 'yes' or 'no' irrespective of the letter case it prompts the above error
> 
> for me it worked i simply appended an underscore to that text in the beginning

Won't that affect the response of the bot to questions? Because when the bot is calculating the response it will calculate the data with an _ in the front... 
I stopped following up on the Chatterbot project as it is too slow for the amount of data I was using so I moved on to other projects.
