### ISSUE TITLE
Default Reply

### ISSUE THREAD

**Issue by futetest** [gunthercox/ChatterBot#204]
Hi
As of now chatbot repeats the statement which it can't map to the database. Suppose it doesn't have a mapping for "Hello", it would throw back hello in reply as well. What I want to do is, for all the matches it can't find, it should give a default reply like "not found" or something. Any help ?
P.S. I've turned off the learning.

**Comment by gunthercox** [comment]
There is not currently a way to set a default response. Having a default response prevents the chat bot from learning new responses (even when it responds incorrectly). It is not likely that this is something that will be added in the future.

**Comment by futetest** [comment]
Since there's an option to turn off the learning, I thought this is something that's achievable. Can you at least tell me, how does it give the same response if it can't find the map to it. Let's say there is no map for "Mercedes", it returns "Mercedes" back, how does it do that ?

**Comment by gunthercox** [comment]
If no responses are known, there is an internal logic adapter that returns the input statement: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/adapters/logic/no_knowledge_adapter.py
