### ISSUE TITLE
Getting different chatbot answers for same set of questions on different systems.

### ISSUE THREAD

**Issue by Siddikulus** [gunthercox/ChatterBot#2047]
Hello, I have the same Chatbot Script on two different systems.

```
System 1 Specifications: Windows, Python - 3.6.8, SQlite - 3.33.0
System 2 Specifications: CentOS 6, Python - 3.6.9, SQlite - 3.6.20
```
Both the bots are trained on the same set of questions and answers saved in a .yml file. 

However I get the correct answers for the bot running on Windows and completely wrong answers for the bot running on CentOS. 

What is the reason for this? I also want to update SQlite on CentOS but I can't, please refer to my question on SO [here](url)https://stackoverflow.com/questions/64041937/problem-upgrading-sqlite3-version-on-centos-for-python

**Comment by Siddikulus** [comment]
```
def chatbot(input_string):
    chatbot = ChatBot('Privilige', response_selection_method=get_random_response, storage_adapter='chatterbot.storage.SQLStorageAdapter',logic_adapters=[ 
            'chatterbot.logic.MathematicalEvaluation',
        {
                "import_path": "chatterbot.logic.BestMatch",
                "statement_comparison_function":
    "chatterbot.comparisons.levenshtein_distance",
                'threshold' : 0.50,
                'default_response' : "Sorry. I can not find the exact answer."
            }
        ],
        read_only= True
            )


    # # Create a new trainer for the chatbot
    # trainer = ChatterBotCorpusTrainer(chatbot)

    # # Train the chatbot based on the english corpus
    # trainer.train("chatterbot.corpus.english.Artify_Privilige.Artify_Privilige")

    response = chatbot.get_response(input_string)
    print(response)


if __name__ == '__main__':
    chatbot_artify(sys.argv[1])
```

**Comment by AnAnalogGuy** [comment]
You might want to set 

`logging.basicConfig(level=logging.INFO)`

which will log all the evaluations and the related confidence values to the console. Like this you can check if both systems are actually doing the same calculations (potentially not) and try to spot the difference. This might give you an idea where the difference might come from.

**Comment by AnAnalogGuy** [comment]
you might also want to check if you have the same libraries/library versions installed, i.e. nltk.

**Comment by Siddikulus** [comment]
> you might also want to check if you have the same libraries/library versions installed, i.e. nltk.

Thank you very much for your response. This solved the issue, I made sure my dependencies were equally updated on both the systems but completely forgot about nltk.
