### ISSUE TITLE
Machine learning methods in ChatterBot?

### ISSUE THREAD

**Issue by DataTerminatorX** [gunthercox/ChatterBot#205]
Hi @gunthercox ,
Thx for launching such a great project ! 
But I was wondering which machine learning methods were used for training ChatterBot? I haven't got the answer after reading source codes and docs. Or it seems that ChatterBot is trained by some text matching methods? 
Looking forward to your reply. Thx!

**Comment by gunthercox** [comment]
ChatterBot represents the knowledge it has learned internally as a graph data structure with connections between each statement and it's known responses. The program then uses a logic adapter to apply the response selection algorithm. ChatterBot has a few different selection algorithms built in. One uses NLTK for matching the closeness of word synonyms, another uses Levenshtein distance.

**Comment by DataTerminatorX** [comment]
Thx for ur reply. I'm much clear now :-)
I'll try ChatterBot myself. Hope further discussion with you :-)
