### ISSUE TITLE
dedicated bot for each client

### ISSUE THREAD

**Issue by adamcohenhillel** [gunthercox/ChatterBot#2054]
I'm trying to create dedicated bot for each of my clients, meaning: each client on my website will have his own instance of chatterbot that was trained on different data.
The only solution that I came up with was to save for each one of them their own database file, but It seems to me a wrong way to do so..
Is there a better way to load different chatbots chatbot?

Thanks

**Comment by AnAnalogGuy** [comment]
Why do you think separating different data into different database files is a wrong way?
