### ISSUE TITLE
How to Handle unknown words and say "I Dont Understand"

### ISSUE THREAD

**Issue by olahivepriyanka** [gunthercox/ChatterBot#206]
when some unknown sentence occurs how to say  "I Dont Understand, Can you be more Specific?"
any method?? code please :)

**Comment by Bomme** [comment]
Maybe the discussion in issue #204 could get you started?

**Comment by futetest** [comment]
There's no way to do that as of now. Even I wanted something similar but couldn't achieve it. The "no_knowledge_adapter.py" wasn't of much use either for me.

Anyways, if you figure it out, let me know as well.

**Comment by LucasZielke** [comment]
The logics of this program do not permit it to not find a response since it is trying to find the closest possible match to the input. A method for achieving what you are attempting might be to change from using this sort of logics to more of an AIML style program (pyAIML is a good library if you are looking to be programming it in python).

**Comment by gunthercox** [comment]
@LucasZielke That is partially correct, part of the process of selecting a response is trying to find the closest possible match to the input, but there is also another step that involves choosing a response from the selection of closest matching known inputs.

**Comment by gunthercox** [comment]
Hi everyone. Here is a solution that may work for you. All you need to do is create a file containing the following logic adapter and add it to your chat bot setup. You will likely need to customize the output based on your needs, but I think this should be a pretty good basis for everyone to work from.

```python
# -*- coding: utf-8 -*-
from chatterbot.adapters.logic.base_match import BaseMatchAdapter
from fuzzywuzzy import fuzz


class TheIDontKnowAdapter(BaseMatchAdapter):
    """
    This adapter checks if a closely matching response is known.
    """

    def get(self, input_statement):
        """
        Takes a statement string and a list of statement strings.
        Returns the closest matching statement from the list.
        """
        statement_list = self.context.storage.get_response_statements()

        default_response = Statement("I don't understand.")

        # Return the default response if there is no data in the database
        if not statement_list:
                return 1, default_response

        confidence = -1
        closest_match = input_statement

        # Find the closest matching known statement
        for statement in statement_list:
            ratio = fuzz.ratio(input_statement.text, statement.text)

            if ratio > confidence:
                confidence = ratio
                closest_match = statement

        # Return the default response if a close match cannot be found
        if confidence < 10:
            return 1, default_response

        return 0, closest_match
```
