### ISSUE TITLE
What is "context"?

### ISSUE THREAD

**Issue by futetest** [gunthercox/ChatterBot#207]
Hi @gunthercox 
I see "context" in the code, but I don't understand it well. Can you please tell me more about it.

**Comment by gunthercox** [comment]
This variable is an object passed to each type of adapter. It allows each adapter to access other adapters. There are cases where it may be beneficial for logic adapters to have direct access to the storage adapter for example.

**Comment by gunthercox** [comment]
I've added updated documentation to cover this. http://chatterbot.readthedocs.io/en/latest/adapters/index.html#context

Feel free to reopen this ticket or submit a pull request if more information is needed.
