### ISSUE TITLE
How to create my own logic adapter?

### ISSUE THREAD

**Issue by kontrybutor** [gunthercox/ChatterBot#208]
Hi @gunthercox  
As the title says, I am wondering how to create my own logic adapter. I know how the default adapters like TimeLogic, MathematicalEvalutaiion work. They are installed in my usr/lib/python~ directory and the only import is "from chatterbot import ChatBot". Variable logic_adapters contains  "chatterbot.adapters.logic.MathematicalEvaluation" for example. 
In my project directory I've tried to create a new module with class "MyLogicAdapter", just like in the documentation. What should I add to the variable logic_adapters? I've trying to add just "MyLogicAdapter" but my IDE throws an error "ValueError: Empty module name"

**Comment by gunthercox** [comment]
It sounds like you need to include the file name in the path as well. For example, if your adapter class `MyLogicAdapter` is in a file named `my_logic_adapter.py` then you would want the string passed to the chat bot's list of adapters to look like `"my_logic_adapter.MyLogicAdapter"`. This string is essentially just an python import path. The class gets split off the end of the string and imported.
