### ISSUE TITLE
can chatterbot learn any persian concept?

### ISSUE THREAD

**Issue by mrmrn** [gunthercox/ChatterBot#210]
Does chatterbot maked bots understand the meaning and concept of non English sentences or this are just some marked phrases?
I mean how this machine learning and AI works in chatterbot?

**Comment by gunthercox** [comment]
ChatterBot is designed to be language independent so bots can be created that can communicate using any language. You can either train your chat bot using pre-recorded data, or it can learn to speak as you communicate with it.
