### ISSUE TITLE
[E941] Can't find model 'en'

### ISSUE THREAD

**Issue by ZodiacRed** [gunthercox/ChatterBot#2111]
Error:

OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0. To load the model, use its full name instead:
nlp = spacy.load("en_core_web_sm")
For more details on the available models, see the models directory: https://spacy.io/models. If you want to create a blank model, use spacy.blank: nlp = spacy.blank("en")

Im using Python 3.7.9

**Comment by monosans** [comment]
This PR solved the issue for me.
https://github.com/gunthercox/ChatterBot/pull/2094/commits/5b0381fa9ab40da980b6a633eff0c9ca61d5bd39
