### ISSUE TITLE
OSError: [E941] Can't find model 'en'.

### ISSUE THREAD

**Issue by quiktea** [gunthercox/ChatterBot#2139]
Hey! I'm working with the ChatterBot library in Python 3.8 - I have successfully installed Chatterbot and spacy, however, I am getting this error when trying to run the bot:

```
OSError: [E941] Can't find model 'en'. It looks like you're trying to load a model from a shortcut, which is deprecated as of spaCy v3.0. To load the model, use its full name instead:

nlp = spacy.load("en_core_web_sm")

For more details on the available models, see the models directory: https://spacy.io/models. If you want to create a blank model, use spacy.blank: nlp = spacy.blank("en")
```

**Comment by matheusfillipe** [comment]
This fixes it: https://stackoverflow.com/a/66087946/5731541 
Basically go to `site-packages/chatterbot/tagging.py` and on line 26 replace:
``` 
self.nlp = spacy.load(self.language.ISO_639_1.lower())
```

With:

``` 
if self.language.ISO_639_1.lower() == 'en':
    self.nlp = spacy.load('en_core_web_sm')
else:
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
```

It is a workaround. Someone could create a pull request for this if this is a proper fix, dunno if it already exists.

**Comment by quiktea** [comment]
Thank you very much
