### ISSUE TITLE
Chinese Training using List Trainer

### ISSUE THREAD

**Issue by Nykho** [gunthercox/ChatterBot#215]
Hi. I'm having problems trying to use the ChatterBot to talk to me in Chinese.

In the terminal I get:

`/usr/local/lib/python2.7/site-packages/chatterbot/conversation/statement.py:46: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if response.text == self.in_response_to[index].text:
Type something to begin...`

for this first case (talk to english and respond in chinese works ok):

Hello
你好。 你好吗?

but it doesn't work for talking in chinese to the bot.

我很好你呢
我很好你呢

I also get this error:

`/usr/local/lib/python2.7/site-packages/chatterbot/adapters/logic/closest_match.py:35: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if input_statement.text in text_of_all_statements:`

The code of what I'm using:

```python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
from chatterbot.training.trainers import ListTrainer

chatterbot = ChatBot("Terminal",
    storage_adapter="chatterbot.adapters.storage.MongoDatabaseAdapter",
    logic_adapters=[
        "chatterbot.adapters.logic.ClosestMatchAdapter"
    ],
    input_adapter="chatterbot.adapters.input.TerminalAdapter",
    output_adapter="chatterbot.adapters.output.TerminalAdapter",
    database="chatterbot-database"
)

chatterbot.set_trainer(ListTrainer)

chatterbot.train([
    "你好。 你好吗?",
    "Hello",
])

chatterbot.train([
    "我很好太感谢",
    "我很好你呢",
])

print("Type something to begin...")

while True:
    try:
        bot_input = chatterbot.get_response(None)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

Thanks!

**Comment by mbarisa** [comment]
Hi, I made a pull request you might want to check out, I think that is same issue I encountered with Croatian language, so I just added utf-8 support for corpus. I tried ListTrainer with your dataset, and it seems to work fine. 

You want to check this commit [https://github.com/gunthercox/ChatterBot/pull/216/commits/9ea48eac3954fd818947dbb0742d1d545b4f8c08](here)

**Comment by nick198205** [comment]
I have the same problem with @Nykho ,and I have merged the commit from @mbarisa said,but it still didn't work for me !

**Comment by gunthercox** [comment]
Hi @Nykho, I've been able to confirm this issue on my end. I will attempt to issue a patch as soon as I can.

**Comment by Nykho** [comment]
Thanks @gunthercox!

**Comment by manhcuogntin4** [comment]
Hi, I met this issue for unicode in python 3.5 in the training phase :
File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Hope for help !
