### ISSUE TITLE
some bug fixes

### ISSUE THREAD

**Issue by PaarthBatra** [gunthercox/ChatterBot#22]
I am still in the process of reading the chatterbot and gettting more familiar slowly . 

I found some bugs like in conversations.py 's Statement class function detect_sentiment 

```
def detect_sentiment():
        """
        A property that describes hows the 
        """

        if self.sentiment:
            return self.sentiment

        # Evaluate the sentiment of the statement
        #else:
```

not sure if we are using this function anywhere however it still miss a self i.e. correct one should be 

```
def detect_sentiment(self):
        """
        A property that describes hows the 
        """

        if self.sentiment:
            return self.sentiment

        # Evaluate the sentiment of the statement
        #else:
```

similarly something wrong in 

```
def get_sentiment(name):
        """
        Returns the average sentiment for a single user throughout a
        conversation.
        """
        sentiment = []
        for statement in self:
            if statement.name == name:
                sentiment.append(statement)

        return "" #TODO: return the average sentiment
```

can i do a change in it and add it in a new brach or is it best to raise a similar issue here

**Comment by gunthercox** [comment]
These methods aren't being used. Feel free to create a branch and make the changes as needed.
