### ISSUE TITLE
Python-Levenstein required

### ISSUE THREAD

**Issue by nuzhdov** [gunthercox/ChatterBot#221]
`/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
`
I have read issues with Levenstein. This error often appears on Windows, as I understood. But I use Linux Mint 17.1 . And I have this error too. Can you help with it?

**Comment by kevin-brown** [comment]
This appears to be a warning, not an error. So I don't think it's _required_, it's just _highly recommended_.

**Comment by gunthercox** [comment]
@kevin-brown is correct.

If you're goal is to remove the warning, your options are
1. Install the python-Levenshtein package with pip.
2. Silence `UserWarning` level warnings when running your code.

**Comment by nuzhdov** [comment]
Ok. Thank you. Python-Levenshtein can't be installed. Got an error with it, too. I will ignore it until it's not critical. Oh try to fix this later.)
