### ISSUE TITLE
Why does the json database store previous statements as values?

### ISSUE THREAD

**Issue by Matgek** [gunthercox/ChatterBot#226]
Hi,
I'm a freshman to chatterbot. I have read the code and docs. It's really a great job. 

But I have a question. Why does the json database store a statement as a key, and its previous statement as the value (`in_response_to.text`)? I think an alternative way is to store a statement's responses as  the value. To be more specific, I want to show an example.

A conversation:
```
[
     "How are you doing?"
     "I am doing well, how about you?"
     "I am also good."
]
```

Existing json data storage:
```
{
     "text": "I am doing well, how about you?"
     “in_response_to”: [{"text": "How are you doing?" }]
}
```

An alternative way:
```
{
     "text": "I am doing well, how about you?"
     “responses”: [{"text": "I am also good. " }]
}
```

I ask this question because I find, when the training scale is 2000+ , the response time for a query statement is too long.  I'm curious whether it might be due to the data storage structure. Using existing data storage, each time to get a response, all statements with responses are filtered out (`StorageAdapter.get_response_statements()`) and a statement closest to the query statement is matched. Then, again, we have to traverse all statements' in_response_to value and find the closest statement's response. So, there are three procedures to traverse all statements in the json database. 
In contrast, if we adopt the other storage method, we only traverse all statements to find a statement closest to the query statement, and give its response. I think this way might reduce the response time. 

I wonder whether I understand the workflow correctly. Or, are there any specific reasons we have to use the existing data storage structure?

Thanks.

**Comment by gunthercox** [comment]
Hi, @Matgek your logic seems valid.. I will set up some test cases to try to benchmark any changes in performance by reversing how the statements are stored.

**Comment by Matgek** [comment]
Thanks.
