### ISSUE TITLE
Number of words matched in closest_meaning

### ISSUE THREAD

**Issue by futetest** [gunthercox/ChatterBot#227]
HI @gunthercox 

how do I know how many words did it actually match of the input with the statement? i tried to look into the closest_meaning but couldn't find with how many word is it matching.

**Comment by gunthercox** [comment]
Hi, @futetest. The [ClosestMeaningAdapter](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/adapters/logic/closest_meaning.py) compare all the words.

![image](https://cloud.githubusercontent.com/assets/2030578/17620135/2ce1b046-6058-11e6-809b-31c6f89933fa.png)

To explain a bit further, it selects the highest value combination of matching tokenized versions of the words in each pair being compared. To do this, it first creates a list of the tokenized words for both statements being compared using NLTK's `get_tokens` function. It then produces what is essentially a matrix of each possible combination of the ordering of the tokens in both lists using Pythons built in `itertools.product` function.

> Note, that the reason that the order of the words is ignored is because the goal of this adapter is to compare the meaning of each word, so order was deemed an invalid heuristic.

The adapter selects and returns the statement with the highest matching token list comparison to the input statements.
