### ISSUE TITLE
Pip install not working.

### ISSUE THREAD

**Issue by MockyIsI** [gunthercox/ChatterBot#2293]
When I try and install with pip, it throws an error message:
        × Running setup.py install for preshed did not run successfully.
        │ exit code: 1
        ╰─> [13 lines of output]
            /Users/family/opt/anaconda3/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            running install
            /Users/family/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_py
            running build_ext
            building 'preshed.maps' extension
            clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/family/opt/anaconda3/include -arch x86_64 -I/Users/family/opt/anaconda3/include -fPIC -O2 -isystem /Users/family/opt/anaconda3/include -arch x86_64 -I/Users/family/opt/anaconda3/include/python3.9 -I/Users/family/opt/anaconda3/include/python3.9 -c preshed/maps.cpp -o build/temp.macosx-10.9-x86_64-cpython-39/preshed/maps.o -O3 -Wno-strict-prototypes -Wno-unused-function
            clang: error: no such file or directory: 'preshed/maps.cpp'
            clang: error: no input files
            error: command '/usr/bin/clang' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> preshed
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(base) family@iMac preshed-master % 

Is there any way to make it work?

**Comment by JavaRockstar** [comment]
Getting stuck on Installing build dependencies ... \
