### ISSUE TITLE
Hi, There is an issue with .text in the code

### ISSUE THREAD

**Issue by woandms** [gunthercox/ChatterBot#2302]
![image](https://user-images.githubusercontent.com/42778957/226905879-2fb68d11-6428-469c-91e5-767b98f3cd26.png)

**Comment by ilikeapple10** [comment]
I can't really determine much without code but I would guess that you need to parse your input_statement to a string if you haven't already

**Comment by woandms** [comment]
Found the issue with the library itself being not compatible with python version
