### ISSUE TITLE
preshed conflict with the backend dependencies wheel

### ISSUE THREAD

**Issue by Hugo-magalhaes** [gunthercox/ChatterBot#2310]
I tried to install the latest version of chatterbot and then i got these error message:

    ERROR: Some build dependencies for preshed<2.1.0,>=2.0.1 from https://files.pythonhosted.org/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz conflict with the backend dependencies: wheel==0.40.0 is incompatible with wheel>=0.32.0,<0.33.0.
      [end of output]

**Comment by rfangzh** [comment]
How did you solve this problem, please?

**Comment by Hugo-magalhaes** [comment]
I can't, that's why I posted the issue. I tried some various things, for
example downgrade Chatterbot, installing dependencies before etc.

Em sex., 19 de mai. de 2023 às 00:24, rfangzh ***@***.***>
escreveu:

**Comment by sonugill** [comment]
** I am getting somehow same type of error plz help to resolve**


 error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Collecting setuptools
        Using cached setuptools-67.8.0-py3-none-any.whl (1.1 MB)
      Collecting wheel<0.33.0,>0.32.0
        Using cached wheel-0.32.3-py2.py3-none-any.whl (21 kB)
      Collecting Cython
        Using cached Cython-0.29.35-py2.py3-none-any.whl (988 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.7-cp311-cp311-win_amd64.whl (28 kB)
      Collecting preshed<2.1.0,>=2.0.1
        Using cached preshed-2.0.1.tar.gz (113 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'

      **_### ERROR: Some build dependencies for preshed<2.1.0,>=2.0.1 from https://files.pythonhosted.org/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz conflict with the backend dependencies: wheel==0.40.0 is incompatible with wheel>=0.32.0,<0.33.0.
      [end of output]_**

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

pip 22.3.1 from C:\Users
(python 3.11)

**Comment by Brayodelight** [comment]
getting the same eror too
  ERROR: Some build dependencies for preshed<2.1.0,>=2.0.1 from https://files.pythonhosted.org/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz conflict with the backend dependencies: wheel==0.40.0 is incompatible with wheel>=0.32.0,<0.33.0.

**Comment by alpharagesadmin** [comment]
@Hugo-magalhaes downgrade wheel version 0.40.0 to 0.33.0. That work for me.

**Comment by Hugo-magalhaes** [comment]
@alpharagesadmin how to do this ? When i tried to downgrade and i got a error saying 'can't found the wheel version'.

**Comment by alpharagesadmin** [comment]
@Hugo-magalhaes I have run the following command. `python3 -m pip wheel==0.33.0`
**Note** I'm using MAC and Python 3.11. ChatterBot Isn't compatible with 3.11

**Comment by jamesbuch** [comment]
Did anyone resolve this issue?  I can't seem to downgrade wheel either, after I install it as wheel==0.33.0 preshed still says it is using backend (whatever that means?) wheel 0.41.3.

ERROR: Some build dependencies for preshed==2.0.1 from https://files.pythonhosted.org/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz conflict with the backend dependencies: wheel==0.41.3 is incompatible with wheel>=0.32.0,<0.33.0.

is the problem trying to install chatterbox.

**Comment by Rasool-P** [comment]
This simple command helped me install the latest version of wheel:

`pip install --upgrade wheel`



Thanks to this comment
#https://github.com/gunthercox/ChatterBot/issues/2317#issuecomment-1671342592
