### ISSUE TITLE
ChatterBotCorpusTraining error

### ISSUE THREAD

**Issue by brohjoe** [gunthercox/ChatterBot#233]
Hello,
I'm testing the ChatterBotCorpusTraining functionality with the 'greetings' corpus and getting errors.  I'm not sure if I understand fully the concept of machine learning using this library and I can't find enough information to help.  I'm using the code from the docs.   If I use "None" as a parameter as listed in the docs:
   `bot_input = bot.get_response(None)` 
I get an error stating: chatterbot.adapters.input.variable_input_type_adapter.UnrecognizedInputFormatException: "The type <class 'NoneType'> is not recognized as a valid input type."

If I enter "text" as a parameter, I get the bot repeating the same response.  Here is the code:

````python
from chatterbot import ChatBot
from chatterbot.training.trainers import ChatterBotCorpusTrainer

# create a new instance of a chatbot
bot = ChatBot("greetings",
              storage_adapter="chatterbot.adapters.storage.JsonDatabaseAdapter",
              logic_adapters=["chatterbot.adapters.logic.ClosestMatchAdapter"],
              input_adapter="chatterbot.adapters.input.VariableInputTypeAdapter",
              output_adapter="chatterbot.adapters.output.OutputFormatAdapter",
              output_format = 'text',
              database="../database.db"
              )

# set up machine learning training

bot.set_trainer(ChatterBotCorpusTrainer)
bot.train("chatterbot.corpus.english.greetings")

print(input('Welcome, I\'m the Response Bot, how are you today?\n'))

while True:
    try:
        bot_input = bot.get_response(None)
        print(bot_input)
    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

Thanks for your help.

**Comment by gunthercox** [comment]
It looks like there is an issue with the example. The `VariableInputTypeAdapter` expects an input value which is why it is erroring out when give a None value. Want to swap out the input and output adapters you are using with the following:
```python
input_adapter="chatterbot.adapters.input.TerminalAdapter",
output_adapter="chatterbot.adapters.output.TerminalAdapter",
```

**Comment by brohjoe** [comment]
Thanks gunthercox.  Its working now.  Now if I wanted to have an action performed like calling a function, would I need to create an adapter for that, say if I wanted a window opened based on a request?

**Comment by gunthercox** [comment]
Correct, you would want to create an adapter for handling that.
