### ISSUE TITLE
BulkWriteError error when training with Mongo Adapter

### ISSUE THREAD

**Issue by ephillipe** [gunthercox/ChatterBot#238]
Traceback (most recent call last):
  File "/home/local/ALTERDATA/erick.cirrus/Desenvolvimento/web/karoo/scripts/chatterbot/train_terminal_karoo.py", line 75, in <module>
    bot.train(conversacao)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 41, in train
    self.storage.update(statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/storage/mongodb.py", line 148, in update
    self.statements.bulk_write(operations, ordered=False)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 435, in bulk_write
    bulk_api_result = blk.execute(self.write_concern.document)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/bulk.py", line 470, in execute
    return self.execute_command(sock_info, generator, write_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/bulk.py", line 314, in execute_command
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred

**Comment by gunthercox** [comment]
Unfortunately the `BulkWriteError` does not give me enough information to debug this issue. Could you tell me what the content of your `conversacao` variable was?

**Comment by Nixellion** [comment]
I get the same error. I'm feeding bot.train(). Here is my code.

`    def vk_train(self):
        global chatbot
        conversations = []  # list of final conversations

        # first we need to parse vk_comments.txt file
        print("// Reading file")
        with open('vk_comments.txt', 'r', encoding='utf-8') as datafile:
            vk_comments = datafile.read()

        print("// Parsing file")
        vk_dialogues = vk_comments.split("{NEW_CONVERSATION}\n")
        for dialog in vk_dialogues:
            messages = dialog.split("{NEXT}\n")
            filtered_messages = []
            for message in messages:
                if "\n" in message:
                    message = message.replace("\n", "")
                if message != "" and message != " ":
                    filtered_messages.append(message.lower())
            conversations.append(filtered_messages)

        print("// Learning from file")
        for conv in conversations:
            chatbot.train(conv)`

So I have this huge file, which is just a text file where I downloaded... i'm not sure, thousands of facebook (vk.com) comments, and trying to use it to train the bot. I'm splitting the file by tags ({NEW_CONVERSATION} and {NEXT}) into a bunch of lists, and then feed each conversation one by one to the bot.train.

Right now I think that maybe I need to wait between chatbot.train calls... Or somehow change this particular logic, hm..

It works for smaller files though

**Comment by Nixellion** [comment]
` print("// Learning from file.", len(conversations), "conversations")
        conversations_count = len(conversations)
        for i, conv in enumerate(conversations):
            print (i, "out of", conversations_count)
            chatbot.train(conv)
            time.sleep(1)`

Using this code it does this:
```
<...>
69 out of 770
70 out of 770
Traceback (most recent call last):
  File "D:/Projects/Python/HomeAI/homeAI.py", line 278, in run
    self.vk_train()
  File "D:/Projects/Python/HomeAI/homeAI.py", line 336, in vk_train
    chatbot.train(conv)
  File "D:\Projects\Python\HomeAI\chatterbot\trainers.py", line 41, in train
    self.storage.update(statement)
  File "D:\Projects\Python\HomeAI\chatterbot\adapters\storage\mongodb.py", line 148, in update
    self.statements.bulk_write(operations, ordered=False)
  File "C:\Python34\lib\site-packages\pymongo\collection.py", line 435, in bulk_write
    bulk_api_result = blk.execute(self.write_concern.document)
  File "C:\Python34\lib\site-packages\pymongo\bulk.py", line 470, in execute
    return self.execute_command(sock_info, generator, write_concern)
  File "C:\Python34\lib\site-packages\pymongo\bulk.py", line 314, in execute_command
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred
```

And no matter what wait i set, it's always at 70.

Checked what it is, it is just a very long conversation. All other conversations are from 0 to 20-ish phrases. This one is 91. Will try to limit maximum number of phrases in conversation to 25while parsing the file and see how that works.

**Comment by Nixellion** [comment]
Hm, thats weird. It seems that this appears on my windows desktop. but it does not on a Raspberry Pi 3. Either it's something to do with windows\linux, or maybe it's just that PC writes to the database to quickly, and it fails? This would be weird...

**Comment by chenjun0210** [comment]
I've had a similar problem.

Traceback (most recent call last):
  File "/Users/chenjun/git/AI_ChatterBot/chatterBot/examples/terminal_mongo_example.py", line 28, in <module>
    bot.train("chatterbot.corpus.sports")
  File "/Users/chenjun/git/AI_ChatterBot/chatterBot/chatterbot/trainers.py", line 80, in train
    trainer.train(pair)
  File "/Users/chenjun/git/AI_ChatterBot/chatterBot/chatterbot/trainers.py", line 68, in train
    self.storage.update(statement)
  File "/Users/chenjun/git/AI_ChatterBot/chatterBot/chatterbot/adapters/storage/mongodb.py", line 202, in update
    self.statements.bulk_write(operations, ordered=False)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/collection.py", line 435, in bulk_write
    bulk_api_result = blk.execute(self.write_concern.document)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/bulk.py", line 470, in execute
    return self.execute_command(sock_info, generator, write_concern)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pymongo/bulk.py", line 314, in execute_command
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred

**Comment by Nixellion** [comment]
Yeah, ill say it again, that I NEVER saw this issue on Raspberry Pi 3, Raspbian linux os. With exactly same files. It just works there, while on my i7 windows machine it works 100x faster, but throws errors

**Comment by AdolHong** [comment]
I met the same error on my Mac OS....

**Comment by Rileghft** [comment]
I have the same issue
>Traceback (most recent call last):
> File "D:\software\PyCharm 2016.3\helpers\pydev\pydevd.py", line 1596, in <module>
>  globals = debugger.run(setup['file'], None, None, is_module)
> File "D:\software\PyCharm 2016.3\helpers\pydev\pydevd.py", line 974, in run
>   pydev_imports.execfile(file, globals, locals)  # execute the script
> File "D:\software\PyCharm 2016.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>   exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "D:/project/courseCrawler/crawler/test.py", line 141, in <module>
>   cardIDs = mergedDB["%s.courseCard" % name].insert_many(courseCards).inserted_ids
> File "C:\Users\young\Anaconda3\lib\site-packages\pymongo\collection.py", line 684, in insert_many
>   blk.execute(self.write_concern.document)
> File "C:\Users\young\Anaconda3\lib\site-packages\pymongo\bulk.py", line 470, in execute
>   return self.execute_command(sock_info, generator, write_concern)
> File "C:\Users\young\Anaconda3\lib\site-packages\pymongo\bulk.py", line 314, in execute_command
>   raise BulkWriteError(full_result)
>pymongo.errors.BulkWriteError: batch op errors occurred

After tracing function call stack, and then I found that a write error occur at **bulk.py** when calling function  **_do_batched_write_command(...)**. The following error message stored in the variable **result**

>{'writeErrors': [{'code': 13636, 'errmsg': 'file /var/lib/mongodb/course.2 open/create failed in createPrivateMap (look in log for more information)', 'index': 0}], 'n': 0, 'ok': 1}

**Comment by gunthercox** [comment]
I'm closing this ticket off as it hasn't been reported in quite some time and I'm fairly certain it was resolved.

**Comment by medmin** [comment]
Not resolved!

I am having the same problem here.

**Comment by gunthercox** [comment]
@medmin Please note any steps that can be used to recreate the issue. A concise, recreatable set of instructions will make this much easier for either myself or other contributors to fix.

**Comment by medmin** [comment]
@gunthercox  Hi, i have solved the problem, I think.

Sometimes, people do some tests and  insert some documents to the collection. And then, they just simply delete these documents using some management tool, like Robo 3T. 

But, when you insert some more documents, especially when you insert the same date or record or document, you get the DuplicateKeyError, because mongodb somehow has a same objectid in its system. It's just like the difference between "delete" and "truncate" in mysql.

So, you just drop the collection and then do the insert again. No error occurs.

It's the mongodb's problem.

**Comment by Siva-Karthi** [comment]
Try this https://stackoverflow.com/questions/30355790/mongodb-bulk-write-error

**Comment by gunthercox** [comment]
I've removed bulk-write functionality from ChatterBot as a part of the changes in #1391. I'm going to close this ticket off. Feel free to open new tickets if the issue manifests in a new way after the changes.
