### ISSUE TITLE
How to make the chatbot remember?

### ISSUE THREAD

**Issue by sgtcal10** [gunthercox/ChatterBot#24]
Hi i am using your chatbot but it only uses the engrams. Everything i say it does not save it just follows the engrams conversation how do i make it remember the conversation and create a engram so i can train it through talking? Like cleverbot?

**Comment by gunthercox** [comment]
Can you confirm that your responses to chatterbot are being saved and that the flag for logging is set to true? (Logging is enabled by default).

**Comment by gunthercox** [comment]
Looking into this a bit more I realized that there was an issue with common responses not being returned. The frequency at which a statement is received by the chat bot is now taken into consideration when returning responses such that more common statements are returned with precedence. This change was made for #31.
