### ISSUE TITLE
TieBreaking - most_frequent_response

### ISSUE THREAD

**Issue by davizucon** [gunthercox/ChatterBot#254]
Hi,

  If I choose most_frequent_response, chatterbot/adapters/logic/mixins.py:16 pass only one argument, but get_most_frequent_response() expect 3.

Thanks,
Davi

**Comment by slin17** [comment]
Could you elaborate your issue a bit more? If you instantiate a TieBreaking class, and call get_most_frequent_response(), the method expects 2 arguments, not 3. However, I don't see "most_frequent_response" method in the TieBreaking class. Where are you calling it?

**Comment by davizucon** [comment]
Hi, 
Sorry about that, 
I`m setting:
chatbot = ChatBot(
...
tie_breaking_method="most_frequent_response"
...
)
I created a pull request, #256 , see if its ok for you.

Thanks!

**Comment by slin17** [comment]
It's alright. I'm still new to this project, and learning about how this all works.

**Comment by davizucon** [comment]
@slin17,  I`m new too. Great question, IRC or Slack are very straightforward. We should ask to
@gunthercox if there is any.

**Comment by gunthercox** [comment]
This issue was fixed in https://github.com/gunthercox/ChatterBot/pull/268/files, closing this ticket off.

**Comment by slin17** [comment]
Hello @gunthercox , is there like a IRC channel or Slack for this project? 
Thanks.

**Comment by gunthercox** [comment]
Hi @slin17, there is on Gitter: https://gitter.im/chatter_bot/Lobby
