### ISSUE TITLE
ValueError from converstation.py, line 100, need more than 3 values to unpack

### ISSUE THREAD

**Issue by Jay-Parker** [gunthercox/ChatterBot#26]
Never used github, so sorry if this is in the wrong place for this or format. 

Seems that chatterbot is creating converstation files that contain an empty line at the end, which converstation.py tries to read. My fix was just to check the line is not empty:

            # Continue only if the file contains lines
            if lines:
                previous_statement = None
                for line in lines:
                    if line:
                        user, date, text = line

**Comment by gunthercox** [comment]
Thank you, I've made the change.

**Comment by Jay-Parker** [comment]
Wow, that was a quick response! Happy to help.
