### ISSUE TITLE
input statement vs existing statement

### ISSUE THREAD

**Issue by gsingers** [gunthercox/ChatterBot#262]
Not sure if there is a bug or intended, but in chatterbot.py, the following code implies that any extra_data that comes in on a statement that is _also_ on an existing statement loses the extra_data of the input statement.  In my case, I have an input adapter for Slack and I'm adding things like the user id and the channel the question came from, but I also have some training data and the extra info is being dropped.  

https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/chatterbot.py#L136

I think the extra_data should be propagated to the statement.

**Comment by gunthercox** [comment]
I believe this issue has been fully resolved now. Feel fee to reopen it if I missed something.
