### ISSUE TITLE
Deprecated Warning with NLTK

### ISSUE THREAD

**Issue by adryr83** [gunthercox/ChatterBot#270]
Hi,
I'm learning with Python. I installed your beautiful Chatterbot 0.4.6. but there is a big problem wit NLTK module because with Python 3.5.2, chatterbot doesn't work because of there is a Deprecated Warning.
I tried a lot of methods to solve this event:
 **First**
With 'python3 -m pip install -U <library_name>'
**Second**
I downloaded the new module nltk  and then I installed it with command: sudo python setup.py install
**Third**
I tried with the command: 
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In all of this cases, Chatterbot 0.4.6 (new file with title "Test.py"):

from chatterbot.training.trainers import ChatterBotCorpusTrainer

After run, it gives me this message:

Warning (from warnings module):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk-3.2.1-py3.5.egg/nltk/decorators.py", line 59
    regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

Can you help me please? Thanks a lot!

**Comment by gunthercox** [comment]
Hi, could you tell me what version of NLTK you have installed? I'm testing with version 3.2.1 and I'm not seeing this error.
You can check the version you have by running:
```
python -c "import nltk; print nltk.__version__"
```

**Comment by adryr83** [comment]
I have the same: 3.2.1

I don't know why it compares the Deprecated Warning message...

Please, help me.

Il 01/Set/2016 02:08, "Gunther Cox" <notifications@github.com> ha scritto:

Hi, could you tell me what version of NLTK you have installed? I'm testing
with version 3.2.1 and I'm not seeing this error.
You can check the version you have by running:

python -c "import nltk; print nltk.__version__"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gunthercox/ChatterBot/issues/270#issuecomment-243939270>,
or mute the thread

**Comment by adryr83** [comment]
Hi,
I find also this:

https://bugs.python.org/issue27172

It seems a bug, but I don't know how to change the code and where put it.

Adriana

Il 01/Set/2016 02:08, "Gunther Cox" <notifications@github.com> ha scritto:

**Comment by gunthercox** [comment]
Lets try making sure you have all of the latest dependencies for NLTK installed.

First, uninstall `nltk` by running `pip uninstall nltk`.
Next, install nltk with the latest dependencies by running `pip install nltk --upgrade`.

Sometimes installing python packages using `setup.py` can have some issues. Using `pip` is usually a safe bet that the package and all of it's dependencies will be installed properly.

Let me know if this works for you.

**Comment by adryr83** [comment]
I tried you solution. I have to uninstall nltk by running sudo pip uninstall nltk. With pip uninstall nltk, the result was permission denied. Then I installed nltk by running pip install nltk --upgrade.
But the result is the same:
Warning (from warnings module):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/decorators.py", line 59
    regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

With the use of setup.py the message of warning was a bit different because in that there was a details about the version of nltk module. Look:
Warning (from warnings module):
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/**nltk-3.2.1-py3.5.egg**/nltk/decorators.py", line 59
regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead

Thanks for your support.

**Comment by kevin-brown** [comment]
This appears to be an issue in NLTK and not one in Chatterbot. I haven't been able to find a ticket for NLTK that is tracking this issue, so either it was reported and fixed or it was never reported.

**Comment by adryr83** [comment]
I opened a ticket for NLTK because I suspected this problem could be
associated to this module with os x.

I don't have answer yet. I hope someone help me.

Thanks a lot.

Il 02/Set/2016 17:06, "Kevin Brown" <notifications@github.com> ha scritto:

**Comment by adryr83** [comment]
Sorry, I have a question: Is it possibile to use your chatterbot with
Python 3.5.2?

I asked to Michele Simionato (author of both modules decorator.py and
decorators.py) and he answered me in this way:

A deprecation warning is a non-issue, it is just a warning. I will remove
it in future versions of the decorator module, bit it is not urgent at all.

But it isn't just a warning because when I try to run a training test, it
compares only Deprecated Warning message.

Could you help me please?

Thanks

Il 02/Set/2016 17:06, "Kevin Brown" <notifications@github.com> ha scritto:

**Comment by gunthercox** [comment]
Hi @adryr83, Michele Simionato is correct. Warnings in python are just warnings, not errors. Regarding your error, I'm not entirely sure I understand what you mean when you say that it _compares only Deprecated Warning_. It sounds like you are saying that an exception is being compared against something else (which is entirely possible).

Perhaps you could describe the issue you are encountering a bit more and post a snippet of the code your have written so that I can help.

**Comment by gunthercox** [comment]
I'm going to close this as I believe it is a non-issue. Feel free to re-open the ticket if I've missed something.

**Comment by adryr83** [comment]
Ok. Thanks a lot.

In the next days I will restart to work with your chatterbot.

A.

Il 10/Set/2016 14:47, "Gunther Cox" <notifications@github.com> ha scritto:
