### ISSUE TITLE
any automatically update response answers functionality

### ISSUE THREAD

**Issue by PengTedShen** [gunthercox/ChatterBot#271]
Hi @gunthercox 

When there is no such closest match answer for new input, chatter robot used “fuzzywuzzy” or other algorithm method to find one and we as user reviewed this answer as qualified (or as user, we add new answer for this new input) can chatter robot update its Jason db or corpus automatically, by this way, it will save re-run time and update knowledge base.

For improving the accurate of two sentences’ similarity, chatter robot used fuzzywuzzy as cloestmatch and wordnet as closetmeaning match, do you think there are any other method or direction we could try?

**Comment by gunthercox** [comment]
Hi @PengTedShen ChatterBot does automatically update it's knowledge database based on the user's input. This is how the program learns new responses to statements that it can use to communicate with.

Also, I am sure that there are numerous other algorithms out there that could be used to select possible responses. For example, in the past I have looked into adding logic adapters that use markov-chains (https://en.wikipedia.org/wiki/Markov_chain) to generate new candidate responses.

**Comment by PengTedShen** [comment]
thanks. Markov chains is good choice. May I double check with you that there is no good python package available for Markov chains based on my understanding?

**Comment by gunthercox** [comment]
@PengTedShen I am not aware of a generic library for markov chains.
