### ISSUE TITLE
Change format of ChatBot parameters

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#287]
Currently, all of the parameters passed to a chat bot are also passed to each of the chat bot's adapters regardless of whether or not that adapter uses that parameter. This setup also makes it a bit unclear as to which adapter an extra parameter is used for. As ChatterBot grows, there might also be future issues with parameter name conflicts between multiple adapters that expect the same argument.

**Proposed parameter change:**

``` python
ChatBot(
    storage_adapter={
        'class_name': 'my.storage.AdapterClass',
        'database_name': 'my_database'
    },
    logic_adapters=[
       {
           'adapter_class': '.some.adapter.ClassName',
           'api_key': 'my_api_key_string'
        },
        {
           'adapter_class': '.some.adapter.ClassName',
           'api_key': 'my_api_key_string'
       }
    ]
)
```

**Comment by navyad** [comment]
@gunthercox  please have a look at PR, let me know your feedback.
