### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by RafaMedina** [gunthercox/ChatterBot#298]
Is there a way to link a hook function to some phrases?

**Comment by gunthercox** [comment]
Yes, you can create a custom logic adapter that checks for your specific phrases. Check out the documentation and the existing logic adapters. Let me know if you have any questions.

- http://chatterbot.readthedocs.io/en/stable/adapters/logic.html
- http://chatterbot.readthedocs.io/en/stable/adapters/create_a_logic_adapter.html
- https://github.com/gunthercox/ChatterBot/tree/master/chatterbot/adapters/logic

**Comment by RafaMedina** [comment]
Oh! great!

I'm trying to create a kind of decision tree implementing a machine learning conversation, it is where chatterbot shows up.

If you know or have something related it, please let me know it,

Thanks.
