### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by sjpatil** [gunthercox/ChatterBot#306]
Hi,

I just tried basic_example.py and it does not seem to work.  Even if we ignore warnings it does not give any output.

_/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/storage/jsonfile.py:19: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production application environments.
  self.UnsuitableForProductionWarning
How are you?_

Even example django app does not look to give any significant  results.

Any suggestion?

**Comment by EnderShadow** [comment]
I got the same problem

**Comment by gunthercox** [comment]
Hi @sjpatil & @EnderShadow , lets take a look at the code for `basic_example.py`.

The goal of this line is to get a response to the input "How are you?". However, it is important to keep in mind that this chat bot is untrained at this point, so it doesn't know **anything** about the world or how to communicate. The first thing we do to it is say "How are you?" so now, it knows one thing (that phrase). So, the only thing it can do is respond back with that input.

```python
response = chatbot.get_response("How are you?")

print(response)
```

Ok, so let's try something else. If we train the bot, it can learn more about the structure of responses.
Here is another example:

```python
from chatterbot.trainers import ListTrainer

chatbot.set_trainer(ListTrainer)

# Tran the chat bot  with an example conversation
chatbot.train([
    "How are you?",
    "I am good",
])

response = chatbot.get_response("How are you?")

print(response)
```

Now that we have trained the bot with a bit of information, the response it will return when given "How are you" is "I am good".

I hope this helps. Please let me know if you encounter any other issues.

**Comment by rashmipandey201222** [comment]
I have written the code:
from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot

bot = ChatBot('Test')
conv = open('chat.txt', 'r').readlines()
bot.set_trainer(ListTrainer)
bot.train(conv)

while True:
            request = input('You: ')
            response = bot.get_response(request)
	    print('Bot: ', response)
but bot is not responding
error:
List Trainer: [####################] 100%
You: Hi
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    request = input('You: ')
  File "<string>", line 1, in <module>
NameError: name 'Hi' is not defined

though my chats.txt is perfect

**Comment by vkosuri** [comment]
It seems to me the porblems input requests, this reference will give some idea https://stackoverflow.com/a/15190646/358458

My this example will help you https://github.com/gunthercox/ChatterBot/blob/master/examples/terminal_example.py
