### ISSUE TITLE
Is there a way to let bot answer the same question with different answers?

### ISSUE THREAD

**Issue by jltchiu** [gunthercox/ChatterBot#311]
Thanks for this great tool. I was looking at the example program. In the English corpus, there are cases where a same question can have multiple answers

        [
            "Hi, How is it going?",
            "Good"
        ],
        [
            "Hi, How is it going?",
            "Fine"
        ],
        [
            "Hi, How is it going?",
            "Okay"
        ],
        [
            "Hi, How is it going?",
            "Great"
        ],
        [
            "Hi, How is it going?",
            "Could be better."
        ],
        [
            "Hi, How is it going?",
            "Not so great."
        ],

However, when I am actually running the app and tries to ask "Hi How is it going?", the answer is always "Could be better."

I did set the 

filters="chatterbot.filters.RepetitiveResponseFilter",
and
    logic_adapters=[
        "chatterbot.adapters.logic.ClosestMatchAdapter"]

But is there a way to just try to let it randomize the response so it's not always the same answer?

**Comment by gunthercox** [comment]
Yes, this is possible. When you create your chat bot, set `tie_breaking_method="random_response"` like this:

```python
chatbot = ChatBot(
    # ... other parameters ...
    tie_breaking_method="random_response"
)
```

http://chatterbot.readthedocs.io/en/latest/adapters/tie_breaking_method_mixins.html#chatterbot.adapters.logic.mixins.TieBreaking.get_random_response

**Comment by jltchiu** [comment]
Thank you very much, that's exactly what I am looking for.

I didn't find that in the document, maybe I missed that.
