### ISSUE TITLE
Send multiple responses for a single input

### ISSUE THREAD

**Issue by rmdort** [gunthercox/ChatterBot#323]
Is it possible to send multiple response to a conversation? How can i do something like this

````
user: Hello
bot: Hello, hi
bot: Good afternoon
bot: How can I help you today?
````

**Comment by gunthercox** [comment]
This would need a custom logic adapter and possibly a custom output adapter to handle this case. At the moment, the existing ones just handle returning a single response.

**Comment by rmdort** [comment]
Ah ok. I see what you are saying - the logic adapter outputs multiple responses in a certain format and let the output adapter send the response as multiple messages

**Comment by VanRH** [comment]
Another use case for the bot returning two response is:
1. User submits a request asking for a report
2. This kicks off a script (python) to run a report 
3. The Bot replies "Hold on. Let me generate that report."
4. Bot replies again "Here's a link to your report and the tracking number is..."
