### ISSUE TITLE
Django multi app support

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#324]
I am planning to add different department services as Django re usable apps. Will it be possible with this framework?

for exampl 

```
| _ ChatterBot (Parent)
|
| _ _Service 1 (Child)
|
| __ Service 2 (Child)
|
| _ _ et..
```
If so, could you please let me how do this?

**Comment by gunthercox** [comment]
I believe you could achieve this by creating a different chat bot instance for each subservice that you wich to provide. Tanking a look at the existing chat bot API view might provide you with a good idea on how to add this in your own code: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/ext/django_chatterbot/views.py

**Comment by vkosuri** [comment]
@gunthercox thank you very much, I'll try and let you about about development, if possible I'll update documentation also.
