### ISSUE TITLE
Can a logic adapter enrich input statement

### ISSUE THREAD

**Issue by rmdort** [gunthercox/ChatterBot#325]
Is it possible for a logic adapter to modify the input statement before it goes to the next adapter?

Can I use extra_data for this, to store some computed value

**Comment by gunthercox** [comment]
Yes you can, just be sure to save it back to the database.

**Comment by rmdort** [comment]
ok noted. How about the input response?

I want to create a logic adapter that does spell correction and handles the output to the next logic adapter.

**Comment by gunthercox** [comment]
The input statement is passed to the logic adapter so it should definitely
be possible to modify. I may be misunderstanding your question, but you can
modify any attribute of the statement in your logic adapter and it will be
available to the next adapter as long as you save it to the database.

**Comment by rmdort** [comment]
Ah ok. So save the computed value in the databse from one logic adapter and retrieve the saved value in the next logic adapter?

**Comment by gunthercox** [comment]
Correct.

**Comment by Jaivignesh92** [comment]
I need to create chatbot to autocorrect all the spelling mistakes? can you help me?

**Comment by gunthercox** [comment]
I would recommend writing this as a preprocessor instead of a logic
adapter. Logic adapters typically are for generating a response while
preprocessors are specifically designed to alow you to modify the input
that the bot recieves.

http://chatterbot.readthedocs.io/en/stable/preprocessors.html

**Comment by Jaivignesh92** [comment]
Actually My question is User will write a sentence with spelling mistake and Chatbot should response same sentence without spelling mistake.

example:

USER: clmate is gaod
BOT: climate is good

can you help me in this?

**Comment by vkosuri** [comment]
I think this might help you https://github.com/mattalcock/blog/blob/master/2012/12/5/python-spell-checker.rst
