### ISSUE TITLE
Extra data doesn't get passed on to response statement

### ISSUE THREAD

**Issue by rmdort** [gunthercox/ChatterBot#326]
Bot Input
````
input = Statement(None)
input.add_extra_data('user_id', 1)
bot_input = chatbot.get_response(input)
````
In my logic adapter,
````
def process(self, statement):
   print (statement.extra_data) # returns {}
````

I only see this issue when using Terminal output adapter. I guess its the job of the input adapter to persist extra_data

**Comment by rmdort** [comment]
I guess preserving `extra_data` is upto the Input/output adapater. Hipchat and Terminal input adapters modify the input_statement, hence extra_data gets lost. 

So i don't think any action is required. What do u think?

**Comment by gunthercox** [comment]
Check out `test_response_extra_data` in https://github.com/gunthercox/ChatterBot/blob/master/tests/test_chatbot.py#L134. It appears to confirm that the `extra_data` parameter is being saved from the input statement.

**Comment by rmdort** [comment]
Yes. Can close this. 👍 

Its just that in the terminal input adapter

```
def process_input(self, statement)
    return Statement(user_input)
```

In this case the input `statement` object is not being used, instead a new instance of `Statement` is returned. So extra_data is lost in the response of the output adapter. But yes, you are right, the core doesnt alter `extra_data`
