### ISSUE TITLE
Cannot get response using Chinese

### ISSUE THREAD

**Issue by winn** [gunthercox/ChatterBot#329]
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
chinesebot = ChatBot("Training Example") 
chinesebot.set_trainer(ChatterBotCorpusTrainer)  
chinesebot.train("chatterbot.corpus.chinese")
chinesebot.get_response("早上好，你好吗?") 

utf-8
Error 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

decode utf-8
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-22: ordinal not in range(128)

**Comment by rmdort** [comment]
Can you make sure your file encoding is set to utf. Add this to the top of your file

```
# -*- coding: utf-8 -*- 
```

**Comment by rmdort** [comment]
Closing this issue. Feel free to reopen if you still have this problem
