### ISSUE TITLE
When no training data is present, logic adapters are skipped

### ISSUE THREAD

**Issue by rmdort** [gunthercox/ChatterBot#336]
When user provides no training data, chatterbot is currently responding with the input statement. Logic adapter output is completely skipped

I guess its because of no knowledge adapter. Can we remove that and make it optional to the user?

````
# Add required system logic adapter
self.add_adapter('chatterbot.adapters.logic.NoKnowledgeAdapter')
````

**Comment by gunthercox** [comment]
I'm not sure if I understand what the benefit of removing it would be. If a bot hasn't been trained and it hasn't communicated with anyone before, then it has no information about how to respond to input. In this scenario (which should only ever occur once) the only information it has to respond with is the user's input.

**Comment by rmdort** [comment]
ok noted.

The bot i was building didn't need any training data. I was using logic adapters for everything. I have adapters for `greetings`, `q&a` etc. I will probably just add one training data to prevent this error.

**Comment by rmdort** [comment]
#337
