### ISSUE TITLE
couchdb storage adapter

### ISSUE THREAD

**Issue by Gokul299210** [gunthercox/ChatterBot#339]
Hi,

Has anyone come up with a storage adapter for couchdb?

**Comment by davizucon** [comment]
Hi @Gokul299210, CouchDB looks interesting, I would like to test several bots instances feeding up a local instance and using master to master replication.

**Comment by vkosuri** [comment]
See some comments from other PR https://github.com/gunthercox/ChatterBot/pull/770#pullrequestreview-47294006 and https://github.com/gunthercox/ChatterBot/pull/770#issuecomment-312465339

**Comment by davizucon** [comment]
@vkosuri I see, CouchDB is very similar as MongoDB as Key-Document, I really don't know how much users will support or need it. 

I'll wait to go further in this.
