### ISSUE TITLE
Unicode characters issue

### ISSUE THREAD

**Issue by forestli** [gunthercox/ChatterBot#342]
I tried to train with Chinese corpus, and then get response by passing some input(for example, "你好"), but exception was thrown,
=====================================================================
/usr/local/lib/python2.7/site-packages/chatterbot/chatterbot.pyc in get_response(self, input_item)
    149         """
    150         input_statement = self.input.process_input(input_item)
--> 151         self.logger.info(u'Recieved input statement: {}'.format(input_statement.text))
    152
    153         self.storage.generate_base_query(self)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
=======================================================================

My solution is to put some code at the start of chatterbot.py,
======================
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
======================

Then the issue is solved. I'm not use this is a fix or just workarouond.
Help evaluate it please. If this is a fix, then consider to merge it.

best regards,
Forest

**Comment by rmdort** [comment]
Duplicate of #329

**Comment by forestli** [comment]
thanks for quick response. close the case.
