### ISSUE TITLE
Russian math words and russian corpus

### ISSUE THREAD

**Issue by Nixellion** [gunthercox/ChatterBot#345]
Hi, so, I decided to separate my AI's command-logic from chatterbot's adapters. At least this way I can better contribute to making chatterbot a better chatterbot, and not an assistant, while also having full control over my command-logic, where just regular expressions work better than full-blown matching\levenshtein distance\dictionary\etc logic of chatterbot :) anyway...

I'll start making russian corpus for chatterbot. Here's math_words.

And how should I approach adding new stuff to git myself? I'm more used to svn myself, which is much simpler in this case... Should I fork the whole project and somehow make pull requests, or how does it work? I know it's probably written a million times, but maybe there are project specific things... Anyway, here's corpus and I'll go read more about how to work with git : D

```json
{
  "numbers" : {
    "один" : 1,
    "два" : 2,
    "три" : 3,
    "четыре" : 4,
    "пять" : 5,
    "шесть" : 6,
    "семь" : 7,
    "восемь" : 8,
    "девять" : 9,
    "десять" : 10,
    "одинадцать" : 11,
    "двенадцать" : 12,
    "тринадцать" : 13,
    "четырнадцать" : 14,
    "пятнадцать" : 15,
    "шестнадцать" : 16,
    "семнадцать" : 17,
    "восемнадцать" : 18,
    "девятнадцать" : 19,
    "двадцать" : 20,
    "тридцать" : 30,
    "сорок" : 40,
    "пятьдесят" : 50,
    "шестьдесят" : 60,
    "семьдесят" : 70,
    "восемьдесят" : 80,
    "девяносто" : 90
  },
  "words" : {
    "плюс" : "+",
    "разделить" : "/",
    "деленное на" : "/",
    "делить на" : "/",
    "минус" : "-",
    "вычесть" : "-",
    "отнять" : "-",
    "умножить" : "*",
    "умноженное на" : "*",
    "умножить на" : "*",
    "квадрат" : "^ 2",
    "в квадрате" : "^ 2",
    "степень" : "^"
  },
  "scales" : {
    "сто" : "* 100",
    "тысяч" : "* 1000",
    "миллион" : "* 1000000",
    "миллиард" : "* 1000000000",
    "триллион" : "* 1000000000000"
  }
}
```

**Comment by gunthercox** [comment]
Sure, contributing changes with GutHub and git is fairly easy. The basic flow to do this is:

- Fork the project
- Clone your fork locally
- Create a new git branch to start working on your changes
- Make code changes in your local copy
- Commit changes to git and push them up to your clone
- Create a pull request to merge changes from your project to the original

If you need more info on any of these steps feel free to ask, I'm sure there is also a ton of information out on the web on how to do this.

**Comment by Nixellion** [comment]
THanks! Yeah, I did that. Will try to make a basic russian corpus asap.

Aand one more question though, is there a central place for switching language in chatter bot, or will it just define language automatically somehow?

**Comment by gunthercox** [comment]
ChatterBot actually doesn't define a language anywhere. It learns based on user input. As a result, the only time a language is really "set" is when a chat bot is being trained with a particular language.

However, the math words language does have to be set manually (currently). This is done by specifying the parameter `math_words_language='russian'` when initializing the chat bot.

**Comment by Nixellion** [comment]
Thanks, that's what I wanted to know :)
