### ISSUE TITLE
JavaScript ChatterBot

### ISSUE THREAD

**Issue by liberaltech** [gunthercox/ChatterBot#355]
Do you plan on expanding chatterbot to any other languages like JavaScript? It seems like it wouldn't be that difficult since python and JavaScript share a somewhat similar syntax. Would be nice to see this type of bot on node.js, most of the JS bots I've seen so far aren't intelligent bots.

**Comment by gunthercox** [comment]
Hi @liberaltech, I currently don't have any plans to recreate ChatterBot in JavaScript. I would not be opposed to helping out with a JavaScript fork of the project if anyone ever decides to create one, but for the time being most of my efforts are placed on developing and expanding the current codebase.

***

As a side note, I've seen several examples of ChatterBot being used in web APIs which can easily be called from Node applications. I realize this isn't the same, but it could be a way to quickly get ChatterBot's functionality present in a JavaScript app.
