### ISSUE TITLE
A way to communicate additional params to the logic adapter?

### ISSUE THREAD

**Issue by thedp** [gunthercox/ChatterBot#356]
Will there be a way to allow a logic adapter to receive additional information beyond just the statement?

For example, with a Django app I would like to send a custom logic adapter the user information, so the bot will take this into account when constructing a reply.

Thanks.

**Comment by gunthercox** [comment]
Currently no. Getting this set up would require some modifications to the current codebase. With that said, I think this would be a fantastic thing to support. I will look into the required changes in the current Django views that would be needed to allow this.

**Comment by vkosuri** [comment]
As said @gunthercox , You could something like below, by introducing a new param ```CHATTERBOT_ARGS``` dict object

```Django
CHATTERBOT_ARGS = {
    'JIRA' : {
        'server': 'https://jira.atlassian.com',
        'user': None,
        'pass': None,
    }
}
```

You can import these setting in your logic adapter, More information here https://docs.djangoproject.com/en/dev/topics/settings/#using-settings-in-python-code

``` Python
# Import CHATTERBOT_ARGS from django.conf  settings
from django.conf import settings
class JiraLogicAdapter(LogicAdapter):
    """
    A logic adapter that returns information regarding the JIRA and
    is returned, but additional features are planned in the future.
    """

    def __init__(self, **kwargs):
        super(JiraLogicAdapter, self).__init__(**kwargs)

        self.tagger = POSTagger()
        jira_params = settings.CHATTERBOT_ARGS['JIRA']
        print jira_params
        self.jira = JIRA(server=jira_params['server'])
   }

```

**Comment by gunthercox** [comment]
@thedp I've made changes in #374 that now allow data to be passed with the statement to the django view using the already existing `extra_data` attribute supported by `Statement` objects.
