### ISSUE TITLE
identify logic adapter using prefix

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#357]
I think most of the chatbots are doing identifying their logic adapter using specific keywords

For exmaple

```
CHATTERBOT = {
    'name': 'test',
    'logic_adapters': [
        'chatterbot.adapters.logic.TimeLogicAdapter',
        'chatterbot.adapters.logic.MathematicalEvaluation',
        'chatterbot_jira.JiraLogicAdapter'
    ]
}
```

I can call logic adapter from chatterbot is something like below 

```
/time what is current time
/time how many seconds in a minute
/math 2+2
/jira search xx-1234
```

**Comment by vkosuri** [comment]
The workaround i am doing

```Python
if re.search(r'^/jira', user_input):
```

**Comment by gunthercox** [comment]
I like what this idea is trying to accomplish, unfortunately I think it might be going slightly against what ChatterBot aims to accomplish. This seems more like a command line application than an interactive conversation.

The goal for ChatterBot is to understand the user's input and then respond appropriately. If there is any opportunities to improve it's ability to answer questions and respond to input I will be happy to execute the necessary changes. However, I don't think specifying the logic adapter can be supported in the project's core.

**Comment by rmdort** [comment]
Agree. Why cant your logic adapter handle this? For example

In your `chatterbot_jira.JiraLogicAdapter` 

````
def can_process (self, statement):
    return re.match(r'^/jira', statement)
````
