### ISSUE TITLE
reponse based previous statements 

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#358]
Is there a way chatterbot can respond previous statements for example, In the below example i am referencing jira xx-1234 only first time.

```
Statement: /jira what is the status of xx-1234
Response: It's in retest
Statement: /jira can i get latest comments?
Response: X Said It should be fixed by next month
```

Few ideas i am not sure will it work or not

Maintain lookup table for statements if user always referencing a particuler thing, This might be slow down process, but it's worth to maintain good conversation with bot.

Any thoughts/suggestions?

**Comment by gunthercox** [comment]
In this case, what if you modified your logic adapter to have a variable like `self.last_ticket_referenced`. Then, if the input contains the desired trigger phrase, `self.last_ticket_referenced` is updated to match. Perhaps something like this:

```python
class JiraLogicAdapter(LogicAdapter):

    def __init__(self, **kwargs):
        super(JiraLogicAdapter, self).__init__(**kwargs)

        self.last_ticket_referenced = ""

    def can_process (self, statement):
        is_match = re.match(r'^/jira', statement.text)

        if is_match:
            self.last_ticket_referenced = # Insert code to get ticket id from text here

        return is_match 
```

This will allow the logic adapter that handles jira related input to keep track of the last ticket that was mentioned by the user.

**Comment by rmdort** [comment]
@gunthercox This wont work if multiple users are asking for the ticket status, because last_ticket_referenced will change (considering that there is only a single chatbot instance)

You will have to spawn multiple chatbots or use mongo DB to store these values

**Comment by vkosuri** [comment]
@rmdort agreed with you, If i use mongo DB how do i handle this situation? could you provide a example scenario?

**Comment by rmdort** [comment]
I usually have a Users class which syncs the data with mongo

This might help. PS: I am using websockets, 
https://gist.github.com/rmdort/be125bf5ab04876bf073563dc755ef7d

Maybe there is a better way of doing it. Open to feedback

**Comment by vkosuri** [comment]
I think the same question i was asked here https://github.com/gunthercox/ChatterBot/issues/2

**Comment by vkosuri** [comment]
Closing this issue it is going address in #2
