### ISSUE TITLE
capabilities of chatbot

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#363]
We are adding different logic adapters to a chatbot but end user man not remember all these logic adapter that are installed/added to an chatbot.

By introduce a special keyword like ``!help`` or something it will produce  logic adapters info and a breif description what it does.

Any suggestions/thoughts?

**Comment by rmdort** [comment]
Hmm. Why should an end user know about your logic adapter.

Logic adapters are processed sequentially

````
1. Time
2. Closest match
3. Weather
````

And whichever get the highest confidence score gets selected. In your case you can have a Logic adapter that captures `!help` and generate a custom message.

**Comment by vkosuri** [comment]
Thank you, Assume i am going to provide a complex Django chat bot that include many customer relations, internal operations, employee related information, other rest operations and etc.,

Here we have different types end users are going use same single chatbot. End user don't know what capabilities or services that chatbot is providing to him this gives customer a bad relation.

We should tell what are the services/capabilities we are going to provide with some keyword ``help``. Then user can easily understood he/she can easily choose what is related to him.

**Comment by rmdort** [comment]
Exactly. Have a logic adapter to do this

````
def can_process(self, statement):
    return statement.text == 'help'

def process(self, statement):
    return 1, Statement('Hey user, Here\'s how you can use my chatbot. Ask me anything')

**Comment by gunthercox** [comment]
I'm going to close this ticket as I believe @rmdort has provided a good solution.

**Comment by vkosuri** [comment]
@gunthercox The solution will solve if i have a couple of logic adapters. I am considering a large amount logic adapter are installed on single adapter this solution i have rewrite everything.

Instead if we have base_helper_logic adapter, we can overwrite those methods inside one logic operator.
