### ISSUE TITLE
Multiple knowledge themes

### ISSUE THREAD

**Issue by Nixellion** [gunthercox/ChatterBot#366]
From what I understand, right now all the conversations of the chatbot are added to one database.

But what about 'injecting' and 'removing' certain knowledge?
For example, a chatbot is trained from live conversations with users, but at some point I want to inject into him dialogues from a certain book, to allow him to use answers from that book along with those trained from actual people.

But then at some point I may want to make him forget only that book's dialogues, not the whole db.

Or maybe I want him to talk to one user using only answers from book N, but to another user using answers from book X, but also using conversation training Y for both of them.

Is it currently possible? If not, it may be an interesting feature to think about.

**Comment by alekaizer** [comment]
I don't think it's currently possible to use X,Y,Z dataset based on the user talking.

And for the training, you can write your own trainers and implement your own logic on removing/updating etc...

**Comment by gunthercox** [comment]
Adding information is currently supported through the [training process](http://chatterbot.readthedocs.io/en/latest/training.html), however not to the extent that you describe.

I'm planning to (very soon) introduce a `Conversation` object that allows the chat bot to manage information from individual conversations that it has had or has been trained with. I believe this will provide the functionality you are looking for as it will, among other things, allow statements from those individual conversations to be removed.

For having the bot maintain different conversations, this functionality will be added as a part of #313. My plan is to add the ability for a chat bot to track different chat `sessions` that it is having with different users. These changes are a bit further off at the moment though.

**Comment by Nixellion** [comment]
Thanks, gunthercox, yes, I believe that Conversation object should be just what I need.

**Comment by gunthercox** [comment]
I'm going to close this ticket off as the functionality mentioned is being tracked in #513
