### ISSUE TITLE
Pythonerror when using german umlauts

### ISSUE THREAD

**Issue by ThomasKoscheck** [gunthercox/ChatterBot#371]
Chatterbot gives me a pythonerror when using german umlauts like ä,ü,ö,ß because of wrong encoding

**Comment by gunthercox** [comment]
Do you have a unicode header at the top of your Python file?

```python
# -*- coding: utf-8 -*-
```

**Comment by gunthercox** [comment]
Hi @ThomasKoscheck, I've made some changes to the formatting of the data in the German corpus so that it passes JSON validation tests. Locally I was able to trigger a `UnicodeDecodeError` due to invalid JSON. This may have been related to the issue you encountered.
