### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#372]
@gunthercox any plans adding sessions management to ChatterBot?

**Comment by gunthercox** [comment]
Yes, I briefly mentioned adding support for supporting conversations with multiple different users in https://github.com/gunthercox/ChatterBot/issues/313#issuecomment-250967889, but essentially the way it would be supported is with a form of session management for each conversation _session_ that that the bot is having.

**Comment by vkosuri** [comment]
@gunthercox Thanks, any guidance to implement this feature?

**Comment by gunthercox** [comment]
So far, I was considering changing the `recent_statements` variable to be a dictionary where the keys are unique session ids and the values are the queues holding the most recent conversation for that session. A few of the methods in the `ChatBot` class will have to be modified and a number of tests will need to be modified or created.

One thing I'm still unsure about is what to add for methods to allow the current session to be specified.

**Comment by rmdort** [comment]
Why not add `session_id` property to the `Statement` object?

https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/conversation/statement.py#L12

**Comment by gunthercox** [comment]
@rmdort That might cause a slight issue if the same `Statement` object in the database becomes a part of multiple conversation sessions that users are having with the bot. It would allow session ids to be overwritten by other user's conversations.

**Comment by vkosuri** [comment]
@gunthercox Something might useful https://github.com/robotframework/robotframework/blob/e544484dc80f04a5e3d391673176c355dbe86faf/src/robot/utils/connectioncache.py

Any comments/suggestions

**Comment by gunthercox** [comment]
@vkosuri Looks interesting, in the `ConnectionCache`, what are the _connections_ usually?

**Comment by vkosuri** [comment]
``Robotframework`` is test framework, It caches different test objects for example ``telnet, ssh, requests,etc.``

**Comment by vkosuri** [comment]
@gunthercox any comments?

**Comment by gunthercox** [comment]
Session management for ChatterBot will essentially just be adding support for having conversations with multiple users at the same time.

Right now, the the `ChatBot` class just stores the current conversation.

```
ChatBot -----> Conversation
```

The change that needs to be made is to allow the chat bot to store multiple conversations.

```
            |-----> Conversation 1
            |
ChatBot --> |-----> Conversation 2
            |
            |-----> Conversation 3
```

Right now my thoughts are as follows, feel free to ask questions or add suggestions.

- Each logic adapter only needs access to the one conversation at a time so no changes to logic adapters should be necessary to facilitate these changes.
- The _current_ conversation will need to be specified by passing an additional argument to the `ChatBot.get_response()` method. This additional argument should be a unique identifier that can be used to select conversation and from the chat bot to be passed to the logic adapter.
- There needs to be a method that adds a new conversation and returns the unique identifier to access it.

**Security:** There is a security component to this. My plan is to investigate how other Python frameworks like Django and Flask handle their session security.

**Comment by vyz1194** [comment]
Hey Everyone 

I been working on 0.6.0 version and have added previous context check variable to the response selector
I was under the impression it would not be shared across the sessions But now when we try from multiple systems, the variable is being overwritten by the last user, anyway to avoid this scenario ?
