### ISSUE TITLE
Missing corpus after upgrade: /data/portuguese/compliment_pt-BR.json'

### ISSUE THREAD

**Issue by alekaizer** [gunthercox/ChatterBot#373]
I just upgrade the module to have the fix on **nltk_loop** and there's a missing corpus after the upgrade

**Comment by gunthercox** [comment]
It looks like it was renamed to `compliment.corpus.json`: https://github.com/gunthercox/ChatterBot/tree/master/chatterbot/corpus/data/portuguese

**Comment by alekaizer** [comment]
Yes I've seen that, but I thought the *_pt-BR* was made to make diff between pt-PT and pt-BR

And any idea on #367 ? haven't heard from you on that

**Comment by gunthercox** [comment]
Are PT and BR representing different dialects of Portuguese? If they are, removing the suffix was my mistake, in which case I will go back and make the necessary changes.

***

Sorry I haven't responded to #367 yet, I haven't had a chance to look into it. It may be a bug, or it might be the result of the existing algorithms being used. Once I have a chance to walk through what is happening I will respond with some kind of answer.

**Comment by alekaizer** [comment]
BR is Brazilian Portuguese while PT is the "original" one from Portugal, but I'm not an expert of PT so I don't know the differences, but there are some surely.

---------
 
ok about #367

**Comment by gunthercox** [comment]
Ok, I'll create a pull request to separate the dialects (i'm also not an expert of Portuguese).
I think I'm going to keep the directories separate though, so something like:
`/data/portuguese.brazilian/compliment.corpus.json` and `/data/portuguese/somethingelse.corpus.json`

**Comment by gunthercox** [comment]
@alekaizer Actually, after [a bit of research](https://en.wikipedia.org/wiki/Portuguese_dialects), it looks like the two dialects are otherwise indistinguishable. I'm going to leave the directory as-is for now. Even google translate appear to not distinguish between Portuguese and Brazilian Portuguese.
