### ISSUE TITLE
Store response occurrence count in Django models

### ISSUE THREAD

**Issue by maclogan** [gunthercox/ChatterBot#379]
Is it possible to train using the corpus data for a django project running Chatterbot?  I can't seem to find a way to alter the chatbot's settings to accept the language corpus. 

Also, it looks like the database of request/responses created by the example django app is just the response/request phrases rather than storing occurrences.  Is there a way to make that happen as well?

**Comment by gunthercox** [comment]
Lack of a way to train in Django is currently a known issue (https://github.com/gunthercox/ChatterBot/issues/295). I'm in the process of developing a method to add this functionality.

It looks like occurrences currently aren't being tracked by the Django models, I will add a migration to fix this for the next release.

**Comment by gunthercox** [comment]
@maclogan Actually, I was wrong. Occurrence counts are already on the Django models: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/ext/django_chatterbot/models.py
