### ISSUE TITLE
How can I use Ubuntu corpus data?

### ISSUE THREAD

**Issue by phpmind** [gunthercox/ChatterBot#382]
Very impressive project. 
How can i use  ubuntu Dialogue Corpus v1.0.  and v2.0.

http://cs.mcgill.ca/~jpineau/datasets/ubuntu-corpus-1.0/    (Dual Encoder LSTM network will be best for this data)   http://www.wildml.com/2016/04/deep-learning-for-chatbots-part-1-introduction/

Then I have to use node red (https://nodered.org ) to extend and make this  for technical  answer machine. 

Thanks for great project.

**Comment by gunthercox** [comment]
This should definitely be possible. I'll have to look into the format of the data in the Ubuntu corpora before I can make a recommendation on how to do this. In the mean time, feel free to take a look at the existing training modules for some ideas: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py
