### ISSUE TITLE
Serialize Chatbot instance

### ISSUE THREAD

**Issue by alekaizer** [gunthercox/ChatterBot#388]
Hi guys, 
I was wondering if anyone runs into the need to serialize a Chatbot instance, like 

Training the bot in background with Celery or Python-rq, then : 

1. store the dump in Redis so the main app can consume it when ready
2. store the dump in Redis so on restart the bot won't need to re-train again

@gunthercox , @vkosuri any idea on that kind of stuffs ? Pickling and storing is my only idea for now, if you guys have another idea it'll be very welcomed

**Comment by vkosuri** [comment]
@alekaizer I'll prefer celery and Redis option. By curiosity, could you please explain your usecase of this feature?

**Comment by alekaizer** [comment]
@vkosuri  I just moved from Celery to Django-rq to have as the processes are not that heavy I just need the async execution

For the use case, here it's:

1. When an user create a bot, and want to test it, the first interaction trigger the bot's training, which can take some times, so the user is left on wait

2. Now let's say the app crash or I reboot the app, and some bots are already running, so next time an user make interaction, the bot will need to retrain again leaving user on wait because during the reboot the queue have been cleared

Solutions:

1. For the first use case, I can train the bot during the creation process, that's what I am actually writing :)
2. For this one, that's where I need to store the bot actual training so on reboot, I can just loads the dumps and put them back to the bots queue like nothing happened

Hope this time I was clear :)

**Comment by gunthercox** [comment]
Hi @alekaizer, I think I might be able to provide a few suggestions. When an instance of the `ChatBot` class is trained, all of the knowledge it learns get's written to it's database. Each `ChatBot`, by default, is actually mostly stateless, the only exception being it's `recent_statements` attribute that stores the current conversation that the user is having with the bot.

What database are you using for your chat bots?

I'm wondering if instead of serializing the entire chat bot, if it would be simpler to specify a different storage location for each user's bot's data..

**Comment by alekaizer** [comment]
hi @gunthercox, I'm using MongoDb, and I've made a custom storage adapter to add bot_id in statements so each statements knows which bot it belongs to.

and I think my problem may come from the fact that every time I launch the bot training.
And if I understand what you just said, I only need to train the bot, once, as long as the DB is populated I don't need to retrain the same data, I should train only new entries, right ?

**Comment by gunthercox** [comment]
If the new bots are using the same database there is no need to train them. Otherwise, if it is an empty database, training is definitely recommended.

**Comment by alekaizer** [comment]
Great, I'll add a **trained** field on the model then to the object to avoid re-training !

Thank you @gunthercox
