### ISSUE TITLE
Pip install not finding 'requirements.txt'

### ISSUE THREAD

**Issue by asya-bergal** [gunthercox/ChatterBot#40]
I'm getting the error "No such file or directory: 'requirements.txt'" when running `pip install chatterbot`. I think this might be because you don't include 'requirements.txt' in your `MANIFEST.in` file.

**Comment by gunthercox** [comment]
Hi @asya-bergal, thank you. Including `requirements.txt` in the manifest fixed this problem. I've released the latest version of ChatterBot (0.2.0) which includes this fix.
