### ISSUE TITLE
python manage.py train

### ISSUE THREAD

**Issue by maclogan** [gunthercox/ChatterBot#402]
I noticed the update allowing for training from external corpora, updated my chatterbot install and pulled the newest version of chatterbot, but when I try to train the chatbot by running the command `python manage.py train` as instructed in docs/django/training.rst, I just get the error `Unknown command: 'train'`.  Is there any additional step I am missing?

**Comment by maclogan** [comment]
Sorry, when reinstalling the new Chatterbot, I forgot to run setup.py.  Issue is resolved now.

**Comment by gunthercox** [comment]
Awesome, glad this got resolved.
