### ISSUE TITLE
Breaking the While loop in Spyder console

### ISSUE THREAD

**Issue by graylu21** [gunthercox/ChatterBot#404]
Hey, im sure this is a noob issue but your example in the docs ends with:

     # The following loop will execute each time the user enters input
     while True:
         try:
             # We pass None to this method because the parameter
             # is not used by the TerminalAdapter
             bot_input = bot.get_response(None)

         # Press ctrl-c or ctrl-d on the keyboard to exit
         except (KeyboardInterrupt, EOFError, SystemExit):
             break

But when i am running my bot in Spyder, i cant break the loop with the keyboard, and i am not familiar with the other functions.

How can i get the loop to break if i input a specific string or input? Like Exit Conversation.

**Comment by gunthercox** [comment]
Hi @graylu21, would removing the try/except block and setting your own termination condition work for you? For example, you could do something like:

```python
 while my_condition:
     bot_input = bot.get_response(None)
```

**Comment by graylu21** [comment]
Yes, but im not sure how set a condition based on something i type to the bot.

**Comment by gunthercox** [comment]
How are you using ChatterBot in Spyder (I'm not very familiar with Spyder)? Maybe I can help figure out a solution based on your setup.

**Comment by graylu21** [comment]
I am running Python 3.5 with Anaconda which comes with a bunch of packages, and Spyder. And i just copy and pasted the Example in your docs. The conversation runs in an IPython console inside the Spyder window, i type and press Enter and the response pops up underneath. I just cant get the loop to stop without closing the console.

**Comment by graylu21** [comment]
And while i have your attention, im am wanting to program a GUI to run my bot it. Like, run the .py file, it pops up a chat window, and i chat with my bot through that window. Do you have any suggestions on the GUI package to use? Like Tkinter or PyQt, or others? Know of any code for a chat window already developed?

**Comment by gunthercox** [comment]
For a GUI example, there is one using Tkinter in the examples directory: https://github.com/gunthercox/ChatterBot/blob/master/examples/tkinter_gui.py

**Comment by gunthercox** [comment]
I'm looking into possible solution. According to a few sources online you should be able to exit a process running in a Spyder console by pressing `ctrl c`.

Another source stated that you can press `I` _twice_ to interrupt the kernel (http://stackoverflow.com/a/38229513/1547223).

Let me know if either of these work for you?

**Comment by graylu21** [comment]
They did not. On the leftside of my Spyder window is the notebook housing my code. On the right i have an 'object inspector' at the top and the IPython console at the bottom. 

When i run your example, the console tells me to download levenshein and stuff, then prints Type something to begin... and my dialouge with the bot starts. But no matter if my crusor is in the console, notebook, or inspector, preasing I, shift I, ctrl c, ctrl c twice, or ctrl d, i can't get the conversation to quit and the console to listen for the next command, without closing the console window.

So i would like to break the loop in the conversation, by a word or phrase. But I'm not sure what the user input is called in your package.

**Comment by graylu21** [comment]
But the GUI link you sent me was perfect! That is exactly what I was looking for! Thank you so much!

**Comment by gunthercox** [comment]
@graylu21 I'm sorry, but I don't think this is a functionality that I can add to ChatterBot. I'm not very familiar with the iPython ecosystem and I can't make a recommendation on how to do this. I've looked into the possibility that other Python frameworks that typically run in a loop might handle this (Django or Flask for example), but I could not find any evidence of other developers attempting this.

I'm open to accepting a pull request if anyone is interested and can figure out a good way to handle this. For now, I'm going to close this ticket because I'm not sure that there is a good way to do this.
