### ISSUE TITLE
python manage.py train

### ISSUE THREAD

**Issue by duicym** [gunthercox/ChatterBot#406]
[root@localhost django_app]# python manage.py train
Unknown command: 'train'
Type 'manage.py help' for usage.
[root@localhost django_app]# python3 manage.py train
Unknown command: 'train'
Type 'manage.py help' for usage.

cannot use this command

**Comment by gunthercox** [comment]
Could you check what version of ChatterBot you have installed?

**Comment by gunthercox** [comment]
If you have version 0.4.12 or lower then you don't have this method available. Right now it is only available if you install ChatterBot from source to get the current version, or if you wait until version 0.4.13 is released.

Feel free to reopen this ticket if I have incorrectly addressed the issue.

**Comment by duicym** [comment]
0.4.12 ,i will get the current version and try it , thx a lot.
