### ISSUE TITLE
Architecture of the project

### ISSUE THREAD

**Issue by gullyy** [gunthercox/ChatterBot#413]
To understand how ChatterBot works, I can go though the code..to understand more easily how it works can we have a high level architecture and a code flow diagram?

**Comment by vkosuri** [comment]
I think you are looking something like this
https://chatterbot.readthedocs.io/en/stable/about.html#process-flow-diagram

**Comment by gunthercox** [comment]
@gullyy I'm going to close this off. Feel free to re-open it if the diagram in the documentation is not what you were looking for or if there are any details of ChatterBot's design that could befit by having another diagram created.
