### ISSUE TITLE
Docs improvement pertaining to input statement learning in the bot

### ISSUE THREAD

**Issue by shank7485** [gunthercox/ChatterBot#427]
I have some docs improvement suggestions pertaining to the learning aspect of the bot.

From the documentation:
An untrained instance of ChatterBot starts off with no knowledge of how to communicate. Each time a user enters a statement, the library saves the text that they entered and the text that the statement was in response to. As ChatterBot receives more input the number of responses that it can reply and the accuracy of each response in relation to the input statement increase. The program selects the closest matching response by searching for the closest matching known statement that matches the input, it then returns the most likely response to that statement based on how frequently each response is issued by the people the bot communicates with.

1. 'An untrained instance of ChatterBot'
Question: Untrained here refers to an empty database.db?

2. 'Each time a user enters a statement, the library saves the text that they entered and the text that the statement was in response to'
Question: Suppose user enters statement: 'Tell me the weather in location'. Bot reponse: 'The weather in location is X degrees'. So here, statement and bot reponse is stored in the database.db file. In the database.db this is stored as:
`
{
  "The weather in location is X degrees": {
    "in_response_to": [
      {
        "text": "Tell me the weather in location",
        "occurrence": 1
      }
    ]
  }
}
`
What is the logic behind occurrence count? This beings me to 3.

3. 'As ChatterBot receives more input the number of responses that it can reply and the accuracy of each response in relation to the input statement increase'
Question: So if more users type in 'What is the weather in location' or 'Weather in location'. The bot response is 'The weather in location is X degrees'. As per the doc, the bot should increase the number of responses it replies back and it should increase the accuracy. Can this learning process be made more elaborate as I can not understand this process when applied to the example above. Also, how does the occurrence count affect here. 

4. 'The program selects the closest matching response by searching for the closest matching known statement that matches the input'
Question: For searching for the closes matching statement, it looks up statements in database.db or corpus json? Need some clarification. 

5. 'it then returns the most likely response to that statement based on how frequently each response is issued by the people the bot communicates with'
Question: So the bot determines the 'most likely response' based on logic adapters used? Applying this and 'frequency of each response' to the weather example above, we have:
Statement 1: Tell me the weather in location
Statement 2: What is the weather in location
Statement 3: Weather in location

We have the answer to Statement 1 in corpus as 'The weather in location is X degrees'. The bot replies the same to the other Statements 2 and 3? Or where does the learning process take place here? Does the bot reply back the Statement 1 as response to Statement 3 after a number of users call the bot similar to Statement 1 as the occurrence count increases eventually? Example: After a number of uses, 

Statement 1: Tell me the weather in location
Bot: The weather in location is X degrees

Statement 2: What is the weather in location
Bot: The weather in location is X degrees (From corpus)  or
Bot: Tell me the weather in location (From learned data)

Please clarify the above example. 

The whole point of this post is to suggest the docs to give a better understanding of the learning process used in the bot's statement/response.

**Comment by gunthercox** [comment]
Hi @shank7485, thank you for opening this ticket. I will make changes to the documentation to hopefully clarify these points.

**Comment by gunthercox** [comment]
I've updated several pages of the documentation to hopefully clarify these questions. Thank you again for asking for clarification. It is very helpful for improving ChatterBot's documentation. Please let me know if there is anything else that can be improved further.
