### ISSUE TITLE
ChatterBot issue on pypy?

### ISSUE THREAD

**Issue by SethDusek** [gunthercox/ChatterBot#43]
I dont know if this is an issue on Pypy only, but this is what happens:

When I start a ChatBot() session and get a response it gives me
IndexError: list index out of range

This does not happen if I use my previous database.db file.

I thought chatbot() creates a database.db file if one does not exist? This does not seem to be happening here...

**Comment by kevin-brown** [comment]
Can you provide the full traceback that is triggering the `IndexError`?

**Comment by gunthercox** [comment]
@SethDusek any word on this?

**Comment by SethDusek** [comment]
I decided to give it a try.
Here's the full log
kamal@vaio ~ $ pypy
Python 2.7.3 (2.2.1+dfsg-1ubuntu0.2, Dec 02 2014, 23:00:55)
[PyPy 2.2.1 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``PyPy is like absurd theater''
>>>> from chatterbot import ChatBot
>>>> t = ChatBot("test")
>>>> t.get_response('Hey')
/usr/local/lib/pypy2.7/dist-packages/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pypy2.7/dist-packages/chatterbot/chatterbot.py", line 97, in get_response
    {"name":user_name, "text": input_text}
  File "/usr/local/lib/pypy2.7/dist-packages/chatterbot/chatterbot.py", line 51, in get_response_data
    match = self.logic.get(data["text"], text_of_all_statements)
  File "/usr/local/lib/pypy2.7/dist-packages/chatterbot/adapters/logic/closest_match.py", line 18, in get
    return process.extract(text, list_of_statements, limit=1)[0][0]
IndexError: list index out of range
>>>>

**Comment by gunthercox** [comment]
I've confirmed this issue. This has been fixed [here](https://github.com/gunthercox/ChatterBot/commit/a234dffb9d74af4d139ad03e8b6cb5b9f062cc4f) and a new test case has been added to ensure that it does not occur again in the future.

These fixes will be available on PyPi in the next release.
