### ISSUE TITLE
ImportError: No module named settings

### ISSUE THREAD

**Issue by loveJasmine** [gunthercox/ChatterBot#436]
rzai@rzai00:~/prj/ykdebug-ChatterBot$ python twitter_training_example.py 
Traceback (most recent call last):
  File "twitter_training_example.py", line 3, in <module>
    from settings import TWITTER
ImportError: No module named settings

**Comment by gunthercox** [comment]
See https://github.com/gunthercox/ChatterBot/issues/437 for my explanation of why there is no `settings.py` file included.

In the case of this example, if you look at the code you should see a comment that provides instructions on how to get set up:

```python
'''
This example demonstrates how you can train your chat bot
using data from Twitter.

To use this example, create a new file called settings.py.
In settings.py define the following:

TWITTER = {
    "CONSUMER_KEY": "my-twitter-consumer-key",
    "CONSUMER_SECRET": "my-twitter-consumer-secret",
    "ACCESS_TOKEN": "my-access-token",
    "ACCESS_TOKEN_SECRET": "my-access-token-secret"
}
'''
```
