### ISSUE TITLE
[ASK] cannot save extra data to database

### ISSUE THREAD

**Issue by bilalbayasut** [gunthercox/ChatterBot#442]
Hi folks, I'm trying to add extra data to each statement by using add_extra method. But when I check in my mongodb , the corresponding statement still does not has any extra_data. 

here is my code

```python
input_statement = bot.input.process_input_statement()
statement, response, confidence = bot.generate_response(input_statement)

st = Statement(input_statement)
st.add_extra_data('intent', 'greetings')
```

**Comment by gunthercox** [comment]
Just a quick note, the `add_extra_data` method adds the data to the statement object. If you want to save the modified statement to your database you can do something like this:

```python
st = Statement(input_statement)
st.add_extra_data('intent', 'greetings')

bot.storage.update(st)
```

**Comment by bilalbayasut** [comment]
Here is my code
`
while True:
    try:
        # bot_input = bot.get_response(None)
        input_statement = bot.input.process_input_statement()
        statement, response, confidence = bot.generate_response(input_statement)

        st = Statement(input_statement)
        st.add_extra_data('intent', 'greetings')
        print(str(st.text))
        bot.storage.update(st)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
`
But I get this error

`...
    self.statements.bulk_write(operations, ordered=False)
  File "/usr/lib/python3.5/pymongo/collection.py", line 435, in bulk_write
    bulk_api_result = blk.execute(self.write_concern.document)
  File "/usr/lib/python3.5/pymongo/bulk.py", line 470, in execute
    return self.execute_command(sock_info, generator, write_concern)
  File "/usr/lib/python3.5/pymongo/bulk.py", line 302, in execute_command
    run.ops, True, self.collection.codec_options, bwc)
bson.errors.InvalidDocument: Cannot encode object: <Statement text:hi>
`

**Comment by gunthercox** [comment]
I think I see the issue. In `input_statement = bot.input.process_input_statement()`, the item returned (`input_statement`) is a statement object. Then you have `st = Statement(input_statement)` which is creating a new statement where the text is another statement object.

Try changing `st = Statement(input_statement)` to `st = Statement(input_statement.text)`.

**Comment by bilalbayasut** [comment]
Yes, I nailed it, instead of I create a new object, I just use the existing statement variable from

`statement, response, confidence = bot.generate_response(input_statement)`

and call `statement.add_extra_data('intent','greetings')`

and now I can see my corresponding statement has the extra data. 

Thanks, cos I just played around with python, still haven't got the deep oop idea behind your code

Thanks again

**Comment by gunthercox** [comment]
No problem! Happy to help.
