### ISSUE TITLE
[Suggestion] Conversational Flow based chatbot

### ISSUE THREAD

**Issue by bilalbayasut** [gunthercox/ChatterBot#444]
I suggest that if this chatterbot can support the mechanism to create a conversational flow chatbot like [wit.ai](https://wit.ai/) with it's story, I think it will be more reaching the needs of creating chatbot for various kind of scenarios.

**Comment by gunthercox** [comment]
After looking at the documentation in [their quickstart guide](https://wit.ai/docs/quickstart) I think ChatterBot actually already supports all of the _story_ functionality that you mentioned. The terminology between the two ChatterBot and wit.ai is rather different but I'm seeing a lot of similarities.

1. **Creating a story** in wit.ai looks to be the same thing as **training** in chatterbot.
2. **Adding a branch to a story** in wit.ai appears to be the same as **training with multiple variations of a conversation** in ChatterBot

I will note that wit.ia does categorize input statements with a label called `intent`. This categorization is something that ChatterBot does not do.

@bilalbayasut Is there a feature of _stories_ that I missed?

**Comment by bilalbayasut** [comment]
@gunthercox , well it means that we have to figure it out our self to make a conversational chatbot. Like what i just did by saving the detected topic or intent for each statement, and adding a step variable so that the bot know where he is in conversation. am I right?

Because, let say if we have a scenario when we want to direct the flow of conversation with the user by slipping some API in the middle of user say and the bot say. for instance like conversation of ordering flowers. 

what do you think about that?

**Comment by gunthercox** [comment]
ChatterBot currently doesn't support form-like information gathering in the core. Typically this is a somewhat specialized process that depends highly on the type of information being gathered and the circumstances under which the information is needed. So yes, if a someone wants to gather specific information from a user, they must code this logic themselves.

ChatterBot does allow you to [create your own logic adapters](http://chatterbot.readthedocs.io/en/latest/logic/create-a-logic-adapter.html). Typically, logic adapters are where responses are selected, but you can also write your own modified ones that look for specific inputs to respond to. In the case of your example of ordering flowers, it would be a simple enough case to check if the user's input says something close to "Place my order of flowers" then make an API call to place the order.

Does this help at all?

**Comment by bilalbayasut** [comment]
ok yes, but how about to make the response ? can I generate my own response in hard code ? or maybe there is a way to store in db by train method, but not by user_input - response pairs, but the response only. 

so I can call chatbot.train(['Thank you for ordering flower with us'])

or you have a more dynamic and simple way? 

thanks in advance

**Comment by gunthercox** [comment]
Hi @bilalbayasut, my apologies for the late response. I appear to have missed your last comment.

You can create response pairs in ChatterBot using it's _training_ functionality. Here is a link to the documentation with more info and examples: http://chatterbot.readthedocs.io/en/latest/training.html

Essentially, training provides several different methods to add statements, as you described. For example, if I want to tech the chat bot that "Hi there!" is a response to "Hello", then I would do the following:

```python
from chatterbot.trainers import ListTrainer

chatterbot = ChatBot("Training Example")
chatterbot.set_trainer(ListTrainer)

chatterbot.train([
    "Hi there!",
    "Hello",
])
```

You can make that conversation of statements as long as you want, ChatterBot treats it as a single conversation. You can also create variations of the conversation by training on different data.

I hope this helps, please let me know if you have any further questions or if you think there is anything I could add to the documentation to help explain this better.

For now, I'm going to close this issue as I believe everything here should be resolved.
