### ISSUE TITLE
how can we give a message to the user if the similarity between the strings are less?

### ISSUE THREAD

**Issue by gpjyothish** [gunthercox/ChatterBot#446]
Imagine if we enter a string as an input to the bot, that have a negligible similarity with the trained set. Then how can make the bot to give a message that it doesn't know the answer instead of giving a comparitevely most similar random output?

**Comment by bilalbayasut** [comment]
you can display the confidence value and use the existing adapter called NoKnowledge where the bot will say a predefined input (let say : "I don't know, please try again") if the statement does not exist on the training set. you can see in example folder, it's already listed and explained there

**Comment by gpjyothish** [comment]
thank you....

**Comment by bilalbayasut** [comment]
happy to help
