### ISSUE TITLE
Chatterbot slows down on large databases

### ISSUE THREAD

**Issue by SethDusek** [gunthercox/ChatterBot#45]
So my plan was, to make a irc bot that would learn from logs and then be in the channel.

I fed it about 25k lines of logs from a large log file, and then I decided to test it out.

I asked it something, then waited for it to respond, it was taking about 40% CPU usage, and I waited an hour for it to respond. Nothing. 

Also I am on PyPy so the default json library is already very fast

**Comment by gunthercox** [comment]
This is a known issue. I'm working on writing database adapters for mongodb and sqllite. The mongodb adapter should be available in the next release of ChatterBot.

**Comment by gunthercox** [comment]
Greetings! Just to provide an update, https://github.com/gunthercox/ChatterBot/pull/51 adds support for connecting ChatterBot to MongoDB which should yield significant performance improvements on large databases.

**Comment by SethDusek** [comment]
Okay I'll give it a try, thanks!
