### ISSUE TITLE
didn't get how to use mongoDB

### ISSUE THREAD

**Issue by HelloJyo** [gunthercox/ChatterBot#454]
I didn't get how to use mongoDB instead of JSON adapter..didn't show any responses from the bot

**Comment by vkosuri** [comment]
@HelloJyo Here is an example located here http://chatterbot.readthedocs.io/en/stable/storage/index.html#mongo-database-adapter

A python code example located here https://github.com/gunthercox/ChatterBot/blob/master/examples/terminal_mongo_example.py

**Comment by HelloJyo** [comment]
i did that but the bot didn't give any response. I created a mongoDB "myDB" and inserted some data into it. Where should i place it? I want to use that one for the bot to give responses...

**Comment by gunthercox** [comment]
@HelloJyo Did you try setting the database parameter to match the name of the one you are using? The available parameters are listed at the documentation link that @vkosuri provided.

Also, if you are looking to add data to the chat bot's database, I recommend taking a look at the [training documentation](http://chatterbot.readthedocs.io/en/latest/training.html). The training process will conveniently set up all of the required relationship data between dialog in the database.

**Comment by HelloJyo** [comment]
I changed to the mongoDB. I trained the bot with new data by making changes with the corpus data.
But couldn't train it with the trainer class (list trainer). If there any way to do that?

**Comment by gunthercox** [comment]
There is other methods for training: http://chatterbot.readthedocs.io/en/latest/training.html

**Comment by HelloJyo** [comment]
ok i'm gonna try

**Comment by HelloJyo** [comment]
ok it worked....thanks
