### ISSUE TITLE
Custom paths for corpus data

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#467]
I think it would be good option to specify custom paths for corpus data, currently its system specified path only

```Python
class Corpus(object):

    def __init__(self):
        current_directory = os.path.dirname(__file__)
        self.data_directory = os.path.join(current_directory, 'data')
```

**Comment by vkosuri** [comment]
@gunthercox Planning to write like this, any suggestions/comments?

```Diff
@@ -9,6 +9,7 @@ class Trainer(object):
 
     def __init__(self, storage, **kwargs):
         self.storage = storage
+        self.corpus_path = None
         self.logger = logging.getLogger(__name__)
 
     def train(self, *args, **kwargs):
@@ -54,6 +55,10 @@ class Trainer(object):
 
         return result
 
+    def import_for_training(self, file_path):
+        self.corpus_path = file_path
+
+
     def export_for_training(self, file_path='./export.json'):
         """
         Create a file from the database that can be used to
@@ -100,7 +105,7 @@ class ChatterBotCorpusTrainer(Trainer):
         super(ChatterBotCorpusTrainer, self).__init__(storage, **kwargs)
         from .corpus import Corpus
 
-        self.corpus = Corpus()
+        self.corpus = Corpus(self.corpus_path)
 
     def train(self, *corpora):
         trainer = ListTrainer(self.storage)
```

**Comment by gunthercox** [comment]
@vkosuri Looks good to me 👍

**Comment by rajasimon** [comment]
I like this to be integrated asap!

**Comment by vkosuri** [comment]
Sure 👍

**Comment by rajasimon** [comment]
Can you make the pull request so I can check it and also does it support for adding my own custom adapters...?

i.e)

```
    'logic_adapters': [
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.BestMatch'
        'funstuff.login.FunStuff'
    ],
```

**Comment by rajasimon** [comment]
Sorry for my prev message I just saw this https://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html#directory-structure

**Comment by rajasimon** [comment]
@vkosuri Shall I have the patch now ?

**Comment by vkosuri** [comment]
Sure

On 26-Dec-2016 09:57, "Raja Simon" <notifications@github.com> wrote:

@vkosuri <https://github.com/vkosuri> Shall I have the patch now ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gunthercox/ChatterBot/issues/467#issuecomment-269160004>,
or mute the thread
