### ISSUE TITLE
How do I post against chatterbot api from channels?

### ISSUE THREAD

**Issue by rajasimon** [gunthercox/ChatterBot#468]
Well I'm using Django channels to send and receive messages. In this case I'm using consumers to get the messages from frontend and process it and return back to frontend.

```
def ws_message(message):
    # I like to call the chatterbot api here
    reply_message = ????
    message.reply_channel.send({
        "text": reply_message,
    })

```
I correctly set `chatterbot.ext.django_chatterbot` in INSTALLED_APPS. And also I have this...

```
# Chatterbot
CHATTERBOT = {
    'name': 'Bot Example',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        'chatterbot.corpus.english.greetings'
    ]
}
```

**Comment by gunthercox** [comment]
Hi @rajasimon, I am not very familiar with Django channels but they look quite interesting. Maybe take a look at the existing API view that is provided in the project: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/ext/django_chatterbot/views.py

**Comment by rajasimon** [comment]
Yes I was expecting something very easy to setup weather I'm using Django channels or normal Django views for the chat messages. Maybe we can setup chatterbot configuration in the settings file and invoke that from our views or channels message to get the response.  

I looked that chatterbot settings in that example and modified what I need.

```
chatterbot = ChatBot(
    'ask',
    storage_adapter="chatterbot.storage.DjangoStorageAdapter",
    input_adapter="chatterbot.input.VariableInputTypeAdapter",
    output_adapter="chatterbot.output.OutputFormatAdapter",
    output_format="object"
)
```


Looks like messages saved into database that's all I want. Will explore more! Thanks.

**Comment by rajasimon** [comment]
@gunthercox 

```
# Settings.py
# Chatterbot
CHATTERBOT = {
    'name': 'Fun stuff bot',
    'logic_adapters': [
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter',
        'chatterbot.logic.BestMatch'
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         'chatterbot.corpus.english.greetings'
    ]
}


# Make sure these imports comes after the CHATTERBOT
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings as chatterbot_settings

BOT = ChatBot(**chatterbot_settings.CHATTERBOT)
```

And in my channels message I have this...
```

    from django.conf import settings
    input_data = {"text": "My input statement"}
    response_data = settings.BOT.get_response(input_data)

```
I know this bad way to try. This will fetch the nltk data two times. I cann't able to make post request to chatterbot API using requests because of the csrf_token issue. What is the best approach?

**Comment by gunthercox** [comment]
@rajasimon Django encourages secure requests. If you are seeing an error about CSRF tokens, then you likely need to add the token to the request you are sending to your API.

Django provides several examples on how you can do this in their documentation: https://docs.djangoproject.com/en/1.10/ref/csrf/

The solution you use depends on the setup of your code. If you are sending your requests to the API using JavaScript then you probably want the AJAX solution.

**Comment by rajasimon** [comment]
@gunthercox Well I'm not planning for using AJAX solution. And I found the way to work with `requests` But I wanted to insert  `{% csrf_token %}` in base.html 

```
    URL = 'http://127.0.0.1:8000'
    client = requests.session()
    client.get(URL)

    # Token
    csrftoken = client.cookies['csrftoken']

    payload = {
        "text": "My input statement"
    }
    headers = {'Content-type': 'application/json',  "X-CSRFToken":csrftoken}
    cookies = dict(client.cookies)

    resp = requests.post(URL + '/chatterbot/', json={"text": "My input"}, headers=headers, cookies=cookies)
```

**Comment by rajasimon** [comment]
And another one thing... I'm getting the No json object could be decoded error from TimeLogicAdapter related. Will investigate into that one. Will update you.
