### ISSUE TITLE
How is the database created and how can I change it?

### ISSUE THREAD

**Issue by dambros** [gunthercox/ChatterBot#47]
I am doing some research on chatting bots for studying purposes, but I have never done any Python programming before and coming from a Java background, the database creation is pure black magic to me. Can you please point me in a direction on how I can add 1 additional "column" to the list of values stored?

I need to add a "score_value" to the database so I can measure how many points an user made throughout a chat session with the bot. 

Thanks.

**Comment by gunthercox** [comment]
Hi @dambros, the default _database_ used by ChatterBot is just a json formatted file. You shouldn't need to make any adjustments to the database itself in this case. I recommend you checkout the `get_response_data` method in the main `ChatBot` object (chatterbot.py). Around line 70 of this file you will see that I assign a few values like this:
```python
values["name"] = name
values["occurrence"] = count
values["in_response_to"] = response_list
```
These are the attributes that are being saved to the database. In your case, you would just want to add another one here that would look like:
```python
values["score_value"] = my_score_value
```

Let me know if you need additional information on this.

**Comment by dambros** [comment]
That did what I wanted. Thanks for your help :D

**Comment by dambros** [comment]
Just one more thing, how can I change the train method to allow passing a score?

**Comment by gunthercox** [comment]
For this you will want to modify the `train` method in the `StorageController` class. You can assign the score in the same way in this method. Since the train method in the `ChatBot` class calls the train method in the `StorageController` class, you may want to modify it to take an additional parameter for the score.

**Comment by dambros** [comment]
Thanks.
