### ISSUE TITLE
Add session management to input hipchat adapters

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#474]
I verified this issue on hipchat only, i made some changes on my machine to work.

**Comment by gunthercox** [comment]
Ok, this makes sense. I never made changes to add it 😐

**Comment by vkosuri** [comment]
Thanks, Any plans to fix this issue? If not can i submit PR?

**Comment by gunthercox** [comment]
@vkosuri If you are interested in working on this that would be greatly appreciated.

**Comment by vkosuri** [comment]
Sure will submit a PR soon
