### ISSUE TITLE
Example `add_response`

### ISSUE THREAD

**Issue by bekerov** [gunthercox/ChatterBot#475]
Please specify example of usage `add_response`

**Comment by vkosuri** [comment]
For a quick example you could look into this testcase, https://github.com/gunthercox/ChatterBot/blob/c3431ced70b88eb08fb36534f18ed62c90ab9723/tests/conversation_tests/test_statements.py#L17

**Comment by gunthercox** [comment]
Hi @bekerov, here is a link to the documentation for this function for reference: [link](http://chatterbot.readthedocs.io/en/latest/conversations.html#chatterbot.conversation.Statement.add_response). The `add_response` method adds the Response object as an element in the list of statements that the current statement is in response to. So, for example:

```python
from chatterbot.conversation import Statement, Response

statement = Statement("I am doing well.")
response = Response("Hello, how are you?")

statement.add_response(response)
```

Also, keep in mind that doing this only modifies the objects in memory, it does not commit them to the chat bot's database until you pass the statement object to the `update` method of the chat bot's storage adapter. Documentation on the available storage adapters can be found here: http://chatterbot.readthedocs.io/en/latest/storage/index.html

Let me know if you have any further questions.

**Comment by bekerov** [comment]
Thanks this very helpful
