### ISSUE TITLE
ChatterBot and Api.ai

### ISSUE THREAD

**Issue by phpmind** [gunthercox/ChatterBot#477]
Hi 
Can we connect ChatterBot with API.AI. 

I like using logical adapter but i would like to know if we can integrate with API.AI.

Thanks

**Comment by phpmind** [comment]
gunthercox - I would love to add this feature in few weeks. I will let you know. 

Thanks

**Comment by gunthercox** [comment]
Looking forward to seeing git. In the meantime, I'm going to close this ticket off. Thank you.
