### ISSUE TITLE
Logic problem in "learning_feedback_example.py"

### ISSUE THREAD

**Issue by boris314159** [gunthercox/ChatterBot#479]
I really like this example, it provides the basis for interactive training of bots. There seems to be logical error if the user responds negatively to the query below. If get_feedback() returns "No", the output is simply the original bot response (which was incorrect), and is assigned a confidence value of 1.0.

```
        print('\n Is "{}" this a coherent response to "{}"? \n'.format(response, input_statement))
        if get_feedback():
            bot.learn_response(response,input_statement)
        bot.output.process_response(response, confidence)
```

**Comment by vkosuri** [comment]
@boris314159 I think this issue was addressed in this PR https://github.com/gunthercox/ChatterBot/pull/817
