### ISSUE TITLE
terminal.py does not work

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [gunthercox/ChatterBot#48]
```
Traceback (most recent call last):
  File "terminal.py", line 9, in <module>
    database="../database.db")
  File "/Users/Frank/Downloads/ChatterBot-master/chatterbot/chatterbot.py", line 32, in __init__
    self.io = IOAdapter()
TypeError: __init__() takes exactly 2 arguments (1 given)
```
When I try to run the example/terminal.py, it gives me above error

**Comment by gunthercox** [comment]
Hi @Xuefeng-Zhu, I just pushed up [a commit](https://github.com/gunthercox/ChatterBot/commit/0ab60a4330daf727f88bb89dd9ce4abd31b6f89e) that fixes the issue here. The problem was that the wrong name was being called for a keyword argument in the main `init` method.
