### ISSUE TITLE
Chatbot text into events

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#482]
It would be great by convert chatterbot text into events. For example, any suggestion/comments?

``` bash
feed baby at 7
Schedule a meeting
```

**Comment by gunthercox** [comment]
Creating efficient scheduling operations can often be a challenging problem to solve. What about offloading the task to the user's calendar? Most calendar apps already display notifications when a scheduled event is coming up, and it would also make it possible synchronize the events across the user's devices if they were all connected to the same calendar.

- https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations
- https://developers.google.com/google-apps/calendar/v3/reference/

**Comment by vkosuri** [comment]
very impressed me alot by looking this https://api.slack.com/rtm, do you have any comments on this?

**Comment by gunthercox** [comment]
Slack has a great API, I've been meaning to look into it at some point.

**Comment by vkosuri** [comment]
@gunthercox By looking into this, any thoughts on best implementation methods?

- https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations
- https://developers.google.com/google-apps/calendar/v3/reference/

**Comment by gunthercox** [comment]
@vkosuri Unfortunately I don't have any recommendations.

**Comment by gunthercox** [comment]
Actually, there is a very cool datetime parsing utility that @rmdort contributed a while back. You can check it out here: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/parsing.py

This might be useful for converting phrases like "later today" to an actual datetime object.

**Comment by vkosuri** [comment]
@gunthercox Thanks, I have few thoughts i will reopen with detailed plan

**Comment by nggary** [comment]
May I know how @vkosuri do the conversation from text to event action? I see there are several calendar
