### ISSUE TITLE
in_response_to properties

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#486]
I think adding a properties object to in_response_to, it will give more control to developer make many decisions by filling in_response properties dict.. For example

``` Json
{
	"Can i get python square root": {
		"extra_data": {},
		"in_response_to": [{
			"text": "def square_root(x): return math.sqrt(x)",
			"occurrence": 15,
			"properties": [{
				"style": "markdown",
				"code": "python",
				"color": "no"
			}]

		}]
	}
}
```

***
I am assuming it may add extra overhead to chatterbot, Any suggestions/comments?

**Comment by gunthercox** [comment]
Each of the items in the `in_response_to` list is technically a `Response()` objects. Each `Response()` object is a representation of the relationship between two statements. If the proposed `properties` attribute is intended for styling the response statement, would there be any issues saving them as `extra_data` on the statement itself?

![image](https://cloud.githubusercontent.com/assets/2030578/21076166/68482b3a-bef2-11e6-9edb-50ebea58ee21.png)

**Comment by vkosuri** [comment]
Awesome, this makes me more clear. I think this could be documented?

**Comment by gunthercox** [comment]
Agreed, my plan is to add a version of that diagram and an explanation to the documentation on statements and responses. http://chatterbot.readthedocs.io/en/latest/conversations.html

**Comment by vkosuri** [comment]
Thanks Master
