### ISSUE TITLE
chatterbot live example

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#493]
I have made a heroku live example for chatterbot to more familiar with chatterbot and what it does. you can access this app from here https://chatterbot-live-example.herokuapp.com/

Any comments/suggestion?

**Comment by vkosuri** [comment]
And alos source of this example you can found here https://github.com/vkosuri/chatterbot-live-example

**Comment by gunthercox** [comment]
I can see it is currently having the issue you reported in #497. As soon as the issue is resolved I'll draft a new version of chatterbot to release to pypi.

**Comment by vkosuri** [comment]
@gunthercox is it possible add this https://chatterbot-live-example.herokuapp.com/ url in somewhere in documentation?

**Comment by gunthercox** [comment]
Sure! Feel free to make a pull request. There is also a section in the readme.md that lists various examples with Django and Flask, a link to the live example might work well there as well.
