### ISSUE TITLE
Identify "Corpus" by IETF language tag rather than just language

### ISSUE THREAD

**Issue by duramato** [gunthercox/ChatterBot#504]
My suggestion is to Identify the "Corpus" by [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) rather than just language. What are the benefits? it would allow for different dialects to be made independent as i might want to just "teach" just one of them. 
### Why i'm bringging this idea up?
For example the corpus for the _Portuguese_ language taking a look at it seems to have mostly _Portuguese Brazilian_ (**pt-BR**) strings and some, here and there, in the Portuguese (**pt** or **pt-PT**). Using said corpus makes the bot a bit of biliangual freak, i'f im allowed to call it that :P

Same goes for the english corpus which, i'd say (not totally sure, but from some expressions), is _English_ (**en** or **en-GB**) with  _United States English_ (**en-US**) in it.

Chinese is another language with _ALOT_ of dialects.. (but this one is an unkown to me as i have zero knowledge in the language) 
The story goes on..

**Comment by gunthercox** [comment]
This is a good suggestion. Making changes to use IETF language tags sounds like it would really benefit ChatterBot.
