### ISSUE TITLE
No handlers could be found for logger "chatterbot.trainers"

### ISSUE THREAD

**Issue by engineer34** [gunthercox/ChatterBot#508]
I got this error can you help me please ?

**Comment by gunthercox** [comment]
Hi @engineer34 Could you please provide some information on how you got the error? Right now there isn't anything there that can let me help you. Some items that you might wight want to include **at minimum** are:

- The version of Python you are using
- The version of ChatterBot you have installed
- **A list of steps that other developers could follow to recreate the error that you encountered.**
