### ISSUE TITLE
how lists of response works?

### ISSUE THREAD

**Issue by stevedipaola** [gunthercox/ChatterBot#514]
can you explain - in a default setup how a long list of responses will change the possible weighty of response  from say doing them in separate lsits. That is how does a list of responses weight the setup to move through to those responses. I am asking mainly to understand how to author these, that is when to keep a long list going as opposed to making another list. 

So then the difference between do this:

chatterbot.train([
     "How are you?",
     "I am good."
])
chatterbot.train([
    "That is good to hear.",
    "Thank you",
])

-- compared to do them in a list:

chatterbot.train([
    "How are you?",
    "I am good.",
    "That is good to hear.",
    "Thank you",
    "You are welcome.",
])

thanks, Steve

**Comment by gunthercox** [comment]
Given the first example with two short lists, the chat bot would not make a connection between "I am good." and "That is good to hear.". That is, it would not know that "I am good." has "That is good to hear." as a possible response.

In the single longer list, each statement will be learned as a response to the previous.

**Comment by stevedipaola** [comment]
Thanks, ok that came off as a dumb question, I was looking for the next level of detail or better yet I should have just explained my issue.  we have a chatterbot setup working with slack (wonderful program and setup! - thanks) and in our code the ability to correct on the fly. So this way, as one current approach, I can start with nothing, then start with a question and after that  answer live just use correction as the better answer. And built up a conversation that way. What the issue is, I appear to be  getting too many latter matching responses to my input questions then my answers. So a never said before "who are you" matches to the question "are you a bot" rather than the answer "yes I am a AI chatbot, my name is ivbot". It hit me that this live correction method just creates two phrase length Q then A lists rather than the longer conversation lists and that might be why this is happening (which means I should abandon this technique and go to the more conventioanl premaking lists) - so that drove my original question. It could be that I have a different mistake in my code that is causing this too. I am using
 logic_adapter="chatterbot.logic.BestMatch", 
statement_comparison_function=synset_distance,

any suggestions appreciated.

thanks, steve

**Comment by gunthercox** [comment]
Hmm, maybe you could set [get_most_frequent_response](http://chatterbot.readthedocs.io/en/latest/logic/response_selection.html#module-chatterbot.response_selection):
```python
response_selection_method=get_most_frequent_response
```

Making this change would cause your bot to select the response that occurs most frequently. If your correcting methods incremented the occurrence count of the correct response, it should cause that response to be selected the next time.
