### ISSUE TITLE
How do I point to the custom corpus within Django project?

### ISSUE THREAD

**Issue by rajasimon** [gunthercox/ChatterBot#522]
I'm planning to create corpus directory inside my Django project, say I have the project called `funstuff` 

```
funstuff
|__corpus
    |__data
        |__english
            |_greetings.json
|__funstuff
    |__settings.py
|__manage.py

```

I like to modify the settings.py file like this
```

# Chatterbot
CHATTERBOT = {
    'name': 'Fun stuff bot',
    'logic_adapters': [
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.BestMatch'
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         'chatterbot.corpus.english.greetings',
         'funstuff.corpus.english.greetings'
    ]
}
```

Finally I want `./manage.py train` should pick those corpus file and start the training!

**Comment by vkosuri** [comment]
You could more documentation from here http://chatterbot.readthedocs.io/en/stable/django/training.html#training

``` Bash
python manage.py train
```

**Comment by rajasimon** [comment]
@vkosuri  Nope still it's not picking my Django project corpus file. Can you replicate my above setup and give me solution

**Comment by gunthercox** [comment]
Hi, the ability to specify a path currently isn't available in ChatterBot.
There are plans to add the ability to do so and there is currently a ticket
open that requests this feature (
https://github.com/gunthercox/ChatterBot/issues/467).

This will be a relatively simple feature to add and it should be possible
to add it in one of the upcoming releases.

**Comment by gunthercox** [comment]
Hi @rajasimon The ability to specify custom corpus paths has been added in https://github.com/gunthercox/ChatterBot/pull/549 and it will be available to use in the next release. I will update the documentation as well.

**Comment by vkosuri** [comment]
Thanks @gunthercox
