### ISSUE TITLE
Chatterbot response in django is in json format

### ISSUE THREAD

**Issue by buildithub** [gunthercox/ChatterBot#523]
![screenshot from 2016-12-21 12 24 01](https://cloud.githubusercontent.com/assets/18592572/21380041/60a84b24-c778-11e6-9809-29907693680f.png)

**Comment by vkosuri** [comment]
@buildithub how you are trying? Did you see this error while running example_app ? Could you please explain a bit your problem, so that is easier to help?

**Comment by buildithub** [comment]
yes I ran example_app and the above problem occurs. This is happening since 0.5.3 version. Before that I used 0.5.1 version of the chatterbot and there was no problem.

**Comment by vkosuri** [comment]
I can able reproduce this issue

**Comment by buildithub** [comment]
I used 0.5.1 version's django_app with 0.5.3's chatterbot. Still not working. Only working with 0.5.1.

**Comment by buildithub** [comment]
I used 0.5.3 version's django_app with 0.5.1's chatterbot. It's working.

**Comment by vkosuri** [comment]
Same answer

> I used 0.5.3 version's django_app with 0.5.1's chatterbot. It's working.

**Comment by gunthercox** [comment]
Hi everyone, #608 corrects this problem. I apologize about the delay in tracking down the issue.
