### ISSUE TITLE
Adding new data to existing corpus.

### ISSUE THREAD

**Issue by melvinabraham** [gunthercox/ChatterBot#524]
@gunthercox 
When I add new Questions/Answers to the existing corpus(I used 'conversations') and then on training it again, the bot doesn't respond with the newly added questions.
![1](https://cloud.githubusercontent.com/assets/12198973/21397898/7450b55a-c7cb-11e6-9d09-63cd4cdd2bae.png)
![2](https://cloud.githubusercontent.com/assets/12198973/21397908/7ca1cffa-c7cb-11e6-9da3-d6d6dfccecb3.png)
![3](https://cloud.githubusercontent.com/assets/12198973/21397912/8336bb0a-c7cb-11e6-8436-292e7b85c02b.png)
Apologise in advance if the question has been asked.
Thank you.

**Comment by gunthercox** [comment]
If you are modifying chatterbot's codebase, you will likely need to
re-install chatterbot after the modification (`pip install . --upgrade`).
After than you should be able to call the train method to re-train the chat
bot with your updated data.

**Comment by melvinabraham** [comment]
Um no. I'm not modifying the codebase. Rather, I added an extra entry to the corpus (english.conversations). However on querying that entry(Essentially a question with answer, refer the pics above) I get a random output, not what I trained it.
Thanks.

**Comment by melvinabraham** [comment]
To be more specific: 
1. **I added the entry** _["This is a test question?","Testing123"]_ to the **english.conversations corpus**
![1](https://cloud.githubusercontent.com/assets/12198973/21427402/64285ab6-c87a-11e6-98d3-9100deda6c60.png)
2. Now I created a bot and trained it with the already **modified and saved** conversations corpus.
So basically the program gets response from the bot for :  "This is a test question?".
![2](https://cloud.githubusercontent.com/assets/12198973/21427420/88951600-c87a-11e6-8aed-7c084eabc12e.png)
3. This was followed by running the code. Instead of getting _"Testing123"_ as the answer, I get some random answer as highlighted.
![3](https://cloud.githubusercontent.com/assets/12198973/21427463/ce353a8c-c87a-11e6-8b78-b12402320013.png)

**Comment by vkosuri** [comment]
@melvinabraham any updates on this? Try to search your test statement exists in database.db or not, if it is there then your data is trained.

If you try to get more specific output you have to use comparison functions http://chatterbot.readthedocs.io/en/stable/logic/index.html#best-match-adapter

**Comment by melvinabraham** [comment]
With reference to the previous answer, the bot was supposed to answer for "**This is a test question**" as "**Testing123**". On searching the **database.db** file for this question I found out that it exists: 
![4](https://cloud.githubusercontent.com/assets/12198973/21589597/6f1ca40c-d119-11e6-8aea-45e953a1994a.png)

Compiling the testcase: 
![5](https://cloud.githubusercontent.com/assets/12198973/21589617/c434864e-d119-11e6-8cfa-20a2d45345d7.png)

Some other random output is obtained.
![6](https://cloud.githubusercontent.com/assets/12198973/21589620/cf7aa63c-d119-11e6-9ad3-1a93e14bd332.png)

**Comment by vkosuri** [comment]
@melvinabraham thanks, did you added statement comparison adapters? And also please read http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-comparison

**Comment by melvinabraham** [comment]
@vkosuri Issue resolved! A comma went haywire in the .json file. 
Sorry and thank you!

**Comment by vkosuri** [comment]
@melvinabraham no problem

**Comment by melvinabraham** [comment]
@vkosuri 
How do I link your awesome 'chatterbot' with my custom corpus with an android application?
