### ISSUE TITLE
Can I initialize two chatterbot at the same time in django?

### ISSUE THREAD

**Issue by buildithub** [gunthercox/ChatterBot#525]
I want to have a django app which has two chatterbot with different databases. Is it feasible? If yes can you give some idea?

**Comment by vkosuri** [comment]
Yes it is feasible

**Comment by buildithub** [comment]
How? can you please give some idea?

**Comment by vkosuri** [comment]
Something could you help you http://michal.karzynski.pl/blog/2013/10/29/serving-multiple-django-applications-with-nginx-gunicorn-supervisor/

I never tried above scenario, I think working with different database you need pass it externally to your app.

**Comment by vkosuri** [comment]
@buildithub i am closing this issue, if you have any questions/suggestion please feel free reopen this issue
