### ISSUE TITLE
ImportError: No module named 'chatterbot.adapters.storage'...

### ISSUE THREAD

**Issue by Nixellion** [gunthercox/ChatterBot#532]
Just updated to the latest git version of chatterbot, and I now get this error when running `chatbot = ChatBot(...` command. Before the update everything worked quite well. Do I need to change something in the way I initialize a bot? I did not update it for a long time actually, so it's possible I missed something. Thanks!

`chatbot = ChatBot("Chatbotname", logic_adapters=[
        "chatterbot.adapters.logic.TimeLogicAdapter",
        # "chatterbot.adapters.logic.ClosestMeaningAdapter",
        # "chatterbot.adapters.logic.ApproximateSentenceMatchAdapter",
        "chatterbot.adapters.logic.ClosestMatchAdapter",
        # "chatterbot.adapters.logic.MathematicalEvaluation"
    ],
                      input_adapter="chatterbot.adapters.input.VariableInputTypeAdapter",
                      output_adapter="chatterbot.adapters.output.OutputFormatAdapter",
                      storage_adapter="chatterbot.adapters.storage.MongoDatabaseAdapter",
                      database='Chatbotname-database',
                      tie_breaking_method="random_response"
                      )`

`Traceback (most recent call last):
  File "D:/Projects/Python/Code/server/app.py", line 764, in <module>
    storage_adapter="chatterbot.adapters.storage.MongoDatabaseAdapter",
  File "D:\Projects\Python\Code\server\chatterbot\chatterbot.py", line 32, in __init__
    utils.validate_adapter_class(storage_adapter, StorageAdapter)
  File "D:\Projects\Python\Code\server\chatterbot\utils.py", line 112, in validate_adapter_class
    if not issubclass(import_module(validate_class), Adapter):
  File "D:\Projects\Python\Code\server\chatterbot\utils.py", line 64, in import_module
    module = importlib.import_module(module_path)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2221, in _find_and_load_unlocked
ImportError: No module named 'chatterbot.adapters.storage'; 'chatterbot.adapters' is not a package`

**Comment by Nixellion** [comment]
Oh, haha. Well. Obviously, i just had to remove ".adapters" from all adapters, I see the change in directories now. Sorry to bother. Will keep digging into further things that changed.  Sorry about this.

**Comment by gunthercox** [comment]
@Nixellion Thanks for the heads up. I will make changes to correct the broken link.
