### ISSUE TITLE
Add documentation on how to use unicode

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#543]
It would be useful to have some documentation on how to use unicode encoding in Python and how troubleshoot unicode errors and warnings. ChatterBot's domain involves working with string type data and a variety of unicode-related questions come up frequently.

**Comment by vkosuri** [comment]
@gunthercox a useful tag,

I want share some of my thoughts here, If i found unicode issues how i resolved those issues

Recommended use [virtual environments](https://virtualenv.pypa.io/en/stable/userguide/) for python2 and [python3](https://docs.python.org/3/library/venv.html).

**python2**
```Bash
virtualenv venv
source venv/bin/activate
python chatterbot-example.py
```
**python3**
```
python3 -m venv /path/to/new/virtual/environment
source venv/bin/activate
python chatterbot-example.py
```

1. [Learn the differences between Python 2 & 3](http://python-future.org/compatible_idioms.html#)
2. Use [Futurize ](http://python-future.org/automatic_conversion.html)(or [Modernize](https://python-modernize.readthedocs.org/en/latest/)) to update your code (e.g. pip install future)
3. Use [Pylint ](https://pypi.python.org/pypi/pylint)to help make sure you don’t regress on your Python 3 support (pip install pylint)
4. Use [caniusepython3 ](https://pypi.python.org/pypi/caniusepython3) to find out which of your 
5. Consider using optional static type checking to make sure your type usage works in both Python 2 & 3 (e.g. use [mypy ](http://mypy-lang.org/)to check your typing under both Python 2 & Python 3).
