### ISSUE TITLE
Error in file index.rst

### ISSUE THREAD

**Issue by DangMinh24** [gunthercox/ChatterBot#544]
In  _**Setting parameters**_ section, I think _**response_selection_method**_ and _**"statement_comparison_function"**_ are in incorrect order.

**Comment by gunthercox** [comment]
Hi @DangMinh24, the ordering of these parameters doesn't matter.

**Comment by DangMinh24** [comment]
Hi @gunthercox , I means in [Setting parameters](https://github.com/gunthercox/ChatterBot/blob/master/docs/logic/index.rst), I try:

> logic_adapters=[
>         {
>             "import_path": "chatterbot.logic.BestMatch",
>             "response_selection_method": "chatterbot.comparisons.levenshtein_distance",
>             "statement_comparison_function": "chatterbot.response_selection.get_first_response"
>         }

It got TypeErrors. Then I try 

> logic_adapters=[
>         {
>             "import_path": "chatterbot.logic.BestMatch",
>             "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
>             "response_selection_method": "chatterbot.response_selection.get_first_response"
>         }

It works great. So I think there is a mistake in an example

**Comment by gunthercox** [comment]
You are correct, it looks like the values for the parameters are reversed. Thank you for pointing this out. I'll make changes to correct it.

**Comment by gunthercox** [comment]
Closed by #545
