### ISSUE TITLE
Best way to restructure mongo storage

### ISSUE THREAD

**Issue by Olamyy** [gunthercox/ChatterBot#546]
Hi,
I'm trying to restructure the MongoStorage to suit own needs.
By restructuring, i mean i want to edit the way the format the documents are stored in the Database.
What would you say is the best way for me to go about that?

**Comment by vkosuri** [comment]
I think this is something you are looking into http://chatterbot.readthedocs.io/en/stable/storage/create-a-storage-adapter.html#creating-a-new-storage-adapter
