### ISSUE TITLE
[QUESTION] session_id suddenly change

### ISSUE THREAD

**Issue by bilalbayasut** [gunthercox/ChatterBot#547]
hi @gunthercox , I tried to embed session in my flask app, and when I create a session, I save the session_id in my database. but when I pass the session_id in generate_response() , then the function call the get() to get the session, suddenly the session changed (as well as the id) , how to solve this? thanks

**Comment by vkosuri** [comment]
@bilalbayasut which version of chatterbot are you using? Use python -m chatterbot --version in your terminal to get version?

**Comment by bilalbayasut** [comment]
0.5.0

**Comment by gunthercox** [comment]
There has been updates to correct a few issues with sessions since the 0.5.0 release. Feel free to check the release notes for more details: https://github.com/gunthercox/ChatterBot/releases. The latest release is 0.5.4. I'd recommend updating to the latest version to check if the problem persists.

**Comment by bilalbayasut** [comment]
@gunthercox how to safely update to the latest? thanks

**Comment by gunthercox** [comment]
ChatterBot can be updated to the latest version using pip. The command is:

```
pip install chatterbot --upgrade
```

**Comment by bilalbayasut** [comment]
can I update it by simply pull origin and merge with my existing one ? thanks @gunthercox

**Comment by vkosuri** [comment]
I don't which OS are you using, If it is Linux I would recommend virtual environments, 

```Bash
virtualenv venv
source venv/bin/activate
pip install --upgrade pip
pip install --upgrade chatterbot
```
