### ISSUE TITLE
Integrate chatscript , which adapter to use and how?

### ISSUE THREAD

**Issue by aliabbasjp** [gunthercox/ChatterBot#551]
Hi,
I need to integerate chatscript  (https://github.com/bwilcox-1234/ChatScript) such that a new Logic adapter named "Chatscript" is possible.
Is this a good thing to do, if yes which methods I need to implement ? And how can I start about doing that?

I need chatscript because it allows us to explicitly model a sequence of conversation and not like a lookup list where responses are looked up from a list database. Is this possible in chatterbot itself without using chatscript?

**Comment by gunthercox** [comment]
Hi @aliabbasjp ChatterBot currently has no support for ChatScript. I actually hadn't heard of ChatScript before but it looks interesting.

I've been working on planning updates to ChatterBot's [training](http://chatterbot.readthedocs.io/en/latest/training.html) data format to support more functionality. The current plans are described here: https://github.com/gunthercox/ChatterBot/wiki/ChatterBot-Corpus-Specification. If you have any input I would definitely be interested in hearing it. I can't promise support for ChatScript integration but similar functionality might be possible to achieve when the new corpus format is introduced.
