### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 48: invalid start byte

### ISSUE THREAD

**Issue by aliabbasjp** [gunthercox/ChatterBot#556]
I just copy pasted following example:
```
# -*- coding: utf-8 -*-
from chatterbot import ChatBot


# Create a new instance of a ChatBot
bot = ChatBot(
    'Default Response Example Bot',
    storage_adapter='chatterbot.storage.JsonFileStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': 'I am sorry, but I do not understand.'
        }
    ],
    trainer='chatterbot.trainers.ListTrainer'
)

# Train the chat bot with a few responses
bot.train([
    'How can I help you?',
    'I want to create a chat bot',
    'Have you read the documentation?',
    'No, I have not'
    # 'This should help get you started: http://chatterbot.rtfd.org/en/latest/quickstart.html'
])

# Get a response for some unexpected input
response = bot.get_response('How do I make an omelette?')
print(response)
```
I get following error:
```

Traceback (most recent call last):
  File "C:/Users/ccx/work/pscripts/conversationalspeech/t2.py", line 27, in <module>
    'No, I have not'
  File "C:\Users\ccx\Anaconda2\lib\site-packages\chatterbot\trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "C:\Users\ccx\Anaconda2\lib\site-packages\chatterbot\trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
  File "C:\Users\ccx\Anaconda2\lib\site-packages\chatterbot\storage\jsonfile.py", line 46, in find
    values = self.database.data(key=statement_text)
  File "C:\Users\ccx\Anaconda2\lib\site-packages\jsondb\db.py", line 98, in data
    return self._get_content(key)
  File "C:\Users\ccx\Anaconda2\lib\site-packages\jsondb\db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "C:\Users\ccx\Anaconda2\lib\site-packages\jsondb\file_writer.py", line 15, in read_data
    obj = decode(content)
  File "C:\Users\ccx\Anaconda2\lib\site-packages\jsondb\compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "C:\Users\ccx\Anaconda2\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\Users\ccx\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ccx\Anaconda2\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 48: invalid start byte

```

**Comment by aliabbasjp** [comment]
Is there any resolution to this?

**Comment by aliabbasjp** [comment]
I am still unable to use chatterbot due to unicode issues.

**Comment by gunthercox** [comment]
Hi @aliabbasjp, sorry about the late reply. Please make sure that you have the latest version of ChatterBot and it's dependencies by running `pip install chatterbot --upgrade`.

Looking at the traceback you can see that the error is being triggered in `jsondb\compat.py` which is one of ChatterBot's dependencies. JsonDB recently had some updates and it's possible that you either have an older version or the latest version has a problem.

What version of Python do you have installed?

**Comment by aliabbasjp** [comment]
@gunthercox Yes I am using the updated latest versions of both.

**Comment by aliabbasjp** [comment]
Also I tried on linux with the same exact problem.

**Comment by gunthercox** [comment]
That is strange, I can't recreate this issue. I'm wondering if is is possibly a difference with Anaconda and regular Python?

**Comment by deepukr85** [comment]
@aliabbasjp
I got same issue when my training dataset is having some  characters like normal white space is causing some issues while I copy data from some other editors which is causing unicode decode error. Pls check your input data, I think that is causing the error.

**Comment by aliabbasjp** [comment]
@deepukr85 @gunthercox  I tried all ways of giving examples but all of them fail like above.

**Comment by vkosuri** [comment]
@aliabbasjp can you try to delete existing ``database.db``, retrain your bot? If still problems exists let us know

**Comment by aliabbasjp** [comment]
@vkosuri  where is this database.db ?

**Comment by vkosuri** [comment]
i think it will be in your current directory, If you are using Ubuntu try ``locate database.db``

**Comment by aliabbasjp** [comment]
@vkosuri  that worked!

**Comment by aliabbasjp** [comment]
@vkosuri @gunthercox  The problem is that I have to delete this database.db each time I run a new script, as there are multiple bot scripts in a directory.

Moreover same error happens if we pass  unicode training statements  in bot.train

Hence should not be closed.

**Comment by vkosuri** [comment]
@aliabbasjp Two things here i observed. May be it will vary.

1. Python2.7
i. In python 2.7 if you train your bot with regular data, it will create a new file called ``database.db`` and then your are trying train your bot with **new data which has unicode values** with name ``database.db`` file Then it is failing.
2. Python3.x
i. You won't see these failures. 

I think @gunthercox have more appropriate answer on this, My initial assumption was, while python2.x trying inserting unicdoe values into json ``database.db`` at that it was failing.

**Comment by gunthercox** [comment]
@vkosuri I don't have a better answer at the moment. I think recommending to delete the database is a poor solution. I need to look into this further to see if I can recreate the issue. If I can recreate it then I can fix it. Unfortunately when I run the code locally, it works. I can't get any unicode errors to show up. This leads me to believe that there is one of the two following problems happening here:

1. There is a local error occurring with the system configuration for those who have encountered this error.
2. There is a decoding issue with the jsondb library: https://github.com/gunthercox/jsondb
