### ISSUE TITLE
Use Semantic Folding Engine to compare text

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#57]
Using Cortical.io's ( http://www.cortical.io ) Semantic Folding Engine, the chat bot might be able to get better performance when identifying the best response for a given input. I'm not sure how well this would work, but it is definitely something to consider.

I'm still researching this, so I'll hopefully have more details on this soon. Have you heard about this before @gunthercox ?

**Comment by gunthercox** [comment]
I haven't heard about this before but it looks very interesting. This might work well as a new logic adapter that takes Cortical's API credentials as a keyword argument.

**Comment by DarkmatterVale** [comment]
That's exactly what I was thinking.

It should be pretty simple to get it to work, but I don't know how effective it would be. Cortical.io seems to relate some similar words to each other very well, but not well for others ( I'm using their demos to explore ). Hopefully I'll get a chance within a couple of days to try to add a logic adapter for this, as long as you would not like to do it yourself?

**Comment by gunthercox** [comment]
Feel free to explore this, I will be traveling for the next four days and won't have a chance to thoroughly experiment with Cortical's API. From what I've seen so far it sounds extremely promising. Keep me posted with what you come up with.

**Comment by DarkmatterVale** [comment]
Sorry for the late reply....Got caught up in some other work. I will be testing this weekend, and will let you know how it goes.

**Comment by gunthercox** [comment]
Awesome, let me know how it goes.

**Comment by DarkmatterVale** [comment]
I'm currently in contact with them and trying to work out some issues/enhancements with the Python-SDK.

Is there currently any way to send information to a LogicAdapter? To add this as a logic adapter, an API-Key will be required to be given to the logic adapter.

**Comment by gunthercox** [comment]
Yes, here is how I would recommend setting this up.

Lets say we create a new ChatBot instance like this:
```python
bot = ChatBot(
    "My ChatterBot",
    storage_adapter="chatterbot.adapters.storage.JsonDatabaseAdapter",
    logic_adapter="chatterbot.adapters.logic.ClosestMatchAdapter",
    io_adapter="chatterbot.adapters.io.TerminalAdapter",
    database="../database.db",
    cortical_api_key="XXXXXX-XXX-XXXXXX-XXXXXX-XXXXXXX"
)
```
Note the last parameter being passed in (` cortical_api_key`). ChatterBot passes all keyword argument parameters to it's adapters. This means you can access these from inside your logic adapter (or any other adapter for that matter).

Then, your new logic adapter would likely look something like this:
```python
class CorticalLogicAdapter(LogicAdapter):
    def __init__(self, **kwargs):
        self.api_key = kwards.get("cortical_api_key")

    def get(self, text, statement_list, current_conversation):
        """
        Post data to cortical api and process results here.
        We can now reference self.api_key any time we need it.
        """
        return response_statement
```

**Comment by DarkmatterVale** [comment]
That sounds like a very elegant way of doing this. Much more elegant than how I would have done it had I not have talked this through :)

As soon as they give some documentation (which is still apparently on their "backlog"), I will get right on this and add a new logic adapter. Sorry for the delay!

**Comment by gunthercox** [comment]
No problem

**Comment by GeraldLoeffler** [comment]
just stumbled across this thread of yours, and not knowing whether you've actually implemented an adapter to the Cortical.io API or not, i thought i should point out that there is a new, simplified Python client to that API: https://github.com/cortical-io/retina-sdk.py

**Comment by gunthercox** [comment]
Hi @GeraldLoeffler, this adapter has not been implemented yet. Thank you, I was unaware of the Python API.
