### ISSUE TITLE
Prioritizing some responses over others

### ISSUE THREAD

**Issue by ArtificialBreeze** [gunthercox/ChatterBot#571]
Hi!
In my case, I have two sets of conversations: general ones (the english corpus you provided, movie conversations,..) and some questions and answers that are relevant to answer technical questions. 
The problem comes up in the fact that these specific conversations are not weighted enough to be selected by the bot. Example:
Q: What is the location of this event?
A: *Some irrelevant answer from english corpus* , but should instead be the specific answer learned.
Is there a way to weight some sentences more than others? I can indeed manually increase the frequency of these phrases in the JSON /MongoDB databases, but is there any efficient way around it?
Many thanks!

**Comment by gunthercox** [comment]
If you have a way to train your bot with the desired responses you could
use the [get_most_frequent_response](
http://chatterbot.readthedocs.io/en/latest/logic/response_selection.html#chatterbot.response_selection.get_most_frequent_response)
response selection method. Training multiple times with the desired data
would increment occurrence counts for those responses and it would ensure
that they get selected.

Using [training](
http://chatterbot.readthedocs.io/en/latest/training.html#training-via-list-data)
to increment the occurrence counts is probably the most efficient way to do
this.

**Comment by ArtificialBreeze** [comment]
Thanks, this makes sense!
