### ISSUE TITLE
Learn_response()

### ISSUE THREAD

**Issue by ArtificialBreeze** [gunthercox/ChatterBot#574]
When using a mongoDB database, I sometimes manually need to save the response in the database.
Assuming ```st1``` and ```st2``` are two valid statements, ```chatbot.learn_response(st1,st2)``` does not seem to do anything.
Any suggestions?

**Comment by gunthercox** [comment]
Hmmm, strange. I can't seem to verify this. I'm checking that this functionality works using the following unit test in [/tests/test_chatbot.py#L117](https://github.com/gunthercox/ChatterBot/blob/master/tests/test_chatbot.py#L117)

```python
def test_learn_response(self):
    previous_response = Statement('Define Hemoglobin.')
    statement = Statement('Hemoglobin is an oxygen-transport metalloprotein.')
    self.chatbot.learn_response(statement, previous_response)
    exists = self.chatbot.storage.find(statement.text)

    self.assertIsNotNone(exists)
```

**Comment by ArtificialBreeze** [comment]
Can this possibly be happening because ```read_only``` is equal to True? I rewrote the ```learn_response()``` method but I think this flag still prevents from writing the database. The goal is essentially to write only specific responses, based on some feedback.

**Comment by gunthercox** [comment]
That sounds like it is probably it. If `read_only` is True, the bot won't learn.

**Comment by ArtificialBreeze** [comment]
Is it possible to make it so that it doesn't learn **all** of the responses, but only some?

**Comment by gunthercox** [comment]
Possibly, under what conditions are you looking to have learning occur? For example, if you only what a bot to learn when talking to a particular user you could do something like:

```python
# Get a response to the input statement
statement, response, confidence = bot.generate_response(input_statement)

# Only learn on this condition
if user.email == 'admin@gmail.com'
    bot.learn_response(response, input_statement)
```

**Comment by ArtificialBreeze** [comment]
I think this will do the job, thanks!
