### ISSUE TITLE
mongodb distinct.. slow. issue.

### ISSUE THREAD

**Issue by vusdo** [gunthercox/ChatterBot#575]
I put 20,000 data in mongo DB now.

The following code will make the query speed too slow.
Response_query = self.statements.distinct ('in_response_to.text')

I need action to improve conversation speed.

Can you recommend it?
thank you.

**Comment by gunthercox** [comment]
Theoretically the distinct shouldn't be needed. I can remove it to correct this issue.

**Comment by vusdo** [comment]
Please explain in more detail.
Thank you..

**Comment by gunthercox** [comment]
Actually, after looking into this a bit further, it doesn't appear that the distinct can be avoided. This method needs to return a list of statements that are responses and it cause larger performance issues if duplicate statements were returned.

It might be possible to improve performance by applying an index, but I currently don't have a way to test what the performance increase (if any) would be.

**Comment by phpmind** [comment]
I would say, using elastic search could be a better choice. But a bit of work involved. https://github.com/elastic/elasticsearch-py/blob/master/docs/index.rst 
I am going to test this and will let you know. 

Once data is in elastic you can visualize and can do a lot more for free using kibana. 
a new adapter needs to be written but it's not that difficult.

**Comment by vusdo** [comment]
I will not use mongodb.
Please suggest a reference.
Thank you.

**Comment by phpmind** [comment]
vusdo@ - You need to install elastic search if you want to use for millions/bill of records and also text based search is very fast. 
 https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-ubuntu-14-04 

Install elastic and kibana. You don't need Logstash. 

Then use this lib to manipulate data,  insert search etc.  https://github.com/elastic/elasticsearch-py/blob/master/docs/index.rst .

This all have a learning curve if you are not using elastic search already. 

Let me know if you have more questions.

**Comment by vusdo** [comment]
I am pleased to learn a new solution.
Thank you for sharing the elasticsearch storage adapter.

**Comment by gunthercox** [comment]
I'm closing this ticket off. It doesn't appear to contain anything actionable to improve ChatterBot.

**Comment by phpmind** [comment]
vusdo - Please share your experience of elastic search implementation.
