### ISSUE TITLE
Chatterbot prints the complete json as response in the chat

### ISSUE THREAD

**Issue by gouthamgtm** [gunthercox/ChatterBot#577]
Hi, 

Instead printing only the 'text' value as response to the input chat from the user, it responds the entire json output there.

python3 --version
Python 3.5.2
python3 -m django --version
1.10.5
python3 -m chatterbot --version
0.5.4

**Input:**
20

**Expected output:**
( 20 ) = 20

**But the output I got:** 
{'text': 'b"{\'extra_data\': {}, \'text\': \'( 20 ) = 20\', \'in_response_to\': [], \'created_at\': datetime.datetime(2017, 1, 13, 14, 59, 18, 347756)}"'}

**Workaround:**

/usr/local/lib/python3.5/dist-packages/chatterbot/ext/django_chatterbot/views.py

**# Modified the below in views.py**
        #response_data = {'text': str(response_data)}
        response_data = {'text': response.text}

Please fix this issue.

Regards,
Goutham GTM

**Comment by gunthercox** [comment]
I believe @buildithub encountered the same issue: https://github.com/gunthercox/ChatterBot/issues/523
It was resolved by using the latest version of the example.
