### ISSUE TITLE
Creating a new logic adapter

### ISSUE THREAD

**Issue by RominYue** [gunthercox/ChatterBot#583]
1. Error
    In Providing extra arguments part, these several lines of code:
```
class MyLogicAdapter(LogicAdapter):
    def __init__(self, **kwargs):
        super(MyLogicAdapter, self).__init__(kwargs)

        self.api_key = kwargs.get('secret_key')
```

**super(MyLogicAdapter, self).__init__(kwargs)** "kwargs" should be "**kwargs"

2. enhancement:
    In Directory structure part, there is only one file example.
    Now I want to put adapter into directory. such as /myadpters/logic/Myadpter.py
    
    Do we must add /myadpters/__init__.py, add /myadpters/logic/__init__.py
    and add content in /myadpters/logic/__init__.py

```
from .MyAdapter import MyAdapter
```

**Comment by gunthercox** [comment]
Hi @RominYue Thank you, I will make adjustments to the documentation to clarify this.
***
Regarding your last question, `from .MyAdapter import MyAdapter` is not required to be added to the `__init__.py` file.

Adding it to `__init__.py` is just a Python convention that allows you to import the class like this:

```python
from myadapters import MyAdapter
```
 instead of like this:

```python
from myadapters.logic.my_adapter import MyAdapter
```

**Comment by RominYue** [comment]
yeah...
but when I want to use it in ChatBot,
```
ChatBot('RominYue',
        logic_adapters=[
            'chatterbot.logic.BestMatch',
            'adapters.logic.MyAdapter'
        ]
    )
```

it would pop out error when I do not add **from myadapters import MyAdapter** in __init__.py

**Comment by gunthercox** [comment]
I'm going to close this off as I believe all of the issues have been addresses. Feel free to reopen it if I missed any documentation changes that were needed,
