### ISSUE TITLE
Google hangouts adapter

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#59]
It would be really cool to have an IO adapter for ChatterBot that makes it possible for a chatbot instance to communicate through the Google Hangouts API.

It may be useful to look at https://github.com/hangoutsbot/hangoutsbot

Pull requests welcomed if anyone is interested.

**Comment by The-Penultimate-Defenestrator** [comment]
I'm already running a chatbot through [discord.py](https://github.com/rapptz/discord.py). I'm running this as a separate script, but maybe it would make sense as an IO adapter?

**Comment by gunthercox** [comment]
That looks promising! I will have to check out how they are accomplishing their [event handling](https://github.com/Rapptz/discord.py/blob/master/examples/reply.py) but something like that may work well.

**Comment by The-Penultimate-Defenestrator** [comment]
I'm pleased with how my bot is working out. The repo in which I've written my code is [here](https://github.com/The-Penultimate-Defenestrator/bergerbot) if you want to take a look at how I'm using discord with chatterbot

**Comment by Arinerron** [comment]
:package:
