### ISSUE TITLE
Issue when getting a response to a known statement

### ISSUE THREAD

**Issue by brunotikami** [gunthercox/ChatterBot#591]
Hello everybody, I've just started with chatterbot so please excuse me if this is not related to your project.

When I try to get a response for a statement for the first time, everything works as expected but when I send it again, I get the following error:

` response = chatter.get_response(payload, session_id)
  File "/bot/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 108, in get_response
    input_statement = self.input.process_input_statement(input_item)
  File "/bot/lib/python2.7/site-packages/chatterbot/input/input_adapter.py", line 24, in process_input_statement
    existing_statement = self.chatbot.storage.find(input_statement.text)
  File "/bot/lib/python2.7/site-packages/chatterbot/storage/mongodb.py", line 121, in find
    values.get('in_response_to', [])
  File "/bot/lib/python2.7/site-packages/chatterbot/storage/mongodb.py", line 141, in deserialize_responses
    return proxy_statement.in_response_to
  File "/bot/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/models.py", line 48, in in_response_to
    return Response.objects.filter(statement=self)
  File "/bot/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/bot/lib/python2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/bot/lib/python2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/bot/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/bot/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/bot/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1183, in build_filter
    condition = lookup_class(lhs, value)
  File "/bot/lib/python2.7/site-packages/django/db/models/lookups.py", line 19, in __init__
    self.rhs = self.get_prep_lookup()
  File "/bot/lib/python2.7/site-packages/django/db/models/fields/related_lookups.py", line 100, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/bot/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 946, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
`

<payload> is a <chatterbot.conversation.Statement> object and I have create a custom LogicAdapter that returns a <chatterbot.conversation.Response> object after processing the input.

Am I doing something wrong with this approach ? 

Thanks,

Tkm

**Comment by gunthercox** [comment]
Hi @brunotikami, could you add a list of step-by-step instructions that I can use to attempt to recreate the error you encountered?

**Comment by brunotikami** [comment]
Sure! I'll remove some business logic from my application but the flow is basically this:

1) a Facebook messaging event is POSTed to my Django view;
2) for each "messaging event" from inside the payload, I do this:

`
# chatterbot_settings is a property that loads the default settings
chatter = ChatBot(self.slug, **self.chatterbot_settings)
        chatter.conversation_sessions = NexusSessionManager()
        chatter.default_session = chatter.conversation_sessions.new()

        session = self.interaction_handler.get_session_for(self, chatter, messaging_event)

        payload = self.interaction_handler.get_payload_from(messaging_event, bot_slug=self.slug)

        response = chatter.get_response(payload, session.id_string)

        self.interaction_handler.send_message(self.page_access_token, self.page_id, session.bot_user.fb_user_id, response)
`

**Comment by gunthercox** [comment]
Ok, so one thing I just noticed as I was checking over your traceback:

> File "/bot/lib/python2.7/site-packages/chatterbot/storage/mongodb.py", line 141, in deserialize_responses
return proxy_statement.in_response_to
> File "/bot/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/models.py", line 48, in in_response_to

I'm assuming that you are using Django with MongoDB as it's database in your project.
I've never actually tested to see if ChatterBot's MongoDB adapter will work with a Django & MongoDB setup. Let me know if I my assumption about your project setup is correct. If so, I will try to set up a project with the same configuration locally to test this out.

**Comment by brunotikami** [comment]
Yes, that's correct. I'm using <chatterbot.storage.MongoDatabaseAdapter> as the storage_adapter while also using the <chatterbot.ext.django_chatterbot> Django app.

**Comment by gunthercox** [comment]
Ok, I'll write up an example and test this out locally as soon as I can.

Just a note, ChatterBot's storage adapters are not the same thing as Django's database backends. By default, ChatterBot will use it's built in _Django storage adapter_ which uses whatever database backend your Django settings are set up to use. So, if you use a Django storage backend like [Django MongoDB Engine](https://django-mongodb-engine.readthedocs.io/en/latest/) then ChatterBot will access your instance of MongoDB through that adapter directly (probably avoiding the error you encountered).

**Comment by brunotikami** [comment]
Sorry, I'm not sure if I got it right. You're saying that I should set the DEFAULT_FILE_STORAGE to django_mongodb_engine (from the backend you've mentioned) or add a different database to the DATABASES map ?

**Comment by brunotikami** [comment]
Hey @gunthercox, any news on this ? Thanks

**Comment by alexpacer** [comment]
I'm getting similar issue. I'm using django 1.10.x and mongodb. 

The exception of
> ValueError: invalid literal for int() with base 10: ''

starts from here
> File "/Users/dev/chatdjango/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/models.py", line 59, in in_response_to
>    return Response.objects.filter(statement=self)

And I tried to switch to JSONfile storage, same problem happened on this line. It seems there'r something wrong with the Statement/Response object who inherits from django model?

**Comment by jonathanglima** [comment]
+1

**Comment by web-maker** [comment]
Hi all. I have a same error. I want to use Django 1.10 and a separate MongoDB for bot data. When I tried to get response from bot, I got an error `invalid literal for int() with base 10: '"`.
I found a bottleneck in StorageAdapter class, in next lines:
`
    def Statement(self):
        """
        Create a storage-aware statement.
        """
        import os

        if 'DJANGO_SETTINGS_MODULE' in os.environ:
            from chatterbot.ext.django_chatterbot.models import Statement
            return Statement
        else:
            from chatterbot.conversation.statement import Statement
            statement = Statement
            statement.storage = self
            return statement 
`
If we use Django - we always get Statement from django models, if we even doesn't need it.
Is it possible to add some option for ChatterBot settings ('use_django_models': True/False, for example), which would triggered what Statement instance we need to use?
I can provide pull request with this changes.

**Comment by gunthercox** [comment]
@web-maker If you are interested in submitting a pull request I would be happy to review it.

**Comment by web-maker** [comment]
@gunthercox Thanks, I added pull request #653

**Comment by gunthercox** [comment]
@web-maker Thank you, I'll check it out.

**Comment by gunthercox** [comment]
I believe this was resolved by #653
