### ISSUE TITLE
Add internal support for different JSON libraries.

### ISSUE THREAD

**Issue by martmists** [gunthercox/ChatterBot#592]
As mentioned in #42, cjson is used when installed automatically to speed up. However, cjson does not yet support Python 3. This is why I'm proposing to add a similar method for a Py3 version of a fast JSON library, such as ujson or python-rapidjson.

**Comment by gunthercox** [comment]
I like this idea. What do you think of the idea of allowing developers to set the JSON library via a parameter?
For example, something like:

```python
chatbot = ChatBot(
    'My Bot',
    # ...
    json_library={
        # json.loads and json.dumps have different method names in various JSON libraries
        'loads': 'import.path.for.json_library.loads',
        'dumps': 'import.path.for.json_library.dumps',
    }
)
```

The advantage would be that it reduces the amount of code that has to be added to ChatterBot to support different JSON libraries in the future. It also gives the developer more control.

**Comment by martmists** [comment]
This looks like a great format to me, along with the advantages for configurable JSON libraries I'd say this is something to work on. I'll see what I myself can do, though I'm not extremely skilled at Python nor do I understand the current way storage based on JSON works.

**Comment by martmists** [comment]
Closing this as I'll be using #597
