### ISSUE TITLE
many-to-many relationship of users and chatterbots

### ISSUE THREAD

**Issue by HelloJyo** [gunthercox/ChatterBot#599]
I am trying to implement an application where **several users** exists and each user can have **many chatterbots**. Each bot needs to have **its own** training data.  I am using **mongo db** as the storage adapter. How can I do it?

**Comment by vkosuri** [comment]
Yes this is possible, you can as many as but point single storage adapter. For more information read http://chatterbot.readthedocs.io/en/stable/storage/index.html

**Comment by HelloJyo** [comment]
To be more specific, **I want to store the bot_id (that identifies a unique bot of a user) along with the training data** in the collection(ie, 'statements'). The training data of a bots is unique and is meant only for that particular bot. When giving responses a bot will only look upon its own training data set by comparing the current bot_id to the stored one in the training data set.

**Comment by vkosuri** [comment]
I think it is very much similar issue https://github.com/gunthercox/ChatterBot/issues/357

For creating multiple instances of db on same server this link will help you http://stackoverflow.com/questions/15124610/multiple-instances-of-mongo-db-on-same-server

**Comment by vkosuri** [comment]
@HelloJyo I am closing this issue, if you need any specific information please feel free to reopen this issue.

**Comment by HelloJyo** [comment]
**how can i filter the responses so that each bot will get responses that are meant for them**. All the training data are residing in the same collection. Thus selecting a response means first **check the bot_id** (which are saved during training of each bots) and if the test passes the bot can have access to the particular response. How can I filter responses with respect to the bot_id.

**Comment by gunthercox** [comment]
Hi @HelloJyo, right now ChatterBot doesn't have this functionality built in. I'm aiming to introduce it in a future release but I'm still working on changes that will make it possible to select responses from a specific bot in situations where multiple bits are being used.

**Comment by HelloJyo** [comment]
thanks guys...I'm gonna give it a try
