### ISSUE TITLE
IRC adapter

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#60]
It would be interesting to have an IO adapter for ChatterBot that makes it possible for a instance of the program to communicate through an IRC client. I don't have a lot of experience with IRC, but this would be a great addition and a pull request would be welcomed if anyone is ever interested.

**Comment by SethDusek** [comment]
You should take a look at the twisted framework

**Comment by bloodywing** [comment]
There are a lot for python, I can try to write one. I already did some irc stuff in the past with python. But never really used twisted for this. Only circuits so far, which is async as well. The most straight forward way would be to use socket. http://wiki.shellium.org/w/Writing_an_IRC_bot_in_Python Without adding the twisted dependency or one for any other library. Keep in mind that the bot needs it's own loop.

**Comment by gunthercox** [comment]
I would be more than happy to accept a pull request if this can be accomplished. I have had people ask me about this before which is why I created the ticket. Again, I don't know a ton about IRC so I can't offer much help if you want to look into this.

One idea which might help is that I have been considering designing an adapter for email communication. The structure is set up so that there is a background thread that periodically checks for a new message. If it finds one, it saves it in a queue until a get_latest_message method is called. I'm wondering if a similar structure would work in this case?

**Comment by bloodywing** [comment]
I doubt that. IRC has a constant stream which you buffer periodically. I doubt your email adapter works like that. (If I understand the irc protocol correctly)

**Comment by LucasZielke** [comment]
What I have researched of IRC is that it requires you to "Pong its Pings", which could really be a problem if you start to get more and more information in your database (because of processing time), so you would have to have it ping ponging and trying to find a proper response for the message in a different thread or vice versa

**Comment by bloodywing** [comment]
In IRC your database can get easily > 1.3MB which gave me a processing time of more than 20 Minutes for a single response, even with MongoDB.

**Comment by LucasZielke** [comment]
@bloodywing do you mean a tails file for the IRC? I am referring to accessing the MongoDB that holds all of the i/o for the chatbot itself

**Comment by bloodywing** [comment]
@LucasZielke Nope, I mean the json file handler but thats a problem with chatterbot itself when. What you want to do with the bot is idling in the irc and following conversations and respond when the boot sees a specific keyword (like the botname or !botrespond) I already did something similar with the bot on a simple website with message system and an API and parsed the conversation. But should the bot save all lines in irc? And use them to respond? This is what I mean, if you save everything in irc you DB would get huge.

**Comment by LucasZielke** [comment]
@bloodywing  Haha if it saved all of the convo from the irc channel youd make one cruel bot

**Comment by AlexanderLJ** [comment]
>Would the best way to implement the response while ping ponging be to multi thread the ping ponging and in the foreground be looking for the proper response?

This is how I do it in my IRC bot that is based on async.  My bot is modular and threaded and It replies to the ping/pongs when needed, then feeds for example what is being said in a channel to any plugin that needs it (or only when there is a certain trigger).
