### ISSUE TITLE
Django JSON reply is invalid JSON format

### ISSUE THREAD

**Issue by thedp** [gunthercox/ChatterBot#602]
I'm having some trouble parsing the reply from django.
It seems the reply contains single quotes instead of JSON standard double quote.
Also, other values that can't be converted with javascript jsonParse, like datatime: `'created_at': datetime.datetime(2017, 1, 22, 17, 38, 35, 878994)`.

Is it a bug?

Thanks.

**Comment by vkosuri** [comment]
@thedp can you elaborate more on this issue?

**Comment by alekaizer** [comment]
@thedp datetime is not JSON serializable 
Maybe you receiving a byte-type response too, can you provide more infos ?

**Comment by thedp** [comment]
@vkosuri 
The JSON reply is structured like this:   `{"text":{'text':'something', 'created_at': datetime.datetime( . . `

@alekaizer What kind of info should I provide?

**Comment by gunthercox** [comment]
I've identified the cause of this issue. Working on a fix.
