### ISSUE TITLE
Can we use botkit to use chatterbot cross platform interface ?

### ISSUE THREAD

**Issue by phpmind** [gunthercox/ChatterBot#603]
https://github.com/howdyai/botkit 

botkit is API based so i guess somehow we can make it ?

**Comment by gunthercox** [comment]
Hi @phpmind, assuming you have access to an API for a botkit app you can definitely make requests to it from ChatterBot. Vice versa, it would not be difficult to create a small API based Python app that could provide responses to a botkit based chatbot. (Either should be able to get information from each other depending on the setup you desire).

Your question doesn't make it entirely clear what information you are looking for. Yes, you can write code to use HTTP request to access information between chat bot's written in different programming languages. For Python I highly recommend the [requests](http://docs.python-requests.org/en/master/) framework.
