### ISSUE TITLE
The confidence level of the answer

### ISSUE THREAD

**Issue by kushalbabel** [gunthercox/ChatterBot#607]
Is there any way of getting to know about how much the bot is confident while answering a question?
The purpose is, if the confidence is low, i would redirect the question to a human and learn the answer for future
It would be great if you could reply fast because I have some deadlines
Thanks for the awesome code

**Comment by vkosuri** [comment]
I think it is based on your comparison method used 
More info http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-comparison

**Comment by kushalbabel** [comment]
No, I dont have the other statement to compare with. I just want to know if my corpus has some "good enough" answer or not

**Comment by gunthercox** [comment]
Hi @kushalbabel, the confidence score is returned with the statement when you call `.get_response()`. So for example:

```python
response = mychatbot.get_response(input)
print response.conficence
>>> 0.25
```

**Comment by vkosuri** [comment]
Thanks Master @gunthercox

**Comment by kushalbabel** [comment]
Thanks you so much @gunthercox  @vkosuri

**Comment by vacharich1** [comment]
@gunthercox

response = mychatbot.get_response(input)
print response.conficence

it doesn't work.

**Comment by vacharich1** [comment]
i got it @gunthercox
