### ISSUE TITLE
Removing corpus data

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#611]
@gunthercox Master, Due to new repository [chatterbot-corpus](https://github.com/gunthercox/chatterbot-corpus). I am planning remove corpus data and tests from this repo. Let me know your inputs

**Comment by gunthercox** [comment]
I agree with this decision. Let's make sure that the following steps have been completed before removing the data from the `chatterbot` repository.

- [x] The corpus data has been copied to the `chatterbot-corpus` module.
- [ ] ChatterBot's documentation has been updated to describe how to download or install the ChatterBot corpus data.
- [ ] Check if any changes need to be made to ChatterBot's corpus trainer for it to work with the files from the `chatterbot-corpus` module.
