### ISSUE TITLE
Replace get_response_statements method with filtering

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#613]
Storage adapters have a `get_response_statements` method that returns all statements that are in response to another statement. A much more elegant solution would be to have the `filter` method be versatile enough to return this same information.

**Comment by vkosuri** [comment]
@gunthercox Master,

 [filter](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/storage/storage_adapter.py#L69) state that ``Returns a list of objects from the database.`` and 

[get_response_statements](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/storage/storage_adapter.py#L106) `` Return only statements that are in response to another statement.``

Question is What are different filters are we going support?

**Comment by gunthercox** [comment]
@vkosuri, some of the other filtering options will likely just be join operations on related fields. The setup will likely end up being similar to the way Django does their filtering for querysets.
