### ISSUE TITLE
context based reply.

### ISSUE THREAD

**Issue by janMbugti** [gunthercox/ChatterBot#616]
hi i want to get reply on context based.... example if i trained my bot with two sets of conversations i.e 
conversation_1=["hi","hi too","please send me sms packages","these are sms packages","price?","these are sms price list"]
conversation_1=["hi","hi too","please send me internet packages","these are internet packages","price?","these are internet price list"]

Note: Now against price statement we have two responses 1("these are sms price list"),2("these are internet price list").......now problem is that when i entered price? it reply some time sms related response and some time internet related ,Now i want  it reply based on previous based dailogs mens my previous dailogs if sms related then it reply sms based response...

**Comment by gunthercox** [comment]
Hi @janMbugti, I am aware of this issue. I am currently working on a fix. The issue stems from the current lack of the ability of the chat bot to search it's knowledge graph for similar conversation sequences. I'm hoping to introduce this functionality in an upcoming major release but there is still a good amount of design work that I need to complete.

**Comment by vkosuri** [comment]
@janMbugti Master already addressed your question hence i am closing this issue, please feel free reopen this issue if you have anything to discuss further.
