### ISSUE TITLE
A Question about Input Adaptors / Output Adaptors

### ISSUE THREAD

**Issue by LorenDavie** [gunthercox/ChatterBot#619]
I'd like to build a chatbot that integrates with (among other things) Facebook Messenger, Slack, and SMS. It looks like there's currently no adaptors for these platforms, nor do I see it anywhere in the roadmap (maybe I'm missing it though).

Any interest in this stuff?  I suppose I could fork Chatterbot, build these adaptors out and submit pull requests. Is this the sort of thing you would theoretically want in the project?

Thanks - Loren

**Comment by LorenDavie** [comment]
Forgot to mention, - I started working on a similar project (https://github.com/Axilent/talkback) a ways back, but I'd rather contribute to a project with momentum than handling this stuff all by myself.

**Comment by phpmind** [comment]
We already have   Microsoft bot framework. 

https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/output/microsoft.py

**Comment by gunthercox** [comment]
Hi @LorenDavie, thank you for your interest in contributing. I actually have plans to eventually phase-out ChatterBot's input and output adapters in favor of making the library simpler. More details on this can be found here: https://github.com/gunthercox/ChatterBot/issues/528

Let me know if you have any questions.

**Comment by vkosuri** [comment]
@LorenDavie I am closing this issue, Please feel free to reopen if you have any thoughts/ideas on this issue.
