### ISSUE TITLE
How to remove old response statements

### ISSUE THREAD

**Issue by HelloJyo** [gunthercox/ChatterBot#620]
When a new response for an **existing**  user-query is given in the training process, how can I **delete the old response** and replace it with the new one?

**Comment by vkosuri** [comment]
I think this will address your question ‎https://github.com/gunthercox/ChatterBot/blob/master/tests/conversation_tests/test_statements.py#L35

**Comment by vkosuri** [comment]
@HelloJyo did i answer your question?
