### ISSUE TITLE
May be a django_storage.py bug

### ISSUE THREAD

**Issue by zorrofox** [gunthercox/ChatterBot#622]
I think the last [line](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/storage/django_storage.py#L153) of the django_storage.py may not correct, because according to the logic description:

> Return only statements that are in response to another statement.
        A statement must exist which lists the closest matching statement in the
        in_response_to field. Otherwise, the logic adapter may find a closest
        matching statement that does not have a known response.

The query statement should be "RESPONSE_ID IN ..." but
```
Statement.objects.filter(in_response__in=responses)
```

change to "STATEMENT_ID IN ..." and I think the correct coding should be

```
Statement.objects.filter(responses__in=responses)
```

**Comment by vkosuri** [comment]
@zorrofox see this line is suggesting ``in_response_to`` converted into [in_response](https://github.com/gunthercox/ChatterBot/blob/7e443ad9d895d08a48e13fb74de28ff9589fc507/chatterbot/storage/django_storage.py#L50). In this context ``in_response`` object referring to another statement, so i think it should be

``` Python
Statement.objects.filter(in_response__in=responses)
```

**Comment by zorrofox** [comment]
I  don't very understand your meaning. But the test fact is also showing the logic is not correct. Bellow is separately training English Greetings CORPUS with JSON file storage and Django storage adapter logging.basicConfig(level=logging.INFO) output:
![image](https://cloud.githubusercontent.com/assets/1528417/23020586/b6cb5eec-f482-11e6-956e-f99987d035dd.png)
![image](https://cloud.githubusercontent.com/assets/1528417/23020618/d9639d5c-f482-11e6-9c88-541653aae056.png)

**Comment by vkosuri** [comment]
@zorrofox Thanks, if possible could you create pull request for this issue?

**Comment by zorrofox** [comment]
Sure! I have created one please review.
