### ISSUE TITLE
Training with UbuntuCorpusTrainer - Arguments invalid

### ISSUE THREAD

**Issue by KgotsoK** [gunthercox/ChatterBot#623]
When I try to use the ubuntu corpus trainer, the app fails with the following trace. It seems like the trainer is being called with two arguments (which is correct according to the documentation) but only one is expected by the function. That's my noob observation - I could be wrong. Please help.

By the way, I'm just editing the included django app example code. only edited the ChatterBot settings declaration block to:
```
CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'trainer': 'chatterbot.trainers.UbuntuCorpusTrainer',
    'database': './db.sqlite3'
}
```

**To get this error:**
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/oberyn/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/oberyn/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/oberyn/.local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/oberyn/.local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/ext/django_chatterbot/management/commands/train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
TypeError: train() takes exactly 1 argument (2 given)
```

**Comment by vkosuri** [comment]
The problem you didn't passed training data, Look this test you will get some idea https://github.com/gunthercox/ChatterBot/blob/master/tests/training_tests/test_ubuntu_corpus_training.py#L28

More info http://chatterbot.readthedocs.io/en/stable/django/training.html#training-settings

**Comment by KgotsoK** [comment]
My assumption was that the UbuntuCorpusTrainer downloads the training data :-/

**Comment by KgotsoK** [comment]
Thanks @vkosuri 

have a look at https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py#L312

`UbuntuCorpusTrainer`'s `train()` method really does take one arg. I'm trying to figure out where two are given :-/

**Comment by KgotsoK** [comment]
Also @vkosuri Do you know where to find corpora for the ListCorpusTrainer?

**Comment by vkosuri** [comment]
https://github.com/gunthercox/ChatterBot/tree/master/chatterbot/corpus/data

**Comment by KgotsoK** [comment]
This is actually a valid issue. I edited line 312 of trainers.py to add an extra (arbitrary) argument for UbuntuCorpusTrainer's train() method. worked like a charm!

Oh and about the   ListCorpusTrainer corpora, I meant additional ones outside of this repo. I think for ChatterBot to work in an at least decent manner, it needs much more training data.

**Comment by KgotsoK** [comment]
So this is how my CHATTERBOT settings code looks now:

```
CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'trainer': 'chatterbot.trainers.UbuntuCorpusTrainer',
    'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
    'database': './db.sqlite3',
    'logic_adapters': [
        'chatterbot.logic.BestMatch'
    ],
    'filters': [
        'chatterbot.filters.RepetitiveResponseFilter'
    ]
}
```

I ran the `train()` method and the extraction ran successfully. Then almost instantaneously, the line `ChatterBot trained using "UbuntuCorpusTrainer"` appeared. Im pretty certain that it's not trained because:

1. The files add up to over 1GB - No way the trainer took less than a second
2. The `sqlite3` database has nothing (Im assuming thats where the training results get stored as my configuration above states.
3. I ran my bot and yeah, nothing happened clearly (from the responses I'm getting)

As I'm looking at the console output, and comparing it to the code for `UbuntuCorpusTrainer` I realise that the trainer may be looking for the `*.tsv` files in the `data` folder and not its subfolders? Not a python expert. Please see the console output snippet below.

![123](https://cloud.githubusercontent.com/assets/10826423/22829162/cf817e72-efa9-11e6-9655-d12ba556c1a8.png)

**Comment by michaelMinar** [comment]
I'm seeing the exact same issue as @KgotsoK. I run the sample code and it takes about 30 minutes to extract the training data, then trains instantaenously and leaves me with an empty database.db file.

**Comment by KgotsoK** [comment]
Back to AIML... https://github.com/Program-O/Program-O
