### ISSUE TITLE
Interface GUI

### ISSUE THREAD

**Issue by Mustyy** [gunthercox/ChatterBot#625]
Hi 
I was wondering if there is a way to deploy chatterbot on a site or a platform after im done training it using my  terminal
any ideas?

**Comment by vkosuri** [comment]
You can use diferent public cloud applications for your app for example [AWS](aws.amazon.com/), [Heroku](heroku.com). Here an example app rl[chatterbot-live-example](https://github.com/vkosuri/chatterbot-live-example)

**Comment by vkosuri** [comment]
@Mustyy I am closing this issue, if you have any thoughts to improve this thread please feel free to reopen this issue.

**Comment by gunthercox** [comment]
Currently there is no way to deploy a trained chat bot, I would highly recommend training the bot _after_ it is deployed to a hosting service such as AWS.
