### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by Sofia8** [gunthercox/ChatterBot#626]

**Comment by lucaszanella** [comment]
This is because the default Storage Adapter os jsonAdapter, which is for
test only, so it gives this warning because if used in production you'll
suffer from serious performance hits

Em 12 de fev de 2017 08:23, "Sofia8" <notifications@github.com> escreveu:

**Comment by vkosuri** [comment]
@Sofia8 I am closing this issue, if you need any help please feel free to reopen this issue.
