### ISSUE TITLE
How could I fix this issues?

### ISSUE THREAD

**Issue by Near-Tam** [gunthercox/ChatterBot#628]
RuntimeError: Model class chatterbot.ext.django_chatterbot.models.Statement doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by KgotsoK** [comment]
Does your Django app settings include the lines marked with arrows?

```
# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot.ext.django_chatterbot',     <-----------
    'example_app',                          <----------- What I think is the app_label
)
```

**Comment by Near-Tam** [comment]
when I set Django app as this:
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot.ext.django_chatterbot',
    'meizu_ai',
]


the result is :

**Comment by Near-Tam** [comment]
when I set Django app as this:
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot.ext.django_chatterbot',
    'meizu_ai',
]


the result is:
ValueError: invalid literal for int() with base 10: ''
[13/Feb/2017 16:20:47] "GET /query/?q=%E4%BD%A0%E5%A5%BD%2F*%2F1111 HTTP/1.1" 500 17898

**Comment by vkosuri** [comment]
@Near-Tam Did you problem is resolved, Could you please elaborate your problem to understand more. Which version chatterbot are you using?
Could you please share stack trace of your problem.

And also If Django settings should like this

``` Django
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot.ext.django_chatterbot',
    'example_app',       
    'meizu_ai',
]
```

**Comment by gunthercox** [comment]
I'm closing this issue because it is inactive and there wan't enough information provided to recreate the problem.
