### ISSUE TITLE
getting following error while testing django example

### ISSUE THREAD

**Issue by kumarneeraj2005** [gunthercox/ChatterBot#635]
django.core.exceptions.ImproperlyConfigured: Requested setting CHATTERBOT, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

hi
{'text': u'hi', 'created_at': datetime.datetime(2017, 2, 24, 17, 15, 31, 350875, tzinfo=<UTC>), 'extra_data': {}, 'in_response_to': [{'text': u'Hi', 'occurrence': 1}, {'text': u'Hello', 'occurrence': 1}]}

**Comment by kumarneeraj2005** [comment]
Please guide me how to solve this issue.

**Comment by gunthercox** [comment]
Hi @kumarneeraj2005, based on the information you have provided I cannot determine how you encountered this problem. Can you provide a list of steps that I can use to recreate this issue?

**Comment by darenr** [comment]
@kumarneeraj2005 I think the app is working, the response contains "hi" which is "correct". I think what you're noticing is that the serialization of the api is not valid json, the api returns a json structure with the "text" node pointing to python serialized (as opposed to json) so you get in the app the data that you show. This is why the app shows the following:

![screenshot from 2017-02-28 14-43-49](https://cloud.githubusercontent.com/assets/5496117/23437786/3ff49496-fdc4-11e6-9fc8-5dbc8abf9961.png)

**Comment by gunthercox** [comment]
Hi @darenr, the issue you are seeing was fixed in https://github.com/gunthercox/ChatterBot/pull/608, it will be available for download when the next version of ChatterBot is released.

**Comment by darenr** [comment]
@gunthercox awesome, thanks, I also fixed it in my local copy, but I'm glad to hear there's a new version, the project has a lot of interesting ideas.
