### ISSUE TITLE
Forcing a String to generate a response from chatterbot

### ISSUE THREAD

**Issue by alequeiroz** [gunthercox/ChatterBot#639]
I'm currently to build a system that process some errors and returns a string message, and need to force it,  changing the "Keyboard" to a str variable, for chatterbot give a response. Anyone have any idea how to do this?

**Comment by gunthercox** [comment]
Hi @alequeiroz, I'm not exactly certain what you mean by "force". Do you just need a string type value to be returned from ChatterBot?

**Comment by alequeiroz** [comment]
Hello @gunthercox Not returned, but inserted in someway, instead of getting the value from the keyboard, i need to use string that is in my python program.

**Comment by gunthercox** [comment]
Have a look at this example: https://github.com/gunthercox/ChatterBot/blob/master/examples/basic_example.py

I believe it is pretty close to what you are looking for.
