### ISSUE TITLE
When I use chatterbot, it seems to be giving responses I didn't train it to give.

### ISSUE THREAD

**Issue by neatville** [gunthercox/ChatterBot#648]
Here's my setup. 
```
chatterbot = ChatBot("Training Example",
	database='CommentDatabase.json',
	logic_adapters=[	
	    {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.70,
            'default_response': 'OhNo'
        }
        ],

	)
chatterbot.set_trainer(ChatterBotCorpusTrainer)

chatterbot.train(
    "chatterbot.corpus.test"
)  
```

I thought it only gave the types of responses originally found in the corpus (then the database, the corpus I created was pretty small). An example of it not doing what it's supposed to be doing, is if it receives a 'no' response, it might type 'No' back. Another weird thing is it has given responses that were previously received as questions. Does it also get trained each time `chatterbot.get_response()` is called? 

```
for q in questions:
	full_text = q.find_element_by_class_name("full-text").text
	if len(full_text) < 20:
		print(full_text)
		response = chatterbot.get_response(full_text)
		if response == 'OhNo':				
			continue
```
Inside of the test folder: 
http://pastebin.com/UVCyKYYB 
http://pastebin.com/JNmzSrN4

I also wondered if any json file I had was malformed, like a missing or extra comma, an unclosed quote, etc. There doesn't seem to be any of those things going on. I did not write any code to actually store the types of input it gets, other than inside of the variables of course until the looping is done with.  
Of course, I deleted the CommentDatabase.json file a number of times to try and get it to start fresh from the corpus I specified, but it continued to behave poorly like the two examples I've given.

**Comment by shafaypro** [comment]
Same is the case here. I am even getting unexpected results. If i train it only for Corpus and the previously i trained only for greetings. Still it retrieves bad output (which i have never trained ) some times simple "single letter words". I did deleted the json file still.

**Comment by shafaypro** [comment]
I checked it , There was a path difference as well if you are using an IDE like PYCHARM, check the path that the pYCHARM is considering , there must be another json file which its referring too. I checked it and i did had on the active path of PYCHARM. plus I did faced some anonymus responces like "V" <-- only when i said "Tweet on twitter"

**Comment by neatville** [comment]
Interesting, I didn't see another file it was referring to. I didn't use PyCharm for it, but the problem seemed to just go away after I started using mongodb. Not sure if that's what solved it or not, in my case.

**Comment by gunthercox** [comment]
@neatville Your chat bot does get trained each time `chatterbot.get_response()` is called. This is by design to help the chat bot learn to communicate. You can also disable this learning by passing the parameter `read_only=True` to the `ChatBot` class.
