### ISSUE TITLE
about chatterbot machine learning technique

### ISSUE THREAD

**Issue by johnduxx** [gunthercox/ChatterBot#649]
Dear Altruist,

I want to contribute in this project. Before going to join with it, i have a very simple question. What machine learning techniques has been used in this project?

Can you please share in details if possible?

**Comment by vkosuri** [comment]
The purpose of [chatterbot ](http://chatterbot.readthedocs.io/en/stable/index.html) is use in [Salvius the Robot ](http://blog.salvius.org/) for more information available [here](http://blog.salvius.org/2014/09/when-good-chat-bots-go-bad.html).

The major techniques used here, as far of i know

1. You could [train](http://chatterbot.readthedocs.io/en/stable/training.html) your bot
2. Build your [corpus data](http://chatterbot.readthedocs.io/en/stable/corpus.html)
3. Store corpus into different [DB](http://chatterbot.readthedocs.io/en/stable/storage/index.html)
4. You could apply [preprocessors ](http://chatterbot.readthedocs.io/en/stable/preprocessors.html) on your corpus.
5. [Django integration](http://chatterbot.readthedocs.io/en/stable/django/index.html)

**Comment by gunthercox** [comment]
Hi @johnduxx I'm glad you're interested in contributing to this project. To answer your question, ChatterBot uses a number of algorithms to select a response. ChatterBot is designed to be modular so each response selection algorithm is broken up into its own module called a logic adapter. A number of logic adapters have been written, at the moment most of them implement search-based artificial intelligence to select an appropriate response to the user's input. Bayesian networks are also used but to a limited extent.

I have been researching seq-to-seq machine learning methods using technologies such as TensorFlow, maybe in the future ChatterBot will have these capabilities as well.

Let me know if you have any further questions 😃

**Comment by arafat-al-mahmud** [comment]
@gunthercox  Please correct me if I am wrong.

For the sake of **Search-based artificial intelligence** I have found following optional algorithms implemented in **ChatterBot** that can be used as the 'statement_comparison_function' for a logic adapter:

**_levenshtein_distance_** : for measuring character based text similarity

**_synset_distance_** : for calculating the synonymous similarity between statements

**_jaccard_similarity_** : for measuring term based text similarity

And **Bayesian networks** is used in comparing _sentiments_.

**Comment by gunthercox** [comment]
@arafat-al-mahmud That is correct.
