### ISSUE TITLE
Closest Meaning Logic Adapter improvements

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#65]
The [Closest Meaning Logic Adapter](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/adapters/logic/closest_meaning.py) currently only checks the path similarity between the first synset for each word (`synset1[0].path_similarity(synset2[0])`). This heuristic might be more accurate if it selected the maximum (shortest path) pair of synsets for the two words.

Because this operation might greatly increase the amount of time required to process each result, it may be useful to look into the possibility of caching logical evaluations made by this adapter on the statement object when it is saved to the database. Then, the check would only need to be processed if the value of the overall synonymous meaning between two statements had not already been evaluated.

**Comment by DarkmatterVale** [comment]
Why did you decide to go with path_similarity as opposed to wup_similarity? The advantage of wup_similarity is that it predicts based on the most specific sense of the word, which might give you a better result depending on what synsets are available for any given word.

**Comment by gunthercox** [comment]
Thank you, I didn't know about `wup_similarity` until now. I will look into it.

**Comment by DarkmatterVale** [comment]
No problem! Let me know if I can help in any way. Give me a little lead time though, because I'm currently working on adding a logic adapter for using SVO comparisons ( which requires I redesign part of my regex4dummies library, so its taking a little while ).
