### ISSUE TITLE
Extracting certain 'key words' from a sentence

### ISSUE THREAD

**Issue by shank7485** [gunthercox/ChatterBot#652]
How can we make the bot to extract certain keywords from a sentence?

Example 1:

`User Question:         What is the weather in Seattle?`

_(Bot reads keyword 'Seattle'. Gets weather in Seattle by some Weather API. Return the weather)_

`Bot Answer:              Weather in Seattle is XX.`

Example 2:

`User Question:          May I know the weather in London?`

_(Bot reads keyword 'London'. Gets weather in London by some Weather API. Return the weather)_

`Bot Answer:              Weather in London is XX. `

In the above question, I need to extract the key words 'Seattle' and 'London'. How is this possible in the chatbot? 

Any idea how to implement this feature?

**Comment by gunthercox** [comment]
This sounds like a structured data analysis problem. I'd recommend taking a look at some of the functionality provided by NLTK http://www.nltk.org/book/ch07.html

**Comment by vkosuri** [comment]
I think this might also help you https://textblob.readthedocs.io/en/dev/
