### ISSUE TITLE
Duplicate 'fact'

### ISSUE THREAD

**Issue by sks4903440** [gunthercox/ChatterBot#656]
The bot displays the same fact after repeated queries.
![a](https://cloud.githubusercontent.com/assets/15520349/24043303/0e1dd556-0b3c-11e7-8666-814c59c49e58.png)

**Comment by vkosuri** [comment]
@sks4903440 Is your problem is resolved? If not can you describe you problem detail?

**Comment by sks4903440** [comment]
Its resolved.
