### ISSUE TITLE
Chatterbot Not installed properly using anaconda

### ISSUE THREAD

**Issue by Jaivignesh92** [gunthercox/ChatterBot#657]
//anaconda/lib/python2.7/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning

**Comment by Jaivignesh92** [comment]
---------------------------------------------------------------------------
BadZipfile                                Traceback (most recent call last)
<ipython-input-8-fe29959b3109> in <module>()
      2 
      3 # Create a new chat bot named Charlie
----> 4 chatbot = ChatBot('Charlie')
      5 
      6 # Get a response to the input text 'How are you?'

//anaconda/lib/python2.7/site-packages/chatterbot/chatterbot.pyc in __init__(self, name, **kwargs)
     81 
     82         if kwargs.get('initialize', True):
---> 83             self.initialize()
     84 
     85     def initialize(self):

//anaconda/lib/python2.7/site-packages/chatterbot/chatterbot.pyc in initialize(self)
     92         nltk_download_corpus('corpora/stopwords')
     93         nltk_download_corpus('corpora/wordnet')
---> 94         nltk_download_corpus('tokenizers/punkt')
     95         nltk_download_corpus('sentiment/vader_lexicon')
     96 

//anaconda/lib/python2.7/site-packages/chatterbot/utils.pyc in nltk_download_corpus(resource_path)
    116 
    117     try:
--> 118         find(resource_path)
    119     except LookupError:
    120         download(corpus_name)

//anaconda/lib/python2.7/site-packages/nltk/data.pyc in find(resource_name, paths)
    626                                      [pieces[i] + '.zip'] + pieces[i:])
    627             try:
--> 628                 return find(modified_name, paths)
    629             except LookupError:
    630                 pass

//anaconda/lib/python2.7/site-packages/nltk/data.pyc in find(resource_name, paths)
    612                 if os.path.exists(p):
    613                     try:
--> 614                         return ZipFilePathPointer(p, zipentry)
    615                     except IOError:
    616                         # resource not in zipfile

//anaconda/lib/python2.7/site-packages/nltk/compat.pyc in _decorator(*args, **kwargs)
    559     def _decorator(*args, **kwargs):
    560         args = (args[0], add_py3_data(args[1])) + args[2:]
--> 561         return init_func(*args, **kwargs)
    562     return wraps(init_func)(_decorator)
    563 

//anaconda/lib/python2.7/site-packages/nltk/data.pyc in __init__(self, zipfile, entry)
    467         """
    468         if isinstance(zipfile, string_types):
--> 469             zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
    470 
    471         # Normalize the entry string, it should be relative:

//anaconda/lib/python2.7/site-packages/nltk/compat.pyc in _decorator(*args, **kwargs)
    559     def _decorator(*args, **kwargs):
    560         args = (args[0], add_py3_data(args[1])) + args[2:]
--> 561         return init_func(*args, **kwargs)
    562     return wraps(init_func)(_decorator)
    563 

//anaconda/lib/python2.7/site-packages/nltk/data.pyc in __init__(self, filename)
    977         if not isinstance(filename, string_types):
    978             raise TypeError('ReopenableZipFile filename must be a string')
--> 979         zipfile.ZipFile.__init__(self, filename)
    980         assert self.filename == filename
    981         self.close()

//anaconda/lib/python2.7/zipfile.pyc in __init__(self, file, mode, compression, allowZip64)
    768         try:
    769             if key == 'r':
--> 770                 self._RealGetContents()
    771             elif key == 'w':
    772                 # set the modified flag so central directory gets written

//anaconda/lib/python2.7/zipfile.pyc in _RealGetContents(self)
    809             raise BadZipfile("File is not a zip file")
    810         if not endrec:
--> 811             raise BadZipfile, "File is not a zip file"
    812         if self.debug > 1:
    813             print endrec

BadZipfile: File is not a zip file

**Comment by vkosuri** [comment]
@Jaivignesh92 chatterbot supported environments are listed [here ](https://github.com/gunthercox/ChatterBot/blob/master/setup.py#L60). A typical related [issue ](https://github.com/gunthercox/ChatterBot/issues/637)
