### ISSUE TITLE
Django Chatterbot JSON Error

### ISSUE THREAD

**Issue by laffyfx** [gunthercox/ChatterBot#658]
Hi! Quick note: I _just_ got into this whole "python/linux" thing so I'm sorry if I sound like a dummy.

On typing literally anything into the most recent version of the Django ChatterBot example (I installed all dependencies with [this file](https://github.com/gunthercox/ChatterBot/blob/master/requirements.txt)), I receive a string of "de-serialized" JSON (again, I'm new, so I'm not sure if that's the right term). This continues for the rest of the conversation with it. There are no errors in the terminal either.

I've seen some other issues about this, but I haven't been able to fix it.

Screenshot:
![vmware_2017-03-18_13-31-29](https://cloud.githubusercontent.com/assets/8283660/24074480/fedc8804-0bdf-11e7-89a6-2c70953f0a28.png)

**Comment by laffyfx** [comment]
After reading [this fix](https://github.com/gunthercox/ChatterBot/issues/523#issuecomment-268476276) and trying it, I now experience this once input is submitted:
[Screenshot here](http://i.imgur.com/xhdKBFM.png)

I'm going to try reinstalling everything from the requirements.txt file and see what I can do from there.

**Comment by vkosuri** [comment]
@laffyfx which version of chatterbot are you using? To get version of chatterbot use below command

```Bash
python -m chatterbot --version
```

If you are not using latest [version ](https://github.com/gunthercox/ChatterBot/releases/tag/0.5.5) you could upgrade by using 
```
pip install --upgrade chatterbot
```

I think this was fixed on https://github.com/gunthercox/ChatterBot/pull/608. Let us know still you are facing this issue?

**Comment by laffyfx** [comment]
@vkosuri according to [this screenshot](http://i.imgur.com/45MKeSp.png), I apparently have no version!
I looken in the /dist-packages/ folder and found that my version is 0.6.0 ([screenshot for verification](http://i.imgur.com/AXNPJFr.png)).

EDIT:
And just like that, although I have executed the command
`pip install chatterbot --upgrade --force-reinstall` (maybe it was the "force-reinstall"?)
over 7 times now, it somehow works.

Thank you very much sir!

Side note: Apparently the favicon isn't found, as [this terminal](http://i.imgur.com/RtodEvr.png) shows.
