### ISSUE TITLE
couchdb Trainer

### ISSUE THREAD

**Issue by galeej** [gunthercox/ChatterBot#659]
Hi,

I have written a couchdb trainer that trains data stored in couchdb.  It works on my local... Would it be possible for me to submit the trainer to you?

Sorry, first time contributor to any git project.

Regards,
Sunil

**Comment by gunthercox** [comment]
Hi @galeej, you are welcome to submit a pull request. I can't guarantee it will get merged into the code base but I would be glad to review it.
