### ISSUE TITLE
Support additional data on response object

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#66]
Serialized response lists should be a list of json objects so that additional data such can be added in the future.

Current format:
```
["Response text", 4]
```

New format:
```json
{
    "text": "Response text",
    "occurrence": 4
}
```

**Comment by DarkmatterVale** [comment]
This sounds like a good idea. You might also want to think about providing the POS tags of the sentence in the new format. Although it only takes a short amount of time to calculate part of speech for every word, on databases that are large that time could add up. The format that I propose would be something similar to this:

```
{
     "text": "Response text",
     "pos_tags": [('Response', 'NN'), ('text', 'NN')],
     "occurrence": 4
}
```

**Comment by gunthercox** [comment]
@DarkmatterVale Definitely, I agree.

**Comment by DarkmatterVale** [comment]
Have you had a chance to work on updating this? If so, what have your results shown? Is there any performance improvement using the current logic adapters?

**Comment by gunthercox** [comment]
I haven't had a chance to work on this yet. I was thinking of implementing it over this upcoming weekend.

**Comment by DarkmatterVale** [comment]
Ok, just checking in...
