### ISSUE TITLE
RethinkDB Storage

### ISSUE THREAD

**Issue by toopay** [gunthercox/ChatterBot#660]
I have an experiment using [RethinkDB](https://rethinkdb.com/) as storage recently - since JSON definetely couldn't be used in production and i'm not Mongo fan. @gunthercox is this something you might be interested in? I could submit a PR soon if that is the case :)

Cool library anyway. Cheers!

**Comment by gunthercox** [comment]
@toopay Thank you for the offer. In the nearer future I may be significantly changing the way storage adapters work in ChatterBot. As much as I want to support as many different databases as possible, refactoring will be much easier for me if there are fewer of them in the core of the repository.

**Comment by toopay** [comment]
Interesting. Could you outline the direction of those refactor?

**Comment by gunthercox** [comment]
I don't have any finalized plans at the current time.

**Comment by vkosuri** [comment]
How this is going to be described here https://github.com/gunthercox/ChatterBot/issues/528

**Comment by gunthercox** [comment]
@vkosuri That is not correct. #528 is for input and output adapters. @toopay was talking about a storage adapter for using RethinkDB.

**Comment by vkosuri** [comment]
@gunthercox apologies i thought #528 will apply storage adapters also. Thanks Master.
