### ISSUE TITLE
What happens if I train the chatbot twice in the same session?

### ISSUE THREAD

**Issue by galeej** [gunthercox/ChatterBot#665]
Hi,

I'd like to know what happens if I happen to train the chatbot twice with the same corpus in the same session.

Would the database.db (assuming I'm using the JsonFileStorageAdapter) get updated with the training dataset (with increment to the 'occurence' field)?

**Comment by gunthercox** [comment]
Hi @galeej, that is correct. Occurrence counts are incremented for each duplicate statement received.

**Comment by galeej** [comment]
ok.  

Also, would it be possible for you to let me know why this loop in the jsonfilestorageadapter exists?

```
        for response_statement in statement.in_response_to:
            response = self.find(response_statement.text)
            if not response:
                response = self.Statement(response_statement.text)
                self.update(response)

```
b
I am trying to write a couchdb storage adapter.  This would help me understand the code better.

Thanks in advance,

Galeej
