### ISSUE TITLE
Training Data Memory?

### ISSUE THREAD

**Issue by kail518** [gunthercox/ChatterBot#666]
Hi everyone
I just started using chatterbot and played around by importing different corpus, as well as adding manual conversations. It seems there is memory from previous conversations. For example, if I do training on the ubuntu database, then redotraining on the English corpus, it seems to have memory of responses from ubuntu. This is creating some very unusual responses

**Comment by gunthercox** [comment]
Hi @kail518, your observation is correct. Knowledge is retained by the chat bot each time it is trained.

Methods exist to remove all learned statements from the chat bot if you wish to do so. You can do:

```
my_chatbot.storage.drop()
```
