### ISSUE TITLE
slow in returning replies 

### ISSUE THREAD

**Issue by xliu019** [gunthercox/ChatterBot#669]
Right now whenever l type a question/line to the bot, l have to wait for quite some time to get the reply. But when l first tried the chatterbot 2 days ago, it is quite fast. May l know why? 
l use the example in the Github: 

import tkinter as tk
try:
    import ttk as ttk
    import ScrolledText
except ImportError:
    import tkinter.ttk as ttk
    import tkinter.scrolledtext as ScrolledText
import time

from chatterbot import ChatBot

#from chatterbot.trainers import ListTrainer
#from chatterbot.trainers import ChatterBotCorpusTrainer

class TkinterGUIExample(tk.Tk):

    def __init__(self, *args, **kwargs):
        """
        Create & set window variables.
        """
        tk.Tk.__init__(self, *args, **kwargs)

        self.chatbot = ChatBot("No Output",
            storage_adapter="chatterbot.storage.JsonFileStorageAdapter",
            logic_adapters=["chatterbot.logic.BestMatch"],
            input_adapter="chatterbot.input.VariableInputTypeAdapter",
            output_adapter="chatterbot.output.OutputAdapter",
            database="../database.db"
        )
  
      #  self.chatbot.set_trainer(ListTrainer)

       # self.chatbot.train([
       #     "Hello",
       #     "Hello. What do you want me to do?",
       #     "What can you do?", 
       #     "l can help you analyze networks.Which data are you interested to analyze?", 
       #     "Anything", 
       #     "Do you wish to find interesting properties?", 
       #     "Yes",
       #     "What properties do you want to know?" , 
       # ])

       # self.chatbot.train([
       #     "Greetings!",
       #     "Hello",
       # ])

        self.title("Chatterbot")

        self.initialize()

    def initialize(self):
        """
        Set window layout.
        """
        self.grid()

        self.respond = ttk.Button(self, text='Get Response', command=self.get_response)
        self.respond.grid(column=0, row=0, sticky='nesw', padx=3, pady=3)

        self.usr_input = ttk.Entry(self, state='normal')
        self.usr_input.grid(column=1, row=0, sticky='nesw', padx=3, pady=3)

        self.conversation_lbl = ttk.Label(self, anchor=tk.E, text='Conversation:')
        self.conversation_lbl.grid(column=0, row=1, sticky='nesw', padx=3, pady=3)

        self.conversation = ScrolledText.ScrolledText(self, state='disabled')
        self.conversation.grid(column=0, row=2, columnspan=2, sticky='nesw', padx=3, pady=3)

    def get_response(self):
        """
        Get a response from the chatbot and display it.
        """
        user_input = self.usr_input.get()
        self.usr_input.delete(0, tk.END)

        response = self.chatbot.get_response(user_input)

        self.conversation['state'] = 'normal'
        self.conversation.insert(
            tk.END, "Human: " + user_input + "\n" + "ChatBot: " + str(response.text) + "\n"
        )
        self.conversation['state'] = 'disabled'

        time.sleep(0.5)

gui_example = TkinterGUIExample()
gui_example.mainloop()

**Comment by vkosuri** [comment]
I think you are using JsonFileStorageAdapter adapter, Check size of JsonFileStorageAdapter, If is huge then you response will become slower. Try to [Mongo DB](http://chatterbot.readthedocs.io/en/stable/storage/index.html#mongo-database-adapter) to avoid slowness. Fro more information fallow this link http://chatterbot.readthedocs.io/en/stable/storage/index.html

**Comment by xliu019** [comment]
Thank you very much! It is super fast now. :)
