### ISSUE TITLE
Basic usage : AttributeError: 'module' object has no attribute 'english'

### ISSUE THREAD

**Issue by zeandrade** [gunthercox/ChatterBot#67]
In [5]: chatbot.train('chatterbot.corpus.english')

AttributeError                            Traceback (most recent call last)
<ipython-input-5-508e33bbf87d> in <module>()
----> 1 chatbot.train('chatterbot.corpus.english')

/usr/lib64/python2.7/site-packages/chatterbot/chatterbot.pyc in train(self, conversation, *args, **kwargs)
    150 
    151             if corpora:
--> 152                 self.trainer.train_from_corpora(corpora)
    153         else:
    154             self.trainer.train_from_list(conversation)

/usr/lib64/python2.7/site-packages/chatterbot/training.pyc in train_from_corpora(self, corpora)
     31     def train_from_corpora(self, corpora):
     32         for corpus in corpora:
---> 33             corpus_data = load_corpus(corpus)
     34             for data in corpus_data:
     35                 for pair in data:

/usr/lib64/python2.7/site-packages/chatterbot/corpus/utils.pyc in load_corpus(corpus_path)
     16     from types import ModuleType
     17 
---> 18     corpus = import_module(corpus_path)
     19 
     20     if isinstance(corpus, ModuleType):

/usr/lib64/python2.7/site-packages/chatterbot/utils/module_loading.pyc in import_module(dotted_path)
     12     module = importlib.import_module(module_path)
     13 
---> 14     return getattr(module, module_parts[-1])

AttributeError: 'module' object has no attribute 'english'

**Comment by DarkmatterVale** [comment]
I just tested my installation and got the same issue.

**Comment by gunthercox** [comment]
I can confirm as well. Interestingly it appears that the [unit test for this](https://github.com/gunthercox/ChatterBot/blob/master/tests/training_tests/test_training_from_corpus.py#L23) is passing.

I believe the issue has something to do with relative / non-relative import paths being loaded in the corpus utility module: https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/corpus/utils.py

I will be looking into this more later today.

**Comment by zeandrade** [comment]
thank you @gunthercox

**Comment by gunthercox** [comment]
I am continuing to look into this issue. I am still trying to debug what is going on here.

What I am seeing is that the corpus modules are being imported differently depending on where the method is called from.

I can currently duplicate both successful and failing module imports by running either:
`nosetests tests/training_tests/` (failing)

or just `nosetests` (passing).

**Comment by gunthercox** [comment]
Hi @zeandrade, this should be all set now. I've switched from using python imports to simply traversing the data directory of files. This makes things much easier to work in general and corrects the issue with the import location you encountered.

**Comment by abhinavlekhi** [comment]
runfile('C:/Users/HP/Documents/Python Scripts/untitled0.py', wdir='C:/Users/HP/Documents/Python Scripts')
Traceback (most recent call last):

  File "<ipython-input-8-6d6675b9ba7e>", line 1, in <module>
    runfile('C:/Users/HP/Documents/Python Scripts/untitled0.py', wdir='C:/Users/HP/Documents/Python Scripts')

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\HP\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/HP/Documents/Python Scripts/untitled0.py", line 1, in <module>
    from chatterbot import Chatbot

  File "C:\Users\HP\Documents\Python Scripts\chatterbot.py", line 2, in <module>
    chatbot = chatterbot.chatbot

AttributeError: module 'chatterbot' has no attribute 'chatbot'

I AM GETTING THIS ERROR N I'M NOT ABEL TO REMOVE IT   
PLZZ HELP

**Comment by gunthercox** [comment]
Rename your chatterbot.py file to something different. Your seeing this error because the file is importing from itself.

**Comment by abhinavlekhi** [comment]
>
> can you tell me which chatterbot.py file should i rename becoz i renamed
> chatterbot.py package which i imported but it didn't work
>
I renamed this file whose img is referred here but didn't worked out.



>

**Comment by vkosuri** [comment]
i think it's ``from chatterbot import ChatBot``

Here more examples https://github.com/gunthercox/ChatterBot/tree/master/examples that will help you how to use chatterbot
