### ISSUE TITLE
How to get the bot to open a file when l type the file name and analyze network properties 

### ISSUE THREAD

**Issue by xliu019** [gunthercox/ChatterBot#670]
Right now l am working on a project which can open a network file and analyze network properties. l need to build a chatbot that ask users questions, let users choose/put file names of the networks, open the networks and return the various network properties in the chat. Is it possible? Thank you very much!

Here is the screenshot of the existing project: 
![image](https://cloud.githubusercontent.com/assets/6997360/24397472/ee1657ba-13d8-11e7-861a-fdbea46e2523.png)
![image](https://cloud.githubusercontent.com/assets/6997360/24397500/0001a632-13d9-11e7-9929-1f83597f9163.png)

**Comment by vkosuri** [comment]
It seems to you are working on TCL/TK widgets, If so i don't exact answer how to integrate both ``Python`` and ``TCL/TK``. 

Coming to your question, What I understood, 

1. you need to read files names from user
2. Input to your tool it will produce above specified graphs.

Then that is the case see this [example ](http://chatterbot.readthedocs.io/en/stable/examples.html#terminal-example)

I want integrate your tool into chatterbot see more examples [input ](http://chatterbot.readthedocs.io/en/stable/input/index.html) and [output ](http://chatterbot.readthedocs.io/en/stable/output/index.html) adapters.

Some other resource python with tk https://wiki.python.org/moin/TkInter
