### ISSUE TITLE
How to storage conversation data when I have a quick start

### ISSUE THREAD

**Issue by qinyuanpei** [gunthercox/ChatterBot#671]
I had installed chatterBot with pip and I wrote a simple demo based on examples:
```
from chatterbot import ChatBot

chatbot = ChatBot('Wechat')
response = chatbot.get_response('How are you?')
print response
```
When I execute this script, it will download data with "nltk_download_corpus", here it shows a exception in terminus, so how can we solve this issues if I don't want to download data from network, because I had found data in this project on GIthub.

**Comment by vkosuri** [comment]
Did you tried like this

```Python
# -*- coding: utf-8 -*-

from chatterbot import ChatBot
# Create a new instance of a ChatBot
bot = ChatBot(
    'Exact Response Example Bot',
    storage_adapter='chatterbot.storage.JsonFileStorageAdapter',
    database='myJson.db',    
    initialize=False
)

# Get a response given the specific input
response = bot.get_response('Help me!')
print(response)
```

**Comment by qinyuanpei** [comment]
Yes，I know that chatterbot use JSON as the default storage，we don't have to define a storage adapter in our script like examples show，my question is that data.py in site-packages shows a BadZipfile exception when I execute this script，I think maybe Python(v2.7/v3) in my system(Ubuntu14) is not work well.

**Comment by vkosuri** [comment]
similar issue see https://github.com/gunthercox/ChatterBot/issues/662#issuecomment-289863176

**Comment by qinyuanpei** [comment]
Thanks for your help，I will download nltk data manually and try again.
