### ISSUE TITLE
if I had a dataset, could I train chatter bot?

### ISSUE THREAD

**Issue by mrmrn** [gunthercox/ChatterBot#674]
Hi, this open source, language independent bot engine is very nice work.
Thank you all.
I like to develop a chatbot for supporting​ a website, and my preferred language is Persian.
So can I use a persian dataset for training chatterbot?

**Comment by vkosuri** [comment]
Yes, You could submit PR to this repository https://github.com/gunthercox/chatterbot-corpus

Some of the examples of other language's are available https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data

**Comment by mrmrn** [comment]
how could I submit PR to [that](https://github.com/gunthercox/chatterbot-corpus) repo?

**Comment by vkosuri** [comment]
Please read the documentation https://help.github.com/articles/fork-a-repo/

**Comment by mrmrn** [comment]
thanks
