### ISSUE TITLE
How do i disable the storage adapter?

### ISSUE THREAD

**Issue by Olamyy** [gunthercox/ChatterBot#678]
I'm working with chatterbot and I really don't think I need a storage adapter.
Basically cause I've got my own storage engine and I'm on a limited storage space so I can't afford to save all conversations.

I was thinking if I left it blank, it'd disable it but it didnt.
The documentation says it defaults to 'JSONFileStorage'

**Comment by vkosuri** [comment]
I haven't tried like this, could you try and let me know?

``` Python
bot = ChatBot("Terminal",
    storage_adapter=False
)
```

I think you will get error on your terminal.

**Comment by gunthercox** [comment]
ChatterBot now supports in-memory databases. If you configure the SQL storage adapter in read-only mode it will achieve the effect desired here because it won't create a database and no statements will be added to it.

```python
bot = ChatBot("Terminal",
    storage_adapter={
        'import_path': 'chatterbot.storage.SQLStorageAdapter',
        'read_only': True
    }
)
```
