### ISSUE TITLE
Making changes to the models does not change the chatbot.

### ISSUE THREAD

**Issue by maclogan** [gunthercox/ChatterBot#680]
I must be missing something here.

When trying to add a model to ext/django_chatterbot/models.py file, nothing happens.  Migrating states that there are no changes detected.  Is this not where to change, add, or delete files in Chatterbot 0.5.5?

**Comment by vkosuri** [comment]
Did you tried making migrations

`` Bash
python manage.py migrate
`` 
https://docs.djangoproject.com/en/1.10/topics/migrations/#workflow
