### ISSUE TITLE
Slack Input/Output Adapter

### ISSUE THREAD

**Issue by monokal** [gunthercox/ChatterBot#682]
Slack is becoming an increasingly popular tool for organisations and individuals to communicate and has a huge developer following thanks to their well documented APIs.

It'd be great to have a native ChatterBot Input/Output Adapter for Slack to allow for more Human responses to wrap around the core functionality of whatever Python Slack Bot you're building.

https://api.slack.com/

**Comment by vkosuri** [comment]
A future update https://github.com/gunthercox/ChatterBot/issues/528
