### ISSUE TITLE
Amazon AVS (Alexa) I/O adapter

### ISSUE THREAD

**Issue by monokal** [gunthercox/ChatterBot#691]
Official example using the Raspberry Pi. Nice thing is that as it uses a 3rd party "wake word engine", we don't have to stick to activating the bot with "Alexa".

https://github.com/alexa/alexa-avs-sample-app/wiki/Raspberry-Pi

**Comment by monokal** [comment]
Oh hell, https://aws.amazon.com/lex/

**Comment by davizucon** [comment]
Hi @monokal, maybe I'm wrong but I think its a kind of Logic Adapter, right ?

**Comment by vkosuri** [comment]
I think it would be an Input and Output adapter

**Comment by davizucon** [comment]
You are right, for avs, should be IO adapter, lex is a full chatbot and depends which service will be used.
