### ISSUE TITLE
Running Chatterbot is very slow

### ISSUE THREAD

**Issue by oddrock** [gunthercox/ChatterBot#692]
When I run the chatterbot on my pc server(4c 8 GB)，it responses very slow， about serverl seconds. I found that the chatterbot process only use one core although my pc server has 4 cores.
Why？Have there some parameter I should ajust!

Help!

**Comment by oddrock** [comment]
PS : I found every time when i get repsponse from a chatterbot , one core of CPU's usage is 100%. I think it is alse very strange.

**Comment by gunthercox** [comment]
Hi @oddrock, I haven't encountered this issue before. Can you provide any additional information about the setup of your chat bot?

**Comment by oddrock** [comment]
@gunthercox thank you. I have solved this problem just by changing the storage adpater to mongodb.
