### ISSUE TITLE
Does Chatterbot  provide HTTP API？

### ISSUE THREAD

**Issue by oddrock** [gunthercox/ChatterBot#698]
hello，Does Chatterbot  provide HTTP API？Can I use chatterbot just by an HTTP request and response?
Does anyone have some examples? or JAVA APIs are also useful.

**Comment by vkosuri** [comment]
Yes, but you have to external mechanism tools such as [Djangoand](http://chatterbot.readthedocs.io/en/stable/django/index.html) flask
