### ISSUE TITLE
No module named jsondb

### ISSUE THREAD

**Issue by vishalgoyal18** [gunthercox/ChatterBot#699]
I keep getting this error when running the chatterbot commands. Please help.

============ RESTART: C:/Users/goyalvi/ChatterBot/chatbottest.py ============

Traceback (most recent call last):
  File "C:/Users/goyalvi/ChatterBot/chatbottest.py", line 2, in <module>
    chatbot = ChatBot("Ron Obvious")
  File "C:/Users/goyalvi/ChatterBot\chatterbot\chatterbot.py", line 37, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:/Users/goyalvi/ChatterBot\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "C:/Users/goyalvi/ChatterBot\chatterbot\storage\jsonfile.py", line 21, in __init__
    from jsondb import Database
ImportError: No module named jsondb
>>>

**Comment by vkosuri** [comment]
could please check the jsondatabase installed in your machine by using  ``pip freeze`` 

If You are using Linux, you could try like this to get to know.

```Bash
(venv)vkosuri@vm-vkosuri:~/chatterbox/ChatterBot$ pip freeze | grep jsondatabase
jsondatabase==0.1.7
```

It seems jsondatabase not installed in your machine try to do a fresh installation of chatterbot

`` 
pip install --upgrade chatterbot
`` 

Still seeing same issue, try to install jsondatabase alone

`` 
pip install --upgrade jsondatabase
``

**Comment by vishalgoyal18** [comment]
It worked now. Thanks.

Regards, Vishal
