### ISSUE TITLE
error when newly installed

### ISSUE THREAD

**Issue by frossaren** [gunthercox/ChatterBot#700]
Getting: Traceback (most recent call last) : 
File "/home/usr/Chatterbot/chatterbot/chatterbot.py", line 3, in <module>
from .storage import Storageadapter
Valueerror: Attempted relative import in non-package

I am a bit unsecure what is causing this and i dont seem to find anything here

**Comment by vkosuri** [comment]
You can't execute chatterbot cloned file. Before that you have to install chatterbot by using

```
pip install --upgrade chatterbot 
```

Recommend use Python Virtual Environment

**Comment by frossaren** [comment]
@vkosuri I have tried that too but just gets this error
File" /home/usr/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 3, in <module> from .storage import Storageadapter
Valueerror: attempted relative import in non-package

**Comment by gunthercox** [comment]
@frossaren did you by any chance write your code in a file called `chatterbot.py`? If you did this will cause import errors.

**Comment by frossaren** [comment]
seems like python had corrupted files on that computer... suddenly realized that nothing with python was working. Tried to copy the code to my main pc and it worked like a charm. Great job
