### ISSUE TITLE
Getting error in python chatbot

### ISSUE THREAD

**Issue by PremVarma** [gunthercox/ChatterBot#701]
![image](https://cloud.githubusercontent.com/assets/28188631/25554895/20264a6c-2cf7-11e7-8538-16d9a1eecda5.png)

Help Me Please To Solving This Error!!

**Comment by vkosuri** [comment]
The reason you were seeing due to default ``JsonStorageAdapter``. It's warning only, if you want avoid this warning please change storage adapter. For more info please read this documentation http://chatterbot.readthedocs.io/en/stable/storage/index.html

**Comment by gunthercox** [comment]
@PremVarma There are a few ways to install ChatterBot.

As @vkosuri mentioned, `pip` is the recommended way to install.

```
pip install chatterbot
```

You can also install your local copy using pip, for example

```
git clone https://github.com/gunthercox/ChatterBot.git
pip install ./ChatterBot
```

http://chatterbot.readthedocs.io/en/latest/setup.html
