### ISSUE TITLE
ImportError: cannot import name API

### ISSUE THREAD

**Issue by ProdigyTech** [gunthercox/ChatterBot#708]
Can someone help me with this error? I followed instructions from the documentation, but I can't seem to get the trainer to work. I have a settings.py file in the same directory as my app.py with the correct twitter keys. 

![image](https://cloud.githubusercontent.com/assets/8797862/25627468/893a3f6e-2f17-11e7-889d-9bd7db18e37d.png)

![image](https://cloud.githubusercontent.com/assets/8797862/25627580/e6aca8d0-2f17-11e7-89c0-e61fb0ae7546.png)

**Comment by gunthercox** [comment]
Hi @ProdigyTech Based on your description it sounds like you don't have the Python `python-twitter`  package installed.
