### ISSUE TITLE
Broken ListTrainer

### ISSUE THREAD

**Issue by weslleylobo** [gunthercox/ChatterBot#709]
Hello, I think ListTrainer is broken again.
See the error message:

from chatterbot.trainers import ListTrainer
conversation = [ "Olá" , "Olá!"  ]
chatbot.set_trainer(ListTrainer)
chatbot.train(conversation)

------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\Weslley\Desktop\treino.py", line 3, in <module>
    chatbot.set_trainer(ListTrainer)
NameError: name 'chatbot' is not defined
[Finished in 0.2s with exit code 1]
[shell_cmd: python -u "C:\Users\Weslley\Desktop\treino.py"]
[dir: C:\Users\Weslley\Desktop]
[path: C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Weslley\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Weslley\AppData\Local\Programs\Python\Python36\;C:\Users\Weslley\AppData\Local\Microsoft\WindowsApps;]

**Comment by gunthercox** [comment]
I think the error message is correct. See the line that says:

> NameError: name 'chatbot' is not defined

Have a look at this example for what needs to be included: http://chatterbot.readthedocs.io/en/latest/examples.html#simple-example
