### ISSUE TITLE
Unable to get any response from mongodb 

### ISSUE THREAD

**Issue by reubenkhanna** [gunthercox/ChatterBot#710]
Hi having this issues since 2 days now. 

I followed the documentation and created  a database stored the conversations in my collections. 
Now when I run it I dont get any response when I use the get_response() Method . 
and the program just get stuck over that line. 
```
bot = ChatBot(
    'Terminal',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch'
    ],
    filters=[
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    database='ChatBotdb'
    #database_uri='mongodb://127.0.0.1:27017/'
)
try: 
print here
response= bot.get_response(text)
                print response
except :
 except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

it does enter the try block and prints here and gets stuck after that

**Comment by gunthercox** [comment]
Can you confirm that mongodb is running? It's possible that this is getting stuck because it it waiting for a connection.

**Comment by reubenkhanna** [comment]
Yes mongoDB is running. I am running this on pycharm also when I use 'None' I am able to give input in my console and it replies correctly. but what if I just want a reply from the get request which I am sending. 

Ex; http://localhost:8080/search/hi 

so it should reply to this 'hi'  I am sending it in "text" and trying to get a response using bot.get_response(text)

This used to work fine while using json adapter but doesnt seem to work in MongoDB approach and I will be using mongo DB as I have a huge data set on which I have to train the bot

**Comment by reubenkhanna** [comment]
@gunthercox  Can you help me with this

**Comment by gunthercox** [comment]
@reubenkhanna I apologize for the late response. The reason you are not getting a response is because of the chat bot is waiting for input from the console. You likely need to use a different input adapter so that the bot won't be waiting for console input.

I recommend using the `VariableInputTypeAdapter` which is describe in more detail here: http://chatterbot.readthedocs.io/en/stable/input/
