### ISSUE TITLE
Frequency and Density

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#718]
Is it possible to calculate frequency and Density for a given statement and response?

**Comment by gunthercox** [comment]
Could you elaborate a bit more about what frequency and density are?

**Comment by vkosuri** [comment]
I am not sure this will benefit to chatterbot, My idea is to identify ``frequent words`` in all the ``statements``, so that i can guess my users are writing sentence or statements in such a way i can update my corpus based on those words

I find we could find frequency through ``NLTK`` module

``` Python
words = nltk.tokenize.word_tokenize(p)
fdist = FreqDist(words)
```

More information https://languagelearning.stackexchange.com/questions/449/what-are-the-advantages-of-studying-words-by-their-frequency/452

**Comment by gunthercox** [comment]
I'm not sure if this would benefit ChatterBot either. I'd be open to suggestions on design or implementation details regarding this if you or anyone else has suggestions about how something like this could be used to accomplish any learning or response generation tasks. For now however, I'm going to close this ticket off.
