### ISSUE TITLE
Still Django Response and Statements are reversed

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#722]
While i trained on ChatterbotCorpusTrainer, and ListTrainer, the statement and Response both are reversed.

Previous issue https://github.com/gunthercox/ChatterBot/issues/308

**Comment by vkosuri** [comment]
To reproduce this issue

``` Python
CHATTERBOT_TRAIN = {
    'name': 'Django Chatter Bot',
    'trainer': 'chatterbot.trainers.ListTrainer',
    'training_data': [
        "how to train your bot",
        "python managem.py train",
        "Will it work",
        "Not sure"
    ],
    'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
    'django_app_name': 'abot',
    'use_django_models': True
}
```
![image](https://cloud.githubusercontent.com/assets/13664257/25772722/a56ec7b6-328e-11e7-8440-2e00e8f21712.png)

**Comment by Air-boy** [comment]
i think ,you train only 4 message, they random ?

**Comment by vkosuri** [comment]
This happening due to foreign key mapping at [L136](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/ext/django_chatterbot/models.py#L136) 

```Python 
    statement = models.ForeignKey(
        'Statement',
        related_name='in_response'
    )

    response = models.ForeignKey(
        'Statement',
        related_name='responses'
    )
```

**Comment by vkosuri** [comment]
@gunthercox Master, Do you have any idea how to solve this?

**Comment by gunthercox** [comment]
I believe it is an issue in the storage adapter, I still need to check over the code and figure out where the inconsistency is.

**Comment by authenticfake** [comment]
Hi gunthercox, any news?

**Comment by andpark** [comment]
I got same problem.
So I inspected trainer code and I've found the solution.

The problem was in trainers.py
`
class ListTrainer(Trainer):
    """
    Allows a chat bot to be trained using a list of strings
    where the list represents a conversation.
    """

    def train(self, conversation):
        """
        Train the chat bot based on the provided list of
        statements that represents a single conversation.
        """
        statement_history = []

        for text in conversation:
            statement = self.get_or_create(text)

            if statement_history:
                statement.add_response(
                    Response(statement_history[-1].text)
                )

            statement_history.append(statement)
            self.storage.update(statement)
`

This code puts previous statement as a response of current statement.
So, you should traverse the conversation in reversed order like this.
`for text in reversed(conversation):`

This should work fine.

![image](https://user-images.githubusercontent.com/3851262/26860808-e90c5a6a-4b7a-11e7-8c80-961eabb24597.png)

**Comment by vkosuri** [comment]
@andpark could you please submit a PR for this issue?

**Comment by vkosuri** [comment]
@andpark could you please submit a PR for this issue?

**Comment by andpark** [comment]
@vkosuri Thanks. I made pull request.

**Comment by gunthercox** [comment]
Do the changes in #630 solve this issue?

**Comment by vkosuri** [comment]
No Master, Still they are in reverse order even after #630
![image](https://user-images.githubusercontent.com/13664257/27212375-3ef85204-527d-11e7-90a9-0d8cef91fe10.png)
