### ISSUE TITLE
Run SQL tests in memory

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#723]
It would be optimal if the tests for the SQL adapter could be run with the database in memory. This would have better performance and make cleanup easier. Sqlite does support this.

**From the documentation (http://docs.sqlalchemy.org/en/latest/core/engines.html):**

To use a SQLite `:memory:` database, specify an empty URL:
```python
engine = create_engine('sqlite://')
```

**Comment by davizucon** [comment]
Yep, I will change the default behavior of database creation, where if unspecified database file, will always create a sqlite memory a database.

**Comment by gunthercox** [comment]
Closes by #745
