### ISSUE TITLE
response slow,about 3.5 seconds, i use mongodb database

### ISSUE THREAD

**Issue by Air-boy** [gunthercox/ChatterBot#724]
i test that if database file is small, response very well, but database is large, about 3 seconds response time,
this porblem hot to  solve? @gunthercox

**Comment by Air-boy** [comment]
@vkosuri  could u help me ?

**Comment by Air-boy** [comment]
i had solve this problem

**Comment by vkosuri** [comment]
@Air-boy could you please let us know how did you solved your problem?

**Comment by sporting** [comment]
I met the same problem. After import large training data to Mangodb, "get_response" will be very slow.

**Comment by Air-boy** [comment]
@vkosuri  @sporting    i use vmware to run linux. i change memory to large, about 20 minits later, response speed had changed.  i do not anything  except this.
