### ISSUE TITLE
one question many answer  And many question one answer 

### ISSUE THREAD

**Issue by Air-boy** [gunthercox/ChatterBot#725]
have simple method?    
do not write    

chatterbot.train([
    "Hi there!",
    "Hello",
])

chatterbot.train([
    "Greetings!",
    "Hello",
])

@gunthercox @vkosuri

**Comment by vkosuri** [comment]
@Air-boy i didn't understand could you please elaborate your question?

**Comment by Air-boy** [comment]
when i input "Hi there",robot response "Hello" or "OK, i know"

i write a *.corpus.json file  fellow:
{
"conversations":[
"i love you",
"me too"
],
[
"i love you",
"i love you too"
]
}
i input one request ,robot response "me too" or "i love you too"
if i have ten response, i hava to repeat ten times
if i write ten times this "i love you",  it is  redundancy

so i want to find a simple write way

**Comment by Air-boy** [comment]
@vkosuri

**Comment by gunthercox** [comment]
@Air-boy There is not a simpler way to organize the training data. The corpus files that ChatterBot uses are just simple structured data. If you need to generate data that has lots of redundant responses to a particular input I would assume that it would be simple to write some code to generate a corpus training file that contained each variation of the statement and it's possible responses.

**Comment by Air-boy** [comment]
@gunthercox   master  , i think  it is necessary,   for example: FAQ need this
