### ISSUE TITLE
How to train new ChatterBot instance with MongoDB storage.?

### ISSUE THREAD

**Issue by Cosmos19** [gunthercox/ChatterBot#726]
Hello,

I have created the Chatterbot with Tornado web application and my storage adapter is MongoDB. 

Now i want to train the bot to respond user queries. So i have two question with respect to training.
1)  Each input statement is getting stored in a database. but how to notify the bot about the answer to the relevant question.
2) How it will make decision with available so many statements.?

Sorry for these questions. Am completely beginner for this machine leaning topic.

**Comment by vkosuri** [comment]
It's not a full answer for your question, but something will help you http://chatterbot.readthedocs.io/en/stable/training.html#training

**Comment by Cosmos19** [comment]
Hello @vkosuri ,

I have gone through that. ! But still am confused with the flow.

Lets take below scenario.

How to make the conversation to be continued with same topic.?
[
"right",
"okay"
],
[
"i have problem with eye",
"which side",
"right",
"oh...thats bad. What happened to right eye.?"
]
In the above scenarion. I want the bot to reply "oh...thats bad. What happened to right eye.?". but instead of that it will reply "okay". because of the best match.

How to overcome this situations.? :(

Thanks.

**Comment by Cosmos19** [comment]
With my understanding. ChatterBot doesn't support flow based conversation. Closing this issue.
