### ISSUE TITLE
Issue about chatterbot.storage.MongoDatabaseAdapter must be a subclass of StorageAdatpter

### ISSUE THREAD

**Issue by FakerGit** [gunthercox/ChatterBot#727]
While I use the django(python manage.py runserver) , it always tell me that there is a InvaliadAdapterTypeException: chatterbot.storage.MongoDatabaseAdapter must be a subclass of StorageAdatpter . 
Here is the setting of my bot:
``` Python
 self.ciri = ChatBot(
            'Ciri',
            storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
            logic_adapter=[
                'chatterbot.logic.BestMatch'
            ],
            filters=[
                'chatterbot.filters.RepetitiveResponseFilter'
            ],
            input_adapter='chatterbot.input.VariableInputTypeAdapter',
            output_adapter='chatterbot.output.TerminalAdapter',
            database='chat_ciri_db',
        )

```

**Comment by vkosuri** [comment]
@FakerGit which version chatterbot are you using?

**Comment by FakerGit** [comment]
@vkosuri  It is 0.6.0.  Without using Django,  my program is functioning well. By the way , the version of Django is 1.11.

**Comment by gunthercox** [comment]
@FakerGit I attempted to recreate the issue you encountered under the following conditions:

- ChatterBot version 0.6.0
- Python 2.7

Running the code snippet you provided I could not recreate this error. The only possibility I can think of is that you may have made modifications to the source code locally?

I'm going to close this issue, feel free to reopen it if you believe this is an error in ChatterBot's codebase.
