### ISSUE TITLE
i want to write my filer,but i can not find filter.py . where is it?

### ISSUE THREAD

**Issue by Air-boy** [gunthercox/ChatterBot#730]
@gunthercox @vkosuri

**Comment by sporting** [comment]
This?
https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/filters.py

**Comment by Air-boy** [comment]
@sporting   yeah,i find it ,  but now  i want to write my filter,to realize search result this confidence is 1.0

**Comment by vkosuri** [comment]
This might help you https://github.com/gunthercox/ChatterBot/blob/351971a21e603642f5797c33e924c4195f96682b/chatterbot/logic/low_confidence.py#L32

**Comment by Air-boy** [comment]
i mean that when i input "hello",they can response and only response ,and response  can cycle, 
for examaple:
hello--->hi
hello--->hello
-----------
hello--->hi
hello--->hello

i use mongodb database @vkosuri

**Comment by vkosuri** [comment]
Then you have to use ``Specific Response Adapter`` http://chatterbot.readthedocs.io/en/stable/logic/index.html#specific-response-adapter

**Comment by Air-boy** [comment]
I stored in the mongo database and a lot of data, a question has more than one answer, I want to ask a question, and then answer the matched the answer machine, with each answer in my answer 
@vkosuri 
my english not well,
hope you can understand

**Comment by vkosuri** [comment]
Could try like this, The logic will work what you are asking, other response you will get ``'I am sorry, but I do not understand.'``. Let me know if you need any help.

```
# Create a new instance of a ChatBot
bot = ChatBot(
    'Default Response Example Bot',
    storage_adapter='chatterbot.storage.JsonFileStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 1.0,
            'default_response': 'I am sorry, but I do not understand.'
        }
    ],
    trainer='chatterbot.trainers.ListTrainer'
)
```

**Comment by Air-boy** [comment]
i use mongodb database, in the *.corpus.json file ，i hava this data:
["大海","蓝蓝的一望无际"],
["大海","好想陪你去看海"],

i write filter in my .py  ,this:
	filters=['chatterbot.filters.RepetitiveResponseFilter'],
when i first input "大海"，chatterbot  first response "蓝蓝的一望无际"  
when i second input "大海"，chatterbot  second response "好想陪你去看海"  

when i third input "大海"，chatterbot  third response  neither "蓝蓝的一望无际"  nor  "好想陪你去看海" ,


when i not write filter in my .py  for this:	filters=['chatterbot.filters.RepetitiveResponseFilter'],
when i first input "大海"，chatterbot  first response "蓝蓝的一望无际"  
when i second input "大海"，chatterbot  second response "蓝蓝的一望无际"  
when i third input "大海"，chatterbot  third response "蓝蓝的一望无际"  
......  always reponse "蓝蓝的一望无际" 


now ,i want chatterbot to reply one of  both("蓝蓝的一望无际"  and "好想陪你去看海"   ),when  i  input "大海"and  No matter how many times i input  "大海"

@vkosuri

**Comment by gunthercox** [comment]
I'm going to close this issue as the question in the title has been answered and the additional questions asked in the comments appear to be duplicates of #725. I will respond to them on their corresponding ticket to try to keep this organized.
