### ISSUE TITLE
How to configure the MongoDB storage adapter of django_chatterbot 

### ISSUE THREAD

**Issue by xilu0** [gunthercox/ChatterBot#733]
hi,
How to configure the MongoDB storage adapter of django_chatterbot ,Hoping to give me a sample

**Comment by Air-boy** [comment]
you can read chatterbot doc

**Comment by gunthercox** [comment]
Hi @xilu0, it is important to note that the ChatterBot storage adapter for Mongo DB is not designed to work with the Django ORM. If you want to use Mongo DB with ChatterBot you will need to modify your Django project to use a "Django storage backend" for MongoDB. There are a few popular ones available such as:

https://django-mongodb-engine.readthedocs.io/en/latest/topics/setup.html

**Comment by xilu0** [comment]
Thank you for your answer!
ganthercox,You know me, I hope support MongoDB, but Django is not good for MONGO, it's ideal to separate databases.
