### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Marcogb81** [gunthercox/ChatterBot#742]
Hello,

I follow the first steps of documentation 'CHatterbot Tutorial' and received this error:

```Bash
Traceback (most recent call last):
  File "/home/marco/Desktop/.idea/TeRiehBot.py", line 12, in <module>
    database='./database.json',
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 39, in __init__
    self.validate_adapter_class(storage_adapter, StorageAdapter)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 85, in validate_adapter_class
    if not issubclass(import_module(validate_class), Adapter):
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils/module_loading.py", line 12, in import_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named storage
```

**Comment by gunthercox** [comment]
Hi @Marcogb81, what editor are you using? I see that there is a `.idea` directory in the trceback and I am wondering if this error is occurring because of the configuration of this editor.

**Comment by Marcogb81** [comment]
Hi Gunther,

Do not worry, finally I found my error: I do not use virtualenv and mi actual versión of Ubuntu 16.04 is a big disastre. Finally I can run the code.

Mi IDE is PyCharm.

Best regards,

MGB


________________________________
De: Gunther Cox <notifications@github.com>
Enviado: lunes, 29 de mayo de 2017 21:40
Para: gunthercox/ChatterBot
Cc: Marco Garcia Baturan; Mention
Asunto: Re: [gunthercox/ChatterBot] Error in documentation (#742)


Hi @Marcogb81<https://github.com/marcogb81>, what editor are you using? I see that there is a .idea directory in the trceback and I am wondering if this error is occurring because of the configuration of this editor.

**Comment by vkosuri** [comment]
@Marcogb81 It seems to you have resolved your issue. Please feel free to reopen this issue if you found any issue?
