### ISSUE TITLE
Setting up chatterbot with Mongodb storage adapter on heroku for messenger bot

### ISSUE THREAD

**Issue by maker101** [gunthercox/ChatterBot#754]
In case of Json storage adapter a .db file is formed after training, uploading the same on heroku works fine. What to do in case of mongodb storage adapter?

**Comment by zhantongz** [comment]
The bot will update the specified database automatically if you train on heroku. You can also import the .db file to MongoDB with the collection name `statements`.

**Comment by maker101** [comment]
Thanks zhantongz ,
Can you please redirect me to 'reading resources' for the same. Do you know any app using chatterbot on heroku using mongodb storage adapter?

**Comment by vkosuri** [comment]
This could help you https://elements.heroku.com/addons/mongolab
