### ISSUE TITLE
Is regular expression matching response is handled.? 

### ISSUE THREAD

**Issue by Cosmos19** [gunthercox/ChatterBot#756]
Hello.

["WHAT ARE WEB *",
"I call them Internet ."
]

In the above json.  The question is something like this " What are web services". In this case it has to match and give a response.

Thanks.
Prakasam

**Comment by vkosuri** [comment]
Currently there is no mechanism implemented in chatterbot. If you need any specific one please write your own pre processor http://chatterbot.readthedocs.io/en/stable/preprocessors.html

I think wild card mapping will procedure many nearest distance/similarity between words. This will slow down you bot for every response request.

**Comment by Cosmos19** [comment]
Closing this issue since it will reduce the bot response time. If other alternative way to implement this behavior is much appreciated in future.
