### ISSUE TITLE
pymongo.errors.OperationFailure: distinct too big, 16mb cap

### ISSUE THREAD

**Issue by peterel** [gunthercox/ChatterBot#757]
Ive seen this here and there as an issue but its not clear to me what to do with it. As far as I can see, when receiving this issue it means that one simply tried to train with a much too large corpus and should re-do the training with something smaller. Is that correct or is there some way around this?

Thanks

**Comment by monokal** [comment]
Already confirmed as a bug here, which you've commented on. https://github.com/gunthercox/ChatterBot/issues/686

**Comment by peterel** [comment]
@monokal Indeed. Ill close this.
