### ISSUE TITLE
Django adapter documentation

### ISSUE THREAD

**Issue by yousifa** [gunthercox/ChatterBot#758]
IMO Django docs need more examples. Where do I put my custom logic, input, output and storage adapters?

I assume I need to create an app in Django, I did and connected it in settings.py, but don't know where to put my code.

Thanks

**Comment by vkosuri** [comment]
Could you please let us know what areas still required, you could revisit the Django documentation from here http://chatterbot.readthedocs.io/en/stable/django/index.html

I am not sure what code your having.

This example app will guide how to build your own app https://github.com/gunthercox/ChatterBot/tree/master/examples/django_app

Here some of the steps we need to perform based on your code.

``` Bash
python manage.py migrate
python manage.py train
python manage.py runserver
```

**Comment by yousifa** [comment]
I went through that tutorial and got it all working up to where the tutorial ends. My question is where do I put the python code for my custom adapters?

**Comment by yousifa** [comment]
The question is where in this Django integration example folder can you have python code to handle get_response, act on the response, .etc.

https://github.com/gunthercox/ChatterBot/tree/master/examples/django_app/example_app

similar to what is done in these examples scripts:
https://github.com/gunthercox/ChatterBot/tree/master/examples
http://chatterbot.readthedocs.io/en/latest/examples.html

Do we need to create a new logic_adapter to intercept the data and add special handling?

**Comment by dexterash** [comment]
I'm also interested on how you send parameters to specific adapter (for example, logic adapter->LowConfidence).

**Comment by gunthercox** [comment]
There is now documentation on the directory setup for custom logic adapters.

http://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html#directory-structure

It is located under the general logic adapter documentation because the setup is the same regardless of if Django is being used.
