### ISSUE TITLE
Issue with Bot Response 

### ISSUE THREAD

**Issue by telkomops** [gunthercox/ChatterBot#759]
```
5/5/2017 10:09:44 AM	AdamAmith	SmithB	No. Atlantic City
5/5/2017 10:10:03 AM	AdamAmith	SmithB	It started last wednesday 
5/5/2017 10:11:28 AM	SmithB	AdamAmith	Ok.Let me see what i can do.
```

I have a chat history as part of 1 conversation which was trained , now the in the statements collection it was established as below in the mongodb collection

```
No. Atlantic City -->in reponse to -->"are you in texas" 
It started last wednesday -->in reponse to -->"No. Atlantic City" 
"Ok.Let me see what i can do." --> in response to --> "It started last wednesday"
```

i tested this scenario in the terminal example. when typed 

`"No. atlantic City" , Bot Responded with "It Started Last Wednesday" `

 Ideally it should be` "Ok. Let me see what i can do" `, as the same user has typed "**it started last wednesday**" as well and logically the next message to the user is `"Ok, let me see what i can do"`

Any pointers on how to resolve this ?

**Comment by Cosmos19** [comment]
as far as i know. If you implement **chatbot.set_trainer(ListTrainer)**  it will look for sequential way. Even i have doubt how th AI is actually working in this chatterbot. Still i couldnt find any answer related to that. I have checked chatterbot docs too.

**Comment by telkomops** [comment]
From my understanding, when you ask a specific question, it takes all distinct, replies_to and tried to find the nearest or similar using , by default, Levenshtein_distance. So in my case, since i said , "No.Atlantic City" it found the match and it then returned "It started last wednesday" , however i feel that , logic should ignore sequence of conversations from same user.  When finding the replies_to, the sequence of chats from the same user should be ignored or handled differently.

- No. Atlantic City -->in reponse to -->"are you in texas" 
- It started last wednesday -->in reponse to -->"No. Atlantic City"   **(IGNORE) flag set in database as from the same user**
- "Ok.Let me see what i can do." --> in response to --> "It started last wednesday"

**Comment by gunthercox** [comment]
@telkomops I closed this issue off because I thought it had been resolved. My apologies if this was a mistake. Are you still encountering this issue?

**Comment by telkomops** [comment]
@gunthercox , how do i handle such scenarios?your guidance in this is much appreciated. my bot is repeating what the user a said in sequence to a question asked by another user.
All my conversations are 1 on 1 conversations.
