### ISSUE TITLE
more than a mongodb databasefile  use?

### ISSUE THREAD

**Issue by Air-boy** [gunthercox/ChatterBot#762]
like this
database="chatterbot-one-database"
database="chatterbot-two-database"
  can run?

**Comment by gunthercox** [comment]
This functionality isn't currently supported. Do you have a use case for when this would be needed?

**Comment by vkosuri** [comment]
@Air-boy could you please let me why you required two DB files for a single instance, and if possible usecase?

**Comment by Air-boy** [comment]
@vkosuri @gunthercox yeah,i want to use many field. for example: political,economy and so on. i want this chatbot Switch freely in two areas.   such as : i input political,it swith political  , i input economy ,it swith economy

**Comment by vkosuri** [comment]
@Air-boy I think you have train your bot with two database and make programming logic to switch between databases based on your input. I think this link will provide more information https://github.com/cool-shark/mongoengine

**Comment by gunthercox** [comment]
ChatterBot supports the ability for you to [add your own](http://chatterbot.readthedocs.io/en/latest/storage/create-a-storage-adapter.html) "storage adapters" to connect to databases as you see fit. You are welcome to modify the [existing storage adapter for Mongo DB](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/storage/mongodb.py) to switch databases depending on the requested content.

Right now this isn't a feature that has been commonly requested in ChatterBot and I'm not sure that I can justify adding this functionality to the project. Luckily the flexibility to create custom storage adapters does exist and I hope that it will provide enough functionality for you to accomplish what you need.

**Comment by Air-boy** [comment]
@gunthercox  this is very well ,really master
