### ISSUE TITLE
did chatterbot use nlp?   it use StanfordNLP?

### ISSUE THREAD

**Issue by Air-boy** [gunthercox/ChatterBot#763]
when i input :i want to withdraw money or i want to withdraw 20K  ,this mean is withdraw

**Comment by Air-boy** [comment]
@vkosuri @gunthercox

**Comment by vkosuri** [comment]
@Air-boy Chatterbot It uses http://www.nltk.org/

**Comment by gunthercox** [comment]
I'm going to close this ticket off. @vkosuri is correct, ChatterBot uses NLTK for natural language processing (NLP).
