### ISSUE TITLE
Django Example  Via Heroku Training not working. 

### ISSUE THREAD

**Issue by nonlin** [gunthercox/ChatterBot#764]
I've followed the migration and train commands and have my django site running on Heroku but every message I give it results in "hello". 

Here is my site live. 

https://polar-basin-92507.herokuapp.com/

Here is my current source. 

https://github.com/nonlin/SEBot

What am I missing to get this to train?

**Comment by vkosuri** [comment]
I checked it is working as expected. Could you please let me how you are Inputted your inputs

**Comment by nonlin** [comment]
@vkosuri I try "How are you?",  "Good Morning". And different stuff. 
What input did you try and what responses did you get? 
I'm not sure exactly what input will work with the default training I'm using.

**Comment by nonlin** [comment]
I found the source to the corpus and asking questions from there seems to work.

**Comment by vkosuri** [comment]
@nonlin could you place your solution, It helps others.
