### ISSUE TITLE
Training bot

### ISSUE THREAD

**Issue by dekken201** [gunthercox/ChatterBot#767]
Hello! I'm doing a college project and would like to ask a question and see if it applies with ChatterBot. 
I have a bunch of answers in a list for some specific questions about a specific subject. Is there some way I can "train" a model and make it give out the answer that matches best with whatever question the user inputs?
For example, user asks "what's the meaning of existance" and the bot will give out the most relevant "string" from my answers database related to that question? 
All questions and answers are to be of the same topic, for example, cotton. How it's produced, how are it's seeds, how do you plant it, etc. Would it still work, taking from the point that many answers would have a lot of keywords in common?

**Comment by nonlin** [comment]
Doesn't sound like you have an issue but rather asking how to train a bot?

There is docs on how to do that here.

http://chatterbot.readthedocs.io/en/stable/training.html

**Comment by dekken201** [comment]
I've checked the docs, but I couldn't find the exact way of developing what I described, and if it's even doable.
Should I just create a new training class? How should I go about doing it?

**Comment by vkosuri** [comment]
Currently chatterbot uses json files to train your bot

```Json
{
    'book' : {
        [
              'question',
               'answer'
        ],
        ....
        [
        ]    
    }
}

**Comment by dekken201** [comment]
Actually, right now, I only got one list with the answers, but I'd like to at least know if it will work.  What are the parameters for list training? How should I go about making my own training class, if necessary?
Do I really need the questions that go with it, or can I just feed the answers?

**Comment by vkosuri** [comment]
Yes, You could write your own class by extending Train class train method https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py#L16

**Comment by dekken201** [comment]
Does the bot accept other formats? Csv, from database? I'll see if I can transform my data to json if not.

-----Mensagem Original-----
De: "Mallikarjunarao Kosuri" <notifications@github.com>
Enviada em: ‎03/‎06/‎2017 10:09
Para: "gunthercox/ChatterBot" <ChatterBot@noreply.github.com>
Cc: "Dekken201" <lucksbp@gmail.com>; "Mention" <mention@noreply.github.com>
Assunto: Re: [gunthercox/ChatterBot] Training bot (#767)

Yes, You could write your own class by extending Train class train method https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py#L16

**Comment by vkosuri** [comment]
No

**Comment by dekken201** [comment]
Alright, thanks.
