### ISSUE TITLE
Custom Storage Adapter in DJango

### ISSUE THREAD

**Issue by iamhssingh** [gunthercox/ChatterBot#769]
This may not be an issue, just lack of documentation maybe. 

How to use custom adapter in Django version?

**Comment by iamhssingh** [comment]
Okay, its easy. Just follow the patter used while initialising w/o Django. Apologies!

**Comment by vkosuri** [comment]
This could help you http://chatterbot.readthedocs.io/en/stable/storage/create-a-storage-adapter.html

**Comment by iamhssingh** [comment]
I have already created a storage adapter. Didn't know how to use it in Django. Figured it out. BTW, can you tell how can I contribute by adding my adapter in this project? No experience in Git!

**Comment by vkosuri** [comment]
https://help.github.com/articles/creating-a-pull-request/
