### ISSUE TITLE
Automated Test Python2.7 support

### ISSUE THREAD

**Issue by iamhssingh** [gunthercox/ChatterBot#771]
I created a new pull but the automated tests are failing! How do I add support for Python 2.7?

**Comment by iamhssingh** [comment]
For more info, I have added ArangoDB Storage Support.

Do I have to create Test Case also?

**Comment by vkosuri** [comment]
thanks, and documentation possible

**Comment by vkosuri** [comment]
I am closing this issue, Updated in PR https://github.com/gunthercox/ChatterBot/pull/770
