### ISSUE TITLE
Graph based NoSQL

### ISSUE THREAD

**Issue by iamhssingh** [gunthercox/ChatterBot#772]
I have successfully implemented ArangoDB Storage Adapter. I have also checked it with DJango. It works like charm. (But for some weird reason online tests are failing. See for yourself: [Pull #770](https://github.com/gunthercox/ChatterBot/pull/770 )

Now I am thinking to create edges and graphs. This will boost the speed to getting statement significantly. How does that sound as a feature? 

I will start working on it right away. But need your feedbacks about if I should and what should I keep in my mind!

**Comment by vkosuri** [comment]
@iamhssingh Thanks, I am very new to [Aragon DB](https://www.arangodb.com/), I have few questions on this

> Now I am thinking to create edges and graphs. This will boost the speed to getting statement significantly. How does that sound as a feature?

Does this feature has capable to know prior graphs information. for example

```
User: Hey, Give me some milk
Bot: no, you have to purchase a token before
```

**Comment by iamhssingh** [comment]
I am also kind of new to Arango. Currently I only want to add graph system to existing logic. Basically, all responses will be connected to each other and as user types statement, we can add "nodes" which will link to other node with respective weight (how similar are they?). I need to structure it. 

But yes, context setup is also possible. And I have already written some stuff on setting up the context. Hopefully, I will share something soon. Give me a week or two?
