### ISSUE TITLE
requests.exceptions.ChunkedEncodingError:

### ISSUE THREAD

**Issue by peterel** [gunthercox/ChatterBot#773]
Hi,

When trying to use the Ubuntu corpus Im facing below. Note, all worked well approx 1 week ago when I tried the same training with this corpus. 

requests.exceptions.ChunkedEncodingError: ("Connection broken: TimeoutError(60, 'Operation timed out')", TimeoutError(60, 'Operation timed out'))

The downloading starts but doesnt finish, end up with above error. When restarting the training it starts extracting for a while but then ends in:

EOFError: Compressed file ended before the end-of-stream marker was reached

Any idea what I can do about this?

Note: Ive tired for some days and get the same error. So its not about temporary internet connection issue.

**Comment by vkosuri** [comment]
Its python requests error, instead I'll try make a PR, to download Ubuntu corpus file

**Comment by peterel** [comment]
@vkosuri Not sure I follow. Shall I do something or just await your PR to be approved and update my chatterbot?

**Comment by vkosuri** [comment]
@peterel I am busy with my other tasks, If possible could you make a PR?

**Comment by peterel** [comment]
@vkosuri Very strange. I was looking to try one more time to pinpoint where the issue was and it all started to work again. It downloaded and extracted "as before". So, Ill close this ticket for now.
