### ISSUE TITLE
I'm hoping for each given question to have a better chance at getting many possible responses.

### ISSUE THREAD

**Issue by neatville** [gunthercox/ChatterBot#777]
My basic setup.  

```
chatterbot = ChatBot("Charlie",
    response_selection_method=get_random_response,
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=[    
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.90,
            'default_response': 'OhNo'
        }
        ],
        database='Chat_Questions'
    )
chatterbot.set_trainer(ChatterBotCorpusTrainer)

corpus = 'favorites.corpus.json'

chatterbot.train(
    corpus
)
```  
Every time this python file run, the database would fill up more basic on what's in that corpus file that's listed. Here's a small sample of that json file.  

```
    [
      "what's your favorite band",
      "Nine Inch Nails"
    ],
    [
      "whats your favorite band",
      "Nirvana"
    ]
```  
So lets say the question to answer was "what's your favorite band". Too often, I think it would give the answer "Nine Inch Nails", all because that's the exact wording, character for character. I'd hope for an equally likely chance that it would get the "Nirvana" response. If I worded similar questions to be exactly the same in this json file, there would be many duplicate entries, making it inefficient.  

I hope that my concern makes sense. Can anyone suggest anything. 

Another thing. If the bot comes across a question like "what is your favorite brand", it might end up thinking it's asking what your favorite band is, because most of the letters are the same. It could end up giving some pretty funny answers.. can anyone recommend a good way to address this problem?

**Comment by sal48** [comment]
Try using the repetive response filter:

```
logic_adapters=[    
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.90,
            'default_response': 'OhNo'
        }
        ],
        filters=[
        'chatterbot.filters.RepetitiveResponseFilter'
        ],
```
That should keep the bot from saying the same thing every time. However, when you think of it, you might want it to say the same band, in this case. Like, if you gave me a diff band every time I asked you what your fave band was, I'd be very confused.

Anyway, try it out and lemme know what you think.
