### ISSUE TITLE
anaconda travis ci

### ISSUE THREAD

**Issue by vkosuri** [gunthercox/ChatterBot#781]
Master, I see many users are using anaconda for development/production environments. I think adding anaconda/conda to Travis will give a value add. For more information https://conda.io/docs/travis.html

If it is ok, can i make a PR?

**Comment by gunthercox** [comment]
Feel free to make a pull request. I'm not sure if all tests will pass at first, there seems to be some odd differences between normal Python installations and Anaconda setups.

**Comment by vkosuri** [comment]
Thanks Master i'll post my observations along with pull change
