### ISSUE TITLE
 Make sure Django training documentation is clear

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#783]
I'm assigning this task to my self to make sure that the documentation on training chat bots under Django configurations is clear and concise.

**Comment by MYZ88** [comment]
Thanks for your efforts. I believe this will help a lot of less experience users like me.

I faced a trouble to follow the current tutorial. Then, I used the modify Django example and follow the tutorial from django website to make it run.

**Comment by vkosuri** [comment]
@MYZ88 could you please let us know what changes you did make it work? I think it can help improve more documentation

**Comment by greggmojica** [comment]
@gunthercox Please keep us posted on this. Currently, training using this app is somewhat unclear...Thanks.

**Comment by sal48** [comment]
What is the status of this @gunthercox ? I was setting up my chatterbot to work with gitter, but that won't actually suit my needs. I'll be setting up the chatterbot as a django app this weekend.

If needed, I can either provide feedback behind what portions are currently unclear, or I can add comments to the current codebase. What would be more beneficial?

**Comment by gunthercox** [comment]
I haven't started work on this yet. Any feedback regarding the current documentation and any unclear parts of it would be useful.

**Comment by yousifa** [comment]
Adding how add custom adaptors and configure them within django would be helpful, especially if you could provide examples on custom logic and storage adaptors.

**Comment by sal48** [comment]
Yup, as @yousifa mentioned, the docs in the website are great for getting chatterbot integrated with Django: http://chatterbot.readthedocs.io/en/stable/django/index.html. However, I was a little lost immediately after.

After syncing  the database for chatterbot, ‘python manage.py migrate django_chatterbot’, what is the next step? I can launch the django server, but I don’t know where to initialize the chatterbot instance as my own. (Naming the chatbot, setting up the logic processors, filters, etc.) It seems that the views.py inside of django_chatterbot  folder contains the API endpoint, but I don’t know where to customize the code to ensure it makes it to my customized chat bot.

**Comment by sal48** [comment]
How is this coming along @gunthercox? I'm having issues setting up API Authorization from a separate server. (I want to create a section to allow users to interact with my chatbot from my blog, meta-game.org, hosted on a separate server.)

The easiest way to setup authorization seems to be setting up a [CSRF Token](https://docs.djangoproject.com/en/1.10/ref/csrf/), but I can't seem to get that to work. How have you worked with django and chatterbot? Was the django application hosting the html files that interacted with the bot, or did you setup an API that allows people to communicate with it from anywhere? Did you run into issues with CSRF Tokens?

**Comment by gunthercox** [comment]
@sal48 I haven't started work on it yet.

It sounds like you need to allow cross-domain requests to the API. There is a number of ways to do this. I highly recommend the `django-cors-headers` package for achieving this: https://github.com/ottoyiu/django-cors-headers/
