### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by LouisJacques** [gunthercox/ChatterBot#789]
I am currently using a common JsonFileStorageAdapter for testing and I wondered if with a 190 Ko json file it's normal that the training last about one minute. I need to use like 1Mo of data and i can't think about how much time a simple print will take.
Some of you use that amount of data in a production environment ? How did you manage to find a balance between the execution time and the amount of data that you can use ? Can you help me to increase the speed of training/print with some simple tricks ? Thanks !

**Comment by sal48** [comment]
Some of you use that amount of data in a production environment?

- JsonFileStorageAdapter shouldn't be used in a production environment. It's really just meant for testing. As soon as I started training my bot, I immediately noticed slowdowns in responses and the size of the db grew rapidly. I would highly recommend switching to a mongodb or something else. There's tutorials in the docs to do so.

Can you help me to increase the speed of training/print with some simple tricks?

- The docs have a nice spot for training, especially if you're just getting started. (http://chatterbot.readthedocs.io/en/stable/training.html) Look at the CorpusTrainer. If you're trying to get the bot moving quickly, that will help you set it up with some quick phrases.

Good luck!
