### ISSUE TITLE
PyPi text formatting

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#79]
@gunthercox  Just an FYI that the text is not formatting properly on PyPi.

https://pypi.python.org/pypi/ChatterBot/0.2.9

**Comment by gunthercox** [comment]
I am aware of the issue. It is due to an improper conversion of `.md` format to `.rst`. I have been meaning to figure out what line the problem is happening on but haven't had time yet. Thank you.

**Comment by DarkmatterVale** [comment]
Awesome; I just wanted to make sure you were aware of the problem.

**Comment by gunthercox** [comment]
This issue has been corrected in the release of ChatterBot v 0.3.0.
