### ISSUE TITLE
Giving nested json-data as database

### ISSUE THREAD

**Issue by decode007** [gunthercox/ChatterBot#791]
Can  chatterbot handle the nested json data and get the response on the basis of ``primary key``?
Internal keys could be same. Like in sample below: ``key1``, ``key2`` will have same internal key parms.

```Json
{
  "key1": {
    "details": [
      { "name" : "xxx",
         "surname" : "yyy"
      }]
  },
  "key2": {
    "details": [
      { "name" : "xxx",
         "surname" : "yyy"
      }]
  }
}
```

**Comment by vkosuri** [comment]
@decode007 Current chatterbot support only simple JSON.

``` JSON
{
   "statement",
   "response"
}
```

By looking your JSON response, you could write your own trainer class for example [UbuntuCorpus](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py#L216)

Add addition details using [add_extra](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py#L350) statement object

More information about we could found here [statement ](http://chatterbot.readthedocs.io/en/stable/conversations.html?highlight=extra_data#statements)

**Comment by vkosuri** [comment]
@decode007 I am closing this issue, Feel free reopen this issue if you have any questions.
