### ISSUE TITLE
Issue with English Corpus

### ISSUE THREAD

**Issue by AmusingThrone** [gunthercox/ChatterBot#793]
So I was just testing ChatterBot, and made a simple Discord Bot. I found the following logs in my files:

```
[%] Query: "What are you?"
[%] Response: "Who? Who is but a form following the function of what"
[%] Query: "Who are you"
[%] Response: "Who? Who is but a form following the function of what"
```

I also found quite a bit of grammar mistakes, responses that made no sense, etc. Is there any place I can contribute to this, or I can go ahead and manually fix. It would be a pain to have to manually override this by using a list.

Edit: I maybe confused, but I cannot create my own corpus bank in JSON if I am using MongoDB right?

**Comment by vkosuri** [comment]
@AmusingThrone Yes, The corpus files are located here https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data

**Comment by vkosuri** [comment]
I am closing off this issue, it was addressed here https://github.com/gunthercox/chatterbot-corpus/pull/23
