### ISSUE TITLE
Chatterbot Issues with Gitter

### ISSUE THREAD

**Issue by sal48** [gunthercox/ChatterBot#794]
I saw that people requested Gitter examples, and some were added. However, I haven't been able to get the bot to connect to Gitter, and when looking at the constructor, it looks so basic. No where in the examples do we pass an OAuth key or secret key. Has anyone been able to connect to Gitter using simply the API key? Here's my sample below attempting to connect to a room called 'meta-game'. (I blocked out my API key for obvious reasons.)

```
# Create a new ChatBot instance
bot = ChatBot('Ava',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=[
        {
            "import_path": "chatterbot.logic.BestMatch"
        }
    ],
    filters=[
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
	# Gitter information
    input_adapter="chatterbot.input.Gitter",
    gitter_api_token="[my_api_key]",
    gitter_room="meta-game",
    gitter_only_respond_to_mentions=True,
    output_adapter="chatterbot.output.Gitter",

    database='ava_gitter',
    database_uri='127.0.0.1:27017',
    trainer='chatterbot.trainers.ListTrainer'
)
```
The above code fails to connect to Gitter with the failure code:

```chatterbot.input.gitter.HTTPStatusException: u'404 status code recieved'```

Has anyone been successful with Gitter? Am I missing something obvious?

**Comment by sal48** [comment]
I figured this out, and there seems to be a bug when joining a room. I know the room id I wanted to join, so I hardcoded the value in input.gitter.py. I can run this to ground, if anyone else has an issue with it, and they don't know python code well. (The issue seems to be that the call was a post, where only a get is supported to get room information.)

**Comment by vkosuri** [comment]
@sal48 Great resolving your issue, if possible could you make a PR to solve this issue?

**Comment by sal48** [comment]
Sure. After I finish profiling chatterbot to figure out my performance issues, I can make a general fix for the Gitter adapter.

I would like someone else to confirm that they're having issues. Basically, I tried to use the current chatterbot on master, and I was getting 404's when connecting.

**Comment by gunthercox** [comment]
Hi @sal48, I can confirm the issue that you encountered.

```
 31, in __init__
    room_data = self.join_room(self.gitter_room)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/input/gitter.py", line 58, in join_room
    self._validate_status_code(response)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/input/gitter.py", line 41, in _validate_status_code
    raise self.HTTPStatusException('{} status code recieved'.format(code))
chatterbot.input.gitter.HTTPStatusException: u'404 status code recieved'
```

**Comment by topcec** [comment]
Have you tried adding "/Lobby" to your chat room name?
example:
`gitter_room="meta-game/Lobby",`

I had the same issue and this resolved it.
