### ISSUE TITLE
Cannot get version number

### ISSUE THREAD

**Issue by yazdat** [gunthercox/ChatterBot#795]
`python -m chatterbot --version`

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/__main__.py", line 8, in <module>
    print(chatterbot.__version__)
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by gabru-md** [comment]
@yazdat 
to get the version number try:
```sh
import chatterbot
chatterbot.__version__
```

This should possibly result in an outcome like:

```sh
'0.6.0'
```

**Comment by vkosuri** [comment]
I am not sure which Operating system are you using, Even after @gabru-md suggestion didn't worked, try to ``pip install chatterbot`` If it is Linux flavor try to ``sudo pip install chatterbot``

**Comment by yazdat** [comment]
Thanks for the response  gabru-md and  vkosuri. 

import chatterbot
chatterbot.__version__

worked fine. I am running 0.6.1
I'm experimenting with chatterbot to use on a robot. I'm sure I will have more questions. I hope to contribute where I can.

**Comment by Barathwaja** [comment]
even for me this **python -m chatterbot --version** at beginning then I used **chatterbot.__version__** to find my version ...
