### ISSUE TITLE
how to train a corpus which i downloaded?

### ISSUE THREAD

**Issue by Barathwaja** [gunthercox/ChatterBot#799]
Hi there I downloaded a corpus json file has data about planets. when I imported it in train function and talks about any planet it doesn't speak.
Can anyone help me on this.. Thanks.. !! 

![image](https://user-images.githubusercontent.com/5066436/27508488-c0d44d82-5903-11e7-9a46-b57a4be8322c.png)

![image](https://user-images.githubusercontent.com/5066436/27508460-fbdcac18-5902-11e7-9441-af5a6c42a2b5.png)

**Comment by gunthercox** [comment]
Hi @Barathwaja, it looks like the data you downloaded isn't in a format that ChatterBot can read. You can still use this data but you will need to find a way to convert it to match the format that ChatterBot's training classes expect.

Here is a short example of the format that ChatterBot expects it's corpus data to be in:

```json

{
    "conversations": [
        [
            "Good morning, how are you?",
            "I am doing well, how about you?",
            "I'm also good.",
            "That's good to hear.",
            "Yes it is."
        ],
        [
            "How are you doing?",
            "I am doing well, how about you?",
            "I am also good.",
            "That's good."
        ],
        [
            "Have you heard the news?",
            "What good news?"
        ],
        [
            "What is your favorite book?",
            "I can't read.",
            "So what's your favorite color?",
            "Blue"
        ]
    ]
}
```

There is more information on the current set of available corpus trainers for ChatterBot in the documentation http://chatterbot.readthedocs.io/en/stable/training.html

**Comment by Barathwaja** [comment]
Yep sure mate.. thanks will try .. but if I wanna du like wat I asked say I feeded info about something and if I ask a question it should frame or through output based on that soo I hope you understand wat I have said so where do I start?? Can you shed some light ?? Thanks..

**Comment by gunthercox** [comment]
You could always write your own training class that takes the planetary data file directly.

**Comment by Barathwaja** [comment]
I feel like I can't understand how to write a training class in ur docs.. can you please tell a bit clear .. and thanks custom QA corpus worked 😊

**Comment by gunthercox** [comment]
Sure, maybe an example would help? This is what the corpus trainer that is currently used looks like. It takes each conversation that is listed in the corpus and adds it to the bot's knowledge base. Each "conversation" in the training data is a series of statements where each statement is a response to the previous one.

You would probably want to make modifications so that your version converts the planetary data into sentence-like data so that the chat bot's responses sound natural.

```python
# https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py
from chatterbot.trainers import Trainer

class ChatterBotCorpusTrainer(Trainer):
    """
    Allows the chat bot to be trained using data from the ChatterBot dialog corpus.
    """

    def __init__(self, storage, **kwargs):
        super(ChatterBotCorpusTrainer, self).__init__(storage, **kwargs)
        from .corpus import Corpus

        self.corpus = Corpus()

    def train(self, *corpora):
        trainer = ListTrainer(self.storage)

        # Allow a list of corpora to be passed instead of arguments
        if len(corpora) == 1:
            if isinstance(corpora[0], list):
                corpora = corpora[0]

        # Train the chat bot with each statement and response pair
        for corpus in corpora:
            corpus_data = self.corpus.load_corpus(corpus)
            for data in corpus_data:
                for pair in data:
                    trainer.train(pair)
```

**Comment by Barathwaja** [comment]
Thanks I will look into it .. will close the issue now thanks . .. :)
