### ISSUE TITLE
Additional response algorithms

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#8]
These are additional methods for returning responses from ChatterBot. These methods will increase the accuracy of any possible output that the program can provide. For example, questions about a specific subject will have to be processed much differently than simple greetings. Some algorithms that would be useful to implement may include the following:

- [ ] **find_a_name()** A method designed to determine the most likely answer to a question regarding a name of a person, place, etc.
Example input: "Who was the president of the United States in 1953?"
Example output: "Dwight D. Eisenhower"
- [x] **evaluate_mathematically()** A method which checks an input value for any references to mathematical operations. If they exist, it will attempt to return a solution. This method should be able to evaluate both words and mathematical characters.
Example input: "What is 2 * the square root of 4?"
Example output: "4"
- [x] **custom_methods()** This would allow a user to ask the bot to run a specific command, for instance entering "Do I have any new messages?" could check several services for new notifications. This would be based on loading in a reference to a third party method upon initialization of the program. (Accomplished through the addition of the adapter system)

***

- ~~**small_truths()** This idea suggests that by knowing a collection of true facts about everyday items, the program will be able to determine the truth of more complex statements. For instance, note the statement "can a can can cans". As a human we are able to determine that a can is a metal container which cannot engage in the act of canning because it is a non-mechanized inanimate object. A computer on the other hand would find this statement more challenging to decipher. Microsoft Word 2010 detects this statement as incorrect http://imgur.com/crDA3eh.~~
- ~~When the program receives an input item, it will process the input using each of the different algorithms and saving the value returned from each.~~ This will be addressed in https://github.com/gunthercox/ChatterBot/issues/85

Compare each answer to known questions and answers. There will need to be a way to  to calculate how successful an algorithm is at generating the appropriate response. The result of this calculation will be used to determine the most appropriate response to return. To do this, the result of each algorithm which was run on the input statement will be compared to training text statements which most closely resemble the initial question. The closest matching response should be the result which has the closest matching question.

**Future optimization**
Further optimization may be possible by performing preliminary checks to determine if certain algorithms do not need to be run when evaluating an input item. An example of this might be that an algorithm designed to extract and interpret mathematical operations in an input statement will not need to be executed if the input contains no numeric values or mathematical characters.

**Comment by DarkmatterVale** [comment]
Would you mind if I took a look at evaluate_mathematically and tried to add that?

Also, just a few comments/questions that I would like to add.

1) How do you plan on choosing which algorithms to apply? Even though you save the input, how will the chatbot know which input to actually use?
2) How will you feed information to the find_a_name() method? For example, how would you train the bot to answer "Who was the president of the United States in 1953?"?
3) What custom methods do you have in mind? Would you want to use my personal assistant as a means for executing custom methods? Or do you already have a plan in mind?

**Comment by gunthercox** [comment]
Sure, the only thing I can think of for mathematical evaluation is that you should decide ahead of time if you just want to deal with numbers and operators, or a combination of those and words. Such as seven + 8.

For the other questions,

1) I am currently unsure about how to logically determine which algorithm to apply. This feature requires an element of trail and error testing that is not currently present in the program. The main issue stems from the difficulty of measuring the "success" of a given response. For instance the response of "You are welcome" could be considered a _successful_ response to "Thank you", however there is no basis for measuring the value of success without prior experience or a way to verify the _correctness_.

2) I think the concept of the find_a_name method could be refactored into something more general that would allow the program to search a knowledge base for a result and format the findings as a proper sentence. Wikipedia database dumps might be a good source of information to use as a knowledge base.

3) This ticket predates the addition of adapters in ChatterBot, the concept for a custom_method feature was a possible precursor to this. I think in the future, the direction will be moving towards the ability to set multiple logic adapters where some could handle things such as conversations and others could accomplish more complex tasks when the bot is appropriately prompted. Completion of this stage of design would rely a bit on question (1) because there needs to be a way to measure the success of a one response choice against another.

**Comment by DarkmatterVale** [comment]
Ok. I will take that into account.

Sorry for all of the changes on the commits....Github is not cooperating with me right now...

**Comment by DarkmatterVale** [comment]
I'm going to be swamped for a little while because of Google Code In, but I will try to work on find_a_name() and get that done by the end of December. I will post a comment containing the specifics for how I plan to develop the algorithm to find a name ( or fact ) as soon as I can.

**Comment by gunthercox** [comment]
Awesome, I will be interested to see what you come up with!

**Comment by dmartincc** [comment]
Some clues about how to do semantic parsing of questions: http://cs.stanford.edu/~pliang/papers/freebase-emnlp2013.pdf

By the way, from my point of view some algorithms that could fit quite well into chatterbot are, a POS tagger, grammar rules from POS tags and custom dictionaries, a named entity recogniser, trigger classifiers (intention, interests, etc.) and access to a third party sources like wikipedia.

Giving these capabilities, chatterbot could understand this kind of questions or statements:

Where is New York? 
Who is Albert Einstein?
I usually play basketball at the New York Knick's Stadium  
I would love to read a new book
...

I would love to help.

**Comment by DarkmatterVale** [comment]
@dmartincc It would definitely be a nice addition to have a "utility kit" for functions like this. We could create custom implementations of each to fit out needs, then use them when parsing input. I will look into adding something like this for chatterbot. @gunthercox What do you think?

Although I would say you are making a little bit of a jump here; you can't just have those functions and then expect chatterbot to be able to respond to "Who is Albert Einstein?". It will require other work including a knowledge "database" & a way to parse through that information.

**Comment by gunthercox** [comment]
I agree these would be useful additions. At the moment chatterbot lacks the ability to use the knowledge it accumulates to understand the context or meaning of the input it receives. I would recommend taking a look at NLTK, I believe it already has implementations of a few of these algorithms.

**Comment by DarkmatterVale** [comment]
I have done a lot with NLTK's built in functions, and I agree they are definitely a good place to start. Unfortunately, they tend to degrade in capability as the sentences and ideas get more complex, mainly because the functions are based on math, not semantic understanding. Because of this, we will eventually need to use a custom implementation (haven't really thought about the details yet).

**Comment by gunthercox** [comment]
I'm going to close this ticket off because it appears that all of the items it covers have either been implemented or are covered in #90
