### ISSUE TITLE
Issue with nltk_data

### ISSUE THREAD

**Issue by sanyam8182** [gunthercox/ChatterBot#802]
When i try to run chatterbot on the local server it shows this error:

[nltk_data] Error loading stopwords: [nltk_data] Error loading wordnet: [nltk_data] Error loading punkt: [nltk_data] Error loading vader_lexicon

Along with it, it also shows the correct response.

**Comment by gunthercox** [comment]
Hi @sanyam8182, have the required NLTK files been downloaded to your local server?

**Comment by sanyam8182** [comment]
i have downloaded the files in my system but i dont know about the server.

**Comment by vkosuri** [comment]
> have the required NLTK files been downloaded to your local server?

It means, the chatterbot running machine, in your case your NLTK downloaded machine.

**Comment by sanyam8182** [comment]
yes i have all the files mentioned in the error

**Comment by vkosuri** [comment]
Try to do fallowing steps

``` Bash
>>> import nltk
>>> print(nltk.data.path)
```
Check the files are copied into specified above directory or not. If files are there then it should work, even after also you are getting same error, try to download all corpus files

```Bash
$ python3
>>> import nltk
>>> nltk.download('all')
```

**Comment by sanyam8182** [comment]
on running the above commands i get this output:
['/Users/yuvikakoul/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']

which directory am i supposed to check

**Comment by vkosuri** [comment]
your home dir i.e '/Users/yuvikakoul/nltk_data'

**Comment by sanyam8182** [comment]
it contains all the files, still i'll try downloading all the corpora files

**Comment by gunthercox** [comment]
@sanyam8182 Remove the files it contains. They will be re-downloaded (hopefully without errors this time) automatically by ChatterBot.
