### ISSUE TITLE
'Statement' object has no attribute 'encode' - The statement has a string attribute like the confidence?

### ISSUE THREAD

**Issue by neopedro** [gunthercox/ChatterBot#807]
I have an issue with encodings, I can't use the str() function to convert the response to a string without getting errors and I can't use an encode function, because the Statement is not a string.

**Comment by vkosuri** [comment]
@neopedro Try to add ``encoding header`` to your source file. for example ``# -*- coding: utf-8 -*-``.

If you share stack trace of what you have encountered error to debug further.

**Comment by gunthercox** [comment]
@neopedro I think you want `statement.text`, this is the string value of the statement.
