### ISSUE TITLE
Session creation is duplicated

### ISSUE THREAD

**Issue by bilalbayasut** [gunthercox/ChatterBot#811]
Hi friends, does anyone experienced this problem :

I tried to make the chatbot to be used by multiple user 

``` Python
class SystemSession(object):
    def __init__(self, **kwargs):
        self.agent_id = kwargs.get('agent_id')
        self.session_id = kwargs.get('session_id')
        self.default_session_id = kwargs.get('default_session_id')

    def process(self):
        existing_session = Database.find_one('system_session', {"agent_id": self.agent_id})
        if not existing_session:
            session_id = self.create()
        else:
            session_id = existing_session['session_id']
        return session_id

    def get_all(self):
        pass

    def create(self):
        default_session = self.default_session_id
        data = {
            "agent_id": self.agent_id,
            "session_id": default_session,
            "created_at": datetime.now(),
            "updated_at": datetime.now()
        }
        Database.insert(collection='system_session', data=data)
        return default_session
```
By using code above, when I do json post and retrieve the session_id, the session_id is duplicated, means that the code generates the same session_id instead of unique one.. any ideas ?

FYI for this code I use the self.bot.default_session.id_string , as it generates new session. but I just realized when I post from the same PC by passing email and utterance , the bot code generates identical session_id string which makes it duplicated

**Comment by gunthercox** [comment]
@bilalbayasut The default session id will be the same for each instance of a chat bot. You will want to generate a new id for each "user session" (however you are tracking that) that is created.

**Comment by bilalbayasut** [comment]
I've implemented the new session from ConversationSessionManager , but I got this error any ideas ?

  File "/home/user/.local/lib/python3.6/site-packages/chatterbot/filters.py", line 31, in filter_selection
    if session.conversation.empty():
AttributeError: 'NoneType' object has no attribute 'conversation'

**Comment by vkosuri** [comment]
@bilalbayasut Any further updates?

**Comment by bilalbayasut** [comment]
Ok I have used the conversationManager, but the weird thing is when I use the generate_response() function and add seession_id within it, somehow the generate_base_query is failed.. somehow it looks like the session_id is None

  File "/home/bilal/.local/lib/python3.6/site-packages/chatterbot/storage/storage_adapter.py", line 41, in generate_base_query
    self.base_query = filter_instance.filter_selection(chatterbot, session_id)
  File "/home/bilal/.local/lib/python3.6/site-packages/chatterbot/filters.py", line 31, in filter_selection

**Comment by gunthercox** [comment]
@bilalbayasut I'm currently working on changes that will allow "sessions" to be stored in the database. They are currently only stored in memory. I'm still working on the changes but they should definitely resolve this problem.

**Comment by gunthercox** [comment]
I'm going to close this issue off. It should be resolved at least on the master branch on GitHub and following the next release to PyPi.
