### ISSUE TITLE
does ChatterBot handle context ? 

### ISSUE THREAD

**Issue by guitarzero** [gunthercox/ChatterBot#812]
Hi,
Thanks for ChatterBot work. Very impressive.
Just a question here : does ChatterBot handle context ? 
In other words, I would like something similar to have a variable set after an answer of Chatterbot . This variable then could be retrieved to select the proper Adapter. I hope i am clear.
Better explained here : https://chatbotsmagazine.com/maintaining-context-in-chatbots-2016b6a5b7c6
Thanks
Stéphane
Sorry: don't know how to label this issue as question

**Comment by gunthercox** [comment]
Currently ChatterBot responds only within the context of the previous input. Work is being done to extend the range of the chat bot's "memory" to make responses in conversations more coherent.

#276 Is currently open for tracking these changes.

**Comment by guitarzero** [comment]
Thanks for your quick answer

**Comment by Selvaganapathi06** [comment]
Hi,
Thanks for chatterbot, it's superb. I have a qusetion?. how to handle contexts?. i'm new so, please share info of context based bot respose.
