### ISSUE TITLE
Action / Intention / Execution Recognition 

### ISSUE THREAD

**Issue by davizucon** [gunthercox/ChatterBot#820]
I wonder if I can interact with bot and it recognize several words or phrases that fire an Action or recognize an Intention that interact with external source and give me a response. 

eg:
User: How about the weather today?
Bot : <city>,<state> ... forecast today.

or: (intention) 
User: I want to run outside today.
Bot : It may rain today.

or (action/execution)
User: Turn on living room lights.
Bot: Sure ! A minute!
Bot: Done, enjoy!

I don't know if LogicAdapter, StorageAdapter either I/OAdapter is the right place to put this logic. 
Maybe some kind of Intention/ActionAdapter, that complements an kind of specific answers that have an special blank space to fill in with results from integration.

Thanks.

**Comment by vkosuri** [comment]
@davizucon My views are like this. Yes you could truly achieve this task but you have to apply some chatterbot hacks here. 

The chatterbot requires some training data, You have to prepare a your train data with some external input methods for example external REST API calls. There are many open external event generators through REST  API. My suggestion google REST API event 

I have described above through an example. Related issue https://github.com/gunthercox/ChatterBot/issues/482

```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot


# Create a new instance of a ChatBot
bot = ChatBot(
    'Action or Intent Response Example Bot',
    storage_adapter='chatterbot.storage.SqlStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'statement_comparison_function': 'chatterbot.comparisons.jaccard_similarity',
            'response_selection_method': 'chatterbot.response_selection.get_first_response'
        },
        {
            'import_path': 'chatterbot.logic.SpecificResponseAdapter',
            'input_text': 'Help me!',
            'output_text': 'Ok, here is a link: https://openweathermap.org/current'
        }
    ],
    trainer='chatterbot.trainers.ListTrainer'
)

# Train the chat bot with a few responses
bot.train([
    'Current weather in London',
    'http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1',
    'Have you read the documentation?',
    'No, I have not',
    'This should help get you started: http://chatterbot.rtfd.org/en/latest/quickstart.html'
])

# Get a response from bot
response = bot.get_response('weather in London?')
# Handle JSON data, get all required data and print them
print(response)
```

**Comment by davizucon** [comment]
@vkosuri nice hack! Issue #482 for is very specific, anyway I'll give a try! 
By the way, my initial idea would be to have something apart from the conversation,  but its ok, using your hack, it can be extended with some metadata inside it.

What you think ?

eg:.
bot.train([
    'Current weather in London',
    '{"adapter":"chatterbot.logic.SpecificResponseAdapter"},
    'Have you read the documentation?',
    'No, I have not',
    '{ "text" : "This should help get you started", "url": "http://chatterbot.rtfd.org/en/latest/quickstart.html"}'
])

**Comment by vkosuri** [comment]
@davizucon I think the specified information is sufficient, I am closing off this issue, please feel free reopen if you have any specific question on this issue.
