### ISSUE TITLE
How does the chatbot learn? 

### ISSUE THREAD

**Issue by juanpialbano** [gunthercox/ChatterBot#832]
Hi, 
   
   When the chatbot starts to work and answers the questions of different users, how does the chatbot learn? 

How does the chatbot get **feedback**? 

How does the chatbot know if the answer was correct or not?
   
 Also
   
 What are the best practices for building a chatbot? How should it be configured?
   
 Should I use Adapters, Filters, etc?

**Comment by vkosuri** [comment]
@juanpialbano A detailed information available here http://chatterbot.readthedocs.io/en/stable/#how-chatterbot-works

However i would like add some information here on learning process. 

1. Chatterbot is Retrieval-Based Bot , all retrieval-based bot are uses some [pre-defined responses](https://github.com/gunthercox/ChatterBot/wiki/ChatterBot-Corpus-Specification#data-representation-schema).

2. After that you have to [train](http://chatterbot.readthedocs.io/en/stable/quickstart.html#training-your-chatbot) your bot. 

3.  The [training process](http://chatterbot.readthedocs.io/en/stable/training.html#training) stores all  [statements ](http://chatterbot.readthedocs.io/en/stable/conversations.html#statements) and [responses ](http://chatterbot.readthedocs.io/en/stable/conversations.html#responses) into a [specified database](http://chatterbot.readthedocs.io/en/stable/storage/index.html#storage-adapters).

4. And also forms a [statement-response-relationship ](http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-response-relationship)

5. When ever user inputs statements, the response selection process uses some [logic adapters](http://chatterbot.readthedocs.io/en/stable/storage/index.html) to select proper response by [compare ](http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-comparison) each statement with inputted statement.

Please let me know if you are still looking any more information.

**Comment by juanpialbano** [comment]
@vkosuri thanks but I have doubt, How does the Chabot learn ? 

here it doesn't explain so much : [ http://chatterbot.readthedocs.io/en/stable/#how-chatterbot-works](url)

When the Chabot makes a response, it stores the request-response in the database for future queries?
How does he know if a request-response was right o wrong so he can use it in the future ? 

Thanks in advance

**Comment by vkosuri** [comment]
@juanpialbano Thanks for your inputs we will improve that phase

> When the Chabot makes a response, it stores the request-response in the database for future queries?

Yes, 

> How does he know if a request-response was right o wrong so he can use it in the future ?

Using [Response selection methods](http://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#module-chatterbot.response_selection)

Let me know if you need any further help

**Comment by telkomops** [comment]
Hi Query on the  [response relationship](http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-response-relationship). does the statement have user affinity. for e.g. User A Says Statement 1, User A Says Statement 2 , User B Says statement 3.
Stored as Statement 1 , Statement_2 ::: In_response_To Statement_1 , Statement_3 :: in_Response_To_Statement_2.
In here the user affinity is lost , correct? how is it typically handled by other users, do you format , 1 and 2 as 1 statement , so that indexing happens as Statement1+Statement 2 , Statement3 :: in_response_to_Statement1_Statement2 ?
