### ISSUE TITLE
 Chatterbot from a Java program

### ISSUE THREAD

**Issue by juanpialbano** [gunthercox/ChatterBot#836]
Hi, I want to run Chatterbot from a Java program, Which is the best option?

How can I achieve that?

**Comment by vkosuri** [comment]
@juanpialbano Currently there is no support on Java. However you could make other workarounds like [Django integration](http://chatterbot.readthedocs.io/en/stable/django/index.html)

**Comment by gunthercox** [comment]
@juanpialbano Just to add to what @vkosuri mentioned, it is possible to build a web API that could allow a Java application to post data and get responses from a chat bot.

**Comment by juanpialbano** [comment]
I  want to put it in Production in my job, I developed an api with werkzeug  but there is not suppor for python in the server ... 

I'm trying to make work with Jython but I have a lot of problems

**Comment by gunthercox** [comment]
Sorry, I don't have any experience with Jython.

**Comment by gabru-md** [comment]
I believe if yoy make a server and then access the chatterbot with custom setup api then you can definitely run chatterbot inside java. 
If there will be a web api , like which produces JSON objects as response then ot can be used overultiple platforms.

I hope this help. 
Cheers!

**Comment by gabru-md** [comment]
@gunthercox sir,

can i start the work on the API ?

**Comment by gabru-md** [comment]
@gunthercox  sir,

can i make the web platform / API for chatterbot?

**Comment by gunthercox** [comment]
@gabru-md What kind of web platform are you imagining?

**Comment by gabru-md** [comment]
sorry! i mean an API as i discussed above.
It will give JSON results for every query. So that any Chatterbot can be used with any programming language.
i have it ready.

**Comment by gunthercox** [comment]
Is your API build using ChatterBot's Django integration or does it use a different framework?

**Comment by gabru-md** [comment]
mine is simple.

It uses node.js for backend and python for response prediction.
sir, you can see it here: [chatterbot-api](https://github.com/gabru-md/chatterbot-api)
i've tried it on localhost though! :P

#justaBeginner

**Comment by gabru-md** [comment]
any suggestions sir ?

**Comment by gunthercox** [comment]
ChatterBot is intended to support the ability for developer to use it in web based APIs. I'm glad that you were able to get this to work for your project.

Right now I don't think I'm ready to support an additional API example being added to the project.

@juanpialbano I'm going to close this ticket off. I hope this conversation has served to provide a sufficient response. There are many ways to get software written in different programming languages to communicate with each other.
