### ISSUE TITLE
Advance use of logic adpater?

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#845]
Hi there, first of all, I would like to say thank you to gunthercox for writing this engine, this engine is amazing.

Assume that i had a currency exchane rate table based on hong kong dollar in database:
Usd: 0.13
Yen: 700
Etc...

If I want to impletment currency checker function to bot like this:

(Default currency is Hong Kong dolloar)
Me: usd rate 
Bot: 1 hkd = 0.13 usd
Me: us dollar rate
Bot: 1 hkd = 0.13 usd
Me: yen rate. *(Yen is japanese dollar name )
Bot: 1 hkd = 700 yen
Me: 1000 yen = ? Usd
Bot: 1000 yen = 20 usd

Do i need to create a new logic adpater for this? If so, how to teach the bot to identify the currecny code/name/amount from input and match it with database.

Second question is how to create corpus embedded with dynamic value from database. For example, if i want to ask the bot about the open time of office, i would expect the bot answer: The open time is 10:00am, but if i train this answer with traidition corpus, i would have to train it every time when open time is changed, which make nk sense to program this.

**Comment by vkosuri** [comment]
@nggary 

> Do i need to create a new logic adpater for this? If so, how to teach the bot to identify the currecny code/name/amount from input and match it with database.

Yes, here is an example of [Mathematics Evaluation](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/logic/mathematical_evaluation.py)

> Second question is how to create corpus embedded with dynamic value from database. For example, if i want to ask the bot about the open time of office

You could found more information in this thread https://github.com/gunthercox/ChatterBot/issues/820

**Comment by nggary** [comment]
For the second part of this question is it possible to make a enhancement to the engine? Such like this:
{
    "test": 
    [
        [
            "What is the best selling product?",
            "The best selling product is [class.method]"
        ],......

The response with automatically replace the tag [class.method] to static method from specific class

**Comment by vkosuri** [comment]
Yes, you can write using some type template mechanism, here is an example i have wrote long back https://github.com/gunthercox/ChatterBot/issues/518#issuecomment-268188844
