### ISSUE TITLE
Responses based the context of the conversation

### ISSUE THREAD

**Issue by juanpialbano** [gunthercox/ChatterBot#847]
Hi, How to make a response based in the context of the conversation?

I mean, if the user say 'I have an error' is not the same if previously he said he was transferring money that if previously he said he was changing his password

So, how can I manage responses based in the context of the conversation?

**Comment by gunthercox** [comment]
Hi @juanpialbano, I am currently working on changes that will add support for this functionality. It currently isn't possible but it will be once I finish making those modifications. See #828 for details.
