### ISSUE TITLE
Create New bot

### ISSUE THREAD

**Issue by PrabinPC** [gunthercox/ChatterBot#849]
Where to write the this section of code. Please kindly help me
If you are using Python 2.7, be sure that the unicode header is the first line of your Python file: 
```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
chatbot = ChatBot("Ron Obvious")
```

**Comment by nggary** [comment]
Please take a look on the example code

**Comment by vkosuri** [comment]
@PrabinPC I am assuming you are trying use this example on fallowing details

OS: Linux
Language: Python

> Where to write the this section of code. Please kindly help me

If want run your script, here some of the steps i am trying to plot in Linux terminal

1. Activate [virtual environment](http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/)
2. Install chatterbot using [pip](https://github.com/gunthercox/ChatterBot#installation)
3. Open new file using your [favorite editor](https://www.cs.colostate.edu/helpdocs/vi.html)
4. Paste above [example](https://github.com/gunthercox/ChatterBot#basic-usage)
5. Run it using Python interpreter.

```Bash
$virtuenv venv
$source venv/bin/activate
(venv)$pip install --upgrade chatterbot
(venv)$vi bot.py
# -- coding: utf-8 --
from chatterbot import ChatBot
chatbot = ChatBot("Ron Obvious")
:wq
(venv)$python bot.py
```
