### ISSUE TITLE
Training the bot response same answer by asking different question?

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#853]
Sample corpus as following:
"new" : {
"What's news?",
"Here is the news: XXX"
},{
"Any news?",
"Here is the news: XXX"
}

Is there any way to train the bot response the same answer but reduce the duplicate training corpus item without implement new training class?

**Comment by juanpialbano** [comment]
Hi, I've made an small function for this : 
```

def processMultiInput(chatbot, input_list, response):
    print(" => processMultiInput ...")
    for item in input_list:
        print(' training chatbot : "' + item + '" => "' + response +'"')
        chatbot.train([item, response])

input_list = ["What's news?", "Any news?"]
response = "Here is the news: XXX"

processMultiInput(chatbot, input_list, response)


```

Hope Hope this can help you

**Comment by nggary** [comment]
Wow, thank you very much.I will try this.
