### ISSUE TITLE
How it handle conversation of booking?

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#857]
If I want to create an account by the chatbot:

Me: Hi, I want to book the dinner.
Bot: May I have your name?
Me: Peter
Bot: May I have your mobile number?
Me: xxxxxxxxxxxxxx
Bot: What time you want to eat at?
Me: 8:00 pm
Bot: Your table is reserved.

This conversation involve few questions:
1. How do the chatbot store the booking information from multiple input (name, mobile no. and time)?
2. How to validate the input from user and move on to next question or ask the user to re-enter?
3. How to process/cancel this booking request at the end of conversation?

**Comment by vkosuri** [comment]
You have to write your own logic adapter to handle above scenario, For more information about custom logic adapter will find [here ](http://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html).

However an example code located in this issue comment https://github.com/gunthercox/ChatterBot/issues/309#issuecomment-249583779

**Comment by nggary** [comment]
Thanks for pointing me the direction.

**Comment by nggary** [comment]
[#309 (comment)](https://github.com/gunthercox/ChatterBot/issues/309#issuecomment-249583779) is a good example, but it still doesn't have the multi-step.

**Comment by nggary** [comment]
I found that there is a sample code of [Chat form](https://github.com/gunthercox/ChatterBot/wiki/Chat-Forms) inside the wiki page, which is perfectly suit my requirement, may I know the feature is under development or completed?

**Comment by gunthercox** [comment]
@nggary Chat Forms are just a feature idea that I recorded a while ago. The functionality you are looking for is a common request that I've had from different developers. I'd love to add it in the future but right now it is something that isn't even on the development roadmap.

**Comment by nggary** [comment]
Thanks for the answer!
