### ISSUE TITLE
ModuleNotFoundError: No module named 'dateutil' on python 3.6

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#858]
I've execute the command "pip install --upgrade chatterbot" already.

When I try to execute the sample code from https://chatterbot.readthedocs.io/en/stable/training.html#

``` Python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatterbot = ChatBot("Training Example")
chatterbot.set_trainer(ListTrainer)

chatterbot.train([
    "Hi there!",
    "Hello"
])

chatterbot.train([
    "Greetings!",
    "Hello"
])
```
Error message:

``` BASH
"D:\Program Files\Python\Python36-32\python.exe" D:/Files/PycharmProjects/untitled/trainer.py
Traceback (most recent call last):
  File "D:/Files/PycharmProjects/untitled/trainer.py", line 10, in <module>
    "Hello"
  File "D:\Program Files\Python\Python36-32\lib\site-packages\chatterbot\trainers.py", line 87, in train
    Response(previous_statement_text)
  File "D:\Program Files\Python\Python36-32\lib\site-packages\chatterbot\conversation\response.py", line 8, in __init__
    import dateutil.parser as date_parser
ModuleNotFoundError: No module named 'dateutil'
```
Process finished with exit code 1

The same code works fine before I updated the chatterbot, but fail after I updated it.

**Comment by vkosuri** [comment]
@nggary we haven't added ``python 3.6`` to travis. I think we have to add those @gunthercox Master any comments adding python 3.6 to travis?

@nggary May be i think dateutil package won't come with python3.6, could you please try to install dateutil using pip ``pip install python-dateutil``

**Comment by gunthercox** [comment]
@nggary It appears I was overzealous in my eagerness to embrace the ["release early, release often"](https://en.wikipedia.org/wiki/Release_early,_release_often) philosophy of the [Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar). My apologies. I will push up a fix shortly that adds `python-dateutil` to the project requirements.

**Comment by nggary** [comment]
No worries, take your time.
