### ISSUE TITLE
0.3.0 cannot be installed via pip

### ISSUE THREAD

**Issue by nielsole** [gunthercox/ChatterBot#86]
`raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'requests ~=2.8.0,<3.0.0', 'at', ' ~=2.8.0,<3.0.0')`

I am using Python 2.7
0.2.9 installs just fine

https://github.com/gunthercox/ChatterBot/commit/750721d75afe4e403e773cb4ce68ca4a6c3e4054 seems to contain the malicious change

`~=` syntax does not seem to be valid syntax!? (https://pip.readthedocs.org/en/1.1/requirements.html)

**Comment by gunthercox** [comment]
Thank you, I have removed the requirements for requests and requests-oauthlib because these are not actually used anywhere in the project anymore.

I will be releasing version 0.3.1 later tonight because there was additional errors in the 0.3.0 release.

**Comment by gunthercox** [comment]
Version 0.3.1 has been released to pypi.
