### ISSUE TITLE
Will removing the unique index from the Mongo DB adapter improve performance?

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#865]
This is something I'm interested in looking into. Possibly, this would remove the overhead of the database having to rebuild the index each time a statement is added (some research on this is still required).

```python
self.statements.create_index('text', unique=True)
```

**Comment by vkosuri** [comment]
Some references https://docs.mongodb.com/manual/tutorial/optimize-query-performance-with-indexes-and-projections/

**Comment by gunthercox** [comment]
Removed as a part of #1391
