### ISSUE TITLE
Training didn't auto generated the database.db

### ISSUE THREAD

**Issue by nggary** [gunthercox/ChatterBot#868]
I used to execute the following code to train my chatbot and the database.db will be auto generated, but It doesn't happen in this version.

``` Python
from chatterbot.trainers import ListTrainer

chatterbot = ChatBot("Training Example")
chatterbot.set_trainer(ListTrainer)

chatterbot.train([
    "Hi there!",
    "Hello",
])

chatterbot.train([
    "Greetings!",
    "Hello",
])
```

**Comment by vkosuri** [comment]
@nggary Chatterbot default storage adapter is ``SQLStorageAdapter``. 

It uses database_uri to connect your database, more information available [here](http://chatterbot.readthedocs.io/en/stable/storage/index.html#sql-alchemy-storage-adapter). 

If you want to know table properties use [find(statement_text)](http://chatterbot.readthedocs.io/en/stable/storage/index.html#chatterbot.storage.SQLStorageAdapter.find) procedure to check your statements are there or not

**Comment by nggary** [comment]
I don't know it is a bug or on purpose on the document modification. There should be something writen about the JsonFileStorageAdapter, but now its gone, and that is what I'm looking for.
