### ISSUE TITLE
speed sqlite 

### ISSUE THREAD

**Issue by semen7907** [gunthercox/ChatterBot#873]
I need to speed up sqlite with 
PRAGMA journal_mode = OFF;
PRAGMA synchronous = OFF; , Where should this be added?

**Comment by gunthercox** [comment]
Internally, ChatterBot uses SQLAlchemy to connect to sqlite databases. It looks like I might have to make some changes to the setup of the SQL Storage adapter so that additional parameters can be specified. I'll look into this and get back to you as soon as possible.

**Comment by lesleslie** [comment]
Try the following (lines 119 to 134) of sql_storage.py:

        self.engine = create_engine(self.database_uri)

        from re import search

        if search('^sqlite://', self.database_uri):
            from sqlalchemy.engine import Engine
            from sqlalchemy import event

            @event.listens_for(Engine, "connect")
            def set_sqlite_pragma(dbapi_connection, connection_record):
                dbapi_connection.execute('PRAGMA journal_mode=WAL')
                dbapi_connection.execute('PRAGMA synchronous=NORMAL')

        self.read_only = self.kwargs.get(
            "read_only", False
        )

I am not the expert on this at all by any means, but from what I found googling turning journal_mode all the way off doesn't give you much, if any, of a substantial speed increase, over turning it to WAL, but dramatically increases your chance of db corruption (at least with *nix, it may be worth doing on Windows).

**Comment by gunthercox** [comment]
Closed by #914 ✔️
