### ISSUE TITLE
Import large list of training data

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#882]
Hi,
I'm new on Django but I got the Chatterbot installed successfully in my own Django installation.
I have also successfully imported the Exampel App you guys have wroted so I can talk though the API.

But now do I have a large list of training data that I want to import to the Database.
How is the easiest way to import that?

I have a text file in the same format as following documentation shows me.
https://chatterbot.readthedocs.io/en/stable/training.html#training-via-list-data
But I don't understand how I can import that list to the Django Chatterbot app?

Thanks for advice
Christian

**Comment by gunthercox** [comment]
There is an additional setting for this that can be used in Django's settings for ChatterBot.

http://chatterbot.readthedocs.io/en/latest/django/training.html#training-settings

The content of the `training_data` can be different, depending on the training class that you are using. I've been meaning to add more documentation to the section on using ChatterBot with Django so I apologize about the lack of guidance.

**Comment by Issen007** [comment]
gunthercox, no problem. I more then happy to help out here if you want to.
I'm more then open to take a quick chat so I can help with documentation for you. 

Because I can probably help you out to create a corpus version in Swedish for you and we probably also want to create a German for you. 
And from here I can probably also with your guidelines get all the steps documentation so more people can create or expand the once we have.

**Comment by gunthercox** [comment]
@Issen007 Thank you, that would be greatly appreciated.

**Comment by Issen007** [comment]
Let's try to catch up over Hangout or similar to do a quick chat and see what I can help you with.

**Comment by Issen007** [comment]
This has now been documented at chatterbot-corpus website "[Chatterbot-Corpus](https://github.com/gunthercox/chatterbot-corpus/)"
