### ISSUE TITLE
Create large responds text

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#885]
Hi,
Continue my testing of the chatterbot and I'm really glad what you guys have done.

Maybe I can fix this on my own by going though the code. But the responds text length is to small for me some times. 

As an example if a end-user has a error code in their text let's say following statement comes up such.

> **User:** I have a issue and the error code is ANR04444W
> **Chatterbot:** Sorry to hear that you got that error.
> Explanation:
> The server detects a protocol error on the specified session because a
> verb has been received that does not adhere to the client-server
> exchange sequence.
>
> System action:
>
>The server ends the client session.
>
>User response:
>
>If the client generating the error is not an API client, contact your
>service representative. If the client generating the error is an API
>client, contact the owner of the API client. If the client generating
>the error is a client that you have created using WDSF verbs, correct
> the programming error in your client program. 

I got 2 issues with the responds, the first is that I got empty lines and the second problem is that the text is to large for the fields that are set in the Django Admin.

**Comment by AxelAli** [comment]
how about you replace newline with a custom character and then store it, when you get it back, replace it.
Ex.
```
reponse = """ we are very sorry, here is the explanation 
The server detects a protocol error on the specified session because a
verb has been received that does not adhere to the client-server
exchange sequence."""

response.replace("\n","^^^") # \n = newline(or a enter if you will) ^^^=newline
#send to django
#when you get it back

#print response.replace("^^^","\n") 
```

**Comment by gunthercox** [comment]
Changes have been made so that it is now possible to create custom statement models and tell the chat bot to use them. This functionality isn't yet documented but I've created a ticket for adding the documentation #1097.
