### ISSUE TITLE
Question:  will ChatterBot support Form type conversation

### ISSUE THREAD

**Issue by praveenrengarajan** [gunthercox/ChatterBot#886]
After Its come to custom adapter, chat should hold the state and continue until the form data filled.
Example, If I have 5 fields in a form : have to do validate and should get input from user. Like iDialog Form in Microsoft Bot Framework

**Comment by gunthercox** [comment]
In the future, this is a feature that might possibly be added. I have notes about a possible design in the project wiki. Right now my focus is on improving the performance and accuracy of the chat bot's responses so this feature likely won't be added any time in the near future.

**Comment by vkosuri** [comment]
Wiki link https://github.com/gunthercox/ChatterBot/wiki/Chat-Forms

**Comment by VanRH** [comment]
This would be really useful. Being able to keep context and track what's required in a "form" would be great.

**Comment by vkosuri** [comment]
@gunthercox Master, I would like work on this feature, could you please guide how to do and where to do

**Comment by gunthercox** [comment]
@vkosuri I'll put together a ticket for it with more details.

**Comment by gunthercox** [comment]
@VanRH Nope, I will be sure to design it so that it can work independently from the environment where the chat bot is being hosted. It is the bot that will be filling in the fields for the form anyway.
