### ISSUE TITLE
Speech IO adapter

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#89]
It would be a great addition to have an IO adapter for speech-to-text and text-to-speech. This would allow people to use ChatterBot in more situations and with less work.

- [ ] STT Adapter
- [ ] TTS Adapter

This is a pretty complicated addition, but the Jasper project does a great job implementing STT and TTS functionality. Some information about their user interaction ( how it can be configured ) can be found here http://jasperproject.github.io/documentation/configuration. The code for the STT and TTS engine(s) they implement can be found here https://github.com/jasperproject/jasper-client/blob/master/client/stt.py and https://github.com/jasperproject/jasper-client/blob/master/client/tts.py.

The implementation would be done in steps, with single-engine configuration coming first followed by multi-engine configuration.

- [ ] Single-engine configuration. In this, we would only allow the use of a single STT & TTS engine that we hard code into ChatterBot
- [ ] Multi-engine configuration. In this, we would allow multiple STT & TTS engines that the user can pick.

**Comment by gunthercox** [comment]
Text to speed and speech synthesis would be an awesome addition.

**Comment by mcolonj** [comment]
I work on a mac and have been using pyobjc to hook into the AppKit NSSpeechSynthesizer to listen to the output. I have also worked on many other STT and TTS applications (iOS and mac). Writing and enhancement for Chatterbot is on my todo list. How do you propose to add STT and TTS adapters to ChatterBot?

**Comment by DarkmatterVale** [comment]
I currently do not have an implementation plan. I would like to do something similar to what the Jasper project does, but recently I have not had time to really explore how their code works. It is also a pure python implementation.

**Comment by gunthercox** [comment]
Closing this ticket off as work on this component of chatterbot will be continuing at https://github.com/gunthercox/chatterbot-voice
