### ISSUE TITLE
Large amount of data, slow inquiry

### ISSUE THREAD

**Issue by yeshoujquery** [gunthercox/ChatterBot#897]
The current version is updated to.75, but it still doesn't solve the big data problem
Only 373754 took 164 seconds
![qq 20170801182431](https://user-images.githubusercontent.com/10823306/28821183-134c3bdc-76e7-11e7-90ce-d9d400f6a5e6.png)

Recommend the following robot
![fc2305d9cbdc0f86db2b46e2a5835fa8](https://user-images.githubusercontent.com/10823306/28821252-50a45e56-76e7-11e7-9f67-268791a36369.png)
WeChat applet

**Comment by gunthercox** [comment]
@yeshoujquery Yes, that is correct. Version 0.7.5 doesn't contain any performance improving features and none were planned for this version.

I assure you that I am aware of the performance issues and they will be greatly improved through future releases.

For reference, you can review the details for the changes in each release in ChatterBot's release notes section: https://github.com/gunthercox/ChatterBot/releases

**Comment by yeshoujquery** [comment]
@gunthercox  OK, which version of the performance problem is likely to be solved?

**Comment by gunthercox** [comment]
@yeshoujquery Hopefully within the releases for either 0.8 or 0.9.

**Comment by yeshoujquery** [comment]
@gunthercox  Quietly waiting, hope can be realized

**Comment by chasingML** [comment]
@yeshoujquery hi,bro, have u solved the problem of efficiency?

**Comment by yeshoujquery** [comment]
@chasingML The project has been abandoned

**Comment by chasingML** [comment]
@yeshoujquery hi. u used 373753 data with mongodb time-consuming 89ms? right? I want to know how to make it ? I used 7w data with mongodb time-consuming 41s for response, it's really too slow? I do not clear what's wrong with my codes? tks a lot!!!

**Comment by zxsimple** [comment]
@chasingML , you probably hasn't install python-Levenshtein， please check whether [https://github.com/gunthercox/ChatterBot/pull/1158](https://github.com/gunthercox/ChatterBot/pull/1158) is helpful or not
