### ISSUE TITLE
Effective training of chatter bot

### ISSUE THREAD

**Issue by Hemanth2396** [gunthercox/ChatterBot#898]
hello all ,

     how can we train the chatterbot effectively to achieve the good response from bot.
can you give suggestions to improve the quality of response from chatbot.

**Comment by vkosuri** [comment]
> how can we train the chatterbot effectively to achieve the good response from bot.

A high amount of confidence. will give accurate response from bot. To set threshold like this

``` Python
bot = ChatBot(
    'Default Response Example Bot',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.90,
            'default_response': 'I am sorry, but I do not understand.'
        }
    ],
    trainer='chatterbot.trainers.ListTrainer'
)
```

**Comment by Hemanth2396** [comment]
thanks for the reply .
 
    Actually i want to know about  HOW TO TRAIN a basic chatbot with more amount of data.

**Comment by 7633** [comment]
@Hemanth2396, you should just create a dataset (dialogue corpus) and format it to one of the using [formats to training](http://chatterbot.readthedocs.io/en/stable/training.html). 
There are list of state-of-the-art corpuses for training chatbots: [](https://github.com/Marsan-Ma/chat_corpus)

**Comment by anilneeluri** [comment]
@7633 Can you give a detailed explanation about this, If you have tried and succeeded in doing this?

**Comment by vkosuri** [comment]
> Actually i want to know about  HOW TO TRAIN a basic chatbot with more amount of data. 

@Hemanth2396 and @anilneeluri 

For large amount of data, it is recommended to write your corpus file. I think the below Q&A will answer your questions.

1. How to write a corpus file?
2. What is training and what are different training class are available?

### 1. How to write a corpus file?
Chatterbot does support both [YAML ](https://en.wikipedia.org/wiki/YAML) and JSON format in question and answers. You could find a large number of corpus files here https://github.com/gunthercox/chatterbot-corpus/tree/master/chatterbot_corpus/data.

Example

```YAML
- - text: Hello, how are you doing today?
  - text: I am doing well, thank you.
- - text: I cannot find my keys.
  - text: Where was the last place you remember having them?
```

### 2. What is training and what are different training class are available?
Training is the process involves loading example dialog into the chat bot’s database. Chatterbot does support different [training classes](http://chatterbot.readthedocs.io/en/stable/training.html#training-classes) to train your bot.

**Comment by anilneeluri** [comment]
So this is not an easy thing to complete. We don't usually get the data set in the yaml format i.e the question and answer format and practically is it possible to get the large amount of data in that format.

**Comment by vkosuri** [comment]
You could write your own training class for example UbuntuDialogCorpus and Twitter Training classes take a look exists training classes https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/trainers.py

**Comment by isaam14** [comment]
I tried writing this on the json file:

{"categories":"test_json", 
"conversations": {"- - text": "Hello, how are you doing today?",
"  - text": "I am doing well, thank you.",
"- - text": "I cannot find my keys.",
"  - text": "Where was the last place you remember having them?"}}

It doesn't send an error on the console but the chatbot doesn't know the answers when say hello or when I ask her about the keys.

**Comment by kashyaparjun** [comment]
Try this:

`
{
    "conversations": [
          [
                "Hello, how are you doing today",
                "I am doing well, thank you"
          ],
         [
                "I cannot find my keys",
                "Where was the last place you remember having them?"
         ]
    ]
}
`

This should be the proper JSON structure for training
