### ISSUE TITLE
Additional Plugins

### ISSUE THREAD

**Issue by DarkmatterVale** [gunthercox/ChatterBot#90]
In addition to evaluate_mathematically, there are many other plugins that would be really nice to have. @gunthercox Do you have a preference for the type of plugins you would like ChatterBot to have? For example, are you alright with having plugins for time?

If so, here is a list of plugins that I would like to implement ( over some long period of time ;) ):
- [x] Time = Get the time ( current, future, past )
- [x] Weather = Location ( current, or user specified )
- [ ] Reminders = User created events that are executed at a user-specified time
- [ ] Email = Send and receive emails
- [ ] Music = Start, stop, or pause music
- [ ] News = Get news headlines ( this can be very difficult because of NLP, but we can start simple and get more complex over time )

What do you think? Do you have any that you would like to add to the list?

Update 1/28/16: Additional Plugins
- [ ] Web search
- [ ] Wikipedia search

**Comment by gunthercox** [comment]
These all sound great. I can't think of any additions at the moment, but I will make a comment if I do.

**Comment by LucasZielke** [comment]
Instead of having to manually tell the program that it has to run these input, would it not be a little easier to have like a form of inline python parsing?

**Comment by DarkmatterVale** [comment]
Can you please elaborate on the implementation of such a system?

**Comment by DarkmatterVale** [comment]
@LucasZielke See #94 for a great way to train the bot to certain inputs ( and results ). I will work on providing details as soon as I can get some time to work on this.

**Comment by LucasZielke** [comment]
Might i suggest like a micro dictionary function in there like:
input: Do you know what the word _____ means?
Output: Yeah, that means _________

**Comment by DarkmatterVale** [comment]
That is similar to the "find_a_name()" function, just a broader dictionary. I think the function you are describing should become an evolved version of the find_a_name() function.

@gunthercox Sorry for being gone for so long! I am still at the beginning of GCI ( which will last through January ), and am having a lot of trouble finding time for everything. I will try and get some stuff done, but timing might be a little bit of a range.

**Comment by gunthercox** [comment]
@DarkmatterVale Not a problem, these next few weeks will likely be very busy for me as well. Good luck with your coding!

**Comment by DarkmatterVale** [comment]
Another great plugin that we could implement is a Developer Assistant. This is a little more complex, but is something that a lot of people could use. In addition, this is a very modular plugin, allowing us to start very simple and expand greatly to add functionality over time.

**Comment by gunthercox** [comment]
I'm closing this off as some of these adapters go beyond the scope of chatbot communication. It would be great to see them created as third party python packages that could be imported by the main ChatterBot module.
