### ISSUE TITLE
Session Management using inbuilt modules  

### ISSUE THREAD

**Issue by vyz1194** [gunthercox/ChatterBot#900]
I have  modified the response selector by adding a variable to keep track of the context 
but when I tried it out with multiple users, I see the context get overwritten by the last incoming message from any user

So thinking of writing the context with the session id into the mongo

Can anybody guide me on how I can use  inbuilt session module to enable this functionality 
or if there any better approach please do suggest 

Any help is welcome :)
Thanks in advance !

**Comment by gunthercox** [comment]
Hi @vyz1194, If by "inbuilt session module" you mean the one included in ChatterBot, I would recommend against using it. I've made changes to remove ChatterBot's session management system in the next version in favor of storing a history of individual conversations in the database. I think this might be closer to what you are looking for.

**Comment by vyz1194** [comment]
Thanks for the Reply @gunthercox 

Can please tell me which all modules will/have change with your update ?

*very sorry for responding this late*

**Comment by vkosuri** [comment]
Reference pull request https://github.com/gunthercox/ChatterBot/pull/828
