### ISSUE TITLE
Possible issue with RepetitiveResponseFilter class when getting responses

### ISSUE THREAD

**Issue by bainadeashish** [gunthercox/ChatterBot#901]
Hi Team,

Initially i was using JsonFileStorageAdapter it was giving correct responses but it was slow.Hence I moved to MongoDatabaseAdapter.It is giving quick responses but inaccurate.:(

Code is :+1: 
``` Python
bot = ChatBot(
    'IVLI',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    database='chatterbot-database',
	logic_adapters=[
		{
            'import_path': 'chatterbot.logic.BestMatch',
			"response_selection_method": "chatterbot.response_selection.get_random_response"
		
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.60,
            'default_response': 'I am sorry, but I do not understand.'
        },

    ],
    preprocessors=['chatterbot.preprocessors.clean_whitespace','chatterbot.preprocessors.unescape_html','chatterbot.preprocessors.convert_to_ascii'],
    silence_performance_warning=True,
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
    filters=["chatterbot.filters.RepetitiveResponseFilter"]
)
bot.train("chatterbot.corpus.english.greetings")
bot.read_only=True
```

Below is sample log for MongoDatabaseAdapter:

START OF MESSAGE
```
DEBUG:root:Original messaage was : hello
DEBUG:root:Complete message was : hello
DEBUG:root:Corrected message was : hello
INFO:chatterbot.adapters:Recieved input statement: hello
INFO:chatterbot.adapters:"hello" is not a known statement
INFO:chatterbot.adapters:Using "hello" as a close match to "Hello"
INFO:chatterbot.adapters:Selecting response from 1 optimal responses.
INFO:chatterbot.response_selection:Selecting a response from list of 1 options.
INFO:chatterbot.adapters:Response selected. Using "Hi"
INFO:chatterbot.adapters:BestMatch selected "Hi" as a response with a confidence of 1.0
INFO:chatterbot.adapters:LowConfidenceAdapter selected "I am sorry, but I do not understand." as a response with a confidence of 0
INFO:chatterbot.adapters:NoKnowledgeAdapter selected "hello" as a response with a confidence of 0
INFO:chatterbot.chatterbot:Adding "hello" as a response to "Greetings!"
DEBUG:root:Response for message was : Hi
DEBUG:root:
```
START OF MESSAGE
```
DEBUG:root:Original messaage was : hello
DEBUG:root:Complete message was : hello
DEBUG:root:Corrected message was : hello
INFO:chatterbot.adapters:Recieved input statement: hello
INFO:chatterbot.adapters:"hello" is not a known statement
INFO:chatterbot.adapters:Using "hello" as a close match to "Hello"
INFO:chatterbot.adapters:No response to "Hello" found. Selecting a random response.
INFO:chatterbot.adapters:BestMatch selected "I'm doing well." as a response with a confidence of 0
INFO:chatterbot.adapters:LowConfidenceAdapter selected "I am sorry, but I do not understand." as a response with a confidence of 0
INFO:chatterbot.adapters:NoKnowledgeAdapter selected "hello" as a response with a confidence of 0
INFO:chatterbot.chatterbot:Adding "hello" as a response to "Hi"
**DEBUG:root:Response for message was : I'm doing well.** ---WRONG RESPONSE
DEBUG:root:
```

What should I do to avoid such false responses?

**Comment by vkosuri** [comment]
@bainadeashish Chatterbot does support multiple response selection methods, from your example, you have choose [random response method](http://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#chatterbot.response_selection.get_random_response), and threshold values as ``0.6``. 

For example In your case and based on your inputs the fallowing statements will fall under threshold value as ``0.6`` among all those values a random response will pick by chatterbot.


Confidence | Statement
-- | --
0.8 | hello
0.7 | how are you
0.6 | doing great!


Here more documentation on multiple [response selection modes ](http://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#module-chatterbot.response_selection)

**Comment by bainadeashish** [comment]
Hi @vkosuri ,I dont think its because of random response method.
From the log i have shared earlier,
INFO:chatterbot.adapters:Selecting response from 1 optimal responses.
when i gave hello as input ,it tries to select from 1 optimal response .

But second time i have given hello as input,log says
INFO:chatterbot.adapters:No response to "Hello" found. Selecting a random response.
Here it is not able to find any optimal response.  i think this is problem & it then it is giving a random response.

**Comment by vkosuri** [comment]
@bainadeashish I think it is slightly confusing, the documentation needs to corrected here, Based on ``closet_match`` the optimal values are selected. Here are the steps the bot is performing. The information started from this [steps ](https://github.com/gunthercox/ChatterBot/blob/351971a21e603642f5797c33e924c4195f96682b/chatterbot/logic/best_match.py#L55)

1. Select the closest match to the input statement
2. Get all statements that are in response to the closest match
3. Selecting optimal responses
4. Response selection

I am not sure did i answer question, let me know what are your inputs/thoughts/suggestions/comments?

**Comment by bainadeashish** [comment]
@vkosuri yesterday i debug the code & found that it is working weird for mongodb storage adapter.
It is removing optimal response at each iteration by 1.

For Hello i was having 3 response Hi,Greetings,Hey.
for the 1st hello input ,it gave me below:
INFO:chatterbot.adapters:Selecting response from 3 optimal responses.
For 2 nd hello input
INFO:chatterbot.adapters:Selecting response from 2 optimal responses.
for 3 rd hello input
INFO:chatterbot.adapters:Selecting response from 1 optimal responses.

for 4 th hello input 
INFO:chatterbot.adapters:No response to "Hello" found. Selecting a random response.

**Comment by bainadeashish** [comment]
@vkosuri  which version of chatterbot works fine with mongodb storage adapter?
so that I can  use previous versions of chatterbot till the time any of us fix this bug.

**Comment by bainadeashish** [comment]
@vkosuri tag 0.5.4 working fine with mongodb storage adaptor ,post 0.5.5 to latest version which is 0.7.5 there is bug for mongodb storage adaptor.
Hope this helps for resolving bug.
We need to check what went wrong from 0.5.4 to 0.5.5.

**Comment by RanjithNair1980** [comment]
I think the issue is with filters=["chatterbot.filters.RepetitiveResponseFilter"]. This is used to avoid repetitive response and can cause the above issue. I faced similar issues and after removing this filter and using random response, I did not face this issue.
