### ISSUE TITLE
Check which logic adapters are english-dependent

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#905]
I believe a few of ChatterBot's logic adapters that use NLTK have english-specific restrictions. The logic adapter for telling the current time is an example of this.

An plan should be developed for supporting other languages in these adapters. I'm not yet sure what the best approach will be. One possibility I am considering is adding that data to the ChatterBot corpus and implementing a warning in the logic adapter if it can't load the required data for that language.

**Comment by vkosuri** [comment]
Some of the resources i have found https://hugonlp.wordpress.com/2015/10/07/how-to-do-pos-tagging-and-lemmatization-in-languages-other-than-english/

**Comment by gunthercox** [comment]
Closing this off, the time-logic adapter now allows custom data to be passed in and the mathematical evaluation adapter now has [mathparse](https://github.com/gunthercox/mathparse) backing it which supports a growing number of languages.
