### ISSUE TITLE
too slow if training custom corps 

### ISSUE THREAD

**Issue by aliray** [gunthercox/ChatterBot#908]
i have corps with 6000000 lines data , and i try to train the corps but it's too slow ,is there any ways to improve the performance in ChatterBot ?

**Comment by gunthercox** [comment]
Right now, no. Luckily training only has to be done once for a chat bot. You may encounter further issues once you finish training with that much data. I'm currently working on changes to solve performance issues for large data sets.

**Comment by neutralboy** [comment]
@aliray , if you don't mind can you please state where you acquired the data from?

**Comment by laonan** [comment]
Corps with 900000 lines data, use mongodb, super slow.

**Comment by chasingML** [comment]
@laonan hello, have u solved the problem of efficiency. I meet the same problem

**Comment by laonan** [comment]
not yet, if u have any good news, would pls let me know? thx.

**Comment by chasingML** [comment]
@laonan I have read the doc and asked the author. There is no good approach to efficiency and the author is working on it. The later version will get some changes and I may do some preprocessing before training to improve retrieve speed of response

**Comment by calmzealA** [comment]
Corps with 10000 lines data, use mongodb, 
trainning once is acceptable.
But getresponse more than 2 second.

BestMatch get all 10000 lines and compute confidence each

**Comment by gunthercox** [comment]
I'm going to close this ticket off because as far as I can see there isn't any actionable items that can be done for it. For details on the planned performance improvements, please refer to #925.

**Comment by zxsimple** [comment]
@calmzealA has you installed python-Levenshtein?
