### ISSUE TITLE
unable to train with Twittertrainer

### ISSUE THREAD

**Issue by anilneeluri** [gunthercox/ChatterBot#909]
I have trying to train with the twitter trainer because of the following error

   twitter.error.TwitterError: [{'code': 89, 'message': 'Invalid or expired token.'}]

how can I solve this problem?

**Comment by vkosuri** [comment]
@anilneeluri I think this something is related to twitter API token broken issue, I have found a similar question comment which will guide to resolve your problem https://stackoverflow.com/a/17994472/358458

**Comment by anilneeluri** [comment]
@vkosuri Thanks. Solved it.
