### ISSUE TITLE
How to train chatterbot with emoticons?

### ISSUE THREAD

**Issue by bainadeashish** [gunthercox/ChatterBot#911]
Can we train chatterbot with smiley as input or response?
I tried using python library emojione with chatterbot but it didn't help.
anyone succeeded in doing this, your help is appreciated.

**Comment by gunthercox** [comment]
@bainadeashish I _believe_ this should work. I'd be more than happy to look into it and add some tests to confirm that it works. There might even be some interesting potential here to add a data set containing emoticons to the [chatterbot corpus](https://github.com/gunthercox/chatterbot-corpus)

**Comment by bainadeashish** [comment]
@gunthercox  thank you.
if your attempt succeeds i will add corpus for emoticons.

**Comment by bainadeashish** [comment]
Hi @gunthercox ,i have update on this.
We can use emojipy --Python library for working with emojione.
There are shortcodes associated with each emoticon.
smiling face ---> shortcode is    :grinning:
Hence we can train chatbot as 
Input :grinning:  response "You seems to be happy today"
Hence,the task is first convert smiley image into short code.
Hope I have written in a way you should understand it.

**Comment by vkosuri** [comment]
@bainadeashish happy to hear from you,Full emoji list  http://www.unicode.org/emoji/charts/full-emoji-list.html

**Comment by gunthercox** [comment]
@bainadeashish Thank you for that note, I'll take that into consideration. A preprocessor would probably be the most optimal way to accomplish the conversion you mentioned http://chatterbot.readthedocs.io/en/stable/preprocessors.html
