### ISSUE TITLE
Shouldn't it be dump (without s) ?

### ISSUE THREAD

**Issue by pgrandinetti** [gunthercox/ChatterBot#912]
https://github.com/gunthercox/ChatterBot/blob/68527223db52c39cbb94393cdf313f39485c5856/chatterbot/trainers.py#L67

**Comment by gunthercox** [comment]
Yes, it should.

**Comment by pgrandinetti** [comment]
cool, I didn't feel like doing a pull request for exactly one character.
Thanks for the nice bot ;)
