### ISSUE TITLE
Facebook chatbot using Chatterbot

### ISSUE THREAD

**Issue by hochochoc** [gunthercox/ChatterBot#917]

**Comment by hochochoc** [comment]
I want to do a Facebook chatbot using Chatterbot, but I  don't know whether I have to create a new input adapter or not. Can you give me a guess?  Thank you so much

**Comment by vkosuri** [comment]
@hochochoc 

> but I don't know whether I have to create a new input adapter or not.

Yes

Please be aware of future expansion https://github.com/gunthercox/ChatterBot/issues/528

I found some resources this might be useful to you http://masnun.com/2016/05/22/building-a-facebook-messenger-bot-with-python.html

**Comment by hochochoc** [comment]
I have just made a simple chatbot using Fb and chatterbot, but I didn't create a new input adapter. 
I only followed this project https://github.com/chamkank/flask-chatterbot . However, I think, in future, I will create a Facebook adapter for chatterbot. This maybe interesting. 
Thank you very much.

**Comment by vkosuri** [comment]
@hochochoc Sure

**Comment by shawnhill121** [comment]
@vkosuri @hochochoc This information was extremely helpful! Thank you both!
