### ISSUE TITLE
NLTK find looks for the wrong thing in closes meaning logic adapter

### ISSUE THREAD

**Issue by gdunstone** [gunthercox/ChatterBot#92]
Changing to this in `__init__.py` fixes the issue:
missing was corpora and tokenizers in find calls.
```
try:
    find('corpora/wordnet')
except LookupError:
    download('wordnet')

try:
    find('corpora/stopwords')
except LookupError:
    download('stopwords')

try:
    find('tokenizers/punkt')
except LookupError:
    download('punkt')

```

**Comment by gunthercox** [comment]
Currently there is some very similar code in https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/adapters/logic/closest_meaning.py#L18

I will check this out, wondering if it might be an NLTK version related issue.

**Comment by gunthercox** [comment]
I am going to close this one off for now. I have not been able to replicate it.
