### ISSUE TITLE
How to unable Enable bing spell checker in Luis?

### ISSUE THREAD

**Issue by dileepkantapop** [gunthercox/ChatterBot#922]
Hi Folks,

I am facing the issue with the spell checker option in LUIS, As i am checked it and published. When i see again its showing as unchecked. I had purchased Bing spell check key too. 

Please help me with this...

Thank you...!!

**Comment by gunthercox** [comment]
Hi @dileepkantapop, I'm not sure what Luis is. I would be happy to try to help. Do you have a link to project you are working with?

**Comment by vkosuri** [comment]
Luis is an Microsoft AI https://www.luis.ai/home

@dileepkantapop I think this thread will help you https://github.com/Microsoft/Cognitive-LUIS-Windows/issues/18#issuecomment-289385413

**Comment by yescay** [comment]
Hi @dileepkantapop , If you are referring to this screenshot, then the state of selection is not saved. It does not persists the selection.
![screen shot 2017-08-11 at 4 53 36 pm](https://user-images.githubusercontent.com/4955155/29211258-a9cf465a-7eb5-11e7-84ee-43e6e4b141fd.png)

However, the following are the steps, 

1.  Get a bing spell check API key
2. Add it in external Association 
3. Publish it with Bing spell check API on
4. Every time the invocation is done from your code - have "spellCheck=true" is set.

https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/c003afeb-e2b1-4890-a780-63a31812c735?subscription-key=8fb772cfd44c492a98280b53edb40c61&verbose=true&timezoneOffset=0&spellCheck=true&q=

**Comment by dileepkantapop** [comment]
buddy @yescay i am using the LUIS in Bot framework C# i can't call API to get the result. I know that it has "spellCheck=true" in API. But my problem is different! The state of the checkbox is not saving.

**Comment by yescay** [comment]
The state of the check box does not matter – the parameter value is what matters. Explore the Request object of your C# code to see if you can set the bing spellcheck that you can set to “true”.

 

AFAIK This checkox in LUIS publish page – does not retain state. 

 

Thanks

Kamesh

**Comment by dileepkantapop** [comment]
Buddy! In Bot framework we won't call API, we just have Intents in which we will get data in entities.
