### ISSUE TITLE
Update installation instruction to use virtualenv

### ISSUE THREAD

**Issue by lesleslie** [gunthercox/ChatterBot#928]
I recommended updating the installation instructions to install chatterbot into a virtualenv.

I would be more than happy to do this if everyone agrees.

**Comment by vkosuri** [comment]
I don't see any issues with python virtualenv. Many users/developers facing issues while installation chatterbot on ``anacoda`` installation instructions.

I am ok, if you are going add both ``python`` and ``anaconda``. 

And also a similar issue https://github.com/gunthercox/ChatterBot/issues/781, if you want you could start work on this issue also.

**Comment by lesleslie** [comment]
i don't have any experience with anaconda.  look it's interesting.  i'll give it a try and see what i can do.

**Comment by gunthercox** [comment]
I decided to take a look at the Django documentation as a roll model for what the best documentation practice would be for adding a note about virtualenv.

From what I found, it looks like the Django docs mention it in two main places:

1. As a recommended step in the development workflow (https://docs.djangoproject.com/en/1.11/intro/contributing/#getting-a-copy-of-django-s-development-version)
2. For installation on Windows (https://docs.djangoproject.com/en/1.11/howto/windows/)

I really like the idea of adding a recommendation in the [development documentation](http://chatterbot.readthedocs.io/en/stable/development.html). I think **if** a step is added to the installation instructions we just need to make is very clear that it is optional.

**Comment by lesleslie** [comment]
ok.  i have virtualenv instructions that i use for my own projects i can reference too.  i can make the instructions optional too.  i personally feel though that installing chatterbox using a virtualenv, by default, is a much better practice - especially for development so i'll definitely add them there.

**Comment by gunthercox** [comment]
Agreed. Thank you!
