### ISSUE TITLE
NLTK SSL Errors loading...

### ISSUE THREAD

**Issue by sedemmler** [gunthercox/ChatterBot#930]
I didn't see this directly addressed earlier, but please correct me if I missed it.

I'm receiving these NLTK related errors when running ChatBot (but no issues when I'm coding up NLTK separately on another project.

Any guidance would be wonderful. Thanks guys.

```
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:749)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:749)>
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:749)>
[nltk_data] Error loading vader_lexicon: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:749)>
```

**Comment by vkosuri** [comment]
@sedemmler I googled your issue found some answer, i think this could help solve your problem

https://stackoverflow.com/a/41692664/358458
https://stackoverflow.com/a/39142816/358458

However the post suggested disable ssl error explicitly, i am not sure how this will effect

``` Python
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()
```

**Comment by sedemmler** [comment]
I appreciate you taking a look. Let me give your suggestion ago tomorrow and I'll let you know how it goes. Thanks!

**Comment by gunthercox** [comment]
I'm going to close this ticket off because it hasn't been reported again. I'm assuming it could have possibly been a temporary error on the side of the servers hosting NLTK's data.

**Comment by QUDUSKUNLE** [comment]
@vkosuri Thanks a lot.
