### ISSUE TITLE
Use multiple databases

### ISSUE THREAD

**Issue by Issen007** [gunthercox/ChatterBot#931]
As suggested, I open a new request for this.
But it should be really nice to be able to have multiple databases connections to a single chatterbot.
And in the chatterbot configuration area you should be able to tell it if you only should have Reaad-Only mode or read-write mode.

In this case you can then have a larger master databases where multiple chatterbots can be connected to, to be able to have a larger standard data.
And a local attach database that has local knowledge such names of people, hardware and data that is only internal use and no use for any other people.

**Comment by lesleslie** [comment]
sqlalchemy does support multiple binds and allows for multiple database
connections.  I can't give you a time frame but I need to see how flask
implements this anyway and I'll get back to you, unless of course someone
is able to get to it before.

I'm pretty sure using multiple mongodbs  wouldn't be that hard to implement
either.

-- les

**Comment by gunthercox** [comment]
I'm wondering about the pros and cons of supporting this. If a particular database architecture (MongoDB, Sqlite, etc.) allows this than I'm all for it.

One possible issue I can foresee is the challenge of merging the results from multiple non-homogeneous database. For example, someone wants to use a Postgres database and a MongoDB database together for their data.

**Comment by lesleslie** [comment]
Yeah, i think this would have to be implemented using multiple mongos OR
multiple sql's.  I know the ability exists in sqlalchemy to mix and a match
your sqldb's, but I just can't see trying to use a sql and a mongo.

-- les

**Comment by Issen007** [comment]
@lesleslie in our case we will probably mix between Centralize Postgress and local SQLite

**Comment by gunthercox** [comment]
I'm going to close this ticket off.

For any developers looking for information on this in the future, my recommendation at the present time is to seek solutions that will store your chat bot's conversational data in the same database. If a single database is insufficient on a hardware level, then there are architectures that can be used which implement multi-machine database storage. For grouping and/or categorizing statements in these setups I recommend adding fields to the existing data models or creating a "grouping" table with one-to-many references to the statements within each group.
