### ISSUE TITLE
Removing support for redundant database connection parameters

### ISSUE THREAD

**Issue by gunthercox** [gunthercox/ChatterBot#939]
Right now, the MongoDB storage adapter and the SQL storage adapter each support both of the following parameters.

- `database`: A simple string such as "chat-bot-database" that then gets turned into a database connection string by the storage adapter.
- `database_uri` A database connection string.

I think it might simplify things if one of these parameters was removed. Considering they both almost do the same thing I don't think there would be too much of an issue if `database` was removed completely as a possible parameter for these two adapters.

***

> "Explicit is better than implicit."
> ~ [The Zen of Python](https://www.python.org/dev/peps/pep-0020/)

**Comment by dapp1990** [comment]
I'm working on this issue. Can I take it?

**Comment by gunthercox** [comment]
Yes, please do. Thank you :smile:
