### ISSUE TITLE
Include information for default selections in documentation

### ISSUE THREAD

**Issue by Arvhus** [gunthercox/ChatterBot#940]
As the title suggests the default choice for Logic Adapter and comparison functions should be called out in the documentation. If this is present then I apologize, I didn't see it and thought people might like to know.

**Comment by gunthercox** [comment]
There currently some brief documentation on this page: http://chatterbot.readthedocs.io/en/latest/chatterbot.html#adapter-defaults

I agree that many of the defaults are lacking. I'll see what I can do about updating these 👍

**Comment by Arvhus** [comment]
Thanks a lot @gunthercox I'm playing around with chatterbot and really like it. Others will definitely also do so if they understand easier
