### ISSUE TITLE
Training with corpus

### ISSUE THREAD

**Issue by 7633** [gunthercox/ChatterBot#944]
I have two questions according to corpus data:

1. How are the specified categories in *.yaml files using in training?
In the source code I found out only parsing separately categories and conversations inside.

```
            corpora.categories = corpus.get('categories', [])
            conversations = corpus.get('conversations', [])

            corpora.extend([conversations])
```

2. How should I write corpus in yaml, if parser doesn't pay attention at `--` and `-` statements?
exmaple from `conversations.yaml`:
```
- - Good morning, how are you?
  - I am doing well, how about you?
  - I'm also good.
  - That's good to hear.
  - Yes it is.
- - Hello
```

example from `ai.yaml`:
```
- - What is ai
  - Artificial Intelligence is the branch of engineering and science devoted to constructing
    machines that think.
- - What language are you written in
  - python
- - You sound like data
  - Yes I am inspired by commander data's artificial personality.
```
I want to write several responses in one statement. e.g.:
```
- - Hello
  - hi
  - good morning
  - hello
  - hey
  - what's up
- - How are you
  - I'm fine
  - good
  - I'm fine, and what about you?
  - I'm sad
```

**Comment by vkosuri** [comment]
@7633 Yes, it should work, I would recommand to you write serveral response before you check YAML lint http://www.yamllint.com/

The below example save it into .yaml and train your bot it should work.

``` YAML
--- 
- 
  - Hello
  - hi
  - "good morning"
  - hello
  - hey
  - "what's up"
- 
  - "How are you"
  - "I'm fine"
  - good
  - "I'm fine, and what about you?"
  - "I'm sad"
```

**Comment by 7633** [comment]
@vkosuri yep, but how Chatterbot use this information about category?

**Comment by vkosuri** [comment]
short and detail described here https://github.com/gunthercox/ChatterBot/issues/925
