### ISSUE TITLE
how to get conversations from django_app

### ISSUE THREAD

**Issue by neutralboy** [gunthercox/ChatterBot#946]
Every time I perform a request to the server, it returns a **[19/Aug/2017 22:21:30] "GET /chatterbot/ HTTP/1.1" 405 110**. 
I changed nothing from the *example_app* for integration of Django and Chatterbot, I have just copied all of it.
Later when I examined the console I found this `Loading failed for the <script> with source “resource://devtools/client/shared/vendor/react-dev.js”`. I have no idea what it means, please help me regarding this. Thanks in advance! 
![screenshot from 2017-08-19 22-31-56](https://user-images.githubusercontent.com/21339738/29488713-43be7938-852e-11e7-8a41-99a32ce4db45.png)

**Comment by gunthercox** [comment]
Hi @neutralboy, I don't believe the error you are seeing is related to ChatterBot. It looks like it might be an error generated in one of your browser extensions.

**Comment by vkosuri** [comment]
@neutralboy if you want get conversations from chatterbot you have do post operation. 

https://github.com/gunthercox/ChatterBot/blob/324c312e036ef63fa80885f93ed2ff808919592f/examples/django_app/example_app/templates/app.html#L82

the error message came from here 

https://github.com/gunthercox/ChatterBot/blob/324c312e036ef63fa80885f93ed2ff808919592f/chatterbot/ext/django_chatterbot/views.py#L103

**Comment by neutralboy** [comment]
@gunthercox : **The error isnt related to the browser extensions.** I disabled all the browser extensions and then tried it again, it didnt work.
@vkosuri : I tried the views.py and html template you had in your github page and even that gave me the **same error.**

**Comment by Issen007** [comment]
Can you send over a code snip view to us so it is easier for us to understand what you are try to do?

**Comment by gunthercox** [comment]
@neutralboy I'm going to close this ticket off due to inactivity. Feel free to reopen it if you are still encountering an issue.
