### ISSUE TITLE
Trying to implement Jaccard similarity comparison

### ISSUE THREAD

**Issue by theman00011** [gunthercox/ChatterBot#949]
```
from chatterbot import ChatBot
from chatterbot.comparisons import JaccardSimilarity

chatbot = ChatBot(
    'Test bot',
    statement_comparison_function=JaccardSimilarity
)
```

I'm trying to implement the Jaccard similarity comparison, but even just using a basic setup with or without any logic adapters renders the error TypeError: get_initialization_functions() missing 1 required positional argument": 'self'

I can provide the entire exception thrown if necessary

**Comment by vkosuri** [comment]
You could write something like this

``` Python
chatbot = ChatBot(
    "My ChatterBot",
    logic_adapters=[
        {
            "import_path": "chatterbot.logic.BestMatch",
            "statement_comparison_function": "chatterbot.comparisons.jaccard_similarity",
            "response_selection_method": "chatterbot.response_selection.get_first_response"
        }
    ]
)
```

or

``` Python
from chatterbot import ChatBot
from chatterbot.comparisons import jaccard_similarity

chatbot = ChatBot(
    'Test bot',
    statement_comparison_function=jaccard_similarity
)
```

The comparison class are converted to calable names at line number [325](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/comparisons.py)

More information about comparison functions http://chatterbot.readthedocs.io/en/stable/conversations.html#statement-comparison

**Comment by theman00011** [comment]
Ah, okay. Everything appears to be functioning as normal now after using the correct class. Thank you
