### ISSUE TITLE
when i use it in Chinese，it don't work in python2

### ISSUE THREAD

**Issue by zhouzebiao** [gunthercox/ChatterBot#951]
**when i use it in Chinese，it don't work in python2：**

`      chatbot.set_trainer(ChatterBotCorpusTrainer)
 
     chatbot.train(

      "chatterbot.corpus.chinese"

      )`

**when i run the code, the error is:**

conversations.yml Training: [####################] 100%
greetings.yml Training: [####################] 100%
trivia.yml Training: [####################] 100%
>你好
Traceback (most recent call last):
  File "chat.py", line 40, in <module>
    print(chatbot.get_response(input(">")))
  File "<string>", line 1
    你好

SyntaxError: invalid syntax

i use the latest chatterbot 's version

**Comment by vkosuri** [comment]
@zhouzebiao Could you please provide fallowing details to resolve issue very quickly

1. version of chatterbot, to know chatterbot version ``python -m catterbot chatterbot.__version__``
2. corpus data examples
3. example code snippet that produced erros

Read this documentation to fix python encoding issues http://chatterbot.readthedocs.io/en/stable/encoding.html#how-do-i-fix-python-encoding-errors

**Comment by nggary** [comment]
This Chinese article may solve your problem, http://blog.just4fun.site/create-a-smart-chat-bot.html, please read the section of "坑", it mention the encoding problem may have in python2

**Comment by monster713** [comment]
I set storage_adapter="chatterbot.storage.MongoDatabaseAdapter", then it works.

**Comment by gunthercox** [comment]
I'm closing this off because I _believe_ this was answered? @zhouzebiao feel free to reopen this if you have any further questions on this issue.
