### ISSUE TITLE
How to create ChatterBot on Facebook Messenger

### ISSUE THREAD

**Issue by milanmaximo** [gunthercox/ChatterBot#953]
Hello, 
does anyone have experience with ChatterBot on Facebook messenger?
I would like to try to make create answers with emoticons. 
Thanks a lot

**Comment by vkosuri** [comment]
similar issue https://github.com/gunthercox/ChatterBot/issues/917

**Comment by hochochoc** [comment]
emoticons issue #911

**Comment by milanmaximo** [comment]
Thank you @vkosuri  and @hochochoc 
It seems that there is no pure python Facebook messenger, except this one with Flask

**Comment by vkosuri** [comment]
and Django http://chatterbot.readthedocs.io/en/stable/django/index.html

**Comment by milanmaximo** [comment]
maybe could help this video https://www.youtube.com/watch?v=6DQ6v1hcNyk&t=185s 

from this source https://github.com/twtrubiks/facebook-messenger-bot-tutorial
