### ISSUE TITLE
ListTrainer with chatbot

### ISSUE THREAD

**Issue by hochochoc** [gunthercox/ChatterBot#954]

**Comment by vkosuri** [comment]
@hochochoc could you please provide more information about this issue?

**Comment by hochochoc** [comment]
Sorry, 
I train my bot with ListTrainer. However, when I change something in Response B to Statement A in train list, I will receive the old response, not the new I have changed. I understand how ListTrainer works and how chatbot select response. But can you guess me how to get the new response, not the old one? May I have to make a new chatbot - select response or something like that? 
Thank you very much.

**Comment by vkosuri** [comment]
Currently training process is static, if you made any changes in your train data, you have to retrain your bot or create new one.

I don't understand why you are trying to change existing statements? Is there any use case behind?

Some of the reference, that might useful to you

https://github.com/gunthercox/ChatterBot/pull/103
https://github.com/gunthercox/ChatterBot/issues/94#issuecomment-167920604

**Comment by hochochoc** [comment]
I don't know why it keep processing the old response when I try to create new bot with new ListTrainer.

**Comment by milanmaximo** [comment]
Same is here, and I have a problem to delete letters with another iso code, let's say I have letter with Č,Ć,Đ.. I cant delete them from admin

**Comment by vkosuri** [comment]
@milanmaximo In your case you could write your own pre-processors to convert your text into desired format, if these chars are unicode apply [convert_to_ascii](http://chatterbot.readthedocs.io/en/stable/preprocessors.html#chatterbot.preprocessors.convert_to_ascii).

If not write your own pre-processor, here some documentation how to write [own processor]( http://chatterbot.readthedocs.io/en/stable/preprocessors.html#creating-new-preprocessors)
