### ISSUE TITLE
How to let Chatbot execute Django query and OS command?

### ISSUE THREAD

**Issue by elcolie** [gunthercox/ChatterBot#955]
I am working with Django and Infra.
I have read all the given example in the repo. But it does focus on training, dataset, feedback, ... etc

How to let `Chatbot` execute `Django query` and `OS commands`?

**Comment by vkosuri** [comment]
@elcolie I didn't understand you question? could you provide with some examples?

Do want access dbshell of chatterbot,

``` Bash
cd examples/django_app
python manage.py dbshell
SQLite version 3.8.4.1 2014-03-11 15:27:36
Enter ".help" for usage hints.
sqlite> .tables
auth_group                               
auth_group_permissions                   
auth_permission                          
auth_user                                
auth_user_groups                         
auth_user_user_permissions               
django_admin_log                         
django_chatterbot_conversation           
django_chatterbot_conversation_statements
django_chatterbot_response               
django_chatterbot_statement              
django_content_type                      
django_migrations                        
django_session                           
sqlite> select * from django_chatterbot_statement;
```

Or Are you trying to access [custom management commands](https://docs.djangoproject.com/en/dev/howto/custom-management-commands/), then the [train](http://chatterbot.readthedocs.io/en/stable/django/training.html#management-command) command and source [code](https://github.com/gunthercox/ChatterBot/tree/master/chatterbot/ext/django_chatterbot/management/commands)

**Comment by elcolie** [comment]
I am considering the very simple plain task like.

```
"How many orders are the this month?"
```

Then I expect `Chatbot` be able to execute my given `custom management commands`.
Or

```
"How long does server up without reboot?"
```

Then I expect `Chatbot` be able to execute `uptime` directly to OS level.

This technique is similar to `customer management commands`.
But I branches a question since I do not known the technical implementation behind the scenes.
However, in opinion. I think first solution can be able to reuse with 2nd one. 
https://stackoverflow.com/questions/89228/calling-an-external-command-in-python

Your answer is about how to config `Chatbot` and let it shares `Django` database.

**Comment by gunthercox** [comment]
@elcolie To achieve this you are likely going to need to write your own logic adapter for your chat bot. Let me know if I can provide any guidance on how to do this. There is information in the documentation as well.

**Comment by elcolie** [comment]
@gunthercox  Thank you very much for keyword `logic adapter`. Let me study it for a while and I will come back to you.

**Comment by kibanatry** [comment]
@elcolie Were you able to get this done.
