### ISSUE TITLE
Chatterbot handles multiple logic adapters

### ISSUE THREAD

**Issue by s0rata** [gunthercox/ChatterBot#961]
Hello,
I am interested in this engine and I want to build a chat bot with multiple logic adapters. Let's say, one logic adapter for asking questions related to weather, another logic adapter for booking events in calendar, and more logic adapters. In this case, I want to have one adapter to handle the input_statement and this adapter will match input_statement with logic adapter.

My question is that is it possible to build chatbot to handle different purpose like this?
If it possible, how can I implement multiple logic adapters like I described above.

Thanks,

**Comment by 7633** [comment]
Hello @s0rata, you could implement your willings with ChatterBot. 
First of all, multiplelogic adapter have already implemented in ChatterBot, when you create it, and it handle all of [standart logic adapters](http://chatterbot.readthedocs.io/en/stable/logic/index.html).
How MultipleLogicAdapter works? - [answer](http://chatterbot.readthedocs.io/en/stable/logic/multi-logic-adapter.html)

Seperate statement processing may be implemented by using method can_process in LogicAdapter class. If input_statement satisfy to handle by your adapter (e.g. weather), you may set confidence = 1, process it and MultipleLogicAdapter choose response from this adapter.

> If it possible, how can I implement multiple logic adapters like I described above.

You don't need to implement multiple logic adapter again, or reimplement it, you just need implement your LogicAdapter and method can_proces, as I described above

**Comment by skanda09** [comment]
Hi 7633,
Can you provide an example where we use one sql database to respond and a second response from another sql database using this MultipleLogicAdapter

**Comment by 7633** [comment]
@skanda09 
In the case, that I described above, we use one database for all logic adapters. You can't use several databases in one ChatterBot to process different logic adapters. There is no such functionality.

If you think, that each logic adapter should keep statements in different databases, I recommend you review your project architecture.

**Comment by skanda09** [comment]
You see there are some things that are already maintained in one database and used for other purposes.

One is getting created for the conversation. For example let us say that the second database is used to get data from the net and store it there.

So I need to answer the question from one database and give the results of searches already made from the other.

**Comment by skanda09** [comment]
Can you at least give an example for multiple outputs for a single statement

E.g.,

User Hi
Bot Hello! How are you doing?
Bot Good Afternoon
Bot How can I help you today?

Where do I have make the changes?

**Comment by 7633** [comment]
@skanda09 

> Can you at least give an example for multiple outputs for a single statement

See documentation for MultipleLogicAdapter: [link](http://chatterbot.readthedocs.io/en/stable/logic/multi-logic-adapter.html#selecting-a-response-from-multiple-logic-adapters):

> The MultiLogicAdapter is used to select a single response from the responses returned by all of the logic adapters that the chat bot has been configured to use. Each response returned by the logic adapters includes a confidence score that indicates the likeliness that the returned statement is a valid response to the input.

Therefore, I can't get such example.

If I'm not mistaken, first database only with questions, another one is answers. For use Chatterbot, you should preprocess this databases into one training format, for example into '*.yml' files contain question and answers line by line. This data you may use to train ChatterBot and then, use to search correct answers in database using LogicAdapters. I haven't see other ways.

**Comment by skanda09** [comment]
7633 
No One is with questions and Answers. Another is a search of all hotels and taxis in the area

**Comment by vkosuri** [comment]
@s0rata Are you looking something like this https://github.com/gunthercox/ChatterBot/issues/357

**Comment by s0rata** [comment]
@7533 thank you. So from what you said, the Multi Adapter class will handle this for me. What I need to do is to classify the input_statement to match with adapter. I think I have an idea for now. Thank again.

**Comment by s0rata** [comment]
@vkosuri #357 is similar. But that somehow give me another idea of what I want to do. Thank for pointing that out.

**Comment by s0rata** [comment]
@7633 @vkosuri Is there any text classifier library for python you can recommend? Because I intend to use it to categorize the input_statement. Sorry, I am new to this. Thank again.

**Comment by 7633** [comment]
I recommend you to look textblob, nltk [link with more info](https://elitedatascience.com/python-nlp-libraries)

**Comment by s0rata** [comment]
@7633 Thank you for your recommendation.

**Comment by vkosuri** [comment]
@s0rata Please feel free ask any question if you need information. Some of the resources that might help you.

1. https://stackoverflow.com/questions/30821188/python-nltk-pos-tag-not-returning-the-correct-part-of-speech-tag
2. Facts and figures https://spacy.io/docs/api/

**Comment by s0rata** [comment]
@vkosuri Thank you.
