### ISSUE TITLE
What is the type of Network that is used to do the Machine learning in ChatterBot

### ISSUE THREAD

**Issue by skanda09** [gunthercox/ChatterBot#963]
What is the type of Network that is used to do the Machine learning in ChatterBot

Can you tell me what is the network? If it is not there then how can I do it.

**Comment by vkosuri** [comment]
@skanda09 

> What is the type of Network that is used to do the Machine learning in ChatterBot

I don't understand you question, could you elaborate your question with more information? 

If you are look for What kinds of machine learning does ChatterBot use?

See this [documentation ](https://github.com/gunthercox/ChatterBot/blob/aeb6a37c3a73e938d00c9dc710fd5929ece1bf05/docs/faq.rst#what-kinds-of-machine-learning-does-chatterbot-use)

**Comment by skanda09** [comment]
I mean which is the Neural Network Used?

**Comment by vkosuri** [comment]
> Can you tell me what is the neural network used?

Not implemented, Chatterbot purely implemented using search algorithms techniques and [naive Bayesian classification
](https://en.wikipedia.org/wiki/Naive_Bayes_classifier)

> If it is not there then how can I do it.
I think you could start this one https://github.com/gunthercox/ChatterBot/issues/289

**Comment by skanda09** [comment]
Can I know how the saving and retrieval from database is happening? In which program would I find this info so that I can plan my json file on specific format

**Comment by vkosuri** [comment]
You will find line number 115 https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/chatterbot.py

**Comment by skanda09** [comment]
Saving is fine retrival where is it done?

**Comment by skanda09** [comment]
How the the processing is happening can you tell me?

**Comment by vkosuri** [comment]
Here is the process flow diagram http://chatterbot.readthedocs.io/en/stable/#process-flow-diagram

Some useful information you will find here https://github.com/gunthercox/ChatterBot/issues/832#issuecomment-314052937
