### ISSUE TITLE
How to access data from two databases of the same type

### ISSUE THREAD

**Issue by skanda09** [gunthercox/ChatterBot#964]
You see there are some things that are already maintained in one database and used for other purposes.

One is getting created for the conversation. For example let us say that the second database is used to get data from the net and store it there.

So I need to answer the question from one database(The Conversation) and give the results of searches already there in the other database.

**Comment by vkosuri** [comment]
@skanda09 I think this thread will provide some information to you https://github.com/gunthercox/ChatterBot/issues/931,
