### ISSUE TITLE
connect to mongodb on aws ec2 ubuntu

### ISSUE THREAD

**Issue by bainadeashish** [gunthercox/ChatterBot#965]
Hi Team,

I have mongo db running on mongodb on aws ec2 ubuntu.
Below is code :
``` Python
bot = ChatBot(
    'IVLI',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    database='chatterbot-database',
    database_uri='mongodb://ec2-52-66-113-108.ap-south-1.compute.amazonaws.com:27017',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            "response_selection_method": "chatterbot.response_selection.get_random_response"
        
        
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.60,
            'default_response': 'I am sorry, but I do not understand.'
        },

    ],
    preprocessors=['chatterbot.preprocessors.clean_whitespace','chatterbot.preprocessors.unescape_html','chatterbot.preprocessors.convert_to_ascii'],
    silence_performance_warning=True,
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
    filters=["chatterbot.filters.RepetitiveResponseFilter"]
)
```

But i am getting below error:

``` Bash
  File "C:\Python27\lib\site-packages\pymongo\helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on chatterbot-database to execute command { createIndexes: "statements", indexes: [ { unique: true, name: "text_1", key: { text: 1 } } ], writeConcern: {} }
```

Any help would be appriciated,I spent almost a day on it & not able to figure out cause.

**Comment by vkosuri** [comment]
@bainadeashish From the error console log, this issue was with Mongo DB driver issue, not an chatterbot issue.

I hunch could be the **firewall issue,** Recently i registered with Mongo DB course, One learning was


> In order to continue in this course, you must be able to make outgoing requests from your computer to database servers we have set up in MongoDB Atlas. Those servers run on port 27017 in Amazon AWS.
> 
> Please confirm that port 27017 is not blocked by clicking http://portquiz.net:27017.
> 
> If successful, you will see a page load that indicates you can make outgoing requests on port 27017.
> 
> If a page does not load and your request eventually times out, outgoing traffic to port 27017 is probably blocked on your local network. If this is the case, please contact your IT department to see if there is a workaround or try to make the request from another location.

Apart from this information I am googled your issues, some of the solution i found are 

1. https://community.bitnami.com/t/pymongo-errors-operationfailure-not-authorized-on-mydb-to-execute/44164/2
2. https://stackoverflow.com/a/41871203/358458

Let me know if you need any further help from us

**Comment by bainadeashish** [comment]
@vkosuri If i use mongodb without authentication then there is know issue.
But when i use authentication i am getting above error.
Wha t is code to pass username & pwd to mongodb instanace?Because while creating chatterbot instanace we are just passing url without authentication info.Please see below 
database_uri='mongodb://ec2-52-66-113-108.ap-south-1.compute.amazonaws.com:27017'
Let me know how to pass username & password at this point.

**Comment by vkosuri** [comment]
Here is the [standard connection string format](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format) Mongo db suggested

``` 
mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
```

In your case, it could be like this

``` 
database_uri='mongodb://username:password@ec2-52-66-113-108.ap-south-1.compute.amazonaws.com:27017
```

**Comment by bainadeashish** [comment]
thanks this is thing i needed:)
big thank you:)
