### ISSUE TITLE
mongoDB method deprecated

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [gunthercox/ChatterBot#97]
According for the documentation for `pymongo.collection.Collection`, the `update` method is deprecated in favor of `update_one` or `update_many`

**Comment by LucasZielke** [comment]
Would it be smart to just have it default to the `update_many` wont that
allow you to just pass one?

**Comment by The-Penultimate-Defenestrator** [comment]
Not sure, I think `update_many` finds multiple matches for one statement, in case a statement occurs more than once, where as `update_one` behaves like `str.find()` in python.
