### ISSUE TITLE
How to fire django_chatterbot from an existing .Net Web application.

### ISSUE THREAD

**Issue by vedantnarayan** [gunthercox/ChatterBot#971]
Hello All,

This is not an issue. Just a question. 

I have build a chatbot using django using chatterbot. I want it to integrate in an existing .Net web application. I want to call this application from an existing .Net application. Please guide me if anyone has any information regarding this.

**Comment by gunthercox** [comment]
Hi @vedantnarayan,

I have never tried this, but one possibility _might_ be Iron Python (http://ironpython.net/). I've never tried it but it might be worth experimenting with.
