### ISSUE TITLE
Enable Read Only mode of ChatBot

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/ChatterBot#975]
From which file and which line of the file can we enable read only mode of chatterbot ?

Please Help !

**Comment by gunthercox** [comment]
Hi @ayushecps, when you instantiate a new instance of the chat bot class in a new file that you have created, you will need to set the `read_only` parameter to `True`. Here is a quick example:

```python
# my_chat_bot.py
chatbot = ChatBot(
    "My Chat Bot",
    read_only=True
)
```

Feel free to check out more examples in the documentation.
http://chatterbot.readthedocs.io/en/latest/quickstart.html#read-only-mode
