### ISSUE TITLE
Saving the bot instance

### ISSUE THREAD

**Issue by nikhilv-quantela** [gunthercox/ChatterBot#979]
I have created an example bot using the code below. My question is, is it possible to access this trained bot instance **my_bot** with name **TestMe** later directly when needed.

``` Python
from chatterbot import ChatBot

from chatterbot.trainers import ChatterBotCorpusTrainer

my_bot = ChatBot(
    'TestMe',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    logic_adapters=[
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter',
        'chatterbot.logic.BestMatch'
    ],
    database='./database.sqlite3'
)

my_bot.set_trainer(ChatterBotCorpusTrainer)

my_bot.train("chatterbot.corpus.english")
```

**Comment by vkosuri** [comment]
@nikhilv-quantela Each object is copied into ``self``. 

https://github.com/gunthercox/ChatterBot/blob/b611cbd0629eb2aed9f840b50d1b3f8869c2589e/chatterbot/chatterbot.py#L17

if want do any operations later time you could do like this
```
if(my_bot.name == "TestMe"):
    # do operations
```

**Comment by nikhilv-quantela** [comment]
@vkosuri  Ok

So, we don't need to train it again right?

**Comment by vkosuri** [comment]
> So, we don't need to train it again right?

I think your question is, to get bot name do i need train it again?
No

**Comment by nikhilv-quantela** [comment]
@vkosuri thanks for clarification

**Comment by gunthercox** [comment]
@nikhilv-quantela You are correct, each bot only needs to be trained once.
