### ISSUE TITLE
low confidence adapter in django chatbot

### ISSUE THREAD

**Issue by saraalosaid** [gunthercox/ChatterBot#982]
how to use low confidence adapter in django chatbot ,the given example in documentation show the use in terminal chatbot, i try the code in django setting but it doesnt work ,please help...

**Comment by ayushecps** [comment]
'logic_adapters':  [
        'chatterbot.logic.LowConfidenceAdapter'
    ],

**Comment by saraalosaid** [comment]
and how i can specify threshold and make default response

**Comment by vkosuri** [comment]
I think this example will help you

``` Python
CHATTERBOT = {
    'name': 'ADTRAN Chatter Bot',
    'logic_adapters': [
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'statement_comparison_function': 'chatterbot.comparisons.jaccard_similarity',
            'response_selection_method': 'chatterbot.response_selection.get_first_response'
        },
        {
            'import_path': 'chatterbot.logic.SpecificResponseAdapter',
            'input_text': 'Help me!',
            'output_text': 'Ok, here is a link: http://portal.adtran.com/web/page/portal/Adtran/wp_sales_contact'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': 'I am sorry, but I do not understand.'
        }
    ],
    'filters': [
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
    'django_app_name': 'abot',
    'use_django_models': True
}
```

**Comment by GowthamSB** [comment]
@vkosuri the above code doesnot work properly. if i include the logic adapters it gives random errors even for trained questions in chat corpus.

**Comment by vkosuri** [comment]
what type error you were facing?

**Comment by GowthamSB** [comment]
I am geting  the query as the response. is there any other way to set default response in django chatterbot

**Comment by GowthamSB** [comment]
@vkosuri It is giving random response from the corpus for unknown queries. How to fix that?Help

**Comment by vkosuri** [comment]
Try to use low confidence adapter http://chatterbot.readthedocs.io/en/stable/logic/index.html#low-confidence-response-adapter

And also enable logging that will show how response working etc.

**Comment by mravunni** [comment]
@vkosuri im getting

{"conversation": [], "detail": "You should make a POST request to this endpoint.", "name": "ChatterBot"},

my logic details :
CHATTERBOT = {
     'logic_adapters' : [
  {
    'import_path': "chatterbot.logic.BestMatch"
  },
  {
    'import_path': 'chatterbot.logic.LowConfidenceAdapter',
    'threshold': 0.5,
    'default_response': 'You can ask other question'
  }

How to fix this ???

**Comment by mravunni** [comment]
@gunthercox latest chatterbot version seems to have some issue with lowconfidence adapter,

im getting below error while implementing in django

{"conversation": [], "detail": "You should make a POST request to this endpoint.", "name": "ChatterBot"},

my logic details :
CHATTERBOT = {
'logic_adapters' : [
{
'import_path': "chatterbot.logic.BestMatch"
},
{
'import_path': 'chatterbot.logic.LowConfidenceAdapter',
'threshold': 0.5,
'default_response': 'You can ask other question'
}

**Comment by mravunni** [comment]
yes the confidence is less than .5, but im expecting a default response 'default_response': 'You can ask other question' not an error message

**Comment by vkosuri** [comment]
I have created a separate issue https://github.com/gunthercox/ChatterBot/issues/1257

**Comment by mravunni** [comment]
Thanks

**Comment by GowthamSB** [comment]
@vkosuri  even this is not working im not getting the default response...and im not getting any response for unknown queries...

**Comment by GowthamSB** [comment]
how to enable logging

**Comment by vkosuri** [comment]
http://chatterbot.readthedocs.io/en/stable/chatterbot.html?highlight=logging#enable-logging

**Comment by GowthamSB** [comment]
@vkosuri in which file django app we have to include that logging code?

**Comment by GowthamSB** [comment]
@vkosuri sir i couldnt use any logic adapters in my django applications . even time and mathematical adapters wont work. Is just adding the import_path in the django settinngs is enough or we have to do anything?

**Comment by vkosuri** [comment]
If you haven't configured then the default adapter will be used your bot

Here a typicl settings example http://chatterbot.readthedocs.io/en/stable/django/settings.html#chatterbot-django-settings

Chatterbot uses Django storage adapter http://chatterbot.readthedocs.io/en/stable/django/index.html#mongodb-and-django

I am not sure what you are trying to logging on to console, this information might help you https://stackoverflow.com/a/1598979
