### ISSUE TITLE
Is it possible to switch between different database.?

### ISSUE THREAD

**Issue by Cosmos19** [gunthercox/ChatterBot#983]
Hi,

I would like to switch between different database based on some user choice. The idea is to maintain uniqueness and also to avoid collision between questions. 
storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
database="chatterrbot-XX-database"
database="chatterrbot-YY-database"

now i want to switch between XX to YY database based on some user input. 

Thanks in advance.!

**Comment by vkosuri** [comment]
Yes, you can, By changing the database_uri runtime

https://github.com/gunthercox/ChatterBot/blob/b611cbd0629eb2aed9f840b50d1b3f8869c2589e/chatterbot/storage/mongodb.py#L89

Not sure consequences and effects, and also you have to train tow databases in order to responses. A sample snippet

``` Python
from chatterbot import ChatBot
import requests

# Uncomment the following lines to enable verbose logging
import logging
logging.basicConfig(level=logging.INFO)

# Create a new instance of a ChatBot
chatbot = ChatBot(
    'SQL Example',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)

chatbot.train(
    "chatterbot.questionandanswers"
)
response = chatbot.get_response("how about status xx db?')
if "status xx db" in respnose.text:
    chatterbot.storage.database_uri="mongodb://localhost:27017/"

```
