### ISSUE TITLE
Weather API Implementation

### ISSUE THREAD

**Issue by ayushecps** [gunthercox/ChatterBot#985]
How can we implement weather API and what changes to be made in code to implement the same.

**Comment by vkosuri** [comment]
See this example https://github.com/gunthercox/chatterbot-weather#example

Adding more information https://github.com/gunthercox/ChatterBot/issues/820#issuecomment-312717335

Let me know if you need any help

**Comment by ayushecps** [comment]
stil I am facing the issue. I am even not able to follow the steps as I am a beginner. Could you please help me at more basic level.

**Comment by vkosuri** [comment]
I don't what steps you are trying to do. You could do weather example with 3 simple steps.

1. ``pip install --upgrade chatterbot``, Recommanded installation using [virtual environments](http://docs.python-guide.org/en/latest/dev/virtualenvs/)
2. create a new file using any text editor for e.g. weather.py, paste below code into that
```
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
import requests

# Create a new instance of a ChatBot
bot = ChatBot(
    'Action or Intent Response Example Bot',
    trainer='chatterbot.trainers.ListTrainer'
)

# Train the chat bot with a few responses
bot.train([
    'Current weather in Hyderabad',
    'http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1',
    'Have you read the documentation?',
    'No, I have not',
    'This should help get you started: http://chatterbot.rtfd.org/en/latest/quickstart.html'
])

# Get a response from bot
response = bot.get_response('weather in London?')
# Handle JSON data, get all required data and print them
print(requests.get(response).text)
```
3. Run your code, python weather.py, it will print current weather in Hyderabad

This example demonstrated using openweathermap.org, read more info http://openweathermap.org/current

openweather map API located here http://openweathermap.org/api

Let me know if you need any help
