### ISSUE TITLE
Can I train a robot with two scenes alone?

### ISSUE THREAD

**Issue by spongejj** [gunthercox/ChatterBot#986]
In detail, what i want is a robot answers questions in two or more scenes, firstly, i have trained a chatbot in mixed scenes-corpus using chatterbot, but it played not very well, and i tried to use chtterbot to build two chatbots trained on different corpus, they can really answer different scenes questions.
But, can i train only one chatbot, split trainers or training corpus to let my chatbot  answer different scenes questions?

**Comment by gunthercox** [comment]
@spongejj Yes, you can train a chat bot using multiple trainers. To do this you will have to consecutively change the training setting for each of the different ones you want to use.
