### ISSUE TITLE
export_example.py empty output file

### ISSUE THREAD

**Issue by evgenibers** [gunthercox/ChatterBot#990]
After running example "export_example.py" I got "my_export.json" in the same directory but it was empty. What could be wrong?

**Comment by vkosuri** [comment]
@evgenibers which version of chatterbot are you using? To know chatterbot version try ``python -m chatterbot --version``

I tried on my machine it is working fine.

``` Bash
(env)vkosuri@vkosuri:~/ChatterBot$ python -m chatterbot --version
0.7.6

(env)developer@cn-vm-vkosuri:~/ChatterBot$ python export_example.py 
ai.yml Training: [####################] 100%
botprofile.yml Training: [####################] 100%
computers.yml Training: [####################] 100%
conversations.yml Training: [####################] 100%
drugs.yml Training: [####################] 100%
emotion.yml Training: [####################] 100%
food.yml Training: [####################] 100%
gossip.yml Training: [####################] 100%
greetings.yml Training: [####################] 100%
history.yml Training: [####################] 100%
humor.yml Training: [####################] 100%
literature.yml Training: [####################] 100%
money.yml Training: [####################] 100%
movies.yml Training: [####################] 100%
politics.yml Training: [####################] 100%
psychology.yml Training: [####################] 100%
science.yml Training: [####################] 100%
sports.yml Training: [####################] 100%
trivia.yml Training: [####################] 100%

(env)vkosuri@vkosuri:~/ChatterBot$ ls -lhrt my_export.json 
-rw-rw-r-- 1 developer developer 48K Sep 21 15:24 my_export.json
```

**Comment by evgenibers** [comment]
I am using 0.7.6 version.

**Comment by rHuggler** [comment]
I also ran into this issue using Chatterbot installed with pip.
Apparently changing `json.dumps()` to `json.dump()` on _chatterbot.trainers_ fix this.

**Comment by ealmonte** [comment]
I, likewise, ran into this issue.
The change from json.dumps() to json.dump() solved the empty file problem. 

However, I got the UnicodeEncodeError: 'ascii' codec can't encode character u'\xbf' in position 2: ordinal not in range(128)... when I used Spanish 

I solved this by adding decode() in the _generate_export_data() function of chatterbot.trainers, as follows:
result.append([response.text.decode("utf-8"), statement.text.decode("utf-8")])

**Comment by gunthercox** [comment]
I'm going to close this ticket off as this issue appears to have been fixed.
