### ISSUE TITLE
Run ChatterBot code on windows 7 PC

### ISSUE THREAD

**Issue by rupinderkr186** [gunthercox/ChatterBot#991]
Hi,
I am new to python have just run the helloWorld example can you please provide me steps how can I use the code of chatterBot and run it on my windows 7 PC so as to see the demo of chatterBot and can analyze its feature. Actually I want to build my own custom bot which can respond to the user and can share the requested file by the user. I did some research and came forward with the chatterBot so I thought of trying it out but I don't have any idea how to run the code so as to see the demo of chatterBot application. Please provide me the steps to successfully run the chatterBot code on my local system.
@gunthercox , can you please provide me steps to run the code and see the output on my local system.

Thanks

**Comment by vkosuri** [comment]
@rupinderkr186 Personally I feel Linux flavored machines are better for any chatbots applications. However chatterbot will work on windows exceptionally.

I think here are the steps that will help run a chatbot example.

1. [Install Python Win7](http://www.openbookproject.net/courses/webappdev/units/softwaredesign/resources/install_python_win7.html)
2. After that install chatterbot on to your machine by using `` pip install --upgrade chatterbot ``. If run into pip problems, see this [thread](https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation), Go through the post it may solve your problem.
3. After we have many [examples ](https://github.com/gunthercox/ChatterBot/tree/master/examples) try to copy these examples into your machine. This [post ](https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo) will guide how to copy/download a folder from GitHub.
4. After all above stesps you are able completed without any error then your move to example directory run any example your wish. For example ``python terminal.py``

Feel free to let us know if you need any help.

Happy chatting 👍
