### ISSUE TITLE
Session Id in Flask

### ISSUE THREAD

**Issue by SherlocKOficial** [gunthercox/ChatterBot#992]
How do I integrate an external id using sessions in the flask?

Exemple:

@app.route("/msg/<string:msg>&id=<string:id>")
def get_raw_response():
    return str(portuguese_bot.get_response(query))

if __name__ == "__main__":
    app.run()

**Comment by vkosuri** [comment]
I am not familiar with flask, I knew there is a repository which implemented on flask https://github.com/chamkank/flask-chatterbot this might help you

**Comment by SherlocKOficial** [comment]
Thanks, but I need to know how to implement the system of individual sessions using flask

.Bad english :/

**Comment by gunthercox** [comment]
A specific conversation session can be selected by passing a unique id into the `get_response` method.

For example, `get_response('My input string', conversation_id=flask_session_id)

I'm not familiar with how to get a session id in Flask, but I'm sure there are resources online that can explain how to get it.
