### ISSUE TITLE
Does Django filter work?

### ISSUE THREAD

**Issue by ellenawoo** [gunthercox/ChatterBot#995]
Hi, does the repetitive response filter work in Django? The bot still returns the same response even though it has other trained responses for the same question.

In settings.py: 
``` Python
CHATTERBOT = {
    'name': 'Bot',
    'filters': [
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
         'chatterbot.corpus.english'
    ]
}
```

**Comment by Issen007** [comment]
Is this a copy of #902 ?

**Comment by ellenawoo** [comment]
@Issen007 for example in the corpus training YML file,
- - tell me a joke
  - joke 1
  - joke 2
  - joke 3 

How do i make it such that the response isn't always the same?

**Comment by gunthercox** [comment]
@ellenawoo If the response you want to return is purely random, you could set the chat bot's `response_selection` parameter so that it uses the random response selection method.

http://chatterbot.readthedocs.io/en/stable/logic/response_selection.html#chatterbot.response_selection.get_random_response

**Comment by kokenjr** [comment]
@gunthercox I'm running into the same issue. Perhaps i'm not understanding the true intent of the RepetitiveResponseFilter. 

The following is what currently occurs with the filter enabled:
```
Request: "What can you do"
Response: "Sadness is not an emotion that i like to experience."
Request: "What can you do"
Response: "Sadness is not an emotion that i like to experience."
```

My expectation:
```
Request: "What can you do"
Response: "Sadness is not an emotion that i like to experience."
Request: "What can you do"
Response: "Some other response."
```

**Comment by gunthercox** [comment]
@ellenawoo @kokenjr I'll have to look into this further. It's possible that the filter is getting skipped.

**Comment by kokenjr** [comment]
@gunthercox I think my issue may have been related to this Issue #1040. I'll monitor the conversations and confirm this is the case.
