### ISSUE TITLE
Throwing "Error float division by zero" while using jaccard_similarity statment comparison.

### ISSUE THREAD

**Issue by Cosmos19** [gunthercox/ChatterBot#997]
Code:

                       trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
			statement_comparison_function=jaccard_similarity,
			database="chatterbot-database"

I have installed NLTK data and then i have changed to jaccard_similarity algo. 

Please help me to solve this.

Thanks in advance.

**Comment by vkosuri** [comment]
@Cosmos19 This is an expected behavior, those are only warning message, but it will not stop your bot

``` Python
# Calculate Jaccard similarity
        try:
            ratio = len(set(lemma_a).intersection(lemma_b)) / float(len(set(lemma_a).union(lemma_b)))
        except Exception as e:
            print('Error', e)
        return ratio >= self.SIMILARITY_THRESHOLD
```

Did you bot program was terminated?

**Comment by gunthercox** [comment]
I'm going to mark this as a bug. Realistically the calculation should be set up so that it doesn't raise an exception.

**Comment by Cosmos19** [comment]
@vkosuri  My Bot is not terminated but somtime it takes time to respond when this message shows.

@gunthercox  Thanks. !
