### ISSUE TITLE
How do I train specific bot from command line?

### ISSUE THREAD

**Issue by nanda248** [gunthercox/ChatterBot#999]
I'm using ChatterBotCorpusTrainer as my trainer and i have lists of YAML files in my training_data. I can train all the bots using "python manage.py train". 
But now I want to train specific bot from command line by passing the YAML file name and training_data will be chatterbot.corpus.english.[yamlFileName] and it will only train that specific bot. How can I do that? 
Can I update training_data from "python manage.py train --settings"?
Or should I pass yaml File name as argument in command line? If so, how to achieve?
Thanks in advance...

**Comment by vkosuri** [comment]
@nanda248 Yes, you could. Read this http://chatterbot.readthedocs.io/en/stable/training.html#specifying-corpus-scope documentation.

**Comment by Issen007** [comment]
@nanda248 you can also read the short documentation on following link 
[https://github.com/gunthercox/chatterbot-corpus/blob/master/readme.md#install-your-training-corpus-data-to-django](https://github.com/gunthercox/chatterbot-corpus/blob/master/readme.md#install-your-training-corpus-data-to-django)

**Comment by nanda248** [comment]
Thanks, I have solved this issue. But not in the way i wanted it. But I created a function call inside my code which can be used to train specific bot. I'm using Django Integration with chatterbot and I use REST API call to that particular function to train the specific bot.
